### PR TITLE
Disable simplify regions after scf-to-cf

### LINKED ISSUE #22887: [regression-onnx] Numeric regression for Conv ops
### What happened?

For the given IR

```mlir
    %994 = torch.operator "onnx.DequantizeLinear"(%676, %674, %675) : (!torch.vtensor<[1024,32,3,3],si8>, !torch.vtensor<[],f32>, !torch.vtensor<[],si8>) -> !torch.vtensor<[1024,32,3,3],f32>
    %995 = torch.operator "onnx.DequantizeLinear"(%679, %677, %678) : (!torch.vtensor<[1024],si8>, !torch.vtensor<[],f32>, !torch.vtensor<[],si8>) -> !torch.vtensor<[1024],f32>
    %996 = torch.operator "onnx.DequantizeLinear"(%686, %684, %685) : (!torch.vtensor<[2048,1024,1,1],si8>, !torch.vtensor<[],f32>, !torch.vtensor<[],si8>) -> !torch.vtensor<[2048,1024,1,1],f32>
    %997 = torch.operator "onnx.DequantizeLinear"(%689, %687, %688) : (!torch.vtensor<[2048],si8>, !torch.vtensor<[],f32>, !torch.vtensor<[],si8>) -> !torch.vtensor<[2048],f32>
    %1456 = torch.operator "onnx.QuantizeLinear"(%arg1, %657, %656) : (!torch.vtensor<[1,1024,14,14],f32>, !torch.vtensor<[],f32>, !torch.vtensor<[],si8>) -> !torch.vtensor<[1,1024,14,14],si8>
    %1457 = torch.operator "onnx.DequantizeLinear"(%1456, %657, %656) : (!torch.vtensor<[1,1024,14,14],si8>, !torch.vtensor<[],f32>, !torch.vtensor<[],si8>) -> !torch.vtensor<[1,1024,14,14],f32>
    %1465 = torch.operator "onnx.Conv"(%1457, %994, %995) {torch.onnx.dilations = [1 : si64, 1 : si64], torch.onnx.group = 32 : si64, torch.onnx.kernel_shape = [3 : si64, 3 : si64], torch.onnx.pads = [1 : si64, 1 : si64, 1 : si64, 1 : si64], torch.onnx.strides = [2 : si64, 2 : si64]} : (!torch.vtensor<[1,1024,14,14],f32>, !torch.vtensor<[1024,32,3,3],f32>, !torch.vtensor<[1024],f32>) -> !torch.vtensor<[1,1024,7,7],f32> 
    %1467 = torch.operator "onnx.QuantizeLinear"(%1465, %681, %680) : (!torch.vtensor<[1,1024,7,7],f32>, !torch.vtensor<[],f32>, !torch.vtensor<[],si8>) -> !torch.vtensor<[1,1024,7,7],si8>
    %1468 = torch.operator "onnx.DequantizeLinear"(%1467, %681, %680) : (!torch.vtensor<[1,1024,7,7],si8>, !torch.vtensor<[],f32>, !torch.vtensor<[],si8>) -> !torch.vtensor<[1,1024,7,7],f32>
    %1469 = torch.operator "onnx.Conv"(%1468, %996, %997) {torch.onnx.dilations = [1 : si64, 1 : si64], torch.onnx.group = 1 : si64, torch.onnx.kernel_shape = [1 : si64, 1 : si64], torch.onnx.pads = [0 : si64, 0 : si64, 0 : si64, 0 : si64], torch.onnx.strides = [1 : si64, 1 : si64]} : (!torch.vtensor<[1,1024,7,7],f32>, !torch.vtensor<[2048,1024,1,1],f32>, !torch.vtensor<[2048],f32>) -> !torch.vtensor<[1,2048,7,7],f32>
    return %1469 : !torch.vtensor<[1,2048,7,7],f32>
```
seeing numeric regression for this [change](https://github.com/iree-org/iree/commit/2e5ce7bd9a4c009895e330f410cb4f142c910712). 

If we pass `arg1` in place of `%1457` for `Conv` operator then o/p are matching. 

### Steps to reproduce your issue

command:

```
iree-compile test.mlir --iree-hal-target-backends=rocm --iree-hip-target=gfx942 -o test.vmfb
iree-run-module --module='test.vmfb' --device=hip --function='main_graph' --input='1x1024x14x14xf32=@input.1.bin
```

[expected_output.bin.txt](https://github.com/user-attachments/files/24098655/expected_output.bin.txt)
[input.1.bin.txt](https://github.com/user-attachments/files/24098656/input.1.bin.txt)
[test.mlir.txt](https://github.com/user-attachments/files/24098657/test.mlir.txt)

### What component(s) does this issue relate to?

_No response_

### Version information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvedhmeshram**
The GreedyPatternRewriter by default tries to merge regions in `GreedySimplifyRegionLevel::Aggressive` mode, this has problems that are previously well documented, for example see here https://github.com/llvm/llvm-project/pull/95057

In an issue reported here https://github.com/iree-org/iree/issues/22887 the merging was preventing the llvm backend from being able to fold some allocas. As a solution all passes that use GreedyPatternRewriter after scf-to-cf have been set to `GreedySimplifyRegionLevel::Normal` and uses of some upstream passes have been changed to have a `IREECodegen` version where we can control the rewriter.

This PR does not add any new logic but just changes the rewriter behavior so no additional tests seem necessary as the logic being moved around is tested upstream and existing tests should catch/signal any odd behavior. 

Fixes : https://github.com/iree-org/iree/issues/22887

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/Common/EmulateNarrowType.cpp [hunk 1]
```diff
@@ -635,16 +635,20 @@ LogicalResult emulateNarrowType(
     return root->emitOpError("failed to emulate bit width");
   }
 
+  GreedyRewriteConfig config;
+  config.setUseTopDownTraversal().setRegionSimplificationLevel(
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Codegen/Common/EmulateNarrowType.cpp]: Why top-down traversal? Cant see immediately if that was the existing behavior.

File: compiler/src/iree/compiler/Codegen/Common/IREECodegenAffineExpandIndexOps.cpp [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+
+struct IREECodegenAffineExpandIndexOpsPass final
+    : impl::IREECodegenAffineExpandIndexOpsPassBase<
+          IREECodegenAffineExpandIndexOpsPass> {
+public:
+  using Base::Base;
+
+  void runOnOperation() override {
+    GreedyRewriteConfig config;
+    config.setUseTopDownTraversal().setRegionSimplificationLevel(
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Codegen/Common/IREECodegenAffineExpandIndexOps.cpp]: Here too (and I suspect below as well). Why `top-down`? Maybe worth just leaving the default that the config uses.

File: compiler/src/iree/compiler/Codegen/Common/IREECodegenFoldMemRefAliasOps.cpp [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+  using Base::Base;
+
+  void runOnOperation() override {
+    GreedyRewriteConfig config;
+    config.setUseTopDownTraversal().setRegionSimplificationLevel(
+        GreedySimplifyRegionLevel::Normal);
+
+    RewritePatternSet patterns(&getContext());
+    memref::populateFoldMemRefAliasOpPatterns(patterns);
+    (void)applyPatternsGreedily(getOperation(), std::move(patterns), config);
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Codegen/Common/IREECodegenFoldMemRefAliasOps.cpp:33]: So if you dont put a `void` here you get a failure?

**Review by MaheshRavishankar — COMMENTED** [review]
Thanks Nirvedh. Mostly looks good. Can we add a pipeline test for this to make sure this doesnt get regressed again?

File: compiler/src/iree/compiler/Codegen/Common/IREECodegenFoldMemRefAliasOps.cpp (hunk 3 above)
Comment (nirvedhmeshram) [reply compiler/src/iree/compiler/Codegen/Common/IREECodegenFoldMemRefAliasOps.cpp:33]: Yes
```
 error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
 ```

**Comment by nirvedhmeshram** [comment]
> Thanks Nirvedh. Mostly looks good. Can we add a pipeline test for this to make sure this doesnt get regressed again?

I am trying to figure out how to test this, all our pipeline tests use `"builtin.module(hal.executable(hal.executable.variant(builtin.module(func.func(iree-llvmgpu-lower-executable-target{for-rocdl=true})))))"` but this only does the specific `DispatchLoweringPassPipeline` e.g TileAndFuse / VecDistribute and the resulting IR is still in scf, we are making changes in the `addLowerToLLVMGPUPasses` which dont seem to be tested as a full pass-pipeline as its mostly calling upstream stuff.

File: compiler/src/iree/compiler/Codegen/Common/IREECodegenFoldMemRefAliasOps.cpp (hunk 3 above)
Comment (krzysz00) [reply compiler/src/iree/compiler/Codegen/Common/IREECodegenFoldMemRefAliasOps.cpp:33]: That's calling for an `if (failed(...)) { return signalPassFailure(); }`

File: compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp [hunk 4]
```diff
@@ -1031,16 +1031,16 @@ static void addLowerToLLVMGPUPasses(OpPassManager &modulePassManager,
       .addPass(createSCFToControlFlowPass)
       .addPass(createCanonicalizerPass)
       .addPass(createCSEPass)
-      .addPass(memref::createFoldMemRefAliasOpsPass)
+      .addPass(createIREECodegenFoldMemRefAliasOpsPass)
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp:1034]: So, as an alternative ... why not move this pass before scf-to-cf, so that the `scf-to-cf` becomes basically the last thing in the pipeline

Comment (nirvedhmeshram) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp:1034]: i think it will hang by a thread in case the pass gets called later again also I am guessing it is called here after scf-to-cf becuase it might be unlocking some optimization in certain cases as we have already used this pass in earlier stages. Also, based on my discussions with @MaheshRavishankar it is ok to make the IREE specific passes as long as we are just calling upstream patterns in them.

File: compiler/src/iree/compiler/Codegen/Common/IREECodegenFoldMemRefAliasOps.cpp (hunk 3 above)
Comment (nirvedhmeshram) [reply compiler/src/iree/compiler/Codegen/Common/IREECodegenFoldMemRefAliasOps.cpp:33]: I dont think we should always be returning single pass failures, this is a pretty common pattern in our codegen
```
src/iree/compiler/Codegen/LLVMCPU/LLVMCPUVectorTransposeLowering.cpp:85:  (void)applyPatternsGreedily(funcOp, std::move(patterns));
src/iree/compiler/Codegen/LLVMCPU/LLVMCPUVirtualVectorLowering.cpp:68:      (void)applyPatternsGreedily(funcOp, std::move(patterns));
src/iree/compiler/Codegen/LLVMCPU/LLVMCPUVirtualVectorLowering.cpp:96:    (void)applyPatternsGreedily(funcOp, std::move(patterns));
src/iree/compiler/Codegen/LLVMCPU/LLVMCPUVectorShapeCastLowering.cpp:41:  (void)applyPatternsGreedily(funcOp, std::move(patterns));
src/iree/compiler/Codegen/Common/VectorTransferLowering.cpp:55:  (void)applyPatternsGreedily(funcOp, std::move(patterns));
src/iree/compiler/Codegen/Common/IREECodegenFoldMemRefAliasOps.cpp:33:    (void)applyPatternsGreedily(getOperation(), std::move(patterns), config);
src/iree/compiler/Codegen/Common/VectorizeMemrefCopy.cpp:120:    (void)applyPatternsGreedily(funcOp, std::move(patterns));
src/iree/compiler/Codegen/Common/GPU/VectorReductionToGPU.cpp:221:      (void)applyPatternsGreedily(getOperation(), std::move(patterns));
src/iree/compiler/Codegen/Common/GPU/VectorReductionToGPU.cpp:298:      (void)applyPatternsGreedily(getOperation(), std::move(patterns));
src/iree/compiler/Codegen/Common/GPU/VectorReductionToGPU.cpp:313:      (void)applyPatternsGreedily(getOperation(), std::move(patterns));
src/iree/compiler/Codegen/Common/GPU/GPUTile.cpp:184:  (void)applyPatternsGreedily(funcOp, std::move(patterns));
src/iree/compiler/Codegen/Common/GPU/GPUTile.cpp:200:  (void)applyPatternsGreedily(funcOp, std::move(patterns));
src/iree/compiler/Codegen/Common/GPU/GPUTile.cpp:330:      (void)applyPatternsGreedily(funcOp, std::move(patterns));
src/iree/compiler/Codegen/Common/DropVectorUnitDims.cpp:47:  (void)applyPatternsGreedily(funcOp, std::move(patterns));
src/iree/compiler/Codegen/Common/FissionTransferOpsInControlFlow.cpp:238:    (void)applyPatternsGreedily(funcOp, {});
src/iree/compiler/Codegen/Common/GenericVectorization.cpp:268:  (void)applyPatternsGreedily(funcOp, std::move(vectorizationPatterns));
```

Comment (nirvedhmeshram) [reply compiler/src/iree/compiler/Codegen/Common/IREECodegenFoldMemRefAliasOps.cpp:33]: Also is just a copy of what the upstream pass does
```
void FoldMemRefAliasOpsPass::runOnOperation() {
  RewritePatternSet patterns(&getContext());
  memref::populateFoldMemRefAliasOpPatterns(patterns);
  (void)applyPatternsGreedily(getOperation(), std::move(patterns));
}
```

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/Common/IREECodegenFoldMemRefAliasOps.cpp:33]: All of those places are effectively bugs. The upstream is also a bug. It's ok to do that for now, but I was curious if we actually see failures

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/Common/IREECodegenFoldMemRefAliasOps.cpp:33]: All of those places are effectively bugs. The upstream is also a bug. It's ok to do that for now, but I was curious if we actually see failures

Comment (nirvedhmeshram) [reply compiler/src/iree/compiler/Codegen/Common/IREECodegenFoldMemRefAliasOps.cpp:33]: Yes indeed the pass can fail and break the compilation if we fall back to if (failed(...)) { return signalPassFailure(); }, the underlying error I see (only visible with debug flag) is 
```
[greedy-rewriter GreedyPatternRewriteDriver.cpp:937 1] The pattern rewrite did not converge after scanning 10 times
```
so I suspect that this might be a hack around this problem in all those cases.

**Review by MaheshRavishankar — APPROVED** [review]
Thanks @nirvedhmeshram !
