### PR TITLE
Fix calculation of byte offset to element offset during bufferization.

### LINKED ISSUE #14642: Sub-byte type globals produce incorrect results
```mlir
#map = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
module {
ml_program.global public @cst(dense<[[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]]> : tensor<8x8xi4>) : tensor<8x8xi4>
  func.func @forward() -> tensor<8x4x2xf32> {
    %cst = ml_program.global_load_const @cst : tensor<8x8xi4>
    %expanded_4 = tensor.expand_shape %cst [[0], [1, 2]] : tensor<8x8xi4> into tensor<8x4x2xi4>
    %0 = tensor.empty() : tensor<8x4x2xf32>
    %5 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded_4 : tensor<8x4x2xi4>) outs(%0 : tensor<8x4x2xf32>) {
    ^bb0(%in: i4, %out: f32):
      %6 = arith.extui %in : i4 to i32 
      %7 = arith.uitofp %6 : i32 to f32 
      linalg.yield %7 : f32 
    } -> tensor<8x4x2xf32>
    return %5 : tensor<8x4x2xf32>
  }
}
```
Compiled + run through vulkan or cpu will produce zero values
```
EXEC @forward
result[0]: hal.buffer_view
8x4x2xf32=[[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]]
```
If the constant is instead an arith.constant it gives correct values.

(compile + run repro)
```
iree-compile packed_global.mlir \
    --iree-stream-resource-index-bits=64 \
    --iree-vm-target-index-bits=64 \
    --iree-input-type=none \
    --iree-hal-target-backends=vulkan-spirv \
    --iree-opt-const-expr-hoisting=false \
    --iree-flow-inline-constants-max-byte-length=0 \
    -o /tmp/i4_packed.vmfb

iree-run-module --device=vulkan --function=forward \
  --module=/tmp/i4_packed.vmfb
```

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
The logic was not adapted to handle sub-byte sizes. This handles powers of 2 sub-byte sizes only. To handle more general case requires upstream MLIR to have a good representation of the packing of such types. This should be revisited and adapted then.

Fixes #14642

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

File: compiler/src/iree/compiler/Codegen/Utils/Utils.cpp [hunk 1]
```diff
@@ -711,29 +711,32 @@ OpFoldResult convertByteOffsetToElementOffset(RewriterBase &rewriter,
...
-          .Default([&](Type t) -> OpFoldResult {
-            return rewriter.create<IREE::Util::SizeOfOp>(loc, elementType)
-                .getResult();
-          });
-  AffineExpr s0, s1;
-  bindSymbols(rewriter.getContext(), s0, s1);
-  return affine::makeComposedFoldedAffineApply(rewriter, loc, s0.floorDiv(s1),
-                                               {byteOffset, elementWidth});
+  if (isa<ComplexType, FloatType, IntegerType, VectorType>(elementType)) {
+    unsigned typeBitWidth = IREE::Util::getTypeBitWidth(elementType);
```
Comment (benvanik) [inline compiler/src/iree/compiler/Codegen/Utils/Utils.cpp:715]: this is wrong too - it doesn't support packing - you need to replicate what getRoundedPhysicalStorageSize is doing (I have a PR I was working on before randomized that does all the affine stuff - we'd want to use that here)

Comment (benvanik) [reply compiler/src/iree/compiler/Codegen/Utils/Utils.cpp:715]: I don't want users trying i3/i5/etc to hit compiler crashes because of this assert - I really think we should probably not add this verifier until we can do it properly)

Comment (benvanik) [reply compiler/src/iree/compiler/Codegen/Utils/Utils.cpp:715]: (got confused and thought this was lei's PR - but it has the same issue - I think this isn't the right expression and I'm not a fan of the compiler crashing if a user tries to use i3/i5)

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/Utils/Utils.cpp:715]: Well, we don't have a good representation of i3/i5 etc. We really can't support those right now. That's why the assert so that we can resist when we can
