### PR TITLE
[CPU] Tile reduction dimensions for non-root reduction ops.

### LINKED ISSUE #21359: [Codegen] compilation fails because of vector size verification error
### What happened?

The compilation of this dispatch (and another I'm not sharing) fails with `error: One or more operations with large vector sizes (8192 bytes) were found`:

```mlir
#executable_target_embedded_elf_x86_64 = #hal.executable.target<"llvm-cpu", "embedded-elf-x86_64", {cpu = "x86-64", cpu_features = "+cmov,+mmx,+sse,+sse2,+cx8,+x87,+fxsr", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128", iree.encoding.resolver = #iree_cpu.cpu_encoding_layout<>, max_stack_allocation_size = 32768 : i64, native_vector_size = 16 : i64, target_triple = "x86_64-unknown-unknown-eabi-elf"}>
#translation2 = #iree_codegen.translation_info<pipeline = CPUDoubleTilingExpert>
#pipeline_layout4 = #hal.pipeline.layout<constants = 8, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>
#config35 = #iree_codegen.lowering_config<tile_sizes = [[32, 32], [1, 4], [0, 0], [0, 0]]>
#config36 = #iree_codegen.lowering_config<tile_sizes = [[32, 32, 0], [1, 4, 0], [0, 0, 4], [0, 0, 0]]>
#config37 = #iree_codegen.lowering_config<tile_sizes = [[32, 32, 0], [1, 4, 0], [0, 0, 0], [0, 0, 4]]>
#map5 = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
#map14 = affine_map<(d0, d1, d2) -> (d0, d1)>
#device_target_local = #hal.device.target<"local", [#executable_target_embedded_elf_x86_64]> : !hal.device
module @module attributes {stream.affinity.default = #hal.device.affinity<@__device_0>} {
  util.global private @__device_0 = #device_target_local
    hal.executable private @SD_generate$async_dispatch_62 {
    hal.executable.variant public @embedded_elf_x86_64 target(#executable_target_embedded_elf_x86_64) {
      hal.executable.export public @SD_generate$async_dispatch_62_softmax_DxDxDxf32_dispatch_tensor_store ordinal(0) layout(#pipeline_layout4) count(%arg0: !hal.device, %arg1: index, %arg2: index) -> (index, index, index) {
        %x, %y, %z = iree_tensor_ext.dispatch.workgroup_count_from_slice %arg1, %arg2
        hal.return %x, %y, %z : index, index, index
      }
      builtin.module {
        func.func @SD_generate$async_dispatch_62_softmax_DxDxDxf32_dispatch_tensor_store() attributes {translation_info = #translation2} {
          %cst = arith.constant 0.000000e+00 : f32
          %cst_0 = arith.constant 0xFFC00000 : f32
          %c32_i64 = arith.constant 32 : i64
          %0 = hal.interface.constant.load layout(#pipeline_layout4) ordinal(0) : i32
          %1 = hal.interface.constant.load layout(#pipeline_layout4) ordinal(1) : i32
          %2 = hal.interface.constant.load layout(#pipeline_layout4) ordinal(2) : i32
          %3 = hal.interface.constant.load layout(#pipeline_layout4) ordinal(3) : i32
          %4 = hal.interface.constant.load layout(#pipeline_layout4) ordinal(4) : i32
          %5 = hal.interface.constant.load layout(#pipeline_layout4) ordinal(5) : i32
          %6 = hal.interface.constant.load layout(#pipeline_layout4) ordinal(6) : i32
          %7 = hal.interface.constant.load layout(#pipeline_layout4) ordinal(7) : i32
          %8 = arith.extui %0 : i32 to i64
          %9 = arith.extui %1 : i32 to i64
          %10 = arith.shli %9, %c32_i64 : i64
          %11 = arith.ori %8, %10 : i64
          %12 = arith.index_castui %11 : i64 to index
          %13 = arith.extui %2 : i32 to i64
          %14 = arith.extui %3 : i32 to i64
          %15 = arith.shli %14, %c32_i64 : i64
          %16 = arith.ori %13, %15 : i64
          %17 = arith.index_castui %16 : i64 to index
          %18 = arith.extui %4 : i32 to i64
          %19 = arith.extui %5 : i32 to i64
          %20 = arith.shli %19, %c32_i64 : i64
          %21 = arith.ori %18, %20 : i64
          %22 = arith.index_castui %21 : i64 to index
          %23 = arith.extui %6 : i32 to i64
          %24 = arith.extui %7 : i32 to i64
          %25 = arith.shli %24, %c32_i64 : i64
          %26 = arith.ori %23, %25 : i64
          %27 = arith.index_castui %26 : i64 to index
          %28:2 = util.assume.int 
              %22[<umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 18446744073709549568>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 288230376151711744>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 144115188075855888>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 96076792050570600>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 72057594037927960>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <umin = 0, umax = 57646075230342372>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 216172782113783808>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 108086391056891916>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 72057594037927950>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 54043195528445970>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>, <umin = 0, umax = 43234556422756779>], 
              %27[<umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 0, umax = 9007199254740991>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 1, umax = 9007199254740992>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 2, umax = 9007199254740993>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 3, umax = 9007199254740994>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 4, umax = 9007199254740995>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>, <umin = 5, umax = 9007199254740996>]
            : index, index
          %29 = iree_tensor_ext.dispatch.workload.ordinal %28#0, 0 : index
          %30 = iree_tensor_ext.dispatch.workload.ordinal %28#1, 1 : index
          %31 = hal.interface.binding.subspan layout(#pipeline_layout4) binding(0) alignment(64) offset(%12) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<?x?x?xf32>>{%29, %30, %30}
          %32 = hal.interface.binding.subspan layout(#pipeline_layout4) binding(1) alignment(64) offset(%17) flags(Indirect) : !iree_tensor_ext.dispatch.tensor<writeonly:tensor<?x?x?xf32>>{%29, %30, %30}
          %33 = iree_tensor_ext.dispatch.tensor.load %31, offsets = [0, 0, 0], sizes = [%29, %30, %30], strides = [1, 1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<?x?x?xf32>>{%29, %30, %30} -> tensor<?x?x?xf32>
          %34 = tensor.empty(%29, %30, %30) : tensor<?x?x?xf32>
          %35 = tensor.empty(%29, %30) : tensor<?x?xf32>
          %36 = linalg.fill {lowering_config = #config35} ins(%cst_0 : f32) outs(%35 : tensor<?x?xf32>) -> tensor<?x?xf32>
          %37 = linalg.generic {indexing_maps = [#map5, #map14], iterator_types = ["parallel", "parallel", "reduction"]} ins(%33 : tensor<?x?x?xf32>) outs(%36 : tensor<?x?xf32>) attrs =  {lowering_config = #config36} {
          ^bb0(%in: f32, %out: f32):
            %41 = arith.maxnumf %in, %out : f32
            linalg.yield %41 : f32
          } -> tensor<?x?xf32>
          %38 = linalg.fill {lowering_config = #config35} ins(%cst : f32) outs(%35 : tensor<?x?xf32>) -> tensor<?x?xf32>
          %39 = linalg.generic {indexing_maps = [#map5, #map14, #map14], iterator_types = ["parallel", "parallel", "reduction"]} ins(%33, %37 : tensor<?x?x?xf32>, tensor<?x?xf32>) outs(%38 : tensor<?x?xf32>) attrs =  {lowering_config = #config36} {
          ^bb0(%in: f32, %in_1: f32, %out: f32):
            %41 = arith.subf %in, %in_1 : f32
            %42 = math.exp %41 : f32
            %43 = arith.addf %42, %out : f32
            linalg.yield %43 : f32
          } -> tensor<?x?xf32>
          %40 = linalg.generic {indexing_maps = [#map5, #map14, #map14, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%33, %37, %39 : tensor<?x?x?xf32>, tensor<?x?xf32>, tensor<?x?xf32>) outs(%34 : tensor<?x?x?xf32>) attrs =  {lowering_config = #config37} {
          ^bb0(%in: f32, %in_1: f32, %in_2: f32, %out: f32):
            %41 = arith.subf %in, %in_1 : f32
            %42 = math.exp %41 : f32
            %43 = arith.divf %42, %in_2 : f32
            linalg.yield %43 : f32
          } -> tensor<?x?x?xf32>
          iree_tensor_ext.dispatch.tensor.store %40, %32, offsets = [0, 0, 0], sizes = [%29, %30, %30], strides = [1, 1, 1] : tensor<?x?x?xf32> -> !iree_tensor_ext.dispatch.tensor<writeonly:tensor<?x?x?xf32>>{%29, %30, %30}
          return
        }
      }
    }
  }
}
```

However, reverting the changes that were recommended here and that are integrated in IREE v3.5.0, the dispatch compiles correctly:

> @ziereis Could you change https://github.com/iree-org/iree/blob/f42b90d23c332bee6dedd1c8f44e07b9b1a52f74/compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp#L408 with 
> `funcPassManager.addPass(createLLVMCPUTileRootAndFuseInputOperands(i));` and try. 

 _Originally posted by @pashu123 in [#19005](https://github.com/iree-org/iree/issues/19005#issuecomment-2462958894)_

### Steps to reproduce your issue

Compile with 
```bash
iree-compile repro.mlir \
-o repro_out.mlir \
--iree-hal-local-target-device-backends=llvm-cpu \
--iree-llvmcpu-target-cpu=x86-64 \
--compile-from=executable-configurations \
--compile-to=executable-targets \
--mlir-print-ir-after-failure \
--mlir-disable-threading \
--mlir-print-stacktrace-on-diagnostic \
2> repro_logs.mlir
```

### What component(s) does this issue relate to?

Compiler

### Version information

v3.5.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hanhanW**
The revision adds an option to skip root op in LLVMCPUTile pass, and uses it in multi level tiling pipeline.

In softmax dispatch, there are two reduction ops. Only the root op is tiled for reduction dimensions when we switched to LLVMCPUTileRootAndFuseInputOperandsPass. It results in large vector sizes in the other reduction op when `util.assume.hint` ops are present.

We did not hit the issue in e2e tests because AnnotateDispatchAssumptions pass behaves differently. The value range is [0, 0] if the input is from `flow.tensor.dynamic_constant`.

Fixes https://github.com/iree-org/iree/issues/21359

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp [hunk 1]
```diff
@@ -418,6 +418,11 @@ void addMultiTilingExpertPassPipeline(OpPassManager &funcPassManager,
             createLLVMCPUSplitReductionPass(clEnableReassociateFpReductions));
         funcPassManager.addPass(createLLVMCPUTileRootAndFuseInputOperandsPass(
             static_cast<IREE::CPU::TilingLevel>(i)));
+        // Tile all the reduction ops for target vector sizes. It is a nop for
+        // rootOp because it is already tiled with the same tile sizes. It
+        // ensures that all the dimensions are tiled in all the reduction ops.
+        funcPassManager.addPass(
+            createLLVMCPUTilePass(static_cast<IREE::CPU::TilingLevel>(i)));
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: It is not NOP if the dimension size is not divisible by tile size, because it becomes dynamic shapes and the for loops can't be folded away.

I think we need to provide an option to `LLVMCPUTilePass` that allows only tiling on non-root ops.

**Review by maxbartel — APPROVED** [review]
Thanks @hanhanW! We will try this out on Monday and tell you if we still see some issues.

**Comment by hanhanW** [comment]
This starts depending on https://github.com/iree-org/iree/pull/21354 because we need a way to determine the root op. The needed patches will be propagated to IREE in https://github.com/iree-org/iree/pull/21510. Instead of adding tech debt, I'd like to wait for a couple of days and land this after the switch.
