### PR TITLE
[GPU] Bail out in matmul TileAndFuse config for unaligned dynamic shapes

### LINKED ISSUE #20581: [compiler] Deepseek-V3 compile fails with codegen issues
### What happened?

[This](https://github.com/iree-org/iree/pull/20576) fix for #20548 further uncovered multiple codegen issues like - https://gist.github.com/archana-ramalingam/84c4fa9b9cbad20385aaf90ffe009abe.

Creating this issue with an end goal of being able to compile the linked deepseek mlir (has 3 attention+FFN and 1 attention+MoE block) successfully by iteratively resolving all underlying sub-issues. 

This is critical for Deepseek-V3 enablement for May 5th release.

### Steps to reproduce your issue

1. Fetch mlir: https://gist.github.com/archana-ramalingam/b692d0a123edb798596ec68f0044dd2e
2. Run compile:
```
iree-compile deepseek_v3_f16_blk_0_3.mlir \
  --iree-hip-target=gfx942  \
  --iree-hal-target-device=hip  \
  -o=deepseek_v3_f16_blk_0_3.vmfb   
```
3. Error:  https://gist.github.com/archana-ramalingam/84c4fa9b9cbad20385aaf90ffe009abe

### What component(s) does this issue relate to?

Compiler

### Version information

Commit @ b3fcfb6c5e7bead99b16285cba3d612687b31ee4

### Additional context

This commit https://github.com/iree-org/iree/commit/b3fcfb6c5e7bead99b16285cba3d612687b31ee4 led to 2 more issues:
1. sharktank **testBenchmark70B_f16_TP8_Non_Decomposed_Input_Len_128** test fail too on 0419 https://github.com/nod-ai/shark-ai/actions/runs/14548496681/job/40816909348#step:7:386534, will xfail it in sharktank https://github.com/nod-ai/shark-ai/pull/1285

fetch mlir https://sharkpublic.blob.core.windows.net/sharkpublic/chi/llama/llama70b/f16_torch_128_tp8.mlir
reproduce issue:
```
iree-compile /home/chi/src/shark-ai/2025-04-20/llama-70b/f16_torch_128_tp8.mlir --iree-hip-target=gfx942 -o=/home/chi/src/shark-ai/2025-04-20/llama-70b/f16_torch_128_tp8.vmfb --iree-hal-target-device=hip[0] --iree-hal-target-device=hip[1] --iree-hal-target-device=hip[2] --iree-hal-target-device=hip[3] --iree-hal-target-device=hip[4] --iree-hal-target-device=hip[5] --iree-hal-target-device=hip[6] --iree-hal-target-device=hip[7] --iree-hal-dump-executable-files-to=/home/chi/src/shark-ai/2025-04-20/llama-70b/f16_torch_128_tp8/files --iree-opt-level=O3 --iree-hal-indirect-command-buffers=true --iree-stream-resource-memory-model=discrete --iree-hal-memoization=true
```

2. llama 8b fp8 performance regression:

|commit|128|128|2048|2048|
|--------|--------|--------|--------|--------|
||prefill|decode|prefill|decode|
|https://github.com/iree-org/iree/commit/b3fcfb6c5e7bead99b16285cba3d612687b31ee4|31.3 | 10.5 | 386 | 20.4| 
|before|30.2 | 10 | 386 | 16.7|
|[042411](https://github.com/iree-org/iree/commit/b4e3694a31a92a814a7b127f288e5928705fb3c4)|40.0|21.7|397|27.8|

### PR DESCRIPTION
**Pull request by nirvedhmeshram**
We cant always handle such shapes with the padding method used by the pipeline.
Fixes : https://github.com/iree-org/iree/issues/20581

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 1]
```diff
@@ -204,6 +204,11 @@ getMatmulLoweringConfigAndWorkgroupSize(SmallVector<int64_t> bounds,
       ShapedType::isDynamic(bounds[contractionDims.k.back()])) {
     return failure();
   }
+  // We can support unaligned shapes as long as there are no dynamic dimensions
+  // as finding padding bounds for dynamic dimensions is not guaranteed.
+  // TODO (nirvedhmeshram) : Add support so that we can find the bounds
+  // information.
+  bool canSupportUnAligned = true;
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: nit:
```suggestion
  bool canSupportUnaligned = true;
```

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 2]
```diff
@@ -212,22 +217,30 @@ getMatmulLoweringConfigAndWorkgroupSize(SmallVector<int64_t> bounds,
   for (int64_t mDim : contractionDims.m) {
     if (!ShapedType::isDynamic(bounds[mDim])) {
       mDims.push_back(mDim);
+    } else {
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: nit: remove the negation in the `if` condition to simplify the logic? Currently it reads like double negation: support for unaligned is disabled when the shape is not dynamic...

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 3]
```diff
@@ -204,31 +204,43 @@ getMatmulLoweringConfigAndWorkgroupSize(SmallVector<int64_t> bounds,
       ShapedType::isDynamic(bounds[contractionDims.k.back()])) {
     return failure();
   }
+  // We can support unaligned shapes as long as there are no dynamic dimensions
+  // as finding padding bounds for dynamic dimensions is not guaranteed.
+  // TODO (nirvedhmeshram) : Add support so that we can find the bounds
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]:
```suggestion
  // TODO(nirvedhmeshram): Add support so that we can find the bounds
```

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 4]
```diff
@@ -204,31 +204,43 @@ getMatmulLoweringConfigAndWorkgroupSize(SmallVector<int64_t> bounds,
       ShapedType::isDynamic(bounds[contractionDims.k.back()])) {
     return failure();
   }
+  // We can support unaligned shapes as long as there are no dynamic dimensions
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]:
```suggestion
  }
  
  // We can support unaligned shapes as long as there are no dynamic dimensions
```

**Review by kuhar — APPROVED** [review]
LGTM
