### PR TITLE
Strided pack/unpack ukernels

### LINKED ISSUE #17507: [LLVMCPU][UKernels] Pack and unpack ukernels not passing appropriate strides
The lowering to ukernels for pack and unpack ops fails to capture necessary striding information. For example, in the following IR, the inner dimension is strided, but the ukernel does not capture that information:

```
// -----// IR Dump After LowerUKernelOpsToCalls (iree-codegen-lower-ukernel-ops-to-calls) //----- //
module {
  func.func private @iree_uk_pack(memref<bf16>, index, index, memref<bf16>, index, index, index, index, index, index, index, index, i64, i32) -> i32 attributes {hal.import.bitcode = true, hal.import.fields = ["processor_data"], llvm.bareptr = true}
  func.func @main$async_dispatch_3_pack_bf16() attributes {translation_info = #iree_codegen.translation_info<CPUDataTiling>} {
    %c5_i32 = arith.constant 5 : i32
    %c2 = arith.constant 2 : index
    %c16 = arith.constant 16 : index
    %c0_i64 = arith.constant 0 : i64
    %c64 = arith.constant 64 : index
    %c8 = arith.constant 8 : index
    %c0 = arith.constant 0 : index
    %c247808 = arith.constant 247808 : index
    %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<121x16x64xbf16>
    memref.assume_alignment %0, 64 : memref<121x16x64xbf16>
    %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c247808) : memref<64x8x8x16x2xbf16, strided<[2048, 256, 32, 2, 1], offset: 123904>>
    memref.assume_alignment %1, 64 : memref<64x8x8x16x2xbf16, strided<[2048, 256, 32, 2, 1], offset: 123904>>
    %workgroup_id_x = hal.interface.workgroup.id[0] : index
    %workgroup_count_x = hal.interface.workgroup.count[0] : index
    %workgroup_id_y = hal.interface.workgroup.id[1] : index
    %workgroup_count_y = hal.interface.workgroup.count[1] : index
    %2 = affine.apply affine_map<()[s0] -> (s0 * 2)>()[%workgroup_id_x]
    %3 = affine.apply affine_map<()[s0] -> (s0 * 2)>()[%workgroup_count_x]
    scf.for %arg0 = %workgroup_id_y to %c64 step %workgroup_count_y {
      scf.for %arg1 = %2 to %c8 step %3 {
        %subview = memref.subview %1[%arg0, %arg1, 0, 0, 0] [1, 2, 8, 16, 2] [1, 1, 1, 1, 1] : memref<64x8x8x16x2xbf16, strided<[2048, 256, 32, 2, 1], offset: 123904>> to memref<1x2x8x16x2xbf16, strided<[2048, 256, 32, 2, 1], offset: ?>>
        %4 = affine.min affine_map<(d0) -> (d0 * -16 + 121, 32)>(%arg1)
        %5 = affine.apply affine_map<(d0) -> (d0 * 16)>(%arg1)
        %subview_0 = memref.subview %0[%5, 0, %arg0] [%4, 16, 1] [1, 1, 1] : memref<121x16x64xbf16> to memref<?x16x1xbf16, strided<[1024, 64, 1], offset: ?>>
        %subview_1 = memref.subview %subview_0[0, 0, 0] [%4, 16, 1] [1, 1, 1] : memref<?x16x1xbf16, strided<[1024, 64, 1], offset: ?>> to memref<?x16xbf16, strided<[1024, 64], offset: ?>>
        %subview_2 = memref.subview %subview[0, 0, 0, 0, 0] [1, 2, 8, 16, 2] [1, 1, 1, 1, 1] : memref<1x2x8x16x2xbf16, strided<[2048, 256, 32, 2, 1], offset: ?>> to memref<2x8x16x2xbf16, strided<[256, 32, 2, 1], offset: ?>>
        %base_buffer, %offset, %sizes:2, %strides:2 = memref.extract_strided_metadata %subview_1 : memref<?x16xbf16, strided<[1024, 64], offset: ?>> -> memref<bf16>, index, index, index, index, index
        %base_buffer_3, %offset_4, %sizes_5:4, %strides_6:4 = memref.extract_strided_metadata %subview_2 : memref<2x8x16x2xbf16, strided<[256, 32, 2, 1], offset: ?>> -> memref<bf16>, index, index, index, index, index, index, index, index, index
        %6 = func.call @iree_uk_pack(%base_buffer, %offset, %strides#0, %base_buffer_3, %offset_4, %strides_6#0, %4, %c16, %c2, %c8, %c16, %c2, %c0_i64, %c5_i32) : (memref<bf16>, index, index, memref<bf16>, index, index, index, index, index, index, index, index, i64, i32) -> i32
      }
    }
    return
  }
}
```

This happens because the `strided_outer_dims` is set to `1` for all pack and unpack ukernels:
https://github.com/iree-org/iree/blob/29e70abcd352a4d037509e6ecf5e52507b738f4e/compiler/src/iree/compiler/Codegen/Common/CPU/CPULowerToUKernels.cpp#L395

This is probably intentional, as it seems that Ukernels may not support cases where inner dimensions are strided. It would be great to be able to support strided cases in the pack ukernels, and then fix this lowering issue, but the lowering should fail at the very least, since it causes correctness issues.

### PR DESCRIPTION
**Pull request by bjacob**
The pack ukernel gains the ability to support inner-strided sources, and the unpack ukernel gains the ability to support inner-strided destinations.

Note that the pack and unpack ukernels both use a small temporary buffer to decouple source vs destination layout aspects, limiting the combinatorics. The inner-striding aspect here is local to the "2D" side, orthogonal to the "4D" side which is what we have architecture specific code paths for. The "2D" side was handled by generic loops with generic memcpy/memset primitives. What changes here is that now we need a "memcpy with stride on either src or dst".

This is implemented as scalar loops. I tried using AVX-512 gather/scatter instructions, but that turned out 2x slower than a scalar loop on AMD Zen4 where they are micro-coded, and the Intel documentation suggests a very high cost there too.

Fixes #17507.

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPULowerToUKernels.cpp [hunk 1]
```diff
@@ -392,7 +392,7 @@ matchDAGForUKernel(RewriterBase &rewriter, tensor::PackOp op,
       ValueRange{in_size0, in_size1, out_size0, out_size1, out_size2, out_size3,
                  paddingVal, flagsVal},
       /*fn_def_attrs=*/rewriter.getDictionaryAttr(fn.defAttrs),
-      /*strided_outer_dims=*/rewriter.getIndexAttr(1));
+      /*strided_outer_dims=*/rewriter.getIndexAttr(2));
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/CPU/CPULowerToUKernels.cpp:395]: Why is it `2`? Do we need a similar change in mmt4d ukernel conversion?

File: runtime/src/iree/modules/vmvx/module.c [hunk 2]
```diff
@@ -636,8 +638,9 @@ IREE_VMVX_ABI_EXPORT(iree_vmvx_pack, pack, v) {
                            /*stride1=*/1,
```
Comment (hanhanW) [inline runtime/src/iree/modules/vmvx/module.c:638]: should this be `args->out_stride1`?

File: runtime/src/iree/modules/vmvx/module.c [hunk 3]
```diff
@@ -689,11 +694,12 @@ IREE_VMVX_ABI_EXPORT(iree_vmvx_unpack, unpack, v) {
                            /*buffer_ref=*/args->out_ref,
                            /*offset=*/args->out_offset,
                            /*stride0=*/args->out_stride0,
-                           /*stride1=*/1,
+                           /*stride1=*/args->out_stride1,
```
Comment (hanhanW) [inline runtime/src/iree/modules/vmvx/module.c:697]: I can't comment on above lines. Should `/*stride1=*/1` be `args->in_stride1` in l.690?

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPULowerToUKernels.cpp (hunk 1 above)
Comment (bjacob) [reply compiler/src/iree/compiler/Codegen/Common/CPU/CPULowerToUKernels.cpp:395]: This `strided_outer_dims` attribute is a single integer govering all strides for all operands of the ukernel. Since we want 2 strides for the input, we have to set it to 2, and then we will get an extra stride passed for the output too, but that's OK, we will simply not use it. The pack output is still not strided beyond the outermost dimension.

File: runtime/src/iree/modules/vmvx/module.c (hunk 2 above)
Comment (bjacob) [reply runtime/src/iree/modules/vmvx/module.c:638]: (Addressing this comment and the next) - Very good question, and actually that is how I initially wrote it, and tests were mysteriously failing. What was happening was an early-return case hidden in those `MAP_BUFFER_2D_UNTYPED_RO`, `MAP_BUFFER_2D_UNTYPED_RW` macros:
https://github.com/iree-org/iree/blob/5145f7e4e9ab65de1dd91a015440526af678b826/runtime/src/iree/modules/vmvx/module.c#L154-L158
What was happening is that this check was failing in `iree_vm_buffer_map`:
https://github.com/iree-org/iree/blob/5145f7e4e9ab65de1dd91a015440526af678b826/runtime/src/iree/vm/buffer.c#L26

What is going on here is that we are abusing shared macros to map 2D buffers (`MAP_BUFFER_2D_UNTYPED_RO`, `MAP_BUFFER_2D_UNTYPED_RW`) to map 4D buffers. We do that by taking advantage of the fact that the inner 3 dimensions are contiguous, so we coalesce them by treating these 3 dimensions as a single dimension with product size:
https://github.com/iree-org/iree/blob/5145f7e4e9ab65de1dd91a015440526af678b826/runtime/src/iree/modules/vmvx/module.c#L610
and
https://github.com/iree-org/iree/blob/5145f7e4e9ab65de1dd91a015440526af678b826/runtime/src/iree/modules/vmvx/module.c#L638

The value 1 for the stride there then simply reflects the fact that this is now treated as the inner-most dimension.

It's a ugly hack, but it's inside vmvx so... probably not worth fixing :-)

**Review by hanhanW — APPROVED** [review]
