### PR TITLE
[Im2Col] Support converting group convs to im2col

### LINKED ISSUE #20498: [GPU] compilation failure for alternative bwd grouped conv
### What happened?

Two similar sets of IR for backward grouped convolution are provided. 

The first performs grouped-dim expansion and collapse around the conv, which happens after filter spatial dim flips and `dLdy` padding (this compiles), and the second performs expand/collapse at the function boundaries and applies filter flipping and padding after expansion (but fails to compile).

## This IR Compiles

```mlir
#map = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#map1 = affine_map<(d0, d1, d2, d3, d4, d5, d6, d7) -> (d0, d1 + d6, d2 + d7, d3, d5)>
#map2 = affine_map<(d0, d1, d2, d3, d4, d5, d6, d7) -> (d3, d5, d6, d7, d4)>
#map3 = affine_map<(d0, d1, d2, d3, d4, d5, d6, d7) -> (d0, d1, d2, d3, d4)>
module @module {
  util.func public @conv_2d_float32_input_backward_128x24x48x384_nhwc_384x1x3x128_fhwc_nhwf_1x1s_0x1p_1x1d_3g$async(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view, %arg2: !hal.fence, %arg3: !hal.fence) -> !hal.buffer_view attributes {inlining_policy = #util.inline.never, iree.abi.model = "coarse-fences", iree.abi.stub, preprocessing_pipeline = #util.preprocessing_pipeline<"iree-preprocessing-make-single-dispatch">} {
    %cst = arith.constant 0.000000e+00 : f32
    %c2 = arith.constant 2 : index
    %0 = hal.tensor.import wait(%arg2) => %arg0 : !hal.buffer_view -> tensor<128x24x48x384xf32>
    %1 = hal.tensor.import wait(%arg2) => %arg1 : !hal.buffer_view -> tensor<384x1x3x128xf32>
    %2 = tensor.empty() : tensor<384x1x3x128xf32>
    %3 = linalg.fill ins(%cst : f32) outs(%2 : tensor<384x1x3x128xf32>) -> tensor<384x1x3x128xf32>
    %4 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%1 : tensor<384x1x3x128xf32>) outs(%3 : tensor<384x1x3x128xf32>) {
    ^bb0(%in: f32, %out: f32):
      %10 = linalg.index 0 : index
      %11 = linalg.index 1 : index
      %12 = linalg.index 2 : index
      %13 = linalg.index 3 : index
      %14 = arith.subi %c2, %12 : index
      %extracted = tensor.extract %1[%10, %11, %14, %13] : tensor<384x1x3x128xf32>
      linalg.yield %extracted : f32
    } -> tensor<384x1x3x128xf32>
    %padded = tensor.pad %0 low[0, 0, 1, 0] high[0, 0, 1, 0] {
    ^bb0(%arg4: index, %arg5: index, %arg6: index, %arg7: index):
      tensor.yield %cst : f32
    } : tensor<128x24x48x384xf32> to tensor<128x24x50x384xf32>
    %expanded = tensor.expand_shape %padded [[0], [1], [2], [3, 4]] output_shape [128, 24, 50, 3, 128] : tensor<128x24x50x384xf32> into tensor<128x24x50x3x128xf32>
    %expanded_0 = tensor.expand_shape %4 [[0, 1], [2], [3], [4]] output_shape [3, 128, 1, 3, 128] : tensor<384x1x3x128xf32> into tensor<3x128x1x3x128xf32>
    %5 = tensor.empty() : tensor<128x24x48x3x128xf32>
    %6 = linalg.fill ins(%cst : f32) outs(%5 : tensor<128x24x48x3x128xf32>) -> tensor<128x24x48x3x128xf32>
    %7 = linalg.generic {indexing_maps = [#map1, #map2, #map3], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel", "reduction", "reduction", "reduction"]} ins(%expanded, %expanded_0 : tensor<128x24x50x3x128xf32>, tensor<3x128x1x3x128xf32>) outs(%6 : tensor<128x24x48x3x128xf32>) {
    ^bb0(%in: f32, %in_1: f32, %out: f32):
      %10 = arith.mulf %in, %in_1 : f32
      %11 = arith.addf %out, %10 : f32
      linalg.yield %11 : f32
    } -> tensor<128x24x48x3x128xf32>
    %collapsed = tensor.collapse_shape %7 [[0], [1], [2], [3, 4]] : tensor<128x24x48x3x128xf32> into tensor<128x24x48x384xf32>
    %8 = hal.tensor.barrier join(%collapsed : tensor<128x24x48x384xf32>) => %arg3 : !hal.fence
    %9 = hal.tensor.export %8 : tensor<128x24x48x384xf32> -> !hal.buffer_view
    util.return %9 : !hal.buffer_view
  }
  util.func public @conv_2d_float32_input_backward_128x24x48x384_nhwc_384x1x3x128_fhwc_nhwf_1x1s_0x1p_1x1d_3g(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub} {
    %0 = util.null : !hal.fence
    %c-1_i32 = arith.constant -1 : i32
    %c0 = arith.constant 0 : index
    %device_0 = hal.devices.get %c0 : !hal.device
    %fence = hal.fence.create device(%device_0 : !hal.device) flags("None") : !hal.fence
    %1 = util.call @conv_2d_float32_input_backward_128x24x48x384_nhwc_384x1x3x128_fhwc_nhwf_1x1s_0x1p_1x1d_3g$async(%arg0, %arg1, %0, %fence) : (!hal.buffer_view, !hal.buffer_view, !hal.fence, !hal.fence) -> !hal.buffer_view
    %status = hal.fence.await until([%fence]) timeout_millis(%c-1_i32) flags("None") : i32
    util.return %1 : !hal.buffer_view
  }
}
```

## This IR Fails To Compile

```mlir
#map = affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2, d3, d4)>
#map1 = affine_map<(d0, d1, d2, d3, d4, d5, d6, d7) -> (d0, d1 + d6, d2 + d7, d3, d5)>
#map2 = affine_map<(d0, d1, d2, d3, d4, d5, d6, d7) -> (d3, d5, d6, d7, d4)>
#map3 = affine_map<(d0, d1, d2, d3, d4, d5, d6, d7) -> (d0, d1, d2, d3, d4)>
module @module {
  util.func public @conv_2d_float32_input_backward_128x24x48x384_nhwc_384x1x3x128_fhwc_nhwf_1x1s_0x1p_1x1d_3g$async(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view, %arg2: !hal.fence, %arg3: !hal.fence) -> !hal.buffer_view attributes {inlining_policy = #util.inline.never, iree.abi.model = "coarse-fences", iree.abi.stub, preprocessing_pipeline = #util.preprocessing_pipeline<"iree-preprocessing-make-single-dispatch">} {
    %cst = arith.constant 0.000000e+00 : f32
    %c2 = arith.constant 2 : index
    %0 = hal.tensor.import wait(%arg2) => %arg0 : !hal.buffer_view -> tensor<128x24x48x384xf32>
    %1 = hal.tensor.import wait(%arg2) => %arg1 : !hal.buffer_view -> tensor<384x1x3x128xf32>
    %expanded = tensor.expand_shape %0 [[0], [1], [2], [3, 4]] output_shape [128, 24, 48, 3, 128] : tensor<128x24x48x384xf32> into tensor<128x24x48x3x128xf32>
    %expanded_0 = tensor.expand_shape %1 [[0, 1], [2], [3], [4]] output_shape [3, 128, 1, 3, 128] : tensor<384x1x3x128xf32> into tensor<3x128x1x3x128xf32>
    %2 = tensor.empty() : tensor<3x128x1x3x128xf32>
    %3 = linalg.fill ins(%cst : f32) outs(%2 : tensor<3x128x1x3x128xf32>) -> tensor<3x128x1x3x128xf32>
    %4 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel"]} ins(%expanded_0 : tensor<3x128x1x3x128xf32>) outs(%3 : tensor<3x128x1x3x128xf32>) {
    ^bb0(%in: f32, %out: f32):
      %10 = linalg.index 0 : index
      %11 = linalg.index 1 : index
      %12 = linalg.index 2 : index
      %13 = linalg.index 3 : index
      %14 = linalg.index 4 : index
      %15 = arith.subi %c2, %13 : index
      %extracted = tensor.extract %expanded_0[%10, %11, %12, %15, %14] : tensor<3x128x1x3x128xf32>
      linalg.yield %extracted : f32
    } -> tensor<3x128x1x3x128xf32>
    %padded = tensor.pad %expanded low[0, 0, 1, 0, 0] high[0, 0, 1, 0, 0] {
    ^bb0(%arg4: index, %arg5: index, %arg6: index, %arg7: index, %arg8: index):
      tensor.yield %cst : f32
    } : tensor<128x24x48x3x128xf32> to tensor<128x24x50x3x128xf32>
    %5 = tensor.empty() : tensor<128x24x48x3x128xf32>
    %6 = linalg.fill ins(%cst : f32) outs(%5 : tensor<128x24x48x3x128xf32>) -> tensor<128x24x48x3x128xf32>
    %7 = linalg.generic {indexing_maps = [#map1, #map2, #map3], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel", "reduction", "reduction", "reduction"]} ins(%padded, %4 : tensor<128x24x50x3x128xf32>, tensor<3x128x1x3x128xf32>) outs(%6 : tensor<128x24x48x3x128xf32>) {
    ^bb0(%in: f32, %in_1: f32, %out: f32):
      %10 = arith.mulf %in, %in_1 : f32
      %11 = arith.addf %out, %10 : f32
      linalg.yield %11 : f32
    } -> tensor<128x24x48x3x128xf32>
    %collapsed = tensor.collapse_shape %7 [[0], [1], [2], [3, 4]] : tensor<128x24x48x3x128xf32> into tensor<128x24x48x384xf32>
    %8 = hal.tensor.barrier join(%collapsed : tensor<128x24x48x384xf32>) => %arg3 : !hal.fence
    %9 = hal.tensor.export %8 : tensor<128x24x48x384xf32> -> !hal.buffer_view
    util.return %9 : !hal.buffer_view
  }
  util.func public @conv_2d_float32_input_backward_128x24x48x384_nhwc_384x1x3x128_fhwc_nhwf_1x1s_0x1p_1x1d_3g(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub} {
    %0 = util.null : !hal.fence
    %c-1_i32 = arith.constant -1 : i32
    %c0 = arith.constant 0 : index
    %device_0 = hal.devices.get %c0 : !hal.device
    %fence = hal.fence.create device(%device_0 : !hal.device) flags("None") : !hal.fence
    %1 = util.call @conv_2d_float32_input_backward_128x24x48x384_nhwc_384x1x3x128_fhwc_nhwf_1x1s_0x1p_1x1d_3g$async(%arg0, %arg1, %0, %fence) : (!hal.buffer_view, !hal.buffer_view, !hal.fence, !hal.fence) -> !hal.buffer_view
    %status = hal.fence.await until([%fence]) timeout_millis(%c-1_i32) flags("None") : i32
    util.return %1 : !hal.buffer_view
  }
}
```

### Steps to reproduce your issue

Try to compile both examples with

```
iree-compile --iree-hal-target-backends=rocm --iree-hip-target=gfx942
```

### What component(s) does this issue relate to?

Compiler

### Version information

pip install:

iree-base-compiler  3.4.0rc20250408

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rkayaith**
This adds support for converting group convs to im2col, allowing them to go down the IGEMM path.

Group dimensions are parallel iterator dims that index into the image, filter, and output. For im2col they are treated as a batch dimension.

This also fixes #20498

### CODE REVIEW

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp [hunk 1]
```diff
@@ -79,37 +79,36 @@ static void collectDimExprs(ArrayRef<AffineExpr> exprs,
...
 // Computes `inputKPerm` that maps the input spatial and channel dimension order
 // to filter's.
-static SmallVector<int64_t> computeInputKPerm(AffineMap inputMap,
-                                              AffineMap filterMap) {
-  DenseSet<AffineExpr> inputDimsSet;
-  DenseSet<AffineExpr> filterDimsSet;
-  collectDimExprs(inputMap.getResults(), inputDimsSet);
-  collectDimExprs(filterMap.getResults(), filterDimsSet);
-
-  // Get shared dims from input and filter in order of appearance.
```
Comment (rkayaith) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp:89]: The previous logic included dimensions shared between the input and filter, but group dimensions are included in that and we don't want them here.

**Comment by rkayaith** [comment]
On MI300X this results in a ~90% reduction in execution time on a number of configurations (benchmarked using [boo_driver](https://github.com/iree-org/iree-turbine/blob/main/iree/turbine/kernel/boo/conv_exports/boo_driver.py)):
```
convbfp16 -n 2 -c 896 -H 59 -W 91 -k 896 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 16 -F 1 -t 1              -5033.66 (-94.3%)
convbfp16 -n 2 -c 448 -H 118 -W 182 -k 448 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 8 -F 1 -t 1             -9760.99 (-91.4%)
convbfp16 -n 2 -c 224 -H 470 -W 725 -k 224 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 4 -F 1 -t 1             -11450.01 (-93.5%)
convbfp16 -n 2 -c 224 -H 235 -W 363 -k 224 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 4 -F 1 -t 1             -11380.67 (-94.2%)
convbfp16 -n 2 -c 448 -H 235 -W 363 -k 448 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 8 -F 1 -t 1             -9761.35 (-90.8%)
convbfp16 -n 2 -c 896 -H 118 -W 182 -k 896 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 16 -F 1 -t 1            -5039.59 (-93.7%)
convbfp16 -n 2 -c 2016 -H 59 -W 91 -k 2016 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 36 -F 1 -t 1            -1504.16 (-84.7%)
```

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp [hunk 2]
```diff
@@ -79,37 +79,36 @@ static void collectDimExprs(ArrayRef<AffineExpr> exprs,
 
 // Computes `inputKPerm` that maps the input spatial and channel dimension order
 // to filter's.
-static SmallVector<int64_t> computeInputKPerm(AffineMap inputMap,
-                                              AffineMap filterMap) {
-  DenseSet<AffineExpr> inputDimsSet;
-  DenseSet<AffineExpr> filterDimsSet;
-  collectDimExprs(inputMap.getResults(), inputDimsSet);
```
Comment (nirvedhmeshram) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp:86]: I think this function is unused now, and can be removed?

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp [hunk 3]
```diff
@@ -79,37 +79,36 @@ static void collectDimExprs(ArrayRef<AffineExpr> exprs,
...
-    });
+    }
   }
-  for (AffineExpr expr : filterMap.getResults()) {
-    expr.walk([&](AffineExpr dimExpr) {
-      if (inputDimsSet.contains(dimExpr)) {
-        filterSharedDims.push_back(dimExpr);
+  SmallVector<int64_t> filterReductionDims;
+  for (auto dimExpr : filterMap.getResults()) {
+    for (auto reductionDim : reductionDims) {
```
Comment (yzhang93) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp]: Nit: concrete type is preferrable than auto.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir [hunk 4]
```diff
@@ -453,3 +453,75 @@ util.func public @conv_1d_nhc_chf(%arg0: tensor<1x3x2xf32>, %arg1: tensor<2x2x2x
...
+// CHECK-DAG:  #[[OUT_MAP:.+]] = affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4)>
+// CHECK:      util.func public @conv_2d_nhwgc_gfhwc(
+// CHECK-SAME:   %[[IMG:.+]]: [[IMG_T:tensor<1x10x10x7x4xf32>]]
+// CHECK-SAME:   %[[FIL:.+]]: [[FIL_T:tensor<7x16x3x3x4xf32>]]
+// CHECK-SAME:   %[[OUT:.+]]: [[OUT_T:tensor<1x8x8x7x16xf32>]]
+// CHECK:      %[[EMPTY:.+]] = tensor.empty() : [[LHS_T:tensor<7x1x8x8x36xf32>]]
+// CHECK:      %[[IM2COL:.+]] = iree_linalg_ext.im2col
+// CHECK-SAME:   strides = [1, 1] dilations = [1, 1] kernel_size = [3, 3]
+// CHECK-SAME:   m_offset = [0, 0] * [8, 1] k_offset = [0] * [1]
+// CHECK-SAME:   batch_pos = [3, 0] m_pos = [1, 2] k_pos = [4]
```
Comment (nirvedhmeshram) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir]: I am wondering why the group dimension is bubbled out like this to the front, to me doing [0,3] seems more natural.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir [hunk 5]
```diff
@@ -453,3 +453,75 @@ util.func public @conv_1d_nhc_chf(%arg0: tensor<1x3x2xf32>, %arg1: tensor<2x2x2x
...
+// -----
+
+util.func public @conv_2d_nhwgc_gfhwc(%arg0: tensor<1x10x10x7x4xf32>, %arg1: tensor<7x16x3x3x4xf32>, %arg2: tensor<1x8x8x7x16xf32>) -> tensor<1x8x8x7x16xf32> {
+  %0 = linalg.conv_2d_nhwgc_gfhwc
+    {dilations = dense<1> : tensor<2xi64>, strides = dense<1> : tensor<2xi64> }
+     ins(%arg0, %arg1: tensor<1x10x10x7x4xf32>, tensor<7x16x3x3x4xf32>)
+    outs(%arg2: tensor<1x8x8x7x16xf32>) -> tensor<1x8x8x7x16xf32>
+  util.return %0 : tensor<1x8x8x7x16xf32>
+}
+// CHECK-DAG:  #[[LHS_MAP:.+]] = affine_map<(d0, d1, d2, d3, d4, d5) -> (d3, d0, d1, d2, d5)>
```
Comment (nirvedhmeshram) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir]: would be nice to have the annotations on the dims like the other tests as it takes some time to infer each.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir [hunk 6]
```diff
@@ -453,3 +453,75 @@ util.func public @conv_1d_nhc_chf(%arg0: tensor<1x3x2xf32>, %arg1: tensor<2x2x2x
...
+// CHECK-SAME:   ins(%[[IMG]] : [[IMG_T]])
+// CHECK-SAME:   outs(%[[EMPTY]] : [[LHS_T]])
+// CHECK-DAG:  %[[COLLAPSED:.+]] = tensor.collapse_shape %[[FIL]] {{\[}}[0], [1], [2, 3, 4]] : [[FIL_T]] into [[RHS_T:tensor<7x16x36xf32>]]
+// CHECK:      %[[MATMUL:.+]] = linalg.generic
+// CHECK-SAME:   indexing_maps = [#[[LHS_MAP]], #[[RHS_MAP]], #[[OUT_MAP]]]
+// CHECK-SAME:   iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel", "reduction"]
+// CHECK-SAME:   ins(%[[IM2COL]], %[[COLLAPSED]] : [[LHS_T]], [[RHS_T]])
+// CHECK-SAME:   outs(%[[OUT]] : [[OUT_T]]) {
+// CHECK:          arith.mulf
+// CHECK:          arith.addf
```
Comment (yzhang93) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir]: Nit: these checks are not needed.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp [hunk 7]
```diff
@@ -211,18 +210,18 @@ class ConvertConvGeneric final
...
+    auto im2colBatchIterDims =
+        llvm::to_vector(llvm::concat<unsigned>(convDims.depth, convDims.batch));
+    SmallVector<int64_t> batchPos(im2colBatchIterDims.size());
+    for (auto dim : im2colBatchIterDims) {
+      auto dimExpr = getAffineDimExpr(dim, inputMap.getContext());
+      int64_t im2colInputDim = inputMap.getResultPosition(dimExpr).value();
+      int64_t igemmInputDim = igemmConvDetails.getIgemmInputImageMap()
+                                  .getResultPosition(dimExpr)
+                                  .value();
+      batchPos[igemmInputDim] = im2colInputDim;
```
Comment (nirvedhmeshram) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp:211]: Is this relying on say a dim like "d3" in the original map stays d3 in the new map. Wondering if this is a fairly safe assumption and if not should we guard against a wrong mapping if that doesnt happen.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir [hunk 8]
```diff
@@ -453,3 +453,75 @@ util.func public @conv_1d_nhc_chf(%arg0: tensor<1x3x2xf32>, %arg1: tensor<2x2x2x
...
+// -----
+
+util.func public @conv_2d_ngchw_fgchw(%arg0: tensor<1x7x4x10x10xf32>, %arg1: tensor<16x7x4x3x3xf32>, %arg2: tensor<1x7x16x8x8xf32>) -> tensor<1x7x16x8x8xf32> {
+  %0 = linalg.conv_2d_ngchw_fgchw
+    {dilations = dense<1> : tensor<2xi64>, strides = dense<1> : tensor<2xi64> }
+     ins(%arg0, %arg1: tensor<1x7x4x10x10xf32>, tensor<16x7x4x3x3xf32>)
+    outs(%arg2: tensor<1x7x16x8x8xf32>) -> tensor<1x7x16x8x8xf32>
+  util.return %0 : tensor<1x7x16x8x8xf32>
+}
+// og filter map (x0, x1, x2, x3, x4, x5) -> ()
```
Comment (yzhang93) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir]: What's the meaning of this line?

**Review by nirvedhmeshram — COMMENTED** [review]
Nice work! I have a few minor questions and comments.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir (hunk 4 above)
Comment (rkayaith) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir]: It's trivial to change, I can put the batch dims first if preferred. Does this materially affect the code generation? I was curious if this affects performance but in my earlier tests it didn't.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir [hunk 9]
```diff
@@ -453,3 +453,75 @@ util.func public @conv_1d_nhc_chf(%arg0: tensor<1x3x2xf32>, %arg1: tensor<2x2x2x
...
+  util.return %0 : tensor<1x8x8x7x16xf32>
+}
+// CHECK-DAG:  #[[LHS_MAP:.+]] = affine_map<(d0, d1, d2, d3, d4, d5) -> (d3, d0, d1, d2, d5)>
+// CHECK-DAG:  #[[RHS_MAP:.+]] = affine_map<(d0, d1, d2, d3, d4, d5) -> (d3, d4, d5)>
+// CHECK-DAG:  #[[OUT_MAP:.+]] = affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4)>
+// CHECK:      util.func public @conv_2d_nhwgc_gfhwc(
+// CHECK-SAME:   %[[IMG:.+]]: [[IMG_T:tensor<1x10x10x7x4xf32>]]
+// CHECK-SAME:   %[[FIL:.+]]: [[FIL_T:tensor<7x16x3x3x4xf32>]]
+// CHECK-SAME:   %[[OUT:.+]]: [[OUT_T:tensor<1x8x8x7x16xf32>]]
+// CHECK:      %[[EMPTY:.+]] = tensor.empty() : [[LHS_T:tensor<7x1x8x8x36xf32>]]
```
Comment (yzhang93) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir]: Does it require the `g dimension` to be in front? Does it work when the `n dimension` is larger than 1? It's better to modify either of these two tests to cover a case that n>1.

**Review by yzhang93 — COMMENTED** [review]
Overall LGTM. Just some minor comments.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir (hunk 4 above)
Comment (nirvedhmeshram) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir]: I think it creates a transpose access pattern when writing the results back, it might matter if we start doing something fancy there but you are right might not make a difference now but lets change to [0,3] so atleast we tried to keep the dimensions in the same sequence within the limits of what im2col needs which is (batch,M,reductions)

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp (hunk 7 above)
Comment (rkayaith) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp:211]: good point, I think with `linalg.generic` it should be possible to come up with a case where they don't match. let me try and come up with a test+fix

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir (hunk 8 above)
Comment (rkayaith) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir]: oops, that shouldn't have been committed

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir (hunk 4 above)
Comment (rkayaith) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir]: I've changed the ordering here: 97e70b2ded8789fb84886ac27c192f2308a8b6ea

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp (hunk 7 above)
Comment (rkayaith) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp:211]: I've fixed this here by including the dimension mapping in `igemmConvDetails` and using that to map to the correct dimension: https://github.com/iree-org/iree/pull/20611/commits/9f5a51c016423c58b170182b4bf9ff7118b84737

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir (hunk 9 above)
Comment (rkayaith) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir]: the dimension order and size doesn't matter. I've updated the tests to use a non-unit batch size

**Review by nirvedhmeshram — APPROVED** [review]
LGTM

**Review by yzhang93 — APPROVED** [review]
Thanks for the changes and improvement! LGTM.
