### PR TITLE
[spirv] Fix element extraction order when breaking down vectors

### LINKED ISSUE #14739: [spirv] Incorrect int4 vicuna model output
### What happened?

Vicuna int4 model outputs are different compared to fake_int8 model (int4 weights in int8 container). The results begin diverging from [dispatch 5](https://storage.googleapis.com/shark-public/vivian/vicuna_i4/module_forward_dispatch_5.mlir).

Build is based on https://github.com/openxla/iree/commit/afc8705fd527680905c9b84c5e06f8cca8051377

### Steps to reproduce your issue

1. Download model [second_vicuna_int4.mlir](https://storage.googleapis.com/shark_tank/vicuna/unsharded/mlir/second_vicuna_int4.mlir).
2. Commands to reproduce:
`./iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=false --iree-util-zero-fill-elided-attrs --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false --iree-vulkan-target-triple=rdna3-unknown-linux --iree-opt-const-expr-hoisting=false --iree-consteval-jit-debug=true ~/Downloads/second_vicuna_int4.mlir -o vicuna_vulkan_i4.vmfb --iree-stream-resource-max-allocation-size=3221225472 --iree-flow-break-dispatch=@forward:5`

`./iree-run-module --device_allocator=caching --vulkan_vma_allocator=false --module=vicuna_vulkan_i4.vmfb --device=vulkan --function=forward --input=1x1xi64 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32  --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --output=@vulkan_dispatch5.npy
`

3. The results I got for dispatch 5 from the above commands: https://storage.googleapis.com/shark-public/vivian/vicuna_i4/vulkan_dispatch5.npy
4. Golden results for comparison: https://storage.googleapis.com/shark-public/vivian/vicuna_i4/vulkan_dispatch5_golden.npy

### PR DESCRIPTION
**Pull request by antiagainst**
Assuming little-endian style encoding of the sub-byte elements, for 8xi4 [A, B, C, D, E, F, G, H], they are stored in memory as [BA, DC, FE, HG], and read as an i32 HGFEDCBA. Therefore the first i4 element is the lest significant 4 bits, and such.

Fixes https://github.com/openxla/iree/issues/14739

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/SPIRV/SPIRVBreakDownLargeVector.cpp [hunk 1]
```diff
@@ -99,11 +103,12 @@ struct BreakDownCastExtractExtend final : OpRewritePattern<arith::ExtUIOp> {
         extractOp.getLoc(), extOp.getType(),
         rewriter.getZeroAttr(extOp.getType()));
 
+    // Extract each elements assuming little-endian style encoding.
```
Comment (stellaraccident) [inline compiler/src/iree/compiler/Codegen/SPIRV/SPIRVBreakDownLargeVector.cpp]: Can't comment on an unchanged line:

```
    if (extractSrcType.getNumElements() <= 4)
      return failure();
```

I'm not convinced that this bit extraction is correct for all bit widths and packings, but I think it will work for POT widths. Wdyt about tightening up this condition so that it only allows the cases tested, and leave a TODO/revisit for other bit widths? Maybe add this to our list of debt to evaluate.

**Review by stellaraccident — APPROVED** [review]
Thanks. Left a comment about how we may want to followup on this.

File: compiler/src/iree/compiler/Codegen/SPIRV/SPIRVBreakDownLargeVector.cpp (hunk 1 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/SPIRV/SPIRVBreakDownLargeVector.cpp]: This is accounted for in the upstream type emulation pass. So we probably want to just use that as a way to do all emulation.

**Comment by MaheshRavishankar** [comment]
> Assuming little-endian style encoding of the sub-byte elements, for 8xi4 [A, B, C, D, E, F, G, H], they are stored in memory as [BA, DC, FE, HG], and read as an i32 HGFEDCBA. Therefore the first i4 element is the lest significant 4 bits, and such.
> 

I think the reading of i32 where you get "HGFEDCBA" is actually using big endian all the way. 

EDIT: NM this is right.

File: compiler/src/iree/compiler/Codegen/SPIRV/SPIRVBreakDownLargeVector.cpp (hunk 1 above)
Comment (antiagainst) [reply compiler/src/iree/compiler/Codegen/SPIRV/SPIRVBreakDownLargeVector.cpp]: > I think it will work for POT widths.

What does "POT" mean here?

> Wdyt about tightening up this condition so that it only allows the cases tested, and leave a TODO/revisit for other bit widths? Maybe add this to our list of debt to evaluate.

> This is accounted for in the upstream type emulation pass. So we probably want to just use that as a way to do all emulation.

Yes we can tighten this pattern for now and take another look later. I added this pattern earlier because the whole picture is rather complicated. To do it in the most proper way, we need to consider a few things:
* How to emulate i4 types itself. In SPIR-V different bitwidth types require different capabilities. i8/i16 is so. i32 is always there; but it would mean that we see i32 -> 8xi4. Then that comes to the issue of:
* How to handle large vectors with more than 4 elements. Need an lowering pattern for vector.bitcast for such cases, which is missing right now. Even after adding it, all following vector ops involving vector<8xi4> needs to be lowered properly. Which comes to--
* How to sequence various vector patterns. There are lots and it's a long standing issue of difficulties to properly organize them together.
* We can try to avoid generating large vectors if possible. But it needs more thinking on how to have various patterns to work together..
* etc.

Comment (stellaraccident) [reply compiler/src/iree/compiler/Codegen/SPIRV/SPIRVBreakDownLargeVector.cpp]: Sorry. Power of two
