### PR TITLE
Remove bf16 buffer operations for all backends

### LINKED ISSUE #13499: LLVM-CPU Backend Fails on BF16 truncation that should be legal
The following program fails compilation with llvm-cpu due to a `__truncsfbf2` operation being generated. This is likely due to LLVM introducing bf16 operations that should not exist. The `llvm` backend appears to insert these operations during optimization. We should rework the lowering to guarantee no `bf16` operations are created. This can likely be done by guaranteeing `hal.interface.binding.subspan` just treats the `bf16` values as `i16`

```
module @jit_median attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<7xbf16> {jax.arg_info = "a", mhlo.sharding = "{replicated}"}) -> (tensor<1xbf16> {jax.result_info = ""}) {
    %0 = stablehlo.constant dense<5.000000e-01> : tensor<f32>
    %1 = call @quantile(%arg0, %0) : (tensor<7xbf16>, tensor<f32>) -> tensor<1xbf16>
    return %1 : tensor<1xbf16>
  }
  func.func private @quantile(%arg0: tensor<7xbf16>, %arg1: tensor<f32>) -> tensor<1xbf16> {
    %0 = call @isnan(%arg0) : (tensor<7xbf16>) -> tensor<7xi1>
    %1 = stablehlo.constant dense<false> : tensor<i1>
    %2 = stablehlo.reduce(%0 init: %1) across dimensions = [0] : (tensor<7xi1>, tensor<i1>) -> tensor<i1>
     reducer(%arg2: tensor<i1>, %arg3: tensor<i1>)  {
      %33 = stablehlo.or %arg2, %arg3 : tensor<i1>
      stablehlo.return %33 : tensor<i1>
    }
    %3 = stablehlo.broadcast_in_dim %2, dims = [] : (tensor<i1>) -> tensor<1xi1>
    %4 = stablehlo.constant dense<0x7FC00000> : tensor<f32>
    %5 = call @_where(%3, %4, %arg0) : (tensor<1xi1>, tensor<f32>, tensor<7xbf16>) -> tensor<7xbf16>
    %6 = "stablehlo.sort"(%5) ({
    ^bb0(%arg2: tensor<bf16>, %arg3: tensor<bf16>):
      %33 = stablehlo.convert %arg2 : (tensor<bf16>) -> tensor<f32>
      %34 = stablehlo.bitcast_convert %33 : (tensor<f32>) -> tensor<i32>
      %35 = stablehlo.bitcast_convert %33 : (tensor<f32>) -> tensor<ui32>
      %36 = stablehlo.constant dense<0.000000e+00> : tensor<f32>
      %37 = stablehlo.compare  EQ, %33, %36,  FLOAT : (tensor<f32>, tensor<f32>) -> tensor<i1>
      %38 = stablehlo.constant dense<0> : tensor<i32>
      %39 = stablehlo.select %37, %38, %34 : tensor<i1>, tensor<i32>
      %40 = stablehlo.compare  NE, %33, %33,  FLOAT : (tensor<f32>, tensor<f32>) -> tensor<i1>
      %41 = stablehlo.constant dense<2143289344> : tensor<i32>
      %42 = stablehlo.select %40, %41, %39 : tensor<i1>, tensor<i32>
      %43 = stablehlo.constant dense<2147483647> : tensor<ui32>
      %44 = stablehlo.subtract %43, %35 : tensor<ui32>
      %45 = stablehlo.bitcast_convert %44 : (tensor<ui32>) -> tensor<i32>
      %46 = stablehlo.constant dense<0> : tensor<i32>
      %47 = stablehlo.compare  LT, %42, %46,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1>
      %48 = stablehlo.select %47, %45, %42 : tensor<i1>, tensor<i32>
      %49 = stablehlo.convert %arg3 : (tensor<bf16>) -> tensor<f32>
      %50 = stablehlo.bitcast_convert %49 : (tensor<f32>) -> tensor<i32>
      %51 = stablehlo.bitcast_convert %49 : (tensor<f32>) -> tensor<ui32>
      %52 = stablehlo.constant dense<0.000000e+00> : tensor<f32>
      %53 = stablehlo.compare  EQ, %49, %52,  FLOAT : (tensor<f32>, tensor<f32>) -> tensor<i1>
      %54 = stablehlo.constant dense<0> : tensor<i32>
      %55 = stablehlo.select %53, %54, %50 : tensor<i1>, tensor<i32>
      %56 = stablehlo.compare  NE, %49, %49,  FLOAT : (tensor<f32>, tensor<f32>) -> tensor<i1>
      %57 = stablehlo.constant dense<2143289344> : tensor<i32>
      %58 = stablehlo.select %56, %57, %55 : tensor<i1>, tensor<i32>
      %59 = stablehlo.constant dense<2147483647> : tensor<ui32>
      %60 = stablehlo.subtract %59, %51 : tensor<ui32>
      %61 = stablehlo.bitcast_convert %60 : (tensor<ui32>) -> tensor<i32>
      %62 = stablehlo.constant dense<0> : tensor<i32>
      %63 = stablehlo.compare  LT, %58, %62,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1>
      %64 = stablehlo.select %63, %61, %58 : tensor<i1>, tensor<i32>
      %65 = stablehlo.compare  LT, %48, %64,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1>
      stablehlo.return %65 : tensor<i1>
    }) {dimension = 0 : i64, is_stable = true} : (tensor<7xbf16>) -> tensor<7xbf16>
    %7 = stablehlo.constant dense<7.000000e+00> : tensor<f32>
    %8 = stablehlo.constant dense<1.000000e+00> : tensor<f32>
    %9 = stablehlo.subtract %7, %8 : tensor<f32>
    %10 = stablehlo.multiply %arg1, %9 : tensor<f32>
    %11 = stablehlo.floor %10 : tensor<f32>
    %12 = stablehlo.ceil %10 : tensor<f32>
    %13 = stablehlo.constant dense<7.000000e+00> : tensor<f32>
    %14 = stablehlo.constant dense<1.000000e+00> : tensor<f32>
    %15 = stablehlo.subtract %13, %14 : tensor<f32>
    %16 = stablehlo.constant dense<0.000000e+00> : tensor<f32>
    %17 = stablehlo.clamp %16, %11, %15 : tensor<f32>
    %18 = stablehlo.constant dense<7.000000e+00> : tensor<f32>
    %19 = stablehlo.constant dense<1.000000e+00> : tensor<f32>
    %20 = stablehlo.subtract %18, %19 : tensor<f32>
    %21 = stablehlo.constant dense<0.000000e+00> : tensor<f32>
    %22 = stablehlo.clamp %21, %12, %20 : tensor<f32>
    %23 = stablehlo.convert %17 : (tensor<f32>) -> tensor<i32>
    %24 = stablehlo.convert %22 : (tensor<f32>) -> tensor<i32>
    %25 = stablehlo.broadcast_in_dim %23, dims = [] : (tensor<i32>) -> tensor<1xi32>
    %26 = "stablehlo.gather"(%6, %25) {dimension_numbers = #stablehlo.gather<offset_dims = [0], start_index_map = [0]>, indices_are_sorted = false, slice_sizes = dense<1> : tensor<1xi64>} : (tensor<7xbf16>, tensor<1xi32>) -> tensor<1xbf16>
    %27 = stablehlo.broadcast_in_dim %24, dims = [] : (tensor<i32>) -> tensor<1xi32>
    %28 = "stablehlo.gather"(%6, %27) {dimension_numbers = #stablehlo.gather<offset_dims = [0], start_index_map = [0]>, indices_are_sorted = false, slice_sizes = dense<1> : tensor<1xi64>} : (tensor<7xbf16>, tensor<1xi32>) -> tensor<1xbf16>
    %29 = stablehlo.add %26, %28 : tensor<1xbf16>
    %30 = stablehlo.constant dense<5.000000e-01> : tensor<bf16>
    %31 = stablehlo.broadcast_in_dim %30, dims = [] : (tensor<bf16>) -> tensor<1xbf16>
    %32 = stablehlo.multiply %29, %31 : tensor<1xbf16>
    return %32 : tensor<1xbf16>
  }
  func.func private @isnan(%arg0: tensor<7xbf16>) -> tensor<7xi1> {
    %0 = stablehlo.compare  NE, %arg0, %arg0,  FLOAT : (tensor<7xbf16>, tensor<7xbf16>) -> tensor<7xi1>
    return %0 : tensor<7xi1>
  }
  func.func private @_where(%arg0: tensor<1xi1>, %arg1: tensor<f32>, %arg2: tensor<7xbf16>) -> tensor<7xbf16> {
    %0 = stablehlo.convert %arg1 : (tensor<f32>) -> tensor<bf16>
    %1 = stablehlo.reshape %arg0 : (tensor<1xi1>) -> tensor<i1>
    %2 = stablehlo.broadcast_in_dim %1, dims = [] : (tensor<i1>) -> tensor<7xi1>
    %3 = stablehlo.broadcast_in_dim %0, dims = [] : (tensor<bf16>) -> tensor<7xbf16>
    %4 = stablehlo.select %2, %3, %arg2 : tensor<7xi1>, tensor<7xbf16>
    return %4 : tensor<7xbf16>
  }
}
```

### PR DESCRIPTION
**Pull request by rsuderman**
LLVM support for BF16 operations (even memory operations) are not
    always supported per-backend. We should investigate incrementally
    enabling BF16 on platforms with native LLVM support, however the
    initial version should aggressively support BF16 types through
    emulated behavior.
    
    This patch focuses on replacing all bf16 buffer operations with
    uint16 equivalents. this allows bf16 types to be converted to
    f32s before being cast back down. It removes any knowledge
    of bf16 from the LLVM backends.
    
    Some additions were needed for vectorized operations to the
    equivalent `f32` arith operations.

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp [hunk 1]
```diff
@@ -633,8 +633,9 @@ static void addLowerToLLVMPasses(OpPassManager &passManager) {
     passManager.addNestedPass<func::FuncOp>(
         createLLVMCPUEmitVectorizationRemarksPass());
   }
-  passManager.addPass(IREE::Util::createPromoteArithBF16ToF32Pass());
   passManager.addNestedPass<func::FuncOp>(createConvertLinalgToLoopsPass());
+  passManager.addPass(IREE::Util::createPromoteArithBF16ToF32Pass());
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp:637]: Confused about these two passes. The first one is promoting to f32, and then the second one is emulating it after promotion?

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp (hunk 1 above)
Comment (rsuderman) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp:637]: I should probably rename. One promotes all arithmetic/math operations from `bf16` to `f32`. The second replaces all vectorized loads / stores with `i16` equivalents to remove the `bf16` type from the LLVM backend. I had hoped that load/store operations of `bf16` would just translate to equivalent bit-lengths but unfortunately I was wrong.

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp:637]: Do you mind renaming this? I didnt know i16 was also implicated here (but thats because I dont understand bf16 and its emulation)

Comment (rsuderman) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp:637]: I renamed to better explain. The arith conversion handles the simulated arithmetic operations (now include `vector.reduce`) however the EmulateBF16 is focused on the buffer operations (loading, storing, subspan). Arguably it shouldn't be required as loading / storing bytes should not matter about the type being operated on, however LLVM apparently disagrees. It also enforces the expansion of `extf`-`truncf` for `bf16` types as starting as `int16` values.

This fix also now puts the `cuda` pipeline down the same path.

File: compiler/src/iree/compiler/Codegen/Common/ConvertBf16ToUInt16Buffers.cpp [hunk 2]
```diff
@@ -209,8 +258,8 @@ struct SPIRVEmulateBf16Pass final
 // Public interface
 //===----------------------------------------------------------------------===//
 
-std::unique_ptr<OperationPass<ModuleOp>> createSPIRVEmulateBf16Pass() {
-  return std::make_unique<SPIRVEmulateBf16Pass>();
+std::unique_ptr<OperationPass<ModuleOp>> createConvertBf16ToUInt16BuffersPass() {
+  return std::make_unique<ConvertBf16ToUInt16BuffersPass>();
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Codegen/Common/ConvertBf16ToUInt16Buffers.cpp]: bf16 to uint16 buffers? Why buffers pass?

**Review by MaheshRavishankar — APPROVED** [review]

File: compiler/src/iree/compiler/Codegen/Common/ConvertBf16ToUInt16Buffers.cpp (hunk 2 above)
Comment (rsuderman) [reply compiler/src/iree/compiler/Codegen/Common/ConvertBf16ToUInt16Buffers.cpp]: I thought buffers pass because its focused on converting buffer related operations. It could be ` `Bf16BuffersToUInt16Pass` or we can drop the `pass` part of the name. I am not invested heavily in the specific name.
