### PR TITLE
[CPU] Propagate scalable flags for compute Ops

### LINKED ISSUE #16334: [CPU][SVE] Compilation fails when scalable vectorization is enabled
Repro:

```
iree-compile --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-target-cpu-features="+sve,+neon" --iree-input-type=stablehlo --iree-llvmcpu-target-triple=aarch64-none-linux-android34 --compile-from=executable-sources test.mlir -o out.vmfb --iree-llvmcpu-enable-scalable-vectorization

hal.executable public @test {
  hal.executable.variant public @system_elf_arm_64 target(<"llvm-cpu", "system-elf-arm_64", {cpu = "", cpu_features = "+v9a,+sve", data_layout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128", link_embedded = false, native_vector_size = 16 : index, target_triple = "aarch64-none-linux-android34", ukernels = "none"}>) {
    hal.executable.export public @test ordinal(0) layout(#hal.pipeline.layout<push_constants = 5, sets = [<0, bindings = [<0, storage_buffer, ReadOnly>, <1, storage_buffer, ReadOnly>, <2, storage_buffer>]>]>) {
    ^bb0(%arg0: !hal.device):
      %x, %y, %z = flow.dispatch.workgroup_count_from_slice
      hal.return %x, %y, %z : index, index, index
    }
    builtin.module {
      func.func @test() {
        %c0_i32 = arith.constant 0 : i32
        %0 = hal.interface.constant.load[0] : i32
        %1 = hal.interface.constant.load[1] : i32
        %2 = hal.interface.constant.load[2] : i32
        %3 = hal.interface.constant.load[3] : i32
        %4 = hal.interface.constant.load[4] : i32
        %5 = arith.index_castui %0 : i32 to index
        %6 = arith.index_castui %1 : i32 to index
        %7 = arith.index_castui %2 : i32 to index
        %8 = arith.index_castui %3 : i32 to index
        %9 = arith.index_castui %4 : i32 to index
        %10 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%5) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<1024x256xi8>>
        %11 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%7) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<256x256xi8>>
        %12 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%6) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<1024xf32>>
        %13 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%8) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<256xf32>>
        %14 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%9) : !flow.dispatch.tensor<writeonly:tensor<1024x256xf32>>
        %15 = flow.dispatch.tensor.load %10, offsets = [0, 0], sizes = [1024, 256], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<1024x256xi8>> -> tensor<1024x256xi8>
        %16 = flow.dispatch.tensor.load %11, offsets = [0, 0], sizes = [256, 256], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<256x256xi8>> -> tensor<256x256xi8>
        %17 = flow.dispatch.tensor.load %12, offsets = [0], sizes = [1024], strides = [1] : !flow.dispatch.tensor<readonly:tensor<1024xf32>> -> tensor<1024xf32>
        %18 = flow.dispatch.tensor.load %13, offsets = [0], sizes = [256], strides = [1] : !flow.dispatch.tensor<readonly:tensor<256xf32>> -> tensor<256xf32>
        %19 = tensor.empty() : tensor<1024x256xf32>
        %20 = tensor.empty() : tensor<1024x256xi32>
        %21 = linalg.fill ins(%c0_i32 : i32) outs(%20 : tensor<1024x256xi32>) -> tensor<1024x256xi32>
        %22 = linalg.matmul ins(%15, %16 : tensor<1024x256xi8>, tensor<256x256xi8>) outs(%21 : tensor<1024x256xi32>) -> tensor<1024x256xi32>
        %23 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0)>, affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%22, %17, %18 : tensor<1024x256xi32>, tensor<1024xf32>, tensor<256xf32>) outs(%19 : tensor<1024x256xf32>) {
        ^bb0(%in: i32, %in_0: f32, %in_1: f32, %out: f32):
          %24 = arith.sitofp %in : i32 to f32
          %25 = arith.mulf %24, %in_0 : f32
          %26 = arith.mulf %25, %in_1 : f32
          linalg.yield %26 : f32
        } -> tensor<1024x256xf32>
        flow.dispatch.tensor.store %23, %14, offsets = [0, 0], sizes = [1024, 256], strides = [1, 1] : tensor<1024x256xf32> -> !flow.dispatch.tensor<writeonly:tensor<1024x256xf32>>
        return
      }
    }
  }
}
```

Error:
```
test.mlir:37:17: error: 'llvm.fmul' op inferred type(s) 'vector<[16]xf32>' are incompatible with return type(s) of operation 'vector<16xf32>'
          %25 = arith.mulf %24, %in_0 : f32
                ^
test.mlir:37:17: error: 'llvm.fmul' op failed to infer returned types
          %25 = arith.mulf %24, %in_0 : f32
                ^
test.mlir:37:17: note: see current operation: %355 = "llvm.fmul"(%340, %326) <{fastmathFlags = #llvm.fastmath<none>}> : (vector<[16]xf32>, vector<16xf32>) -> vector<16xf32>
```

We may also extend the verifier of `vector.broadcast` as the following illegal broadcast is not caught:
```
    %146 = vector.broadcast %145 : vector<8x[16]xf32> to vector<8x16xf32>                                                                                                          
```

### PR DESCRIPTION
**Pull request by banach-space**
Makes sure that when computing the lowering config for compute Ops
(based on the corresponding root Op), scalable flags for tile sizes are
propagated correctly.

There's a few caveats:
  * ATM IREE will only use scalable sizes for linalg.matmul, hence
    testing is limited to that Op (i.e. we can't really use other Ops as
    the root Op),
  * As DT is not yet available for scalable vectors, updates for
    tensor.pack are left as a TODO.

In the forthcoming patches we will gradually make other Ops ready for
scalable vectors and update the tests accordingly.

In addition, a couple of extra debug logs are added and missing CHECK
lines restored (those were accidentally omitted in #16322)

Fixes #16334.

### CODE REVIEW

**Comment by banach-space** [comment]
cc @c-rhodes

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 1]
```diff
@@ -2407,19 +2427,27 @@ setLoweringConfigForComputeOps(mlir::FunctionOpInterface entryPointFn,
             } else {
               tileSizesList.push_back(zeros);
             }
+            // ATM Assume there are no scalable sizes for reduciton dims
```
Comment (dcaballe) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: reduciton

**Review by dcaballe — APPROVED** [review]
Thanks for the fix!

**Review by MaheshRavishankar — COMMENTED** [review]
I think it is best to wait for @hanhanW  to review this one.

**Review by hanhanW — CHANGES_REQUESTED** [review]
I will take a look in a couple days. Relying on lowering config to get scalable input_vector_size is still a red flag to me. I wonder what's the plan to infer them from IRs. Have we considered to teach ValueBoundsConstraintSet about it?

**Comment by dcaballe** [comment]
> I will take a look in a couple days. Relying on lowering config to get scalable input_vector_size is still a red flag to me. I wonder what's the plan to infer them from IRs. Have we considered to teach ValueBoundsConstraintSet about it?

Not sure I understand the concern. We use `lowering_config` to pass tile size information and scalable tile sizes have been supported for a while. We need that information not only for vectorization but also to apply scalable tiling. `ValueBoundsAnalysis` is an expensive analysis that we used in the past as a gas stopper when `lowering_config` was not in a good state but I not sure why we would use that analysis to try to infer the information from the IR when that information is already in `lowering_config` (now working properly).

**Comment by banach-space** [comment]
> I will take a look in a couple days. 

Thanks! Please, could you bump it on your list? This is quite a blocker for scalable vectorisation.

> Relying on lowering config to get scalable input_vector_size is still a red flag to me. I wonder what's the plan to infer them from IRs. 

To add to Diego's points, we have been using this mechanism to specify "scalable" flags since https://github.com/openxla/iree/pull/15108 (Oct 2023), so quite a while. I don't really recall anyone raising any concerns about that design, so this is rather surprising. Also, please note that this patch merely implements the existing design (this is not proposing anything new).

**Comment by MaheshRavishankar** [comment]
I think the concern is mostly about now all tiling configuration settings need to account for scalable vector sizes as well and it is not a "you dont need to know about it if you dont care about it" kind of thing. Now every tile size decision needs to account for scalable tile sizes. This is just an observation from someone sitting on the sidelines, and watching things here. 

To the original point, at some point I remember having a discussion (and agreement?) that we were going to rely on looking at the IR + target info to get the vector sizes (ideally on target info). It seems from your previous comment that this is not a direction this is headed in.  But looking at the PR itself, it seems its just adding to the propagation (which itself I dont think is a good idea, but it is what we do today). So that leads to the question of, now everything added to the tile size selection logic needs to account for scalability as we go forward, so thats an extra burden on the whole eco system.


What I am really curious about is, what was not working `lowering_config` and what changed to it now working. I am not sure I have a handle on what changed

**Comment by dcaballe** [comment]
Well, we have to deal with scalable vectors if we want to support them but, as Andrzej mentioned, that support in lowering config happened already in the past and there were no concerns. There are explicit field in `lowering_config` to hold this information.

I think the conclusion was that the translation unit approach wasn't feasible as multiple ops within the dispatch may need different tile sizes and have different tile levels. Instead, we decided to go from having one `lowering_config` per dispatch to having one `lowering_config` per op.  `ValueBoundsAnalysis` was actually covering some bugs related to `lowering_config` and pack/unpack ops. We were putting the wrong information in `lowering_config` and luckily not using it. We moved to a much better state once that was fixed and I think that's the direction that we ended up following. Hopefully this provides more context although I think this is orthogonal to the problem discussed here.

The added complexity seems ok to me as we evolve the system to support more cases. Another example: we would need the concept of "tile size is multiple of X" or even dynamic tile sizes when using the number of threads at runtime to compute the tile sizes for distribution.

**Comment by banach-space** [comment]
Thanks for getting back to me! It's quite late for me, so replying briefly.

> I think the concern is mostly about now all tiling configuration settings need to account for scalable vector sizes as well and it is not a "you dont need to know about it if you dont care about it" kind of thing. Now every tile size decision needs to account for scalable tile sizes. 

That's a fair point, but it's the first time I'm hearing this feedback (I went through previous discussions and couldn't find anything related). Also, as I mentioned above, this PR merely implements the design that we have today.

Now that I understand your concern I know what needs fixing :) We can abstract this whole logic away in future PRs, that shouldn't be a problem.  In fact, we have been trying something similar in MLIR (re scalable vectors), but couldn't really agree on the right approach.

> To the original point, at some point I remember having a discussion (and agreement?) that we were going to rely on looking at the IR + target info to get the vector sizes (ideally on target info).

_Something_ at _some point_ needs to decide what dimension are suitable to be scalable and what dimension are not. Scalable vectors allow Vector Length Agnostic (VLA) programming, but that doesn't mean that any dimension can be scalable. There are various limitations (due to hardware and LLVM implementation) and also some configuration simply don't make sense (due to perf consideration). A compiler driver (IREE in this case) needs to make that decision.

Specifically, we cannot infer information from IR that's not present there. It's for the compiler driver to drive the compilation and to set these things up. As for target info, we know that for SVE we can only have 1 scalable dim and for SME we can have 2 scalable dims. For operations like `linalg.matmul` that have 3 dims that gives us 3 possibilities to choose from for both extensions (in practice only 1 option makes sense).

**Comment by MaheshRavishankar** [comment]
> Well, we have to deal with scalable vectors if we want to support them but, as Andrzej mentioned, that support in lowering config happened already in the past and there were no concerns. There are explicit field in `lowering_config` to hold this information.

Yes, they were added but they were "optional" fields. If you were on a path that wasnt related to SVE or SME, then you just ignore that field. 

> 
> I think the conclusion was that the translation unit approach wasn't feasible as multiple ops within the dispatch may need different tile sizes and have different tile levels. Instead, we decided to go from having one `lowering_config` per dispatch to having one `lowering_config` per op. `ValueBoundsAnalysis` was actually covering some bugs related to `lowering_config` and pack/unpack ops. We were putting the wrong information in `lowering_config` and luckily not using it. We moved to a much better state once that was fixed and I think that's the direction that we ended up following. Hopefully this provides more context although I think this is orthogonal to the problem discussed here.
> 

Different discussion for sure, but there is probably some nuance from the previous discussion missed here. Some things are for the whole dispatch. For example, tile and fuse is "common" for all operations. By common, I mean it only matters what the tiling for the consumer is, the same values at producers dont matter, they just get pulled in based on indexing maps. This need to be moved to the translation unit. For individual tiling decisions, yes those are operator specific, but we only need those for vectorization, and if we deduce them based on hardware you dont really need them to be in lowering config, but its OK if we need it. Those need to be per op..

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 2]
```diff
@@ -2372,17 +2383,26 @@ setLoweringConfigForComputeOps(mlir::FunctionOpInterface entryPointFn,
...
       // Build 4-level lowering configs for other ops.
       tileSizesList = {distTileSizes, commonVecTileSizes};
       SmallVector<int64_t> zeros(numLoops, 0);
+      SmallVector<bool> falseVec(numLoops, 0);
+      // No scalable tiling for the distribution
+      scalableTileFlagsList.push_back(falseVec);
+      scalableTileFlagsList.push_back(commonVecScalableTileFlags);
       TypeSwitch<Operation *>(op)
           .Case<tensor::PackOp>([&](auto packOp) {
+            // TODO: Handle scalable flags
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: Should we have an assertion? It sounds very bad if they are failed silently

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 3]
```diff
@@ -2407,19 +2427,27 @@ setLoweringConfigForComputeOps(mlir::FunctionOpInterface entryPointFn,
             } else {
               tileSizesList.push_back(zeros);
             }
+            // ATM Assume there are no scalable sizes for reduction dims
+            scalableTileFlagsList.push_back(falseVec);
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: Should this be an assertion?

**Review by hanhanW — APPROVED** [review]
The code looks okay to me. Thanks for the waiting.

> we have been using this mechanism to specify "scalable" flags since https://github.com/openxla/iree/pull/15108 (Oct 2023), so quite a while. I don't really recall anyone raising any concerns about that design, so this is rather surprising.

I was on vacation for ~1.5 month. It's landed when I was just back. I noticed it since early Dec, and I thought that it is an intermediate stage to unblock scalable vectorization. (my bad, sorry about that).

> Well, we have to deal with scalable vectors if we want to support them but, as Andrzej mentioned, that support in lowering config happened already in the past and there were no concerns. There are explicit field in lowering_config to hold this information.

Totally agree with this! I'm not asking to not land the PR, but I'd like to bring up the discussion. Otherwise, you'll hit other issues (and the potential solutions that I can think of are all read flags to me) I approved the PR to unblock compilation issue for now. But I think we should have a conclusion about the future direction.

> ValueBoundsAnalysis was actually covering some bugs related to lowering_config and pack/unpack ops. We were putting the wrong information in lowering_config and luckily not using it.

This looks like on an opposite side to me. The issue is that something is missing and we rely on `lowering_config`. IIRC, we did not have pad vectorization, and it was lowered to (maybe) linalg.fill + tensor.insert_slice. Some of the ops were not modeled by vectorizer, so there were failures. Relying on lowering_config is problematic, especially when there are decompositions in lowering pipeline. We don't have direct vectorization for pack/unpack at this moment, so lowering_config is not used for sure. We are just lucky that they are working without lowering_config, so ValueBoundsAnalysis can help on decomposed ops (i.e, pad + linalg.transpose in pack case).

My main concern is that we are putting burdens to all the decomposition patterns. Most of them live in upstream, and they don't know anything about lowering_config. You will ask all the developers to handle the lowering_config after every decomposition. So far we have three sets of ops in CPU pipeline:

1. All the convolution ops
2. All the pack ops
3. All the unpack ops

The decomposition patterns will convert the op to a sequence of tensor/linalg/arith/etc ops. Assigning lowering_confgis (based on the previous one) in the driver is very problematic to me. I imagine that there will be more decomposition patterns for other ops in the future based on my experience. I implemented pack/unpack vectorization patterns, but I got push back. There will be more complicated ops in the future, and might be decomposed. Re-iterating the lowering_config on those ops looks bad to me.

> Specifically, we cannot infer information from IR that's not present there. It's for the compiler driver to drive the compilation and to set these things up. 

So I really want to understand what's the actual issues. The lowering_config has the information about all the tiling. You also apply vector level of tiling on the operations. I believe that you can know which dimension is a scalable dim, and whis is not. If we can not get the information, why do we treat tiling specially for scalable tile sizes? I thought that they will generate different scf.for loops, so we should be able to gather some information. Can you share some IRs? What is missing in the IR?

We can discuss it either on the issue/PR, or one of Mai-Tai meeting after 2/18. (I'll be on vacation next week)

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp (hunk 2 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: Or maybe we can return failures?

Comment (banach-space) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: I'll add a failure, though it's going to be a bit awkward given that ATM this `TypeSwitch` doesn't return anything :)

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp (hunk 3 above)
Comment (banach-space) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: Assert would be tricky as we are simply not tracking this information yet. In fact, it will be much easier just to add it here and in other places where it's missing. Let me do that instead.

**Comment by banach-space** [comment]
> > Well, we have to deal with scalable vectors if we want to support them but, as Andrzej mentioned, that support in lowering config happened already in the past and there were no concerns. There are explicit field in `lowering_config` to hold this information.
> 
> Yes, they were added but they were "optional" fields. If you were on a path that wasnt related to SVE or SME, then you just ignore that field.
> 

While the "scalable flags" are always present, they default to `false`. In this sense they **are** optional. I'm not sure whether we can do better than that. Also, it is safe to ignore them for all targets not supporting scalable vectors.

> > ValueBoundsAnalysis was actually covering some bugs related to lowering_config and pack/unpack ops. We were putting the wrong information in lowering_config and luckily not using it.
> 
> This looks like on an opposite side to me. The issue is that something is missing and we rely on `lowering_config`. 

OK, this definitely requires more thought. I wasn't aware of these discussions.

> We can discuss it either on the issue/PR, or one of Mai-Tai meeting after 2/18. (I'll be on vacation next week)

The earliest I can do is 3/5. I'll add an item to the agenda so that we don't forget.

> Can you share some IRs? What is missing in the IR?

This will be pretty simple. We start with something like this:
```mlir
func.func @pipeline(%A: tensor<1020x1020xf32>, %B: tensor<1020x1020xf32>, %C: tensor<1020x1020xf32>) -> tensor<1020x1020xf32>{
  %1 = linalg.matmul ins(%A, %B: tensor<1020x1020xf32>, tensor<1020x1020xf32>)
            outs(%C: tensor<1020x1020xf32>) -> tensor<1020x1020xf32>
  return %1 : tensor<1020x1020xf32>
}
```
At what point should IREE select which dimension to tile using scalable sizes? ATM that comes from `lowering_config`.

> The code looks okay to me. Thanks for the waiting.

Thank you for reviewing 🙏🏻 This is very important and very timely for us! If there are no new comments, I'll land it tomorrow.
