### PR TITLE
[LLVMGPU] Support linalg.pack through LLVMGPUTileAndFuse

### LINKED ISSUE #20212: Slow compilation in `check_rocm_hip_pack.mlir_module.vmfb`
### What happened?

The https://github.com/iree-org/iree/blob/main/tests/e2e/tensor_ops/pack.mlir test is slow to compile, taking up to 90 seconds on my machine:
```
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.exe" --build d:/dev/projects/iree-build --config RelWithDebInfo --target iree_tests_e2e_tensor_ops_check_rocm_hip_pack.mlir_module --
[build] [1/2   0% :: 3.469] Re-checking globbed directories...
[build] [1/1 100% :: 83.962] Generating check_rocm_hip_pack.mlir_module.vmfb from pack.mlir
[driver] Build completed: 00:01:24.029
```

### Steps to reproduce your issue

1. Run compile command for the test:

    ```
    iree-compile \
      --output-format=vm-bytecode \
      --iree-hal-target-backends=rocm \
      --iree-hip-target=gfx1100
      tests/e2e/tensor_ops/pack.mlir \
      -o /dev/null
    ```

2. Observe slow performance

### What component(s) does this issue relate to?

_No response_

### Version information

https://github.com/iree-org/iree/commit/6eadf3df6f57a20283da8318f9178b0d92ae50eb

### Additional context

Originally discussed [here on Discord](https://discord.com/channels/689900678990135345/689906000043573354/1349050777410338858)

Here's a snippet of IR showing roughly what the compiler is working with: https://gist.github.com/ScottTodd/993d1b3007081e828bef0e6aab53274a

Screenshot of a trace: 

Image

Pack tests are generating larger programs than other tests in that folder (which matches the larger number of ops): 

Image

### PR DESCRIPTION
**Pull request by Max191**
Add lowering config selection logic for linalg.pack through LLVMGPUTileAndFuse, and remove the old LLVMGPUPackUnPack pipeline. Pack lowering configs are set similarly to other linalg ops going through TileAndFuse, because they are effectively just a linalg.transpose with a padded input.

fixes https://github.com/iree-org/iree/issues/20212

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 1]
```diff
@@ -544,9 +548,35 @@ static unsigned getRepresentativeBitWidth(linalg::LinalgOp linalgOp) {
   return 32;
 }
 
-LogicalResult setTileAndFuseLoweringConfig(IREE::GPU::TargetAttr target,
-                                           mlir::FunctionOpInterface entryPoint,
-                                           Operation *op) {
+static bool elementHasPowerOfTwoBitwidth(Value operand) {
+  Type elementType = getElementTypeOrSelf(operand.getType());
+  return isa<IntegerType, FloatType>(elementType) &&
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: nit: you can use `elementType.isIntOrFloat()`

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 2]
```diff
@@ -2549,10 +2500,6 @@ static LogicalResult setRootConfig(IREE::GPU::TargetAttr target,
         LDBG("Winograd Config");
         return setWinogradOpConfig(target, entryPointFn, winogradOp);
       })
-      .Case<linalg::PackOp>([&](auto packOp) {
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2552]: Where is the entry of setting config on pack op now? I'm having hard time to figure it out when I look at the code around it.

Comment (Max191) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2552]: It becomes part of the Default case now, and is handled by `IREE::GPU::setTileAndFuseLoweringConfig`. The implementation lives in ConfigUtils.cpp

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2552]: I see, I missed this. I don't get that why we have a flag on default, and the default is not the default anymore..

https://github.com/iree-org/iree/blob/ce2585aa5db62151157e9af4b0449109e9335f4c/compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp#L2571-L2578

File: compiler/src/iree/compiler/Codegen/Common/TileInferenceUtils.cpp [hunk 3]
```diff
@@ -362,6 +365,11 @@ static SmallVector<int64_t> inferUseWorkgroupTileMultiples(OpOperand *use) {
 SmallVector<int64_t> getWorkgroupSizeMultiples(TilingInterface tilingOp) {
   LDBG("Computing workgroup tile size multiples for: "
        << *tilingOp.getOperation());
+  if (auto packOp = dyn_cast<linalg::PackOp>(tilingOp.getOperation())) {
+    // We do not expect to find multiple pack/unpack ops in the same dispatch
+    // region, so we can simply return the multiples for the given `packOp`.
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/TileInferenceUtils.cpp]: Is it true? I thought that there are cases like `unpack -> elementwise/reduction -> pack`?

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 4]
```diff
@@ -560,16 +590,41 @@ LogicalResult setTileAndFuseLoweringConfig(IREE::GPU::TargetAttr target,
     return failure();
   }
 
-  SmallVector<unsigned int> partitionableLoops;
-  linalgOp.getParallelDims(partitionableLoops);
+  // SmallVector<unsigned int> partitionableLoops;
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: nit: delete the comment

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 5]
```diff
@@ -544,9 +548,35 @@ static unsigned getRepresentativeBitWidth(linalg::LinalgOp linalgOp) {
...
+  return isa<IntegerType, FloatType>(elementType) &&
+         llvm::isPowerOf2_64(IREE::Util::getTypeBitWidth(elementType));
+}
+
+struct DistributionInfo {
+  SmallVector<unsigned int> partitionableLoops;
+  SmallVector<int64_t> loopBounds;
+  unsigned minBitwidth;
+  unsigned representativeBitWidth;
+  bool vectorizable;
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: It is better to initialize them in struct definition. Otherwise, it may lead to undefined behavior. E.g., the `vectorizable` is not initialized in the below pack distribution config.

https://abseil.io/tips/182

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 6]
```diff
@@ -560,16 +590,41 @@ LogicalResult setTileAndFuseLoweringConfig(IREE::GPU::TargetAttr target,
...
+  if (distInfo.partitionableLoops.empty()) {
+    return failure();
+  }
+
+  // Whether we can try to use the vectorization pipeline.
+  distInfo.loopBounds = linalgOp.getStaticLoopRanges();
+  bool projPerm =
+      llvm::all_of(linalgOp.getIndexingMapsArray(),
+                   [](AffineMap map) { return map.isProjectedPermutation(); });
+  bool powTwo = llvm::all_of(op->getOperands(), elementHasPowerOfTwoBitwidth);
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: optional nit: I'd name them as `isProjPerm` and `isPowerOfTwo`.

File: compiler/src/iree/compiler/Codegen/Common/TileInferenceUtils.cpp (hunk 3 above)
Comment (Max191) [reply compiler/src/iree/compiler/Codegen/Common/TileInferenceUtils.cpp]: The assumption is not about dispatch formation. It is about root op selection. If we have a dispatch like `unpack -> elementwise -> pack`, then the elementwise op would become the root op, and we will not set a config on the pack/unpack ops.

I think I let the assumptions about the lowering config selection leak into the TileInferenceUtils, so it is quite confusing. I'll try to figure out a better way to handle this.

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/TileInferenceUtils.cpp]: I see what you meant. So it is more like we do not expect to find multiple pack/unpack ops when the root op is a pack op. What if we have `unpack->pack` dispatch? What op is a root op?

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp (hunk 2 above)
Comment (Max191) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2552]: I see, yeah, it is a little confusing. I'll clean up the logic in this PR. Maybe we can remove the flag too, but I'll keep it in this PR for now.

File: compiler/src/iree/compiler/Codegen/Common/TileInferenceUtils.cpp (hunk 3 above)
Comment (Max191) [reply compiler/src/iree/compiler/Codegen/Common/TileInferenceUtils.cpp]: The root op would be pack in that case, but I don't think we would form that dispatch.

Comment (Max191) [reply compiler/src/iree/compiler/Codegen/Common/TileInferenceUtils.cpp]: I added a test for the unpack->pack case and supported the case in TIleInferenceUtils. We still shouldn't get those dispatches, but I think it is better that the utils are doing the correct thing.

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 7]
```diff
@@ -544,9 +548,35 @@ static unsigned getRepresentativeBitWidth(linalg::LinalgOp linalgOp) {
   return 32;
 }
 
-LogicalResult setTileAndFuseLoweringConfig(IREE::GPU::TargetAttr target,
-                                           mlir::FunctionOpInterface entryPoint,
-                                           Operation *op) {
+static bool elementHasPowerOfTwoBitwidth(Value operand) {
+  Type elementType = getElementTypeOrSelf(operand.getType());
+  return elementType.isIntOrFloat() &&
+         llvm::isPowerOf2_64(IREE::Util::getTypeBitWidth(elementType));
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: Sorry, I did not notice it in the previous review round. If we already check that the element type is either int or float, we do not use the `getTypeBitWidth`? It is good for complex and vector types, for sure. Here I think it's better to use `elementType.getIntOrFloatBitWidth()`, because it is straight-forward. We won't have to think why do we use the method, and the outcome is that they result into the same thing.

https://github.com/iree-org/iree/blob/d3d66748b36b6e38546e0f77ba0604cef5c442ef/compiler/src/iree/compiler/Dialect/Util/IR/UtilTypes.h#L310-L321

File: compiler/src/iree/compiler/Codegen/Common/TileInferenceUtils.cpp (hunk 3 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/TileInferenceUtils.cpp]: We could see it in some cases. I can construct it on default path, but it is rare for sure. I did not ask for a change, but it is good that you take it into account. I was mostly trying to clarify things.

**Review by hanhanW — COMMENTED** [review]
Overall looks good to me

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp (hunk 7 above)
Comment (Max191) [reply compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: That's true, thanks for the suggestion. Lot's of copied code from the old path that I didn't clean up :)

File: compiler/src/iree/compiler/Codegen/Common/TileInferenceUtils.cpp (hunk 3 above)
Comment (Max191) [reply compiler/src/iree/compiler/Codegen/Common/TileInferenceUtils.cpp]: Ah, I thought we don't even fuse these 2 ops together, but I am rusty on the fusion logic in IREE. I'll update the comment in my new test so it's not saying that we don't create such dispatches.

**Review by hanhanW — APPROVED** [review]

**Comment by krzysz00** [comment]
As a followup, could you reenable the pack test that was hitting a compiler bug on MI-300?

**Comment by Max191** [comment]
> As a followup, could you reenable the pack test that was hitting a compiler bug on MI-300?

@krzysz00 could you point me to where I need to add back the test? I think I lost track of where it got removed.
