### PR TITLE
Plumb 'torch' input to auto detect via plugin interface.

### LINKED ISSUE #15353: Improve handling of 'torch' input type
Spotted this while responding to https://github.com/nod-ai/SHARK-Turbine/issues/118#issuecomment-1787497716

I'm trying to compile a sample program exported by SHARK-Turbine using [this Colab notebook](https://colab.research.google.com/github/openxla/iree/blob/main/samples/colab/pytorch_aot_simple.ipynb). Some workflows that should work do not.
<details><summary>Click to expand sample MLIR</summary>
<p>

```mlir
module @LinearModule {
  util.global private @_params.weight {noinline} = dense<[[1.54099607, -0.293428898, -2.17878938], [0.568431258, -1.08452237, -1.39859545], [0.403346837, 0.838026344, -0.719257593], [-0.403343529, -0.596635341, 0.182036489]]> : tensor<4x3xf32>
  util.global private @_params.bias {noinline} = dense<[-0.856674611, 1.10060418, -1.07118738]> : tensor<3xf32>
  func.func @main(%arg0: tensor<4xf32>) -> tensor<3xf32> attributes {torch.args_schema = "[1, {\22type\22: \22builtins.tuple\22, \22context\22: \22null\22, \22children_spec\22: [{\22type\22: \22builtins.list\22, \22context\22: \22null\22, \22children_spec\22: [{\22type\22: null, \22context\22: null, \22children_spec\22: []}]}, {\22type\22: \22builtins.dict\22, \22context\22: \22[]\22, \22children_spec\22: []}]}]", torch.return_schema = "[1, {\22type\22: null, \22context\22: null, \22children_spec\22: []}]"} {
    %0 = torch_c.from_builtin_tensor %arg0 : tensor<4xf32> -> !torch.vtensor<[4],f32>
    %1 = call @forward(%0) : (!torch.vtensor<[4],f32>) -> !torch.vtensor<[3],f32>
    %2 = torch_c.to_builtin_tensor %1 : !torch.vtensor<[3],f32> -> tensor<3xf32>
    return %2 : tensor<3xf32>
  }
  func.func private @forward(%arg0: !torch.vtensor<[4],f32>) -> !torch.vtensor<[3],f32> {
    %int0 = torch.constant.int 0
    %0 = torch.aten.unsqueeze %arg0, %int0 : !torch.vtensor<[4],f32>, !torch.int -> !torch.vtensor<[1,4],f32>
    %_params.weight = util.global.load @_params.weight : tensor<4x3xf32>
    %1 = torch_c.from_builtin_tensor %_params.weight : tensor<4x3xf32> -> !torch.vtensor<[4,3],f32>
    %2 = torch.aten.mm %0, %1 : !torch.vtensor<[1,4],f32>, !torch.vtensor<[4,3],f32> -> !torch.vtensor<[1,3],f32>
    %int0_0 = torch.constant.int 0
    %3 = torch.aten.squeeze.dim %2, %int0_0 : !torch.vtensor<[1,3],f32>, !torch.int -> !torch.vtensor<[3],f32>
    %_params.bias = util.global.load @_params.bias : tensor<3xf32>
    %4 = torch_c.from_builtin_tensor %_params.bias : tensor<3xf32> -> !torch.vtensor<[3],f32>
    %int1 = torch.constant.int 1
    %5 = torch.aten.add.Tensor %3, %4, %int1 : !torch.vtensor<[3],f32>, !torch.vtensor<[3],f32>, !torch.int -> !torch.vtensor<[3],f32>
    return %5 : !torch.vtensor<[3],f32>
  }
}
```

</p>
</details> 

## Compilation workflows tested

* CLI `iree-compile` with `--iree-input-type=torch` works:
  ```
  D:\dev\projects\iree-build
  λ .\tools\iree-compile.exe D:\dev\scratch\iree-tmp\python\torch_input.mlir --iree-input-type=torch --iree-hal-target-backends=llvm-cpu -o D:\dev\scratch\iree-tmp\python\torch_output.vmfb
  ```
  
* CLI `iree-compile` _without_ `iree-input-type=torch` does not work:
  ```
  D:\dev\projects\iree-build
  λ .\tools\iree-compile.exe D:\dev\scratch\iree-tmp\python\torch_input.mlir --iree-hal-target-backends=llvm-cpu -o D:\dev\scratch\iree-tmp\python\torch_output.vmfb
  D:\dev\scratch\iree-tmp\python\torch_input.mlir:5:10: error: failed to legalize operation 'torch_c.from_builtin_tensor' that was explicitly marked illegal
      %0 = torch_c.from_builtin_tensor %arg0 : tensor<4xf32> -> !torch.vtensor<[4],f32>
           ^
  D:\dev\scratch\iree-tmp\python\torch_input.mlir:4:3: note: called from
    func.func @main(%arg0: tensor<4xf32>) -> tensor<3xf32> attributes {torch.args_schema = "[1, {\22type\22: \22builtins.tuple\22, \22context\22: \22null\22, \22children_spec\22: [{\22type\22: \22builtins.list\22, \22context\22: \22null\22, \22children_spec\22: [{\22type\22: null, \22context\22: null, \22children_spec\22: []}]}, {\22type\22: \22builtins.dict\22, \22context\22: \22[]\22, \22children_spec\22: []}]}]", torch.return_schema = "[1, {\22type\22: null, \22context\22: null, \22children_spec\22: []}]"} {
    ^
  D:\dev\scratch\iree-tmp\python\torch_input.mlir:5:10: note: see current operation: %25 = "torch_c.from_builtin_tensor"(%24) : (tensor<4xf32>) -> !torch.vtensor<[4],f32>
      %0 = torch_c.from_builtin_tensor %arg0 : tensor<4xf32> -> !torch.vtensor<[4],f32>
           ^
  ```

* Python `iree.compiler.tools.compile_file` with `input_type="torch"` does not work:

  ```python
  import iree.compiler.tools
  
  binary = iree.compiler.tools.compile_file(
      "D:/dev/scratch/iree-tmp/python/torch_input.mlir",
      input_type="torch",
      target_backends=["llvm-cpu"],
  )
  ```
  
  ```
  D:\dev\projects\iree-build
  λ python3 D:\dev\scratch\iree-tmp\python\torch_input.py
  Traceback (most recent call last):
    File "D:\dev\scratch\iree-tmp\python\torch_input.py", line 36, in <module>
      binary = iree.compiler.tools.compile_file(
    File "D:\dev\projects\iree-build\compiler\bindings\python\iree\compiler\tools\core.py", line 240, in compile_file
      options = CompilerOptions(**kwargs)
    File "<string>", line 17, in __init__
    File "D:\dev\projects\iree-build\compiler\bindings\python\iree\compiler\tools\core.py", line 161, in __post_init__
      self.input_type = InputType.parse(self.input_type)
    File "D:\dev\projects\iree-build\compiler\bindings\python\iree\compiler\tools\core.py", line 65, in parse
      raise ValueError(
  ValueError: For input_type= argument, expected one of: NONE, AUTO, STABLEHLO, STABLEHLO_XLA, TOSA, TM_TENSOR
  ```

* Python `iree.compiler.tools.compile_file` without `input_type="torch"` does not work:

  ```python
  import iree.compiler.tools
  
  binary = iree.compiler.tools.compile_file(
      "D:/dev/scratch/iree-tmp/python/torch_input.mlir", target_backends=["llvm-cpu"]
  )
  ```
  
  ```
  D:\dev\projects\iree-build
  λ python3 D:\dev\scratch\iree-tmp\python\torch_input.py
  Traceback (most recent call last):
    File "D:\dev\scratch\iree-tmp\python\torch_input.py", line 9, in <module>
      binary = iree.compiler.tools.compile_file(
    File "D:\dev\projects\iree-build\compiler\bindings\python\iree\compiler\tools\core.py", line 254, in compile_file
      result = invoke_immediate(cl)
    File "D:\dev\projects\iree-build\compiler\bindings\python\iree\compiler\tools\binaries.py", line 198, in invoke_immediate
      raise CompilerToolError(process)
  iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile.exe
  Error code: 1
  Diagnostics:
  D:/dev/scratch/iree-tmp/python/torch_input.mlir:5:10: error: failed to legalize operation 'torch_c.from_builtin_tensor' that was explicitly marked illegal
      %0 = torch_c.from_builtin_tensor %arg0 : tensor<4xf32> -> !torch.vtensor<[4],f32>
           ^
  D:/dev/scratch/iree-tmp/python/torch_input.mlir:4:3: note: called from
    func.func @main(%arg0: tensor<4xf32>) -> tensor<3xf32> attributes {torch.args_schema = "[1, {\22type\22: \22builtins.tuple\22, \22context\22: \22null\22, \22children_spec\22: [{\22type\22: \22builtins.list\22, \22context\22: \22null\22, \22children_spec\22: [{\22type\22: null, \22context\22: null, \22children_spec\22: []}]}, {\22type\22: \22builtins.dict\22, \22context\22: \22[]\22, \22children_spec\22: []}]}]", torch.return_schema = "[1, {\22type\22: null, \22context\22: null, \22children_spec\22: []}]"} {
    ^
  
  
  Invoked with:
   iree-compile.exe D:\dev\projects\iree-build\compiler\bindings\python\iree\compiler\tools\..\_mlir_libs\iree-compile.exe D:/dev/scratch/iree-tmp/python/torch_input.mlir --iree-input-type=auto --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-embedded-linker-path=D:\dev\projects\iree-build\compiler\bindings\python\iree\compiler\tools\..\_mlir_libs\iree-lld.exe --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
  
  Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.
  ```

## How to fix

All four should work. Probably needs changes across [`compiler/bindings/python/iree/compiler/tools/core.py`](https://github.com/openxla/iree/blob/main/compiler/bindings/python/iree/compiler/tools/core.py) and the input pipeline C++ code.

We should also have unit tests for each of these workflows.

### PR DESCRIPTION
**Pull request by ScottTodd**
This teaches the 'auto' input conversion pipeline how to run plugin-provided conversions automatically when plugins detect that ops in their related dialects are present in a module. Now, programs coming from PyTorch (torch-mlir) can omit `--iree-input-type=torch` and rely on the default of `--iree-input-type=auto` (this fixes https://github.com/openxla/iree/issues/15353).

The code is awkward for a few reasons, but I think it can be improved incrementally:

* StableHLO and TOSA are "built in" to the compiler (gated on `IREE_HAVE_STABLEHLO_INPUT` / `IREE_HAVE_TOSA_INPUT`), while Torch is implemented via a compiler plugin
  * I think we could migrate both to be plugins, which would put the input dialects on even footing
* The new dynamic pass pipeline needs to know which dialects to register
  * If all input conversions were plugins, that would feel like less of a special case
* There is a dep cycle that I'm trying to avoid narrowly... that may be fixed by migrating all input conversions to plugins

### CODE REVIEW

File: compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp [hunk 1]
```diff
@@ -72,6 +75,28 @@ struct TorchSession
...
   }
+
+  std::string detectCustomInputOperations(ModuleOp &module) override {
+    auto *ctx = module.getContext();
+
+    const Dialect *torchDialect = ctx->getLoadedDialect("torch");
+    const Dialect *torchConversionDialect = ctx->getLoadedDialect("torch_c");
+    const Dialect *tmTensorDialect = ctx->getLoadedDialect("tm_tensor");
+
+    std::string typeMnemonic = "";
```
Comment (jpienaar) [inline compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp]: Could torchDialect etc be null here?

File: compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp [hunk 2]
```diff
@@ -72,6 +75,28 @@ struct TorchSession
     typeMnemonics.insert("tm_tensor");
     typeMnemonics.insert("torch");
   }
+
+  std::string detectCustomInputOperations(ModuleOp &module) override {
```
Comment (jpienaar) [inline compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp]: Is a string sufficient though? Also is their a hierarchy here? E.g., if you see torch_c and torch, then return torch?

File: compiler/src/iree/compiler/PluginAPI/PluginManager.h [hunk 3]
```diff
@@ -108,6 +108,18 @@ class PluginManagerSession : public PipelineExtensions {
     }
   }
 
+  std::string detectCustomInputOperations(ModuleOp &module) override {
+    for (auto *s : initializedSessions) {
+      // Return the type mnemonic from the first session that detects support.
+      std::string typeMnemonic = s->detectCustomInputOperations(module);
+      if (!typeMnemonic.empty()) {
+        // TODO(scotttodd): error if multiple sessions found ops they support?
```
Comment (jpienaar) [inline compiler/src/iree/compiler/PluginAPI/PluginManager.h]: Ideally we can support multiple of these together, could end up populating many pipelines together (e.g., why not some TOSA, StableHLO and ATen ops all together?:)

**Review by jpienaar — COMMENTED** [review]
It would be nicer if more of these plugins indeed - esp StableHLO one given deps.

File: compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp (hunk 1 above)
Comment (ScottTodd) [reply compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp]: I hope not 👀 maybe I should check

File: compiler/src/iree/compiler/PluginAPI/PluginManager.h (hunk 3 above)
Comment (ScottTodd) [reply compiler/src/iree/compiler/PluginAPI/PluginManager.h]: Yeah, agreed. I think putting the input conversions on equal footing as plugins (with a clear API to implement) will also help untangle some of those design questions. As it is now, we have a mix of conversions following different sets of rules.

File: compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp (hunk 2 above)
Comment (ScottTodd) [reply compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp]: It's sufficient for calling `detectCustomInputOperations` -> the existing `extendCustomInputConversionPassPipeline` method (since the latter takes a "typeMnemonic" string). There is a chance here to further rework the API though. It wasn't quite clear to me what would be needed by the API until I had this plumbed all the way across... I'll think on this a bit.

Comment (ScottTodd) [reply compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp]: A string is easier to manage across arbitrary plugins, but we could add more structure to that string if needed (namespaces, parameters/modifiers, etc.). We could also have a list/map of strings for combinations, but at that point we may just want to allow all plugins to do their input preprocessing in an arbitrary order (one after another), at least until we find a case of plugins conflicting with one another.

Regarding the multiple strings here: "torch" and "torch_c" are both covered by the "torch" pipeline. "tm_tensor" is a legacy pipeline that we might just be able to remove entirely now. I'm not too concerned with doing a priority selection of one or the other.

File: compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp (hunk 1 above)
Comment (ScottTodd) [reply compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp]: It could be if you use the API functions out of order. I'm not sure if it's worth checking for that vs letting the code just crash/error/fall-through.

File: compiler/src/iree/compiler/PluginAPI/Client.h [hunk 4]
```diff
@@ -58,6 +62,13 @@ class PipelineExtensions {
   // considered valid.
   virtual void populateCustomInputConversionTypes(StringSet<> &typeMnemonics) {}
 
+  // Returns an appropriate typeMnemonic if operations from a dialect this
+  // instance supports are present in the module.
+  // Requires that dialects have already been added using |registerDialects|.
+  virtual std::string detectCustomInputOperations(ModuleOp &module) {
```
Comment (jpienaar) [inline compiler/src/iree/compiler/PluginAPI/Client.h]: I think most here are fine as we can relatively freely change, this one is something that spans across repos.

I don't like "custom" here, I don't know what else to call. Reading the description, it feels like "is supported" or "is required" ... but yes still tangled to do this. It almost feels like if a plugin says it doesn't support then it doesn't get added, else it is used to populate pipeline. Currently we'd have only 1 say required (e.g., only if stablehlo then stablehlo would say required) on a supported path. Now if input is mixed then it won't work but ideally all would be partial conversions and these could be composed.

Comment (ScottTodd) [reply compiler/src/iree/compiler/PluginAPI/Client.h]: I was trying to match the other API methods, and two of them use "custom" already:

```c++
virtual void registerDialects(DialectRegistry &registry);
virtual void extendInputConversionPreprocessingPassPipeline(
    OpPassManager &passManager, InputDialectOptions::Type inputType);
virtual void populateCustomInputConversionTypes(StringSet<> &typeMnemonics);

// New:
virtual std::string detectCustomInputOperations(ModuleOp &module);

virtual bool
    extendCustomInputConversionPassPipeline(OpPassManager &passManager,
                                            std::string_view typeMnemonic);
virtual void extendPreprocessingPassPipeline(OpPassManager &passManager);
```

Good points though. How about `detectCustomInputConversionTypes` that returns all of the "custom input conversion types" from `populateCustomInputConversionTypes` that are detected within a module? Any type that function returns could then be used with `extendCustomInputConversionPassPipeline`.

```c++
virtual StringSet<> detectCustomInputConversionTypes(ModuleOp &module);
```

(could return a different data structure)

**Comment by ScottTodd** [comment]
Just merged past some conflicts. Still need to make a few updates (reworking the new API function). Might not get to that today though.

File: compiler/src/iree/compiler/PluginAPI/Client.h (hunk 4 above)
Comment (ScottTodd) [reply compiler/src/iree/compiler/PluginAPI/Client.h]: Pretty verbose, but renamed to this:

```c++
  // Adds input type mnemonics that this instance supports, if those types are
  // detected in |module|.
  // Requires that |registerDialects| has been called first.
  virtual void
  populateDetectedCustomInputConversionTypes(ModuleOp &module,
                                             StringSet<> &typeMnemonics) {}
```

Also considered renaming `populateCustomInputConversionTypes` to `populateAvailableCustomInputConversionTypes` to differentiate.

File: compiler/src/iree/compiler/InputConversion/Common/AutoInputConversionPipeline.cpp [hunk 5]
```diff
@@ -99,12 +104,50 @@ static void populateFeatures(Operation *op, const Dialect *chloDialect,
...
+  MLIRContext *context = &getContext();
+
+  // Check if any plugin-provided pipeline extensions can convert dialects in
+  // the module first.
+  if (pipelineExtensions) {
+    llvm::StringSet<> detectedTypeMnemonics;
+    pipelineExtensions->populateDetectedCustomInputConversionTypes(
+        module, detectedTypeMnemonics);
+
+    if (detectedTypeMnemonics.getNumItems() >= 2) {
```
Comment (stellaraccident) [inline compiler/src/iree/compiler/InputConversion/Common/AutoInputConversionPipeline.cpp]: super-nit: Use `> 1` as it parses to humans easier.

File: compiler/src/iree/compiler/InputConversion/Common/AutoInputConversionPipeline.cpp [hunk 6]
```diff
@@ -99,12 +104,50 @@ static void populateFeatures(Operation *op, const Dialect *chloDialect,
...
+      // TODO(scotttodd): handle multiple typeMnemonics (use all?)
+      module.emitError("not yet implemented mixture of input types");
```
Comment (stellaraccident) [inline compiler/src/iree/compiler/InputConversion/Common/AutoInputConversionPipeline.cpp]: This will be a common error message that users encounter, if history is a guide. Perhaps include some advice (i.e. set a specific --iree-input-type= or audit the code to understand why dialects are mixed)?

File: compiler/src/iree/compiler/InputConversion/Common/AutoInputConversionPipeline.cpp [hunk 7]
```diff
@@ -99,12 +104,50 @@ static void populateFeatures(Operation *op, const Dialect *chloDialect,
...
+    if (!detectedTypeMnemonics.empty()) {
+      auto typeMnemonic = detectedTypeMnemonics.begin()->getKey();
+      OpPassManager passManager(module.getOperationName());
+      bool foundExtension =
+          pipelineExtensions->extendCustomInputConversionPassPipeline(
+              passManager, typeMnemonic);
+      if (!foundExtension) {
+        // We expect that callers properly validate supported extensions and
+        // that if a plugin advertises support, it actually provides it.
+        llvm::errs() << "internal error: custom input conversion for extension "
```
Comment (stellaraccident) [inline compiler/src/iree/compiler/InputConversion/Common/AutoInputConversionPipeline.cpp]: Use the usual error reporting mechanism. Spew to llvm::errs(), especially in API cases, often goes to nether regions that are never checked or correlated back to the actual cause of failure.

**Review by stellaraccident — APPROVED** [review]
Thanks. A few nits to address before submission.

File: compiler/src/iree/compiler/InputConversion/Common/AutoInputConversionPipeline.cpp (hunk 6 above)
Comment (ScottTodd) [reply compiler/src/iree/compiler/InputConversion/Common/AutoInputConversionPipeline.cpp]: Thanks, updated. Sample error message:

`error: mixture of input types not yet implemented, set '--iree-input-type=[type]' explicitly instead of using 'auto' or audit the input program to understand why dialects are mixed (detected: 'foo' 'torch')`
