### PR TITLE
[DT] Improve encoding hoisting pass.

### LINKED ISSUE #21100: [DispatchCreation] Failed to hoist out of dispatch in DT-fusion
### What happened?

Compilation fails with `error: 'iree_encoding.set_encoding' op failed to hoist the op out of dispatch` on the DT-fusion path when the producer of the `set_encoding` op is cloned inside the dispatch region. This might be the case especially for the DT-fusion pipeline, since the `set_encoding` op itself is not really present at the time of dispatch formation or cloning producers into dispatches. So the `extract_slice -> matmul` chain becomes `extract -> set_encoding -> matmul` and the hoisting out of the dispatch fails.

### Steps to reproduce your issue

Here is an artificial reproducer that reproduces the above issue, although this pattern can also occur naturally as a result of some decompositions - or also handwritten layers etc. An example that results in this would be multi-head attention with a three-fold extraction instead of the two above - for Q, K and V.

```mlir
func.func @foo(%arg1 : tensor<8x8xf32>, %arg2 : tensor<8x8xf32>) -> (tensor<8x8xf32>, tensor<8x8xf32>){
    %arg0 = arith.constant dense_resource<__auto.constant_16_8_torch.float32> : tensor<16x8xf32>
    %extracted_slice = tensor.extract_slice %arg0[0, 0] [8, 8] [1, 1] : tensor<16x8xf32> to tensor<8x8xf32>
    %extracted_slice_1 = tensor.extract_slice %arg0[8, 0] [8, 8] [1, 1] : tensor<16x8xf32> to tensor<8x8xf32>
    %c0 = arith.constant 0.0 : f32
    
    %init = tensor.empty() : tensor<8x8xf32>
    %fill = linalg.fill ins(%c0 : f32) outs(%init : tensor<8x8xf32>) -> tensor<8x8xf32>
    %res = linalg.matmul_transpose_b ins(%extracted_slice, %arg1 : tensor<8x8xf32>, tensor<8x8xf32>) outs(%fill : tensor<8x8xf32>) -> tensor<8x8xf32>
    
    %init_1 = tensor.empty() : tensor<8x8xf32>
    %fill_1 = linalg.fill ins(%c0 : f32) outs(%init_1 : tensor<8x8xf32>) -> tensor<8x8xf32>
    %res_1 = linalg.matmul_transpose_b ins(%extracted_slice_1, %arg2 : tensor<8x8xf32>, tensor<8x8xf32>) outs(%fill_1 : tensor<8x8xf32>) -> tensor<8x8xf32>

    return %res, %res_1 : tensor<8x8xf32>, tensor<8x8xf32>
}

```

To compile:

```bash

iree-compile \
    --iree-input-type=auto \
    --iree-hal-target-backends=llvm-cpu \
    --iree-llvmcpu-target-cpu-features=host \
    --iree-opt-data-tiling=false \
    --iree-dispatch-creation-experimental-data-tiling=true \
    --mlir-print-ir-after-all \
    --mlir-print-ir-after-change \
    --mlir-elide-elementsattrs-if-larger=10 \
    --mlir-elide-resource-strings-if-larger=10 \
    ~/reproducer.mlir -o ~/reproducer.vmfb 2> ~/reproducer-logs.mlir

```

This results in the following snippet where the `set_encoding` op cannot be hoisted out of the dispatch because its producer is also inside the same dispatch region:

```mlir
...
%2 = flow.dispatch.region -> (tensor<8x8xf32>) {
    %cst_0 = arith.constant 0.000000e+00 : f32
    %extracted_slice = tensor.extract_slice %cst[0, 0] [8, 8] [1, 1] : tensor<16x8xf32> to tensor<8x8xf32>
    %6 = iree_encoding.set_encoding %extracted_slice : tensor<8x8xf32> -> tensor<8x8xf32, #iree_encoding.encoding<operand_index = 0 : index, op_type =  matmul, element_types = [f32, f32, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>], iteration_sizes = [8, 8, 8]>>
    %7 = iree_encoding.set_encoding %0 : tensor<8x8xf32> -> tensor<8x8xf32, #iree_encoding.encoding<operand_index = 1 : index, op_type =  matmul, element_types = [f32, f32, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>], iteration_sizes = [8, 8, 8]>>
    %8 = tensor.empty() : tensor<8x8xf32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [f32, f32, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>], iteration_sizes = [8, 8, 8]>>
    %9 = linalg.fill ins(%cst_0 : f32) outs(%8 : tensor<8x8xf32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [f32, f32, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>], iteration_sizes = [8, 8, 8]>>) -> tensor<8x8xf32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [f32, f32, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>], iteration_sizes = [8, 8, 8]>>
    %10 = linalg.matmul_transpose_b ins(%6, %7 : tensor<8x8xf32, #iree_encoding.encoding<operand_index = 0 : index, op_type =  matmul, element_types = [f32, f32, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>], iteration_sizes = [8, 8, 8]>>, tensor<8x8xf32, #iree_encoding.encoding<operand_index = 1 : index, op_type =  matmul, element_types = [f32, f32, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>], iteration_sizes = [8, 8, 8]>>) outs(%9 : tensor<8x8xf32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [f32, f32, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>], iteration_sizes = [8, 8, 8]>>) -> tensor<8x8xf32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [f32, f32, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>], iteration_sizes = [8, 8, 8]>>
    %11 = iree_encoding.unset_encoding %10 : tensor<8x8xf32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [f32, f32, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>], iteration_sizes = [8, 8, 8]>> -> tensor<8x8xf32>
    flow.return %11 : tensor<8x8xf32>
  }
...
```

### What component(s) does this issue relate to?

Compiler

### Version information

_No response_

### Additional context

AFAICS, there is a [TODO](https://github.com/iree-org/iree/blob/925f2f155058760368ed098afe1f68b33a1c8e69/compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp#L210) in the `HoistEncodingOps` pass that annotates that we should be able to hoist out entire slices/chains of IR out of the dispatch, which we could do over here. These would (maybe with additional changes in the Stream MaterializeEncodings pass) then get their own dispatches later.

On the other hand, I think the case where these would actually not be hoisted out of the dispatch should also be investigated. I understand the problem with fusing pack operations as producers with some tile sizes (see [here](https://github.com/llvm/llvm-project/blob/854b9e931703dd1b9d8a2b0fe8da787f9e26058d/mlir/lib/Dialect/Linalg/Transforms/TilingInterfaceImpl.cpp#L731)), but I believe the tile sizes we choose should be divisible by the inner tile sizes, which also came up during a discussion about the consumer fusion counterpart of the pack operation.

So I could think of two options for this specific case over here:
- The `extract_slice` ops (or maybe in other cases some other op), get cloned into the same region as the matmul in the `CloneProducersIntoDispatchRegionsPass`, we could preemptively block the cloning of operations that in turn lead to such sequences of unhoistable ops as above. I'm not entirely sure of the assumptions one would have to make here to guarantee that we indeed would have the `set_encoding` op materializing into something and not becoming a nop.
- As the TODO above suggests, add the mechanism to hoist out the sequence of IR that leads to the `set_encoding` op out of the dispatch and _possibly_ adjust the materialization pass to handle these sequences as well. I'm not sure how well this would actually work if we have, e.g. two separate set of encodings for the two (or possibly more) slices extracted that possibly require padding.

For the longer run, I think it might also be sensible to revisit lowering configs/codegen for the case of `pack -> mmt4d -> unpack` instead of bailing on compilation. I'm sure there are problems here that I'm overseeing, so any clarification/pointers here would be wildly appreciated :) 

Also, I'm aware that the correct solution here might also be "don't end up with such sequnce of IR, have two separate buffers/inputs instead of extracting from the same buffer", but I'd also like to ask if such patterns might occur elsewhere maybe more frequently and naturally?

### PR DESCRIPTION
**Pull request by hanhanW**
The revision runs ConstExprHoistingPolicy and hoist the chain ops outside dispatch if they are const-exprs. Furthermore, it allows hoisting tensor.extract_slice ops when they are mappable into Flow ops. It also allows constant-like ops because the ConstExpr analysis has an assumption that any root op is already hoisted to initializers. The rest of operations are not allowed to be hoisted out atm.

The hoistEncodingsForConstExpr is dropped because it is no longer needed. It was created for padding strategy.

The pass is changed to ModuleOp scope because it requires the analysis for const-exprs. Otherwise, it causes a thread race condition.

Fixes https://github.com/iree-org/iree/issues/21100

### CODE REVIEW

**Comment by hanhanW** [comment]
cc @egebeysel who might be interested in it.

File: compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp [hunk 1]
```diff
@@ -197,28 +227,55 @@ void HoistEncodingOpsPass::runOnOperation() {
...
+      Operation *op = worklist.front();
+      worklist.pop();
+      opsWithinDispatch.insert(op);
+      for (auto input : op->getOperands()) {
+        if (auto inputOp = input.getDefiningOp();
+            inputOp &&
+            inputOp->getParentOfType<IREE::Flow::DispatchRegionOp>() &&
+            !opsWithinDispatch.contains(inputOp)) {
+          if (!isHoistableOp(inputOp)) {
+            inputOp->dump();
```
Comment (egebeysel) [inline compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp]: nit: looks like a forgotten debug print :)

File: compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp [hunk 2]
```diff
@@ -135,6 +143,21 @@ static LogicalResult bubbleUpSetEncoding(RewriterBase &rewriter,
...
+  if (auto sliceOp = dyn_cast<tensor::ExtractSliceOp>(op)) {
+    SmallVector<OpFoldResult> offsets = sliceOp.getMixedOffsets();
+    SmallVector<OpFoldResult> sizes = sliceOp.getMixedSizes();
+    SmallVector<OpFoldResult> strides = sliceOp.getMixedStrides();
+    ArrayRef<int64_t> srcShape = sliceOp.getSourceType().getShape();
+    return IREE::Flow::isOffsetSizeAndStrideMappableToFlow(offsets, sizes,
+                                                           strides, srcShape);
+  }
+
+  // Compute ops are not hoistable after dispatch formation.
```
Comment (egebeysel) [inline compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp]: nit: might make sense to have a utility function `isComputeOp` and use it [here](https://github.com/iree-org/iree/blob/a96f886a11e681fa89f47140fb9a37ba7b4bda7f/compiler/src/iree/compiler/Codegen/Utils/Utils.cpp#L919) as well, so that we're also sure they're aligned.

**Review by egebeysel — COMMENTED** [review]
Thank you for the ping and the PR :) I think it looks good! One thing I was curious about: we're unable to do const evaluation after dispatch creation. Why was that exactly and does/could these changes maybe relate to that?

P.S.: I tagged this on another issue but on a second look, didn't look at the other one carefully at first, so it's irrelevant.

File: compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp [hunk 3]
```diff
@@ -135,6 +143,21 @@ static LogicalResult bubbleUpSetEncoding(RewriterBase &rewriter,
...
+  return !isa<linalg::LinalgDialect, IREE::LinalgExt::IREELinalgExtDialect>(
+      op->getDialect());
```
Comment (Max191) [inline compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp]: Is it safe to hoist all non linalg/linalg_ext ops like this? Would it be better to check for specific dialects that we _want_ to hoist rather than dialects that we don't want to hoist?

Maybe it is okay because of some assumptions we can make about dispatch formation, but we should be careful about leaking the dispatch formation assumptions into other passes (at the very least I think we should document the assumptions in the comments).

File: compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp [hunk 4]
```diff
@@ -197,28 +227,55 @@ void HoistEncodingOpsPass::runOnOperation() {
...
+    bool isHoistable = true;
+    SetVector<Operation *> opsWithinDispatch;
+    std::queue<Operation *> worklist;
+    worklist.push(setEncodingOp);
+    while (!worklist.empty()) {
+      Operation *op = worklist.front();
+      worklist.pop();
+      opsWithinDispatch.insert(op);
+      for (auto input : op->getOperands()) {
+        if (auto inputOp = input.getDefiningOp();
```
Comment (Max191) [inline compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp]: nit: put the `inputOp` definition outside the if condition?

File: compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp [hunk 5]
```diff
@@ -197,28 +227,55 @@ void HoistEncodingOpsPass::runOnOperation() {
...
-        failed(IREE::Flow::hoistOutOfDispatch(rewriter, src))) {
-      src->emitOpError("failed to hoist the source out of dispatch");
-      return signalPassFailure();
-    }
-    if (failed(IREE::Flow::hoistOutOfDispatch(rewriter, setEncodingOp))) {
-      setEncodingOp.emitOpError("failed to hoist the op out of dispatch");
-      return signalPassFailure();
+  for (auto hoistableOps : candidates) {
+    LDBG("Hoisting the ops for " << *hoistableOps.back());
+    for (auto op : hoistableOps) {
```
Comment (Max191) [inline compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp]: nit: spell out type for `hoistableOps` and `op`.

**Comment by hanhanW** [comment]
> Thank you for the ping and the PR :) I think it looks good! One thing I was curious about: we're unable to do const evaluation after dispatch creation. Why was that exactly and does/could these changes maybe relate to that?
> 
> P.S.: I tagged this on another issue but on a second look, didn't look at the other one carefully at first, so it's irrelevant.

One of the answers is that they will be hoisted into initializers; we'll run it only once when we start the execution, e.g., `iree-benchmark-module`, etc.

IMHO, we should be able to support const-eval after dispatch creation in the future, but I'm not sure how the layering'd look like atm.

File: compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp (hunk 2 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp]: I'd like to be careful about it because global utils could make it harder for dialects/phases to change independently, and that can be a good thing, especially when the function is simple. E.g., we can incrementally add support in different dialects under a flag without plumbing through the whole stack. Different backends can support the case in their timeline; it won't become a blocker if any backend can't support the feature and we don't have resources for it.

For the compute op, I think the assumption is that it is a compute op if it implements TilingInterface. There could be outliers like ukernel ops, but it is codegen specific.

File: compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp (hunk 3 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp]: Yeah, maybe it should be an allow-list because people may add more operations that we don't expect, e.g., tensor_ext.bitcast ops. Let me run an experiment in https://github.com/iree-org/iree/pull/21181, and I'll circle back.

File: compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp (hunk 1 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp]: good catch, thanks!

File: compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp (hunk 3 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp]: The current allow-list is okay for integration tests, I think we can go with the current version. PTAL

**Review by Max191 — APPROVED** [review]

**Comment by hanhanW** [comment]
cc @jtuyls who recently looks at hoisting and propagation as well.
