### PR TITLE
[LinalgExt] Decompose sub-byte map_scatter to extract/store

### LINKED ISSUE #22215: [Codegen] Support map_scatter for blocked fp4 tensors
Tracking issue for blocked fp4 layout transformations. Compilation currently fails because we end up with an fp4 `vector.scatter` operation.

### Reproducing the issue ###

1. Checkout https://github.com/iree-org/iree/pull/22189
2. Compile mxfp4 using the test harness here: https://github.com/iree-org/iree/issues/22217#issuecomment-3373276984
   - Some extra flags are needed to enable scaled matmul data tiling:
     - `./run_and_compare.sh 256 256 256 --iree-dispatch-creation-data-tiling=true --iree-dispatch-creation-test-set-scaled-matmul-encodings=true`

### Solution ###

The input encoding dispatches fail in narrow type emulation, because vector.scatter ops with subbyte types are not supported. However, for scaled matmuls, the layout transformations should always have blocks of 32 i4 values as the innermost dimension in both the source and destination layout by construction. This is because the core reason for blocking is to pack the i4 values into a chunk that is easily loadable. We can take advantage of this for layout transformation codegen.

Because the block dimension will always be innermost in the source and destination for the layout transformation, that means we will end up with a map_scatter that looks like some form of the following:

```mlir
  %0 = iree_linalg_ext.map_scatter %input into %output {
    ^bb0(%idx0: index, %idx1: index):
      // Compute indices and mask
      iree_linalg_ext.yield %some_val0, %some_val1, %some_val2, %idx1, %some_mask : index, index, index, index, i1
  } : tensor<?x32xf32> into tensor<?x?x?x32xf32> -> tensor<?x?x?x32xf32>
```

When we finally decompose the map_scatter op, we currently just decompose it into some index computation plus a vector.scatter using the computed indices. Instead, we want to be able to take advantage of the fact that the op above returns `%idx1` directly in its innermost dimension. More generally, we want to check for the following:

1. The innermost input index is directly returned as the innermost output index.
2. The mask is not a function of the innermost source index.

If both of these conditions are true, then instead of creating a vector.scatter op, we can unroll the op into a series of `vector.extract -> vector.store`, where it is extracting and storing the full innermost dimension.

Map scatter decomposition for reference: https://github.com/iree-org/iree/blob/8f7065e76cc245200ebbd24e010dcf7a50209b8e/compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp#L129-L130

We should also avoid vectorization if we won't be able to perform this block extract + store, but this will not show up today, since we will always have blocks. More notes on this in the section below.

A couple of context notes that make the above solution more clear:

 - The decomposition will only happen on vector types, meaning all shapes should be static and resonable sized.
 - If the map_scatter is not vectorized, it will go down the slower path of `LinalgExtToLoops`, which unrolls the whole map_scatter into a series of scalar `memref.load->memref.store`, so compilation should at least not fail if we don't vectorize.

### Temporary fix to get around the issue ###

The way to get around the issue today is to force the slower non-vectorization path, by removing the map_scatter vectorization passes in the codegen pipeline: 
https://github.com/iree-org/iree/blob/8f7065e76cc245200ebbd24e010dcf7a50209b8e/compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp#L545-L546

https://github.com/iree-org/iree/blob/8f7065e76cc245200ebbd24e010dcf7a50209b8e/compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp#L843-L844

For the proper solution above, we still want to avoid vectorizing map_scatter if we won't be able to vectorize into extract/store of blocks of subbyte types, so we should safeguard against any unexpected cases. This is lower priority, but it would be implemented here: https://github.com/iree-org/iree/blob/8f7065e76cc245200ebbd24e010dcf7a50209b8e/compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/VectorizeIREELinalgExtOps.cpp#L24-L51

We can add a check to not vectorize if the element type is subbyte, and the inner dimension is not contiguous in both the source and destination.

### PR DESCRIPTION
**Pull request by jtuyls**
Resolves: https://github.com/iree-org/iree/issues/22215

Vectorizes `map_scatter` on sub-byte types with contiguous accesses that are a multiple of a byte size to a sequence of `vector.extract` and `vector.store` operations.

### CODE REVIEW

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp [hunk 1]
```diff
@@ -131,6 +174,29 @@ static LogicalResult decomposeMapScatter(MapScatterOp mapScatterOp,
...
+  // a sequence of vector extract/stores operations if possible.
+  if (bitWidth < 8) {
+    Block &transformBody = mapScatterOp.getTransformationRegion().front();
+    SmallVector<Value> args(transformBody.getArguments());
+    Value innermostInputIdx = args[args.size() - 1];
+    auto bodyYield =
+        cast<IREE::LinalgExt::YieldOp>(transformBody.getTerminator());
+    Value innermostOutputIdx =
+        bodyYield.getOperand(bodyYield.getNumOperands() - 2);
+    if (isUnitFunctionOf(innermostOutputIdx, innermostInputIdx)) {
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp]: nit: Maybe move this logic into a member function of the op? I think the same checks were also used in the vectorization pass, so would be good to have a single shared implementation so they are less likely to get out of sync.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp [hunk 2]
```diff
@@ -131,6 +174,29 @@ static LogicalResult decomposeMapScatter(MapScatterOp mapScatterOp,
   Location loc = mapScatterOp.getLoc();
   OpBuilder::InsertionGuard g(rewriter);
   rewriter.setInsertionPoint(mapScatterOp);
+  const int64_t bitWidth = mapScatterOp.getInputType().getElementTypeBitWidth();
+  // In case of a sub-byte bitwidth, we check that there is a contiguous copy
+  // on the inner dimension that is a multiple of a byte size and decompose into
+  // a sequence of vector extract/stores operations if possible.
+  if (bitWidth < 8) {
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp]: This optimization doesn't necessarily have to only be for subbyte types. It is always beneficial to vectorize the stores, even for non subbyte types.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp [hunk 3]
```diff
@@ -119,6 +120,48 @@ static Value createFlatOutputBuffer(RewriterBase &rewriter, Location loc,
                                            collapsedShape, collapsedStrides);
 }
 
+/// Decompose the `map_scatter` into a sequence of `vector.extract` and
+/// `vector.store` operations.
+static LogicalResult decomposeToLoadStore(MapScatterOp mapScatterOp,
+                                          RewriterBase &rewriter) {
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp]: We should still be vectorizing the index computation here. The existing vector decomposition uses the linalg.generic vectorizer to compute a vector of indices, and this should do the same.
https://github.com/iree-org/iree/blob/9fdd3ddadcf6aac36698c4c02e100b88d4123d85/compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp#L141-L184
You can follow the logic here^, but for the contiguous dimensions, use `arith.constant 0 : index` instead of `linalg.index`. Then you can do a loop of `vector.extract(index), vector.extract(values) -> vector.store`.

**Review by Max191 — CHANGES_REQUESTED** [review]

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp (hunk 3 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp]: @Max191 I updated the PR to vectorize the index and mask computation as well. I am not sure though why this was needed? I compared both implementations and vectorizing the index computation didn't result in any performance boost (at least for the sub-byte cases I tried). I can see the benefit of a more consistent output + reuse of logic, but not sure whether you were expecting performance benefits?

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp (hunk 2 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp]: Yeah, updated it now.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp (hunk 1 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp]: I added functions to return the mask, input and output indices now as these seem useful more broadly as well.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp (hunk 3 above)
Comment (Max191) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp]: It probably depends on the shape of the matmul as to whether or not there will be noticeable performance impact, but the reason to do this is so that when the index computation is vectorized, it is possible to lower into more efficient packed math instructions. For matmuls with large reduction dimensions, the difference from the output index computation often isn't noticeable because the computation is so read heavy.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp [hunk 4]
```diff
@@ -119,15 +123,56 @@ static Value createFlatOutputBuffer(RewriterBase &rewriter, Location loc,
...
-/// and then a vector.scatter op to scatter the input vector to the output
-/// buffer at the indices in the computed index vector. The output buffer is
-/// also flattened to a 1D memref. If the collapse is not possible due to non
-/// collapsible strides, then the decomposition will fail.
-static LogicalResult decomposeMapScatter(MapScatterOp mapScatterOp,
-                                         RewriterBase &rewriter) {
+static Value create2DOutputBuffer(RewriterBase &rewriter, Location loc,
+                                  Value outputBuffer,
+                                  ArrayRef<OpFoldResult> sizes,
+                                  SmallVectorImpl<Value> &strides) {
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp]: This function seems to not be used anywhere?

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir [hunk 5]
```diff
@@ -16,13 +16,27 @@ func.func @identity_map_scatter(
...
-//   CHECK-DAG:   %[[FLAT_INPUT:.+]] = vector.shape_cast %[[INPUT]] : vector<4x16xf32> to vector<64xf32>
-//       CHECK:   vector.scatter %[[FLAT_OUTPUT]][%[[C0]]]
-//  CHECK-SAME:     [%[[FLAT_INDICES]]], %[[FLAT_MASK]], %[[FLAT_INPUT]]
+//   CHECK-DAG:   %[[STEP_4:.+]] = vector.step : vector<4xindex>
+//   CHECK-DAG:   %[[BROADCAST_4x1:.+]] = vector.broadcast %[[STEP_4]] : vector<4xindex> to vector<1x4xindex>
+//   CHECK-DAG:   %[[TRANSPOSE:.+]] = vector.transpose %[[BROADCAST_4x1]], [1, 0] : vector<1x4xindex> to vector<4x1xindex>
+//   CHECK-DAG:   %[[STEP_1:.+]] = vector.step : vector<1xindex>
+//   CHECK-DAG:   %[[MULI:.+]] = arith.muli %[[TRANSPOSE]], %[[CST]] overflow<nsw> : vector<4x1xindex>
+//   CHECK-DAG:   %[[BROADCAST_1x4:.+]] = vector.broadcast %[[STEP_1]] : vector<1xindex> to vector<4x1xindex>
+//   CHECK-DAG:   %[[ADDI:.+]] = arith.addi %[[MULI]], %[[BROADCAST_1x4]] overflow<nsw> : vector<4x1xindex>
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir]: You can omit this part of the lit test. This is just the result of the generic vectorization, which is well tested upstream. IMO it's better to just check the extract/store part to reduce maintenance burden.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir [hunk 6]
```diff
@@ -114,14 +135,28 @@ func.func @map_scatter_into_collapsible_subview(
...
-//   CHECK-DAG:   %[[FLAT_INPUT:.+]] = vector.shape_cast %[[INPUT]] : vector<4x16xf32> to vector<64xf32>
-//       CHECK:   vector.scatter %[[FLAT_OUTPUT]][%[[C0]]]
-//  CHECK-SAME:     [%[[FLAT_INDICES]]], %[[FLAT_MASK]], %[[FLAT_INPUT]]
+//   CHECK-DAG:   %[[STEP_4:.+]] = vector.step : vector<4xindex>
+//   CHECK-DAG:   %[[BROADCAST_1x4:.+]] = vector.broadcast %[[STEP_4]] : vector<4xindex> to vector<1x4xindex>
+//   CHECK-DAG:   %[[TRANSPOSE:.+]] = vector.transpose %[[BROADCAST_1x4]], [1, 0] : vector<1x4xindex> to vector<4x1xindex>
+//   CHECK-DAG:   %[[STEP_1:.+]] = vector.step : vector<1xindex>
+//   CHECK-DAG:   %[[MULI:.+]] = arith.muli %[[TRANSPOSE]], %[[CST]] overflow<nsw> : vector<4x1xindex>
+//   CHECK-DAG:   %[[BROADCAST_4x1:.+]] = vector.broadcast %[[STEP_1]] : vector<1xindex> to vector<4x1xindex>
+//   CHECK-DAG:   %[[ADDI:.+]] = arith.addi %[[MULI]], %[[BROADCAST_4x1]] overflow<nsw> : vector<4x1xindex>
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir]: Same here. Better to reduce the size of the test.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir [hunk 7]
```diff
@@ -146,13 +181,150 @@ func.func @map_scatter_into_strided_output(
...
+//   CHECK-DAG:   %[[STEP_4:.+]] = vector.step : vector<4xindex>
+//   CHECK-DAG:   %[[BROADCAST_1x4:.+]] = vector.broadcast %[[STEP_4]] : vector<4xindex> to vector<1x4xindex>
+//   CHECK-DAG:   %[[TRANSPOSE:.+]] = vector.transpose %[[BROADCAST_1x4]], [1, 0] : vector<1x4xindex> to vector<4x1xindex>
+//   CHECK-DAG:   %[[STEP_1:.+]] = vector.step : vector<1xindex>
+//   CHECK-DAG:   %[[BROADCAST_STRIDES0:.+]] = vector.broadcast %[[STRIDES]]#0 : index to vector<4x1xindex>
+//   CHECK-DAG:   %[[MULI_STRIDES:.+]] = arith.muli %[[TRANSPOSE]], %[[BROADCAST_STRIDES0]] : vector<4x1xindex>
+//   CHECK-DAG:   %[[BROADCAST_STRIDES1:.+]] = vector.broadcast %[[STRIDES]]#1 : index to vector<1xindex>
+//   CHECK-DAG:   %[[MULI_STEP:.+]] = arith.muli %[[STEP_1]], %[[BROADCAST_STRIDES1]] : vector<1xindex>
+//   CHECK-DAG:   %[[BROADCAST_STEP:.+]] = vector.broadcast %[[MULI_STEP]] : vector<1xindex> to vector<4x1xindex>
+//   CHECK-DAG:   %[[ADDI:.+]] = arith.addi %[[MULI_STRIDES]], %[[BROADCAST_STEP]] : vector<4x1xindex>
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir]: ditto

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir [hunk 8]
```diff
@@ -146,13 +181,150 @@ func.func @map_scatter_into_strided_output(
...
+//  CHECK-SAME:     %[[OUTPUT:[a-zA-Z0-9_]+]]
+//   CHECK-DAG:   %[[CST:.+]] = arith.constant dense<16> : vector<4x1xindex>
+//   CHECK-DAG:   %[[FLAT_OUTPUT:.+]] = memref.collapse_shape %[[OUTPUT]] {{.*}} memref<4x16xf4E2M1FN{{.*}} into memref<64xf4E2M1FN{{.*}}
+//   CHECK-DAG:   %[[STEP_4:.+]] = vector.step : vector<4xindex>
+//   CHECK-DAG:   %[[BROADCAST_1x4:.+]] = vector.broadcast %[[STEP_4]] : vector<4xindex> to vector<1x4xindex>
+//   CHECK-DAG:   %[[TRANSPOSE:.+]] = vector.transpose %[[BROADCAST_1x4]], [1, 0] : vector<1x4xindex> to vector<4x1xindex>
+//   CHECK-DAG:   %[[STEP_1:.+]] = vector.step : vector<1xindex>
+//       CHECK:   %[[MULI:.+]] = arith.muli %[[TRANSPOSE]], %[[CST]] overflow<nsw> : vector<4x1xindex>
+//       CHECK:   %[[BROADCAST_4x1:.+]] = vector.broadcast %[[STEP_1]] : vector<1xindex> to vector<4x1xindex>
+//       CHECK:   %[[ADDI:.+]] = arith.addi %[[MULI]], %[[BROADCAST_4x1]] overflow<nsw> : vector<4x1xindex>
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir]: ditto

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir [hunk 9]
```diff
@@ -146,13 +181,150 @@ func.func @map_scatter_into_strided_output(
...
+//   CHECK-DAG:   %[[CST_2:.+]] = arith.constant dense<2> : vector<4x1xindex>
+//   CHECK-DAG:   %[[FLAT_OUTPUT:.+]] = memref.collapse_shape %[[OUTPUT]] {{.*}} memref<8x16xf4E2M1FN> into memref<128xf4E2M1FN>
+//   CHECK-DAG:   %[[STEP_4:.+]] = vector.step : vector<4xindex>
+//   CHECK-DAG:   %[[BROADCAST_1x4:.+]] = vector.broadcast %[[STEP_4]] : vector<4xindex> to vector<1x4xindex>
+//   CHECK-DAG:   %[[TRANSPOSE:.+]] = vector.transpose %[[BROADCAST_1x4]], [1, 0] : vector<1x4xindex> to vector<4x1xindex>
+//   CHECK-DAG:   %[[STEP_1:.+]] = vector.step : vector<1xindex>
+//   CHECK-DAG:   %[[CMPI:.+]] = arith.cmpi ult, %[[TRANSPOSE]], %[[CST_2]] : vector<4x1xindex>
+//   CHECK-DAG:   %[[MULI:.+]] = arith.muli %[[TRANSPOSE]], %[[CST_16]] overflow<nsw> : vector<4x1xindex>
+//   CHECK-DAG:   %[[BROADCAST_4x1:.+]] = vector.broadcast %[[STEP_1]] : vector<1xindex> to vector<4x1xindex>
+//   CHECK-DAG:   %[[ADDI:.+]] = arith.addi %[[MULI]], %[[BROADCAST_4x1]] overflow<nsw> : vector<4x1xindex>
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir:278]: ditto

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir [hunk 10]
```diff
@@ -16,13 +16,27 @@ func.func @identity_map_scatter(
...
+//       CHECK:   %[[EXTRACT_1:.+]] = vector.extract %[[INPUT]][1] : vector<16xf32> from vector<4x16xf32>
+//       CHECK:   vector.store %[[EXTRACT_1]], %[[FLAT_OUTPUT]][%[[EXTRACT_IDX_1]]] : memref<64xf32>, vector<16xf32>
+//       CHECK:   %[[EXTRACT_IDX_2:.+]] = vector.extract %[[ADDI]][2, 0] : index from vector<4x1xindex>
+//       CHECK:   %[[EXTRACT_2:.+]] = vector.extract %[[INPUT]][2] : vector<16xf32> from vector<4x16xf32>
+//       CHECK:   vector.store %[[EXTRACT_2]], %[[FLAT_OUTPUT]][%[[EXTRACT_IDX_2]]] : memref<64xf32>, vector<16xf32>
+//       CHECK:   %[[EXTRACT_IDX_3:.+]] = vector.extract %[[ADDI]][3, 0] : index from vector<4x1xindex>
+//       CHECK:   %[[EXTRACT_3:.+]] = vector.extract %[[INPUT]][3] : vector<16xf32> from vector<4x16xf32>
+//       CHECK:   vector.store %[[EXTRACT_3]], %[[FLAT_OUTPUT]][%[[EXTRACT_IDX_3]]] : memref<64xf32>, vector<16xf32>
 
 // -----
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir:35]: I can't add a comment on the line, but can you expand the checks in `map_scatter_with_linearize_delinearize_idx` below? I don't see any tests that are checking the vector.scatter case anymore, so it would be good to have at least one test that has all the checks for it.

**Review by Max191 — COMMENTED** [review]
Overall LGTM, just some comments about the tests.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir (hunk 5 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir]: It's also a result of the input you provide to vectorization tool so imo it's good to have at least some way to test that the computations are correct here? I actually added it because I was unsure whether the index computation for the new case was correct with the changes so I had to look at those operations, and so I thought it was good to test as well. Also, maintenance is important, but imo it's becoming less of a concern these days for these tests with coding LLMs, so I would rather have correctness tested well. WDYT?

Comment (Max191) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir]: That is a good point. How about we keep one test with all the checks, then, and omit it for the rest?

Even with LLMs the maintenance burden can be bothersome, because if something changes upstream, then the integrate author will need to gather context, and update the corresponding tests properly.

I agree it is good for completeness to have the checks as an indicator when changes are made, but if there are multiple tests that check the same thing, then I think we add the checks only once. Correctness is also checked via e2e tests, so ensuring the correct indexing math is less important for the lit tests.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp (hunk 4 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeMapScatter.cpp]: That was an oversight, thanks for catching! Removed it now.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir (hunk 5 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir]: Ok, I updated it to only keep two now, one for the vector.scatter path and one for the extract/store path. I added explicit comments to those tests as well mentioning this. Could you have another look?

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir (hunk 10 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/decompose_map_scatter.mlir:35]: Expanded it now.

File: compiler/src/iree/compiler/Utils/Indexing.cpp [hunk 11]
```diff
@@ -148,7 +148,7 @@ std::optional<int64_t> getCoefficient(Value a, Value b) {
   if (a == b) {
     return 1;
   }
-  auto applyOp = dyn_cast<affine::AffineApplyOp>(a.getDefiningOp());
+  auto applyOp = dyn_cast_if_present<affine::AffineApplyOp>(a.getDefiningOp());
```
Comment (jtuyls) [inline compiler/src/iree/compiler/Utils/Indexing.cpp:151]: This was causing a test failure for rdna3 so fixed it here as well.

**Review by Max191 — APPROVED** [review]
LGTM, nice!
