### PR TITLE
Fix intermittent failure - functions with `_try_` in their name may fail spuriously.

### LINKED ISSUE #15488: Intermittent failure of iree/task/queue_test on arm64
Seeing this intermittently on arm64 linux runners.

The following tests FAILED:
	 97 - iree/task/queue_test (Failed)

```
[ RUN      ] QueueTest.TryStealAll
/work/runtime/src/iree/task/queue_test.cc:310: Failure
Expected equality of these values:
  &task_c
    Which is: 0xffffc6ae6260
  iree_task_queue_try_steal(&source_queue, &target_queue, 1000)
    Which is: NULL

/work/runtime/src/iree/task/queue_test.cc:311: Failure
Expected equality of these values:
  &task_d
    Which is: 0xffffc6ae6[220](https://github.com/openxla/iree/actions/runs/6802769949/job/18496627564?pr=15470#step:6:221)
  iree_task_queue_pop_front(&target_queue)
    Which is: NULL

/work/runtime/src/iree/task/queue_test.cc:316: Failure
Value of: iree_task_queue_is_empty(&source_queue)
  Actual: false
Expected: true
```

Looks like some memory model, atomic, mumble-mumble thing.

### PR DESCRIPTION
**Pull request by bjacob**
Fixes #15488.

This is the fix discussed there. Hat tip to @RoboTux and @freddan80 for the tenacious debugging - we certainly wouldn't have been able to complete this without your help!!

### CODE REVIEW

File: runtime/src/iree/task/queue_test.cc [hunk 1]
```diff
@@ -6,8 +6,26 @@
 
 #include "iree/task/queue.h"
 
+#include <thread>
+
 #include "iree/testing/gtest.h"
 
+// Like iree_task_queue_try_steal but retries until success.
+// This is used in this test as iree_task_queue_try_steal may (rarely) fail even
+// in simple tests that don't look particularly contended, see #15488.
```
Comment (RoboTux) [inline runtime/src/iree/task/queue_test.cc]:
```suggestion
// in simple tests with no contention, see #15488.
```

Or perhaps even "with no concurrency". The tests use queues allocated on the stack and there is no threading involve in the individual testcases so there is absolutely no concurrency on the mutex. So let's make it clear that it can fail even though we know the lock is free (e.g. on AArch64 due to interrupt, cache eviction or the like that causes the exclusive monitor to be dropped before the stxr).

File: runtime/src/iree/task/queue_test.cc [hunk 2]
```diff
@@ -6,8 +6,26 @@
...
+static iree_task_t* iree_task_queue_try_steal_until_success(
+    iree_task_queue_t* source_queue, iree_task_queue_t* target_queue,
+    iree_host_size_t max_tasks) {
+  while (true) {
+    iree_task_t* task =
+        iree_task_queue_try_steal(source_queue, target_queue, max_tasks);
+    if (task) {
+      return task;
+    }
+    std::this_thread::yield();
```
Comment (benvanik) [inline runtime/src/iree/task/queue_test.cc]: use iree_thread_yield from iree/base/internal/threading.h instead

**Review by benvanik — APPROVED** [review]

**Review by RoboTux — COMMENTED** [review]
LGTM otherwise. FWIW when running the test under valgrind in a loop it the failure would happens quite quickly. With this patch I didn't experience any failure for 5 minutes,
 as expected.

**Review by RoboTux — APPROVED** [review]
LGTM

File: runtime/src/iree/task/queue_test.cc (hunk 1 above)
Comment (bjacob) [reply runtime/src/iree/task/queue_test.cc]: done!

File: runtime/src/iree/task/queue_test.cc (hunk 2 above)
Comment (bjacob) [reply runtime/src/iree/task/queue_test.cc]: done! (didn't know about that one! I saw `iree_processor_yield` static in `synchronization.c` but it's kind of different, as the name indicates. I'm actually not clear as to what the exact difference is, and so i dont understand why this is both a CPU instruction that userspace code can directly run (as in `iree_processor_yield`) and a OS syscall (as in `iree_thread_yield`) ?

**Comment by bjacob** [comment]
@RoboTux 

> FWIW when running the test under valgrind in a loop it the failure would happens quite quickly. With this patch I didn't experience any failure for 5 minutes, as expected.

Great, thanks for the confirmation!

File: runtime/src/iree/task/queue_test.cc (hunk 2 above)
Comment (bjacob) [reply runtime/src/iree/task/queue_test.cc]: Self-answering, `iree_processor_yield` is just a hint that it's ok to deprioritize this thread, it doesn't immediately end the thread timeslice in the way a yield syscall does. So, the reason why `iree_processor_yield` is static in `synchronization.c` is that it is something you really only would use in the implementation of a spinlock.
