### PR TITLE
Fix the infinite application of TileAndDistribute on unpack ops.

### LINKED ISSUE #11607: Properly fix infinite application of TileAndDistribute to `unpack` ops with dynamic tile sizes
In #11601 we work around the problem that dynamic inner tile sizes currently trigger infinite application of tile-and-distribute on the unpack op, each time calling getTiledImplementation -> getSlice creating more and more extract_slice. As a temporary work-around, we annotate unpack ops with a custom already_tiled attribute to keep track of what's already been tiled.

What is the long-term fix, removing the need for this attribute?

@MaheshRavishankar (when you come back, not urgent), @hanhanW

### PR DESCRIPTION
**Pull request by hanhanW**
It removes a cleanup pattern that is no longer needed. The fix is using arith::MulIOp instead of affine ops to compute expanded output sizes in non-perfect tiling cases. Because the affine map could be too complicated, which triggers issues in affine ops simplification.

Fixes https://github.com/iree-org/iree/issues/11607

### CODE REVIEW

**Comment by hanhanW** [comment]
> It removes a cleanup pattern that is no longer needed. The fix is using arith::MulIOp instead of affine ops to compute expanded output sizes in non-perfect tiling cases. Because the affine map could be too complicated, which triggers issues in affine ops simplication.

Fixes https://github.com/iree-org/iree/issues/11607

**Comment by hanhanW** [comment]
@bjacob this would make the unpack dispatch be `unpack + extract_slice`, not a single `unpack` op. FYI

**Review by bjacob — APPROVED** [review]
Woohoo! 🥳 Thank you for the fix!

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
I'd like to take a look at this with fresh eyes in the morning

**Comment by hanhanW** [comment]
> I'd like to take a look at this with fresh eyes in the morning

SG, that's also why I did not merge the commit!

File: compiler/src/iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp [hunk 1]
```diff
@@ -253,6 +253,22 @@ static LogicalResult convertToDestinationPassingStyle(OpBuilder &b,
       [&](tensor::EmptyOp emptyTensorOp) -> WalkResult {
         for (auto result : emptyTensorOp->getResults()) {
           if (!result.getType().isa<RankedTensorType>()) continue;
+
+          // The tensor.empty op created by tiling unpack ops is intended to be
+          // a stack allocation. We can't replace it with destination buffer
+          // because it is larger than the destination buffer.
+          bool isUsedByNonPerfectUnpack = false;
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp]: Could you post the IR that is obtained from the tiling of unpack.. I am wondering if we should just change `BufferizationAnalysis` to handle `UnPackOp` specially so that the `tensor.empty` automatically doesnt come into a equivalence set with a store. Then you dont need the special handling. If you post the IR, I can give you more pointers.

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp]: I think it's hard to replace the empty op with `flow.tensor.load` stuff. The empty op could have more elements than the destination buffer. In any case, here is the dump before the pass: https://gist.github.com/hanhanW/d95b1c2c1f8a5e4b7b01c5737b42a78a/raw

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp]: I see what you are saying. If you want to avoid some `tensor.empty` from being converted away, its probably better to do a pre-pass and convert `tensor.empty -> unpack` operation to `bufferization.alloc_tensor -> unpack` operation. This is a definitive hint to the bufferization infra to create an allocation. This also matches the intent of the `tensor.empty` and having split `bufferization.alloc_tensor` out of the `tensor.empty` semantics. The former is meant for real allocations, while latter is meant to just be a proxy for tensor types.

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp]: Good point, thanks for the suggestion. This makes sense to me!

File: compiler/src/iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp [hunk 2]
```diff
@@ -463,6 +465,33 @@ static LogicalResult adaptComputeConsumerToAvoidStackAllocation(
...
 }
 
+/// Replaces a tensor.empty op with bufferization.alloc_tensor op which is
+/// created by tiling tensor.unpack op. It is intended because tiling unpack ops
+/// with non-perfect sizes needs extra elements. See the tiling implementation
+/// of tensor.unpack op for more details.
+static LogicalResult replaceUnpackEmptyWithAllocTensor(OpBuilder &b,
+                                                       func::FuncOp funcOp) {
+  funcOp.walk<WalkOrder::PreOrder>([&](tensor::EmptyOp emptyOp) {
+    bool isUsedByNonPerfectUnpack = false;
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp]: Wouldn't this be easier if you just walk for the unpack operation and look at operand that is a `tensor.empty`. (You can delete the `tensor.empty` if it has no other uses).

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]

**Review by MaheshRavishankar — APPROVED** [review]
Awesome! Thanks!
