### PR TITLE
[LLVMCPU] Disable split reduction for operations with index semantics.

### LINKED ISSUE #14934: Different Results for CPU and CUDA backend
### What happened?

I'm getting a different result from the PyTorch and IREE path for the [NLLLoss](https://pytorch.org/docs/stable/generated/torch.nn.NLLLoss.html) lowering. The result from the CPU backend is incorrect while the result from the CUDA backend is correct.

### Steps to reproduce your issue

To reproduce the issue, compile and run the following IR:
```
#map = affine_map<(d0) -> (d0)>
#map1 = affine_map<(d0) -> ()>
module attributes {torch.debug_module_name = "train_func"} {
  ml_program.global private mutable @global_seed(dense<0> : tensor<i64>) : tensor<i64>
  func.func @forward(%arg0: tensor<4096x8192xf32>, %arg1: tensor<4096xi64>) -> tensor<f32> {
    %cst = arith.constant 0.000000e+00 : f32
    %c-100 = arith.constant -100 : index
    %cst_0 = arith.constant 4.096000e+03 : f32
    %0 = tensor.empty() : tensor<4096xf32>
    %1 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel"]} ins(%arg1 : tensor<4096xi64>) outs(%0 : tensor<4096xf32>) {
    ^bb0(%in: i64, %out: f32):
      %5 = arith.index_cast %in : i64 to index
      %6 = arith.cmpi eq, %5, %c-100 : index
      %7 = linalg.index 0 : index
      %extracted = tensor.extract %arg0[%7, %5] : tensor<4096x8192xf32>
      %8 = arith.negf %extracted : f32
      %9 = arith.select %6, %cst, %8 : f32
      linalg.yield %9 : f32
    } -> tensor<4096xf32>
    %2 = tensor.empty() : tensor<f32>
    %3 = linalg.fill ins(%cst : f32) outs(%2 : tensor<f32>) -> tensor<f32>
    %4 = linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["reduction"]} ins(%1 : tensor<4096xf32>) outs(%3 : tensor<f32>) {
    ^bb0(%in: f32, %out: f32):
      %5 = arith.divf %in, %cst_0 : f32
      %6 = arith.addf %5, %out : f32
      linalg.yield %6 : f32
    } -> tensor<f32>
    return %4 : tensor<f32>
  }
}
```

For CPU (producing incorrect results):
1.) Compilation Command:
```
iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary     --iree-hal-target-backends=llvm-cpu --mlir-print-debuginfo     --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host     --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64     --iree-vm-bytecode-module-strip-source-map=false --iree-util-zero-fill-elided-attrs     --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false    --iree-consteval-jit-debug=true   --iree-stream-resource-max-allocation-size=3221225472 nll_loss.mlir -o nll_loss.vmfb
```
2.) Runtime Command:
```
iree-run-module --module=nll_loss.vmfb  --device=local-task --function=forward --input=@log_softmax.npy --input=@view_12.npy
```
Please download the files [log_softmax.npy](https://storage.googleapis.com/shark-public/avi/log_softmax.npy), and [view_12.npy](https://storage.googleapis.com/shark-public/avi/view_12.npy).

For CUDA (producing correct results):
1.) Compilation Command:
```
iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary     --iree-hal-target-backends=cuda --mlir-print-debuginfo     --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host     --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64     --iree-vm-bytecode-module-strip-source-map=false --iree-util-zero-fill-elided-attrs     --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false --iree-opt-const-expr-hoisting=false   --iree-consteval-jit-debug=true   --iree-stream-resource-max-allocation-size=3221225472 nll_loss.mlir -o nll_loss.vmfb
```
2.) Runtime Command:
```
iree-run-module --module=nll_loss.vmfb  --device=cuda --function=forward --input=@log_softmax.npy --input=@view_12.npy
```

### What component(s) does this issue relate to?

MLIR, Compiler, Runtime

### Version information

de4f4e539a1e1dd7f0ffe2ec2eee32b4587faa12

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
The core method used by the pass does not support operations with indexing semantics. Disable the split reduction pass for ops with indexing semantics.

Also add some previously missed tests.

Fixes #14934

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.h [hunk 1]
```diff
@@ -56,7 +56,7 @@ std::unique_ptr<OperationPass<func::FuncOp>> createLLVMCPUPeelPass();
 
 /// Pass to perform SplitReduction transformations of `LinalgOp`s.
 std::unique_ptr<OperationPass<func::FuncOp>>
-createLLVMCPUSplitReductionPass(bool enableReassociateFpReductions = false);
+createLLVMCPUSplitReductionPass(bool enableReassociateFpReductions = true);
```
Comment (Groverkss) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.h]: Not sure how this change is related to this patch.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.td [hunk 2]
```diff
@@ -105,7 +105,7 @@ def LLVMCPUSplitReduction : Pass<"iree-llvmcpu-split-reduction", "func::FuncOp">
   let constructor = "mlir::iree_compiler::createLLVMCPUSplitReductionPass()";
   let options = [
     Option<"enableFpReductionReordering", "enable-fp-reduction-reordering",
-      "bool", /*default=*/"false",
+      "bool", /*default=*/"true",
```
Comment (Groverkss) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.td]: Not sure how this change is related to this patch.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUSplitReduction.cpp [hunk 3]
```diff
@@ -67,6 +67,11 @@ LogicalResult splitReductionPrecondition(Operation *op,
     LLVM_DEBUG(llvm::dbgs() << "doesn't have exactly 1 input\n");
     return failure();
   }
+  if (linalgOp.hasIndexSemantics()) {
```
Comment (Groverkss) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUSplitReduction.cpp:72]: Could we write how to fix this here, maybe? I think you had a comment on the GitHub issue. A link to that also would be good.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.h (hunk 1 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.h]: Oh, the reassociation is true by default in IREE, but the pass has it false by default. So I made those consistent. Ill update the PR message.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.td (hunk 2 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.td]: Oh, the reassociation is true by default in IREE, but the pass has it false by default. So I made those consistent. Ill update the PR message.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUSplitReduction.cpp (hunk 3 above)
Comment (dcaballe) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUSplitReduction.cpp:72]: Yeah, that would help. It's not clear to me what is missing

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.h (hunk 1 above)
Comment (dcaballe) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.h]: I think we should remove the default value. Enabling or disabling fp reassoc has significant consequences that every caller should think about.

**Review by dcaballe — APPROVED** [review]
LG % pending comments. Thanks!

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.h (hunk 1 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.h]: Reverted this.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.td (hunk 2 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.td]: Reverted this.
