### PR TITLE
Early inc to avoid invalidation

### LINKED ISSUE #9925: iree-import-tf is crashing in several Colab notebooks
### What happened?

Several of our sample Colab notebooks are currently broken, with unsymbolized stack traces like
```
[2022-07-21T00:27:42Z] CompilerToolError: Error invoking IREE compiler tool iree-import-tf
[2022-07-21T00:27:42Z] Diagnostics:
[2022-07-21T00:27:42Z] TensorFlow crashed, please file a bug on https://github.com/tensorflow/tensorflow/issues with the trace below.
[2022-07-21T00:27:42Z] Stack dump:
[2022-07-21T00:27:42Z] 0.	Program arguments: /usr/src/github/iree/.notebook.venv/lib/python3.7/site-packages/iree/tools/tf/iree-import-tf /tmp/resaved_model --tf-import-type=savedmodel_v1 --tf-savedmodel-exported-names= --tf-savedmodel-tags=serve --mlir-print-debuginfo --save-temp-tf-input=/tmp/iree/colab_artifacts/mobilenet_v2_tf_input.mlir --save-temp-iree-input=/tmp/iree/colab_artifacts/mobilenet_v2_iree_input.mlir
[2022-07-21T00:27:42Z]  #0 0x0000000009e68891 (/usr/src/github/iree/.notebook.venv/lib/python3.7/site-packages/iree/tools/tf/iree-import-tf+0x9e68891)
[2022-07-21T00:27:42Z]  #1 0x0000000009e669a5 (/usr/src/github/iree/.notebook.venv/lib/python3.7/site-packages/iree/tools/tf/iree-import-tf+0x9e669a5)
```

This was first reported on the https://buildkite.com/iree/iree-samples/builds/416 nightly build (Wed 20th Jul at 5:13 PM, https://github.com/iree-org/iree/releases/tag/candidate-20220720.210).

Failing notebooks:
* [`variables_and_state.ipynb`](https://colab.research.google.com/github/iree-org/iree/blob/main/samples/variables_and_state/variables_and_state.ipynb)
* [`tensorflow_hub_import.ipynb`](https://colab.research.google.com/github/iree-org/iree/blob/main/samples/colab/tensorflow_hub_import.ipynb)

### Steps to reproduce your issue

This reproduces in both the nightly buildkite CI pipeline and when running the notebooks manually:

1. Open a notebook like [`variables_and_state.ipynb`](https://colab.research.google.com/github/iree-org/iree/blob/main/samples/variables_and_state/variables_and_state.ipynb)
2. Click `Runtime` -> `Run all`
3. Scroll to where `iree-import-tf` / `tfc.compile_module()` is run
4. See the error messages

### What component(s) does this issue relate to?

Frontends

### Version information

Started with https://github.com/iree-org/iree/releases/tag/candidate-20220720.210 . This could also be related to the TensorFlow version - Colab currently bundles 2.8.2 and we test with 2.8.0: https://github.com/iree-org/iree/blob/068b172e04e33b3d0d1b4c784f425ee759e2bfcb/build_tools/docker/samples/Dockerfile#L29

### Additional context

It's a bit surprising that notebooks failed in this way without anything else failing. We are likely missing some presubmit test coverage.

### PR DESCRIPTION
**Pull request by jpienaar**
Fixes #9925

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

File: integrations/tensorflow/iree_tf_compiler/TF/LowerGlobalTensors.cpp [hunk 1]
```diff
@@ -179,7 +179,7 @@ void LowerGlobalTensors::runOnOperation() {
           *latticeElement->getValue().ops.begin();
       ml_program::GlobalOp globalOp = symbolRefMap[globalTensor];
 
-      for (Operation *user : val.getUsers()) {
+      for (Operation *user : llvm::make_early_inc_range(val.getUsers())) {
```
Comment (ScottTodd) [inline integrations/tensorflow/iree_tf_compiler/TF/LowerGlobalTensors.cpp:182]: Can you add a test case that runs on presubmit for this?

**Review by ScottTodd — APPROVED** [review]
Thanks! I'll check the build status after this lands. There were two different post-submit Colab notebooks failing, and they might have different root causes.

File: integrations/tensorflow/iree_tf_compiler/TF/LowerGlobalTensors.cpp (hunk 1 above)
Comment (jpienaar) [reply integrations/tensorflow/iree_tf_compiler/TF/LowerGlobalTensors.cpp:182]: Good idea, http://github.com/iree-org/iree/pull/9982, only triggers with ASAN or TSAN but I believe those are now on presubmit.
