### PR TITLE
[LinalgExt] Fix map_scatter verifier

### LINKED ISSUE #22965: Assertion failure in MapScatterOp::verify when region block is missing a terminator
### What happened?

**Description**
The compiler crashes during verification of the `map_scatter` operation because it assumes a terminator is present in the internal block. 

**Output**
```
iree-opt: /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Block.cpp:245: mlir::Operation *mlir::Block::getTerminator(): Assertion `mightHaveTerminator()' failed.
Please report issues to https://github.com/iree-org/iree/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: /workdir/builds/iree/tools/iree-opt test.mlir
 #0 0x000055916a90c74b backtrace (/workdir/builds/iree/tools/iree-opt+0x9174b)
 #1 0x00007fab0ef1f828 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /workdir/sources/iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:842:13
 #2 0x00007fab0ef175e3 llvm::sys::RunSignalHandlers() /workdir/sources/iree/third_party/llvm-project/llvm/lib/Support/Signals.cpp:109:18
 #3 0x00007fab0ef222e4 SignalHandler(int, siginfo_t*, void*) /workdir/sources/iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:429:38
 #4 0x00007faae9035520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x00007faae90899fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #6 0x00007faae9035476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #7 0x00007faae901b7f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #8 0x00007faae901b71b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #9 0x00007faae902ce96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#10 0x00007fab0f09c5e6 llvm::ilist_detail::node_base_prevnext<llvm::ilist_node_base<false, void>, false>::getPrev() const /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/ilist_node_base.h:27:38
#11 0x00007fab0f09c5e6 llvm::ilist_node_impl<llvm::ilist_detail::node_options<mlir::Operation, false, false, void, false, void> >::getPrev() /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/ilist_node.h:104:59
#12 0x00007fab0f09c5e6 llvm::ilist_iterator<llvm::ilist_detail::node_options<mlir::Operation, false, false, void, false, void>, true, false>::operator++() /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/ilist_iterator.h:187:36
#13 0x00007fab0f09c5e6 llvm::simple_ilist<mlir::Operation>::rbegin() /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/simple_ilist.h:122:38
#14 0x00007fab0f09c5e6 llvm::simple_ilist<mlir::Operation>::back() /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/simple_ilist.h:139:30
#15 0x00007fab0f09c5e6 mlir::Block::back() /workdir/sources/iree/third_party/llvm-project/mlir/include/mlir/IR/Block.h:152:41
#16 0x00007fab0f09c5e6 mlir::Block::getTerminator() /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Block.cpp:246:11
#17 0x00007fab106deb1e decltype(auto) llvm::cast<mlir::iree_compiler::IREE::LinalgExt::YieldOp, mlir::Operation>(mlir::Operation*) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/Casting.h:571:53
#18 0x00007fab106deb1e mlir::iree_compiler::IREE::LinalgExt::MapScatterOp::verify() /workdir/sources/iree/compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp:639:18
#19 0x00007fab10665cd4 llvm::failed(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:71:42
#20 0x00007fab10665cd4 mlir::Op<mlir::iree_compiler::IREE::LinalgExt::MapScatterOp, mlir::OpTrait::OneRegion, mlir::OpTrait::VariadicResults, mlir::OpTrait::ZeroSuccessors, mlir::OpTrait::NOperands<2u>::Impl, mlir::OpTrait::SingleBlock, mlir::OpTrait::SingleBlockImplicitTerminator<mlir::iree_compiler::IREE::LinalgExt::YieldOp>::Impl, mlir::OpTrait::OpInvariants, mlir::TilingInterface::Trait, mlir::MemoryEffectOpInterface::Trait, mlir::DestinationStyleOpInterface::Trait, mlir::iree_compiler::IREE::LinalgExt::LinalgExtOp::Trait>::verifyInvariants(mlir::Operation*) /workdir/sources/iree/third_party/llvm-project/mlir/include/mlir/IR/OpDefinition.h:2053:9
#21 0x00007fab10661f8d llvm::unique_function<llvm::LogicalResult (mlir::Operation*) const>::operator()(mlir::Operation*) const /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/FunctionExtras.h:390:12
#22 0x00007fab10661f8d mlir::RegisteredOperationName::Model<mlir::iree_compiler::IREE::LinalgExt::MapScatterOp>::verifyInvariants(mlir::Operation*) /workdir/sources/iree/third_party/llvm-project/mlir/include/mlir/IR/OperationSupport.h:555:14
#23 0x00007fab0f3fce63 llvm::failed(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:71:42
#24 0x00007fab0f3fce63 (anonymous namespace)::OperationVerifier::verifyOnEntrance(mlir::Operation&) /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Verifier.cpp:175:25
#25 0x00007fab0f3fce63 auto (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_2::operator()<mlir::Operation>(mlir::Operation*) const /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Verifier.cpp:296:45
#26 0x00007fab0f3fce63 auto (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_1::operator()<(anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_2>((anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_2&&, llvm::PointerUnion<mlir::Operation*, mlir::Block*>) const /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Verifier.cpp:276:16
#27 0x00007fab0f3fce63 (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&) /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Verifier.cpp:295:16
#28 0x00007fab0f3fce63 (anonymous namespace)::OperationVerifier::verifyOpAndDominance(mlir::Operation&) /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Verifier.cpp:81:14
#29 0x00007fab0f3fdc5b llvm::failed(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:71:42
#30 0x00007fab0f3fdc5b (anonymous namespace)::OperationVerifier::verifyOnExit(mlir::Operation&)::$_3::operator()(mlir::Operation*) const /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Verifier.cpp:225:9
#31 0x00007fab0f3fdc5b auto void mlir::parallelForEach<mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOnExit(mlir::Operation&)::$_3>(mlir::MLIRContext*, mlir::Operation**, mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOnExit(mlir::Operation&)::$_3&&)::'lambda'(mlir::Operation**&&)::operator()<mlir::Operation*&>(mlir::Operation**&&) const /workdir/sources/iree/third_party/llvm-project/mlir/include/mlir/IR/Threading.h:120:12
#32 0x00007fab0f3fdc5b llvm::LogicalResult mlir::failableParallelForEach<mlir::Operation**, void mlir::parallelForEach<mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOnExit(mlir::Operation&)::$_3>(mlir::MLIRContext*, mlir::Operation**, mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOnExit(mlir::Operation&)::$_3&&)::'lambda'(mlir::Operation**&&)>(mlir::MLIRContext*, mlir::Operation**, mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOnExit(mlir::Operation&)::$_3&&) /workdir/sources/iree/third_party/llvm-project/mlir/include/mlir/IR/Threading.h:46:18
#33 0x00007fab0f3fdc5b void mlir::parallelForEach<mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOnExit(mlir::Operation&)::$_3>(mlir::MLIRContext*, mlir::Operation**, mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOnExit(mlir::Operation&)::$_3&&) /workdir/sources/iree/third_party/llvm-project/mlir/include/mlir/IR/Threading.h:119:9
#34 0x00007fab0f3fdc5b void mlir::parallelForEach<llvm::SmallVector<mlir::Operation*, 6u>&, (anonymous namespace)::OperationVerifier::verifyOnExit(mlir::Operation&)::$_3>(mlir::MLIRContext*, llvm::SmallVector<mlir::Operation*, 6u>&, (anonymous namespace)::OperationVerifier::verifyOnExit(mlir::Operation&)::$_3&&) /workdir/sources/iree/third_party/llvm-project/mlir/include/mlir/IR/Threading.h:131:3
#35 0x00007fab0f3fdc5b (anonymous namespace)::OperationVerifier::verifyOnExit(mlir::Operation&) /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Verifier.cpp:224:3
#36 0x00007fab0f3fdc5b auto (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0::operator()<mlir::Operation>(mlir::Operation*) const /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Verifier.cpp:287:53
#37 0x00007fab0f3fdc5b auto (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_1::operator()<(anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0>((anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0&&, llvm::PointerUnion<mlir::Operation*, mlir::Block*>) const /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Verifier.cpp:276:16
#38 0x00007fab0f3fdc5b (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&) /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Verifier.cpp:287:15
#39 0x00007fab0f3fdc5b (anonymous namespace)::OperationVerifier::verifyOpAndDominance(mlir::Operation&) /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Verifier.cpp:81:14
#40 0x00007fab0f3fb5a7 mlir::verify(mlir::Operation*, bool) /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Verifier.cpp:426:1
#41 0x00007fab3229cd56 llvm::failed(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:71:42
#42 0x00007fab3229cd56 (anonymous namespace)::OperationParser::finalize() /workdir/sources/iree/third_party/llvm-project/mlir/lib/AsmParser/Parser.cpp:931:48
#43 0x00007fab3229cd56 (anonymous namespace)::TopLevelOperationParser::parse(mlir::Block*, mlir::Location) /workdir/sources/iree/third_party/llvm-project/mlir/lib/AsmParser/Parser.cpp:2876:20
#44 0x00007fab322989b5 mlir::parseAsmSourceFile(llvm::SourceMgr const&, mlir::Block*, mlir::ParserConfig const&, mlir::AsmParserState*, mlir::AsmParserCodeCompleteContext*) /workdir/sources/iree/third_party/llvm-project/mlir/lib/AsmParser/Parser.cpp:0:41
#45 0x00007fab0f49cfe8 mlir::parseSourceFile(std::shared_ptr<llvm::SourceMgr> const&, mlir::Block*, mlir::ParserConfig const&, mlir::LocationAttr*) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Parser/Parser.cpp:0:10
#46 0x00007fab0ec9ea37 llvm::failed(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:71:42
#47 0x00007fab0ec9ea37 mlir::OwningOpRef<mlir::ModuleOp> mlir::detail::parseSourceFile<mlir::ModuleOp, std::shared_ptr<llvm::SourceMgr> const&>(mlir::ParserConfig const&, std::shared_ptr<llvm::SourceMgr> const&) /workdir/sources/iree/third_party/llvm-project/mlir/include/mlir/Parser/Parser.h:158:7
#48 0x00007fab10dbe09c mlir::OwningOpRef<mlir::ModuleOp>::operator mlir::OwningOpRef<mlir::Operation*>() && /workdir/sources/iree/third_party/llvm-project/mlir/include/mlir/IR/OwningOpRef.h:64:42
#49 0x00007fab10dbe09c mlir::parseSourceFileForTool(std::shared_ptr<llvm::SourceMgr> const&, mlir::ParserConfig const&, bool) /workdir/sources/iree/third_party/llvm-project/mlir/include/mlir/Tools/ParseUtilities.h:31:12
#50 0x00007fab10dbe09c performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:521:33
#51 0x00007fab10dbd6c8 processBuffer(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef, mlir::MlirOptMainConfig const&, mlir::DialectRegistry&, mlir::SourceMgrDiagnosticVerifierHandler*, llvm::ThreadPoolInterface*) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:673:12
#52 0x00007fab10dbd6c8 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_3::operator()(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef, llvm::raw_ostream&) const /workdir/sources/iree/third_party/llvm-project/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:771:12
#53 0x00007fab10dbd6c8 llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_3>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:46:12
#54 0x00007fab10dc6934 llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>::operator()(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&) const /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:69:12
#55 0x00007fab10dc6934 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0::operator()(llvm::StringRef) const /workdir/sources/iree/third_party/llvm-project/mlir/lib/Support/ToolUtilities.cpp:94:13
#56 0x00007fab10dc5351 void llvm::interleave<llvm::StringRef const*, mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0, void llvm::interleave<llvm::SmallVector<llvm::StringRef, 8u>, mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0, llvm::raw_ostream, llvm::StringRef>(llvm::SmallVector<llvm::StringRef, 8u> const&, llvm::raw_ostream&, mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0, llvm::StringRef const&)::'lambda'(), void>(llvm::SmallVector<llvm::StringRef, 8u>, llvm::SmallVector<llvm::StringRef, 8u>, mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0, llvm::raw_ostream) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLExtras.h:2230:16
#57 0x00007fab10dc5351 void llvm::interleave<llvm::SmallVector<llvm::StringRef, 8u>, mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0, llvm::raw_ostream, llvm::StringRef>(llvm::SmallVector<llvm::StringRef, 8u> const&, llvm::raw_ostream&, mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0, llvm::StringRef const&) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLExtras.h:2250:3
#58 0x00007fab10dc5351 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Support/ToolUtilities.cpp:97:3
#59 0x00007fab10d9d16e mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:776:26
#60 0x00007fab0eca583a llvm::failed(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:71:42
#61 0x00007fab0eca583a ireeOptMainFromCL(int, char**, llvm::StringRef, mlir::DialectRegistry&) /workdir/sources/iree/compiler/src/iree/compiler/API/Internal/IREEOptToolEntryPoint.cpp:147:7
#62 0x00007fab0eca583a ireeOptRunMain /workdir/sources/iree/compiler/src/iree/compiler/API/Internal/IREEOptToolEntryPoint.cpp:170:14
#63 0x00007faae901cd90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#64 0x00007faae901ce40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#65 0x000055916a8d0c15 _start (/workdir/builds/iree/tools/iree-opt+0x55c15)
Aborted (core dumped)
```

### Steps to reproduce your issue

**Minimal MLIR program (test.mlir)**
```
"builtin.module"() ({
  %0 = "tensor.empty"() : () -> tensor<1xf16>
  %1 = "tensor.empty"() : () -> tensor<1xf16>
  %2 = "iree_linalg_ext.map_scatter"(%0, %1) ({
  ^bb0(%arg1: index):
    %3 = "arith.constant"() <{value = true}> : () -> i1
  }) : (tensor<1xf16>, tensor<1xf16>) -> tensor<1xf16>
}) : () -> ()
```

**Command**
```
iree-opt test.mlir
```

### What component(s) does this issue relate to?

MLIR

### Version information

[d4b9bb0150db9e3c20673c912cb785e988846936](https://github.com/iree-org/iree/commit/d4b9bb0150db9e3c20673c912cb785e988846936)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sommerlukas**
Fix verification of the `iree_linalg_ext.map_scatter` operation for the case where the `transformation_region` does not have a terminator. So far, we tried to verify the nested `yield` operation before region traits, after this change, this check happens in `verifyRegions` as required.

This is based on the bug reported from fuzzing and fixes https://github.com/iree-org/iree/issues/22965.

### CODE REVIEW

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp [hunk 1]
```diff
@@ -636,6 +636,10 @@ LogicalResult MapScatterOp::verify() {
                     llvm::IsaPred<IndexType>)) {
     return emitOpError("expected block arguments to be index types");
   }
+  if (!transformBody.mightHaveTerminator() ||
+      !isa<IREE::LinalgExt::YieldOp>(transformBody.getTerminator())) {
+    return emitOpError("expected transformation_region to have a terminator");
+  }
```
Comment (sommerlukas) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: An alternative to manually verifying the existence of the terminator would be to use the `SingleBlockImplicitTerminator` trait here, which would also ensure that there is only a single block (currently also implicitly assumed, but not verified by the verifier). 

If it's OK to limit the region to a single block and have the terminator implicit, I can switch to the trait instead. If not, it's probably worth verifying that there's only a single block as assumed.

Comment (kuhar) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: FTR, I don't have strong opinions on this either way

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/test/invalid.mlir [hunk 2]
```diff
@@ -555,6 +555,19 @@ func.func @map_scatter_wrong_mask_type(
...
 // -----
 
+func.func @map_scatter_no_terminator(
+    %input: memref<4xf32>, %output: memref<4xf32>
+){
+  // expected-error@+1 {{expected transformation_region to have a terminator}}
+  "iree_linalg_ext.map_scatter"(%input, %output) ({
+  ^bb0(%idx0: index):
+    %0 = "arith.constant"() <{value = true}> : () -> i1
+  }) : (memref<4xf32>, memref<4xf32>) -> ()
```
Comment (kuhar) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/test/invalid.mlir:567]: Do we have to use the generic IR format here?

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp (hunk 1 above)
Comment (sommerlukas) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: I had overlooked this initially, `MapScatterOp` already inherits `SingleBlockImplicitTerminator` from its base-class `IREELinalgExt_Op`. I'll investigate why the verifier of that trait didn't catch this case.

**Review by hanhanW — COMMENTED** [review]
It seems to be a bug in upstream. All the linalg_ext ops has `SingleBlockImplicitTerminator` trait, and I think it should be captured by the upstream verifier: [verifyRegionTrait method](https://github.com/llvm/llvm-project/blob/ccb47d0fb9d01d44764fa4ca5c6dcf239ab76ed2/mlir/include/mlir/IR/OpDefinition.h#L980-L1001)

https://github.com/iree-org/iree/blob/9273e925c1319312b1f7a4e9ad0d6b2f4c28995c/compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td#L25-L34

Here is the upstream documentation: https://mlir.llvm.org/docs/DefiningDialects/Operations/#verification-ordering

> The verification of an operation involves several steps,
>
> 1. StructuralOpTrait will be verified first, they can be run independently.
> 2. `verifyInvariants` which is constructed by ODS, it verifies the type, attributes, .etc.
> 3. Other Traits/Interfaces that have marked their verifier as verifyTrait or verifyWithRegions=0.
> 4. Custom verifier which is defined in the op and has been marked hasVerifier=1

I thought the fix you have is in step `4` and it should be captured in step `3`.

My concern is that it can happen in other ops as well and it is better to fix the root cause.

**Comment by hanhanW** [comment]
Oh, I see the issue: https://github.com/llvm/llvm-project/blob/ccb47d0fb9d01d44764fa4ca5c6dcf239ab76ed2/mlir/include/mlir/IR/OpDefinition.h#L983-L985. It allows empty region that I'm not expecting.

```
        // Empty regions are fine.
        if (region.empty())
          continue;
```

It looks like an upstream bug to me because it mismatches the documentation: https://mlir.llvm.org/docs/Traits/#single-block-with-implicit-terminator

> This trait implies the SingleBlock above, but adds the additional requirement that the single block must terminate with TerminatorOpType.

It must terminate with the `TerminatorOpType`. Let me try if we can remove the check or not.

**Comment by hanhanW** [comment]
> It must terminate with the TerminatorOpType. Let me try if we can remove the check or not.

It is not a simple fix (i.e., removing the check) because it breaks a lot of tests. E.g., scf.if op has the trait, but some test cases do not have the yield op: https://github.com/llvm/llvm-project/blob/ccb47d0fb9d01d44764fa4ca5c6dcf239ab76ed2/mlir/test/Analysis/DataFlow/test-next-access.mlir#L105-L117

```mlir
// CHECK-LABEL: @conditional
func.func @conditional(%cond: i1, %arg0: memref<f32>) {
  // CHECK:      name = "pre"
  // CHECK-SAME: next_access = {{\[}}["post", "then"]]
  memref.load %arg0[] {name = "pre"}: memref<f32>
  scf.if %cond {
    // CHECK:      name = "then"
    // CHECK-SAME: next_access = {{\[}}["post"]]
    memref.load %arg0[] {name = "then"} : memref<f32>
  }
  memref.load %arg0[] {name = "post"} : memref<f32>
  return
}
```

It also breaks IREE in the codegen pipeline. I did not look at details, and my guess is that we create few ops without the terminator, like above example.

The best fix in my mind now is adding the trait (either in IREE or upstream) and use that trait for LinalgExt ops. What do you think?

EDIT: I think we can name the new trait as `SingleBlockExplicitTerminator`.

**Comment by Max191** [comment]
> It allows empty region that I'm not expecting.

The failing case in this PR and the issue does have a region, though, so allowing empty regions may be an unrelated bug. The bug in this PR may need some more narrowing down.

**Comment by sommerlukas** [comment]
I agree with @Max191, the region isn't empty here (and neither is the block), so the empty region is not the problem here.

I've dug deeper into this issue, and it is related to the order of verification.

Operation verification in `Verifier.cpp` happens in two phases for each operation.
* The first phase happens on the first visit to the operation (`verifyOnEntrance`). This is before nested operations have been created. It verifies traits and also calls the custom `verify()`.
* The second phase happens when the operation is touched for the second time (`verifyOnExit`). This is after nested operations have been created. It verifies region traits and can also call a custom `verifyRegions()`.

The documentation also states that: 
> For verificaiton which needs to access the nested operations, you should use `hasRegionVerifier` to ensure that it won’t access any ill-formed operation.

In contrast to `SingleBlock`, the `SingleBlockImplictTerminator` trait only implements `verifyRegionTrait`, but not `verifyTrait` (which makes sense due to the above), so `SingleBlockImplicitTerminator` is only verified in the second phase, whereas we currently try to verify things about the `YieldOp` in the first phase.

The issue here is that we currently have checks in `verify` that should be in `verifyRegions`, where they would only happen after the verification of `SingleBlockImplicitTerminator`.

I've therefore enabled `hasRegionVerifier` for the operation and moved the checks relating to the `YieldOp` to `verifyRegions`.

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/test/invalid.mlir (hunk 2 above)
Comment (sommerlukas) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/test/invalid.mlir:567]: Yes, we need to use generic format here, because in contrast to the generated custom parser, the generic parser does not implicitly insert the terminator.

Comment (kuhar) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/test/invalid.mlir:567]: Maybe add a code comment that explains this?

**Review by hanhanW — APPROVED** [review]
Thanks for digging into this and the sharing!

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/test/invalid.mlir (hunk 2 above)
Comment (sommerlukas) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/test/invalid.mlir:567]: Good idea, I've added a comment.
