### PR TITLE
[LLVMGPU] Fix linking error when one of the variants has no modules.

### LINKED ISSUE #21024: Crash during  GPU linking
Attempting to do hip kernel injection fails due to a crash in the gpu linking

Using the following patch https://github.com/nod-ai/shark-ai/pull/1585

```
iree-compile artifacts/model.mlir -o artifacts/model.vmfb \
        --iree-hal-target-device=hip \
        --iree-hip-target=gfx1100 \
        --iree-opt-aggressively-propagate-transposes \
        --iree-opt-level=O3 \
        --iree-dispatch-creation-enable-aggressive-fusion=true \
        --iree-hal-executable-debug-level=3 \
        --iree-hal-indirect-command-buffers=true  \
        --iree-codegen-enable-default-tuning-specs=true \
        --iree-stream-resource-memory-model=discrete  \
        --iree-hal-memoization=true \
        --iree-preprocessing-transform-spec-filename=topk_spec.mlir
```

[topk_f.zip](https://github.com/user-attachments/files/20618700/topk_f.zip)

[model.zip](https://github.com/user-attachments/files/20618708/model.zip)

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
Fixes #21024

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/Utils/LinkingUtils.cpp [hunk 1]
```diff
@@ -312,6 +312,10 @@ LogicalResult linkExecutablesInto(
       }
 
       // Merge the existing module into the new linked module op.
+      if (!variantOp.getInnerModule() || !linkedTargetOp.getInnerModule()) {
+        continue;
+      }
+
```
Comment (benvanik) [inline compiler/src/iree/compiler/Codegen/Utils/LinkingUtils.cpp]: you want to do this earlier on - by here we've already modified some things
the variantOp check can go right at the top of the `for (auto variantOp : variantOps) {` loop
linkedTargetOp could go at the very top of the function

**Review by benvanik — CHANGES_REQUESTED** [review]

**Review by benvanik — APPROVED** [review]
