### PR TITLE
[CodeGen] Fix gather fusion on vector distribute path

### LINKED ISSUE #21107: Shared memory failure on softmax
When compiling the following IR:
https://gist.github.com/rsuderman/c2ff931ca5ddad20f061f31f7a8847a2

We see a shared memory failure:
https://gist.github.com/rsuderman/318fb1db5735d9d311060dfeebdf2cfd

### PR DESCRIPTION
**Pull request by pashu123**
Don't attach lowering config to the gather operation. Let it fuse with the consumer operation. This eliminates the creation of a temporary buffer.
The change restricts element-wise fusion in the case of softmax with a gather-like operation.
Fixes https://github.com/iree-org/iree/issues/21107

### CODE REVIEW

**Review by hanhanW — COMMENTED** [review]
Common is too vague because IREE does not only have codegen codes. Also, we need tests.

I'm also curious if the change in `DecomposeSoftmax` impacts other backends. It looks like a GPU specific, based on the PR title. Any comment about the change is valuable to reviewers and future contributors that don't have context.

File: compiler/src/iree/compiler/Codegen/Common/DecomposeSoftmax.cpp [hunk 1]
```diff
@@ -45,7 +45,10 @@ struct FuseElementWiseGenericOps : public OpRewritePattern<linalg::GenericOp> {
     for (OpOperand &opOperand : genericOp->getOpOperands()) {
       if (!linalg::areElementwiseOpsFusable(&opOperand))
         continue;
-
+      auto producer = opOperand.get().getDefiningOp<linalg::GenericOp>();
+      if (producer && hasExternalCapture(producer)) {
+        continue;
+      }
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/DecomposeSoftmax.cpp:54]: nit: I think it's worth to add a comment for it.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 2]
```diff
@@ -544,6 +544,11 @@ populateConfigInfo(const llvm::SetVector<linalg::LinalgOp> &computeOps,
   // LinalgOp with only parallel dims. This is needed if the op cannot be fused
   // with a reduction or introduces new loop dimensions.
   auto shouldAttachLoweringConfig = [&](linalg::LinalgOp linalgOp) -> bool {
+    // If the operation has a gather, we want to fuse it with the
+    // reduction.
+    if (hasExternalCapture(cast<linalg::GenericOp>(linalgOp))) {
+      return false;
+    }
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:551]: Should we add a lit test to reflect the lowering config change on GPU side?

**Comment by hanhanW** [comment]
@pashu123 if this PR fixes the issue, you can add `Fixes https://github.com/iree-org/iree/issues/21107` in the PR description. The issue will be closed when you land the PR.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp (hunk 2 above)
Comment (pashu123) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:551]: Added.

File: compiler/src/iree/compiler/Codegen/Common/DecomposeSoftmax.cpp (hunk 1 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/DecomposeSoftmax.cpp:54]: Sorry, not being clear in the first place. I'm not looking for code explanation, i.e., repeat the code logic when it is self documented. What I'm looking for is why we make the decision. (And it is better to use gather-like in the comment, because you explicitly mentioned it in the PR description.)

**Review by MaheshRavishankar — APPROVED** [review]

File: compiler/src/iree/compiler/Codegen/Common/DecomposeSoftmax.cpp (hunk 1 above)
Comment (pashu123) [reply compiler/src/iree/compiler/Codegen/Common/DecomposeSoftmax.cpp:54]: PTAL.

**Comment by MaheshRavishankar** [comment]
@Groverkss  can you review this please.

File: compiler/src/iree/compiler/Codegen/Common/DecomposeSoftmax.cpp [hunk 3]
```diff
@@ -45,7 +45,13 @@ struct FuseElementWiseGenericOps : public OpRewritePattern<linalg::GenericOp> {
     for (OpOperand &opOperand : genericOp->getOpOperands()) {
       if (!linalg::areElementwiseOpsFusable(&opOperand))
         continue;
-
+      // Don't fuse if it has external capture. For e.g., the gather like
```
Comment (Groverkss) [inline compiler/src/iree/compiler/Codegen/Common/DecomposeSoftmax.cpp:48]: I'm a bit confused why we don't want this, do you have an example of what gets messed up?

Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/Common/DecomposeSoftmax.cpp:48]: ok there is an issue linked, let me ahve a look

**Review by Groverkss — APPROVED** [review]

File: compiler/src/iree/compiler/Codegen/Common/DecomposeSoftmax.cpp (hunk 3 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/Common/DecomposeSoftmax.cpp:48]: makes sense
