### PR TITLE
[LinalgExt] Fix reshape fusion crash

### LINKED ISSUE #21439: Non-shaped type with >0 results in attn operand
### What happened?

I'm hitting this [assert](https://github.com/iree-org/iree/blob/f87452f3fc7481d820b5c38f6cadbbb6c7f17beb/compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp#L291)

Adding some debug prints left me even more confused:
```
operandType: tensor<1x32x1x256xf16>
num_results: 4
! operandType: 0

operandType: tensor<?x256xf16>
num_results: 2
! operandType: 0

operandType: tensor<?x256xf16>
num_results: 2
! operandType: 0

operandType: f32
num_results: 0
! operandType: 1

operandType: tensor<?x?xf16>
num_results: 2
! operandType: 0

operandType: tensor<1x32x1x256xf32>
num_results: 4
! operandType: 0
```
It seems like I shouldn't be hitting the assert as the only `!operandType` from the prints does have 0 results. What am I missing?

[input ir](https://gist.github.com/dan-garvey/3271194824b4a9b84fb8f4c6b66e0849)

compile command
`iree-compile input.mlir  --iree-hal-target-device=hip  --iree-hip-target=gfx942  -o output.vmfb   --iree-opt-level=O3   --iree-hal-indirect-command-buffers=true   --iree-stream-resource-memory-model=discrete  --iree-hal-memoization=true`

### PR DESCRIPTION
**Pull request by IanWood1**
The upstream reshape builder requires that no change in static/dynamic dims. This causes `getOrCreateExpanded` to fail but at that point the pattern has already modified the IR so it's too late for the pattern to return `failure()` (will cause infinite looping). Instead, exit early when computing expansion info for ops with mixed static & dynamic dims.

Related issue for propagating static shape info https://github.com/iree-org/iree/issues/21471
Closes https://github.com/iree-org/iree/issues/21439

### CODE REVIEW

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp [hunk 1]
```diff
@@ -413,8 +425,10 @@ fuseWithReshapeByExpansion(OpTy op, Operation *reshapeOp,
 
   IRMapping mapping;
   for (OpOperand &operand : op->getOpOperands()) {
-    mapping.map(operand.get(),
-                info.getOrCreateExpanded(loc, &operand, rewriter).value());
+    std::optional<Value> maybeNewOperand =
+        info.getOrCreateExpanded(loc, &operand, rewriter);
+    assert(maybeNewOperand.has_value());
+    mapping.map(operand.get(), maybeNewOperand.value());
```
Comment (dan-garvey) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp:431]: Is this just because you want to force a failure in the case that `getOrCreateExpanded` has no value? Is that not what was already happening?

Comment (IanWood1) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp:431]: Mostly it is so that any future errors here are easier to diagnose by hitting an explicit assert instead of just aborting. Also, I could be wrong but I think it might be undefined behavior to call `.value()` because exceptions are disabled. But I can undo this change if it's unnecessary.

Comment (dan-garvey) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp:431]: Easier to diagnose = yes please

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp [hunk 2]
```diff
@@ -200,6 +200,18 @@ LogicalResult ExpansionInfo::compute(
   if (operandReassoc.empty())
     return failure();
 
+  // Check that the operand dim size matches the iteration space dim size. This
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp:203]: I think this is an indication of a missing canonicalization/static dim propagation before this pass is called.

**Review by MaheshRavishankar — APPROVED** [review]
This change itself is fine, but we probably nede some "static dim propagation" for attention ops (something similar to https://github.com/llvm/llvm-project/blob/3d5b18af1752ad4b859de6bdba4b25ef040a3dce/mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp#L2667)

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp (hunk 2 above)
Comment (IanWood1) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp:203]: Yep, I created an issue https://github.com/iree-org/iree/issues/21471. It should be fairly easy to implement.
