### PR TITLE
[DispatchCreation] Add unset encoding through generic propagation

### LINKED ISSUE #21253: [GPU][DT] Propagate unset_encoding through elementwise generic
I am seeing the following dispatch before materialization in Llama3 with data-tiling enabled:
```
// -----// IR Dump Before MaterializeDeviceEncodingPass (iree-codegen-materialize-device-encoding) //----- //
func.func @prefill_bs4$async_dispatch_2_matmul_like_Dx4096x4096_f8E4M3FNUZxf8E4M3FNUZxf32() {
  %c32_i64 = arith.constant 32 : i64
  %cst = arith.constant 0.000000e+00 : f32
  %cst_0 = arith.constant -2.400000e+02 : f32
  %cst_1 = arith.constant 2.400000e+02 : f32
  %0 = hal.interface.constant.load layout(<constants = 9, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) ordinal(0) : i32
  %1 = hal.interface.constant.load layout(<constants = 9, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) ordinal(1) : i32
  %2 = hal.interface.constant.load layout(<constants = 9, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) ordinal(2) : i32
  %3 = hal.interface.constant.load layout(<constants = 9, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) ordinal(3) : i32
  %4 = hal.interface.constant.load layout(<constants = 9, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) ordinal(4) : i32
  %5 = hal.interface.constant.load layout(<constants = 9, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) ordinal(5) : i32
  %6 = hal.interface.constant.load layout(<constants = 9, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) ordinal(6) : i32
  %7 = hal.interface.constant.load layout(<constants = 9, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) ordinal(7) : i32
  %8 = hal.interface.constant.load layout(<constants = 9, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) ordinal(8) : i32
  %9 = arith.extui %1 : i32 to i64
  %10 = arith.shli %9, %c32_i64 : i64
  %11 = arith.extui %0 : i32 to i64
  %12 = arith.ori %11, %10 : i64
  %13 = arith.index_castui %12 : i64 to index
  %14 = arith.extui %3 : i32 to i64
  %15 = arith.shli %14, %c32_i64 : i64
  %16 = arith.extui %2 : i32 to i64
  %17 = arith.ori %16, %15 : i64
  %18 = arith.index_castui %17 {stream.alignment = 8192 : index, stream.values = [532480 : index, 218636288 : index, 436740096 : index, 654843904 : index, 872947712 : index, 1091051520 : index, 1309155328 : index, 1527259136 : index, 1745362944 : index, 1963466752 : index, 2181570560 : index, 2399674368 : index, 2617778176 : index, 2835881984 : index, 3053985792 : index, 3272089600 : index, 3490193408 : index, 3708297216 : index, 3926401024 : index, 4144504832 : index, 4362608640 : index, 4580712448 : index, 4798816256 : index, 5016920064 : index, 5235023872 : index, 5453127680 : index, 5671231488 : index, 5889335296 : index, 6107439104 : index, 6325542912 : index, 6543646720 : index, 6761750528 : index]} : i64 to index
  %19 = arith.extui %5 : i32 to i64
  %20 = arith.shli %19, %c32_i64 : i64
  %21 = arith.extui %4 : i32 to i64
  %22 = arith.ori %21, %20 : i64
  %23 = arith.index_castui %22 {stream.alignment = 64 : index, stream.values = [1067458624 : index, 1285579712 : index, 1503700800 : index, 1721821888 : index, 1939942976 : index, 2158064064 : index, 2376185152 : index, 2594306240 : index, 2812427328 : index, 3030548416 : index, 3248669504 : index, 3466790592 : index, 3684911680 : index, 3903032768 : index, 4121153856 : index, 4339274944 : index, 4557396032 : index, 4775517120 : index, 4993638208 : index, 5211759296 : index, 5429880384 : index, 5648001472 : index, 5866122560 : index, 6084243648 : index, 6302364736 : index, 6520485824 : index, 6738606912 : index, 6956728000 : index, 7174849088 : index, 7392970176 : index, 7611091264 : index, 7829212352 : index]} : i64 to index
  %24 = arith.extui %7 : i32 to i64
  %25 = arith.shli %24, %c32_i64 : i64
  %26 = arith.extui %6 : i32 to i64
  %27 = arith.ori %26, %25 : i64
  %28 = arith.index_castui %27 : i64 to index
  %29 = arith.index_castui %8 : i32 to index
  %30:5 = util.assume.int 
      %13<umin = 70254592, umax = 12948865024>, 
      %18[<umin = 532480, umax = 532480, udiv = 532480>, <umin = 218636288, umax = 218636288, udiv = 218636288>, <umin = 436740096, umax = 436740096, udiv = 436740096>, <umin = 654843904, umax = 654843904, udiv = 654843904>, <umin = 872947712, umax = 872947712, udiv = 872947712>, <umin = 1091051520, umax = 1091051520, udiv = 1091051520>, <umin = 1309155328, umax = 1309155328, udiv = 1309155328>, <umin = 1527259136, umax = 1527259136, udiv = 1527259136>, <umin = 1745362944, umax = 1745362944, udiv = 1745362944>, <umin = 1963466752, umax = 1963466752, udiv = 1963466752>, <umin = 2181570560, umax = 2181570560, udiv = 2181570560>, <umin = 2399674368, umax = 2399674368, udiv = 2399674368>, <umin = 2617778176, umax = 2617778176, udiv = 2617778176>, <umin = 2835881984, umax = 2835881984, udiv = 2835881984>, <umin = 3053985792, umax = 3053985792, udiv = 3053985792>, <umin = 3272089600, umax = 3272089600, udiv = 3272089600>, <umin = 3490193408, umax = 3490193408, udiv = 3490193408>, <umin = 3708297216, umax = 3708297216, udiv = 3708297216>, <umin = 3926401024, umax = 3926401024, udiv = 3926401024>, <umin = 4144504832, umax = 4144504832, udiv = 4144504832>, <umin = 4362608640, umax = 4362608640, udiv = 4362608640>, <umin = 4580712448, umax = 4580712448, udiv = 4580712448>, <umin = 4798816256, umax = 4798816256, udiv = 4798816256>, <umin = 5016920064, umax = 5016920064, udiv = 5016920064>, <umin = 5235023872, umax = 5235023872, udiv = 5235023872>, <umin = 5453127680, umax = 5453127680, udiv = 5453127680>, <umin = 5671231488, umax = 5671231488, udiv = 5671231488>, <umin = 5889335296, umax = 5889335296, udiv = 5889335296>, <umin = 6107439104, umax = 6107439104, udiv = 6107439104>, <umin = 6325542912, umax = 6325542912, udiv = 6325542912>, <umin = 6543646720, umax = 6543646720, udiv = 6543646720>, <umin = 6761750528, umax = 6761750528, udiv = 6761750528>], 
      %23[<umin = 1067458624, umax = 1067458624, udiv = 1067458624>, <umin = 1285579712, umax = 1285579712, udiv = 1285579712>, <umin = 1503700800, umax = 1503700800, udiv = 1503700800>, <umin = 1721821888, umax = 1721821888, udiv = 1721821888>, <umin = 1939942976, umax = 1939942976, udiv = 1939942976>, <umin = 2158064064, umax = 2158064064, udiv = 2158064064>, <umin = 2376185152, umax = 2376185152, udiv = 2376185152>, <umin = 2594306240, umax = 2594306240, udiv = 2594306240>, <umin = 2812427328, umax = 2812427328, udiv = 2812427328>, <umin = 3030548416, umax = 3030548416, udiv = 3030548416>, <umin = 3248669504, umax = 3248669504, udiv = 3248669504>, <umin = 3466790592, umax = 3466790592, udiv = 3466790592>, <umin = 3684911680, umax = 3684911680, udiv = 3684911680>, <umin = 3903032768, umax = 3903032768, udiv = 3903032768>, <umin = 4121153856, umax = 4121153856, udiv = 4121153856>, <umin = 4339274944, umax = 4339274944, udiv = 4339274944>, <umin = 4557396032, umax = 4557396032, udiv = 4557396032>, <umin = 4775517120, umax = 4775517120, udiv = 4775517120>, <umin = 4993638208, umax = 4993638208, udiv = 4993638208>, <umin = 5211759296, umax = 5211759296, udiv = 5211759296>, <umin = 5429880384, umax = 5429880384, udiv = 5429880384>, <umin = 5648001472, umax = 5648001472, udiv = 5648001472>, <umin = 5866122560, umax = 5866122560, udiv = 5866122560>, <umin = 6084243648, umax = 6084243648, udiv = 6084243648>, <umin = 6302364736, umax = 6302364736, udiv = 6302364736>, <umin = 6520485824, umax = 6520485824, udiv = 6520485824>, <umin = 6738606912, umax = 6738606912, udiv = 6738606912>, <umin = 6956728000, umax = 6956728000, udiv = 6956728000>, <umin = 7174849088, umax = 7174849088, udiv = 7174849088>, <umin = 7392970176, umax = 7392970176, udiv = 7392970176>, <umin = 7611091264, umax = 7611091264, udiv = 7611091264>, <umin = 7829212352, umax = 7829212352, udiv = 7829212352>], 
      %28<umin = 69206016, umax = 8654946304>, 
      %29<umin = 128, umax = 524160, udiv = 128>
    : index, index, index, index, index
  %31 = hal.interface.binding.subspan layout(<constants = 9, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(1) alignment(64) offset(%30#1) flags(ReadOnly) : !iree_tensor_ext.dispatch.tensor<readonly:tensor<4096x4096xf8E4M3FNUZ, #iree_encoding.layout<[#iree_gpu.gpu_encoding_resolver<configuration = {encoding_info = {innerDimsPos = [0, 1], innerTileSizes = [128, 64], outerDimsPerm = [0, 1], swizzle = {expandShape = [[["CrossThread", 4 : i16], ["CrossThread", 16 : i16], ["CrossIntrinsic", 2 : i16]], [["CrossIntrinsic", 2 : i16], ["CrossThread", 4 : i16], ["Internal", 8 : i16]]], permutation = [0, 2, 4, 1, 3, 5]}}}>]>>>
  %32 = hal.interface.binding.subspan layout(<constants = 9, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(2) alignment(64) offset(%30#2) flags(ReadOnly) : !iree_tensor_ext.dispatch.tensor<readonly:tensor<f32>>
  %33 = iree_tensor_ext.dispatch.workload.ordinal %30#4, 0 : index
  %34 = hal.interface.binding.subspan layout(<constants = 9, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%30#0) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<?x4096xf8E4M3FNUZ, #iree_encoding.layout<[#iree_gpu.gpu_encoding_resolver<configuration = {encoding_info = {innerDimsPos = [0, 1], innerTileSizes = [128, 64], outerDimsPerm = [0, 1], swizzle = {expandShape = [[["CrossThread", 4 : i16], ["CrossIntrinsic", 8 : i16], ["CrossThread", 4 : i16]], [["CrossIntrinsic", 2 : i16], ["CrossThread", 4 : i16], ["Internal", 8 : i16]]], permutation = [1, 4, 0, 2, 3, 5]}}}>]>>>{%33}
  %35 = hal.interface.binding.subspan layout(<constants = 9, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(3) alignment(64) offset(%30#3) flags(Indirect) : !iree_tensor_ext.dispatch.tensor<writeonly:tensor<?x4096xf8E4M3FNUZ>>{%33}
  %36 = iree_tensor_ext.dispatch.tensor.load %34, offsets = [0, 0], sizes = [%33, 4096], strides = [1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<?x4096xf8E4M3FNUZ, #iree_encoding.layout<[#iree_gpu.gpu_encoding_resolver<configuration = {encoding_info = {innerDimsPos = [0, 1], innerTileSizes = [128, 64], outerDimsPerm = [0, 1], swizzle = {expandShape = [[["CrossThread", 4 : i16], ["CrossIntrinsic", 8 : i16], ["CrossThread", 4 : i16]], [["CrossIntrinsic", 2 : i16], ["CrossThread", 4 : i16], ["Internal", 8 : i16]]], permutation = [1, 4, 0, 2, 3, 5]}}}>]>>>{%33} -> tensor<?x4096xf8E4M3FNUZ, #iree_encoding.encoding<operand_index = 0 : index, op_type =  matmul, element_types = [f8E4M3FNUZ, f8E4M3FNUZ, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>]>>
  %37 = iree_tensor_ext.dispatch.tensor.load %31, offsets = [0, 0], sizes = [4096, 4096], strides = [1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<4096x4096xf8E4M3FNUZ, #iree_encoding.layout<[#iree_gpu.gpu_encoding_resolver<configuration = {encoding_info = {innerDimsPos = [0, 1], innerTileSizes = [128, 64], outerDimsPerm = [0, 1], swizzle = {expandShape = [[["CrossThread", 4 : i16], ["CrossThread", 16 : i16], ["CrossIntrinsic", 2 : i16]], [["CrossIntrinsic", 2 : i16], ["CrossThread", 4 : i16], ["Internal", 8 : i16]]], permutation = [0, 2, 4, 1, 3, 5]}}}>]>>> -> tensor<4096x4096xf8E4M3FNUZ, #iree_encoding.encoding<operand_index = 1 : index, op_type =  matmul, element_types = [f8E4M3FNUZ, f8E4M3FNUZ, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>]>>
  %38 = iree_tensor_ext.dispatch.tensor.load %32, offsets = [], sizes = [], strides = [] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<f32>> -> tensor<f32>
  %39 = tensor.empty(%33) : tensor<?x4096xf32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [f8E4M3FNUZ, f8E4M3FNUZ, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>]>>
  %40 = linalg.fill ins(%cst : f32) outs(%39 : tensor<?x4096xf32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [f8E4M3FNUZ, f8E4M3FNUZ, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>]>>) -> tensor<?x4096xf32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [f8E4M3FNUZ, f8E4M3FNUZ, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>]>>
  %41 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>], iterator_types = ["parallel", "parallel", "reduction"]} ins(%36, %37 : tensor<?x4096xf8E4M3FNUZ, #iree_encoding.encoding<operand_index = 0 : index, op_type =  matmul, element_types = [f8E4M3FNUZ, f8E4M3FNUZ, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>]>>, tensor<4096x4096xf8E4M3FNUZ, #iree_encoding.encoding<operand_index = 1 : index, op_type =  matmul, element_types = [f8E4M3FNUZ, f8E4M3FNUZ, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>]>>) outs(%40 : tensor<?x4096xf32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [f8E4M3FNUZ, f8E4M3FNUZ, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>]>>) {
  ^bb0(%in: f8E4M3FNUZ, %in_2: f8E4M3FNUZ, %out: f32):
    %45 = arith.extf %in : f8E4M3FNUZ to f32
    %46 = arith.extf %in_2 : f8E4M3FNUZ to f32
    %47 = arith.mulf %45, %46 : f32
    %48 = arith.addf %out, %47 : f32
    linalg.yield %48 : f32
  } -> tensor<?x4096xf32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [f8E4M3FNUZ, f8E4M3FNUZ, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>]>>
  %42 = iree_encoding.unset_encoding %41 : tensor<?x4096xf32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [f8E4M3FNUZ, f8E4M3FNUZ, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>]>> -> tensor<?x4096xf32>{%33}
  %43 = tensor.empty(%33) : tensor<?x4096xf8E4M3FNUZ>
  %44 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> ()>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%42, %38 : tensor<?x4096xf32>, tensor<f32>) outs(%43 : tensor<?x4096xf8E4M3FNUZ>) {
  ^bb0(%in: f32, %in_2: f32, %out: f8E4M3FNUZ):
    %45 = arith.divf %in, %in_2 : f32
    %46 = arith.cmpf ult, %45, %cst_0 : f32
    %47 = arith.select %46, %cst_0, %45 : f32
    %48 = arith.cmpf ugt, %47, %cst_1 : f32
    %49 = arith.select %48, %cst_1, %47 : f32
    %50 = arith.truncf %49 : f32 to f8E4M3FNUZ
    linalg.yield %50 : f8E4M3FNUZ
  } -> tensor<?x4096xf8E4M3FNUZ>
  iree_tensor_ext.dispatch.tensor.store %44, %35, offsets = [0, 0], sizes = [%33, 4096], strides = [1, 1] : tensor<?x4096xf8E4M3FNUZ> -> !iree_tensor_ext.dispatch.tensor<writeonly:tensor<?x4096xf8E4M3FNUZ>>{%33}
  return
}
```
This leads to the following error in codegen:
```
error: 'vector.transfer_write' op write affecting operations on global resources are restricted to workgroup distributed contexts.
```
My first observation here is that the unset_encoding is squashed in between the matmul and elementwise operation and I think the first thing to do here is propagating the unset_encoding through the elementwise generic operation.

### PR DESCRIPTION
**Pull request by jtuyls**
Resolves: https://github.com/iree-org/iree/issues/21253

This implements the propagation of unset encoding ops through generic operations in case the unset encoding has a single use and the generic is fully parallel and has a single result. This avoids unset encoding ops in the middle of a dispatch seen in data-tiled Llama3 (see issue above).

### CODE REVIEW

File: compiler/src/iree/compiler/DispatchCreation/PropagateEncodings.cpp [hunk 1]
```diff
@@ -95,11 +103,66 @@ LogicalResult SwapEncodingOpWithTensorCollapseShapeOp::matchAndRewrite(
   return success();
 }
 
+template <typename Op>
+LogicalResult BubbleDown<Op>::matchAndRewrite(Op op,
```
Comment (Max191) [inline compiler/src/iree/compiler/DispatchCreation/PropagateEncodings.cpp]: nit: I think the templating here isn't necessary. The implementation only bubbles down UnsetEncoding ops, and we probably won't be propagating any other encoding ops down.

File: compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp [hunk 2]
```diff
@@ -106,19 +109,157 @@ struct ContractionOpPropagationInterface
...
+                      FailureOr<IREE::Encoding::PropagationEncoding>>(
+               target->getOwner())
+        .Case<linalg::GenericOp>([&](auto genericOp) {
+          // The operand and result encoding will be the same as the encoding
+          // present in the unset encoding operation.
+          IREE::Encoding::PropagationEncoding propEncoding;
+          propEncoding.operandEncodings.insert(
+              propEncoding.operandEncodings.end(),
+              genericOp.getDpsInputOperands().size(), encoding);
+          propEncoding.resultEncodings.push_back(encoding);
```
Comment (Max191) [inline compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp]: This is not true if there are transpositions or broadcasts. Each operand needs to add its matching indexing map to the corresponding user_indexing_maps list to create the propagated encoding. Results also need to add the corresponding map of the DPS init operand. If there is a non-identity map on the target operand, then I think the inverse indexing map also needs to be added to each new encoding first.

This must happen in the `generateSinkingEncodings` function, because it is the function in which we know the direction of propagation, and the operand that is being propagated from, so we need to generate the correct final encodings in this function, and then simply apply them in the `propagateEncoding` implementation.

File: compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp [hunk 3]
```diff
@@ -106,19 +109,157 @@ struct ContractionOpPropagationInterface
...
+                // If the source op is the encoding op, we can just add the
+                // source to new operands vector and continue.
+                Operation *sourceOp = operand->get().getDefiningOp();
+                if (sourceOp && sourceOp == encodingOp) {
+                  encodedOperands.push_back(encodingOp.getSource());
+                  continue;
+                }
+
+                // Append the operand's indexing map to the encoding's user
+                // indexing maps.
```
Comment (Max191) [inline compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp]: This should happen in the `generateSinkingEncodings` function, and then the encodings can be used as-is here. We don't know the direction or source of propagation in the `propagateEncoding` function, so we shouldn't modify the encodings here.

**Review by Max191 — CHANGES_REQUESTED** [review]
Higher level comment: We probably want to add the pattern to `HoistEncodingOpsPass`, since the scope of the propagation is within dispatch regions, and it can open up new hoisting opportunities. We can run the pattern in that pass before we do hoisting.

File: compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp [hunk 4]
```diff
@@ -106,19 +109,163 @@ struct ContractionOpPropagationInterface
...
+            AffineMap operandMap = genericOp.getMatchingIndexingMap(operand);
+            IREE::Encoding::EncodingAttr newEncoding =
+                encoding.cloneWithNewOperandIndexingMap(operandMap);
+            propEncoding.operandEncodings.push_back(newEncoding);
+          }
+          for (OpOperand &operand : genericOp.getDpsInitsMutable()) {
+            AffineMap operandMap = genericOp.getMatchingIndexingMap(&operand);
+            IREE::Encoding::EncodingAttr newEncoding =
+                encoding.cloneWithNewOperandIndexingMap(operandMap);
+            propEncoding.resultEncodings.push_back(newEncoding);
```
Comment (Max191) [inline compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp:180]: propEncoding.operandEncodings should have the encodings for the DPS inits too.

File: compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp [hunk 5]
```diff
@@ -106,19 +109,163 @@ struct ContractionOpPropagationInterface
...
+          // The operand and result encoding will be the same as the encoding
+          // present in the unset encoding operation.
+          IREE::Encoding::PropagationEncoding propEncoding;
+          propEncoding.operandEncodings.reserve(genericOp->getNumOperands());
+          for (OpOperand *operand : genericOp.getDpsInputOperands()) {
+            // Append the operand's indexing map to the encoding's indexing
+            // maps.
+            AffineMap operandMap = genericOp.getMatchingIndexingMap(operand);
+            IREE::Encoding::EncodingAttr newEncoding =
+                encoding.cloneWithNewOperandIndexingMap(operandMap);
```
Comment (Max191) [inline compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp]: The new encodings should also have the inverse of the `target`s indexing map. As an example:
```
%generic = linalg.generic {
    indexing_maps = [affine_map<(d0, d1, d2) -> (d1, d2, d0)>,
                     affine_map<(d0, d1, d2) -> (d0, d1, d2)>] ...
    ins(%target : tensor<2x4x8xf32>) outs(%out : tensor<8x2x4xf32>)
```
If only the output map is added for the new `%out` encoding, then the resulting encoding will have the incorrect mapping of operand dimensions to contraction dimensions. To produce the correct mapping, the dims of each operand need to first be mapped to the domain of the op (inverse of `target` map), and then mapped from the domain of the op to the operand's range (operand's map). The `target` operand can just stay the same, of course, and if the `target` operand's map is identity, then there is no need to add the additional inverse target map (actually, any identity map does not need to be added, even the operand maps).

File: compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp [hunk 6]
```diff
@@ -199,6 +199,64 @@ struct BubbleUpSetEncodingOp
   }
 };
 
+/// Pattern to bubble UnsetEncoding ops down through consumers.
+struct BubbleDownUnsetEncodingOp
```
Comment (Max191) [inline compiler/src/iree/compiler/DispatchCreation/HoistEncodingOps.cpp]: optional nit: Rename to `SinkUnsetEncodingOp` to match the naming of the interface method (i.e., `generateSinkingEncodings`)?

File: compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp (hunk 5 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp]: Thanks for the pointer! I saw your comment above on this and was looking at that but wasn't sure what you meant exactly. I think this is correct now, however I might run an e2e test tomorrow to ensure (for myself) that that's indeed the case and that I am not missing anything else. But if you could already have another look that would be helpful.

Comment (jtuyls) [reply compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp]: Yeah, so I tested this locally on an e2e example with permuted target indexing maps and got the same results :)

File: compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp [hunk 7]
```diff
@@ -106,19 +109,185 @@ struct ContractionOpPropagationInterface
   }
 };
 
+struct EncodingAttrPropagationInterface
+    : public IREE::Encoding::EncodingPropagationAttrInterface::ExternalModel<
+          EncodingAttrPropagationInterface, IREE::Encoding::EncodingAttr> {
+  bool isPropagableDown(Attribute attr, OpOperand *target) const {
```
Comment (Max191) [inline compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp:115]: It just occurred to me, we probably want to check that all indexing maps are projected permutations (i.e., `map.isProjectedPermutation()`). Otherwise, I think it's unlikely we will be able to lower the encoding.

File: compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp [hunk 8]
```diff
@@ -106,19 +109,185 @@ struct ContractionOpPropagationInterface
...
+        .Case<IREE::Encoding::UnsetEncodingOp>(
+            [&](auto encodingOp)
+                -> FailureOr<IREE::Encoding::PropagationResult> {
+              IREE::Encoding::PropagationResult result;
+              // Set encodings on each input.
+              SmallVector<Value> encodedOperands;
+              encodedOperands.reserve(operandEncodings.size() +
+                                      resultEncodings.size());
+              for (auto &&[operand, encoding] : llvm::zip(
+                       genericOp.getDpsInputOperands(), operandEncodings)) {
```
Comment (Max191) [inline compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp:212]: nit: Since the init operand encodings are part of the operandEncodings now, all the operand encodings could be combined into one loop over `genericOp->getOpOperands()`. The special case for empty ops can also happen in the same loop, since the special case is valid for input and init operands.

File: compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp [hunk 9]
```diff
@@ -106,19 +109,185 @@ struct ContractionOpPropagationInterface
...
+              for (unsigned i = 0; i < genericOp->getNumResults(); i++) {
+                auto resultType = cast<RankedTensorType>(
+                                      encodedGenericOp.getResult(i).getType())
+                                      .dropEncoding();
+                auto newUnsetEncoding =
+                    rewriter.create<IREE::Encoding::UnsetEncodingOp>(
+                        encodingOp.getLoc(), resultType,
+                        encodedGenericOp.getResult(i),
+                        encodingOp.getResultDims());
+                result.replacements = {newUnsetEncoding.getResult()};
```
Comment (Max191) [inline compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp]: Should this just do `result.replacements.push_back(newUnsetEncoding.getResult())`?

File: compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp [hunk 10]
```diff
@@ -106,19 +109,185 @@ struct ContractionOpPropagationInterface
...
+              // Create the replacement unset encoding ops.
+              for (unsigned i = 0; i < genericOp->getNumResults(); i++) {
+                auto resultType = cast<RankedTensorType>(
+                                      encodedGenericOp.getResult(i).getType())
+                                      .dropEncoding();
+                auto newUnsetEncoding =
+                    rewriter.create<IREE::Encoding::UnsetEncodingOp>(
+                        encodingOp.getLoc(), resultType,
+                        encodedGenericOp.getResult(i),
+                        encodingOp.getResultDims());
```
Comment (Max191) [inline compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp]: nit: Iterate over the results directly?
```suggestion
              for (OpResult genericResult : encodedGenericOp->getOpResults()) {
                auto resultType = cast<RankedTensorType>(genericResult.getType())
                                      .dropEncoding();
                auto newUnsetEncoding =
                    rewriter.create<IREE::Encoding::UnsetEncodingOp>(
                        encodingOp.getLoc(), resultType, genericResult,
                        encodingOp.getResultDims());
```

**Comment by jtuyls** [comment]
@Max191 Could you have another look?

**Review by Max191 — COMMENTED** [review]
Nice, overall LGTM now, mostly just a few nits!

File: compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp (hunk 8 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp:212]: I think I prefer it in two separate loops. There's not that much in common, just the type and push into the encodedOperands. The empty related logic and push into resultEncodingTypes is all different.

Comment (Max191) [reply compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp:204]: Sounds good, I don't have a strong opinion here, so it is just a nit.

Comment (Max191) [reply compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp:212]: Sounds good, I don't have a strong opinion here, so it is just a nit.

File: compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp (hunk 7 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp:115]: Done and added a test case

File: compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp (hunk 9 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp]: Yeah, that's what it should be. Thanks for catching!

File: compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp [hunk 11]
```diff
@@ -106,19 +109,190 @@ struct ContractionOpPropagationInterface
...
+          if (genericOp.getNumReductionLoops() != 0) {
+            return false;
+          }
+          // The unset encoding should not be on one of the inits.
+          if (genericOp.isDpsInit(target)) {
+            return false;
+          }
+          // Non-projected permutation indexing maps will unlikely get lowered
+          // correctly with the encoding.
+          AffineMap map = genericOp.getMatchingIndexingMap(target);
```
Comment (Max191) [inline compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp]: I think we want to check all the permutation maps of the generic, since they will all get new encodings, and we don't want any to have non projected permutation maps.

**Review by Max191 — APPROVED** [review]
LGTM, just one minor comment!

File: compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp (hunk 11 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/ExternalInterfaces/EncodingExternalModels.cpp]: Done
