### PR TITLE
[Codegen] Allow pre-padding other dims of a conv except the input channel

### LINKED ISSUE #22277: Error for split reduction on some weight backward convolutions
Most weight backward convolutions work without problem when applying split reduction along input channel dimension. However, some configurations, e.g.,

```
convbfp16 -n 16 -c 13 -H 225 -W 225 -k 64 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 4 -t 1 --in_layout NHWC --out_layout NHWC --fil_layout NHWC --iter 100
convbfp16 -n 16 -c 5 -H 225 -W 225 -k 64 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 4 -t 1 --in_layout NHWC --out_layout NHWC --fil_layout NHWC --iter 100
convbfp16 -n 16 -c 9 -H 100 -W 1 -k 192 -y 4 -x 1 -p 0 -q 0 -u 4 -v 1 -l 1 -j 1 -m conv -g 1 -F 4 -t 1 --in_layout NHWC --out_layout NHWC --fil_layout NHWC --iter
```
failed with error:
```
error: LLVM Translation failed for operation: builtin.unrealized_conversion_cast
```

One common thing of these failed cases is that the batch dimension (as `-c` in above examples) are all odd numbers and unaligned shape, which means padding maybe a cause for the issue. For comparison, the below settings are working:

- The above configurations without split reduction.
- convbfp16 -n 16 **-c 16** -H 225 -W 225 -k 64 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 4 -t 1 --in_layout NHWC --out_layout NHWC --fil_layout NHWC --iter 100

To reproduce with https://github.com/iree-org/iree/pull/22275, and run command
```
iree-compile --iree-hal-target-backends=rocm --iree-hip-target=mi300x --iree-opt-level=O3 --iree-dispatch-creation-enable-fuse-padding-into-linalg-consumer-ops --iree-dispatch-creation-enable-split-reduction weight_backward_conv.mlir --mlir-print-ir-after-all
```

### PR DESCRIPTION
**Pull request by yzhang93**
Previous PR disabled padding for all conv dimensions when input channel size is much smaller than the padding size. However, for backward conv CHWN layout, when batch and input channel dimensions are both unaligned, it is still useful to pad the batch dimension. 

This PR fixed https://github.com/iree-org/iree/issues/22277.

### CODE REVIEW

**Review by Max191 — APPROVED** [review]

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 1]
```diff
@@ -766,16 +767,15 @@ getMatmulOrIGEMMLoweringConfigAndWorkgroupSize(
       kPackFactor = std::get<2>(mmaKind.getMNKShape());
     }
     paddingTileSizes[innerKDim] *= kPackFactor;
+    attrs.emplace_back(StringAttr::get(context, "padding"),
+                       b.getI64ArrayAttr(paddingTileSizes));
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: FYI, you can pass the name as stringref, only the value needs to be an attribute
```suggestion
    attrs.emplace_back("padding", b.getI64ArrayAttr(paddingTileSizes));
```

Comment (kuhar) [reply compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: also a few lines below
