### PR TITLE
[Flow] Teach RaiseSpecialOps to raise tensor.extract and views

### LINKED ISSUE #14742: Compilation issue for Vulkan/Cuda backend - at WarpOpToScfIfPattern
### What happened?

While compiling second_vicuna model for Vulkan/Cuda backend I see the following crash :-
```
Please report issues to https://github.com/openxla/iree/issues and include the crash backtrace.                                                           
 #0 0x00007f81053b8aef llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/abhishek/SRT/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:6
02:22                                                                                                                                                     
 #1 0x00007f81053b6f84 llvm::sys::RunSignalHandlers() /home/abhishek/SRT/third_party/llvm-project/llvm/lib/Support/Signals.cpp:104:20      
 #2 0x00007f81053b7126 SignalHandler(int) /home/abhishek/SRT/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:413:1                      
 #3 0x00007f8101242520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)                                                                                          
 #4 0x00007f81074557a3 mlir::AbstractType::getTypeID() const /home/abhishek/SRT/third_party/llvm-project/mlir/include/mlir/IR/TypeSupport.h:101:37        
 #5 0x00007f81074557a3 mlir::Type::getTypeID() /home/abhishek/SRT/third_party/llvm-project/mlir/include/mlir/IR/Types.h:112:64                     
 #6 0x00007f81074557a3 bool mlir::detail::StorageUserBase<mlir::VectorType, mlir::Type, mlir::detail::VectorTypeStorage, mlir::detail::TypeUniquer, mlir::
ShapedType::Trait>::classof<mlir::Type>(mlir::Type) /home/abhishek/SRT/third_party/llvm-project/mlir/include/mlir/IR/StorageUniquerSupport.h:114:25       
 #7 0x00007f81074557a3 llvm::CastInfo<mlir::VectorType, mlir::Type const, void>::isPossible(mlir::Type) /home/abhishek/SRT/third_party/llvm-project/mlir/i
nclude/mlir/IR/Types.h:403:25                                                                                                                             
 #8 0x00007f81074557a3 llvm::DefaultDoCastIfPossible<mlir::VectorType, mlir::Type const, llvm::CastInfo<mlir::VectorType, mlir::Type const, void> >::doCas
tIfPossible(mlir::Type) /home/abhishek/SRT/third_party/llvm-project/llvm/include/llvm/Support/Casting.h:311:29                                            
 #9 0x00007f81074557a3 decltype(auto) llvm::dyn_cast<mlir::VectorType, mlir::Type>(mlir::Type const&) /home/abhishek/SRT/third_party/llvm-project/llvm/inc
lude/llvm/Support/Casting.h:651:52                                                                                                                        
#10 0x00007f81074557a3 DistributedLoadStoreHelper /home/abhishek/SRT/third_party/llvm-project/mlir/lib/Dialect/Vector/Transforms/VectorDistribute.cpp:65:4
9
#11 0x00007f81074557a3 (anonymous namespace)::WarpOpToScfIfPattern::matchAndRewrite(mlir::vector::WarpExecuteOnLane0Op, mlir::PatternRewriter&) const /hom
e/abhishek/SRT/third_party/llvm-project/mlir/lib/Dialect/Vector/Transforms/VectorDistribute.cpp:322:63
```

With the dispatch I've added, I tried debugging via code instrumentation [here](https://github.com/llvm/llvm-project/blob/f631a10ac364ba39a396cb823ca1ca5eff4ad8b3/mlir/lib/Dialect/Vector/Transforms/VectorDistribute.cpp#L354) and see that it fails to print the `distributedVal`.
Here's what it prints:
```
distributedVal = <block argument> of type 'vector<4xf32>' at index: 1                                                                                     
getType of distributedVal = vector<4xf32>                                                                                                                                             
<CRASHES FOR THE SECOND ITERATION ON WarpOp>
```
I even tried dumping the WarpOp in concern right before this LLVM Pattern Rewrite is invoked in IREE and it fails.

### Steps to reproduce your issue

1. Input dispatch can be found here : [Dispatch 4](https://gist.github.com/Abhishek-Varma/39c45e6dd21ddec3ce6f3e93d68524f7).
2. For CUDA - Command to run on the above dispatch:
```
time ./build/tools/iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=cuda --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=false --iree-util-zero-fill-elided-attrs --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false --iree-opt-const-expr-hoisting=false --iree-hal-dump-executable-sources-to=hal_sources --iree-consteval-jit-debug=true --iree-stream-resource-max-allocation-size=3221225472 module_forward_dispatch_4.mlir -o test.vmfb
```
3. For Vulkan - Command to run on the above dispatch:
```
time ./build/tools/iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-vulkan-target-triple=ampere-a100-linux --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=false --iree-util-zero-fill-elided-attrs --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false --iree-opt-const-expr-hoisting=false --iree-hal-dump-executable-sources-to=hal_sources --iree-consteval-jit-debug=true --iree-stream-resource-max-allocation-size=3221225472 module_forward_dispatch_4.mlir -o test.vmfb
```

### What component(s) does this issue relate to?

_No response_

### Version information

I'm using latest source build of IREE/SRT.

@powderluv @stellaraccident 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Groverkss**
This patch teaches RaiseSpecialOps pass to raise tensor.extract to an input arguement to a linalg.generic. It also teaches it to raise linalg.generic to tensor.expand_shape.

Fixes #14742

### CODE REVIEW

File: compiler/src/iree/compiler/Preprocessing/Common/Passes.h [hunk 1]
```diff
@@ -28,6 +28,9 @@ createMakeSingleDispatchForFunctionPass();
 /// A pass to pad linalg ops to the next integer multiple of `paddingSize`.
 std::unique_ptr<Pass> createPadLinalgOpsToIntegerMultiplePass();
 
+/// A pass to pad linalg ops to the next integer multiple of `paddingSize`.
```
Comment (benvanik) [inline compiler/src/iree/compiler/Preprocessing/Common/Passes.h]: new comment needed here and in the summary in passes.td

File: compiler/src/iree/compiler/Preprocessing/Common/RaiseSlicingLinalgOps.cpp [hunk 2]
```diff
@@ -0,0 +1,152 @@
+// Copyright 2021 The IREE Authors
```
Comment (benvanik) [inline compiler/src/iree/compiler/Preprocessing/Common/RaiseSlicingLinalgOps.cpp]: 2023

File: compiler/src/iree/compiler/Preprocessing/Common/RaiseSlicingLinalgOps.cpp [hunk 3]
```diff
@@ -0,0 +1,152 @@
...
+
+      // The value can one of the 4: constant, linalg.index,
+      // tensor<64> in inits, variable outside the linalg region.
+      if (auto constantOp = indexValue.getDefiningOp<arith::ConstantOp>()) {
+        offsets.push_back(constantOp.getValueAttr());
+        size.push_back(one);
+        continue;
+      }
+
+      // // We assume that the indexing map is an identity.
```
Comment (benvanik) [inline compiler/src/iree/compiler/Preprocessing/Common/RaiseSlicingLinalgOps.cpp]:
```suggestion
      // We assume that the indexing map is an identity.
```

File: compiler/src/iree/compiler/Preprocessing/Common/RaiseSlicingLinalgOps.cpp [hunk 4]
```diff
@@ -0,0 +1,152 @@
...
+    SmallVector<OpFoldResult> offsets;
+    SmallVector<OpFoldResult> size;
+    SmallVector<OpFoldResult> strides(rank, one);
+
+    auto outShape = initTensor.getShape();
+    for (auto it : llvm::enumerate(extractOp.getIndices())) {
+      Value indexValue = it.value();
+
+      // The value can one of the 4: constant, linalg.index,
+      // tensor<64> in inits, variable outside the linalg region.
```
Comment (benvanik) [inline compiler/src/iree/compiler/Preprocessing/Common/RaiseSlicingLinalgOps.cpp]:
```suggestion
      // tensor<i64> in inits, variable outside the linalg region.
```

**Review by benvanik — COMMENTED** [review]
@MaheshRavishankar / @hanhanW should probably review as I don't know what's correct :)

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Could we move this into `RaiseSpecialOps`?

File: compiler/src/iree/compiler/Preprocessing/Common/RaiseSlicingLinalgOps.cpp [hunk 5]
```diff
@@ -0,0 +1,152 @@
...
+
+namespace {
+class RaiseSlicingOp : public OpInterfaceRewritePattern<linalg::LinalgOp> {
+public:
+  RaiseSlicingOp(MLIRContext *context, PatternBenefit benefit = 1)
+      : OpInterfaceRewritePattern(context, benefit) {}
+
+  LogicalResult matchAndRewrite(linalg::LinalgOp linalgOp,
+                                PatternRewriter &rewriter) const override {
+    if (!linalgOp.hasTensorSemantics())
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Preprocessing/Common/RaiseSlicingLinalgOps.cpp]: Just looking at this, I think there is a missing piece here. What I would expect is something that computes the shape of iteration space of Linalg op (something like this https://github.com/llvm/llvm-project/blob/22b9404f09dc4411e4f6d05f4a1724897e5e131a/mlir/include/mlir/Dialect/Linalg/IR/LinalgInterfaces.td#L737 ) to get the loop ranges. That gives you the size of the slice... Then you can for now assume the offsets and strides to be 0 and 1 respectively.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
(commented earlier from phone, so sorry for the comment without context).

Instead of a separate pass, I am trying to keep everything  in `RaiseSpecialOps`. We can use the matcher dialect/ PDL patterns to have a place where we can manage many such patterns. Havent looked into it deeply yet, but that at least we can keep everything in one place for now.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 6]
```diff
@@ -46,14 +144,22 @@ struct RaiseSpecialOpsPass : public RaiseSpecialOpsBase<RaiseSpecialOpsPass> {
...
       linalg::LinalgOp op = softmax.first;
       Value src = softmax.second;
-      IRRewriter rewriter(op.getContext());
       rewriter.setInsertionPoint(softmax.first);
       rewriter.replaceOpWithNewOp<IREE::LinalgExt::SoftmaxOp>(
           op, src, op.getDpsInitOperand(0)->get(), op.getNumLoops() - 1);
     }
+
+    getOperation()->walk([&](linalg::LinalgOp op) {
+      IRRewriter rewriter(op.getContext());
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: I think we can reuse the same `rewriter`, so we dont have to declare a new one in this walk. WDYT?

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 7]
```diff
@@ -27,6 +28,103 @@ namespace Flow {
...
+    return failure();
+
+  // The outs should be a tensor.
+  auto initTensor =
+      dyn_cast<TensorType>(linalgOp.getDpsInitOperand(0)->get().getType());
+  if (!initTensor)
+    return failure();
+
+  linalg::YieldOp yieldOp =
+      cast<linalg::YieldOp>(linalgOp.getBlock()->getTerminator());
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: nit: use `auto`. `cast` already spells the type.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 8]
```diff
@@ -27,6 +28,103 @@ namespace Flow {
...
+    return failure();
+
+  // Check that the extract op is extracting a tensor defined outside
+  // the linalg op.
+  if (source.getDefiningOp() &&
+      source.getDefiningOp()->getParentOp() == linalgOp)
+    return failure();
+
+  auto one = rewriter.getIntegerAttr(rewriter.getIntegerType(64), 1);
+  auto zero = rewriter.getIntegerAttr(rewriter.getIntegerType(64), 0);
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: nit: these can be `rewriter.getI64IntegerAttr(1/0)`.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 9]
```diff
@@ -27,6 +28,103 @@ namespace Flow {
...
+
+  int64_t rank = source.getType().getRank();
+  SmallVector<OpFoldResult> offsets;
+  SmallVector<OpFoldResult> size;
+  // We can assume strides of 1, since we checked for elementwise before.
+  SmallVector<OpFoldResult> strides(rank, one);
+
+  auto outShape = initTensor.getShape();
+  for (auto it : llvm::enumerate(extractOp.getIndices())) {
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: nit: prefer using `structured binding declaration`.

```suggestion
  for (auto [idx, indexValue] : llvm::enumerate(extractOp.getIndices())) {
```

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 10]
```diff
@@ -27,6 +28,103 @@ namespace Flow {
...
+      size.push_back(one);
+      continue;
+    }
+
+    // We assume that the indexing map is an identity.
+    if (auto indexOp = indexValue.getDefiningOp<linalg::IndexOp>()) {
+      offsets.push_back(zero);
+      if (outShape[it.index()] >= 1) {
+        size.push_back(rewriter.getIntegerAttr(rewriter.getIntegerType(64),
+                                               outShape[it.index()]));
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: ditto: can use `getI64IntegerAttr` method.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 11]
```diff
@@ -27,6 +28,103 @@ namespace Flow {
...
+
+  auto outShape = initTensor.getShape();
+  for (auto it : llvm::enumerate(extractOp.getIndices())) {
+    Value indexValue = it.value();
+
+    // The value can one of the 4: constant, linalg.index,
+    // tensor<64> in inits, variable outside the linalg region.
+    if (auto constantOp = indexValue.getDefiningOp<arith::ConstantOp>()) {
+      offsets.push_back(constantOp.getValueAttr());
+      size.push_back(one);
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: Can you add some examples or lit tests? I don't really follow why sizes could be `1`. We will replace the result of generic op with `tensor::ExtractSliceOp`. The sizes should always match initTensor?

**Review by hanhanW — CHANGES_REQUESTED** [review]
I don't follow some logics.. could you add a lit test or share an example with me?

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 12]
```diff
@@ -27,6 +28,103 @@ namespace Flow {
...
+  auto extractOp =
+      dyn_cast<tensor::ExtractOp>(yieldOp.getOperand(0).getDefiningOp());
+  if (!extractOp)
+    return failure();
+
+  // Get the tensor being extracted from.
+  TypedValue<RankedTensorType> source = extractOp.getTensor();
+
+  // Slicing does not change rank.
+  if (initTensor.getRank() == source.getType().getRank())
```
Comment (qedawkins) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: The condition is flipped here; it should be checking whether the ranks differ. Also you can add a TODO for supporting rank-reducing slicing.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp (hunk 11 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: Sorry, this was wrong, I made a refactor to do things much better.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 13]
```diff
@@ -27,6 +28,170 @@ namespace Flow {
...
+
+    // 1. Indexing value is a constant.
+    APInt constantIndex;
+    if (matchPattern(indexValue, m_ConstantInt(&constantIndex))) {
+      exprs.push_back(getAffineConstantExpr(constantIndex.getLimitedValue(),
+                                            rewriter.getContext()));
+      continue;
+    }
+    // 2. The indexing value is a linalg.index.
+    assert(isElementwise(linalgOp) && "Expected elementwise linalg op");
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: Instead of `assert, just make this the very first check, and return failure ?

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 14]
```diff
@@ -27,6 +28,170 @@ namespace Flow {
...
+    return failure();
+  }
+  AffineMap indexingMap = AffineMap::get(
+      /*dimCount=*/linalgOp.getNumLoops(),
+      /*symbolCount=*/0, exprs, rewriter.getContext());
+
+  // Replace the linalgOp with a new linalgOp where the source tensor is
+  // an input with the indexing map.
+  SmallVector<Value> newInputs = linalgOp.getInputs();
+  newInputs.insert(newInputs.begin(), extractOp.getTensor());
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp:153]: why `insert`, and not `push_back`?

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 15]
```diff
@@ -27,6 +28,170 @@ namespace Flow {
 
 namespace {
 
+static LogicalResult raiseTensorExtractToInput(linalg::GenericOp linalgOp,
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: Please leave some comments about what this method is doing.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 16]
```diff
@@ -27,6 +28,170 @@ namespace Flow {
...
+    return failure();
+
+  Value input = inputOperand->get();
+  Value output = outputOperand->get();
+  AffineMap inputIndexingMap = linalgOp.getMatchingIndexingMap(inputOperand);
+  AffineMap outputIndexingMap = linalgOp.getMatchingIndexingMap(outputOperand);
+
+  // TODO: Add raise to tensor.extract_slice.
+  // Try raising to tensor.collapse_shape.
+  (void)tryRaiseToCollapseShape(inputIndexingMap, outputIndexingMap, input,
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: return `failure` here instead of ignore it.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 17]
```diff
@@ -27,6 +28,170 @@ namespace Flow {
...
+  // Check if linalg.yield yields a block arguement.
+  auto yieldOp = dyn_cast<linalg::YieldOp>(linalgOp.getBody()->getTerminator());
+  if (!yieldOp)
+    return failure();
+  // Check if the result is a block argument.
+  auto blockArg = dyn_cast<BlockArgument>(yieldOp.getOperand(0));
+  if (!blockArg)
+    return failure();
+  // Check if the block argument is an argument of the linalgOp.
+  if (!llvm::is_contained(linalgOp.getBody()->getArguments(), blockArg))
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: you should be able to do `blockArg.getOwner() == linalgOp.getBody()`? You also need to check that the `blockArg.getArgumentNumber() == 0`

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 18]
```diff
@@ -27,6 +28,170 @@ namespace Flow {
...
+      ArrayAttr::get(linalgOp->getContext(), newIndexingMaps),
+      linalgOp.getIteratorTypesAttr(), linalgOp.getDocAttr(),
+      linalgOp.getLibraryCallAttr(), bodyBuilder);
+
+  rewriter.replaceOp(linalgOp, newLinalgOp.getResults());
+
+  return success();
+}
+
+static LogicalResult tryRaiseToCollapseShape(AffineMap inputIndexingMap,
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: Add some comments here for the logic please.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 19]
```diff
@@ -27,6 +28,170 @@ namespace Flow {
...
+                                             AffineMap outputIndexingMap,
+                                             Value input, Value output,
+                                             linalg::GenericOp linalgOp,
+                                             RewriterBase &rewriter) {
+  // Output shape must be smaller than input shape.
+  if (outputIndexingMap.getNumResults() >= inputIndexingMap.getNumResults())
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: AFAICS, if you have a `linalg.generic` operation that is all parallel, then it is undefined behavior to have the output indexing map not be a permutation. Here it seems like you are looking for a case where the input is a permutation, and output is a strict projection. I think that is undefined. To extend that, I am not sure a `tensor.collapse_shape`/`tensor.expand_shape` can be represented by a `linalg.generic`. Could you post the concrete case that made you go down that path?

EDIT: I see where you are going with this based on the test below. I think a better solution would be to use a rank-reduced extract_slice here instead of trying to use a `tensor.collapse_shape`/`tensor.expand_shape`. As mentioned above, inherently you cannot use a `linalg.generic` to represent these operations, so we are going through some "undefined behavior" when we are basically dropping unit dimensions. So I'd rather use a rank-reduced extract slice.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
This is a great start! I have some concerns about the conversion to `tensor.expand_shape`/`tensor.collapse_shape` which I explain in more detail below. But otherwise this seems to be on the right track.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
This is a great start! I have some concerns about the conversion to `tensor.expand_shape`/`tensor.collapse_shape` which I explain in more detail below. But otherwise this seems to be on the right track.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp (hunk 14 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp:153]: Adding the new input as the last input adds a new block argument between the input/init block arguments. It's easier to create the IR mapping if there is a new argument at start. For example, If we have the block arguments:

```
^bb0(%in1, %in2, %out1)
```

where in1, in2 are input args and out1 is init arg, adding the new input at end would lead to the new block arguments being:

```
^bb0(%in1, %in2, %newIn, %out1)
``` 

and we have to add checks in IR mapping. Just easier to add it to start.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 20]
```diff
@@ -76,6 +76,197 @@ std::optional<Value> matchATransposeBMatmul(linalg::LinalgOp matmulOp) {
...
+static LogicalResult raiseTensorExtractToInput(linalg::GenericOp linalgOp,
+                                               RewriterBase &rewriter) {
+  if (!linalgOp.hasTensorSemantics())
+    return failure();
+  if (!isElementwise(linalgOp))
+    return failure();
+
+  // Find a tensor.extract op in the linalgOp body.
+  tensor::ExtractOp extractOp;
+  linalgOp.walk([&](tensor::ExtractOp op) {
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: Nit: `linalgOp` have a single block... So you can just do
```
auto extractOps = linalgOp.getBody().getOps<tensor::ExtractOp>();
if (!llvm::hasSingleElement(extractOps)) {
  return failure();
}
auto extractOp = extractOps.front();
```

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 21]
```diff
@@ -76,6 +76,197 @@ std::optional<Value> matchATransposeBMatmul(linalg::LinalgOp matmulOp) {
...
+  SmallVector<AffineExpr> exprs;
+  for (Value indexValue : extractOp.getIndices()) {
+    // For raising, the indexing value must be one of the following:
+    //    1. A constant value.
+    //    2. A linalg.index.
+
+    // 1. Indexing value is a constant.
+    APInt constantIndex;
+    if (matchPattern(indexValue, m_ConstantInt(&constantIndex))) {
+      exprs.push_back(getAffineConstantExpr(constantIndex.getLimitedValue(),
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: Having constants in indexing maps is not generally a good idea. This is one of the drawbacks of going the `gather` -> `linalg.generic` -> `tensor.extract_slice` route. If we were going from `gather` -> `tensor.extract_slice` directly we would just use this value for the `offset` of the slice.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 22]
```diff
@@ -76,6 +76,197 @@ std::optional<Value> matchATransposeBMatmul(linalg::LinalgOp matmulOp) {
...
+      /*dimCount=*/linalgOp.getNumLoops(),
+      /*symbolCount=*/0, exprs, rewriter.getContext());
+
+  // Replace the linalgOp with a new linalgOp where the source tensor is
+  // an input with the indexing map.
+  SmallVector<Value> newInputs = linalgOp.getInputs();
+  newInputs.insert(newInputs.begin(), extractOp.getTensor());
+  SmallVector<Attribute> newIndexingMaps;
+  newIndexingMaps.push_back(AffineMapAttr::get(indexingMap));
+  for (AffineMap map : linalgOp.getIndexingMapsArray())
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: Nit: Please add `{` `}` around all statements. THis is the one divergence between IREE coding style and LLVM coding style.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 23]
```diff
@@ -76,6 +76,197 @@ std::optional<Value> matchATransposeBMatmul(linalg::LinalgOp matmulOp) {
...
+
+  auto bodyBuilder = [&](OpBuilder &builder, Location loc, ValueRange args) {
+    // Create an IR mapping from old block arguements to new ones.
+    IRMapping mapper;
+    ArrayRef<BlockArgument> oldArgs = linalgOp.getBody()->getArguments();
+    // Map i^th old argument to (i + 1)^th new argument.
+    for (unsigned i = 0; i < oldArgs.size(); ++i)
+      mapper.map(oldArgs[i], args[i + 1]);
+    // Clone the body of the linalgOp.
+    for (Operation &op : linalgOp.getBody()->getOperations()) {
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp:169]: It is not a requirement here, but `clone` can be pretty expensive (but here it might be OK). Ideally you should be moving the region as much as possible.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 24]
```diff
@@ -76,6 +76,197 @@ std::optional<Value> matchATransposeBMatmul(linalg::LinalgOp matmulOp) {
...
+        sizes.push_back(dim.getResult());
+      } else {
+        sizes.push_back(rewriter.getI64IntegerAttr(outShape[currOutDim]));
+      }
+      ++currOutDim;
+      continue;
+    }
+    // Assume that the constant access is a rank reducing access.
+    if (expr.isa<AffineConstantExpr>() &&
+        expr.cast<AffineConstantExpr>().getValue() == 0) {
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: It doesnt have to be 0. It could be any constant value.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 25]
```diff
@@ -119,6 +313,18 @@ struct RaiseSpecialOpsPass : public RaiseSpecialOpsBase<RaiseSpecialOpsPass> {
       rewriter.replaceOpWithNewOp<linalg::MatmulTransposeBOp>(
           matmulOp, ValueRange{lhs, newRhs}, ValueRange{init}, attrs);
     }
+
+    // Raise tensor.export.
+    getOperation()->walk([&](linalg::GenericOp op) {
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: This now does two walks over the whole program.... can be expensive....

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Great! Looking much better. I just have one concern w.r.t having indexing maps that have constant values in their results. This is generally not "good practice" for Linalg ops, and this is only happening cause we are having an intermediate `linalg.generic`. I think it has value, but if we went to a `tensor.extract_slice` directly, (a) the code is significantly less complex and (b) we dont introduce the constant value in results of indexing maps. I'd still strongly suggest doing that. (I do think the path to go to an intermediate `linalg.generic` was a good one, but just doesnt seem to be justified at this point). What do you think?

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp (hunk 25 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: Merged to one walk.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp (hunk 21 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: I feel like tensor.extract in general is a bigger evil than having constants in an affine map. I would always prefer a tensor.extract to be raised to an input, even if it produces constants in an affine map. So while, I agree it's bad, it's a lesser evil for me.

Also, another reason I match for constants in the raising to view pattern is a lot of inputs use a constant for dimensions of size 1, instead of getting the dimension from linalg.index. So we have to support constants in AffineMap in these raising patterns.

**Comment by Groverkss** [comment]
I mentioned the reason I prefer tensor.extract raising in another comment. Another reason is that while writing the pass in one-shot, the reasoning is more complex and was much harder to implement. I find this way much easier.

Personally, I prefer this "partial" raising approach much more than a combined approach. But if you still feel that we should go with the combined approach, I will switch to that.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp (hunk 21 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: Ok, my concern is more when the raising to `linalg.generic` happens and the conversion to `tensor.extract_slice` doesnt happen. How about we split the difference (and I do like the intermediate `linalg.generic`) : For a gather-like op convert it to the intermediate `linalg.generic` and return it (i.e. dont replace uses of the gather-like op with the `linalg.generic`). Use that to immediately convert the `linalg.generic` to `tensor.extract_slice`. If the second conversion succeeds, replace the original gather-like op with the `tensor.extract_slice`. If it doesnt, just leave the original gather-like op as is (the intermediate generated will get DCEed or you can explicitly delete it as well).

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 26]
```diff
@@ -286,18 +305,24 @@ struct RaiseSpecialOpsPass : public RaiseSpecialOpsBase<RaiseSpecialOpsPass> {
     IRRewriter rewriter(&getContext());
 
     getOperation()->walk([&](linalg::GenericOp op) {
-      rewriter.setInsertionPoint(op);
+      linalg::GenericOp linalgOp = op;
 
-      // Try raising to tensor.export.
+      // Try raising to tensor.export and create an intermediate linalg.generic.
+      rewriter.setInsertionPoint(op);
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp:317]: Typically good to guard insertion point changes with 
```
OpBuilder::InsertionGuard g(rewriter);
```

otherwise the insertion point doesnt get reset and then leads to weird errors.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp [hunk 27]
```diff
@@ -76,12 +76,255 @@ std::optional<Value> matchATransposeBMatmul(linalg::LinalgOp matmulOp) {
...
+  SmallVector<AffineExpr> exprs;
+  for (auto [idx, indexValue] : llvm::enumerate(extractOp.getIndices())) {
+    // For raising, the indexing value must be one of the following:
+    //    1. A constant value.
+    //    2. A linalg.index.
+
+    // 1. Indexing value is a constant.
+    APInt constantIndex;
+    if (matchPattern(indexValue, m_ConstantInt(&constantIndex))) {
+      exprs.push_back(getAffineConstantExpr(constantIndex.getLimitedValue(),
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RaiseSpecialOps.cpp]: Could you restrict this to cases where the value is 0?

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
I only have one small remaining comment. After that this should be good to land.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
I only have one small remaining comment. After that this should be good to land.

**Review by MaheshRavishankar — APPROVED** [review]

**Review by hanhanW — APPROVED** [review]
