### PR TITLE
Reapply "[GPU] Allow multi result and indexing compute generic ops in TilleAndFuse pipeline" (#22205)"

### LINKED ISSUE #22175: [GPU] RoPE + Scatter dispatch producing incorrect results
### What happened?

Fusion changes https://github.com/iree-org/iree/pull/22065 led to RoPE and scatter operations fusing into a single dispatch. However, this produced incorrect results when testing accuracy of `llama-70b-fp8`.

I found that for [this executable source](https://gist.github.com/IanWood1/f8b41697bd722fcbff82d301d149f091) the RoPE operation is getting assigned the default config. Forcing the config to be set on the scatter and giving it a "Scatter Op Config" produces correct results for the full model.

### Version information

IREE @ 139f642875c931953d09b44730ec51d8fedf6266

### Additional context

The model was only producing incorrect output on 1 of 3 test cases so the bug here might be subtle. I don't currently have a good correctness reproducer since I was testing with shark-ai but I can help validate any changes and/or get a better reproducer.

### LINKED ISSUE #22204: [GPU] Llama 70b fp8 compilation regression
### What happened?

Llama 70 fails to compile after https://github.com/iree-org/iree/pull/22195. I reverted the PR and llama could successfully compile.

Error:

```
sources/module_decode_bs4$async_dispatch_1014.mlir:28:17: error: 'vector.transfer_write' op write affecting operations on global resources are restricted to workgroup distributed contexts.          
%11 = arith.muli %10, %c2_i64 : i64
                ^                                                                                                                                                                           
sources/module_decode_bs4$async_dispatch_1014.mlir:28:17: note: see current operation: "vector.transfer_write"(%41, %23, %38) <{in_bounds = [true], operandSegmentSizes = array<i32: 1, 1, 1, 0>, permutation_map = affine_map<(d0) -> (d0)>}> : (vector<2xi64>, memref<4xi64, #amdgpu.address_space<fat_raw_buffer>>, index) -> ()                                                     
sources/module_decode_bs4$async_dispatch_1014.mlir:8:7: error: 'func.func' op failed on workgroup distribution verification    
```

### Steps to reproduce your issue

1. Download any/all of the executable sources from the gist https://gist.github.com/IanWood1/273c2d25493dc9d9f75d66c76988164e
2. Run `iree-compile --compile-from=executable-sources source.mlir`
3. See error (similar to above)

### What component(s) does this issue relate to?

_No response_

### Version information

f7fa7b09ca26f691ca361ae27d4633ca6f067d46

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvedhmeshram**
Supporting this cases exposed an unrelated issue with broadcasting dims from a producer of the consumer op which is now fixed in this version of the PR. We wont distibute the broadcasted dims as the producer cant be fused in that case.

Fixes : https://github.com/iree-org/iree/issues/22204
Fixes : https://github.com/iree-org/iree/issues/22175

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 1]
```diff
@@ -1025,6 +1025,47 @@ struct DistributionInfo {
   bool vectorizable = false;
 };
 
+// Generally parallel loops are pationable, however if the dims for it
```
Comment (qedawkins) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]:
```suggestion
// Generally parallel loops are partitionable, however if the dims for it
```

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 2]
```diff
@@ -1025,6 +1025,47 @@ struct DistributionInfo {
...
+    auto producerOp = operand->get().getDefiningOp<linalg::LinalgOp>();
+    if (producerOp) {
+      ProducerOperands.push_back(operand);
+    }
+  }
+  if (ProducerOperands.empty()) {
+    return partitionableLoops;
+  }
+  // If we have producer operands then we need to confirm that all of them
+  // also have the the partionableLoop dims if not we skip that dim.
```
Comment (qedawkins) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: This is not what we want. When a broadcasted producer is only consumed by one op (this one) distributing that dim is no problem. It's only a problem if we also are returning that value from a dispatch because the producer ends up rematerialized across workgroups.

**Review by qedawkins — CHANGES_REQUESTED** [review]
This needs a stronger check that the broadcasted producer is returned from the executable. Then otherwise this looks good.

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp (hunk 2 above)
Comment (nirvedhmeshram) [reply compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: makes sense should we check if the producer has a `iree_codegen.store_to_buffer` user or should we check if it has any user at all thats not the core compute op? The former might be brittle if we change the API but later might not be strong enough as if a consumer of the compute op is using it maybe those dims are ok to distribute.

Comment (nirvedhmeshram) [reply compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: I did the check for `iree_codegen.store_to_buffer` way, I think its ok as lot of codegen is using that op in a load bearing way anyway.

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 3]
```diff
@@ -1025,6 +1025,55 @@ struct DistributionInfo {
...
 
+// Generally parallel loops are partitionable, however if the dims for it
+// are not present in a producer of the compute op within the dispatch and the
+// results of that producer op are also returned from the dispatch
+// then that dim is not partitioned as codegen for this is unsupported.
+static SmallVector<unsigned int>
+getSupportedPartitionableLoops(linalg::LinalgOp linalgOp) {
+  SmallVector<unsigned int> partitionableLoops;
+  linalgOp.getParallelDims(partitionableLoops);
+  SmallVector<OpOperand *> ProducerOperands;
```
Comment (qedawkins) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: nit: camel case.
```suggestion
  SmallVector<OpOperand *> producerOperands;
```

**Review by qedawkins — APPROVED** [review]

**Comment by pdhirajkumarprasad** [comment]
We have regression in compile for llama model due to this change.

command:
```
iree-compile output.mlir --iree-hip-target=gfx942 -o tt.vmfb --iree-hal-target-device=hip --iree-opt-level=O3 --iree-hal-indirect-command-buffers=true --iree-stream-resource-memory-model=discrete --iree-hip-enable-tensor-ukernels --iree-stream-affinity-solver-max-iterations=1024 --iree-hal-memoization=true --iree-codegen-enable-default-tuning-specs=true --iree-llvmgpu-test-combine-layout-transformation=false
```
[output.mlir.txt](https://github.com/user-attachments/files/22878200/output.mlir.txt)

**Comment by IanWood1** [comment]
@pdhirajkumarprasad which model variant is regressing?

**Comment by Groverkss** [comment]
We have CI to prevent this. 

If this is a llama 8b fp8/fp16 variant, can we first update the IR in the cI here: https://github.com/iree-org/iree/blob/main/tests/external/iree-test-suites/torch_models/llama_8b_fp16/modules/llama_gfx942.json

and

https://github.com/iree-org/iree/blob/main/tests/external/iree-test-suites/torch_models/llama_8b_fp8/modules/llama_gfx942.json

We can then catch these regressions in CI

**Comment by MaheshRavishankar** [comment]
> We have regression in compile for llama model due to this change.
> 
> command:
> 
> ```
> iree-compile output.mlir --iree-hip-target=gfx942 -o tt.vmfb --iree-hal-target-device=hip --iree-opt-level=O3 --iree-hal-indirect-command-buffers=true --iree-stream-resource-memory-model=discrete --iree-hip-enable-tensor-ukernels --iree-stream-affinity-solver-max-iterations=1024 --iree-hal-memoization=true --iree-codegen-enable-default-tuning-specs=true --iree-llvmgpu-test-combine-layout-transformation=false
> ```
> 
> [output.mlir.txt](https://github.com/user-attachments/files/22878200/output.mlir.txt)

@pdhirajkumarprasad  We have to revert a few changes if we need to revert. A little more information about the failure would help..

@nirvedhmeshram / @IanWood1  can you see if ToM is failing with this?

**Comment by IanWood1** [comment]
Here are the failing executable sources from ToM(4efac5b962b7a58f5c1ff26353eae057b3bda475): https://gist.github.com/IanWood1/9a6ee98c76a8ef186071a69c539fcefa

To reproduce use ` iree-compile source.mlir -o /dev/null --compile-from=executable-sources  --iree-llvmgpu-test-combine-layout-transformation=false` on any of the sources.

`--iree-llvmgpu-test-combine-layout-transformation=false` seems to be related. Removing it fixes the compilation error. Why are we using a "test" flag?

**Comment by nirvedhmeshram** [comment]
> Here are the failing executable sources from ToM([4efac5b](https://github.com/iree-org/iree/commit/4efac5b962b7a58f5c1ff26353eae057b3bda475)): https://gist.github.com/IanWood1/9a6ee98c76a8ef186071a69c539fcefa
> 
> To reproduce use ` iree-compile source.mlir -o /dev/null --compile-from=executable-sources --iree-llvmgpu-test-combine-layout-transformation=false` on any of the sources.
> 
> `--iree-llvmgpu-test-combine-layout-transformation=false` seems to be related. Removing it fixes the compilation error. Why are we using a "test" flag?

ok so the problem is without that flag we end up with `iree_tensor_ext.dispatch.tensor.store ` but now our codegen is set up for `iree_codegen.store_to_buffer` @Max191 is it ok to not use this flag? would like to understand the context why model people are using it..

**Comment by nirvedhmeshram** [comment]
ok I have a fix over here https://github.com/iree-org/iree/pull/22291
