### PR TITLE
[LinalgExt] Fix `FoldWithProducerReshapeByExpansion` for >1 dyn dim

### LINKED ISSUE #21889: Compilation Failure during `FoldWithProducerReshapeByExpansion` pattern
### What happened?

While compiling the repro IR provided below, compilation fails during the pass `-iree-dispatch-creation-bubble-up-expand-shapes` with the below error:
```
error: 'tensor.expand_shape' op expected number of static shape dims to be equal to the output rank (5) but found 0 inputs instead
  %9 = iree_linalg_ext.scatter dimension_map = [0] unique_indices(true) ins(%collapsed, %1 : tensor<?x4x32x32xf16>, tensor<?xi64>) outs(%3 : tensor<?x4x32x32xf16>) {
       ^
repro.mlir:15:8: note: see current operation: %10 = "tensor.expand_shape"(%9) <{reassociation = [[0, 1], [2], [3], [4]], static_output_shape = array<i64>}> : (tensor<?x4x32x32xf16>) -> tensor<?x?x4x32x32xf16>
```

The error originates from the pattern `FoldWithProducerReshapeByExpansion` here: https://github.com/iree-org/iree/blob/dd1688bcc968b265769eb9114023acc2d46789d1/compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp#L428 because the `expandOp` created here: https://github.com/iree-org/iree/blob/dd1688bcc968b265769eb9114023acc2d46789d1/compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp#L99-L100 does not specify output shape, as a result, it fails during the verifier run of the `expandOp`.

### Steps to reproduce your issue

Run the following command:
```
iree-opt -iree-dispatch-creation-bubble-up-expand-shapes repro.mlir
```
for the below IR:
```
util.func public @prefill_bs4$async(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view, %arg2: !hal.buffer_view, %arg3: !hal.buffer_view, %arg4: !hal.buffer_view, %arg5: !hal.fence, %arg6: !hal.fence) -> !hal.buffer_view attributes {inlining_policy = #util.inline.never, iree.abi.model = "coarse-fences", iree.abi.stub} {
  %0 = hal.buffer_view.dim<%arg2 : !hal.buffer_view>[0] : index
  %1 = hal.tensor.import wait(%arg5) => %arg2 : !hal.buffer_view -> tensor<?xi64>{%0}
  %2 = hal.buffer_view.dim<%arg3 : !hal.buffer_view>[0] : index
  %3 = hal.tensor.import wait(%arg5) => %arg3 : !hal.buffer_view -> tensor<?x4x32x32xf16>{%2}
  %4 = hal.buffer_view.dim<%arg4 : !hal.buffer_view>[0] : index
  %5 = hal.buffer_view.dim<%arg4 : !hal.buffer_view>[1] : index
  %6 = hal.tensor.import wait(%arg5) => %arg4 : !hal.buffer_view -> tensor<?x?x32x4x32xf16>{%4, %5}
  %7 = tensor.empty(%4, %5) : tensor<?x?x4x32x32xf16>
  %8 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2, d3, d4)>, affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d3, d2, d4)>], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel"]} ins(%6 : tensor<?x?x32x4x32xf16>) outs(%7 : tensor<?x?x4x32x32xf16>) {
  ^bb0(%in: f16, %out: f16):
    linalg.yield %in : f16
  } -> tensor<?x?x4x32x32xf16>
  %collapsed = tensor.collapse_shape %8 [[0, 1], [2], [3], [4]] : tensor<?x?x4x32x32xf16> into tensor<?x4x32x32xf16>
  %9 = iree_linalg_ext.scatter dimension_map = [0] unique_indices(true) ins(%collapsed, %1 : tensor<?x4x32x32xf16>, tensor<?xi64>) outs(%3 : tensor<?x4x32x32xf16>) {
  ^bb0(%arg7: f16, %arg8: f16):
    iree_linalg_ext.yield %arg7 : f16
  } -> tensor<?x4x32x32xf16>
  %10 = hal.tensor.barrier join(%9 : tensor<?x4x32x32xf16>) => %arg6 : !hal.fence
  %11 = hal.tensor.export %10 : tensor<?x4x32x32xf16>{%2} -> !hal.buffer_view
  util.return %11 : !hal.buffer_view
}
```

### What component(s) does this issue relate to?

_No response_

### Version information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by IanWood1**
The builder for `tensor.expand_shape` cannot infer the output shape in cases where there are more then 1 dynamic dimensions. So, `ExpansionInfo` needs to track the SSA values for the expanded shape to be able to create reshapes. 

This introduces two problems:
1. Creating `tensor.dim` ops early (i.e. before knowing if the pattern can be successfully applied) will cause the greedy pattern rewrite driver to loop forever. This is fixed by using the `DimSize` class to delay IR modifications until the pattern is known to not fail.
2. In the case of `iree_linalg_ext -> tensor.expand_shape`, the output shape SSA values must be moved to dominate the op. This is also done upstream:
   https://github.com/llvm/llvm-project/blob/879f40ab041b31fa73b9b25e4ec9e06e810bc767/mlir/lib/Dialect/Linalg/Transforms/ElementwiseOpFusion.cpp#L875-L894

Closes https://github.com/iree-org/iree/issues/21889

### CODE REVIEW

**Comment by IanWood1** [comment]
The `DimSize` class feels a bit clunky so suggestions there would be helpful (I don't think its possible to use an `llvm::PointerUnion` or a `std::variant`).


Side note: I think the upstream pattern might also hit issues with problem (1).

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp [hunk 1]
```diff
@@ -11,17 +11,62 @@
...
 #include <cstdint>
 #include <optional>
 
 namespace mlir::iree_compiler::IREE::LinalgExt {
+namespace {
+
+/// Represents the size of a dimension of some ShapedType value in the IR. This
+/// is used instead of OpFoldResult when modifying the IR is illegal. This can
+/// still be constructed from an OpFoldResult in cases where the value can be
+/// obtained without ir modification.
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp]: nit

```suggestion
/// obtained without IR modification.
```

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp [hunk 2]
```diff
@@ -81,13 +125,16 @@ class ExpansionInfo {
...
-    SmallVector<int64_t> flattenedArray;
+    SmallVector<OpFoldResult> outputShape;
     for (auto &shape : shapeMap) {
-      flattenedArray.append(shape.begin(), shape.end());
+      llvm::append_range(
+          outputShape, llvm::map_range(shape, [&rewriter](const DimSize &size) {
+            return size.materialize(rewriter);
+          }));
     }
+    auto [staticShape, _] = decomposeMixedValues(outputShape);
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp]: Don't you need `(void)_` to prevent unused var warning? In this case, maybe we can give it a better name like `dynShapeValues`.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp [hunk 3]
```diff
@@ -206,7 +248,8 @@ LogicalResult ExpansionInfo::compute(
     for (auto [operandDim, iterDim] :
          llvm::enumerate(info.operandToIterationSpace)) {
       if (iterDim != ReshapeOperandInfo::kNoMapping &&
-          loopRanges[iterDim] != info.originalShape[operandDim]) {
+          ShapedType::isStatic(loopRanges[iterDim]) !=
+              info.originalShape[operandDim].isStatic()) {
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp:253]: IIUC, this only checks if they are both static or both dynamic. Where do we check if the static sizes match?

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp [hunk 4]
```diff
@@ -229,12 +272,23 @@ LogicalResult ExpansionInfo::compute(
...
+    for (auto [operandIdx, loopIdx] :
+         llvm::enumerate(info.operandToIterationSpace)) {
+      if (loopIdx == ReshapeOperandInfo::kNoMapping) {
+        continue;
+      }
+
+      if (this->loopShapeMap[loopIdx].empty()) {
+        this->loopShapeMap[loopIdx] =
+            SmallVector<DimSize>{info.originalShape[operandIdx]};
+      }
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp]: I'd combine two checks and save one level of indent. E.g.,

```cpp
if (... || !this....empty()) {
  continue;
}
// set the value;
```

**Review by hanhanW — COMMENTED** [review]
cool improvement!

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp (hunk 3 above)
Comment (IanWood1) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp:253]: Static sizes should match via the verifier, but the operands can be mixed static/dynamic. For example, a simple elementwise op can have an input of `tensor<10xi32>` and an output of `tensor<?xi32>`. The dynamic dim of `tensor<?xi32>` can be made more static (10) but doesn't have to be.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp (hunk 2 above)
Comment (IanWood1) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp]: I'm not sure why its not giving a warning, but good point I'll change this.

Comment (hanhanW) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp]: I think we don't have the check in presubmit CI, but maybe we have it in some post-submit windows build. (I don't remember details)

**Review by hanhanW — APPROVED** [review]
LGTM

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp [hunk 5]
```diff
@@ -81,13 +125,17 @@ class ExpansionInfo {
...
-    SmallVector<int64_t> flattenedArray;
+    SmallVector<OpFoldResult> outputShape;
     for (auto &shape : shapeMap) {
-      flattenedArray.append(shape.begin(), shape.end());
+      llvm::append_range(
+          outputShape, llvm::map_range(shape, [&rewriter](const DimSize &size) {
+            return size.materialize(rewriter);
+          }));
     }
+    auto [staticShape, dynamicShape] = decomposeMixedValues(outputShape);
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp:135]: I think you can do `auto [staticShape, _] = decomposeMixedValues(outputShape)`

**Review by MaheshRavishankar — APPROVED** [review]

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp (hunk 5 above)
Comment (IanWood1) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ReshapeFusion.cpp:135]: I looked and it seems there is nothing special about `_` its just a variable name. As @hanhanW was suggesting if we don't need `(void)_` using `_` seems fine. But I'm not sure why its not producing a unused variable warning.
