### PR TITLE
[VectorDistribute] Do not handle bit extend during matmul configuration

### LINKED ISSUE #21434: iree compile failed on mi355 for llama 8b fp8
### What happened?

iree compile failed on mi355 10-09 for llama 8b fp8 start from commit `4b831861c5341cafd0eef55fdbfe3f8c2b53a20c`  https://github.com/iree-org/iree/pull/21346 @IanWood1 @MaheshRavishankar 
Here is the bisect log [bisect_355_0718-0721.txt](https://gist.github.com/AmosLewis/04c13a2858dfef1a3d7daada45ebe47f#file-bisect_355_0718-0721-txt)

### Steps to reproduce your issue

The mlir was exported by shark-ai 0718_5cc015
```
wget https://sharkpublic.blob.core.windows.net/sharkpublic/chi/llama/atten/fp8_attn_iree0718.shark0718_5cc015_kv_float8_e4m3fn.mlir
```
```
iree-compile /sharedfile/f8/128/out/fp8_attn_iree0718.shark0718_5cc015_kv_float8_e4m3fn.mlir --iree-hip-target=gfx950 -o=/sharedfile/f8/bisect/bisect.vmfb --iree-hal-target-device=hip --iree-opt-level=O3 --iree-dispatch-creation-propagate-collapse-across-expands=true --iree-stream-affinity-solver-max-iterations=1024 --iree-hal-indirect-command-buffers=true --iree-stream-resource-memory-model=discrete --iree-hip-specialize-dispatches --iree-hal-memoization=true --iree-codegen-enable-default-tuning-specs=true
```

```
/sharedfile/f8/128/out/fp8_attn_iree0718.shark0718_5cc015_kv_float8_e4m3fn.mlir:3517:13: error: Unable to set intrinsic layouts on operation based on given lowering config: #iree_gpu.lowering_config<{mma_kind = #iree_gpu.mma_layout<MFMA_F32_16x16x128_F8E4M3FN>, promote_operands = [0, 1], reduction = [0, 0, 0, 512], subgroup_m_count = 2 : i64, subgroup_n_count = 2 : i64, workgroup = [1, 64, 128, 0]}>
    %1186 = torch.aten.mm %1185, %1183 : !torch.vtensor<[?,4096],f32>, !torch.vtensor<[4096,14336],f32> -> !torch.vtensor<[?,14336],f32>
            ^
...
```

### What component(s) does this issue relate to?

Compiler

### Version information

4b831861c5341cafd0eef55fdbfe3f8c2b53a20c

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Groverkss**
We shouldn't be handling bit extends outside of the contraction during configuration. The bit extend should be fused with the contraction for it to target intrinsics. This behavior matches what TileAndFuse does and prevents problems with cases like:

```

%lhs = linalg.generic {
  %ext = arith.extf %in
  %scaled = arith.mulf %ext, %scale
}

...

// mma
linalg.generic %lhs, %rhs
```

Here the scaling doesn't allow us to target intrinsics, but currently vector distribute will target intrinsics.

Fixes: https://github.com/iree-org/iree/issues/21434

### CODE REVIEW

**Comment by Groverkss** [comment]
Depends on https://github.com/iree-org/iree/pull/21797 , please only review the top commit

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 1]
```diff
@@ -616,37 +617,28 @@ populateConfigInfo(const llvm::SetVector<linalg::LinalgOp> &computeOps,
...
-        llvm::any_of(linalgOp->getUsers(), [&](Operation *user) {
+    // We want to attach a lowering config to this operation if it introduces
+    // a new dimension, when going by topological order in the backward slice.
+    // The only two ways to introduce a new dimension are:
+    //
+    // 1. We have a reduction dimension.
+    if (hasReductionIterator(linalgOp)) {
+      return true;
+    }
+    // 2. There is no consumer which is a compute op (i.e. it already
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp]:
```suggestion
    // 2. There is no consumer which is a compute op (i.e., it already
```

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 2]
```diff
@@ -616,37 +617,28 @@ populateConfigInfo(const llvm::SetVector<linalg::LinalgOp> &computeOps,
...
+    // has some way of getting fused).
+    if (!llvm::any_of(linalgOp->getUsers(), [&](Operation *user) {
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp]: nit/optional: use `llvm::none_of`?

**Review by kuhar — APPROVED** [review]
Ooops, seems like I didn't read the instructions:
> please only review the top commit

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp (hunk 2 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:630]: none_of returns false if the list is empty, while !any_of returns true if the list is empty. I want the true behavior if the list is empty.
