### PR TITLE
[Flow] Fix dominance error in `FormScalarDispatches`

### LINKED ISSUE #17759: dominance-related failure occurs when compiling an opt model
### What happened?

This error came from testing the `/onnx/models/opt-125M-vaiq` model in <https://github.com/nod-ai/SHARK-TestSuite>:

```
opt-125M-awq.default.onnx.torch.mlir:1218:13: error: operand #0 does not dominate this use
    %1166 = torch.aten.item %1165 : !torch.vtensor<[],si64> -> !torch.int
            ^
opt-125M-awq.default.onnx.torch.mlir:1218:13: note: see current operation: %412 = "tensor.extract"(%415#1) : (tensor<i32>) -> i32
opt-125M-awq.default.onnx.torch.mlir:1229:13: note: operand defined here (op in the same block)
    %1175 = torch.aten.where.self %1172, %1173, %1174 : !torch.vtensor<[],i1>, !torch.vtensor<[],si64>, !torch.vtensor<[],si64> -> !torch.vtensor<[],si64>
            ^
```

### Steps to reproduce your issue

Download a smaller reproducer from [this gist](https://gist.github.com/zjgarvey/32cebbb721e725839676e734879dfc02), then run 

```
iree-compile --iree-input-demote-i64-to-i32 --iree-hal-target-backends=llvm-cpu  --iree-input-type=torch dom_error_repro.torch.mlir -o dump.vmfb
```

This will result in the error message:

```
dom_error_repro.torch.mlir:62:11: error: operand #0 does not dominate this use
    %55 = torch.aten.item %54 : !torch.vtensor<[],si64> -> !torch.int
          ^
dom_error_repro.torch.mlir:62:11: note: see current operation: %17 = "tensor.extract"(%20#1) : (tensor<i32>) -> i32
dom_error_repro.torch.mlir:71:11: note: operand defined here (op in the same block)
    %64 = torch.aten.where.self %61, %62, %63 : !torch.vtensor<[],i1>, !torch.vtensor<[],si64>, !torch.vtensor<[],si64> -> !torch.vtensor<[],si64>

```

It seems to be failing on the pass `iree-flow-form-scalar-dispatches`. Here is the dump after failure:

```MLIR
// -----// IR Dump After FormScalarDispatchesPass Failed (iree-flow-form-scalar-dispatches) //----- //
"util.func"() <{function_type = (!hal.buffer_view, !hal.buffer_view, !hal.buffer_view, !hal.fence, !hal.fence) -> !hal.buffer_view, inlining_policy = #util.inline.never, sym_name = "main_graph$async"}> ({
^bb0(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view, %arg2: !hal.buffer_view, %arg3: !hal.fence, %arg4: !hal.fence):
  %0 = "arith.constant"() <{value = 0 : index}> : () -> index
  %1 = "arith.constant"() <{value = 1 : index}> : () -> index
  %2 = "arith.constant"() <{value = 0 : i32}> : () -> i32
  %3 = "arith.constant"() <{value = dense<[-1, 0]> : tensor<2xi32>}> : () -> tensor<2xi32>
  %4 = "hal.buffer_view.dim"(%arg0) {index = 0 : index} : (!hal.buffer_view) -> index
  %5 = "hal.buffer_view.dim"(%arg0) {index = 1 : index} : (!hal.buffer_view) -> index
  %6 = "hal.tensor.import"(%arg0, %4, %5, %arg3) {operandSegmentSizes = array<i32: 1, 2, 1>, target_encoding = tensor<?x?xi64>} : (!hal.buffer_view, index, index, !hal.fence) -> tensor<?x?xi32>
  %7 = "arith.index_cast"(%4) : (index) -> i32
  %8 = "arith.index_cast"(%5) : (index) -> i32
  %9 = "tensor.empty"() : () -> tensor<i32>
  %10 = "flow.dispatch.region"() <{operandSegmentSizes = array<i32: 0, 0>}> ({
    %34 = "linalg.generic"(%9) <{indexing_maps = [affine_map<() -> ()>], iterator_types = [], operandSegmentSizes = array<i32: 0, 1>}> ({
    ^bb0(%arg7: i32):
      "linalg.yield"(%8) : (i32) -> ()
    }) : (tensor<i32>) -> tensor<i32>
    "flow.return"(%34) : (tensor<i32>) -> ()
  }, {
    %33 = "arith.constant"() <{value = 1 : index}> : () -> index
    "flow.return"(%33, %33, %33) : (index, index, index) -> ()
  }) : () -> tensor<i32>
  %11 = "tensor.expand_shape"(%10) <{reassociation = [], static_output_shape = array<i64: 1>}> : (tensor<i32>) -> tensor<1xi32>
  %12 = "tensor.insert_slice"(%10, %3) <{operandSegmentSizes = array<i32: 1, 1, 0, 0, 0>, static_offsets = array<i64: 1>, static_sizes = array<i64: 1>, static_strides = array<i64: 1>}> : (tensor<i32>, tensor<2xi32>) -> tensor<2xi32>
  %13 = "tensor.extract_slice"(%12) <{operandSegmentSizes = array<i32: 1, 0, 0, 0>, static_offsets = array<i64: 0>, static_sizes = array<i64: 1>, static_strides = array<i64: 1>}> : (tensor<2xi32>) -> tensor<i32>
  %14 = "tensor.expand_shape"(%13) <{reassociation = [], static_output_shape = array<i64: 1>}> : (tensor<i32>) -> tensor<1xi32>
  %15 = "tensor.extract"(%14, %0) : (tensor<1xi32>, index) -> i32
  %16 = "arith.cmpi"(%15, %2) <{predicate = 0 : i64}> : (i32, i32) -> i1
  %17 = "tensor.extract"(%20#1) : (tensor<i32>) -> i32
  %18 = "tensor.extract"(%11, %0) : (tensor<1xi32>, index) -> i32
  %19 = "arith.cmpi"(%18, %2) <{predicate = 0 : i64}> : (i32, i32) -> i1
  %20:2 = "flow.dispatch.region"() <{operandSegmentSizes = array<i32: 0, 0>}> ({
    %29 = "linalg.generic"(%9) <{indexing_maps = [affine_map<() -> ()>], iterator_types = [], operandSegmentSizes = array<i32: 0, 1>}> ({
    ^bb0(%arg6: i32):
      %32 = "arith.select"(%16, %7, %15) : (i1, i32, i32) -> i32
      "linalg.yield"(%32) : (i32) -> ()
    }) : (tensor<i32>) -> tensor<i32>
    %30 = "linalg.generic"(%9) <{indexing_maps = [affine_map<() -> ()>], iterator_types = [], operandSegmentSizes = array<i32: 0, 1>}> ({
    ^bb0(%arg5: i32):
      %31 = "arith.select"(%19, %8, %18) : (i1, i32, i32) -> i32
      "linalg.yield"(%31) : (i32) -> ()
    }) : (tensor<i32>) -> tensor<i32>
    "flow.return"(%30, %29) : (tensor<i32>, tensor<i32>) -> ()
  }, {
    %28 = "arith.constant"() <{value = 1 : index}> : () -> index
    "flow.return"(%28, %28, %28) : (index, index, index) -> ()
  }) : () -> (tensor<i32>, tensor<i32>)
  %21 = "tensor.extract"(%20#0) : (tensor<i32>) -> i32
  %22 = "tensor.from_elements"(%17, %21) : (i32, i32) -> tensor<2xi32>
  %23 = "tensor.reshape"(%6, %22) : (tensor<?x?xi32>, tensor<2xi32>) -> tensor<?x?xi32>
  %24 = "hal.tensor.barrier"(%23, %arg4) : (tensor<?x?xi32>, !hal.fence) -> tensor<?x?xi32>
  %25 = "tensor.dim"(%24, %0) : (tensor<?x?xi32>, index) -> index
  %26 = "tensor.dim"(%24, %1) : (tensor<?x?xi32>, index) -> index
  %27 = "hal.tensor.export"(%24, %25, %26) {source_encoding = tensor<?x?xi64>} : (tensor<?x?xi32>, index, index) -> !hal.buffer_view
  "util.return"(%27) : (!hal.buffer_view) -> ()
}) {iree.abi.model = "coarse-fences", iree.abi.stub} : () -> ()
```

### What component(s) does this issue relate to?

Compiler

### Version information

using a local build at commit 3b5d269c7fec61743cc41f4394b33a31625ef2ae

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by IanWood1**
Issue here https://github.com/iree-org/iree/issues/17759

When preforming horizontal fusion, ops that were clonable (but not used by the fusion group) were ignored. If these ops were dependent on values produced by 'root ops', then the root op would get moved into the region. The logic here probably needs to get refactored because there is probably missed horizontal fusion opportunities. This probably need a more in depth analysis, however.

### CODE REVIEW

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/FormScalarDispatches.cpp [hunk 1]
```diff
@@ -197,7 +197,18 @@ void FormScalarDispatchesPass::runOnOperation() {
...
-        if (isClonableIntoDispatchOp(prevOp)) {
+        // Keep looking for more roots to horizontally fuse if the `prevOp` has
+        // no dependencies. e.g. `tensor.empty()`
+        if (prevOp->getNumOperands() == 0 && prevOp->getNumRegions() == 0)
+          continue;
+
+        // If `prevOp` is clonable AND only used by the fused/cloned then it
+        // will get cloned before any possible roots that may define its
+        // operands. (if it is not used by the region it may not be cloned)
+        if (isClonableIntoDispatchOp(prevOp) &&
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/FormScalarDispatches.cpp]: Maybe we just stop forming dispatches past clonable ops. They will get transitively cloned

Comment (IanWood1) [reply compiler/src/iree/compiler/Dialect/Flow/Transforms/FormScalarDispatches.cpp]: I think this would result in nearly no horizontal fusion since any root directly proceeding a `tensor.empty` would not be fusible with any other op. For example, in this test case https://github.com/iree-org/iree/blob/c28823103cf86d971ee46e5405d9badeacaa286d/compiler/src/iree/compiler/Dialect/Flow/Transforms/test/form_scalar_dispatches.mlir#L97-L116

`%2` and `%6` can't be placed in the same dispatch but because `%5 = tensor.empty() : tensor<f32>` is between them.

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Dialect/Flow/Transforms/FormScalarDispatches.cpp]: Ok, i see your point... let me think about this a bit more.

**Comment by IanWood1** [comment]
The previous logic is that after finding a root, `rootOp`, that can be put into a dispatch, it would search backwards for further root ops, skipping over clonable ops, and stopping when encountering a non-clonable and non-root operation (*Note: a root op is not clonable. see isScalarOperation*). In order for this to work properly, none of the clonable ops can use values defined by roots that will be horizontally fused.

In the example below, assume `%0` and `%2` both satisfy `isSliceRoot`. first `%2` would be found as the main root, then `%1` would be skipped over because is is clonable (assumed to be moved into the dispatch but not). Finally, `%0` would be horizontally fused breaking the use-def chain.

```mlir
%0 = linalg.generic ...
%1 = tensor.extract %0[] ...
%2 = linalg.generic ...

...
uses of %1 and %2
```

Unlike when forming the slice to move into the dispatch, the horizontal fusion root is used outside of the dispatch. So to fix this case, we must keep track of uses between where the root is and where it will be moved to. This ensures that it doesnt get moved past any uses.


@MaheshRavishankar we talked last week about keeping track of 'moved' vs 'cloned' ops. And then only looking past 'moved' ops, but it seems this would reduce the fusion opportunities. For example, in the test case `interleaving`, we wouldn't be able to horizontally fuse `%2` and `%6` because the `tensor.empty` has 2 uses, forcing it to be cloned.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/FormScalarDispatches.cpp [hunk 2]
```diff
@@ -150,6 +152,24 @@ formDispatchRegionFromSlice(RewriterBase &rewriter, Operation *rootOp,
...
+static void
+insertAllOperationsUsedAbove(Operation *op,
+                             llvm::SetVector<Operation *> &operations) {
+  mlir::visitUsedValuesDefinedAbove(op->getRegions(), [&](OpOperand *operand) {
+    if (auto definingOp = operand->get().getDefiningOp()) {
+      operations.insert(definingOp);
+    }
+  });
+
+  for (Value val : op->getOperands()) {
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/FormScalarDispatches.cpp]: Could you move the insertion into the set out of this method and into the caller. I dont find it very easy to read when things get passed around by reference and updated. Makes the logic of reading the caller more convoluted cause you dont see the insertion happening in the caller code.

**Review by MaheshRavishankar — APPROVED** [review]
