### PR TITLE
Transform dialect fix to allow multiple calls to same custom dispatch

### LINKED ISSUE #17327: Transform dialect custom dispatches make util.func instead of flow.dispatch which seems to run into trouble for slightly complex case
In this [gist](https://gist.github.com/nirvedhmeshram/a1f5d52c32470b29adaab4239b5ebe43)
See the transform_output.mlir and pdl_output.mlir,
It appears the transform output runs into the error with expecting particular type of stream buffers
[Here](https://gist.github.com/nirvedhmeshram/d6dbfab6c2f7301447778fedd0f4c46b) is a full IR dump as well.

### PR DESCRIPTION
**Pull request by nirvedhmeshram**
Adds an inliner pass that fixes https://github.com/iree-org/iree/issues/17327
Adds a mlp_spec transform dialect script that just matches matmuls and tests it on the existing two matmul linalg payload IR.

### CODE REVIEW

File: compiler/src/iree/compiler/Preprocessing/Passes.cpp [hunk 1]
```diff
@@ -82,6 +82,8 @@ void buildPreprocessingPassPipeline(
         preprocessingOptions.preprocessingTransformSpecFilename;
     passManager.addPass(
         Preprocessing::createInterpreterPass(interpreterOptions));
+    // Custom dispatch formation creates util.func ops that need to be inlined.
+    passManager.addPass(mlir::createInlinerPass());
```
Comment (benvanik) [inline compiler/src/iree/compiler/Preprocessing/Passes.cpp]:
```suggestion
```
run this pass from your script instead - "custom dispatch formation" is just one thing the interpreter is used for and not something we want to reference/bake in here

(we should fix the bugs that require the inliner to be run, but for today the workaround is to run it yourself)

**Review by benvanik — DISMISSED** [review]

**Review by ScottTodd — APPROVED** [review]

**Comment by ScottTodd** [comment]
Oh, agreed with Ben. I'm also wondering as this samples/ subdir grows if it should graduate into something out of tree at some point (under https://github.com/iree-org/iree-experimental, for example). I worry about how much code is in some of these spec files.

**Comment by nirvedhmeshram** [comment]
> Oh, agreed with Ben. I'm also wondering as this samples/ subdir grows if it should graduate into something out of tree at some point (under https://github.com/iree-org/iree-experimental, for example). I worry about how much code is in some of these spec files.

Makes sense, can look at moving these there as a next step.
