### PR TITLE
[Im2col] Add input-filter permutation info to im2col metadata

### LINKED ISSUE #20473: [GPU] very poor numerics for certain conv layouts
### What happened?

I'm trying to decompose backwards convolutions into forward convolutions, and this sometimes results in unusual layouts. Here is a some simple `conv_1d_nhc_chf` IR which reproduces a significant numerical error:

```mlir
#map = affine_map<(d0, d1, d2, d3, d4) -> (d0, d1 + d4, d3)>
#map1 = affine_map<(d0, d1, d2, d3, d4) -> (d3, d4, d2)>
#map2 = affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2)>
module @module {
  util.func public @conv_1d_float32_forward_1x3x2_nhc_2x2x2_chf_nhf_1s_0p_1d_1g$async(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view, %arg2: !hal.fence, %arg3: !hal.fence) -> !hal.buffer_view attributes {inlining_policy = #util.inline.never, iree.abi.model = "coarse-fences", iree.abi.stub, preprocessing_pipeline = #util.preprocessing_pipeline<"iree-preprocessing-make-single-dispatch">} {
    %cst = arith.constant 0.000000e+00 : f32
    %0 = hal.tensor.import wait(%arg2) => %arg0 : !hal.buffer_view -> tensor<1x3x2xf32>
    %1 = hal.tensor.import wait(%arg2) => %arg1 : !hal.buffer_view -> tensor<2x2x2xf32>
    %2 = tensor.empty() : tensor<1x2x2xf32>
    %3 = linalg.fill ins(%cst : f32) outs(%2 : tensor<1x2x2xf32>) -> tensor<1x2x2xf32>
    %4 = linalg.generic {indexing_maps = [#map, #map1, #map2], iterator_types = ["parallel", "parallel", "parallel", "reduction", "reduction"]} ins(%0, %1 : tensor<1x3x2xf32>, tensor<2x2x2xf32>) outs(%3 : tensor<1x2x2xf32>) {
    ^bb0(%in: f32, %in_0: f32, %out: f32):
      %7 = arith.mulf %in, %in_0 : f32
      %8 = arith.addf %out, %7 : f32
      linalg.yield %8 : f32
    } -> tensor<1x2x2xf32>
    %5 = hal.tensor.barrier join(%4 : tensor<1x2x2xf32>) => %arg3 : !hal.fence
    %6 = hal.tensor.export %5 : tensor<1x2x2xf32> -> !hal.buffer_view
    util.return %6 : !hal.buffer_view
  }
  util.func public @conv_1d_float32_forward_1x3x2_nhc_2x2x2_chf_nhf_1s_0p_1d_1g(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub} {
    %0 = util.null : !hal.fence
    %c-1_i32 = arith.constant -1 : i32
    %c0 = arith.constant 0 : index
    %device_0 = hal.devices.get %c0 : !hal.device
    %fence = hal.fence.create device(%device_0 : !hal.device) flags("None") : !hal.fence
    %1 = util.call @conv_1d_float32_forward_1x3x2_nhc_2x2x2_chf_nhf_1s_0p_1d_1g$async(%arg0, %arg1, %0, %fence) : (!hal.buffer_view, !hal.buffer_view, !hal.fence, !hal.fence) -> !hal.buffer_view
    %status = hal.fence.await until([%fence]) timeout_millis(%c-1_i32) flags("None") : i32
    util.return %1 : !hal.buffer_view
  }
}
```

### Steps to reproduce your issue

Compile the above IR with

```
iree-compile --iree-hal-target-backends=rocm --iree-hip-target=gfx942 -o conv_repro.vmfb
```

Then run on some simple arguments:

```
iree-run-module --device=hip \
   --module="conv_repro.vmfb" \
   --input=1x3x2xf32=[[[0,1],[0,0],[0,0]]] \
   --input=2x2x2xf32=[[[1,2],[3,4]],[[5,6],[7,8]]]
```

The result of this run gives:

```
result[0]: hal.buffer_view
1x2x2xf32=[[3 4][0 0]]
```

But it should be `[[5 6][0 0]]` (you can check this by hand, or just compile and run this same IR for `llvm-cpu`).

### What component(s) does this issue relate to?

Compiler

### Version information

iree-base-compiler  3.4.0rc20250406
iree-base-runtime   3.4.0rc20250406

### Additional context

This issue is present for similar 2d convolution layouts. I suspect that something is going wrong during im2col, since:

```
// -----// IR Dump After ConvolutionToIGEMMPass (iree-codegen-convolution-to-igemm) //----- //
func.func @conv_1d_float32_forward_1x3x2_nhc_2x2x2_chf_nhf_1s_0p_1d_1g$async_dispatch_0_conv_2x2x2x2_f32() attributes {translation_info = #iree_codegen.translation_info<pipeline = LLVMGPUTileAndFuse workgroup_size = [64, 1, 1] subgroup_size = 64, {gpu_pipeline_options = #iree_gpu.pipeline_options<prefetch_shared_memory = true, no_reduce_shared_memory_bank_conflicts = false, use_igemm_convolution = true>}>} {
  %cst = arith.constant 0.000000e+00 : f32
  %c0 = arith.constant 0 : index
  %0 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%c0) flags("ReadOnly|Indirect") {iree_gpu.use_rocdl_buffer_instructions} : !flow.dispatch.tensor<readonly:tensor<3x2xf32>>
  %1 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(1) alignment(64) offset(%c0) flags("ReadOnly|Indirect") : !flow.dispatch.tensor<readonly:tensor<4x2xf32>>
  %2 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(2) alignment(64) offset(%c0) flags(Indirect) {iree_gpu.use_rocdl_buffer_instructions} : !flow.dispatch.tensor<writeonly:tensor<2x2xf32>>
  %3 = flow.dispatch.tensor.load %0, offsets = [0, 0], sizes = [3, 2], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<3x2xf32>> -> tensor<3x2xf32>
  %4 = tensor.empty() : tensor<2x2xf32>
  %5 = linalg.fill ins(%cst : f32) outs(%4 : tensor<2x2xf32>) -> tensor<2x2xf32>
  %6 = tensor.empty() : tensor<2x4xf32>
  %7 = iree_linalg_ext.im2col strides = [1] dilations = [1] kernel_size = [2] m_offset = [0] * [1] k_offset = [0] * [1] batch_pos = [] m_pos = [0] k_pos = [1] ins(%3 : tensor<3x2xf32>) outs(%6 : tensor<2x4xf32>) -> tensor<2x4xf32>
  %8 = flow.dispatch.tensor.load %1, offsets = [0, 0], sizes = [4, 2], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<4x2xf32>> -> tensor<4x2xf32>
  %9 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d2, d1)>, affine_map<(d0, d1, d2) -> (d0, d1)>], iterator_types = ["parallel", "parallel", "reduction"]} ins(%7, %8 : tensor<2x4xf32>, tensor<4x2xf32>) outs(%5 : tensor<2x2xf32>) attrs =  {lowering_config = #iree_gpu.lowering_config<{mma_kind = #iree_gpu.mma_layout<MFMA_F32_16x16x4_F32>, padding = [16, 16, 4], promote_operands = [0, 1, 2], reduction = [0, 0, 1], subgroup = [1, 1, 0], workgroup = [16, 16, 0]}>} {
  ^bb0(%in: f32, %in_0: f32, %out: f32):
    %10 = arith.mulf %in, %in_0 : f32
    %11 = arith.addf %10, %out : f32
    linalg.yield %11 : f32
  } -> tensor<2x2xf32>
  flow.dispatch.tensor.store %9, %2, offsets = [0, 0], sizes = [2, 2], strides = [1, 1] : tensor<2x2xf32> -> !flow.dispatch.tensor<writeonly:tensor<2x2xf32>>
  return
}
```

Indicates that the `ck` weight dims get flattened together (in that order), but I have no reason to suspect that the `im2col` for the input is also performing the necessary logic to transpose `Hkc` to `Hck` (`H`=output `h`) before flattening the last two dims. This would make sense with the numerical results shown above (since the index of the `1` in `x` is `n=0, h=0, c=1`, and this is getting multiplied by the `3` in `w` at `c=0,k=1,f=0` for the output value at `n=0, ho = 0, f=0`. However, `h != ho + k` for these indices, and this equation would hold if `k` and `c` indices were confused in `w`. This is corroborated by other shapes and example args.

### PR DESCRIPTION
**Pull request by yzhang93**
This PR extends the `im2col` operation to support a new attribute `input_filter_perm`, which encodes the permutation required to align the layout of input and filter reduction dimensions. This is useful when the logical layout of the filter (e.g., `CHW`) differs from that of the input (e.g., `HWC`). Then in im2col decomposition, using permutation metadata to handle layout mismatches and reorder index computations.

This fixes https://github.com/iree-org/iree/issues/20473.

### CODE REVIEW

**Review by nirvedhmeshram — APPROVED** [review]
LGTM

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/AggregatedOpInterfaceImpl.cpp [hunk 1]
```diff
@@ -777,6 +777,22 @@ FailureOr<SmallVector<Value>> Im2colOp::decomposeOperation(OpBuilder &b) {
     }
     kBasis.push_back(size);
   }
+
+  // Check if the reduction dimension has different layouts between input and
+  // filter, if so, transpose the order of (P, Q, C) according to
+  // `inputFilterPerm` encoded in im2col metadata.
+  auto isIdentityPermutation = [](ArrayRef<int64_t> perm) -> bool {
+    return llvm::equal(llvm::seq<int64_t>(0, perm.size()), perm);
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/AggregatedOpInterfaceImpl.cpp]: More out of curiosity, are there tradeoffs here between `llvm::seq` and `llvm::iota`?

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/AggregatedOpInterfaceImpl.cpp [hunk 2]
```diff
@@ -792,17 +808,22 @@ FailureOr<SmallVector<Value>> Im2colOp::decomposeOperation(OpBuilder &b) {
            /*hasOuterBound=*/true)
           .getResults();
   // Split the delinearized offsets into the window offsets (for M offsets)
-  // and the K offsets for the input tensor.
+  // and the K offsets for the input tensor based on the layout.
+  auto getIndex = [&inputFilterPerm](int64_t value) -> int64_t {
+    auto it = std::find(inputFilterPerm.begin(), inputFilterPerm.end(), value);
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/AggregatedOpInterfaceImpl.cpp]: `invertPermutation()` and then this is just an array lookup?

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp [hunk 3]
```diff
@@ -60,14 +60,67 @@ static SmallVector<int64_t> getBasisFromShape(ArrayRef<int64_t> shape) {
...
+// Collect all AffineDimExprs from an AffineExpr.
+static void collectDimExprs(ArrayRef<AffineExpr> exprs,
+                            DenseSet<AffineExpr> &out) {
+  for (auto &expr : exprs) {
+    if (auto dimExpr = dyn_cast<AffineDimExpr>(expr)) {
+      out.insert(dimExpr);
+    } else if (auto binOpExpr = dyn_cast<AffineBinaryOpExpr>(expr)) {
+      collectDimExprs({binOpExpr.getLHS(), binOpExpr.getRHS()}, out);
+    } else {
+      llvm::errs() << "Non-dimension expression found: " << expr << "\n";
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp]: Don't `llvm::errs()` like this. `emitError()` or `notifyMatchFailure()` on some relevant nearby object if this recover, or `assert()` away if it isn't. This could spam people's logs. LLVM_DEBUG(), maybe

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp [hunk 4]
```diff
@@ -60,14 +60,67 @@ static SmallVector<int64_t> getBasisFromShape(ArrayRef<int64_t> shape) {
...
+        filterSharedDims.push_back(dimExpr);
+      }
+    });
+  }
+  // Compute the permutation that maps inputSharedDims to filterSharedDims.
+  SmallVector<int64_t> inputFilterPerm;
+  for (AffineExpr filterExpr : filterSharedDims) {
+    auto it = llvm::find(inputSharedDims, filterExpr);
+    if (it == inputSharedDims.end()) {
+      llvm_unreachable(
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp]: `assert()` this instead - no need for an `_unreachable`

**Review by krzysz00 — COMMENTED** [review]
I've got style complaints

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td [hunk 5]
```diff
@@ -794,6 +794,14 @@ def IREELinalgExt_Im2colOp : IREELinalgExt_Op<"im2col",
...
     index into the flat `K` increases by 4. The strides in M from `m_strides`
     are orthogonal to the strides in `K` from `k_strides`.
+
+    The `input_filter_perm` attribute specifies the permutation required to align
+    the reduction dimensions of the input layout with the filter layout,
+    particularly for computing the K dimension of the im2col output. This is useful
+    when the logical layout of the filter (e.g., `CHW`) differs from that of the
+    input (e.g., `HWC`). For instance, an `input_filter_perm = [2, 0, 1]` indicates
+    the input needs to be transposed from `HWC` to `CHW` layout before extracting
+    patches into K.
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td]: Could you add to the docs of `input_filter_perm`, explaining what the identity permutation indicates? My understanding is something like:

When input_filter_perm is identity, the order of the K dimensions matches the order in which the corresponding m_pos and k_pos dimensions appear in the input. For example, `m_pos = [2, 4] k_pos = [0, 3] kernel_size = [F0, F1]` would result in a `K0xF0xK1xF1` ordering (F0 and F1 correspond to the m_pos, and K0 and K1 correspond to the k_pos).

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td [hunk 6]
```diff
@@ -811,7 +819,8 @@ def IREELinalgExt_Im2colOp : IREELinalgExt_Op<"im2col",
                        DenseI64ArrayAttr:$static_k_strides,
                        DenseI64ArrayAttr:$batch_pos,
                        DenseI64ArrayAttr:$m_pos,
-                       DenseI64ArrayAttr:$k_pos);
+                       DenseI64ArrayAttr:$k_pos,
+                       DenseI64ArrayAttr:$input_filter_perm);
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td]: Maybe to keep the naming consistent with the M/N/K/Batch terminology, a more clear name would be `input_k_perm`? WDYT?

The way I named things originally tried to tie it more to the matmul iteration space than the convolution iteration space.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp (hunk 3 above)
Comment (Max191) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp]: +1 on causing an actual failure here. If something unexpected happens in the pattern matching, then the best option is to return a match failure, and abort the pattern. The llvm::errs() is good too, but please wrap it in `LLVM_DEBUG()`.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir [hunk 7]
```diff
@@ -359,3 +367,85 @@ util.func public @conv_nhwc_hwfc_nobatch(%arg0: tensor<16x16x4xf32>, %arg1: tens
 // CHECK-SAME:   iterator_types = ["parallel", "parallel", "parallel", "reduction", "reduction"]
 // CHECK-SAME:   ins(%[[IM2COL]], %[[COLLAPSED]] : tensor<14x14x9x4xf32>, tensor<9x16x4xf32>)
 // CHECK:      util.return %[[MATMUL]] : tensor<14x14x16xf32>
+
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir:370]: Since these new tests are mostly just testing the input_filter_perm, I think we can shrink the CHECK portion. Maybe just check that the im2col op has the correct input_filter_perm for the 2 new tests? Having lots of long tests means more maintenance cost when making small changes.

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/AggregatedOpInterfaceImpl.cpp [hunk 8]
```diff
@@ -777,6 +777,22 @@ FailureOr<SmallVector<Value>> Im2colOp::decomposeOperation(OpBuilder &b) {
...
+  };
+
+  ArrayRef<int64_t> inputFilterPerm = getInputFilterPerm();
+  if (!isIdentityPermutation(inputFilterPerm)) {
+    SmallVector<OpFoldResult> origKBasis = kBasis;
+    for (auto [newIdx, transIdx] : llvm::enumerate(inputFilterPerm)) {
+      kBasis[newIdx] = origKBasis[transIdx];
+    }
+  }
+
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/AggregatedOpInterfaceImpl.cpp]: nit: I think this can be simplified using `applyPermutationToVector`:

https://github.com/llvm/llvm-project/blob/dbeb7c1bbbc90f3d556b9d010d7899311cfc62d6/mlir/include/mlir/Dialect/Utils/IndexingUtils.h#L220-L229

```suggestion
  // Transpose the order of (P, Q, C) according to `inputFilterPerm` encoded in im2col metadata.
  applyPermutationToVector(kBasis, getInputFilterPerm());
```

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/AggregatedOpInterfaceImpl.cpp [hunk 9]
```diff
@@ -792,17 +808,22 @@ FailureOr<SmallVector<Value>> Im2colOp::decomposeOperation(OpBuilder &b) {
...
   for (int i = 0; i < getInputRank(); ++i) {
     if (batchPosSet.contains(i))
       continue;
     if (mPosSet.contains(i)) {
-      windowOffset.push_back(delinKOffset[delinKIdx++]);
+      windowOffset.push_back(delinKOffset[getIndex(delinKIdx++)]);
       continue;
     }
-    inputKOffset.push_back(delinKOffset[delinKIdx++]);
+    inputKOffset.push_back(delinKOffset[getIndex(delinKIdx++)]);
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/AggregatedOpInterfaceImpl.cpp]: nit: I think getIndex can be replaced with the inverse permutation of inputFilterPerm:

https://github.com/llvm/llvm-project/blob/dbeb7c1bbbc90f3d556b9d010d7899311cfc62d6/mlir/include/mlir/Dialect/Utils/IndexingUtils.h#L231-L232

```cpp
    SmallVector<int64_t> invInputFilterPerm = invertPermutationVector(inputFilterPerm);
    inputKOffset.push_back(delinKOffset[invInputFilterPerm[delinKIdx++]]);
```

**Review by Max191 — COMMENTED** [review]
Overall looks good! Just some nits and some comments about the naming.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp (hunk 3 above)
Comment (yzhang93) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp]: Thanks for your suggestions! I've changed the codes to wrap this under the debug mode.

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/AggregatedOpInterfaceImpl.cpp (hunk 1 above)
Comment (yzhang93) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/AggregatedOpInterfaceImpl.cpp]: This part of codes have been removed in the revision. But regarding to your question, I think both could work. Do you have any idea of which could be a more efficient way? So I can make a correct choice the next time it's needed.

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td (hunk 6 above)
Comment (yzhang93) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td]: Agreed. Using `input_k_perm` now.

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir (hunk 7 above)
Comment (yzhang93) [reply compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/conv_to_im2col.mlir:370]: Done.

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/AggregatedOpInterfaceImpl.cpp (hunk 8 above)
Comment (yzhang93) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/AggregatedOpInterfaceImpl.cpp]: Thanks for sharing this useful utility function. This is a great reduction of codes!

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td (hunk 5 above)
Comment (yzhang93) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td]: I've added the doc based on my understanding. Basically, my point is the index transformation during decomposition should match the input order with the filter order, so that's where the transpose is happening. Please check again and let me know if it is clear.

**Comment by yzhang93** [comment]
@Max191 would you like to take another look at this?

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp [hunk 10]
```diff
@@ -69,15 +71,16 @@ static void collectDimExprs(ArrayRef<AffineExpr> exprs,
...
   }
 }
 
-// Computes `inputFilterPerm` that maps the input spatial and channel order to
+// Computes `inputKPerm` that maps the input spatial and channel order to
 // filter's.
-static SmallVector<int64_t> computeInputFilterPerm(AffineMap inputMap,
-                                                   AffineMap filterMap) {
+static SmallVector<int64_t> computeinputKPerm(AffineMap inputMap,
+                                              AffineMap filterMap) {
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp]:
```suggestion
static SmallVector<int64_t> computeInputKPerm(AffineMap inputMap,
                                              AffineMap filterMap) {
```

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp [hunk 11]
```diff
@@ -60,14 +62,66 @@ static SmallVector<int64_t> getBasisFromShape(ArrayRef<int64_t> shape) {
...
+      collectDimExprs({binOpExpr.getLHS(), binOpExpr.getRHS()}, out);
+    } else {
+      LLVM_DEBUG(llvm::dbgs()
+                 << "Non-dimension expression found: " << expr << "\n");
+    }
+  }
+}
+
+// Computes `inputKPerm` that maps the input spatial and channel order to
+// filter's.
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp]:
```suggestion
// Computes `inputKPerm` that maps the input spatial and channel dimension
// order to filter's.
```

File: compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp [hunk 12]
```diff
@@ -211,6 +265,9 @@ class ConvertConvGeneric final
 
     SmallVector<OpFoldResult> kOffset(kBasis.size(), rewriter.getIndexAttr(0));
     SmallVector<OpFoldResult> mOffset(mBasis.size(), rewriter.getIndexAttr(0));
+
+    SmallVector<int64_t> inputKPerm = computeinputKPerm(inputMap, filterMap);
```
Comment (Max191) [inline compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/ConvertConvToIm2ColOp.cpp]:
```suggestion
    SmallVector<int64_t> inputKPerm = computeInputKPerm(inputMap, filterMap);
```

**Review by Max191 — APPROVED** [review]
Looks good % nit, thanks!
