### PR TITLE
Freeze all statuses emitted by calls into dynamic modules 

### LINKED ISSUE #16046: Dynamic VM Modules crash with status source file locations
### What happened?

When `IREE_STATUS_FEATURE_SOURCE_LOCATION` is set when using dynamic VM modules, when trying to print out failure messages iree-run-module will crash when trying to format the message for printing here: https://github.com/openxla/iree/blob/6ac9b7e906ccd2cd878bae868dd37a19a272bc28/runtime/src/iree/base/status.c#L1077

Asan + printf debugging shows that the source file string is no longer a valid address.
```
==396383==ERROR: AddressSanitizer: SEGV on unknown address 0x7f330fcbc35b (pc 0x560ad199ccb0 bp 0x7ffcc08d7630 sp 0x7ffcc08d6da8 T0)
==396383==The signal is caused by a READ memory access.
    #0 0x560ad199ccb0 in __sanitizer::internal_strlen(char const*) crtstuff.c
    #1 0x560ad19249ab in printf_common(void*, char const*, __va_list_tag*) crtstuff.c
    #2 0x560ad1924ce8 in vsnprintf (/home/quinn/iree-asan-build/tools/iree-run-module+0x184ce8) (BuildId: c63a95cf6694b781)
    #3 0x560ad1926400 in snprintf (/home/quinn/iree-asan-build/tools/iree-run-module+0x186400) (BuildId: c63a95cf6694b781)
    #4 0x560ad19c64c4 in iree_status_format /home/quinn/SHARK-Runtime/runtime/src/iree/base/status.c:1117:9
    #5 0x560ad19c6a12 in iree_status_to_string /home/quinn/SHARK-Runtime/runtime/src/iree/base/status.c:1209:7
    #6 0x560ad19c55e1 in iree_status_fprint /home/quinn/SHARK-Runtime/runtime/src/iree/base/status.c:1242:7
    #7 0x560ad19c33ae in main /home/quinn/SHARK-Runtime/tools/iree-run-module-main.c:55:5
    #8 0x7f3312229d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #9 0x7f3312229e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #10 0x560ad1902e84 in _start (/home/quinn/iree-asan-build/tools/iree-run-module+0x162e84) (BuildId: c63a95cf6694b781)
```

Guessing about what's happening, the dynamic module gets unloaded before this point, which in turn might be deallocating the file path string.

### Steps to reproduce your issue

This diff will reproduce the crash when running the test in `samples/custom_module/dynamic/test/example.mlir`.
```
diff --git a/samples/custom_module/dynamic/module.cc b/samples/custom_module/dynamic/module.cc
index ac7687e9b6..2bc5d15822 100644
--- a/samples/custom_module/dynamic/module.cc
+++ b/samples/custom_module/dynamic/module.cc
@@ -65,7 +65,8 @@ static iree_status_t iree_custom_string_create(
   string->value.size = value.size;
   memcpy((void*)string->value.data, value.data, string->value.size);
   *out_string = string;
-  return iree_ok_status();
+  return iree_make_status(IREE_STATUS_UNKNOWN, "forced failure");
+  //return iree_ok_status();
 }
 
 static void iree_custom_string_destroy(void* ptr) {
```
```
EXEC @main
Segmentation fault (core dumped)
```

### What component(s) does this issue relate to?

Runtime

### Version information

Top of main.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qedawkins**
When unloading a dynamic module we might inadvertently destroy any
status annotations it added, causing pitfalls/segfaults around status
usage. When allocating the formatted string we already do a copy that
changes ownership of the status annotation, so this does the same for
file paths.

I'm not sure this is the way we want to do this, we could instead force
the clone to happen only for dynamic modules as the surprise deallocation of
source file strings seems unique to dynamically loaded and unloaded things.

Fixes https://github.com/openxla/iree/issues/16046

Depends on https://github.com/openxla/iree/pull/16065

### CODE REVIEW

**Comment by benvanik** [comment]
(still waking up)

yeah this is something we want to avoid as we don't want to make 100% of all status emission perform this duplication when nearly 0% require it. we try not to use errors as control flow but it does happen and putting an extra malloc/memcpy there is rough.

we could make this an iree/base/config.h setting and then have dynamic modules set it - that way they get the copy but the hosting binary (where 99% of statuses come from) doesn't. a user could still opt to compile the whole runtime with the setting (for some reason) but wouldn't be required to do so.

once my coffee kicks in I'll take a look at the code - if we can make it easy to #ifdef then that may just be a few line change to preserve the old behavior while opting into the new.

**Comment by qedawkins** [comment]
> (still waking up)
> 
> yeah this is something we want to avoid as we don't want to make 100% of all status emission perform this duplication when nearly 0% require it. we try not to use errors as control flow but it does happen and putting an extra malloc/memcpy there is rough.
> 
> we could make this an iree/base/config.h setting and then have dynamic modules set it - that way they get the copy but the hosting binary (where 99% of statuses come from) doesn't. a user could still opt to compile the whole runtime with the setting (for some reason) but wouldn't be required to do so.
> 
> once my coffee kicks in I'll take a look at the code - if we can make it easy to #ifdef then that may just be a few line change to preserve the old behavior while opting into the new.

For sure, I was hoping there was a better solution here. I'm not sure about `iree/base/config.h` as this clone needs to happen in the hosting binary. The dynamic module has no (direct) control over when it is going to be uninitialized and so the hosting application needs to be able to do this clone to preserve any status returned by the dynamic module. Maybe the better solution here is to just add an `iree_status_deep_clone` (or change only `iree_status_clone`) that also does this copy.

**Comment by benvanik** [comment]
status.c should be statically linked into the dynamic modules but I guess changing the config would be tricky as we generally build with the same cmake config for both (thus the same .a).

having a version of iree_status_allocate that copies and that is selected in the header on some config IREE_STATUS_ALWAYS_COPY_METADATA (or whatever) would get around that so any iree_status_allocate made from dynamic modules calls the iree_status_allocate_copy (or whatever) instead of the non-copying iree_status_allocate.

I'm a bit confused here why the clone in run_module.c is needed if you are copying the strings where they are emitted? if we're going to be cloning there then we don't need to copy the strings when we emit the errors, but I don't think that really solves the problem - it'd be better if status just worked without needing the clone (as python and other non-iree-run-module tools don't do that clone and would need the same workaround).

**Comment by qedawkins** [comment]
> having a version of iree_status_allocate that copies and that is selected in the header on some config IREE_STATUS_ALWAYS_COPY_METADATA (or whatever) would get around that so any iree_status_allocate made from dynamic modules calls the iree_status_allocate_copy (or whatever) instead of the non-copying iree_status_allocate.

This makes sense to me, but I'm still a little fuzzy on where this allocation needs to happen. I can try this and see what happens.

> I'm a bit confused here why the clone in run_module.c is needed if you are copying the strings where they are emitted? if we're going to be cloning there then we don't need to copy the strings when we emit the errors, but I don't think that really solves the problem - it'd be better if status just worked without needing the clone (as python and other non-iree-run-module tools don't do that clone and would need the same workaround).

I couldn't get it to work without the clone but I can give it another try. There might be some other places that need similar handling w/ an `IREE_STATUS_ALWAYS_COPY_METADATA` or something.

**Comment by benvanik** [comment]
if the contract we want is that a status can be emitted containing pointers to library .text and immediately afterward while the status is still live the library can be unloaded then we must copy at the time the status is emitted. I think that's what we want - less footguns than requiring a clone at the right place - with layering a particular layer may not know if another part of the codebase loaded/unloaded a dynamic module at any given time.

**Comment by qedawkins** [comment]
> if the contract we want is that a status can be emitted containing pointers to library .text and immediately afterward while the status is still live the library can be unloaded then we must copy at the time the status is emitted. I think that's what we want - less footguns than requiring a clone at the right place - with layering a particular layer may not know if another part of the codebase loaded/unloaded a dynamic module at any given time.

Makes sense, and IIUC dynamic modules aren't the recommended flow for absolute maximum performance anyway. I'll try to make that work then.

File: runtime/src/iree/base/status.c [hunk 1]
```diff
@@ -1150,6 +1139,144 @@ IREE_API_EXPORT bool iree_status_format(iree_status_t status,
...
+
+IREE_API_EXPORT IREE_MUST_USE_RESULT iree_status_t
+iree_status_freeze(iree_status_t status) {
+#if IREE_STATUS_FEATURES == 0
+  // Statuses are just codes; nothing to do.
+  return status;
+#else
+  iree_status_code_t code = iree_status_code(status);
+  if (code == IREE_STATUS_OK) {
+    iree_status_free(status);
```
Comment (benvanik) [inline runtime/src/iree/base/status.c]: no need to free if ok (keeps this common path in IREE_RETURN_IF_ERROR cheap)
```suggestion
```

File: runtime/src/iree/base/status.c [hunk 2]
```diff
@@ -1150,6 +1139,144 @@ IREE_API_EXPORT bool iree_status_format(iree_status_t status,
...
+  }
+
+#if (IREE_STATUS_FEATURES & IREE_STATUS_FEATURE_SOURCE_LOCATION) != 0
+  if (file) {
+    new_storage->file = storage->file;
+    char* storage_file = (char*)new_storage + sizeof(iree_status_storage_t);
+    // Copy the file into the storage allocated for it.
+    memcpy(storage_file, file, file_storage_size);
+    new_storage->file = (const char*)storage_file;
+    new_storage->message.data += file_storage_size;
```
Comment (benvanik) [inline runtime/src/iree/base/status.c]: it'd be good to combine the offsetting together up above in one block - only setting ->message.data once, ->file once, etc - right now it's set a few different times (message_data gets offset, then it's calculated again in new_storage->message.data, then it's reset here, etc)

to make it simpler you can also put the file after the message as the file is optional and the message isn't - then you always put the message at the same place (after storage) and tack on the file only if the feature is enabled and the file is non-NULL (would be less #ifs) - no need to reset the message ptr

File: runtime/src/iree/base/status.c [hunk 3]
```diff
@@ -1150,6 +1139,144 @@ IREE_API_EXPORT bool iree_status_format(iree_status_t status,
...
+  }
+  new_storage->line = line;
+#endif  // has IREE_STATUS_FEATURE_SOURCE_LOCATION
+
+  iree_status_free(status);
+  return new_status;
+#endif
```
Comment (benvanik) [inline runtime/src/iree/base/status.c]:
```suggestion
#endif  // has any IREE_STATUS_FEATURES
```

for readability it's also sometimes nicer when the function being #ifdefed out is beyond a page to instead just define the function twice - one in the #if as a no-op and the other in the #else - then no need for a reader to track what parts of a function are enabled and instead can easily see the function is just a return _or_ actual work

**Review by benvanik — CHANGES_REQUESTED** [review]
minor cleanup and otherwise LGTM! nice fix!

**Review by benvanik — APPROVED** [review]

File: samples/custom_module/dynamic/test/example.mlir
Comment (ScottTodd) [inline samples/custom_module/dynamic/test/example.mlir:1]: Nice new test case! Thanks.

**Review by ScottTodd — APPROVED** [review]
(Was waiting for Ben's comments to be addressed) LGTM
