### PR TITLE
[Codegen][LLVMGPU] Avoid long compilation times of warp reduction pipeline

### LINKED ISSUE #19263: Llama 3.1 8B fp16 TP8 sharded fails to compile for CPU and GPU
### What happened?

When I try to compile the sharded Llama 3.1 8b fp16 [IR](https://gist.github.com/aviator19941/bab5886f53f2fd0b3b8458519148542c) for CPU or GPU:

I get this error for CPU:
https://gist.github.com/aviator19941/82bceb2624571d446da0964440790fde

and this error for GPU:
https://gist.github.com/aviator19941/89761b3bbb6ace5a6945de667e6d1e39

I tried to use these flags that were suggested to be used when compiling Llama as well:
`
--iree-dispatch-creation-enable-aggressive-fusion=true --iree-global-opt-propagate-transposes=true --iree-opt-aggressively-propagate-transposes=true --iree-opt-data-tiling=false --iree-preprocessing-pass-pipeline='builtin.module(util.func(iree-preprocessing-generalize-linalg-matmul-experimental))' --iree-hal-indirect-command-buffers=true --iree-stream-resource-memory-model=discrete --iree-hip-legacy-sync=false --iree-hal-memoization=true --iree-opt-strip-assertions
`

### Steps to reproduce your issue

1. wget the IR: https://gist.github.com/aviator19941/bab5886f53f2fd0b3b8458519148542c
2. Try to compile for CPU:
`
../iree-build-no-trace/tools/iree-compile 8b_f16_tp8_decomposed.mlir -o=8b_f16_tp8_decomposed_cpu.vmfb --iree-hal-target-device=llvm-cpu[0] --iree-hal-target-device=llvm-cpu[1] --iree-hal-target-device=llvm-cpu[2] --iree-hal-target-device=llvm-cpu[3] --iree-hal-target-device=llvm-cpu[4] --iree-hal-target-device=llvm-cpu[5] --iree-hal-target-device=llvm-cpu[6] --iree-hal-target-device=llvm-cpu[7]
`
3. CPU error: https://gist.github.com/aviator19941/82bceb2624571d446da0964440790fde
4. Try to compile for GPU:
`
../iree-build-no-trace/tools/iree-compile 8b_f16_tp8_decomposed.mlir --iree-hip-target=gfx942 -o=8b_f16_tp8_decomposed.vmfb --iree-hal-target-device=hip[0] --iree-hal-target-device=hip[1] --iree-hal-target-device=hip[2] --iree-hal-target-device=hip[3] --iree-hal-target-device=hip[4] --iree-hal-target-device=hip[5] --iree-hal-target-device=hip[6] --iree-hal-target-device=hip[7]
`
5. GPU error: https://gist.github.com/aviator19941/89761b3bbb6ace5a6945de667e6d1e39

### What component(s) does this issue relate to?

_No response_

### Version information

iree-base-compiler 3.1.0rc20241121

### Additional context

_No response_

### LINKED ISSUE #19377: [Codegen] Llama 3.1 8B fp16 TP8 compile time regression
### What happened?

There is a secondary problem with compiling the IR in https://github.com/iree-org/iree/issues/19263. If the IR gets past the failure in that issue, it will get stuck on a dispatch that takes a very long time to compile. There is an excessive amount of ops generated during `ConvertToROCDLPass` [IR dump before the pass](https://gist.github.com/IanWood1/5462349ce6b20bcf4f3536764cfc7954).

### Steps to reproduce your issue

1. Download https://gist.github.com/IanWood1/d3d6255ce4e1f8a8dbb2ff99cf7133da
2. `iree-compile repro.mlir --compile-from=executable-sources`

### What component(s) does this issue relate to?

_No response_

### Version information

9f8aad85b469b224bb9594d002f35bd8febebbf9

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
The warp reduction pipeline tile size logic isnt very robust for dynamic dimensions. For now use a fallback in case where dynamic dimensions exist to allow for reasonable compilation times.

Fixes #19377

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 1]
```diff
@@ -1617,9 +1618,9 @@ setWarpReductionConfig(IREE::GPU::TargetAttr target,
   size_t numLoops = partitionedLoops.empty() ? 0 : partitionedLoops.back() + 1;
   SmallVector<int64_t> workgroupTileSizes(numLoops, 1);
 
-  // Without any bounds on dynamic reduction dims, we need specialization to
+  // Without any bounds on dynamic dims, we need specialization to
   // get peak performance. For now, just use the warp size.
-  if (numDynamicReductionDims) {
+  if (numDynamicDims) {
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp]:
```suggestion
  if (numDynamicDims > 0) {
```

**Review by kuhar — APPROVED** [review]
