### PR TITLE
Ensure that compiler output is sufficiently aligned.

### LINKED ISSUE #14926: ireeCompilerOutputMapMemory can return insufficiently aligned memory
On Linux with glibc>=2.27, we use memfd to allocate/map memory for loaded binaries. This always produces an alignment that is directly usable to load executables.

However, on others, this can fall back to malloc and produce insufficiently aligned memory. In the Python API, alignment is checked and raises an exception if violated.

The PJRT plugin also uses this mechanism but with raw C APIs that are not enforcing alignment checks. This will result in UB on ancient linux builds (which include manylinux2014) and other platforms.

We should strengthen this API to always align.

### PR DESCRIPTION
**Pull request by stellaraccident**
On modern Linux, memfd_create is used, which is always page aligned. However on others (Windows/MacOS), we fall back to a malloc-based implementation, which is not.

Adds aligned allocation fallback so we always meet this invariant.

Fixes #14926

### CODE REVIEW

File: compiler/src/iree/compiler/API/Internal/CompilerDriver.cpp [hunk 1]
```diff
@@ -90,6 +89,74 @@
...
+// While memfd_create aligns to a page, we align these to 64 bytes,
+// which matches runtime requirements.
+const size_t kOutputBufferAlignment = 64;
+
+template <typename T>
+struct rt_aligned_allocator {
+  using value_type = T;
+  rt_aligned_allocator() noexcept {}
+  template <class U>
+  rt_aligned_allocator(const rt_aligned_allocator<U> &) noexcept {}
```
Comment (kuhar) [inline compiler/src/iree/compiler/API/Internal/CompilerDriver.cpp:103]: Do we expect IREE to be ever built with exceptions enabled and benefit from `noexcept`?

File: compiler/src/iree/compiler/API/Internal/CompilerDriver.cpp [hunk 2]
```diff
@@ -90,6 +89,74 @@
 namespace mlir::iree_compiler::embed {
 namespace {
 
+// If note using memfd_create, then we need to align output buffers
```
Comment (kuhar) [inline compiler/src/iree/compiler/API/Internal/CompilerDriver.cpp]: nit: did you mean 'not'?
```suggestion
// If not using memfd_create, then we need to align output buffers
```

File: compiler/src/iree/compiler/API/Internal/CompilerDriver.cpp (hunk 1 above)
Comment (stellaraccident) [reply compiler/src/iree/compiler/API/Internal/CompilerDriver.cpp:103]: No. But allocators are finicky and this is the exact standard compliant way to define one.

**Review by kuhar — APPROVED** [review]
LGTM

File: compiler/src/iree/compiler/API/Internal/CompilerDriver.cpp [hunk 3]
```diff
@@ -516,6 +586,8 @@ Error *Output::openMembuffer() {
   // Fallback to an std::string based accumulator if no platform support
   // for memfiles.
   type = Type::Membuffer;
+  // Avoid some initial memcpys with a size appropriate for program output.
+  outputString.reserve(16384);
```
Comment (antiagainst) [inline compiler/src/iree/compiler/API/Internal/CompilerDriver.cpp:590]: Nit: might want to define a constant at the beginning of the file for this magic number?

Comment (stellaraccident) [reply compiler/src/iree/compiler/API/Internal/CompilerDriver.cpp:590]: I'll do so in a follow-up. There's another place in the compiler I need this, so it will be moving to a utility header soon.

**Comment by ScottTodd** [comment]
Something in this PR appears to have broken `iree-run-mlir` tests on macOS: https://github.com/openxla/iree/actions/runs/6516064860/job/17699184208

```

RUN: at line 3: iree-run-mlir --Xcompiler,iree-input-type=stablehlo --Xcompiler,iree-hal-target-backends=vmvx /Users/cheyuw/actions-runner/_work/iree/iree/tests/e2e/models/mnist_fake_weights.mlir --input=1x28x28x1xf32 | FileCheck /Users/cheyuw/actions-runner/_work/iree/iree/tests/e2e/models/mnist_fake_weights.mlir
+ iree-run-mlir --Xcompiler,iree-input-type=stablehlo --Xcompiler,iree-hal-target-backends=vmvx /Users/cheyuw/actions-runner/_work/iree/iree/tests/e2e/models/mnist_fake_weights.mlir --input=1x28x28x1xf32
+ FileCheck /Users/cheyuw/actions-runner/_work/iree/iree/tests/e2e/models/mnist_fake_weights.mlir
Please report issues to https://github.com/openxla/iree/issues and include the crash backtrace.
Stack dump:
0.	Program arguments: iree-run-mlir --iree-input-type=stablehlo --iree-hal-target-backends=vmvx
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libIREECompiler.dylib    0x00000001270d6248 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  libIREECompiler.dylib    0x00000001270d475c llvm::sys::RunSignalHandlers() + 112
2  libIREECompiler.dylib    0x00000001270d6900 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000018ad76a24 _sigtramp + 56
4  libsystem_platform.dylib 0xffff800126fe5794 _sigtramp + [184](https://github.com/openxla/iree/actions/runs/6516064860/job/17699184208#step:7:185)46603334546025896
5  iree-run-mlir            0x0000000104abe7d8 main + 3444
6  dyld                     0x000000018a9eff28 start + 2236
FileCheck error: '<stdin>' is empty.
FileCheck command line:  FileCheck /Users/cheyuw/actions-runner/_work/iree/iree/tests/e2e/models/mnist_fake_weights.mlir

...

The following tests FAILED:
	 58 - iree/tests/e2e/models/collatz.mlir.test (Failed)
	 59 - iree/tests/e2e/models/edge_detection.mlir.test (Failed)
	 60 - iree/tests/e2e/models/fragment_000.mlir.test (Failed)
	 61 - iree/tests/e2e/models/fullyconnected.mlir.test (Failed)
	 62 - iree/tests/e2e/models/mnist_fake_weights.mlir.test (Failed)
	 63 - iree/tests/e2e/models/unidirectional_lstm.mlir.test (Failed)
	 69 - iree/tests/e2e/regression/fill_i64.mlir.test (Failed)
	 70 - iree/tests/e2e/regression/force_single_dispatch.mlir.test (Failed)
	 71 - iree/tests/e2e/regression/globals.mlir.test (Failed)
	 73 - iree/tests/e2e/regression/scalar.mlir.test (Failed)
	 74 - iree/tests/e2e/regression/trace_dispatch_tensors.mlir.test (Failed)
	 75 - iree/tests/e2e/regression/unused_args.mlir.test (Failed)
	321 - iree/tests/e2e/stablehlo_ops/check_metal-spirv_metal_log.mlir (SEGFAULT)
	351 - iree/tests/e2e/tensor_ops/tensor_cast.mlir.test (Failed)
	540 - iree/tools/test/iree-run-mlir.mlir.test (Failed)
	545 - iree/tools/test/multiple_args.mlir.test (Failed)
	548 - iree/tools/test/repeated_return.mlir.test (Failed)
	549 - iree/tools/test/scalars.mlir.test (Failed)
	559 - iree/compiler/API/test/api-test-binary (SEGFAULT)
	1152 - iree/compiler/bindings/python/test/api/api_test (SEGFAULT)
```

**Comment by stellaraccident** [comment]
Thanks. I'll need to figure out what is going on and fix forward. This PR did have the potential to impact Windows and MacOS and these cross platform things are hard to get completely right.

**Comment by stellaraccident** [comment]
@bjacob says he is sending a patch for this.

**Comment by bjacob** [comment]
https://github.com/openxla/iree/pull/15199
