### PR TITLE
Only fuse gather-like producer for query operand of attention ops.

### LINKED ISSUE #19822: Flux Dev transformer RoPE IREE custom kernel bad performance
### What happened?

In this [PR](https://github.com/nod-ai/shark-ai/pull/871) I switched the Flux transformer to use the custom kernel for rotary embeddings and got a significant drop in performance.
The runtime increased from 552 ms to 6131 ms.

I have not investigated yet what is the cause.

### Steps to reproduce your issue

Refer to #19751 for more detailed instruction on how to run the benchmark.
Download [tracy-profile.zip](https://github.com/user-attachments/files/18561305/tracy-profile.zip) to get modified MLIR that uses the custom kernel RoPE. There is also a Tracy capture inside of a benchmark with 2 iterations.

### What component(s) does this issue relate to?

Compiler

### Version information

ebb961562ceca34976bac91ec5cbd42b2b2d4214

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
Fixes #19822

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
@Groverkss  do you think that we should restrict the fusion of gather-like operations only along query dimension, or do we just do this all the time. I was going to try to land this, but based on what we think we need to do for K and V (especially for decode), we probably want to fuse all gathers in right?

**Comment by MaheshRavishankar** [comment]
cc @sogartar

**Comment by sogartar** [comment]
@MaheshRavishankar is this ready to try it out? Should we try it on the actual Flux transformer before merging?

cc @KyleHerndon, @PhaneeshB

File: compiler/src/iree/compiler/DispatchCreation/CollapseDimensions.cpp [hunk 1]
```diff
@@ -1010,10 +1011,17 @@ void CollapseDimensionsPass::runOnOperation() {
...
 
   SmallVector<IREE::Flow::DispatchRegionOp> modifiedDispatchOps;
   funcOp->walk([&](IREE::Flow::DispatchRegionOp dispatchOp) {
     if (collapseDimensionsForDispatch(rewriter, dispatchOp, maxIterations)) {
+      // Remove duplicated reshapes
+      // FIX: workaround for `optimizeClosureLikeOp` breaking when a
+      // `flow.dispatch.workgroup` op has 2 of the same operands but one is
+      // readonly and the other is readwrite.
+      mlir::eliminateCommonSubExpressions(rewriter, domInfo, dispatchOp,
+                                          /*changed=*/nullptr);
```
Comment (IanWood1) [inline compiler/src/iree/compiler/DispatchCreation/CollapseDimensions.cpp]: there is a `flow.dispatch.workgroup` op that has uses the same value twice but once as `read` and the second is `readwrite`. This means that the bb args have different types and a verification error ocurrs after `optimizeClosureLikeOp` tries to replace the `readwrite` arg with the `read` arg.

reproducer (need to remove mlir::eliminateCommonSubExpressions) https://gist.github.com/IanWood1/ce8bb2e1f649ea431c86222bcab9dc50

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/DispatchCreation/CollapseDimensions.cpp]: I trid your example, and it passes.... Was trying to look deeper into the error.

Comment (IanWood1) [reply compiler/src/iree/compiler/DispatchCreation/CollapseDimensions.cpp]: Here's a better example https://gist.github.com/IanWood1/ad9953e5a4a485fafa2aa8ae69e366d9 with just `iree-opt -canonicalize`

Comment (IanWood1) [reply compiler/src/iree/compiler/DispatchCreation/CollapseDimensions.cpp]: The error goes away if we clone the outs operand. It seems unrelated to this PR, I can create a separate issue

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/DispatchCreation/CollapseDimensions.cpp]: Ok, that was indeed my mistake... I think I should have cloned the outs for attention ops, then the flow tracker is able to figure out the tied operands.

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/DispatchCreation/CollapseDimensions.cpp]: Do we drop this now? I dont think it is necessarily bad to do this, but it might be unnecessary.

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/DispatchCreation/CollapseDimensions.cpp]: Ah, I see you already did that. Cool!

**Comment by MaheshRavishankar** [comment]
@hanhanW can you review this please

**Review by benvanik — APPROVED** [review]
