### PR TITLE
Properly use TrackingListener in transforms that do not consume their operands

### LINKED ISSUE #12759: src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir flake segault
Ran into this flake on one bazel run in a PR chain. Logging for posterity. I have no further information.

```
FAIL: IREE :: src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir (1 of 1)
******************** TEST 'IREE :: src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir' FAILED ********************
Script:
--
: 'RUN: at line 1';   iree-opt /dev/shm/bazel-sandbox.55f9fb942a89558c0ebc0aedd0d9a7544e74d0ab744e8907da495b34261debfd/linux-sandbox/18069/execroot/iree_core/bazel-out/k8-opt/bin/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir.test.runfiles/iree_core/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir  --pass-pipeline="builtin.module(hal.executable(hal.executable.variant(iree-llvmgpu-lower-executable-target)))"      --iree-codegen-llvmgpu-enable-transform-dialect-jit=false      --iree-codegen-llvmgpu-use-transform-dialect=/dev/shm/bazel-sandbox.55f9fb942a89558c0ebc0aedd0d9a7544e74d0ab744e8907da495b34261debfd/linux-sandbox/18069/execroot/iree_core/bazel-out/k8-opt/bin/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir.test.runfiles/iree_core/compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_bufferize_spec.mlir |  FileCheck /dev/shm/bazel-sandbox.55f9fb942a89558c0ebc0aedd0d9a7544e74d0ab744e8907da495b34261debfd/linux-sandbox/18069/execroot/iree_core/bazel-out/k8-opt/bin/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir.test.runfiles/iree_core/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir
: 'RUN: at line 6';   iree-opt /dev/shm/bazel-sandbox.55f9fb942a89558c0ebc0aedd0d9a7544e74d0ab744e8907da495b34261debfd/linux-sandbox/18069/execroot/iree_core/bazel-out/k8-opt/bin/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir.test.runfiles/iree_core/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir  --pass-pipeline="builtin.module(hal.executable(hal.executable.variant(iree-llvmgpu-lower-executable-target)))"      --iree-codegen-llvmgpu-enable-transform-dialect-jit=false      --iree-codegen-llvmgpu-use-transform-dialect=/dev/shm/bazel-sandbox.55f9fb942a89558c0ebc0aedd0d9a7544e74d0ab744e8907da495b34261debfd/linux-sandbox/18069/execroot/iree_core/bazel-out/k8-opt/bin/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir.test.runfiles/iree_core/compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_foreach_to_gpu_spec.mlir |  FileCheck /dev/shm/bazel-sandbox.55f9fb942a89558c0ebc0aedd0d9a7544e74d0ab744e8907da495b34261debfd/linux-sandbox/18069/execroot/iree_core/bazel-out/k8-opt/bin/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir.test.runfiles/iree_core/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir --check-prefix=FOREACH-TO-GPU
--
Exit Code: 2

Command Output (stderr):
--
Please report issues to https://github.com/openxla/iree/issues and include the crash backtrace.
Stack dump:
0.	Program arguments: iree-opt /dev/shm/bazel-sandbox.55f9fb942a89558c0ebc0aedd0d9a7544e74d0ab744e8907da495b34261debfd/linux-sandbox/18069/execroot/iree_core/bazel-out/k8-opt/bin/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir.test.runfiles/iree_core/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir --pass-pipeline=builtin.module(hal.executable(hal.executable.variant(iree-llvmgpu-lower-executable-target))) --iree-codegen-llvmgpu-enable-transform-dialect-jit=false --iree-codegen-llvmgpu-use-transform-dialect=/dev/shm/bazel-sandbox.55f9fb942a89558c0ebc0aedd0d9a7544e74d0ab744e8907da495b34261debfd/linux-sandbox/18069/execroot/iree_core/bazel-out/k8-opt/bin/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir.test.runfiles/iree_core/compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_foreach_to_gpu_spec.mlir
 #0 0x000055eb7132417b llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x73db17b)
 #1 0x000055eb713[222](https://github.com/openxla/iree/actions/runs/4508189372/jobs/7936659654#step:4:223)d5 llvm::sys::RunSignalHandlers() (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x73d92d5)
 #2 0x000055eb7132479d SignalHandler(int) Signals.cpp:0:0
 #3 0x00007fd9d41ef520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000055eb6cf2feaf mlir::OpInterface<mlir::FunctionOpInterface, mlir::detail::FunctionOpInterfaceInterfaceTraits>::getInterfaceFor(mlir::Operation*) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x2fe6eaf)
 #5 0x000055eb70527479 hasTensorSemantics(mlir::Operation*) Bufferize.cpp:0:0
 #6 0x000055eb70527[225](https://github.com/openxla/iree/actions/runs/4508189372/jobs/7936659654#step:4:226) mlir::bufferization::bufferizeOp(mlir::Operation*, mlir::bufferization::BufferizationOptions const&, bool, mlir::bufferization::OpFilter const*, mlir::bufferization::BufferizationStatistics*) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x65de225)
 #7 0x000055eb6ea23db5 mlir::iree_compiler::runIREEOneShotBufferize(mlir::Operation*, mlir::bufferization::OneShotBufferizationOptions const&) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x4adadb5)
 #8 0x000055eb6e9d8d79 mlir::iree_compiler::IREE::transform_dialect::IREEBufferizeOp::apply(mlir::transform::TransformResults&, mlir::transform::TransformState&) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x4a8fd79)
 #9 0x000055eb6e9e675c mlir::transform::detail::TransformOpInterfaceInterfaceTraits::Model<mlir::iree_compiler::IREE::transform_dialect::IREEBufferizeOp>::apply(mlir::transform::detail::TransformOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*, mlir::transform::TransformResults&, mlir::transform::TransformState&) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x4a9d75c)
#10 0x000055eb70ff94ea mlir::transform::TransformState::applyTransform(mlir::transform::TransformOpInterface) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x70b04ea)
#11 0x000055eb710132b2 mlir::transform::SequenceOp::apply(mlir::transform::TransformResults&, mlir::transform::TransformState&) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x70ca2b2)
#12 0x000055eb70ff177c mlir::transform::detail::TransformOpInterfaceInterfaceTraits::Model<mlir::transform::SequenceOp>::apply(mlir::transform::detail::TransformOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*, mlir::transform::TransformResults&, mlir::transform::TransformState&) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x70a877c)
#13 0x000055eb70ff94ea mlir::transform::TransformState::applyTransform(mlir::transform::TransformOpInterface) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x70b04ea)
#14 0x000055eb70ffed62 mlir::transform::applyTransforms(mlir::Operation*, mlir::transform::TransformOpInterface, mlir::RaggedArray<llvm::PointerUnion<mlir::Operation*, mlir::Attribute, mlir::Value>> const&, mlir::transform::TransformOptions const&) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x70b5d62)
#15 0x000055eb6fbaacab mlir::transform::iree_dialects::detail::interpreterBaseRunOnOperationImpl(mlir::Operation*, llvm::StringRef, std::shared_ptr<mlir::OwningOpRef<mlir::ModuleOp>> const&, mlir::Pass::Option<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, llvm::cl::parser<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, mlir::Pass::Option<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, llvm::cl::parser<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, mlir::Pass::Option<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, llvm::cl::parser<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x5c61cab)
#16 0x000055eb6e85edb7 mlir::transform::iree_dialects::TransformInterpreterPassBase<(anonymous namespace)::TransformDialectInterpreterPass, mlir::iree_compiler::TransformDialectInterpreterBase>::runOnOperation() TransformDialectInterpreterPass.cpp:0:0
#17 0x000055eb711bdf54 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x7274f54)
#18 0x000055eb711be327 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x7275327)
#19 0x000055eb711c[229](https://github.com/openxla/iree/actions/runs/4508189372/jobs/7936659654#step:4:230)2 mlir::LogicalResult llvm::function_ref<mlir::LogicalResult (mlir::OpPassManager&, mlir::Operation*)>::callback_fn<mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_0>(long, mlir::OpPassManager&, mlir::Operation*) Pass.cpp:0:0
#20 0x000055eb6e82fda1 mlir::iree_compiler::(anonymous namespace)::LLVMGPULowerExecutableTargetPass::runOnOperation() LLVMGPULowerExecutableTarget.cpp:0:0
#21 0x000055eb711bdf54 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad35[235](https://github.com/openxla/iree/actions/runs/4508189372/jobs/7936659654#step:4:236)30d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x7274f54)
#22 0x000055eb711be327 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x7275327)
#23 0x000055eb711bfb59 mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x7276b59)
#24 0x000055eb711bde5e mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x7274e5e)
#25 0x000055eb711be327 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x7275327)
#26 0x000055eb711bfb59 mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x7276b59)
#27 0x000055eb711bde5e mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x7274e5e)
#28 0x000055eb711c0ab7 mlir::PassManager::runPasses(mlir::Operation*, mlir::AnalysisManager) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x7277ab7)
#29 0x000055eb711c0891 mlir::PassManager::run(mlir::Operation*) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x7277891)
#30 0x000055eb6cf26a55 performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#31 0x000055eb6cf2607f mlir::LogicalResult llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#32 0x000055eb712b4d0e mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, bool, bool) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x736bd0e)
#33 0x000055eb6cf[243](https://github.com/openxla/iree/actions/runs/4508189372/jobs/7936659654#step:4:244)ed mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x2fdb3ed)
#34 0x000055eb6cf17bc4 ireeOptRunMain (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x2fcebc4)
#35 0x00007fd9d41d6d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#36 0x00007fd9d41d6e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#37 0x000055eb6cf174e5 _start (/home/runner/.cache/bazel/_bazel_runner/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/iree_core/bazel-out/k8-opt/bin/tools/iree-opt+0x2fce4e5)
FileCheck error: '<stdin>' is empty.
FileCheck command line:  FileCheck /dev/shm/bazel-sandbox.55f9fb942a89558c0ebc0aedd0d9a7544e74d0ab744e8907da495b34[261](https://github.com/openxla/iree/actions/runs/4508189372/jobs/7936659654#step:4:262)debfd/linux-sandbox/18069/execroot/iree_core/bazel-out/k8-opt/bin/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir.test.runfiles/iree_core/compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir --check-prefix=FOREACH-TO-GPU

--

********************
********************
Failed Tests (1):
  IREE :: src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir
```

### PR DESCRIPTION
**Pull request by nicolasvasilache**
#12681 simplified the effects of IREE transforms to avoid always consuming the input handle and thus improve usage.
This was however lacking proper tracking now that the nested handles were not automatically invalidated anymore.
The revision fixes this oversight.

Fixes #12759

This also requires an upstream cherry-pick to properly pass RewriterBase for IR rewrites in VectorTransferOpTransforms: 
 553cebde0669aa98bb0624d9203b008c6e02f40e

### CODE REVIEW

**Comment by nicolasvasilache** [comment]
@stellaraccident could you patch this and rerun where you observed the flake ?

**Comment by stellaraccident** [comment]
> @stellaraccident could you patch this and rerun where you observed the flake ?

The flake was just two unrelated head presubmit that has already landed and subsequently passed. I'd estimate a 1/50 failure rate or so. So i don't have a reliable way to repro.

**Review by matthias-springer — APPROVED** [review]

File: compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp [hunk 1]
```diff
@@ -397,11 +400,14 @@ DiagnosedSilenceableFailure transform_dialect::ApplyPatternsOp::applyToOne(
   LogicalResult result =
       applyOpPatternsAndFold(ops, std::move(patterns), config);
   if (failed(result)) {
-    return mlir::emitDefiniteFailure(target, "greedy patterns failed");
+    return listener.check(
+        loc, mlir::emitDefiniteFailure(target, "greedy patterns failed"));
```
Comment (ftynse) [inline compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp:399]: I ticked at this because `emitDefiniteFailure` prints the error message immediately. It's unclear to me what is the API of `check` that requires passing it there.

File: llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/StructuredTransformOpsExt.h [hunk 2]
```diff
@@ -57,6 +57,21 @@ class TrackingListener : public RewriterBase::Listener,
 #endif // LLVM_ENABLE_ABI_BREAKING_CHECKS
   }
 
+  DiagnosedSilenceableFailure check(Location loc) {
+    if (failed(checkErrorState()))
+      return emitDefiniteFailure(loc, "listener failed");
+    return DiagnosedSilenceableFailure::success();
+  }
+  DiagnosedSilenceableFailure check(Location loc,
+                                    DiagnosedSilenceableFailure &&diag) {
```
Comment (ftynse) [inline llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/StructuredTransformOpsExt.h:67]: Note that the error message is reported when _constructing_ the definite failure, taking an rvalue doesn't do anything to that here. So the error message will be printed even if listenerState is a success.

File: llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/StructuredTransformOpsExt.h [hunk 3]
```diff
@@ -57,6 +57,21 @@ class TrackingListener : public RewriterBase::Listener,
...
+    LogicalResult listenerState = checkErrorState();
+    if (failed(listenerState)) {
+      (void)diag.checkAndReport();
+      return emitDefiniteFailure(loc, "listener failed");
```
Comment (ftynse) [inline llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/StructuredTransformOpsExt.h]: The second message is redundant. The definite error message will have been printed before entering this function, and silenceable errors will be printed in `checkAndReport` just before.

**Review by ftynse — COMMENTED** [review]
Error reporting looks off.

**Review by MaheshRavishankar — DISMISSED** [review]
Could we wait for the integrate to catch up?

**Comment by nicolasvasilache** [comment]
sync'ed offline w/ @ftynse to get the check API in a better state, addressed.

**Review by ftynse — APPROVED** [review]
