### PR TITLE
[CPU] Support dynamic attention by tiling K1 when needed.

### LINKED ISSUE #23277: Compiler crash in LLVMCPUSelectLoweringStrategy with dynamic-shape iree_linalg_ext.attention
### Description

The compiler crashes during the `LLVMCPUSelectLoweringStrategy` pass when compiling an `iree_linalg_ext.attention` op with fully dynamic 3D input shapes (`tensor<?x?x?xf32>`).

The crash occurs in `setRootConfig` for `AttentionOp` when calling `limitVectorTileSizes`.

### Reproducer

Save as `attention_crash.mlir`:

```mlir
module @attention_crash {
  util.func public @attention(
      %query: tensor<?x?x?xf32>,
      %key: tensor<?x?x?xf32>,
      %value: tensor<?x?x?xf32>,
      %scale: f32
  ) -> tensor<?x?x?xf32> {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c2 = arith.constant 2 : index

    %batch = tensor.dim %query, %c0 : tensor<?x?x?xf32>
    %seq_len = tensor.dim %query, %c1 : tensor<?x?x?xf32>
    %head_dim = tensor.dim %query, %c2 : tensor<?x?x?xf32>

    %output_init = tensor.empty(%batch, %seq_len, %head_dim) : tensor<?x?x?xf32>
    %output = iree_linalg_ext.attention {
      indexing_maps = [
        affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2)>,
        affine_map<(d0, d1, d2, d3, d4) -> (d0, d3, d2)>,
        affine_map<(d0, d1, d2, d3, d4) -> (d0, d3, d4)>,
        affine_map<(d0, d1, d2, d3, d4) -> ()>,
        affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d4)>
      ]
    } ins(%query, %key, %value, %scale : tensor<?x?x?xf32>, tensor<?x?x?xf32>, tensor<?x?x?xf32>, f32)
      outs(%output_init : tensor<?x?x?xf32>) {
    ^bb0(%arg0: f32):
      iree_linalg_ext.yield %arg0 : f32
    } -> tensor<?x?x?xf32>

    util.return %output : tensor<?x?x?xf32>
  }
}
```

Compile with:
```bash
iree-compile attention_crash.mlir --iree-hal-target-backends=llvm-cpu -o /dev/null
```

### Stack trace (key frames)

```
#4 limitVectorTileSizes(...) KernelDispatch.cpp:747
#8 setRootConfig(..., AttentionOp) KernelDispatch.cpp:2344
#14 LLVMCPUSelectLoweringStrategyPass::runOnOperation() LLVMCPUSelectLoweringStrategy.cpp:238
```

### Environment

- IREE: pip package (current release)
- OS: Fedora 43, Linux 6.17
- Target: `llvm-cpu`

### Notes

Static shapes compile successfully. The crash appears to occur during tile size computation when shapes are unknown at compile time.

---

*This issue was authored by Claude (Opus 4.5) and reviewed by @stellaraccident.*

### PR DESCRIPTION
**Pull request by hanhanW**
The K1 dimension (head_dim) in attention was unconditionally left untiled, which leads large stack allocation when the dimension is dynamic.

K1 is typically small (64/128 per AttentionOpDetail docs), so the original heuristic to leave it untiled was reasonable. The revision sets the tile sizes if the dimension is dynamic or it is not within typical range (<= 128).

E2E tests are added, and they have the same inputs and expected outputs like attention.mlir (which is a static version). Some backends, e.g., AMDGPU, does not support dynamic attention, so we create a new file. The test is enabled on CPU and VMVX backends in the revision.

Fixes https://github.com/iree-org/iree/issues/23277

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 1]
```diff
@@ -2395,13 +2395,18 @@ static LogicalResult setRootConfig(mlir::FunctionOpInterface entryPointFn,
...
   }
 
+  // K1 dimensions (head_dim) are typically small. Per AttentionOpDetail docs
+  // (IndexingUtils.h), K1 is generally 64 or 128. When K1 is static and within
+  // this typical range, we leave it untiled. However, for dynamic K1 or
+  // unusually large K1, we must tile to avoid unbounded allocations.
+  constexpr int64_t kTypicalK1Threshold = 128;
   SmallVector<int64_t> vecTileSizes(vecTileSizeBounds.size(), 1);
-  // Due to the way attention works, K1 dimensions cannot be tiled. Mark k1
-  // reduction dimensions not to distribute.
```
Comment (Groverkss) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:2400]: I wonder what I was thinking when i wrote this comment, ofcourse you can serially tile it.

**Review by Groverkss — APPROVED** [review]

**Review by bjacob — APPROVED** [review]

**Comment by amd-eochoalo** [comment]
@hanhanW this [PR produces a build error while generating tests for android:](https://github.com/iree-org/iree/actions/runs/21419015906/job/61674679972#step:10:2970)

```
FAILED: [code=1] tests/e2e/linalg_ext_ops/check_llvm-cpu_local-task_dynamic_attention.mlir_module.vmfb /home/runner/work/iree/iree/build-android-arm_64/tests/e2e/linalg_ext_ops/check_llvm-cpu_local-task_dynamic_attention.mlir_module.vmfb 
cd /home/runner/work/iree/iree/build-android-arm_64/tests/e2e/linalg_ext_ops && /home/runner/work/iree/iree/.venv/bin/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-target-cpu=generic /home/runner/work/iree/iree/tests/e2e/linalg_ext_ops/dynamic_attention.mlir -o check_llvm-cpu_local-task_dynamic_attention.mlir_module.vmfb --iree-hal-executable-object-search-path=\"/home/runner/work/iree/iree/build-android-arm_64\" --iree-llvmcpu-target-triple=aarch64-none-linux-android29
/home/runner/work/iree/iree/tests/e2e/linalg_ext_ops/dynamic_attention.mlir:26:13: error: Yield operand #1 is not equivalent to the corresponding iter bbArg
  %result = iree_linalg_ext.attention {
            ^
/home/runner/work/iree/iree/tests/e2e/linalg_ext_ops/dynamic_attention.mlir:26:13: error: Yield operand #1 is not equivalent to the corresponding iter bbArg
  %result = iree_linalg_ext.attention {
            ^
/home/runner/work/iree/iree/tests/e2e/linalg_ext_ops/dynamic_attention.mlir:26:13: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"llvm-cpu", "embedded-elf-arm_64", {cpu = "generic", cpu_features = "+reserve-x18", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32", iree.encoding.resolver = #iree_cpu.cpu_encoding_resolver<>, max_stack_allocation_size = 32768 : i64, native_vector_size = 16 : i64, target_triple = "aarch64-unknown-unknown-eabi-elf"}>
  %result = iree_linalg_ext.attention {
            ^
```

**Comment by hanhanW** [comment]
It looks like it triggers a bug, looking. Let's revert it for now.

**Comment by hanhanW** [comment]
The issue happens when masking is disabled. It routes back to the other old issue: https://github.com/iree-org/iree/issues/16956

I have a local fix and I'm polishing it.

**Comment by hanhanW** [comment]
https://github.com/iree-org/iree/pull/23318 fixes the issue. I'll re-land the PR once the other change is landed.
