### PR TITLE
[Codegen] Teach MaterializeEncodingIntoPadding about resolved layouts.

### LINKED ISSUE #20362: [GPU] Failed to materialize encodings for a dispatch in padding approach
To repro:

Run: `iree-opt --pass-pipeline="builtin.module(func.func(iree-codegen-materialize-encoding-into-padding))" ~/repro.mlir`

```mlir
#encoding = #iree_encoding.encoding<operand_index = 1 : index, op_type =  matmul, element_types = [f16, f16, f32], layouts = [#iree_encoding.pad_encoding_layout<[0, 64]>]>
#pipeline_layout = #hal.pipeline.layout<constants = 4, bindings = [#hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer>], flags = None>
module {
  func.func @_encoding_0_encode_4096x4096xf16_to_4096x4096xf16() {
    %c32_i64 = arith.constant 32 : i64
    %0 = hal.interface.constant.load layout(#pipeline_layout) ordinal(0) : i32
    %1 = hal.interface.constant.load layout(#pipeline_layout) ordinal(1) : i32
    %2 = hal.interface.constant.load layout(#pipeline_layout) ordinal(2) : i32
    %3 = hal.interface.constant.load layout(#pipeline_layout) ordinal(3) : i32
    %4 = arith.extui %0 : i32 to i64
    %5 = arith.extui %1 : i32 to i64
    %6 = arith.shli %5, %c32_i64 : i64
    %7 = arith.ori %4, %6 : i64
    %8 = arith.index_castui %7 : i64 to index
    %9 = arith.extui %2 : i32 to i64
    %10 = arith.extui %3 : i32 to i64
    %11 = arith.shli %10, %c32_i64 : i64
    %12 = arith.ori %9, %11 : i64
    %13 = arith.index_castui %12 : i64 to index
    %14 = hal.interface.binding.subspan layout(#pipeline_layout) binding(0) alignment(64) offset(%8) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<4096x4096xf16>>
    %15 = hal.interface.binding.subspan layout(#pipeline_layout) binding(1) alignment(64) offset(%13) flags("None") : !flow.dispatch.tensor<writeonly:tensor<4096x4096xf16, #encoding>>
    %16 = flow.dispatch.tensor.load %14, offsets = [0, 0], sizes = [4096, 4096], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<4096x4096xf16>> -> tensor<4096x4096xf16>
    %17 = iree_encoding.set_encoding %16 : tensor<4096x4096xf16> -> tensor<4096x4096xf16, #encoding>
    flow.dispatch.tensor.store %17, %15, offsets = [0, 0], sizes = [4096, 4096], strides = [1, 1] : tensor<4096x4096xf16, #encoding> -> !flow.dispatch.tensor<writeonly:tensor<4096x4096xf16, #encoding>>
    return
  }
}
```

### PR DESCRIPTION
**Pull request by hanhanW**
The revision updates the converted type for MaterializePadEncodingTypeConverter because it should always return the final type of the dialect conversion. In this context, the padding encoding should be dropped for any tensor type, and the binding type should get padded type. Thus, it implements `MaterializeInterfaceBindingEncoding` pattern for the pass.

It is a step towards https://github.com/iree-org/iree/issues/20160, since we now have better understanding about the abstraction.

Fixes https://github.com/iree-org/iree/issues/20362

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/Common/MaterializeEncodingIntoPadding.cpp [hunk 1]
```diff
@@ -199,6 +211,38 @@ struct MaterializeFlowDispatchTensorStoreOp final
...
 };
 
+/// Pattern to convert `flow.dispatch.tensor.store` operation when
+/// materializing the encoding. We can not reuse the existing one because it
+/// does not transform new dynamic dimension through interface. The other
+/// difference is that the converted type of the padding attribute is not as the
+/// same as the tensor type that drops encoding.
+/// TODO(#20160): Abstract new interface methods and collapse two patterns.
+struct MaterializeInterfaceBindingEncoding
+    : public OpMaterializeEncodingPattern<
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/Common/MaterializeEncodingIntoPadding.cpp]: nit:
```suggestion
struct MaterializeInterfaceBindingEncoding final
    : OpMaterializeEncodingPattern<
```

File: compiler/src/iree/compiler/Codegen/Common/MaterializeEncodingIntoPadding.cpp [hunk 2]
```diff
@@ -199,6 +211,38 @@ struct MaterializeFlowDispatchTensorStoreOp final
...
+          IREE::HAL::InterfaceBindingSubspanOp> {
+  using OpMaterializeEncodingPattern<
+      IREE::HAL::InterfaceBindingSubspanOp>::OpMaterializeEncodingPattern;
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/Common/MaterializeEncodingIntoPadding.cpp]:
```suggestion
  using OpMaterializeEncodingPattern::OpMaterializeEncodingPattern;
```

File: compiler/src/iree/compiler/Codegen/Common/MaterializeEncodingIntoPadding.cpp [hunk 3]
```diff
@@ -199,6 +211,38 @@ struct MaterializeFlowDispatchTensorStoreOp final
...
+
+  LogicalResult
+  matchAndRewrite(IREE::HAL::InterfaceBindingSubspanOp subspanOp,
+                  OpAdaptor adaptor,
+                  ConversionPatternRewriter &rewriter) const override {
+    auto resultType = llvm::dyn_cast<IREE::Flow::DispatchTensorType>(
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/Common/MaterializeEncodingIntoPadding.cpp]:
```suggestion
    auto resultType = dyn_cast<IREE::Flow::DispatchTensorType>(
```

**Review by kuhar — APPROVED** [review]
