### PR TITLE
[Codegen] Fix shared memory overflow for accumulating scaled matmuls

### LINKED ISSUE #22992: [Codegen] Shared memory exceeded the limit for `e2e_matmul_cdna4_mxfp4_rocm_hip_matmul`
Input MLIR: https://gist.github.com/Yu-Zhewen/a8c64060cc6f376654bb1b56176e58da

Error message:
```
[643/1524] Generating /home/zhewenyu/iree/build/tests/e2e/matmul/e2e_matmul_cdna4_mxfp4_rocm_hip_matmul.vmfb from e2e_matmul_cdna4_mxfp4_rocm_hip_matmul.mlir
FAILED: tests/e2e/matmul/e2e_matmul_cdna4_mxfp4_rocm_hip_matmul.vmfb /home/zhewenyu/iree/build/tests/e2e/matmul/e2e_matmul_cdna4_mxfp4_rocm_hip_matmul.vmfb
cd /home/zhewenyu/iree/build/tests/e2e/matmul && /home/zhewenyu/iree/build/tools/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=rocm --iree-hip-target=gfx950 /home/zhewenyu/iree/build/tests/e2e/matmul/e2e_matmul_cdna4_mxfp4_rocm_hip_matmul.mlir -o /home/zhewenyu/iree/build/tests/e2e/matmul/e2e_matmul_cdna4_mxfp4_rocm_hip_matmul.vmfb --iree-hal-executable-object-search-path=\"/home/zhewenyu/iree/build\"
/home/zhewenyu/iree/build/tests/e2e/matmul/e2e_matmul_cdna4_mxfp4_rocm_hip_matmul.mlir:6:13: error: function 'matmul_accumulate_mx_scale_f8E8M0FNU_512x4x32xf4E2M1FN_times_512x4x32xf4E2M1FN_into_512x512xf32_dispatch_0_scaled_matmul_like_512x512x4x32_f4E2M1FNxf4E2M1FNxf8E8M0FNUxf8E8M0FNUxf32' uses 296960 bytes of shared memory; exceeded the limit of 163840 bytes
  %result = linalg.generic {
```

Triggered by: https://github.com/iree-org/iree/pull/22975

The error wasn't captured by CI because the test requires cdna4, and I believe we still have some setup issues on the mi350 machine?

Looking at https://github.com/iree-org/iree/blob/55430fded30d7ef4ab74ebb9659c571c1d07cca3/compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp#L682-L687, I can see two problems:

1. We don't count usage for LHS/RHS scales, though this is already a known issue flagged by https://github.com/iree-org/iree/issues/22785

2. I don't have much context, but I saw we actually never set the `doCPromotion` flag, which seems more relevant to https://github.com/iree-org/iree/pull/22975

### PR DESCRIPTION
**Pull request by jtuyls**
This resolves: https://github.com/iree-org/iree/issues/22992

We're seeing a shared memory usage failure in the e2e tests for scaled accumulating matmuls when targeting gfx950 which isn't catched as this is not checked in CI (see this PR for that: https://github.com/iree-org/iree/pull/23090). This PR fixes this by taking the shared memory usage for this into when applicable.

Sweep of failing matmul_accumulate shapes and selected tile sizes and effect on LDS allocation **(before this PR)**:

| M | N | Workgroup Tiles | Acc Size | Total Est. | Result |
|---|---|-----------------|----------|------------|--------|
| 128 | 128 | 32×32 | 4 KB | ~8 KB | ✅ OK |
| 128 | 256 | 32×32 | 4 KB | ~8 KB | ✅ OK |
| 128 | 384 | 128×128 | 64 KB | ~81 KB | ✅ OK |
| 128 | 512 | 128×256 | 128 KB | ~153 KB | ✅ OK |
| 128 | 768 | 128×256 | 128 KB | ~153 KB | ✅ OK |
| 128 | 1024 | 128×256 | 128 KB | ~153 KB | ✅ OK |
| 256 | 128 | 32×32 | 4 KB | ~8 KB | ✅ OK |
| **256** | **256** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| 256 | 384 | 256×128 | 128 KB | ~153 KB | ✅ OK |
| **256** | **512** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| **256** | **768** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| **256** | **1024** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| 384 | 128 | 128×128 | 64 KB | ~81 KB | ✅ OK |
| 384 | 256 | 128×256 | 128 KB | ~153 KB | ✅ OK |
| 384 | 384 | 128×128 | 64 KB | ~81 KB | ✅ OK |
| 384 | 512 | 128×256 | 128 KB | ~153 KB | ✅ OK |
| 384 | 768 | 128×256 | 128 KB | ~153 KB | ✅ OK |
| 384 | 1024 | 128×256 | 128 KB | ~153 KB | ✅ OK |
| 512 | 128 | 256×128 | 128 KB | ~153 KB | ✅ OK |
| **512** | **256** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| 512 | 384 | 256×128 | 128 KB | ~153 KB | ✅ OK |
| **512** | **512** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| **512** | **768** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| **512** | **1024** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| 768 | 128 | 256×128 | 128 KB | ~153 KB | ✅ OK |
| **768** | **256** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| 768 | 384 | 256×128 | 128 KB | ~153 KB | ✅ OK |
| **768** | **512** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| **768** | **768** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| **768** | **1024** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| 1024 | 128 | 256×128 | 128 KB | ~153 KB | ✅ OK |
| **1024** | **256** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| 1024 | 384 | 256×128 | 128 KB | ~153 KB | ✅ OK |
| **1024** | **512** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| **1024** | **768** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |
| **1024** | **1024** | **256×256** | **256 KB** | **~290 KB** | ❌ FAIL |

With this PR:
| M | N | Workgroup Tiles | Acc Size | Total Est. | Result |
|---|---|-----------------|----------|------------|--------|
| 128 | 128 | 32×32 | 4 KB | ~8 KB | ✅ OK |
| 128 | 256 | 32×32 | 4 KB | ~8 KB | ✅ OK |
| 128 | 384 | 128×128 | 64 KB | ~81 KB | ✅ OK |
| 128 | 512 | 128×256 | 128 KB | ~153 KB | ✅ OK |
| 128 | 768 | 128×256 | 128 KB | ~153 KB | ✅ OK |
| 128 | 1024 | 128×256 | 128 KB | ~153 KB | ✅ OK |
| 256 | 128 | 32×32 | 4 KB | ~8 KB | ✅ OK |
| 256 | 256 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 256 | 384 | 256×128 | 128 KB | ~153 KB | ✅ OK |
| 256 | 512 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 256 | 768 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 256 | 1024 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 384 | 128 | 128×128 | 64 KB | ~81 KB | ✅ OK |
| 384 | 256 | 128×256 | 128 KB | ~153 KB | ✅ OK |
| 384 | 384 | 128×128 | 64 KB | ~81 KB | ✅ OK |
| 384 | 512 | 128×256 | 128 KB | ~153 KB | ✅ OK |
| 384 | 768 | 128×256 | 128 KB | ~153 KB | ✅ OK |
| 384 | 1024 | 128×256 | 128 KB | ~153 KB | ✅ OK |
| 512 | 128 | 256×128 | 128 KB | ~153 KB | ✅ OK |
| 512 | 256 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 512 | 384 | 256×128 | 128 KB | ~153 KB | ✅ OK |
| 512 | 512 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 512 | 768 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 512 | 1024 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 768 | 128 | 256×128 | 128 KB | ~153 KB | ✅ OK |
| 768 | 256 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 768 | 384 | 256×128 | 128 KB | ~153 KB | ✅ OK |
| 768 | 512 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 768 | 768 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 768 | 1024 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 1024 | 128 | 256×128 | 128 KB | ~153 KB | ✅ OK |
| 1024 | 256 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 1024 | 384 | 256×128 | 128 KB | ~153 KB | ✅ OK |
| 1024 | 512 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 1024 | 768 | **128×256** | **128 KB** | ~153 KB | ✅ OK |
| 1024 | 1024 | **128×256** | **128 KB** | ~153 KB | ✅ OK |

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp [hunk 1]
```diff
@@ -681,6 +681,11 @@ FailureOr<GPUMMASchedule> deduceMMASchedule(
                              transposedLhs, transposedRhs);
       int64_t sharedMemoryUsed = calculateOperandsSharedMemoryUsedInBytes(
           schedule, lhsBitwidth, rhsBitwidth, problem.numHorizontallyFusedOps);
+      // Add accumulator/result memory when it uses shared memory (LDS):
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp:684]: Do we need these comments?

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 2]
```diff
@@ -615,12 +618,16 @@ static bool checkForElementwiseUsersWithNewOperands(linalg::LinalgOp linalgOp) {
 /// determine the convolution dimensions for padding when creating
 /// `padding_conv` config. `padding_conv` attribute is only used when padding
 /// convolutions before converting them to IGEMM.
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp:620]: We seem to have been usin ` and not | for variables here

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 3]
```diff
@@ -795,23 +802,26 @@ getMatmulOrIGEMMLoweringConfigAndWorkgroupSize(
                              rhsElemType,
                              initElemType};
 
+  // Accumulator needs shared memory if:
+  // - Padding requires C promotion, OR
+  // - The operation has an existing accumulator (matmul_accumulate)
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp:807]: ... Why would we be using shared memory for existing accumulators unconditionally? Can we be more precise here?

File: compiler/src/iree/compiler/Codegen/Utils/Utils.cpp [hunk 4]
```diff
@@ -2218,4 +2219,77 @@ std::optional<SmallVector<int64_t>> getCopyTileSizes(linalg::CopyOp copyOp) {
...
+// Get the `iree_tensor_ext.dispatch.tensor.load` that this value is
+// populated with. This could potentially walk the use-def chain to get the load
+// operation, but for now it just returns the load op if that is the defining
+// operation for `v`.
+template <typename LoadOpTy>
+static std::optional<LoadOpTy> getLoadOp(Value v) {
+  auto loadOp = v.getDefiningOp<LoadOpTy>();
+  if (loadOp) {
+    return loadOp;
+  }
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/Utils/Utils.cpp]:
```suggestion
  if (auto loadOp = v.getDefiningOp<LoadOpTy>()) {
    return loadOp;
  }
```

File: compiler/src/iree/compiler/Codegen/Utils/Utils.cpp [hunk 5]
```diff
@@ -2218,4 +2219,77 @@ std::optional<SmallVector<int64_t>> getCopyTileSizes(linalg::CopyOp copyOp) {
...
+// store op if the result has a single use and that use is the store op.
+template <typename StoreOpTy>
+static std::optional<StoreOpTy> getStoreOp(Value v) {
+  if (v.getNumUses() != 1) {
+    return std::nullopt;
+  }
+  auto storeOp = dyn_cast<StoreOpTy>(*(v.getUsers().begin()));
+  if (storeOp) {
+    return storeOp;
+  }
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/Utils/Utils.cpp]:
```suggestion
  if (auto storeOp = dyn_cast<StoreOpTy>(*(v.getUsers().begin()))) {
    return storeOp;
  }
```

**Review by kuhar — APPROVED** [review]

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp (hunk 1 above)
Comment (kuhar) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp:684]: I appreciate them FWIW

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp (hunk 3 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp:807]: It's based on the current implementation and yes, all accumulating matmuls should follow the same flow here to load the inits into shared memory and this needs to be accounted for, so I don't think we can be more precise here.

**Review by Yu-Zhewen — APPROVED** [review]
Thanks! This resolves https://github.com/iree-org/iree/issues/22992.

CC: @Muzammiluddin-Syed-ECE

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp (hunk 2 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp:620]: Yeah, different files in this PR are using different conventions.. I updated it now to follow the surrounding documentation

File: compiler/src/iree/compiler/Codegen/Utils/Utils.cpp (hunk 4 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/Utils/Utils.cpp]: Thanks, updated now

File: compiler/src/iree/compiler/Codegen/Utils/Utils.cpp (hunk 5 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/Utils/Utils.cpp]: Thanks, updated now.

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp (hunk 3 above)
Comment (krzysz00) [reply compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp:807]: ... I claim that the inits do not need to be loaded to shared memory? Why is this being done?

Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp:807]: Yeah, I think that's a different discussion and worth having for sure. For me, that's orthogonal to this PR, because currently the lowering of accumulating matmuls is implemented this way and we're in a broken state and this PR puts us back on correct compilation on a wide variety of problematic shapes, so I think it worth to first get this in and think about other ways to handle accumulating matmuls later.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp (hunk 1 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp:684]: I think it's useful as well.

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp (hunk 3 above)
Comment (krzysz00) [reply compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp:807]: Agreed, let's make that a followup

Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp:807]: Created an issue here: https://github.com/iree-org/iree/issues/23095
