### PR TITLE
[ConstEval] Do not hoist if the hoisted value increases size significantly

### LINKED ISSUE #15017: GPTQ: Vmfb Size is Double of the IR size
### What happened?

Hi, while compiling the [falcon-7b-instruct-GPTQ](https://huggingface.co/TheBloke/falcon-7b-instruct-GPTQ) model, the size of the [Linalg IR](https://storage.googleapis.com/shark_tank/falcon/falcon_7b_gptq_linalg.mlir) I get is 7.7GB, on the other hand after the iree-compile the [vmfb](https://storage.googleapis.com/shark_tank/falcon/falcon_7b_gptq_cpu.vmfb) which I'm getting is of 13.4GB. I'm not able to understand how's this possible. Also, is this expected or not? The issue exists for both the CPU and CUDA backend. You can find the elided Linalg IR [here](https://gist.github.com/vivekkhandelwal1/8104982239e89e3be22730909fbb43d6).

### Steps to reproduce your issue

To reproduce the issue, run the following compilation command:
```
iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary     --iree-hal-target-backends=llvm-cpu --mlir-print-debuginfo     --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host     --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64     --iree-vm-bytecode-module-strip-source-map=false --iree-util-zero-fill-elided-attrs     --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false --iree-hal-dump-executable-sources-to=hal_sources_falcon_7b_gptq_cpu    --iree-consteval-jit-debug=true   --iree-stream-resource-max-allocation-size=3221225472 --iree-llvmcpu-target-triple=x86_64-linux-gnu falcon_7b_gptq_linalg.mlir -o falcon_7b_gptq_cpu.vmfb
```
over the following [Linalg IR](https://storage.googleapis.com/shark_tank/falcon/falcon_7b_gptq_linalg.mlir).

### What component(s) does this issue relate to?

MLIR, Compiler

### Version information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Groverkss**
Currently, the constant expression hoisting policy does not account the increase in size
of global constants when hoisting. This makes ConstEval dequantize weights for models.
This patch fixes this by making constant expression size delta aware. 

Fixes #15017

### CODE REVIEW

File: compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp [hunk 1]
```diff
@@ -309,6 +309,32 @@ void ConstExprHoistingPolicy::initialize() {
...
+    }
+  }
+
+  int64_t outSizeBits = 0;
+  if (auto type = dyn_cast<ShapedType>(info->constValue.getType())) {
+    outSizeBits = type.getNumElements() * type.getElementTypeBitWidth();
+  }
+
+  // Anything smaller than 1MB is okay to hoist.
+  const int64_t kThresholdVerySmall = 1024 * 1024 * 8;
```
Comment (qedawkins) [inline compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp]: If possible, this would be really nice to have control over with a flag IMHO (at least for being able to set it to 0 in certain cases).

File: compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp [hunk 2]
```diff
@@ -309,6 +309,32 @@ void ConstExprHoistingPolicy::initialize() {
...
 }
 
+static bool doesHoistingIncreaseSizeSignificantly(
+    const ConstExprAnalysis::ConstValueInfo *info) {
+
+  int64_t inSizeBits = 0;
+  for (Value root : info->roots) {
+    // TODO: Are there any other types we care about here?
+    if (auto type = dyn_cast<ShapedType>(root.getType())) {
+      inSizeBits += type.getNumElements() * type.getElementTypeBitWidth();
```
Comment (benvanik) [inline compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp]: use `IREE::Util::getRoundedPhysicalStorageSize` instead of computing this yourself - it takes a shaped type and gets you the byte count and properly handles sub-byte types (here and below)

File: compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp (hunk 1 above)
Comment (benvanik) [reply compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp]: yeah, make a flag like we have https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp#L34-L38
(e.g. "iree-flow-const-expr-max-size-increase-threshold")

**Review by benvanik — CHANGES_REQUESTED** [review]

**Review by stellaraccident — CHANGES_REQUESTED** [review]
Agreed with the comments from Ben and Quinn.

**Comment by stellaraccident** [comment]
Also, this looks like a legitimate issue:

```
2023-09-29T18:14:06.7678477Z FAILED: tests/e2e/regression/check_regression_tosa_llvm-cpu_linalg_quantized_matmul_vs_linalg_matmul.mlir_module.vmfb /work/full-build-dir/tests/e2e/regression/check_regression_tosa_llvm-cpu_linalg_quantized_matmul_vs_linalg_matmul.mlir_module.vmfb 
2023-09-29T18:14:06.7682461Z cd /work/full-build-dir/tests/e2e/regression && /work/full-build-dir/tools/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=llvm-cpu --iree-input-type=tosa /work/tests/e2e/regression/linalg_quantized_matmul_vs_linalg_matmul.mlir -o check_regression_tosa_llvm-cpu_linalg_quantized_matmul_vs_linalg_matmul.mlir_module.vmfb --iree-hal-executable-object-search-path=\"/work/full-build-dir\" --iree-llvmcpu-embedded-linker-path=\"/work/full-build-dir/llvm-project/bin/lld\" --iree-llvmcpu-wasm-linker-path=\"/work/full-build-dir/llvm-project/bin/lld\"
2023-09-29T18:14:06.7687985Z iree-compile: /work/full-build-dir/llvm-project/tools/mlir/include/mlir/IR/BuiltinTypeInterfaces.h.inc:162: int64_t mlir::ShapedType::getNumElements() const: Assertion `hasStaticShape() && "cannot get element count of dynamic shaped type"' failed.
2023-09-29T18:14:06.7689482Z Please report issues to https://github.com/openxla/iree/issues and include the crash backtrace.
2023-09-29T18:14:06.7690224Z Stack dump:
```

I expect that we are excluding dynamic shaped parts of the analysis subsequently but the cost is still being evaluated with them still in.

File: compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp [hunk 3]
```diff
@@ -21,6 +22,12 @@ namespace iree_compiler {
 namespace IREE {
 namespace Util {
 
+static llvm::cl::opt<int64_t> clConstExprMaxSizeIncreaseThreshold(
```
Comment (stellaraccident) [inline compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp:25]: We will likely want to plumb this through as a real option vs a global cl option (so it can be controlled by API). Fine to do later.

**Review by stellaraccident — APPROVED** [review]
Thanks!

**Review by benvanik — APPROVED** [review]

File: compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp (hunk 3 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp:25]: Filed an issue for this to do later: https://github.com/openxla/iree/issues/15073
