### PR TITLE
[InputConversion] Support dynamic torch.aten.view.dtype

### LINKED ISSUE #20002: torch.aten.view.dtype from f8E4M3FNUZ to si8 with dynamic dimension fails to lower
### What happened?

```mlir
    %0 = torch.aten.view.dtype %arg0, %int1
        : !torch.vtensor<[?,32,8,128],f8E4M3FNUZ>, !torch.int
        -> !torch.vtensor<[?,32,8,128],si8>
```

results in error
```
small-reproducer.mlir:5:10: error: 'flow.tensor.bitcast' op value set has 1 dynamic dimensions but only 0 dimension values are attached
    %0 = torch.aten.view.dtype %arg0, %int1
         ^
small-reproducer.mlir:5:10: note: see current operation: %1 = "flow.tensor.bitcast"(%0) <{operandSegmentSizes = array<i32: 1, 0, 0>}> : (tensor<?x32x8x128xf8E4M3FNUZ>) -> tensor<?x32x8x128xi8>
```

### Steps to reproduce your issue

Compile the below IR with
```
iree-compile small-reproducer.mlir \
  -o=small-reproducer.vmfb \
  --iree-hip-target=gfx942 \
  --iree-hal-target-device=hip
```

```mlir
func.func @main(
  %arg0: !torch.vtensor<[?,32,8,128],f8E4M3FNUZ>
) -> !torch.vtensor<[?,32,8,128],si8> {
    %int1 = torch.constant.int 1
    %0 = torch.aten.view.dtype %arg0, %int1
        : !torch.vtensor<[?,32,8,128],f8E4M3FNUZ>, !torch.int
        -> !torch.vtensor<[?,32,8,128],si8>
  return %0 : !torch.vtensor<[?,32,8,128],si8>
}
```

### What component(s) does this issue relate to?

MLIR, Compiler

### Version information

8fab35ce603ecd6cef5c90cb62c0115b432aa66d

### Additional context

This was encountered when trying to compile Lllam f8 and the bitcasting was required to appease Torch for not supporting `torch.Tensor.index_copy_` for `torch.float8_e4m3fnuz`.
More context at https://github.com/nod-ai/shark-ai/pull/896#issuecomment-2658503338

### PR DESCRIPTION
**Pull request by IanWood1**
Adds dynamic dims when building `flow.tensor.bitcast` ops and scales them when the innermost dim is dynamic.

Fixes https://github.com/iree-org/iree/issues/20002

### CODE REVIEW

File: compiler/plugins/input/Torch/InputConversion/BitCastQuantTensor.cpp [hunk 1]
```diff
@@ -51,8 +52,29 @@ class BitCastViewDtype
...
+    SmallVector<Value> inDynamicDims =
+        IREE::Util::buildDynamicDimsForValue(loc, builtinCast, rewriter);
+    SmallVector<Value> outDynamicDims(inDynamicDims);
+    if (bType.isDynamicDim(bType.getRank() - 1)) {
+      auto inElemWidth = IREE::Util::getTypeBitWidth(bType.getElementType());
+      auto outElemWidth = IREE::Util::getTypeBitWidth(rType.getElementType());
+      if (inElemWidth > outElemWidth) {
+        auto scale = rewriter.create<arith::ConstantIndexOp>(
+            loc, inElemWidth / outElemWidth);
+        outDynamicDims.back() = rewriter.create<arith::DivUIOp>(
```
Comment (MaheshRavishankar) [inline compiler/plugins/input/Torch/InputConversion/BitCastQuantTensor.cpp]: Make this divsi. That has better chance of folding away with a muli with nsw.

**Review by MaheshRavishankar — APPROVED** [review]
