### PR TITLE
[LLVMCPU] Tracks the dimension mapping for multi lowering config

### LINKED ISSUE #21539: [CPU] Incorrect result in lowering config propagation
To repro: `iree-opt --pass-pipeline='builtin.module(iree-llvmcpu-select-lowering-strategy)' repro.mlir`

Input: https://gist.github.com/hanhanW/f4581c2860535cc7aa71be71c27b4070

```mlir
#executable_target_embedded_elf_x86_64_ = #hal.executable.target<"llvm-cpu", "embedded-elf-x86_64", {cpu_features = "+avx512f", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-linux-gnu"}>
#map = affine_map<(d0, d1) -> (d0, d1)>
#map1 = affine_map<(d0, d1) -> (d0)>
#map2 = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
#map3 = affine_map<(d0, d1, d2) -> (d0)>
#map4 = affine_map<(d0, d1, d2) -> (d0, d1)>
#map5 = affine_map<(d0, d1, d2) -> (d2, d0, d1)>
#pipeline_layout = #hal.pipeline.layout<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>
module {
  func.func @decode$async_dispatch_16_reduction_32x262144_f32() attributes {hal.executable.target = #executable_target_embedded_elf_x86_64_} {
    %cst = arith.constant 0.000000e+00 : f32
    %cst_0 = arith.constant 2.621440e+05 : f32
    %cst_1 = arith.constant 9.99999997E-7 : f32
    %c50872448 = arith.constant 50872448 : index
    %c0 = arith.constant 0 : index
    %c128 = arith.constant 128 : index
    %0 = hal.interface.binding.subspan layout(#pipeline_layout) binding(0) alignment(64) offset(%c50872448) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<32x262144xf16>>
    %1 = hal.interface.binding.subspan layout(#pipeline_layout) binding(0) alignment(64) offset(%c0) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<32xf32>>
    %2 = hal.interface.binding.subspan layout(#pipeline_layout) binding(0) alignment(64) offset(%c50872448) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<32x16x16384xf16>>
    %3 = hal.interface.binding.subspan layout(#pipeline_layout) binding(1) alignment(64) offset(%c0) flags(ReadOnly) : !iree_tensor_ext.dispatch.tensor<readonly:tensor<32x16xf16>>
    %4 = hal.interface.binding.subspan layout(#pipeline_layout) binding(2) alignment(64) offset(%c0) flags(ReadOnly) : !iree_tensor_ext.dispatch.tensor<readonly:tensor<32x16xf16>>
    %5 = hal.interface.binding.subspan layout(#pipeline_layout) binding(3) alignment(64) offset(%c128) flags(Indirect) : !iree_tensor_ext.dispatch.tensor<writeonly:tensor<16384x32x16xf16>>
    %6 = iree_tensor_ext.dispatch.tensor.load %0, offsets = [0, 0], sizes = [32, 262144], strides = [1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<32x262144xf16>> -> tensor<32x262144xf16>
    %7 = iree_tensor_ext.dispatch.tensor.load %1, offsets = [0], sizes = [32], strides = [1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<32xf32>> -> tensor<32xf32>
    %8 = iree_tensor_ext.dispatch.tensor.load %2, offsets = [0, 0, 0], sizes = [32, 16, 16384], strides = [1, 1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<32x16x16384xf16>> -> tensor<32x16x16384xf16>
    %9 = iree_tensor_ext.dispatch.tensor.load %3, offsets = [0, 0], sizes = [32, 16], strides = [1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<32x16xf16>> -> tensor<32x16xf16>
    %10 = iree_tensor_ext.dispatch.tensor.load %4, offsets = [0, 0], sizes = [32, 16], strides = [1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<32x16xf16>> -> tensor<32x16xf16>
    %11 = tensor.empty() : tensor<16384x32x16xf16>
    %12 = tensor.empty() : tensor<32xf32>
    %13 = linalg.fill ins(%cst : f32) outs(%12 : tensor<32xf32>) -> tensor<32xf32>
    %14 = linalg.generic {indexing_maps = [#map, #map1, #map1], iterator_types = ["parallel", "reduction"]} ins(%6, %7 : tensor<32x262144xf16>, tensor<32xf32>) outs(%13 : tensor<32xf32>) {
    ^bb0(%in: f16, %in_2: f32, %out: f32):
      %16 = arith.extf %in : f16 to f32
      %17 = arith.subf %16, %in_2 : f32
      %18 = arith.mulf %17, %17 : f32
      %19 = arith.addf %18, %out : f32
      linalg.yield %19 : f32
    } -> tensor<32xf32>
    %15 = linalg.generic {indexing_maps = [#map2, #map3, #map3, #map4, #map4, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%8, %7, %14, %9, %10 : tensor<32x16x16384xf16>, tensor<32xf32>, tensor<32xf32>, tensor<32x16xf16>, tensor<32x16xf16>) outs(%11 : tensor<16384x32x16xf16>) {
    ^bb0(%in: f16, %in_2: f32, %in_3: f32, %in_4: f16, %in_5: f16, %out: f16):
      %16 = arith.divf %in_3, %cst_0 : f32
      %17 = arith.addf %16, %cst_1 : f32
      %18 = math.rsqrt %17 : f32
      %19 = arith.extf %in : f16 to f32
      %20 = arith.subf %19, %in_2 : f32
      %21 = arith.mulf %20, %18 : f32
      %22 = arith.extf %in_4 : f16 to f32
      %23 = arith.mulf %21, %22 : f32
      %24 = arith.extf %in_5 : f16 to f32
      %25 = arith.addf %23, %24 : f32
      %26 = arith.truncf %25 : f32 to f16
      linalg.yield %26 : f16
    } -> tensor<16384x32x16xf16>
    iree_tensor_ext.dispatch.tensor.store %15, %5, offsets = [0, 0, 0], sizes = [16384, 32, 16], strides = [1, 1, 1] : tensor<16384x32x16xf16> -> !iree_tensor_ext.dispatch.tensor<writeonly:tensor<16384x32x16xf16>>
    return
  }
}
```

It sets `vector_common_parallel = [4, 0, 4], vector_inner_parallel = [0, 1, 0]` config to `%15`, where it should be something like `vector_common_parallel = [4, 0, 0], vector_inner_parallel = [0, 1, 4]`.

It is likely that the transposed result indexing map is not taken into account. I haven't taken a deeper look yet, so it needs to be confirmed.

### LINKED ISSUE #21643: One or more operations with large vector sizes (32768 bytes) were found
```
hal.executable public @main_graph$async_dispatch_9 {
  hal.executable.variant public @embedded_elf_x86_64 target(<"llvm-cpu", "embedded-elf-x86_64", {cpu = "znver4", cpu_features = "+prfchw,-cldemote,+avx,+aes,+sahf,+pclmul,-xop,+crc32,-amx-fp8,+xsaves,-avx512fp16,-usermsr,-sm4,-egpr,+sse4.1,+avx512ifma,+xsave,+sse4.2,-tsxldtrk,-sm3,-ptwrite,-widekl,-movrs,+invpcid,+64bit,+xsavec,-avx10.1-512,+avx512vpopcntdq,+cmov,-avx512vp2intersect,+avx512cd,+movbe,-avxvnniint8,-ccmp,-amx-int8,-kl,-avx10.1-256,+evex512,-avxvnni,-rtm,+adx,+avx2,-hreset,-movdiri,-serialize,-sha512,+vpclmulqdq,+avx512vl,-uintr,-cf,+clflushopt,-raoint,-cmpccxadd,+bmi,-amx-tile,+sse,-avx10.2-256,+gfni,-avxvnniint16,-amx-fp16,-zu,-ndd,+xsaveopt,+rdrnd,+avx512f,-amx-bf16,+avx512bf16,+avx512vnni,-push2pop2,+cx8,+avx512bw,+sse3,+pku,-nf,-amx-tf32,-amx-avx512,+fsgsbase,+clzero,+mwaitx,-lwp,+lzcnt,+sha,-movdir64b,-ppx,+wbnoinvd,-enqcmd,-amx-transpose,-avx10.2-512,-avxneconvert,-tbm,-pconfig,-amx-complex,+ssse3,+cx16,+bmi2,+fma,+popcnt,-avxifma,+f16c,+avx512bitalg,+rdpru,+clwb,+mmx,+sse2,+rdseed,+avx512vbmi2,-prefetchi,-amx-movrs,+rdpid,-fma4,+avx512vbmi,+shstk,+vaes,-waitpkg,-sgx,+fxsr,+avx512dq,+sse4a", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128", iree.encoding.resolver = #iree_cpu.cpu_encoding_resolver<>, max_stack_allocation_size = 32768 : i64, native_vector_size = 64 : i64, target_triple = "x86_64-unknown-unknown-eabi-elf"}>) {
    hal.executable.export public @main_graph$async_dispatch_9_reduction_16x3x256x32_f32_pack ordinal(0) layout(#hal.pipeline.layout<constants = 1, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) count(%arg0: !hal.device) -> (index, index, index) {
      %x, %y, %z = iree_tensor_ext.dispatch.workgroup_count_from_slice
      hal.return %x, %y, %z : index, index, index
    }
    builtin.module {
      func.func @main_graph$async_dispatch_9_reduction_16x3x256x32_f32_pack() {
        %c2_i64 = arith.constant 2 : i64
        %cst = arith.constant 9.99999996E-13 : f32
        %cst_0 = arith.constant 5.000000e-01 : f32
        %cst_1 = arith.constant 0.000000e+00 : f32
        %c3145728 = arith.constant 3145728 : index
        %0 = hal.interface.constant.load layout(<constants = 1, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) ordinal(0) : i32
        %1 = arith.index_castui %0 : i32 to index
        %2 = util.assume.int %1[<umin = 9633792, umax = 9633792, udiv = 9633792>, <umin = 11206656, umax = 11206656, udiv = 11206656>] : index
        %3 = hal.interface.binding.subspan layout(<constants = 1, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%2) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<3x16x3x256x32xf32>>
        %4 = hal.interface.binding.subspan layout(<constants = 1, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(1) alignment(64) offset(%c3145728) flags(Indirect) : !iree_tensor_ext.dispatch.tensor<writeonly:tensor<16x3x16x32x16x1xf32>>
        %5 = tensor.empty() : tensor<16x3x16x32x16x1xf32>
        %6 = tensor.empty() : tensor<16x3x32x256xf32>
        %7 = tensor.empty() : tensor<16x3x256xf32>
        %8 = iree_tensor_ext.dispatch.tensor.load %3, offsets = [1, 0, 0, 0, 0], sizes = [1, 16, 3, 256, 32], strides = [1, 1, 1, 1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<3x16x3x256x32xf32>> -> tensor<16x3x256x32xf32>
        %9 = linalg.fill ins(%cst_1 : f32) outs(%7 : tensor<16x3x256xf32>) -> tensor<16x3x256xf32>
        %10 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel", "reduction"]} ins(%8 : tensor<16x3x256x32xf32>) outs(%9 : tensor<16x3x256xf32>) {
        ^bb0(%in: f32, %out: f32):
          %12 = math.absf %in : f32
          %13 = math.fpowi %12, %c2_i64 : f32, i64
          %14 = arith.addf %13, %out : f32
          linalg.yield %14 : f32
        } -> tensor<16x3x256xf32>
        %11 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d3, d2)>], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%8, %10 : tensor<16x3x256x32xf32>, tensor<16x3x256xf32>) outs(%6 : tensor<16x3x32x256xf32>) {
        ^bb0(%in: f32, %in_2: f32, %out: f32):
          %12 = math.powf %in_2, %cst_0 : f32
          %13 = arith.cmpf ult, %12, %cst : f32
          %14 = arith.select %13, %cst, %12 : f32
          %15 = arith.divf %in, %14 : f32
          linalg.yield %15 : f32
        } -> tensor<16x3x32x256xf32>
        %pack = linalg.pack %11 outer_dims_perm = [0, 1, 3, 2] inner_dims_pos = [3, 2] inner_tiles = [16, 1] into %5 : tensor<16x3x32x256xf32> -> tensor<16x3x16x32x16x1xf32>
        iree_tensor_ext.dispatch.tensor.store %pack, %4, offsets = [0, 0, 0, 0, 0, 0], sizes = [16, 3, 16, 32, 16, 1], strides = [1, 1, 1, 1, 1, 1] : tensor<16x3x16x32x16x1xf32> -> !iree_tensor_ext.dispatch.tensor<writeonly:tensor<16x3x16x32x16x1xf32>>
        return
      }
    }
  }
}
```

above IR gives error as:

```
error: One or more operations with large vector sizes (32768 bytes) were found:

      func.func @main_graph$async_dispatch_9_reduction_16x3x256x32_f32_pack() {
      ^
test_mlir.mlir:39:17: note:   %14 = vector.transfer_read %11[%c0, %c0, %c0, %13], %cst_4 {in_bounds = [true, true, true, true]} : tensor<8x3x32x32xf32>, vector<8x3x32x16xf32>

```

How to reproduce the error?

Run :
iree-compile test.mlir --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-target-cpu=host -o compiled_model.vmfb

### PR DESCRIPTION
**Pull request by Yu-Zhewen**
This adds `IterationDimTracker` to determine dimension mappings both within individual operations and across multiple operations. 

The tracker assigns a global dimension index to all loop dimensions encountered (where “local” refers to an individual operation and “global” refers to all target operations). By analyzing producer-consumer relationships of SSA values, dimensions that are considered equivalent are assigned the same global dimension index.

It is currently used to improve lowering configuration propagation by identifying loop dimensions that are common across all target operations.

### CODE REVIEW

**Comment by hanhanW** [comment]
Thanks @Yu-Zhewen, I'll take a look. Meanwhile, can you check if the PR also fixes https://github.com/iree-org/iree/pull/21649?

I think it is the case that you're looking at with a pack consumer op.

**Review by hanhanW — CHANGES_REQUESTED** [review]
Thanks for the nice work! The prototype is good, but we can isolate the `rootOp` concept from the class. Then it can be more useful in other places. The `rootOp` is not important in the concept; we can rename the class as `IterationDimTracker`.

The other point is that we will need to track the dimensions for consumers, so it is better to make it general.

High-level comments:

- Move `mlir::computeTopologicalSorting` to initializer; we can construct the dimension mapping in the initializer. The [basic rule](https://google.github.io/styleguide/cppguide.html#Doing_Work_in_Constructors) is avoiding initialization that can fail if you can't signal an error.
- Update the `isCommonDim` to `isCommonDim(opA, dimA, opB, dimB)` that return true if the given dimension `dimA` in `opA` and `dimB` in `opB` is the same dimension loop.

Likely, we'll need a few private member like:
- `llvm::EquivalenceClasses<unsigned> indicesEquivalence`
- `llvm::SmallDenseMap<Operation *, std::pair<unsigned, unsigned> opDimRange`

Then the new `isCommonDim` method can query if they are in the same group or not.

The other comment is that we can create three private methods and use them in the `TypeSwitch` case, because we prefer small and focused functions; it is a reasonable split. https://google.github.io/styleguide/cppguide.html#Write_Short_Functions

-----

Let me mirror the offline discussion here, and we will need to document the algorithm in the implementation.

```mlir
%6 = linalg.fill ins(%c0_i32 : i32) outs(%4 : tensor<1024xi32>) -> tensor<1024xi32>
%7 = linalg.fill ins(%cst : f32) outs(%5 : tensor<1024xf32>) -> tensor<1024xf32>
%8:2 = linalg.generic {indexing_maps = [#map2, #map3, #map3], iterator_types =   ["parallel", "reduction"]} ins(%3 : tensor<1024x128xf32>) outs(%7, %6 :  tensor<1024xf32>, tensor<1024xi32>) attrs =  {lowering_config = #config}
```

- We log the dimension for `%6`, say `dim[0]`.
- We log the dimension for `%7`, say `dim[1]`.
- There are four dimensions in %8. I think `#map3` is something like `(d0, d1, d2, d3) -> (d3)`. So we log the dimensions like `dim[2]` , `dim[3]`, `dim[4]`, `dim[5]`.
Let's ignore complex result dims for now, i.e., we don't process all the result dimensions in `%3`.
- Looking at the first inits, i.e., `%7`, you can query `(%7, d_i) = dim[1]` from the method, where `d_i` is the `i`-th result dimension in `#map3`. The information we get here is that `dim[1]` ties to `dim[5]`. So you can union `dim[1]` and `dim[5]`.
- Do the same thing for `%6`. We can union `dim[0]` and `dim[5]`.

After the processing, there are four groups in total: `{dim[0], dim[1], dim[5]}, {dim[2]}, {dim[3]}, {dim[4]}`.

**Comment by Yu-Zhewen** [comment]
> Thanks @Yu-Zhewen, I'll take a look. Meanwhile, can you check if the PR also fixes #21649?
> 
> I think it is the case that you're looking at with a pack consumer op.

Which issue are you referring to? It looks like you accidentally quoted this PR instead of the issue number.

**Comment by Yu-Zhewen** [comment]
> The prototype is good, but we can isolate the rootOp concept from the class. Then it can be more useful in other places. The rootOp is not important in the concept; we can rename the class as IterationDimTracker.

Done.

> Move mlir::computeTopologicalSorting to initializer; we can construct the dimension mapping in the initializer. The [basic rule](https://google.github.io/styleguide/cppguide.html#Doing_Work_in_Constructors) is avoiding initialization that can fail if you can't signal an error.

I realized that previously `buildDimMapping` always returned success, so I’ve updated it to return void and moved it together with `computeTopologicalSorting` into the initializer.

> Update the isCommonDim to isCommonDim(opA, dimA, opB, dimB) that return true if the given dimension dimA in opA and dimB in opB is the same dimension loop.

I believe we are talking about two different functions here:
- `func1`: Checks if a given dimension dimA in opA and dimB in opB correspond to the same dimension loop.
- `func2`: Checks if dimA in opA is present in all other operations (regardless of its exact position in those operations).

So far, I have only implemented `func2`, as it’s the one used in this PR to fix splitting parallel vector tile sizes into common parts and op-specific parts.

For  `func1`, the implementation should be straightforward. Since I introduced the concept of `operationToGlobalDimMaps`,  which maps equivalent dimensions to the same global dimension index, we can simply compare `operationToGlobalDimMaps[opA][dimA] == operationToGlobalDimMaps[opB][dimB]`.

I haven’t added `func1` to this PR because it’s not used yet, but I’m happy to include it when needed.

**Comment by hanhanW** [comment]
> > Thanks @Yu-Zhewen, I'll take a look. Meanwhile, can you check if the PR also fixes #21649?
> > I think it is the case that you're looking at with a pack consumer op.
> 
> Which issue are you referring to? It looks like you accidentally quoted this PR instead of the issue number.

Sorry, my bad. I'm referring to https://github.com/iree-org/iree/issues/21643

**Comment by Yu-Zhewen** [comment]
> > > Thanks @Yu-Zhewen, I'll take a look. Meanwhile, can you check if the PR also fixes #21649?
> > > I think it is the case that you're looking at with a pack consumer op.
> > 
> > 
> > Which issue are you referring to? It looks like you accidentally quoted this PR instead of the issue number.
> 
> Sorry, my bad. I'm referring to #21643

Confirmed that #21643 is also fixed by this PR

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 1]
```diff
@@ -1067,6 +1070,192 @@ class LoweringConfigGenerator {
...
+class IterationDimTracker {
+public:
+  explicit IterationDimTracker(ArrayRef<Operation *> operations)
+      : operations(operations.begin(), operations.end()) {
+    // Ensure operations are processed in topological order.
+    mlir::computeTopologicalSorting(this->operations);
+    buildDimMapping();
+  }
+
+  /// Checks if the given dimension is common across all operations.
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]:
```suggestion
  /// Returns true if the given dimension of `op` is common across all operations.
```

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 2]
```diff
@@ -1067,6 +1070,192 @@ class LoweringConfigGenerator {
...
+      auto tilingOp = cast<TilingInterface>(op);
+      unsigned numLoops = tilingOp.getLoopIteratorTypes().size();
+      // Assign new global indices for this op.
+      for (unsigned end = totalLoopNum + numLoops; totalLoopNum < end;
+           ++totalLoopNum) {
+        indicesEquivalence.insert(totalLoopNum);
+        operationToGlobalDimMaps[op].push_back(totalLoopNum);
+      }
+      // Unify the global dimension indices by using the
+      // producer-consumer relationship of the SSA values.
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: The comment can be formatted a bit:

```suggestion
      // Unify the global dimension indices by using the producer-consumer
      // relationship of the SSA values.
```

We can add few implementation details like below, and it explains the algorithm. What I'm looking for is having a single place to explain the algorithm. The current documentation of `propagateOn*` functions do not have to elaborate part of the algorithm, IMO. Instead, they can focus on what they are doing as a function unit. I took a stab at writing the algorith, please take a look and help polish it. Thanks!

```
The dimensions are tracked with topological order, which means that all the producer's dimension indices are already unified. Now we can unify the global dimension indices by using producer-consumer relationship of the SSA values.
- For any operation that implements `IndexingMapOpInterface`, they can tie the dimensions by iterating indexing maps.
- For pack and unpack ops, an identity mapping can be used because tiling is applied to the outer (unpacked) dimensions.
- For the rest of unknown ops, we assume an identity  mapping from any value whose rank matches the operation's loop number.
```

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 3]
```diff
@@ -1067,6 +1070,192 @@ class LoweringConfigGenerator {
...
+      if (numLoops == cast<ShapedType>(result.getType()).getRank()) {
+        valueToGlobalDimMaps[result] = operationToGlobalDimMaps[op];
+      }
+    }
+  }
+
+  SmallVector<Operation *> operations;
+  // Tracks the total number of unique loop dimensions among the given set of
+  // operations.
+  unsigned totalLoopNum = 0;
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: This can be a local variable in `buildDimMapping`

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 4]
```diff
@@ -1067,6 +1070,192 @@ class LoweringConfigGenerator {
...
+
+    for (Operation *op : operations) {
+      auto tilingOp = cast<TilingInterface>(op);
+      unsigned numLoops = tilingOp.getLoopIteratorTypes().size();
+      // Assign new global indices for this op.
+      for (unsigned end = totalLoopNum + numLoops; totalLoopNum < end;
+           ++totalLoopNum) {
+        indicesEquivalence.insert(totalLoopNum);
+        operationToGlobalDimMaps[op].push_back(totalLoopNum);
+      }
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: optional: I'd iterate it like below, because it is more readable. People don't need to think why `totalLoopNum` is used.

```
for (unsigned i = 0; i < numLoops; ++i) {
  unsigned dim = totalLoopNum++;
  indicesEquivalence.insert(dim);
  operationToGlobalDimMaps[op].push_back(dim);
}
```

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 5]
```diff
@@ -1067,6 +1070,192 @@ class LoweringConfigGenerator {
...
+      replaceMap1[tempDimIndex] = totalLoopNum;
+      tempDimIndex++;
+      totalLoopNum++;
+    }
+    applyReplaceMap(replaceMap0);
+    applyReplaceMap(replaceMap1);
+  }
+
+  /// For IndexingMapOpInterface, use its indexing maps for
+  /// propagation.
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: nit: we can have better function comments: https://google.github.io/styleguide/cppguide.html#Function_Comments

Ties the dimensions based on indexing maps, if the result dim expr is an AffineDimExpr.
The complex result dim expr is ignored because it is not within the loop concept. It describes what the indices are in the innermost loop body, but it does not provide the information of which loop dimensions are tied.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 6]
```diff
@@ -1067,6 +1070,192 @@ class LoweringConfigGenerator {
...
+          if (auto dimExpr = dyn_cast<AffineDimExpr>(expr);
+              dimExpr && dim < valueToGlobalDimMaps[value].size()) {
+            unsigned pos = dimExpr.getPosition();
+            indicesEquivalence.unionSets(valueToGlobalDimMaps[value][dim],
+                                         operationToGlobalDimMaps[op][pos]);
+          }
+        }
+      }
+    }
+    auto dsOp = cast<DestinationStyleOpInterface>(op);
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: You are right that we can assume that all the indexing map ops implement DPS interface. It they don't implement the interface, the future proper fix is to bail out the case.

In the implementation, you can iterate on `dpsOp.getDpsInputOperands()` and `dpsOpgetDpsInitsMutable()` that returns a list of `OpOperand`; then you can use [getMatchingIndexingMap](https://github.com/llvm/llvm-project/blob/d0ee82040cb22ae38c92eb83b0c9ae71ca51a517/mlir/include/mlir/Interfaces/IndexingMapOpInterface.td#L47-L61), which is safer.

https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Interfaces/DestinationStyleOpInterface.td

style nit: prefer early-exit to simplify the code: https://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code

So something like:

```cpp
if (!valueToGlobalDimMaps.contains(value)) {
  continue;
}
// ...
auto dimExpr = dyn_cast<AffineDimExpr>(expr);
if (!dimExpr) {
  LDBG() << "....."; // optional
  continue;
}
// The rest of the work.
```

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 7]
```diff
@@ -1067,6 +1070,192 @@ class LoweringConfigGenerator {
...
+    for (auto [offset, result] : llvm::enumerate(indexingMapOp->getResults())) {
+      AffineMap map = indexingMapOp.getIndexingMapsArray()[numInputs + offset];
+      for (AffineExpr expr : map.getResults()) {
+        if (auto dimExpr = dyn_cast<AffineDimExpr>(expr)) {
+          unsigned pos = dimExpr.getPosition();
+          valueToGlobalDimMaps[result].push_back(
+              operationToGlobalDimMaps[op][pos]);
+        }
+      }
+    }
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: ditto: you should use the DPS method to get `OpOperand` (for inits), and query the corresponding indexing map.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 8]
```diff
@@ -1067,6 +1070,192 @@ class LoweringConfigGenerator {
...
+        for (unsigned i = 0; i < outDimSize; ++i) {
+          indicesEquivalence.unionSets(valueToGlobalDimMaps[value][i],
+                                       operationToGlobalDimMaps[op][i]);
+        }
+      }
+    }
+    for (Value result : op->getResults()) {
+      valueToGlobalDimMaps[result] = operationToGlobalDimMaps[op];
+    }
+  }
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: Please refresh the comment a bit, something like: `Ties the dimensions of pack and unpack operations with their operands in unpacked domain.....`

Can we make `numLoops` be `int64_t` type, so we don't need casting? The `getRank` returns `int64_t` types; I think it is quite common in the codebase.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 9]
```diff
@@ -1067,6 +1070,192 @@ class LoweringConfigGenerator {
...
+
+  /// For other operations, assume an identity
+  /// mapping from any value whose rank matches the operation's loop
+  /// number.
+  void propagateOnDefaultOp(
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: ditto:

- Format and refresh the comment a bit.
- Use early-exit in the `valueToGlobaDimMaps.contains(...)`.
- I'd rename it to `propagateOnUnknownOp`, which is clearer than default.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 10]
```diff
@@ -1067,6 +1070,192 @@ class LoweringConfigGenerator {
...
+  /// Checks if the given dimension is common across all operations.
+  bool isCommonDim(Operation *op, unsigned pos) {
+    unsigned dim = operationToGlobalDimMaps[op][pos];
+    for (auto &[_, dims] : operationToGlobalDimMaps) {
+      if (!llvm::is_contained(dims, dim)) {
+        return false;
+      }
+    }
+    return true;
+  }
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: I'd add an assertion, because the error message is more readable. Otherwise, it initializes an empty list and triggers an assertion when it accesses the `pos`-th element in the empty list.

```
assert(operationToGlobalDimMaps.contains(op));
```

btw, I think we can add `[[maybe_unused]]` in front of `auto` because `_` is not used and there may be warnings in debug build.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 11]
```diff
@@ -1067,6 +1070,192 @@ class LoweringConfigGenerator {
...
+      for (auto mit = indicesEquivalence.member_begin(**it);
+           mit != indicesEquivalence.member_end(); ++mit) {
+        replaceMap0[*mit] = tempDimIndex;
+      }
+      replaceMap1[tempDimIndex] = totalLoopNum;
+      tempDimIndex++;
+      totalLoopNum++;
+    }
+    applyReplaceMap(replaceMap0);
+    applyReplaceMap(replaceMap1);
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: IIUC, it remaps the range to `[0, numDims)`? I think we drop the code because it does not matter in terms of functionality. It makes the visualization better indeed, but it is not required.

If the intention is helping debug, I think you can move it to a separate function and use `std::once_flag` feature. E.g.,

https://github.com/iree-org/iree/blob/7ae61af936b4e7a649fa0ccf159c61b6d724c176/compiler/src/iree/compiler/Dialect/HAL/Target/TargetRegistry.h#L33-L42

Furthermore, you can implement a printer for it; call the method in the printer. E.g., `void print(llvm::raw_ostream &os)`. The example usage would be `dimTracker.print(llvm::dbgs())`. It is optional, just in case if it is helpful. In the printer, you can print the operation (without regions) and the mapped global dims.

(The example of print without region is `computeOp->print(llvm::dbgs(), OpPrintingFlags().skipRegions());`)

**Review by hanhanW — CHANGES_REQUESTED** [review]
Thanks, it is going to be awesome!

**Comment by hanhanW** [comment]
@Yu-Zhewen please also add some context to PR description.

https://google.github.io/eng-practices/review/developer/cl-descriptions.html

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp (hunk 3 above)
Comment (Yu-Zhewen) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: Not in this PR, but I plan to use it to replace `maxLoopNums` in the future.
https://github.com/iree-org/iree/blob/7ae61af936b4e7a649fa0ccf159c61b6d724c176/compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp#L2972-L2986

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp (hunk 11 above)
Comment (Yu-Zhewen) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: There are two remaps here, each serving a different purpose.
- First remap (unification): For example, `{dim[0], dim[1], dim[5]}, {dim[2]}, {dim[3]}, {dim[4]} ->{dim[6], dim[6], dim[6]}, {dim[7]}, {dim[8]}, {dim[9]}` . This lets us avoid further using `llvm::EquivalenceClasses` and instead directly query `operationToGlobalDimMaps[opA][dimA] == operationToGlobalDimMaps[opB][dimB]` to check if the dimensions are pointing to the same. I think this is useful on its own and could potentially make the code more efficient.
- Second remap (normalization):  Currently, it just remaps the range to [0, numDims) and serves no functional purpose. However, it could be useful in the future, by simplifying indexing into a shared `tileSizes` vector for the multi-lowering case.

Let me know if you think it's better leaving them out this PR.

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: I see. Technically, it does not make the code more efficient that much. Because the query (i.e., `getLeader()`) takes `O(α(n))`, which is very close to `O(1)` in practice. Although LLVM does not implement all the optimization technique, it is still fast. IIRC, it only implements path compression, but not union by rank. It makes the state cleaner, which is okay to me.

**Review by hanhanW — APPROVED** [review]
