### PR TITLE
[spirv] Fix transfer op crash when vectorizing memref 

### LINKED ISSUE #14973: `SPIRVVectorizeLoadStore` error with https://github.com/openxla/iree/pull/14656
PR #14656 seems to be hitting an issue with `SPIRVVectorizeLoadStore`. The initial error was happening on this IR

```
module {
  func.func @forward_dispatch_120_generic_32x10x1024_f32() {
    %cst = arith.constant dense<1.024000e+04> : vector<2xf32>
    %cst_0 = arith.constant dense<0.000000e+00> : vector<1x4xf32>
    %c1_i32 = arith.constant 1 : i32
    %c32_i32 = arith.constant 32 : i32
    %c2_i32 = arith.constant 2 : i32
    %c4_i32 = arith.constant 4 : i32
    %c8_i32 = arith.constant 8 : i32
    %c16_i32 = arith.constant 16 : i32
    %c32 = arith.constant 32 : index
    %c0 = arith.constant 0 : index
    %c15 = arith.constant 15 : index
    %c0_i32 = arith.constant 0 : i32
    %c8982592 = arith.constant 8982592 : index
    %c7671872 = arith.constant 7671872 : index
    %c6361152 = arith.constant 6361152 : index
    %c2 = arith.constant 2 : index
    %c10 = arith.constant 10 : index
    %cst_1 = arith.constant 0.000000e+00 : f32
    %0 = gpu.thread_id  x
    %1 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c6361152) flags(ReadOnly) : memref<32x10x1024xf32, strided<[10240, 1024, 1], offset: 1590288>, #hal.descriptor_type<storage_buffer>>
    memref.assume_alignment %1, 64 : memref<32x10x1024xf32, strided<[10240, 1024, 1], offset: 1590288>, #hal.descriptor_type<storage_buffer>>
    %2 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c7671872) : memref<32x10x1024xf32, strided<[10240, 1024, 1], offset: 1917968>, #hal.descriptor_type<storage_buffer>>
    memref.assume_alignment %2, 64 : memref<32x10x1024xf32, strided<[10240, 1024, 1], offset: 1917968>, #hal.descriptor_type<storage_buffer>>
    %workgroup_id_x = hal.interface.workgroup.id[0] : index
    %3 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%c8982592) : memref<32x10x1024xf32, strided<[10240, 1024, 1], offset: 2245648>, #hal.descriptor_type<storage_buffer>>
    memref.assume_alignment %3, 64 : memref<32x10x1024xf32, strided<[10240, 1024, 1], offset: 2245648>, #hal.descriptor_type<storage_buffer>>
    %4 = affine.apply affine_map<()[s0] -> (s0 * 4 - (s0 floordiv 256) * 1024)>()[%0]
    %5 = scf.for %arg0 = %c0 to %c10 step %c2 iter_args(%arg1 = %cst_0) -> (vector<1x4xf32>) {
      %26 = affine.apply affine_map<(d0)[s0] -> (d0 + s0 floordiv 256)>(%arg0)[%0]
      %27 = vector.transfer_read %1[%workgroup_id_x, %26, %4], %cst_1 {in_bounds = [true]} : memref<32x10x1024xf32, strided<[10240, 1024, 1], offset: 1590288>, #hal.descriptor_type<storage_buffer>>, vector<4xf32>
      %28 = vector.extract %arg1[0] : vector<1x4xf32>
      %29 = arith.addf %27, %28 : vector<4xf32>
      %30 = vector.broadcast %29 : vector<4xf32> to vector<1x4xf32>
      scf.yield %30 : vector<1x4xf32>
    }
    %6 = vector.shape_cast %5 : vector<1x4xf32> to vector<4xf32>
    %7 = vector.reduction <add>, %6 : vector<4xf32> into f32
    %shuffleResult, %valid = gpu.shuffle  xor %7, %c1_i32, %c32_i32 : f32
    %8 = arith.addf %7, %shuffleResult : f32
    %shuffleResult_2, %valid_3 = gpu.shuffle  xor %8, %c2_i32, %c32_i32 : f32
    %9 = arith.addf %8, %shuffleResult_2 : f32
    %shuffleResult_4, %valid_5 = gpu.shuffle  xor %9, %c4_i32, %c32_i32 : f32
    %10 = arith.addf %9, %shuffleResult_4 : f32
    %shuffleResult_6, %valid_7 = gpu.shuffle  xor %10, %c8_i32, %c32_i32 : f32
    %11 = arith.addf %10, %shuffleResult_6 : f32
    %shuffleResult_8, %valid_9 = gpu.shuffle  xor %11, %c16_i32, %c32_i32 : f32
    %12 = arith.addf %11, %shuffleResult_8 : f32
    %alloc = memref.alloc() : memref<16xf32, #gpu.address_space<workgroup>>
    %13 = arith.divui %0, %c32 : index
    %14 = arith.remui %0, %c32 : index
    %15 = arith.cmpi eq, %14, %c0 : index
    scf.if %15 {
      memref.store %12, %alloc[%13] : memref<16xf32, #gpu.address_space<workgroup>>
    }
    gpu.barrier
    %16 = arith.minui %14, %c15 : index
    %17 = memref.load %alloc[%16] : memref<16xf32, #gpu.address_space<workgroup>>
    %shuffleResult_10, %valid_11 = gpu.shuffle  xor %17, %c1_i32, %c32_i32 : f32
    %18 = arith.addf %17, %shuffleResult_10 : f32
    %shuffleResult_12, %valid_13 = gpu.shuffle  xor %18, %c2_i32, %c32_i32 : f32
    %19 = arith.addf %18, %shuffleResult_12 : f32
    %shuffleResult_14, %valid_15 = gpu.shuffle  xor %19, %c4_i32, %c32_i32 : f32
    %20 = arith.addf %19, %shuffleResult_14 : f32
    %shuffleResult_16, %valid_17 = gpu.shuffle  xor %20, %c8_i32, %c32_i32 : f32
    %21 = arith.addf %20, %shuffleResult_16 : f32
    %shuffleResult_18, %valid_19 = gpu.shuffle  idx %21, %c0_i32, %c32_i32 : f32
    %22 = arith.addf %shuffleResult_18, %cst_1 : f32
    %23 = vector.splat %22 : vector<2xf32>
    %24 = arith.divf %23, %cst : vector<2xf32>
    %25 = affine.apply affine_map<()[s0] -> (s0 * 2)>()[%0]
    scf.for %arg0 = %c0 to %c10 step %c2 {
      %26 = vector.transfer_read %1[%workgroup_id_x, %arg0, %25], %cst_1 {in_bounds = [true]} : memref<32x10x1024xf32, strided<[10240, 1024, 1], offset: 1590288>, #hal.descriptor_type<storage_buffer>>, vector<2xf32>
      %27 = affine.apply affine_map<(d0) -> (d0 + 1)>(%arg0)
      %28 = vector.transfer_read %1[%workgroup_id_x, %27, %25], %cst_1 {in_bounds = [true]} : memref<32x10x1024xf32, strided<[10240, 1024, 1], offset: 1590288>, #hal.descriptor_type<storage_buffer>>, vector<2xf32>
      %29 = arith.subf %26, %24 : vector<2xf32>
      %30 = arith.subf %28, %24 : vector<2xf32>
      vector.transfer_write %29, %2[%workgroup_id_x, %arg0, %25] {in_bounds = [true]} : vector<2xf32>, memref<32x10x1024xf32, strided<[10240, 1024, 1], offset: 1917968>, #hal.descriptor_type<storage_buffer>>
      vector.transfer_write %30, %2[%workgroup_id_x, %27, %25] {in_bounds = [true]} : vector<2xf32>, memref<32x10x1024xf32, strided<[10240, 1024, 1], offset: 1917968>, #hal.descriptor_type<storage_buffer>>
      %31 = arith.mulf %29, %29 : vector<2xf32>
      %32 = arith.mulf %30, %30 : vector<2xf32>
      vector.transfer_write %31, %3[%workgroup_id_x, %arg0, %25] {in_bounds = [true]} : vector<2xf32>, memref<32x10x1024xf32, strided<[10240, 1024, 1], offset: 2245648>, #hal.descriptor_type<storage_buffer>>
      vector.transfer_write %32, %3[%workgroup_id_x, %27, %25] {in_bounds = [true]} : vector<2xf32>, memref<32x10x1024xf32, strided<[10240, 1024, 1], offset: 2245648>, #hal.descriptor_type<storage_buffer>>
    }
    return
  }
}
```

Running this example with 

```
iree-opt --iree-spirv-vectorize-load-store pass_repro.mlir
```

throws this error

```
iree-opt: /data/mahesh/iree/iree/third_party/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:257: const T &llvm::ArrayRef<mlir::AffineExpr>::operator[](size_t) const [T = mlir::AffineExpr]: Assertion `Index < Length && "Invalid index!"' failed.
Please report issues to https://github.com/openxla/iree/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: /data/mahesh/iree/build/Debug/tools/iree-opt --iree-spirv-vectorize-load-store pass_repro.mlir
 #0 0x00007f683769acb6 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /data/mahesh/iree/iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:723:11
 #1 0x00007f683769b29b PrintStackTraceSignalHandler(void*) /data/mahesh/iree/iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:798:1
 #2 0x00007f6837698ed3 llvm::sys::RunSignalHandlers() /data/mahesh/iree/iree/third_party/llvm-project/llvm/lib/Support/Signals.cpp:105:5
 #3 0x00007f683769bb41 SignalHandler(int) /data/mahesh/iree/iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:413:1
 #4 0x00007f682d6644d0 (/usr/lib64/libc.so.6+0x384d0)
 #5 0x00007f682d6b20bc (/usr/lib64/libc.so.6+0x860bc)
 #6 0x00007f682d664432 raise (/usr/lib64/libc.so.6+0x38432)
 #7 0x00007f682d64e4b2 abort (/usr/lib64/libc.so.6+0x224b2)
 #8 0x00007f682d64e3d5 (/usr/lib64/libc.so.6+0x223d5)
 #9 0x00007f682d65d362 (/usr/lib64/libc.so.6+0x31362)
#10 0x00007f6837708629 llvm::ArrayRef<mlir::AffineExpr>::operator[](unsigned long) const /data/mahesh/iree/iree/third_party/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:0:7
#11 0x00007f683771777b mlir::AffineMap::getResult(unsigned int) const /data/mahesh/iree/iree/third_party/llvm-project/mlir/lib/IR/AffineMap.cpp:355:10
#12 0x00007f6837717aa8 mlir::AffineMap::getDimPosition(unsigned int) const /data/mahesh/iree/iree/third_party/llvm-project/mlir/lib/IR/AffineMap.cpp:359:10
#13 0x00007f683ad12405 mlir::iree_compiler::(anonymous namespace)::ScalarizeVectorTransferRead::matchAndRewrite(mlir::vector::TransferReadOp, mlir::PatternRewriter&) const /data/mahesh/iree/iree/compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp:656:14
```

I made this ([link](https://github.com/openxla/iree/pull/14656/files#diff-0f37e60c03d9fcab811f0470c41dc5173d2fc844432ae46c34c2ffb0a5f81e21R650)) change that seemed to fix the error. But that is having more errors. I am not sure I understand enough of this pass to see whats happening.

### PR DESCRIPTION
**Pull request by antiagainst**
In the `SPIRVVectorizeLoadStore` pass, we try to use the smallest
vector as the new element type for vectorizing scalar memref types.
This means afterwards we can see transfer ops where we are reading
or writing a larger vector size, e.g., vector<4xf32> -> memref of
vector<2xf32>. Such cases would require us to unroll the vector
and perform read/write for its subparts.

Fixes https://github.com/openxla/iree/issues/14973

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp [hunk 1]
```diff
@@ -37,13 +37,17 @@ constexpr int kMaxVectorNumElements = 4;
 
 namespace mlir {
 namespace iree_compiler {
+namespace {
+
+//===----------------------------------------------------------------------===//
+// Utility Functions
+//===----------------------------------------------------------------------===//
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp]: nit: @benvanik and I had a discussion about this a few months ago and we converged on keeping functions static instead of moving them to anonymous namespaces. This is because it's easier to tell by just looking at the definition and more difficult to mess up when moving namespaces around. I believe this is also the state of things in mlir.

File: compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp [hunk 2]
```diff
@@ -292,7 +301,29 @@ class ProcessFunctionArgument final
 
   LogicalResult
   matchAndRewrite(func::FuncOp funcOp, OpAdaptor adaptor,
-                  ConversionPatternRewriter &rewriter) const override;
+                  ConversionPatternRewriter &rewriter) const override {
+    TypeConverter::SignatureConversion signatureConverter(
+        funcOp.getFunctionType().getNumInputs());
+    for (const auto &[index, arg] : llvm::enumerate(funcOp.getArguments())) {
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp]: No need for `const &` over enumerate -- it makes it seem like you can't modify `arg` but actually you can. And it's more typing.

File: compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp [hunk 3]
```diff
@@ -312,40 +343,88 @@ class ProcessTransferRead final
...
+    // If there is only two component vectors, we can use ShuffleOp, which is a
+    // bit simpler.
+    if (vectorCount == 2) {
+      SmallVector<int64_t> seqIndices =
+          llvm::to_vector(llvm::seq<int64_t>(readVectorType.getNumElements()));
+      auto ShuffleOp = rewriter.create<vector::ShuffleOp>(
+          loc, vectors[0], vectors[1], seqIndices);
+      rewriter.replaceOpWithNewOp<vector::BitCastOp>(read, readVectorType,
+                                                     ShuffleOp);
+      return success();
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp:416]: neat

File: compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp [hunk 4]
```diff
@@ -367,38 +446,70 @@ class ProcessTransferWrite final
...
+      offsets.back() = i * memrefVectorType.getNumElements();
+      auto slice = rewriter.create<vector::ExtractStridedSliceOp>(
+          loc, adaptor.getVector(), offsets, sizes, strides);
+      auto component =
+          rewriter.create<vector::BitCastOp>(loc, memrefVectorType, slice);
+      Value iVal = rewriter.create<arith::ConstantIndexOp>(loc, i);
+      indices->back() = rewriter.create<affine::AffineApplyOp>(
+          loc, addMap, ValueRange{oldIndex, iVal});
+      rewriter.create<memref::StoreOp>(loc, component, adaptor.getSource(),
+                                       *indices);
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp:512]: Do we have some preference when it comes to `vector` vs. `memref` `load`/`store`? Just curious.

File: compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp [hunk 5]
```diff
@@ -773,38 +891,27 @@ class SPIRVVectorizeLoadStorePass final
...
 void SPIRVVectorizeLoadStorePass::runOnOperation() {
   // Uses the signature conversion methodology of the dialect conversion
   // framework to implement the conversion.
   ModuleOp module = getOperation();
   MLIRContext *context = &getContext();
 
+  // Prior pass should have unrolled and broken down vectors with rank > 1.
+  for (func::FuncOp func : module.getOps<func::FuncOp>()) {
+    auto result = func.walk([](VectorTransferOpInterface transferOp) {
+      if (cast<VectorType>(transferOp.vector().getType()).getRank() > 1) {
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp]: nit: isn't there `getVectorType()` in this interface?

File: compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp (hunk 1 above)
Comment (antiagainst) [reply compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp]: I don't have a strong preference here; I was trying to silence the warnings from clang-tidy in the category of "misc-use-anonymous-namespace". Maybe we should copy the LLVM's `.clang-tidy` to IREE root so we inherit some configurations there.

Comment (antiagainst) [reply compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp]: Reverted back to the original form.

File: compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp (hunk 4 above)
Comment (antiagainst) [reply compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp:512]: `vector.load` performs vectorized load from a scalar-element-type memref. We don't have a direct correspondance in SPIR-V _in logical addressing mode_--In SPIR-V scalar-element-type memref translates to scalar-element-type runtime array. Access chains to it gives us pointers to scalar values; there is no way to get a pointer to a vector of arbiarty size there. OpBitcast the pointer might seems a way; but it's explicitly forbidden in logical addressing mode by excluded in the allowed op list in "2.16.1. Universal Validation Rules". (It might be actually supported by some drivers; though still ill semantics territory.) So that's why we have this pass entirely--trying to change the memref element type to vector type so we can use the basic `memref.load` to load vectors. It's a pain. Physical addressing mode makes this easier as we can do whatever with the pointers.

**Review by kuhar — APPROVED** [review]
