### PR TITLE
[hip] Skip HIP kernel execution when any workgroup size is zero.

### LINKED ISSUE #18834: [HIP] Dynamic inputs with zero elements cause `hipErrorInvalidConfiguration` when launching the kernel.
### What happened?

Running a module with dynamic sized inputs on HIP fails when the input passed has a dynamic dimension with size zero.

### Steps to reproduce your issue

1. Compile a module with a dynamic input.
<details>
<summary>add.mlir</summary>

```
func.func @main(%input : tensor<?xf32>) -> (tensor<?xf32>) {
  %result = arith.addf %input, %input : tensor<?xf32>
  return %result : tensor<?xf32>
}
```

</details>

```
iree-compile --iree-hal-target-backends=rocm --iree-hip-target=gfx1100 --iree-hip-bc-dir=$(pwd)/bitcode add.mlir -o add.vmfb
```

2. Run the module with a zero-sized input:
```
iree-run-module --device='hip://0' --module=add.vmfb --input='0xf32=1.1'
```

3. You should see an error like:
```
external/com_github_iree_org_iree/runtime/src/iree/hal/drivers/hip/event_semaphore.c:350: ABORTED; while calling import; while invoking native function hal.fence.await;
[ 0] bytecode module.main:634 add.mlir:2:13
      at add.mlir:1:1; invoking function 'main'; `sync func @main(%input0: tensor<?xf32>) -> (%output0: tensor<?xf32>)`
```

If I make the following patch:
<details> <summary>semaphore patch</summary>

```
diff --git a/runtime/src/iree/hal/drivers/hip/event_semaphore.c b/runtime/src/iree/hal/drivers/hip/event_semaphore.c
index 926eb54ce5..7b2a30e9fb 100644
--- a/runtime/src/iree/hal/drivers/hip/event_semaphore.c
+++ b/runtime/src/iree/hal/drivers/hip/event_semaphore.c
@@ -347,7 +347,8 @@ static iree_status_t iree_hal_hip_semaphore_wait(

   iree_slim_mutex_lock(&semaphore->mutex);
   if (semaphore->current_value == IREE_HAL_SEMAPHORE_FAILURE_VALUE) {
-    status = iree_make_status(IREE_STATUS_ABORTED);
+    status = iree_status_clone(semaphore->failure_status);
+    //status = iree_make_status(IREE_STATUS_ABORTED);
   }
   iree_slim_mutex_unlock(&semaphore->mutex);

```

</details>

Then I can see the actual error:
```
external/com_github_iree_org_iree/runtime/src/iree/hal/drivers/hip/stream_command_buffer.c:550: FAILED_PRECONDITION; HIP driver error 'hipErrorInvalidConfiguration' (9): invalid configuration argument; while invoking native function hal.fence.await; while calling import;
[ 0] bytecode module.main:634 add.mlir:2:13
      at add.mlir:1:1; invoking function 'main'; `sync func @main(%input0: tensor<?xf32>) -> (%output0: tensor<?xf32>)`
```

Looking into it more, one of the workgroup counts passed to `hipModuleLaunchKernel` on line 552 of stream_command_buffer.c, is zero which causes the invalid configuration error.

I have a PR out that just skips kernel execution when any of the workgroup counts are zero, but let me know if you think this should be handled differently, for example somehow elliding the dispatch call from the compiler when the workgroup count is zero.

### What component(s) does this issue relate to?

Runtime

### Version information

running off of main as of October 17, 2024.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JamesMBartlett**
This fixes `hipErrorInvalidConfiguration` errors when launching kernels with dynamic sized inputs when the dynamic size is zero.

See #18834 for more details.

Fixes #18834.

### CODE REVIEW

File: runtime/src/iree/hal/drivers/hip/stream_command_buffer.c [hunk 1]
```diff
@@ -478,6 +478,16 @@ static iree_status_t iree_hal_hip_stream_command_buffer_dispatch(
       z0, iree_hal_hip_native_executable_lookup_kernel_params(
               executable, entry_point, &kernel_params));
 
+  // If any of the workgroup counts/block dims are zero, we can skip execution
```
Comment (benvanik) [inline runtime/src/iree/hal/drivers/hip/stream_command_buffer.c]: the block dims will never be zero (or if they are, that should be checked when loading the executable) - you just need to check the workgroup count and can do it above before flushing collectives

**Review by benvanik — APPROVED** [review]
