### PR TITLE
[mlir][GPU] Make small reductions go down tile and fuse pipeline.

### LINKED ISSUE #21038: Dynamic dim issue for one_hot
### What happened?

Follow up on #21028.

MLIR is from tracing the following python code:
```
one_hot_expert_indices = F.one_hot(
    top_experts_index, num_classes=num_experts
).to(dtype=h.dtype, device=h.device)
weighted_scores = one_hot_expert_indices * expert_gate.unsqueeze(-1)
router_scores = weighted_scores.sum(dim=1).transpose(0, 1).T
```

The [failing mlir](https://github.com/user-attachments/files/20620580/one_hot_good.mlir.txt) produces incorrect numbers when compared to torch reference, [passing mlir](https://github.com/user-attachments/files/20620581/one_hot.mlir.txt) produces correct numbers.

### Steps to reproduce your issue

```
iree-compile case.mlir \
  -o=result.vmfb \
  --iree-hal-target-device=hip \
  --iree-hip-target=gfx942 \
  --iree-opt-level=O3 \
  --iree-hal-indirect-command-buffers=true \
  --iree-stream-resource-memory-model=discrete \
  --iree-hal-memoization=true
```

### What component(s) does this issue relate to?

_No response_

### Version information

`iree-3.5.0rc20250605` + #21036

### Additional context

_No response_

### LINKED ISSUE #21039: .sum() across dynamic dim produces incorrect results.
### What happened?

Both examples are from the following torch code:
```
num_experts = 4
num_tokens, input_feature_dim = h.shape

# (self.num_experts, num_tokens)
router_indices = (
    torch.arange(num_tokens)
    .view(1, -1)
    .expand(num_experts, -1)
)
# (self.num_experts * num_tokens, input_feature_dim)
router_indices = router_indices.reshape(-1, 1).expand(-1, input_feature_dim).to(dtype=torch.float)
return router_indices.view(num_experts, num_tokens, input_feature_dim).sum(
    dim=x
)
```

With the following dynamic shapes specified:
```
dynamic_shapes = {
    "ffn_input": {0: num_tokens}
}
```

If the dynamic dim is **not** specified it runs correctly, if it **is** specified it run correctly if `x=1` and inccorrectly if `x=0`.

[correct mlir](https://github.com/user-attachments/files/20636202/fail.mlir.txt)
[wrong mlir](https://github.com/user-attachments/files/20636203/pass.mlir.txt)

### Steps to reproduce your issue

```
iree-compile case.mlir \
  -o=result.vmfb \
  --iree-hal-target-device=hip \
  --iree-hip-target=gfx942 \
  --iree-opt-level=O3 \
  --iree-hal-indirect-command-buffers=true \
  --iree-stream-resource-memory-model=discrete \
  --iree-hal-memoization=true
```

### What component(s) does this issue relate to?

_No response_

### Version information

`iree-3.5.0rc20250605` + #21036

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
Small reductions already go down tile and fuse pipeline. The presence
of dynamic dimensions tripped up the kernel selection logic.

Fixes https://github.com/iree-org/iree/issues/21039, https://github.com/iree-org/iree/issues/21038

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 1]
```diff
@@ -2506,6 +2506,20 @@ setWarpReductionConfig(IREE::GPU::TargetAttr target,
 
   SmallVector<int64_t> workgroupTileSizes(op.getNumParallelLoops(), 1);
 
+  int64_t reductionSize = 1;
+  for (int64_t dim : reductionDims)
+    reductionSize *= bounds[dim];
```
Comment (benvanik) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2511]: is this safe? previously this was guarded by the dynamic dim count logic below

```
      for (unsigned dim : reductionDims) {
        if (ShapedType::isDynamic(bounds[dim])) {
```

may be needed here too so you don't end up with a negative size by multiplying by -1?

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2511]: https://github.com/iree-org/iree/pull/21063/files#diff-e491707653524e61bd22ba47ca5bd8414065b70bd1c6b85f45947929d7a49aafL2476 already checks that none of the reduction dimensions are dynamic. 
This all is going to be deleted soon anyway.

**Review by benvanik — APPROVED** [review]

**Comment by IanWood1** [comment]
@MaheshRavishankar this broke compilation for the reproducer in https://github.com/iree-org/iree/issues/21087. I can create a new issue for this if needed. Here is the [failing dispatch](https://gist.github.com/IanWood1/40ee4965a23a4eba4ff71794b52ee6bb)


```
error: 'vector.transfer_write' op write affecting operations on global resources are restricted to workgroup distributed contexts.
```
