### PR TITLE
[LLVMGPU] Track shared parallel dimensions better in reduction config

### LINKED ISSUE #22529: Batchnorm fails to compile
### What happened?

IR and dump: https://gist.github.com/rkayaith/6ade85cfc176a7a024fe2a03342c3dc4

```
$ iree-compile --iree-hal-target-backends=rocm --iree-hip-target=mi300x --iree-opt-level=O3 batchnorm.mlir
batchnorm.mlir:57:11: error: 'func.func' op failed to distribute
    %16 = linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["reduction", "parallel", "reduction", "reduction"]} ins(%15 : tensor<128x512x24x48xf64>) outs(%11 : tensor<1x512x1x1xf64>) {
          ^
batchnorm.mlir:57:11: note: see current operation: 
"func.func"() <{function_type = () -> (), sym_name = "fused_op__native_batch_norm_legit_functional_getitem_getitem_1_getitem_2_getitem_3_getitem_4_8cfb52a1793ae2bd6dcd4e3c6e9c12478b78ecdb_128x512x24x48xbfloat16_perm_0231_512xfloat32_512xfloat32_512xfloat32_512xfloat32$async_dispatch_0_reduction_512x147456_f32"}> ({
  %0 = "arith.constant"() <{value = dense<0.000000e+00> : vector<f32>}> : () -> vector<f32>
  %1 = "arith.constant"() <{value = dense<0.000000e+00> : vector<1x1x8xf32>}> : () -> vector<1x1x8xf32>
  %2 = "arith.constant"() <{value = dense<0.000000e+00> : vector<1x1x8xbf16>}> : () -> vector<1x1x8xbf16>
  %3 = "arith.constant"() <{value = dense<0.000000e+00> : vector<512x1x1x1x1x1xf32>}> : () -> vector<512x1x1x1x1x1xf32>
  %4 = "arith.constant"() <{value = 512 : index}> : () -> index
  ...
```

### What component(s) does this issue relate to?

Compiler

### Version information

1e2abb8c

### Additional context

BOO driver command `bnormbfp16 --batchsize 128 --in_channels 512 --in_h 24 --in_w 48 --time 1 --iter 100 --save 1 --run 1 --layout NHWC`

### PR DESCRIPTION
**Pull request by Groverkss**
This patch moves IterationDimTracker from Codegen/LLVMGPU/KernelDispatch.cpp to Codegen/Utils and uses it in reduction configuration. This allows us to map iteration space dimensions between different operations instead of assuming everything to be in a certain order.

Also adds a better reasoning for how we configure things and the assumptions we make. This makes it easier to understand the configuration logic as well.

Fixes https://github.com/iree-org/iree/issues/22529, https://github.com/iree-org/iree/issues/23951, https://github.com/iree-org/iree/issues/24008

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/Utils/SliceUtils.cpp [hunk 1]
```diff
@@ -0,0 +1,260 @@
...
+#include "mlir/IR/BuiltinTypeInterfaces.h"
+#include "mlir/Interfaces/DestinationStyleOpInterface.h"
+#include "mlir/Interfaces/IndexingMapOpInterface.h"
+#include "mlir/Interfaces/TilingInterface.h"
+
+namespace mlir::iree_compiler {
+
+//===----------------------------------------------------------------------===//
+// Propagation helpers (file-local)
+//===----------------------------------------------------------------------===//
```
Comment (sommerlukas) [inline compiler/src/iree/compiler/Codegen/Utils/SliceUtils.cpp:54]: What is the rationale to make these file-local helpers instead of private methods of the class? As far as I can see, it means that we now need to explicitly pass the map in instead of being able to access the member directly.

File: compiler/src/iree/compiler/Codegen/Utils/SliceUtils.cpp [hunk 2]
```diff
@@ -0,0 +1,260 @@
...
+  applyReplaceMap(replaceMap0);
+  applyReplaceMap(replaceMap1);
+}
+
+//===----------------------------------------------------------------------===//
+// getParallelGlobalDims
+//===----------------------------------------------------------------------===//
+
+DenseSet<int64_t> getParallelGlobalDims(const IterationDimTracker &tracker,
+                                        ArrayRef<Operation *> ops) {
```
Comment (sommerlukas) [inline compiler/src/iree/compiler/Codegen/Utils/SliceUtils.cpp]: Why is this not a member of `IterationDimTracker` or at least a static method on the class?

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ReductionConfigUtils.cpp [hunk 3]
```diff
@@ -217,21 +203,32 @@ static FailureOr<TileSizesConfig> getVectorDistributeReductionConfig(
   if (reductionDims.empty()) {
     SmallVector<int64_t> serialTileSizes(op.getNumLoops(), 1);
 
-    // For the shared wgp dimension, set the serial tile sizes to be zero.
-    for (const auto &[dim, tile_size] : sharedWgpTiles) {
-      serialTileSizes[dim] = 0;
+    // For dimensions that are being tiled on workgroups, do not tile them on
+    // the serial level.
+    for (auto [serialTile, wgpTile] :
```
Comment (sommerlukas) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ReductionConfigUtils.cpp:208]:
```suggestion
    for (auto& [serialTile, wgpTile] :
```

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ReductionConfigUtils.cpp [hunk 4]
```diff
@@ -415,12 +408,32 @@ populateConfigInfo(const llvm::SetVector<linalg::LinalgOp> &computeOps,
...
     if (failed(config)) {
       return failure();
     }
+
+    // Propagate any WG tile updates (e.g., from local split-k) back to
+    // wgTilePerDim.
+    for (auto [dim, tile] : llvm::enumerate(localWgpTiles)) {
+      int64_t gd = tracker.getGlobalDimIdx(linalgOp, dim);
+      if (wgTilePerDim.contains(gd) &&
+          static_cast<int64_t>(tile) > wgTilePerDim[gd]) {
```
Comment (sommerlukas) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ReductionConfigUtils.cpp]: Could we make `localWgpTiles` `int64_t` to avoid all the casting?

**Comment by hanhanW** [comment]
The `IterationDimTracker` is implemented and reviewed by @Yu-Zhewen and me. I'm happy to see that it is useful for other backends. @Yu-Zhewen can you help review?

File: compiler/src/iree/compiler/Codegen/Utils/SliceUtils.cpp (hunk 1 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/Utils/SliceUtils.cpp:54]: fixed

File: compiler/src/iree/compiler/Codegen/Utils/SliceUtils.cpp (hunk 2 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/Utils/SliceUtils.cpp]: removed method

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ReductionConfigUtils.cpp (hunk 3 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ReductionConfigUtils.cpp:208]: This is a compilation failure. auto on zip_equal is a reference automatically.

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ReductionConfigUtils.cpp [hunk 5]
```diff
@@ -339,31 +335,46 @@ static FailureOr<TileSizesConfig> getVectorDistributeReductionConfig(
...
+  // Build a tracker to track shared dimensions across the compute ops.
+  SmallVector<Operation *> ops(computeOps.begin(), computeOps.end());
+  IterationDimTracker tracker(ops);
+  // Tracker for minimum tile size required for shared parallel dimensions.
+  DenseMap<int64_t, int64_t> wgTilePerDim;
+  for (auto dim : llvm::seq<int64_t>(0, root.getNumLoops())) {
+    if (linalg::isParallelIterator(root.getIteratorTypesArray()[dim])) {
+      int64_t globalDim = tracker.getGlobalDimIdx(root, dim);
+      wgTilePerDim[globalDim] = 1;
+    }
```
Comment (sommerlukas) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ReductionConfigUtils.cpp:377]: Nit: Can't we just iterate over `root.getParallelDims()` here?

**Review by sommerlukas — APPROVED** [review]
LGTM, modulo one nit.

**Comment by Groverkss** [comment]
Test failures are fixed after https://github.com/iree-org/iree/pull/23991

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ReductionConfigUtils.cpp (hunk 5 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ReductionConfigUtils.cpp:377]: that function takes a smallvector as input and i didn't want to create another piece of allocation lying around that's all.

**Review by Yu-Zhewen — APPROVED** [review]
LGTM, thanks!
