### PR TITLE
[CPU][DT] Implement data layout propagation for CPU dispatches.

### LINKED ISSUE #21180: [CPU][DT] Failed to compile matvec using data-tiling fusion
To repro:

```bash
iree-compile \
  --iree-hal-target-device=local \
  --iree-hal-local-target-device-backends=llvm-cpu \
  --iree-llvmcpu-target-cpu=znver4 \
  --iree-opt-data-tiling=true \
  --iree-dispatch-creation-experimental-data-tiling=false \
  repro.mlir 
```

```
func.func @matvec(%arg0: tensor<3x4xi8>, %arg1: tensor<4xi8>, %arg2: tensor<3xi32>) -> tensor<3xi32> {
  %0 = linalg.matvec ins(%arg0, %arg1 : tensor<3x4xi8>, tensor<4xi8>) outs(%arg2 : tensor<3xi32>) -> tensor<3xi32>
  return %0 : tensor<3xi32>
}
```

In the `matmul->unset_encoding` dispatch, it generates collapse_shape in between, which blocks the fusion. E.g.,

```mlir
func.func @matvec_dispatch_0_matvec_3x4_i8xi8xi32() {
  %c0 = arith.constant 0 : index
  %c64 = arith.constant 64 : index
  %c128 = arith.constant 128 : index
  %0 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%c0) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<3x4xi8, #iree_encoding.layout<[#iree_cpu.cpu_encoding_resolver<configuration = {encoding_info = {innerDimsPos = [0, 1], innerTileSizes = [16, 2], outerDimsPerm = [0, 1]}}>]>>>
  %1 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%c64) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<4xi8, #iree_encoding.layout<[#iree_cpu.cpu_encoding_resolver<configuration = {encoding_info = {innerDimsPos = [0], innerTileSizes = [2], outerDimsPerm = [0]}}>]>>>
  %2 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%c128) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<3xi32, #iree_encoding.layout<[#iree_cpu.cpu_encoding_resolver<configuration = {encoding_info = {innerDimsPos = [0], innerTileSizes = [16], outerDimsPerm = [0]}}>]>>>
  %3 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(1) alignment(64) offset(%c0) flags(Indirect) : !iree_tensor_ext.dispatch.tensor<writeonly:tensor<3xi32>>
  %4 = iree_tensor_ext.dispatch.tensor.load %0, offsets = [0, 0], sizes = [3, 4], strides = [1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<3x4xi8, #iree_encoding.layout<[#iree_cpu.cpu_encoding_resolver<configuration = {encoding_info = {innerDimsPos = [0, 1], innerTileSizes = [16, 2], outerDimsPerm = [0, 1]}}>]>>> -> tensor<3x4xi8, #iree_encoding.encoding<operand_index = 0 : index, op_type =  matmul, element_types = [i8, i8, i32], user_indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0)>], iteration_sizes = [3, 4]>>
  %5 = iree_tensor_ext.dispatch.tensor.load %1, offsets = [0], sizes = [4], strides = [1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<4xi8, #iree_encoding.layout<[#iree_cpu.cpu_encoding_resolver<configuration = {encoding_info = {innerDimsPos = [0], innerTileSizes = [2], outerDimsPerm = [0]}}>]>>> -> tensor<4xi8, #iree_encoding.encoding<operand_index = 1 : index, op_type =  matmul, element_types = [i8, i8, i32], user_indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0)>], iteration_sizes = [3, 4]>>
  %6 = iree_tensor_ext.dispatch.tensor.load %2, offsets = [0], sizes = [3], strides = [1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<3xi32, #iree_encoding.layout<[#iree_cpu.cpu_encoding_resolver<configuration = {encoding_info = {innerDimsPos = [0], innerTileSizes = [16], outerDimsPerm = [0]}}>]>>> -> tensor<3xi32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [i8, i8, i32], user_indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0)>], iteration_sizes = [3, 4]>>
  %7 = linalg.matvec ins(%4, %5 : tensor<3x4xi8, #iree_encoding.encoding<operand_index = 0 : index, op_type =  matmul, element_types = [i8, i8, i32], user_indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0)>], iteration_sizes = [3, 4]>>, tensor<4xi8, #iree_encoding.encoding<operand_index = 1 : index, op_type =  matmul, element_types = [i8, i8, i32], user_indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0)>], iteration_sizes = [3, 4]>>) outs(%6 : tensor<3xi32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [i8, i8, i32], user_indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0)>], iteration_sizes = [3, 4]>>) -> tensor<3xi32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [i8, i8, i32], user_indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0)>], iteration_sizes = [3, 4]>>
  %8 = iree_encoding.unset_encoding %7 : tensor<3xi32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [i8, i8, i32], user_indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0)>], iteration_sizes = [3, 4]>> -> tensor<3xi32>
  iree_tensor_ext.dispatch.tensor.store %8, %3, offsets = [0], sizes = [3], strides = [1] : tensor<3xi32> -> !iree_tensor_ext.dispatch.tensor<writeonly:tensor<3xi32>>
  return
}

// -----// IR Dump After MaterializeDeviceEncodingPass (iree-codegen-materialize-device-encoding) //----- //
func.func @matvec_dispatch_0_matvec_3x4_i8xi8xi32() {
  %c0 = arith.constant 0 : index
  %c64 = arith.constant 64 : index
  %c128 = arith.constant 128 : index
  %0 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%c0) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x2x16x2xi8>>
  %1 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%c64) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x2x1x2xi8>>
  %2 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%c128) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x1x1x16xi32>>
  %3 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(1) alignment(64) offset(%c0) flags(Indirect) : !iree_tensor_ext.dispatch.tensor<writeonly:tensor<3xi32>>
  %4 = iree_tensor_ext.dispatch.tensor.load %0, offsets = [0, 0, 0, 0], sizes = [1, 2, 16, 2], strides = [1, 1, 1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x2x16x2xi8>> -> tensor<1x2x16x2xi8>
  %5 = iree_tensor_ext.dispatch.tensor.load %1, offsets = [0, 0, 0, 0], sizes = [1, 2, 1, 2], strides = [1, 1, 1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x2x1x2xi8>> -> tensor<1x2x1x2xi8>
  %6 = iree_tensor_ext.dispatch.tensor.load %2, offsets = [0, 0, 0, 0], sizes = [1, 1, 1, 16], strides = [1, 1, 1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x1x1x16xi32>> -> tensor<1x1x1x16xi32>
  %7 = linalg.mmt4d ins(%5, %4 : tensor<1x2x1x2xi8>, tensor<1x2x16x2xi8>) outs(%6 : tensor<1x1x1x16xi32>) -> tensor<1x1x1x16xi32>
  %collapsed = tensor.collapse_shape %7 [[0, 1], [2, 3]] : tensor<1x1x1x16xi32> into tensor<1x16xi32>
  %8 = tensor.empty() : tensor<3xi32>
  %unpack = linalg.unpack %collapsed outer_dims_perm = [0] inner_dims_pos = [0] inner_tiles = [16] into %8 : tensor<1x16xi32> -> tensor<3xi32>
  iree_tensor_ext.dispatch.tensor.store %unpack, %3, offsets = [0], sizes = [3], strides = [1] : tensor<3xi32> -> !iree_tensor_ext.dispatch.tensor<writeonly:tensor<3xi32>>
  return
}
```

A potential solution is folding the collapse_shape op into the unpack ops. IIRC, the reshape code was introduced for less code redundancy. I.e. it is used to drop unit dims. It may leave an extract_slice op at the end, which introduces other issues, though.

The other potential solution is just dropping the reshape, i.e., not dropping unit dims for materialized types.

https://github.com/iree-org/iree/blob/e601ec83c4528861aa4c162bae26b19b1fc82432/compiler/src/iree/compiler/Codegen/ExternalInterfaces/CPUEncodingExternalModels.cpp#L316-L319

### PR DESCRIPTION
**Pull request by hanhanW**
The revision implements a specialized propagation pattern for `tensor.collapse_shape->linalg.unpack`, if the packed dimension and the corresponding inner dimension are collapsed.

In the data layout propagation, we also populate patterns that sink down tensor.collapse_shape across `linalg.generic` ops. Because how we materialize matvec in CPU backends is converting it to `linalg.mmt4d->tensor.collapse_shape` op chain.

At the end, the pass folds the reshapes into bindings.

Fixes https://github.com/iree-org/iree/issues/21180

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp [hunk 1]
```diff
@@ -0,0 +1,164 @@
...
+    }
+    auto emptyOp = op.getDest().getDefiningOp<tensor::EmptyOp>();
+    if (!emptyOp) {
+      return rewriter.notifyMatchFailure(
+          op, "expected destination to be a tensor.empty op");
+    }
+    auto collapseOp = op.getSource().getDefiningOp<tensor::CollapseShapeOp>();
+    if (!collapseOp) {
+      return rewriter.notifyMatchFailure(
+          op, "expected the source to be a tensor.collpase_shape op");
```
Comment (jtuyls) [inline compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]:
```suggestion
          op, "expected the source to be a tensor.collapse_shape op");
```

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp [hunk 2]
```diff
@@ -0,0 +1,164 @@
...
+    }
+
+    int64_t srcRank = collapseOp.getSrcType().getRank();
+    if (srcRank != 4 && srcRank != 5) {
+      return rewriter.notifyMatchFailure(
+          op, "expected the rank of collapseOp's source is either 4 or 5");
+    }
+    bool hasBatch = collapseOp.getSrcType().getRank() == 5;
```
Comment (jtuyls) [inline compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]: This feels quite hardcoded with the exact ranks. Can't we implement this with respect to the rank of the unpack? Then it could potentially work for collapse->unpack of any dimension as long as other constraints are fulfilled?

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp [hunk 3]
```diff
@@ -0,0 +1,164 @@
...
+    SmallVector<int64_t> innerDimPos(op.getInnerDimsPos());
+    if (hasBatch && innerDimPos[0] == 0) {
+      return rewriter.notifyMatchFailure(
+          op, "expected unpacking either M or N dimension");
+    }
+
+    SmallVector<OpFoldResult> innerTiles(op.getMixedTiles());
+    SmallVector<OpFoldResult> destShape = emptyOp.getMixedSizes();
+    if (missUnitDimM) {
+      for (auto &pos : innerDimPos) {
```
Comment (jtuyls) [inline compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]:
```suggestion
      for (int64_t &pos : innerDimPos) {
```

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp [hunk 4]
```diff
@@ -0,0 +1,164 @@
...
+    }
+
+    RankedTensorType mmt4dSrcType = collapseOp.getSrcType();
+    bool missUnitDimM = mmt4dSrcType.getDimSize(outerRi[0]) == 1 &&
+                        mmt4dSrcType.getDimSize(innerRi[0]) == 1;
+    bool missUnitDimN = mmt4dSrcType.getDimSize(outerRi[1]) == 1 &&
+                        mmt4dSrcType.getDimSize(innerRi[1]) == 1;
+    if (!missUnitDimM && !missUnitDimN) {
+      return rewriter.notifyMatchFailure(
+          op, "expected collapsing either M dimensions or N dimensions");
```
Comment (jtuyls) [inline compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]: I know this is for matmul, but the pass just considers collapse and unpack operations and could be more general, so I feel like we shouldn avoid talking about M/N dimensions here.

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp [hunk 5]
```diff
@@ -0,0 +1,164 @@
...
+  MLIRContext *ctx = &getContext();
+  FunctionOpInterface funcOp = getOperation();
+  RewritePatternSet patterns(ctx);
+  patterns.insert<SinkDownCollapsingUnitDimsAcrossUnpack>(ctx);
+  populateReshapeToInterfaceTensorPatterns(patterns);
+  tensor::populateFoldTensorEmptyPatterns(patterns, /*foldSingleUseOnly=*/1);
+  linalg::populateFoldReshapeOpsByExpansionPatterns(
+      patterns, [](OpOperand *fusedOperand) -> bool {
+        Operation *producer = fusedOperand->get().getDefiningOp();
+        auto consumerGenercOp =
```
Comment (jtuyls) [inline compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]:
```suggestion
        auto consumerGenericOp =
```

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp (hunk 2 above)
Comment (Max191) [reply compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]: It might actually be okay IMO. To fill in some context, the reason this pattern is being added is that the mmt4d op requires 4-dimensional inputs and outputs. The point is mainly to make matching easier when ultimately lowering to ukernels on CPU. Hanhan and I chatted about it offline, and we decided to just do the simple thing for now (propagate the collapse_shape), since updating the mmt4d semantics is a larger task, and better left for another time if we really need to do it (we would rather just unblock enabling the late materialization).

Propagating the collapse down here, and introducing more unit dims is generally something we don't want to do, but we have a unique reason to do it in this case. I think the pattern will be somewhat short-lived, so I personally don't have an issue with it being very special-cased like this. It does feel slightly tech-debty to me, but I think it is a pretty small debt, and we want to unblock the late materialization path.

I do think we should include some TODOs about updating the mmt4d semantics and ultimately getting rid of this pattern, though. It is better IMO to just not have the unit dims to begin with.

Comment (Max191) [reply compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]: Also, one more piece of context. I think the main reason we would eventually need to generalize this pattern would be to support having multiple M/N dimensions, but if we want to do that, then we would need to update the mmt4d semantics anyway, and take the opportunity to drop the pattern.

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp [hunk 6]
```diff
@@ -0,0 +1,164 @@
...
+namespace {
+
+// Sinks down tensor.collapse_shape across linalg.unpack op, if the collapsing
+// dims are two unit dims where one is outer dimension and the other is inner
+// dimension. It implies that we swap two operations by adjusting the packing
+// metadata in linalg.unpack op.
+// Note that the pattern only supports the case where the destination tensor of
+// linalg.unpack op is a tensor.empty op. The constraint can be removed by
+// introducing tensor.expand_shape op on the destination tensor. However, it is
+// not common in practice, so it is not supported now.
```
Comment (Max191) [inline compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]: Can we add some context in the comments here that this is used for the mmt4d layout constraints? And also add a TODO to get rid of the pattern once mmt4d becomes more flexible (or is replaced with linalg.generic)

**Review by Max191 — APPROVED** [review]
LGTM, just one request about documentation.

Also, out of curiosity, why don't we have the same issue with linalg.pack + expand_shape on the LHS and RHS of the mmdt4d?

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp (hunk 2 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]: Yes, what Max said. They are doable to me, but the implementation may be more complicated. We may see the case if the elementwise consumer op has broadcasting semantics, for example. If local encoding propagation does not happen, this is all we need.

I'd prefer keeping it simple and revamp it when needed.

RE multiple M/N dimensions, the other approach may be inserting transpose + reshape, so it is still mmt4d op. +1 on not build the things for the problems we're not looking at.

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp (hunk 4 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]: I refresh the message to exclude matmul context.

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp (hunk 2 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]: > To fill in some context, the reason this pattern is being added is that the mmt4d op requires 4-dimensional inputs and outputs. The point is mainly to make matching easier when ultimately lowering to ukernels on CPU. Hanhan and I chatted about it offline, and we decided to just do the simple thing for now (propagate the collapse_shape), since updating the mmt4d semantics is a larger task, and better left for another time if we really need to do it (we would rather just unblock enabling the late materialization).

I can see that the encountered case has an mmt4d operation, but this pass itself doesn't know about any mmt4d, just collapse and unpack, so this pattern could in principle show up with any generic (doesn't even need to be any matmul/mmtXd) and therefore we shouldn't tie it to the mmt4d imo. And I think the logic here can be implemented based on the unpack and collapse dimensions itself without making an assumption on what comes before, which would avoid the hardcoding.

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]: It turns out that it is not complicated if we scope it to packing single dimension. I update the implementation, please take a look. Thanks!

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp [hunk 7]
```diff
@@ -0,0 +1,174 @@
...
+      if (outerRi.empty()) {
+        outerRi.assign(indices.begin(), indices.end());
+        continue;
+      }
+      if (innerRi.empty()) {
+        innerRi.assign(indices.begin(), indices.end());
+        continue;
+      }
+      return rewriter.notifyMatchFailure(
+          op, "expected only two re-association map to have two dimensions");
```
Comment (jtuyls) [inline compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]:
```suggestion
          op, "expected only two re-association maps to have two dimensions");
```

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp [hunk 8]
```diff
@@ -0,0 +1,174 @@
...
+    }
+    if (outerRi.empty() || innerRi.empty()) {
+      return rewriter.notifyMatchFailure(
+          op, "expected only two re-association map to have two dimensions");
```
Comment (jtuyls) [inline compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]:
```suggestion
          op, "expected exactly two re-association maps to have two dimensions");
```

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp [hunk 9]
```diff
@@ -0,0 +1,174 @@
...
+    }
+
+    RankedTensorType srcType = collapseOp.getSrcType();
+    if (innerRi.back() != srcType.getRank() - 1) {
+      return rewriter.notifyMatchFailure(
+          op, "expected two innermost dimensions are collapsed");
```
Comment (jtuyls) [inline compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]:
```suggestion
          op, "expected that the two innermost dimensions are collapsed");
```

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp [hunk 10]
```diff
@@ -0,0 +1,174 @@
...
+      innerTiles.insert(innerTiles.end(), rewriter.getIndexAttr(1));
+      destShape.insert(destShape.end(), rewriter.getIndexAttr(1));
+    }
+
+    Location loc = op.getLoc();
+    auto newDestOp = rewriter.create<tensor::EmptyOp>(
+        loc, destShape, emptyOp.getType().getElementType());
+    auto newUnpackOp = rewriter.create<linalg::UnPackOp>(
+        loc, collapseOp.getSrc(), newDestOp, innerDimPos, innerTiles);
+    SmallVector<ReassociationIndices> newRi;
```
Comment (jtuyls) [inline compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp:133]:
```suggestion
    SmallVector<ReassociationIndices> newRi;
    newRi.reserve(op.getDestRank());
```

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp [hunk 11]
```diff
@@ -0,0 +1,174 @@
...
+      return rewriter.notifyMatchFailure(
+          op, "expected only two re-association map to have two dimensions");
+    }
+    if (outerRi.empty() || innerRi.empty()) {
+      return rewriter.notifyMatchFailure(
+          op, "expected only two re-association map to have two dimensions");
+    }
+
+    RankedTensorType srcType = collapseOp.getSrcType();
+    if (innerRi.back() != srcType.getRank() - 1) {
```
Comment (jtuyls) [inline compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp:87]: Do you have a test for when this is not the case?

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp [hunk 12]
```diff
@@ -0,0 +1,174 @@
...
+      return rewriter.notifyMatchFailure(
+          op, "expected two innermost dimensions are collapsed");
+    }
+    SmallVector<int64_t> innerDimPos(op.getInnerDimsPos());
+    if (innerDimPos[0] != outerRi[0] && outerRi[1] != innerDimPos[0]) {
```
Comment (jtuyls) [inline compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]:
```suggestion
    if (innerDimPos[0] != outerRi[0] && innerDimPos[0] != outerRi[1]) {
```
I think re-arranging is more readable here.

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp [hunk 13]
```diff
@@ -0,0 +1,174 @@
...
+                              srcType.getDimSize(innerRi[0]) == 1;
+    bool missTrailingUnitDim = srcType.getDimSize(outerRi[1]) == 1 &&
+                               srcType.getDimSize(innerRi[1]) == 1;
+    if (!missLeadingUnitDim && !missTrailingUnitDim) {
+      return rewriter.notifyMatchFailure(op,
+                                         "expected collapsing either leading "
+                                         "unit dims or trailing outer dims");
+    }
+
+    SmallVector<OpFoldResult> innerTiles(op.getMixedTiles());
```
Comment (jtuyls) [inline compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp:112]: I think it's useful to add a comment here to explain how the new positions and tiles are created, maybe with an example.

**Review by jtuyls — APPROVED** [review]
Thanks for the changes! Looks mostly good to me, I just have a few nits/suggestions and a question on a test case.

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp (hunk 10 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp:133]: I think it is fine because the main advantage of `SmallVector` is that it allocates some number of elements (N) in the object itself. The rank is usually smaller than `8`, so the stack allocation (and the performance) is not significant here. It is a dead code in 99% cases, I think.

https://llvm.org/docs/ProgrammersManual.html#llvm-adt-smallvector-h

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp (hunk 11 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp:87]: Thanks, I missed this.

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp (hunk 12 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp]: Thanks, I missed this. I'll update it to `!llvm::is_contained(outerRi, innerDimPos[0])`.

File: compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp (hunk 10 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/Common/CPU/CPUPropagateDataLayout.cpp:133]: Yeah, sure
