### PR TITLE
Fixing bug in Vulkan HAL that was not handling binding offsets.

### LINKED ISSUE #3489: Investigate out-of-tolerance keras:large_cifar10_internal_tests_ResNet50__tf__iree_vulkan
After PR #3424 `//integrations/tensorflow/e2e/keras:large_cifar10_internal_tests_ResNet50__tf__iree_vulkan` started having larger diffs (~0.1) than the previous max tolerance. LLVM passes with no tolerance change, so there may be something specific to the Vulkan HAL, swiftshader, or SPIR-V codegen. It'd be useful to narrow down where this is happening and see if we can get a test earlier in the pipeline for whichever area it falls under.

Log:
https://source.cloud.google.com/results/invocations/c52975b6-bc8c-4aed-aa32-a544d7dcfc71/targets/iree%2Fgcp_ubuntu%2Fbazel%2Flinux%2Fx86-swiftshader%2Fintegrations%2Fpresubmit/log

### LINKED ISSUE #3507: Investigate correctness issue in MobileBert on vulkan
log:

Floating point difference between ref and tar was too large. Max abs diff: 1.76e+03, atol: 1.00e+00, max relative diff: 8.48e+03, rtol: 1.00e-06

### PR DESCRIPTION
**Pull request by benvanik**
Fixes #3489 and fixes #3507.

### CODE REVIEW

File: iree/hal/vulkan/vulkan_driver_module.cc [hunk 1]
```diff
@@ -78,7 +78,7 @@ StatusOr<ref_ptr<Driver>> CreateVulkanDriver() {
 
   if (absl::GetFlag(FLAGS_vulkan_validation_layers)) {
     options.instance_extensibility.optional_layers.push_back(
-        "VK_LAYER_LUNARG_standard_validation");
+        "VK_LAYER_KHRONOS_validation");
```
Comment (ScottTodd) [inline iree/hal/vulkan/vulkan_driver_module.cc:81]: Can you update the other instances of this name too?

https://github.com/google/iree/blob/14257a619ffec02d02a618aeceac4786c09d36b5/iree/hal/vulkan/api.h#L51

https://github.com/google/iree/blob/99913e489ed7271f95253ab53188db8976ef1bd0/iree/hal/vulkan/api.cc#L91-L93

**Review by ScottTodd — APPROVED** [review]
