### PR TITLE
[GPU] C promote (I)GEMM when there is elementwise with additonal operands

### LINKED ISSUE #22919: [regression-onnx] compilation timeout for beit_large_patch16_224_Opset16
### What happened?

Compilation time increased at this commit - `1cbf99570f`
from `0m57.585s` to `3m34.501s` resulting in a timeout during tests.
time timeout for tests is set at 100s

Last Working Version: 3.9.0rc20251103 
First Failing Version: 3.9.0rc20251104

---

Data gathered from command `time iree-compile ...`

`1cbf99570f [Codegen][GPU] Allow intentional padding for non-K-major matmul layouts (#22486)`
```
real    3m33.391s
user    3m34.501s
sys     0m4.056s
```
`20149ebd43 [GPU] Clean up misc issues in IREEGPUAttrs. NFC. (#22531)` (one commit before)
```
real    1m14.580s
user    1m14.096s
sys     0m4.897s
```
`bdf9393d9e (tag: iree-3.9.0rc20251103, tag: iree-3.9.0rc20251102) Bump LLVM to llvm/llvm-project@04f87c693c7e (#22515)` (working release tag)
```
real    0m57.515s
user    0m57.585s
sys     0m3.916s
```

### Steps to reproduce your issue

mlir file : `/shark-dev/iree-bug/22919_beit_large_patch16_224_Opset16/model.mlir` (path in SharkMi300X-4 machine) 
file >2GB, stored locally on the SharkMi300X-4

compile command
```
iree-compile model.torch_onnx.mlir \
--iree-hal-target-backends=rocm --iree-hip-target=gfx942 -o compiled_model.vmfb
```

### What component(s) does this issue relate to?

_No response_

### Version information

_No response_

### Additional context

_No response_

### LINKED ISSUE #22986: [onnx regression] Seg fault for due to `7cdfc13c36578453fb0156f8dbbb4d5eae53376b`
### What happened?

for the given IR

```mlir
module {
  func.func @main_graph(%arg0: !torch.vtensor<[1,3,224,224],f32>) -> !torch.vtensor<[1,64,56,56],f32> attributes {torch.onnx_meta.ir_version = 8 : si64, torch.onnx_meta.opset_version = 16 : si64, torch.onnx_meta.producer_name = "pytorch", torch.onnx_meta.producer_version = "2.1.0"} {
    %211 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<1.0> : tensor<1x1x64x56x56xf32>} : () -> !torch.vtensor<[1,1,64,56,56],f32> 
    %0 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<1.0> : tensor<128x16x1x1xf32>} : () -> !torch.vtensor<[128,16,1,1],f32> 
    %1 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<1.0> : tensor<64x3x7x7xf32>} : () -> !torch.vtensor<[64,3,7,7],f32> 
    %2 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<1.0> : tensor<64xf32>} : () -> !torch.vtensor<[64],f32> 
    %3 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<1.0> : tensor<64x32x3x3xf32>} : () -> !torch.vtensor<[64,32,3,3],f32> 
    %4 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<1.0> : tensor<64xf32>} : () -> !torch.vtensor<[64],f32> 
    %9 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<1.0> : tensor<64x64x3x3xf32>} : () -> !torch.vtensor<[64,64,3,3],f32> 
    %10 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<1.0> : tensor<64xf32>} : () -> !torch.vtensor<[64],f32> 
    %11 = torch.operator "onnx.Conv"(%arg0, %1, %2) {torch.onnx.dilations = [1 : si64, 1 : si64], torch.onnx.group = 1 : si64, torch.onnx.kernel_shape = [7 : si64, 7 : si64], torch.onnx.pads = [3 : si64, 3 : si64, 3 : si64, 3 : si64], torch.onnx.strides = [2 : si64, 2 : si64]} : (!torch.vtensor<[1,3,224,224],f32>, !torch.vtensor<[64,3,7,7],f32>, !torch.vtensor<[64],f32>) -> !torch.vtensor<[1,64,112,112],f32> 
    %12 = torch.operator "onnx.Relu"(%11) : (!torch.vtensor<[1,64,112,112],f32>) -> !torch.vtensor<[1,64,112,112],f32> 
    %13 = torch.operator "onnx.MaxPool"(%12) {torch.onnx.ceil_mode = 0 : si64, torch.onnx.kernel_shape = [3 : si64, 3 : si64], torch.onnx.pads = [1 : si64, 1 : si64, 1 : si64, 1 : si64], torch.onnx.strides = [2 : si64, 2 : si64]} : (!torch.vtensor<[1,64,112,112],f32>) -> !torch.vtensor<[1,64,56,56],f32> 
    %14 = torch.operator "onnx.Constant"() {torch.onnx.value = dense_resource<_> : tensor<2xsi64>} : () -> !torch.vtensor<[2],si64> 
    %15:2 = torch.operator "onnx.Split"(%13, %14) {torch.onnx.axis = 1 : si64} : (!torch.vtensor<[1,64,56,56],f32>, !torch.vtensor<[2],si64>) -> (!torch.vtensor<[1,32,56,56],f32>, !torch.vtensor<[1,32,56,56],f32>) 
    %16 = torch.operator "onnx.Conv"(%15#0, %3, %4) {torch.onnx.dilations = [1 : si64, 1 : si64], torch.onnx.group = 1 : si64, torch.onnx.kernel_shape = [3 : si64, 3 : si64], torch.onnx.pads = [1 : si64, 1 : si64, 1 : si64, 1 : si64], torch.onnx.strides = [1 : si64, 1 : si64]} : (!torch.vtensor<[1,32,56,56],f32>, !torch.vtensor<[64,32,3,3],f32>, !torch.vtensor<[64],f32>) -> !torch.vtensor<[1,64,56,56],f32> 
    %22 = torch.operator "onnx.Constant"() {torch.onnx.value = dense_resource<__2> : tensor<1xsi64>} : () -> !torch.vtensor<[1],si64> 
    %23 = torch.operator "onnx.Unsqueeze"(%16, %22) : (!torch.vtensor<[1,64,56,56],f32>, !torch.vtensor<[1],si64>) -> !torch.vtensor<[1,1,64,56,56],f32> 
    %24 = torch.operator "onnx.Concat"(%211, %23) {torch.onnx.axis = 1 : si64} : (!torch.vtensor<[1,1,64,56,56],f32>, !torch.vtensor<[1,1,64,56,56],f32>) -> !torch.vtensor<[1,2,64,56,56],f32> 
    %25 = torch.operator "onnx.Constant"() {torch.onnx.value = dense_resource<__3> : tensor<1xsi64>} : () -> !torch.vtensor<[1],si64> 

    %331 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<1.0> : tensor<1x2x64x1x1xf32>} : () -> !torch.vtensor<[1,2,64,1,1],f32> 
    %34 = torch.operator "onnx.Mul"(%24, %331) : (!torch.vtensor<[1,2,64,56,56],f32>, !torch.vtensor<[1,2,64,1,1],f32>) -> !torch.vtensor<[1,2,64,56,56],f32> 
    %35 = torch.operator "onnx.ReduceSum"(%34, %25) {torch.onnx.keepdims = 0 : si64} : (!torch.vtensor<[1,2,64,56,56],f32>, !torch.vtensor<[1],si64>) -> !torch.vtensor<[1,64,56,56],f32> 
    %36 = torch.operator "onnx.Conv"(%35, %9, %10) {torch.onnx.dilations = [1 : si64, 1 : si64], torch.onnx.group = 1 : si64, torch.onnx.kernel_shape = [3 : si64, 3 : si64], torch.onnx.pads = [1 : si64, 1 : si64, 1 : si64, 1 : si64], torch.onnx.strides = [1 : si64, 1 : si64]} : (!torch.vtensor<[1,64,56,56],f32>, !torch.vtensor<[64,64,3,3],f32>, !torch.vtensor<[64],f32>) -> !torch.vtensor<[1,64,56,56],f32> 
    %37 = torch.operator "onnx.Add"(%36, %13) : (!torch.vtensor<[1,64,56,56],f32>, !torch.vtensor<[1,64,56,56],f32>) -> !torch.vtensor<[1,64,56,56],f32> 
    return %37 : !torch.vtensor<[1,64,56,56],f32>
  }
}

{-#
  dialect_resources: {
    builtin: {
      _: "0x0800000020000000000000002000000000000000",
      __1: "0x080000000100000000000000",
      __2: "0x080000000100000000000000",
      __3: "0x080000000100000000000000"
    }
  }
#-}
```

seeing seg fault due to https://github.com/iree-org/iree/commit/7cdfc13c36578453fb0156f8dbbb4d5eae53376b

command:

```
rm -rf test.vmfb

iree-compile test.mlir --iree-hal-target-backends=rocm --iree-hip-target=gfx942 -o test.vmfb 

iree-run-module --module='test.vmfb' --device=hip --function='main_graph' --input='1x3x224x224xf32=@input.0.bin' 
```

[input.0.bin.txt](https://github.com/user-attachments/files/24366190/input.0.bin.txt)

we have 65 model impacted due to this for GPU only while passing on CPU

```
| darknetaa53 | PASS | compiled_inference |
| model--mT5-base-HunSum-1--SZTAKI-HLT | PASS | compiled_inference |
| dla34_Opset17_timm | PASS | compiled_inference |
| efficientnetv2_rw_s_Opset17_timm | PASS | compiled_inference |
| gernet_m_Opset18_timm | PASS | compiled_inference |
| resnet10t_Opset17_timm | PASS | compiled_inference |
| resnet18_Opset18_torch_hub | PASS | compiled_inference |
| resnet18d_Opset17_timm | PASS | compiled_inference |
| resnet34_Opset17_torch_hub | PASS | compiled_inference |
| resnet34_Opset18_timm | PASS | compiled_inference |
| resnet34d_Opset17_timm | PASS | compiled_inference |
| resnet34d_Opset18_timm | PASS | compiled_inference |
| skresnet18_Opset16_timm | PASS | compiled_inference |
| skresnet34_Opset16_timm | PASS | compiled_inference |
| ssl_resnet18_Opset16_timm | PASS | compiled_inference |
| visformer_tiny_Opset18_timm | PASS | compiled_inference |
| xcit_medium_24_p8_384_dist_Opset16_timm | PASS | compiled_inference |
| xcit_tiny_12_p8_224_Opset16_timm | PASS | compiled_inference |
| xcit_tiny_24_p8_224_dist_Opset16_timm | PASS | compiled_inference |
| dla34_Opset16 | PASS | compiled_inference |
| dla34_Opset17 | PASS | compiled_inference |
| dla34_Opset18 | PASS | compiled_inference |
| efficientnetv2_rw_s_Opset16 | PASS | compiled_inference |
| efficientnetv2_rw_s_Opset17 | PASS | compiled_inference |
| gernet_m_Opset16 | PASS | compiled_inference |
| gernet_m_Opset17 | PASS | compiled_inference |
| gernet_m_Opset18 | PASS | compiled_inference |
| gluon_resnet18_v1b_Opset16 | PASS | compiled_inference |
| gluon_resnet18_v1b_Opset17 | PASS | compiled_inference |
| gluon_resnet18_v1b_Opset18 | PASS | compiled_inference |
| gluon_resnet34_v1b_Opset16 | PASS | compiled_inference |
| gluon_resnet34_v1b_Opset17 | PASS | compiled_inference |
| gluon_resnet34_v1b_Opset18 | PASS | compiled_inference |
| resnet10t_Opset16 | PASS | compiled_inference |
| resnet10t_Opset17 | PASS | compiled_inference |
| resnet10t_Opset18 | PASS | compiled_inference |
| resnet18d_Opset16 | PASS | compiled_inference |
| resnet18d_Opset17 | PASS | compiled_inference |
| resnet18d_Opset18 | PASS | compiled_inference |
| resnet34d_Opset16 | PASS | compiled_inference |
| resnet34d_Opset17 | PASS | compiled_inference |
| resnet34d_Opset18 | PASS | compiled_inference |
| skresnet18_Opset16 | PASS | compiled_inference |
| skresnet18_Opset17 | PASS | compiled_inference |
| skresnet34_Opset16 | PASS | compiled_inference |
| skresnet34_Opset17 | PASS | compiled_inference |
| ssl_resnet18_Opset16 | PASS | compiled_inference |
| ssl_resnet18_Opset17 | PASS | compiled_inference |
| ssl_resnet18_Opset18 | PASS | compiled_inference |
| swsl_resnet18_Opset16 | PASS | compiled_inference |
| swsl_resnet18_Opset17 | PASS | compiled_inference |
| swsl_resnet18_Opset18 | PASS | compiled_inference |
| tv_resnet34_Opset16 | PASS | compiled_inference |
| tv_resnet34_Opset17 | PASS | compiled_inference |
| tv_resnet34_Opset18 | PASS | compiled_inference |
| visformer_tiny_Opset16 | PASS | compiled_inference |
| visformer_tiny_Opset17 | PASS | compiled_inference |
| visformer_tiny_Opset18 | PASS | compiled_inference |
| xcit_medium_24_p8_384_dist_Opset16 | PASS | compiled_inference |
| xcit_small_12_p8_384_dist_Opset16 | PASS | compiled_inference |
| xcit_small_24_p8_384_dist_Opset16 | PASS | compiled_inference |
| xcit_tiny_12_p8_224_Opset16 | PASS | compiled_inference |
| xcit_tiny_12_p8_224_dist_Opset16 | PASS | compiled_inference |
| xcit_tiny_24_p8_224_Opset16 | PASS | compiled_inference |
| xcit_tiny_24_p8_224_dist_Opset16 | PASS | compiled_inference |
```

### What component(s) does this issue relate to?

_No response_

### Version information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvedhmeshram**
We have trouble with fusion of operands to elementwise operations without c promotion. We have work in progress for proper support of this as per https://github.com/iree-org/iree/issues/23038

However in the time being we have several issues blocked by this so we will just enable c promotion for this specific case, which is using padding AND has an elementwise with operands other than the (I)GEMM itself. 

We have a dev flag (default true) so that we can continue the work on map_gather while observing the problem with `--iree-codegen-test-c-promtion=false`

Fixes :  https://github.com/iree-org/iree/issues/22919
Fixes : https://github.com/iree-org/iree/issues/22986

### CODE REVIEW

**Comment by nirvedhmeshram** [comment]
FYI @MaheshRavishankar this solves the compilation time and segfault bug for now.

File: compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp [hunk 1]
```diff
@@ -856,12 +892,20 @@ getMatmulOrIGEMMLoweringConfigAndWorkgroupSize(
...
+    promotionList.push_back(2);
+  }
   if (scaled) {
     // TODO(#22119): We don't use global load DMA for scaled matmuls, because
     // compilation doesn't support it. Once this is fixed, we should use global
     // load DMA here when possible.
     promotionArray = {};
-    promotionList.append({2, 3});
+    if (mustCpromote) {
+      promotionList.append({3, 4});
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp]: Can you add a comment noting that operand 2 (which would normally be C in an unscaled GEMM but is the LHS scales here) is already on the promotion list? Alternatively, could you restructure the control flow to make the logic more obvious?

**Review by MaheshRavishankar — APPROVED** [review]
