### PR TITLE
Populate dependent dialects in auto input conversion pipeline

### LINKED ISSUE #13860: Auto input conversion pipeline pass does not declare dependent dialects
### What happened?

IREE's [`--iree-auto-input-conversion` pass](https://github.com/openxla/iree/pull/13443) walks the input module and decides which input conversion pipeline to run based on the module contents.

The issue with this implementation is that the selected pipeline may produce ops from some other dialects which were not registered by the auto input conversion pass.

I'm not sure how to fix this -- I think we would have to query all the dependent dialects across all input conversion pipelines available, so that we can declare the dependencies before the pass manager starts executing the input conversion pass. Or perhaps it shouldn't be a pass in the first place?

### Steps to reproduce your issue

Repro:
```mlir
func.func @simple_add(%arg0: tensor<2x2xi32>, %arg1: tensor<2x2xi32>) -> tensor<2x2xi32> {
  %0 = "mhlo.add"(%arg0, %arg1) : (tensor<2x2xi32>, tensor<2x2xi32>) -> tensor<2x2xi32>
  return %0 : tensor<2x2xi32>
}
```

Command: `tools/iree-opt --split-input-file --iree-auto-input-conversion repro.mlir`

Error:
```
LLVM ERROR: Building op `tensor.empty` but it isn't registered in this MLIRContext: the dialect may not be loaded or this operation isn't registered by the dial
ect. See also https://mlir.llvm.org/getting_started/Faq/#registered-loaded-dependent-whats-up-with-dialects-management                                          
Please report issues to https://github.com/openxla/iree/issues and include the crash backtrace.                                                                 
Stack dump:  
```

### What component(s) does this issue relate to?

_No response_

### Version information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kuhar**
Because we don't statically know the exact pipeline, add dialects from all pipelines.

Add a missing dialect to the MHLO pipeline.

Fixes: https://github.com/openxla/iree/issues/13860

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

File: compiler/src/iree/compiler/InputConversion/Common/AutoInputConversionPipeline.cpp [hunk 1]
```diff
@@ -166,6 +167,36 @@ void AutoInputConversionPipelinePass::runOnOperation() {
   }
 }
 
+void AutoInputConversionPipelinePass::getDependentDialects(
+    DialectRegistry& registry) const {
+  // Register dialects from all possible pipelines, as we do not statically know
+  // which pipeline will be selected, while dialect registration happens before
+  // we run any detection on the input.
```
Comment (jpienaar) [inline compiler/src/iree/compiler/InputConversion/Common/AutoInputConversionPipeline.cpp:174]: Could you add a TODO that we should revise this? E.g., we are building pipelines just to discard them here and then rebuilding below. This may require different support upstream or some such.

**Review by jpienaar — APPROVED** [review]
