### PR TITLE
[cuda][hip] Fix launch host func and worker thread state update

### LINKED ISSUE #15790: [Epic] HIP HAL driver rewrite
### Background 

The current ROCm HAL driver was based on the initial CUDA HAL driver; both are prototypes in the early days. We are in the process of rewriting the CUDA HAL driver, tracked in https://github.com/openxla/iree/issues/13245, to fix various issues listed there. The ROCm HAL inherits similar issues and needs to be rewritten too. This is the tracking epic for this effort.

### Goals and Plans
The goals to achieve are similar to the CUDA HAL driver rewrite, listed in https://github.com/openxla/iree/issues/13245. The overall plan is to start a new experimental HAL driver in [experiemental/](https://github.com/openxla/iree/tree/main/experimental), `hip`, and leverage corresponding pieces in `cuda2` there to bring up.

Along the way, we want to flesh out CTS https://github.com/openxla/iree/issues/13250.

### Concrete Tasks

These are major abstract tasks now; as we go we'll break them down into smaller ones and create seprate task list to track.

```[tasklist]
### Basics
- [ ] https://github.com/openxla/iree/pull/15506
- [ ] https://github.com/openxla/iree/pull/15887
```

```[tasklist]
### Memory Management
- [ ] https://github.com/openxla/iree/pull/15791
```

```[tasklist]
### Compute Pipeline
- [ ] https://github.com/openxla/iree/pull/15910
- [ ] https://github.com/openxla/iree/pull/15937
- [ ] https://github.com/openxla/iree/pull/16290
- [ ] Enable graph command buffer with latest HIP API
```

```[tasklist]
### Synchronization
- [ ] https://github.com/openxla/iree/pull/16305
```

```[tasklist]
### Collectives
- [ ] Support collective APIs
```
```[tasklist]
### HAL conformance testing suite
- [ ] https://github.com/openxla/iree/pull/16380
```

### PR DESCRIPTION
**Pull request by antiagainst**
This commits fixes a few issues in pending action queue to
resolve driver deadlock issues:

* In host launch func, which is called from a driver thread,
  we cannot invoke any GPU API. Otherwise we might see
  deadlock. This includes cleaning up the actions after
  execution--it may involve buffer releasing/unregistering
  which was the issue causing hip driver hang. Now move
  this cleanup into the worker thread. This is done by adding
  a state field to each action to indicate whether it's alive
  or zombie. We enqueue each action again after done
  execution by flipping its state to zombie to let the worker
  thread to cleanup.
* The worker thread can have five states--two normal states
  (idle waiting or workload pending), three exit states (requested,
  committed, error). They have increasing priorities w.r.t.
  overwriting. We cannot overwrite state later in the list
  without checking. This guarantees that exit requests are
  properly respected and not dropping to the floor so to have
  clean exit.
* When the worker thread is waken to process ready list, we
  need to immediately flip the worker state from workload
  pending to idle waiting, before any real processing. This
  makes sure we don't drop new workload enqueued while
  we are processing, and the worker thread can be waken
  up again properly later.

With the above fixes, we can pass all stablehlo/tosa e2e op
tests on hip driver without hang or crashes. The same
change is mirrored to the cuda pending action queue.

Fixes https://github.com/openxla/iree/issues/15790
Progress towards https://github.com/openxla/iree/issues/16504

### CODE REVIEW

**Comment by antiagainst** [comment]
This patch depends on https://github.com/openxla/iree/pull/16466; the first commit comes there.

**Comment by nithinsubbiah** [comment]
Thanks for the fix!

**Review by nithinsubbiah — APPROVED** [review]

**Comment by antiagainst** [comment]
hey @benvanik could you take a look? thanks!

File: experimental/hip/pending_queue_actions.c [hunk 1]
```diff
@@ -49,6 +57,11 @@ typedef struct iree_hal_hip_queue_action_t {
   // Retained to make sure it outlives the current action.
   iree_hal_hip_pending_queue_actions_t* owning_actions;
 
+  // The current state of this action. When an action is initially created it
+  // will be alive and enqueued to wait for releasing to the GPU. After done
+  // execution, it will be flipped into zombie state and enqueued again for
+  // destruction.
+  iree_hal_hip_queue_action_state_t status;
```
Comment (benvanik) [inline experimental/hip/pending_queue_actions.c]:
```suggestion
  iree_hal_hip_queue_action_state_t state;
```

File: experimental/hip/pending_queue_actions.c [hunk 2]
```diff
@@ -498,33 +523,41 @@ iree_status_t iree_hal_hip_pending_queue_actions_enqueue_execution(
...
 static void iree_hal_hip_execution_device_signal_host_callback(
     void* user_data) {
   IREE_TRACE_ZONE_BEGIN(z0);
   iree_hal_hip_queue_action_t* action = (iree_hal_hip_queue_action_t*)user_data;
+  IREE_ASSERT(action->kind == IREE_HAL_HIP_QUEUE_ACTION_TYPE_EXECUTION);
+  IREE_ASSERT(action->status == IREE_HAL_HIP_QUEUE_ACTION_STATE_ALIVE);
   iree_hal_hip_pending_queue_actions_t* actions = action->owning_actions;
+
+  // Flip the action status to zombie and enqueue it again so that we can let
+  // the worker thread to clean it up. Note that this is necessary because
```
Comment (benvanik) [inline experimental/hip/pending_queue_actions.c]:
```suggestion
  // the worker thread clean it up. Note that this is necessary because
```

File: experimental/hip/pending_queue_actions.c [hunk 3]
```diff
@@ -498,33 +523,41 @@ iree_status_t iree_hal_hip_pending_queue_actions_enqueue_execution(
...
-  // Try to release more pending actions to the GPU now.
-  IREE_IGNORE_ERROR(iree_hal_hip_pending_queue_actions_issue(actions));
+
   IREE_TRACE_ZONE_END(z0);
 }
 
 // Issues the given kernel dispatch |action| to the GPU.
 static iree_status_t iree_hal_hip_pending_queue_actions_issue_execution(
     iree_hal_hip_queue_action_t* action) {
+  IREE_ASSERT(action->kind == IREE_HAL_HIP_QUEUE_ACTION_TYPE_EXECUTION);
```
Comment (benvanik) [inline experimental/hip/pending_queue_actions.c]: note there are some helpers like IREE_ASSERT_EQ and IREE_ASSERT_TRUE/FALSE

File: experimental/hip/pending_queue_actions.c [hunk 4]
```diff
@@ -605,27 +638,32 @@ static iree_status_t iree_hal_hip_pending_queue_actions_issue_execution(
...
   iree_hal_hip_pending_queue_actions_t* actions = action->owning_actions;
   iree_allocator_t host_allocator = actions->host_allocator;
   IREE_TRACE_ZONE_BEGIN(z0);
 
+  // First call user provided callback before releasing any resource.
   if (action->cleanup_callback) {
     action->cleanup_callback(action->callback_user_data);
   }
 
+  // Then release all retained resources.
```
Comment (benvanik) [inline experimental/hip/pending_queue_actions.c]: nit: ordering comments shouldn't require context as new lines of code added can make things less clear - usually best to state the condition (`// Only release resources after callbacks have been issued.`)

File: experimental/hip/pending_queue_actions.c [hunk 5]
```diff
@@ -814,18 +878,34 @@ static int iree_hal_hip_worker_execute(
         (iree_condition_fn_t)iree_hal_hip_worker_has_incoming_request,
         working_area, iree_infinite_timeout());
 
+    // Immediately flip the state to idle waiting if and only if the preivous
```
Comment (benvanik) [inline experimental/hip/pending_queue_actions.c]:
```suggestion
    // Immediately flip the state to idle waiting if and only if the previous
```

File: runtime/src/iree/hal/drivers/cuda/pending_queue_actions.c [hunk 6]
```diff
@@ -49,6 +57,11 @@ typedef struct iree_hal_cuda_queue_action_t {
   // Retained to make sure it outlives the current action.
   iree_hal_cuda_pending_queue_actions_t* owning_actions;
 
+  // The current state of this action. When an action is initially created it
+  // will be alive and enqueued to wait for releasing to the GPU. After done
+  // execution, it will be flipped into zombie state and enqueued again for
+  // destruction.
+  iree_hal_cuda_queue_action_state_t status;
```
Comment (benvanik) [inline runtime/src/iree/hal/drivers/cuda/pending_queue_actions.c]:
```suggestion
  iree_hal_cuda_queue_action_state_t state;
```

File: runtime/src/iree/hal/drivers/cuda/pending_queue_actions.c [hunk 7]
```diff
@@ -607,27 +640,32 @@ static iree_status_t iree_hal_cuda_pending_queue_actions_issue_execution(
...
   iree_hal_cuda_pending_queue_actions_t* actions = action->owning_actions;
   iree_allocator_t host_allocator = actions->host_allocator;
   IREE_TRACE_ZONE_BEGIN(z0);
 
+  // First call user provided callback before releasing any resource.
   if (action->cleanup_callback) {
     action->cleanup_callback(action->callback_user_data);
   }
 
+  // Then release all retained resources.
```
Comment (benvanik) [inline runtime/src/iree/hal/drivers/cuda/pending_queue_actions.c]: (same comments in this copy)

**Review by benvanik — APPROVED** [review]
minor things and LGTM!
