### PR TITLE
[Codegen][GPU] Add support for allocating private memory for unused DPS results

### LINKED ISSUE #20699: topk: Failed to bufferize op
### What happened?

Trying to compile the attached [mlir file](https://github.com/user-attachments/files/20004319/topk.txt) fails in two different ways.
**Without** `--iree-opt-level=O3`: [err_no03.txt](https://github.com/user-attachments/files/20004331/err_no03.txt)
```
iree-compile: iree/compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/ConfigUtils.cpp:147: std::optional<GPUMMASchedule> mlir::iree_compiler::IREE::GPU::getMmaScheduleFromProblemAndTarget(IREE::GPU::TargetAttr, mlir::iree_compiler::GPUMatmulShapeType, bool, bool, bool, bool): Assertion `problem.aType == problem.bType && "expected the same aType and bType."' failed.
```

**With** `--iree-opt-level=O3`: [err.txt](https://github.com/user-attachments/files/20004327/err.txt)
```
topk.txt:73:25: error: failed to bufferize op
    %values, %indices = torch.aten.topk %24, %int2_8, %int-1_9, %true, %true_10 : !torch.vtensor<[?,2,2],f32>, !torch.int, !torch.int, !torch.bool, !torch.bool -> !torch.vtensor<[?,2,2],f32>, !torch.vtensor<[?,2,2],si64>
                        ^
topk.txt:73:25: note: see current operation: %24 = "bufferization.alloc_tensor"(%23) <{operandSegmentSizes = array<i32: 0, 1, 0>}> : (tensor<1x1x2xi64>) -> tensor<1x1x2xi64>
```

### Steps to reproduce your issue

Compiled with 
```
iree-compile topk.txt \
  --iree-hal-target-device=hip[0] \
  --iree-hal-executable-debug-level=3 \
  -o=output.vmfb --iree-hip-target=gfx942 --iree-opt-level=O3
```

### What component(s) does this issue relate to?

_No response_

### Version information

Built from source using iree-3.4.0rc20250423.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Muzammiluddin-Syed-ECE**
Fixes https://github.com/iree-org/iree/issues/20699

Fixes bufferization failures caused by unused results of DPS ops. Adds a `tensor_alloc` copy in private space to prevent allocation in global space during bufferization. In the specific case of SortOp, also adds a canonicalization pattern to remove unused results.

### CODE REVIEW

**Comment by Muzammiluddin-Syed-ECE** [comment]
@MaheshRavishankar We originally agreed to put this pattern in `GPUInferMemorySpace` however it felt like it didn't really belong so I placed it in a new pass.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDsp.cpp [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
+#include "mlir/Dialect/GPU/IR/GPUDialect.h"
+
+namespace mlir::iree_compiler {
+
+#define GEN_PASS_DEF_GPUPRUNEDSPPASS
+#include "iree/compiler/Codegen/Common/GPU/Passes.h.inc"
+
+namespace {
+/// Pass to create a `bufferization.alloc_tensor` in private space for all DSP
```
Comment (pashu123) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDsp.cpp]: I think it's DPS (Destination passing style) ops.

File: compiler/src/iree/compiler/Codegen/Common/GPU/BUILD.bazel [hunk 2]
```diff
@@ -80,7 +80,7 @@ iree_compiler_cc_library(
         "GPUPatterns.cpp",
         "GPUPipelining.cpp",
         "GPUPromoteMatmulOperands.cpp",
-        "GPUPruneDsp.cpp",
+        "GPUPruneDps.cpp",
```
Comment (pashu123) [inline compiler/src/iree/compiler/Codegen/Common/GPU/BUILD.bazel]: `GPUPruneDPSOps` might be more specific.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDps.cpp [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+  MLIRContext *context = &getContext();
+  FunctionOpInterface funcOp = getOperation();
+
+  gpu::AddressSpaceAttr privSpace = gpu::AddressSpaceAttr::get(
+      context, gpu::GPUDialect::getPrivateAddressSpace());
+
+  bufferization::BufferizationOptions options;
+  options.defaultMemorySpaceFn =
+      [&p = privSpace](TensorType t) -> std::optional<Attribute> { return p; };
+  bufferization::AnalysisState analysisState(options);
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDps.cpp]: Do we even need to use the `bufferization::AnalysisState`? Not following what this is for

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp [hunk 4]
```diff
@@ -507,6 +507,63 @@ SortOp::reifyResultShapes(OpBuilder &b,
       .reifyResultShapes(b, reifiedReturnShapes);
 }
 
+LogicalResult SortOp::canonicalize(SortOp sortOp, PatternRewriter &rewriter) {
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: Could you separate this into its own commit?

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Needs test and also probably needs to be split. Also have a question (in the code).

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDps.cpp (hunk 3 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDps.cpp]: That's used as an instance to access this non-static member function:
> SetVector<Value> producers = analysisState.findValueInReverseUseDefChain(
          value, stoppingConditionFn);
 
It may feel a bit redundant, but using this function made the traversal much easier, else I'd have to duplicate that code somewhat, which would also be fine.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 5]
```diff
@@ -0,0 +1,107 @@
...
+
+namespace {
+/// Pass to create a `bufferization.alloc_tensor` in private space for all DPS
+/// ops with unused results that can't be removed.
+/// These unused results, if originating from loads from global memory, trigger
+/// allocations in global memory space during bufferization, which will fail.
+/// So, the allocations must be made earlier to avoid failed bufferization.
+/// This pass is a hack to get around other work that can be done to improve
+/// the bufferization algorithm.
+/// TODO: Fix this.
```
Comment (pashu123) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: Can you provide a brief description of a fix? It could be an idea or direction towards implementing the fix.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 6]
```diff
@@ -0,0 +1,107 @@
...
+struct GPUPruneDPSOpsPass final
+    : impl::GPUPruneDPSOpsPassBase<GPUPruneDPSOpsPass> {
+
```
Comment (pashu123) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: Remove blank line.

Comment (pashu123) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: Please follow: https://google.github.io/styleguide/cppguide.html#Vertical_Whitespace

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 7]
```diff
@@ -0,0 +1,107 @@
...
+  options.defaultMemorySpaceFn =
+      [&p = privSpace](TensorType t) -> std::optional<Attribute> { return p; };
+  bufferization::AnalysisState analysisState(options);
+
+  // Check if this is an op that doesn't change the address space
+  // and is neither a consumer nor producer.
+  auto isPassThroughOp = [](Operation *op) -> bool {
+    return llvm::isa<tensor::ExtractSliceOp, tensor::DimOp>(op);
+  };
+  auto isGlobalLoad = [](Operation *op) -> bool {
```
Comment (pashu123) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: `isGlobalLoadOp`

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 8]
```diff
@@ -0,0 +1,107 @@
...
+  };
+
+  // Iterate over all DPS ops.
+  WalkResult res = funcOp.walk([&](DestinationStyleOpInterface dpsOp) {
+    for (int idx = 0; idx < dpsOp.getNumDpsInits(); ++idx) {
+      OpOperand *value = dpsOp.getDpsInitOperand(idx);
+      // If the associated result is used, do nothing.
+      if (!dpsOp->getResult(idx).use_empty()) {
+        continue;
+      }
```
Comment (pashu123) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: Modifying the IR while walking can mess up the use-def chain and cause problems. I suggest collecting the legal/modifiable operations and performing rewrites/inplace updates.

File: compiler/src/iree/compiler/Codegen/Common/GPU/test/gpu_prune_dps_ops.mlir [hunk 9]
```diff
@@ -0,0 +1,89 @@
+// RUN: iree-opt %s --split-input-file --verify-diagnostics \
```
Comment (pashu123) [inline compiler/src/iree/compiler/Codegen/Common/GPU/test/gpu_prune_dps_ops.mlir]: I don't think we need --verify-diagnostics unless we are checking for errors or warnings.

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp [hunk 10]
```diff
@@ -507,6 +507,63 @@ SortOp::reifyResultShapes(OpBuilder &b,
...
+
+  // If there are no results, bufferization has happened.
+  // Do not try to prune results anymore.
+  if (results.size() == 0) {
+    return failure();
+  }
+
+  Block &block = sortOp.getRegion().front();
+  auto blockArgs = block.getArguments();
+  auto used = [&](Value result) { return !result.use_empty(); };
```
Comment (pashu123) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: Lambda doesn't capture anything, you can remove the &.

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp [hunk 11]
```diff
@@ -507,6 +507,63 @@ SortOp::reifyResultShapes(OpBuilder &b,
...
+  SmallVector<bool> resUsed = llvm::map_to_vector(results, used);
+  SmallVector<bool> argsUsed = llvm::map_to_vector(blockArgs, used);
```
Comment (pashu123) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]:
```suggestion
 SmallVector<bool> isResultIdxUsed = llvm::map_to_vector(results, used);
SmallVector<bool> isArgIdxUsed = llvm::map_to_vector(blockArgs, used);
``` Looks more descriptive.

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp [hunk 12]
```diff
@@ -507,6 +507,63 @@ SortOp::reifyResultShapes(OpBuilder &b,
...
+  // Each result of this DPS op is associated to two block arguments.
+  for (int i = 0; i < blockArgs.size(); i = i + 2) {
+    if (resUsed[i / 2] || argsUsed[i] || argsUsed[i + 1]) {
+      newOperands.push_back(operands[i / 2]);
+      usedResults.push_back(results[i / 2]);
+      newResultTypes.push_back(results[i / 2].getType());
+      argsUsed[i] = true;
+      argsUsed[i + 1] = true;
+    }
+  }
```
Comment (pashu123) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: Instead of iterating over blockArgs, could you iterate over argsUsed? Do something like llvm::enumerate. I am just thinking of how this can be simplified.

File: compiler/src/iree/compiler/Codegen/Common/GPU/Passes.td [hunk 13]
```diff
@@ -209,6 +209,15 @@ def GPUPromoteMatmulOperandsPass :
   ];
 }
 
+def GPUPruneDPSOpsPass :
+    InterfacePass<"iree-codegen-gpu-prune-dps-ops", "mlir::FunctionOpInterface"> {
+  let summary = "Pass to add private memory allocations to DPS interface ops.";
```
Comment (pashu123) [inline compiler/src/iree/compiler/Codegen/Common/GPU/Passes.td]: Please add a description of why we need this pass.

File: compiler/src/iree/compiler/Codegen/Common/GPU/test/gpu_prune_dps_ops.mlir [hunk 14]
```diff
@@ -0,0 +1,89 @@
...
+  %1 = hal.interface.constant.load layout(<constants = 2, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) ordinal(1) : i32
+  %2 = arith.extui %0 : i32 to i64
+  %3 = arith.extui %1 : i32 to i64
+  %4 = arith.shli %3, %c32_i64 : i64
+  %5 = arith.ori %2, %4 : i64
+  %6 = arith.index_castui %5 : i64 to index
+  %7 = util.assume.int %6<umin = 0, umax = 9007199254740991> : index
+  %8 = iree_tensor_ext.dispatch.workload.ordinal %7, 0 : index
+  %9 = hal.interface.binding.subspan layout(<constants = 2, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%c0) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<?x10xf32>>{%8}
+  %10 = hal.interface.binding.subspan layout(<constants = 2, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(1) alignment(64) offset(%c0) flags(Indirect) : !iree_tensor_ext.dispatch.tensor<readwrite:tensor<?x10xi64>>{%8}
```
Comment (pashu123) [inline compiler/src/iree/compiler/Codegen/Common/GPU/test/gpu_prune_dps_ops.mlir]: You can reuse the pipeline layout. Just pull it out and reuse. See https://github.com/iree-org/iree/blob/5bad3ba07f1e5081f9a82d39c7a7943df2efc384/compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/config_vector_distribute_reduction_gfx942.mlir#L186

**Review by pashu123 — COMMENTED** [review]
Nice work! Some comments.

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp (hunk 12 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: That would be cleaner let me try that!

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 5 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: The fix is at flow level and I'm not sure what it would involve specifically.
@MaheshRavishankar thoughts?

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 8 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: +1

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp (hunk 4 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: Sorry, I meant to say pull this into its own PR.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 5 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: The extent to my understanding for a fix is the phrase "Ensuring operands of DPS operations are tied to dispatches appropriately" which I would need to do some homework on Dispatch Region Formation to flesh out.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 15]
```diff
@@ -0,0 +1,110 @@
...
+
+  bufferization::BufferizationOptions options;
+  options.defaultMemorySpaceFn =
+      [&p = privSpace](TensorType t) -> std::optional<Attribute> { return p; };
+  bufferization::AnalysisState analysisState(options);
+
+  // Check if this is an op that doesn't change the address space
+  // and is neither a consumer nor producer.
+  auto isPassThroughOp = [](Operation *op) -> bool {
+    return llvm::isa<tensor::ExtractSliceOp, tensor::DimOp>(op);
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: Does this also include stuff like `pad` or `pack`?

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 16]
```diff
@@ -0,0 +1,110 @@
...
+      worklist.push_back({dpsOp, idx});
+    }
+    return WalkResult::advance();
+  });
+  if (res.wasInterrupted()) {
+    return signalPassFailure();
+  }
+  // Create alloc in private space for each dps op and set it as the new
+  // in-place result.
+  for (auto [dpsOp, idx] : worklist) {
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: ... Really silly question. Isn't all this logic equivalent to the much simpler test of ensuring that the corresponding *result* has no uses? That is, if the result tied to the init has no uses, then that init can be replaced by a fresh private allocation?

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp [hunk 17]
```diff
@@ -507,6 +507,62 @@ SortOp::reifyResultShapes(OpBuilder &b,
       .reifyResultShapes(b, reifiedReturnShapes);
 }
 
+LogicalResult SortOp::canonicalize(SortOp sortOp, PatternRewriter &rewriter) {
+  // To avoid problems in dispatches associated with unused results, prune them
+  // here.
+  auto loc = sortOp->getLoc();
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: Nit on auto

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp [hunk 18]
```diff
@@ -507,6 +507,62 @@ SortOp::reifyResultShapes(OpBuilder &b,
       .reifyResultShapes(b, reifiedReturnShapes);
 }
 
+LogicalResult SortOp::canonicalize(SortOp sortOp, PatternRewriter &rewriter) {
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: This might make more sense as canonicalization patterns in case we end up with more canonicalizations to do

**Review by krzysz00 — COMMENTED** [review]
One big note

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 16 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: I think this logic is a stronger (more specific) condition than checking if the result has no uses. 

We check two conditions when iterating over the operands of a DPS op here:
- (1) check if the associated result has no uses
- (2) check if the operand is going to bufferize to global addr space

So, we only change to private if both (1) and (2) are true. Not just (1). 
I'm worried about the case where the producer for an unused result is something that wouldn't have a global addr space, like an add op or something. In that case I imagine we wouldn't run into this bufferization issue, since it would choose private or shared mem space when bufferizing that add. 

But also I don't understand this pass fully which is why I'm erring on the side of caution and choosing the stronger condition. Perhaps I should do more investigation.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 15 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: I think it should? Ill add them!

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp (hunk 18 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: This is harder than I first thought. It's hard to generalize the analysis over regions. For example, within the Sort Op's region there is a mapping of a given operand to two associated block arguments. I'm not sure this would be the same for another op, so removal of block arguments becomes difficult unless I make some baseless assumptions.

Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: Oh you mean that we add this to the SortOp's list of canonicalization patterns, nevermind i thought you were asking for this to be a templated pattern to be used to canonicalize other ops.

Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: ignore my first reply

**Comment by Muzammiluddin-Syed-ECE** [comment]
[Time out failure on punet](https://github.com/iree-org/iree/actions/runs/15008255749/job/42172277836?pr=20793) ~~hoping~~ wondering if this is a flakey test. 

edit: wrong thing to hope for

**Comment by MaheshRavishankar** [comment]
> [Time out failure on punet](https://github.com/iree-org/iree/actions/runs/15008255749/job/42172277836?pr=20793) ~~hoping~~ wondering if this is a flakey test. 
> 
> edit: wrong thing to hope for

Oh oh!!

**Comment by Muzammiluddin-Syed-ECE** [comment]
Upon rerun causes [regression](https://github.com/iree-org/iree/actions/runs/15008255749/job/42172277836?pr=20793#step:9:157) in `sdxl::vae_rocm`:

```
=========================== short test summary info ============================
ERROR iree-test-suites/sharktank_models/benchmarks/model_benchmark_run.py::sdxl :: vae_rocm - check 69.08412174787372 <= 68.2: sdxl vae benchmark time should not regress more than a factor of 1.1
iree-test-suites/sharktank_models/benchmarks/model_benchmark_run.py:233 in runtest() -> check.less_equal(
```

**Comment by Muzammiluddin-Syed-ECE** [comment]
> Upon rerun causes [regression](https://github.com/iree-org/iree/actions/runs/15008255749/job/42172277836?pr=20793#step:9:157) in `sdxl::vae_rocm`:
> 
> ```
> =========================== short test summary info ============================
> ERROR iree-test-suites/sharktank_models/benchmarks/model_benchmark_run.py::sdxl :: vae_rocm - check 69.08412174787372 <= 68.2: sdxl vae benchmark time should not regress more than a factor of 1.1
> iree-test-suites/sharktank_models/benchmarks/model_benchmark_run.py:233 in runtest() -> check.less_equal(
> ```

Actually this regression also affected [an unrelated PR](https://github.com/iree-org/iree/actions/runs/15019382132/job/42205259180#step:9:174), implying that perhaps this is not due to this change.

**Comment by Muzammiluddin-Syed-ECE** [comment]
> > Upon rerun causes [regression](https://github.com/iree-org/iree/actions/runs/15008255749/job/42172277836?pr=20793#step:9:157) in `sdxl::vae_rocm`:
> > ```
> > =========================== short test summary info ============================
> > ERROR iree-test-suites/sharktank_models/benchmarks/model_benchmark_run.py::sdxl :: vae_rocm - check 69.08412174787372 <= 68.2: sdxl vae benchmark time should not regress more than a factor of 1.1
> > iree-test-suites/sharktank_models/benchmarks/model_benchmark_run.py:233 in runtest() -> check.less_equal(
> > ```
> 
> Actually this regression also affected [an unrelated PR](https://github.com/iree-org/iree/actions/runs/15019382132/job/42205259180#step:9:174), implying that perhaps this is not due to this change.

@MaheshRavishankar thoughts?

**Comment by pashu123** [comment]
> > > Upon rerun causes [regression](https://github.com/iree-org/iree/actions/runs/15008255749/job/42172277836?pr=20793#step:9:157) in `sdxl::vae_rocm`:
> > > ```
> > > =========================== short test summary info ============================
> > > ERROR iree-test-suites/sharktank_models/benchmarks/model_benchmark_run.py::sdxl :: vae_rocm - check 69.08412174787372 <= 68.2: sdxl vae benchmark time should not regress more than a factor of 1.1
> > > iree-test-suites/sharktank_models/benchmarks/model_benchmark_run.py:233 in runtest() -> check.less_equal(
> > > ```
> > 
> > 
> > Actually this regression also affected [an unrelated PR](https://github.com/iree-org/iree/actions/runs/15019382132/job/42205259180#step:9:174), implying that perhaps this is not due to this change.
> 
> @MaheshRavishankar thoughts?

You can rebase to https://github.com/iree-org/iree/pull/20809 .

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 19]
```diff
@@ -0,0 +1,111 @@
...
+      bool globalProducer = llvm::all_of(producers, arePartOfGlobalChain);
+      if (!globalProducer)
+        continue;
+      worklist.push_back({dpsOp, idx});
+    }
+    return WalkResult::advance();
+  });
+  if (res.wasInterrupted()) {
+    return signalPassFailure();
+  }
```
Comment (rkayaith) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: the walk doesn't ever skip/interrupt, so you could just remove this and use the `void`-returning `walk` overload.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 5 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: I think you can add something like. "For such cases, need to make Flow preserve the unused result as a result of the dispatch"

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 20]
```diff
@@ -0,0 +1,111 @@
...
+  // Create alloc in private space for each dps op and set it as the new
+  // in-place result.
+  for (auto [dpsOp, idx] : worklist) {
+    OpOperand *value = dpsOp.getDpsInitOperand(idx);
+    PatternRewriter rewriter(dpsOp->getContext());
+    rewriter.setInsertionPoint(dpsOp);
+    FailureOr<Value> copy = allocateTensorForShapedValue(
+        rewriter, dpsOp->getLoc(), value->get(), options, true);
+    if (failed(copy))
+      WalkResult::interrupt();
```
Comment (rkayaith) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: this is outside the walk, so here you want either `continue` or `emitError`+`signalPassFailure`, depending on whether this should be considered an error (should probably have a test that hits this)

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 21]
```diff
@@ -0,0 +1,111 @@
...
+    return llvm::isa<IREE::TensorExt::DispatchTensorLoadOp>(op);
+  };
+
+  // Iterate over all DPS ops, collecting ops to modify.
+  SmallVector<std::pair<DestinationStyleOpInterface, int>> worklist;
+  WalkResult res = funcOp.walk([&](DestinationStyleOpInterface dpsOp) {
+    for (int idx = 0; idx < dpsOp.getNumDpsInits(); ++idx) {
+      OpOperand *value = dpsOp.getDpsInitOperand(idx);
+      // If the associated result is used, do nothing.
+      if (!dpsOp->getResult(idx).use_empty()) {
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: I think I would also add a check for the size. Really large private allocations will just kill the compiler. So maybe keep a size to the next power of 2 bytes that the filed issue is hitting.

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp [hunk 22]
```diff
@@ -507,6 +507,76 @@ SortOp::reifyResultShapes(OpBuilder &b,
       .reifyResultShapes(b, reifiedReturnShapes);
 }
 
+namespace {
+struct RemoveUnusedDPSOpResults
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: Can you move these changes to a different PR? They are unrelated, its better to land them as separate PRs.

**Review by MaheshRavishankar — APPROVED** [review]

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 5 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: If there is an issue, you can do `TODO(#XXXX): action item` which provides more context to future contributors.

Otherwise, the comment is meaningless.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 23]
```diff
@@ -0,0 +1,111 @@
...
+    : impl::GPUPruneDPSOpsPassBase<GPUPruneDPSOpsPass> {
+  void runOnOperation() override;
+};
+
+void GPUPruneDPSOpsPass::runOnOperation() {
+  MLIRContext *context = &getContext();
+  FunctionOpInterface funcOp = getOperation();
+
+  gpu::AddressSpaceAttr privSpace = gpu::AddressSpaceAttr::get(
+      context, gpu::GPUDialect::getPrivateAddressSpace());
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: style nit: use auto because `XXX:get` already spells the type. 

https://llvm.org/docs/CodingStandards.html#use-auto-type-deduction-to-make-code-more-readable

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 19 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: +1

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 24]
```diff
@@ -0,0 +1,111 @@
...
+  // in-place result.
+  for (auto [dpsOp, idx] : worklist) {
+    OpOperand *value = dpsOp.getDpsInitOperand(idx);
+    PatternRewriter rewriter(dpsOp->getContext());
+    rewriter.setInsertionPoint(dpsOp);
+    FailureOr<Value> copy = allocateTensorForShapedValue(
+        rewriter, dpsOp->getLoc(), value->get(), options, true);
+    if (failed(copy))
+      WalkResult::interrupt();
+    auto alloc = dyn_cast<bufferization::AllocTensorOp>(copy->getDefiningOp());
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: If you're not going to check the failure and the assumption is that it is always AllocTensorOp, you should use `cast`

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 25]
```diff
@@ -0,0 +1,111 @@
...
+
+  // Check if this is an op that doesn't change the address space
+  // and is neither a consumer nor producer.
+  auto isPassThroughOp = [](Operation *op) -> bool {
+    return llvm::isa<linalg::PackOp, tensor::ExtractSliceOp, tensor::DimOp,
+                     tensor::PadOp>(op);
+  };
+  auto isGlobalLoadOp = [](Operation *op) -> bool {
+    return llvm::isa<IREE::TensorExt::DispatchTensorLoadOp>(op);
+  };
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: nit: drop `llvm::` prefix.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 26]
```diff
@@ -0,0 +1,111 @@
...
+    FailureOr<Value> copy = allocateTensorForShapedValue(
+        rewriter, dpsOp->getLoc(), value->get(), options, true);
+    if (failed(copy))
+      WalkResult::interrupt();
+    auto alloc = dyn_cast<bufferization::AllocTensorOp>(copy->getDefiningOp());
+    alloc.setMemorySpaceAttr(privSpace);
+    rewriter.modifyOpInPlace(dpsOp,
+                             [&idx = idx, &dpsOp = dpsOp, &copy = copy]() {
+                               dpsOp.setDpsInitOperand(idx, *copy);
+                             });
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: I'd just use `[&]` to make it simple. The scope of the function is not that big, IMO.

File: compiler/src/iree/compiler/Codegen/Common/GPU/test/gpu_prune_dps_ops.mlir
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/test/gpu_prune_dps_ops.mlir:1]: Can you simplify the tests? I think those bindings, forall, extract slices are not needed in the test?

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp (hunk 22 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: +1

nit: should it be applied to other LinalgExt ops? If not, maybe rename it to RemoveUnusedSortOpResults.

**Review by hanhanW — CHANGES_REQUESTED** [review]

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 26 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: [I run into an issue with & not capturing loop variables that are part of a tuple](https://stackoverflow.com/questions/46114214/lambda-implicit-capture-fails-with-variable-declared-from-structured-binding). So, the fix seems to be declaring them explicitly.

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: I did not get enough time to review if we can use OpOperand to update it or not. If we can use that, we might not need the pair in the first place. We might not need the`modifyOpInPlace` at all.

FWIW, maybe you can replace the `rewriter.modifyOpInPlase` update with `value->set(*copy)`. (I haven't tried it yet and I don't remember details, so I did not make the suggestion in the first place.)

I'll take a deeper look later today.

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: > [I run into an issue with & not capturing loop variables that are part of a tuple](https://stackoverflow.com/questions/46114214/lambda-implicit-capture-fails-with-variable-declared-from-structured-binding). So, the fix seems to be declaring them explicitly.

btw, this is something new to me, thanks for sharing!

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 20 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: encountering this error would require having non shaped types which would be really strange at this stage so i'll leave it as just a signalPassFailure maybe?

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 21 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: Added test to verify this also.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 26 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: Ah the `value->set(*copy)` way of doing it is much cleaner, thanks!

File: compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp (hunk 22 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp]: new PR here: https://github.com/iree-org/iree/pull/20827

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 27]
```diff
@@ -0,0 +1,126 @@
...
+  };
+  auto isGlobalLoadOp = [](Operation *op) -> bool {
+    return isa<IREE::TensorExt::DispatchTensorLoadOp>(op);
+  };
+  // An arbitrary choice of too big.
+  auto isAllocSizeTooBig = [](Type typ) -> bool {
+    auto shapedType = cast<ShapedType>(typ);
+    int allocSize = 1;
+    for (auto dimSize : shapedType.getShape()) {
+      if (ShapedType::isDynamic(dimSize))
```
Comment (pashu123) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: Minor nit: We use braces in IREE project. (I am not a fan, but we use) :)

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 28]
```diff
@@ -0,0 +1,126 @@
...
+          value, stoppingConditionFn);
+
+      // If producer of this OpOperand is some value that isn't a subview or
+      // slice of a global load, do nothing.
+      auto arePartOfGlobalChain = [&](Value a) -> bool {
+        auto op = a.getDefiningOp();
+        return isPassThroughOp(op) || isGlobalLoadOp(op);
+      };
+      bool globalProducer = all_of(producers, arePartOfGlobalChain);
+      if (!globalProducer)
```
Comment (pashu123) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: Braces here.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 29]
```diff
@@ -0,0 +1,126 @@
...
+    }
+  });
+  // Create alloc for each dps op and set it as the new in-place result.
+  for (auto value : worklist) {
+    auto dpsOp = value->getOwner();
+    PatternRewriter rewriter(context);
+    rewriter.setInsertionPoint(value->getOwner());
+    FailureOr<Value> copy = allocateTensorForShapedValue(
+        rewriter, dpsOp->getLoc(), value->get(), options, true);
+    if (failed(copy))
```
Comment (pashu123) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: Same braces here too.

**Review by pashu123 — COMMENTED** [review]
Style nits.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 30]
```diff
@@ -0,0 +1,129 @@
...
+
+  // Check if this is an op that doesn't change the address space
+  // and is neither a consumer nor producer.
+  auto isPassThroughOp = [](Operation *op) -> bool {
+    return isa<linalg::PackOp, tensor::ExtractSliceOp, tensor::DimOp,
+               tensor::PadOp>(op);
+  };
+  auto isGlobalLoadOp = [](Operation *op) -> bool {
+    return isa<IREE::TensorExt::DispatchTensorLoadOp>(op);
+  };
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: Is the comment accurate? What does `is neither a consumer of producer` mean in this context? I only see a single operation in the methods.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 31]
```diff
@@ -0,0 +1,129 @@
...
+void GPUPruneDPSOpsPass::runOnOperation() {
+  MLIRContext *context = &getContext();
+  FunctionOpInterface funcOp = getOperation();
+
+  auto privSpace = gpu::AddressSpaceAttr::get(
+      context, gpu::GPUDialect::getPrivateAddressSpace());
+
+  bufferization::BufferizationOptions options;
+  options.defaultMemorySpaceFn =
+      [&p = privSpace](TensorType t) -> std::optional<Attribute> { return p; };
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: I'm -1 on having an alias for the variable. It adds complex to parse the code. If it matters, make it a local function.

```suggestion
      [&privSpace](TensorType t) -> std::optional<Attribute> { return privSpace; };
```

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 32]
```diff
@@ -0,0 +1,129 @@
...
+    auto shapedType = cast<ShapedType>(typ);
+    int allocSize = 1;
+    for (auto dimSize : shapedType.getShape()) {
+      if (ShapedType::isDynamic(dimSize)) {
+        continue;
+      }
+      allocSize *= dimSize;
+    }
+    return allocSize >= 32;
+  };
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: nit: typ -> type
nit2: Please avoid magic numbers (i.e., 32). You can declare a `constexpr int64_t kAllocationSizeInBytes = 32` before the lambda (i.e., line 55). And the `An arbitrary choise...` comment can be the comment of the variable.

IMO, a local function is a better fit for the lambda. You are not capturing any non-trivial variable in the lambda. If we move it to lambda, you can make the const variable global because you can also use it in the below documentation.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 33]
```diff
@@ -0,0 +1,129 @@
...
+/// Pass to create a `bufferization.alloc_tensor` in private space for all DPS
+/// ops with unused results that can't be removed.
+/// These unused results, if originating from loads from global memory, trigger
+/// allocations in global memory space during bufferization, which will fail.
+/// So, the allocations must be made earlier to avoid failed bufferization.
+/// This pass is a hack to get around other work that can be done to improve
+/// the bufferization algorithm.
+/// For such cases, need to make Flow preserve the unused result as a
+/// result of the dispatch.
+struct GPUPruneDPSOpsPass final
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: I think we need to rename the pass. There is no pruning, IMO. I'm not good at naming, but let me give it a try. How about `GPUAllocPrivateMemoryForDPSOpsPass`?

Also, please do not duplicate the comment. I think the documentation of the pass is in `Passes.td`. And the rest of comment can be:

```suggestion
/// This pass is a hack to get around other work that can be done to improve
/// the bufferization algorithm.
/// For such cases, need to make Flow preserve the unused result as a
/// result of the dispatch.
struct GPUPruneDPSOpsPass final
```

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 34]
```diff
@@ -0,0 +1,129 @@
...
+
+  // Iterate over all DPS ops and their inits, collecting ops to add a
+  // tensor_alloc for.
+  // There are 3 conditions of interest:
+  // 1) The result associated to the current init is unused.
+  // 2) The allocation size if appropriately small.
+  // 3) The reverse use-def chain of this op is a global load followed by ops
+  //    that do not change the address space.
+  // The 3rd condition is not strictly necessary but this is just a precation
+  // given the hacky nature of this fix.
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: For the second point, I think it's worth to mention that dynamic dimension is ignored if it is present. And maybe rephrase it with the new global variable.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 35]
```diff
@@ -0,0 +1,129 @@
...
+      bool globalProducer = all_of(producers, arePartOfGlobalChain);
+      if (!globalProducer) {
+        continue;
+      }
+      worklist.push_back(value);
+    }
+  });
+  // Create alloc for each dps op and set it as the new in-place result.
+  for (auto value : worklist) {
+    auto dpsOp = value->getOwner();
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: If it were me, I'd write `Location loc = value->getOwner().getLoc()`. It is easier for contributors. We don't need to think about why dpsOp is declared. Is it used somewhere? etc

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 36]
```diff
@@ -0,0 +1,129 @@
...
+    PatternRewriter rewriter(context);
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: I think we just need `IRRewriter`, because you don't need anything else from PatternRewriter.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 37]
```diff
@@ -0,0 +1,129 @@
...
+    rewriter.setInsertionPoint(value->getOwner());
+    FailureOr<Value> copy = allocateTensorForShapedValue(
+        rewriter, dpsOp->getLoc(), value->get(), options, true);
+    if (failed(copy)) {
+      return signalPassFailure();
+    }
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: Please emit an error. Otherwise, it just exit(1). The user experience would be very bad.

```suggestion
    if (failed(copy)) {
      funcOp.emitError("....");
      return signalPassFailure();
    }
```

File: compiler/src/iree/compiler/Codegen/Common/GPU/test/gpu_prune_dps_ops.mlir
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/test/gpu_prune_dps_ops.mlir:1]: I was wrong on the previous suggestion about extract_slice, and I'm sorry about that. I think you need more tests to exercise pack/extract_slice/dim/pad ops. The test coverage is not enough for me.

```
    return isa<linalg::PackOp, tensor::ExtractSliceOp, tensor::DimOp,
               tensor::PadOp>(op);
```

**Review by hanhanW — CHANGES_REQUESTED** [review]

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 38]
```diff
@@ -0,0 +1,129 @@
...
+    return isa<linalg::PackOp, tensor::ExtractSliceOp, tensor::DimOp,
+               tensor::PadOp>(op);
+  };
+  auto isGlobalLoadOp = [](Operation *op) -> bool {
+    return isa<IREE::TensorExt::DispatchTensorLoadOp>(op);
+  };
+  // An arbitrary choice of too big.
+  auto isAllocSizeTooBig = [](Type typ) -> bool {
+    auto shapedType = cast<ShapedType>(typ);
+    int allocSize = 1;
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: Nit: int64_t for dimensions

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp [hunk 39]
```diff
@@ -0,0 +1,129 @@
...
+        auto op = a.getDefiningOp();
+        return !isPassThroughOp(op);
+      };
+      SetVector<Value> producers = analysisState.findValueInReverseUseDefChain(
+          value, stoppingConditionFn);
+
+      // If producer of this OpOperand is some value that isn't a subview or
+      // slice of a global load, do nothing.
+      auto arePartOfGlobalChain = [&](Value a) -> bool {
+        auto op = a.getDefiningOp();
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: These could probably be `Operation *`s, not `auto`s

**Review by krzysz00 — COMMENTED** [review]
Minor nitpicking

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 30 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: That is a weirdly worded comment. By not a consumer or producer, I meant an operation that doesn't change the values inside a tensor but instead does data movement or logistical changes? If that makes sense? I think my vocabulary is lacking.

Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: well this is deleted so lets not worry about it

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 32 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: Im not entirely sure what you mean by 
> IMO, a local function is a better fit for the lambda. You are not capturing any non-trivial variable in the lambda. If we move it to lambda, you can make the const variable global because you can also use it in the below documentation.

I assume this statement is in the format: Suggestion -> Explanation. So, the suggestion is to move it to a local function like `isAllocTooBig()` but the explanation is that in lambda's we can make the const variable global. So, I'm confused because it doesn't feel like the last two sentences follow from the first.

File: compiler/src/iree/compiler/Codegen/Common/GPU/test/gpu_prune_dps_ops.mlir
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Codegen/Common/GPU/test/gpu_prune_dps_ops.mlir:1]: The traversal has been removed so this test is no longer covering these cases in its scope.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp (hunk 32 above)
Comment (Muzammiluddin-Syed-ECE) [reply compiler/src/iree/compiler/Codegen/Common/GPU/GPUPruneDPSOps.cpp]: I ended up just making the magic number a global let me know if that is a sufficient change.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUAllocPrivateMemoryForDPSOps.cpp [hunk 40]
```diff
@@ -0,0 +1,95 @@
...
+    }
+  });
+
+  // Create alloc for each dps op and set it as the new in-place result.
+  auto privSpace = gpu::AddressSpaceAttr::get(
+      context, gpu::GPUDialect::getPrivateAddressSpace());
+  bufferization::BufferizationOptions options;
+  for (auto value : worklist) {
+    Location loc = value->getOwner()->getLoc();
+    IRRewriter rewriter(context);
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUAllocPrivateMemoryForDPSOps.cpp]: nit: move it outside the loop, this way we only need to create the rewriter once.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUAllocPrivateMemoryForDPSOps.cpp [hunk 41]
```diff
@@ -0,0 +1,95 @@
...
+    rewriter.setInsertionPoint(value->getOwner());
+    FailureOr<Value> copy = allocateTensorForShapedValue(
+        rewriter, loc, value->get(), options, true);
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUAllocPrivateMemoryForDPSOps.cpp]: IMO, the function argument is not obvious. We can add a comment to improve it. https://google.github.io/styleguide/cppguide.html#Function_Argument_Comments

```suggestion
        rewriter, loc, value->get(), options, /*copy=*/true);
```

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUAllocPrivateMemoryForDPSOps.cpp [hunk 42]
```diff
@@ -0,0 +1,95 @@
...
+    for (int idx = 0; idx < dpsOp.getNumDpsInits(); ++idx) {
+      OpOperand *value = dpsOp.getDpsInitOperand(idx);
+      // If the associated result is used, do nothing.
+      if (!dpsOp->getResult(idx).use_empty()) {
+        continue;
+      }
+      // If the buffer allocation is too large for private space, do nothing.
+      if (isAllocSizeTooBig(value->get().getType())) {
+        continue;
+      }
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUAllocPrivateMemoryForDPSOps.cpp]: I think it is better to remove the comments because you already have good comments above. This chunk is small, which fits the entire screen easily.

**Review by hanhanW — APPROVED** [review]
LGTM % few nits. Thanks for addressing my comments!

Tip: you can put `Fixes https://github.com/iree-org/iree/issues/20699` to the PR description if this is the last PR to fix the issue. Github will close the corresponding issue when you land the PR.

https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
