### PR TITLE
[Codegen][LLVMGPU] Later scf-to-cf to support math.erf 

### LINKED ISSUE #21813: Error: Missing `LLVMTranslationDialectInterface` registration for dialect for op: scf.if
### What happened?

While compiling some of the onnx models for ROCM backend, I am seeing the following error:
```
error: cannot be converted to LLVM IR: missing `LLVMTranslationDialectInterface` registration for dialect for op: scf.if
```
There are 2 different commits https://github.com/iree-org/iree/commit/2c378d0fec99a584923b301c875b08b424525725 and https://github.com/iree-org/iree/commit/8c26dfc0b94918e2599969e07399706c2197a85b that results in the same error.

### Steps to reproduce your issue

Steps to repro the error:
1.) Commit: https://github.com/iree-org/iree/commit/2c378d0fec99a584923b301c875b08b424525725
Compilation command: `iree-compile  --iree-hal-target-backends=rocm --iree-hip-target=gfx942 repro.mlir`
Failing dispatch: https://gist.github.com/vivekkhandelwal1/8758902727e4c67637c9f6bdc1a09426

2.) Commit: https://github.com/iree-org/iree/commit/8c26dfc0b94918e2599969e07399706c2197a85b
Compilation command: `iree-compile  --iree-hal-target-backends=rocm --iree-hip-target=gfx942 repro.mlir`
Failing dispatch: https://gist.github.com/vivekkhandelwal1/2df1928da93127c9d00f82c1f1c76c84

On reverting the respective commits the dispatches compile.

### What component(s) does this issue relate to?

Compiler

### Version information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by newling**
Before this PR, `math-transform` ran after `cf-to-scf`. But `math-transform` introduces `scf.if` when there is a `math.erf`. 

This PR moves `scf-to-cf` later, so that the scf.if can be converted. Fixes https://github.com/iree-org/iree/issues/21813

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp [hunk 1]
```diff
@@ -1090,6 +1088,10 @@ static void addLowerToLLVMGPUPasses(OpPassManager &modulePassManager,
       .addPass(createConvertComplexToStandardPass)
       // Math dialect ops rewrites, approximations, casts.
       .addPass(createMathTransformPass)
+      // SCF -> CF
+      .addPass(createSCFToControlFlowPass)
+      .addPass(createCanonicalizerPass)
+      .addPass(createCSEPass)
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp:1053]: Do we need to run these both at the top and here?

File: tests/e2e/regression/linalg_ops_dynamic.mlir [hunk 2]
```diff
@@ -130,3 +130,39 @@ func.func @softmax_dynamic_reduction_N65_K1531(){
...
+
+  %lhs = flow.tensor.dynamic_constant dense<0.125> : tensor<1x1x64xf32> -> tensor<?x?x64xf32>
+  %rhs = flow.tensor.dynamic_constant dense<0.125> : tensor<1x64x32xf32> -> tensor<?x64x32xf32>
+  %B = tensor.dim %lhs, %c0 : tensor<?x?x64xf32>
+  %M = tensor.dim %lhs, %c1 : tensor<?x?x64xf32>
+
+  %empty = tensor.empty(%B, %M) : tensor<?x?x32xf32>
+  %filled = linalg.fill ins(%c0_f32: f32) outs(%empty : tensor<?x?x32xf32>) -> tensor<?x?x32xf32>
+  %bmm = linalg.batch_matmul ins(%lhs, %rhs : tensor<?x?x64xf32>, tensor<?x64x32xf32>)
+                                    outs(%filled : tensor<?x?x32xf32>) -> tensor<?x?x32xf32>
```
Comment (kuhar) [inline tests/e2e/regression/linalg_ops_dynamic.mlir]:
```suggestion
  %bmm = linalg.batch_matmul ins(%lhs, %rhs : tensor<?x?x64xf32>, tensor<?x64x32xf32>)
                             outs(%filled : tensor<?x?x32xf32>) -> tensor<?x?x32xf32>
```

**Review by kuhar — APPROVED** [review]

**Comment by newling** [comment]
In the most recent commit, I added a numerical test. It shows there are still issues somewhere. Triangulating our state here

- Without the change making scf-to-cf run later, this new test fails compilation as reported in the issue. 
- With the changes, the compilation works, but numerics are off. 
- By forcing the WarpReduction to be used, the numerics are correct. 

Looking at the IRs with WarpReduction vs VectorDistribute, I see that `MathTransformPass` does not change math.erf. I think this is because it has a vector type operand when it is run. When MathTransformPass is run in VectorDistribute, math.erf has a scalar operand. 

In WarpReduction, the math.erf gets converted in ConvertToROCDLPass. I see a 

```
 %128 = llvm.call @__ocml_erf_f32(%127) : (f32) -> f32 
 ```
 
 there. With VectorDistribute, MathTransformPass converts the erf to some fma ops. Possibly related to https://github.com/iree-org/iree/pull/20598

Needs further investigation

**Comment by newling** [comment]
@keshavvinayak01  I'm hitting a math.erf issue in this PR. I was wondering if the approximation in https://github.com/iree-org/iree/pull/20598 has numerical tests?

**Comment by kuhar** [comment]
cc: @bjacob who worked on the lowering of math functions

**Comment by keshavvinayak01** [comment]
> @keshavvinayak01 I'm hitting a math.erf issue in this PR. I was wondering if the approximation in #20598 has numerical tests?

You're right, likely that is the issue. IIUC, the original PR did have inaccurate calculations, but the CI didn't have scalar quality tests, and we did not test for accuracy. [This ](https://github.com/iree-org/iree/pull/21849)PR introduced the vector extension, and I got caught at quality tests, and ended up fixing them; so they pass the CI tests now. I think with the latest PR we will also fix the erf issue you're facing.
