### PR TITLE
Fix stack use-after-free in MaterializeEncodingConversionTarget

### LINKED ISSUE #11220: MaterializeEncodingConversionTarget + Debug + ASan = weird stack-buffer-overflow
STR:

Configure with `Debug` build type and enable ASan:

```
cmake -DCMAKE_BUILD_TYPE=Debug IREE_ENABLE_ASAN=ON
```

Rebuild `iree-compile`.

```
cmake --build . --target iree-compile
```

Run:

```
tools/iree-compile --iree-hal-target-backends=llvm-cpu $HOME/iree/runtime/src/iree/modules/check/test/success.mlir -o /tmp/a.vmfb
```

Result:

https://gist.github.com/bjacob/bd789d070aae45a6848887cef60fe064

I debugged this in GDB. The `op` here is a `arith.constant 0 : index` .   The `getOperands()` returns an empty range, which consists of a `nullptr` base pointer and a `0` length. Then as I step into the `llvm::any_of` at https://github.com/iree-org/iree/blob/1b95a2f285ac8d44e44f06de322abf5b315495bd/llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp#L413 , it immediately triggers the ASan error (above gist link).  Emphasis on *immediately*. So the code that's at fault here is part of the mechanics of the function call to `llvm::any_of`, before the actual start of `llvm::any_of`. Either that, or a miscompile.

### PR DESCRIPTION
**Pull request by bjacob**
Fixes #11220. (thanks to Mahesh for figuring this out!)

### CODE REVIEW

File: llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp [hunk 1]
```diff
@@ -400,21 +400,20 @@ MaterializeEncodingTypeConverter::MaterializeEncodingTypeConverter(
...
-  };
   // Mark any operation that has operands/results with encoding as
   // illegal.
-  auto hasOperandOrResultsWithEncoding = [=](Operation *op) {
-    return llvm::any_of(op->getOperands(), valueHasEncoding) ||
-           llvm::any_of(op->getResultTypes(), typeHasEncoding);
-  };
-  markUnknownOpDynamicallyLegal(
-      [&](Operation *op) { return !hasOperandOrResultsWithEncoding(op); });
+  markUnknownOpDynamicallyLegal([=](Operation *op) {
```
Comment (MaheshRavishankar) [inline llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp:405]: Is this correct. Where is the `typeHasEncoding` method defined?

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]

File: llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp (hunk 1 above)
Comment (bjacob) [reply llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp:405]: oh lol, sorry. so there's actually a fair use for at least the `typeHasEncoding` lambda here. this tips the scale back to some lambda + any_of usage then, how about this.

**Review by MaheshRavishankar — APPROVED** [review]

File: llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp (hunk 1 above)
Comment (bjacob) [reply llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp]: Actually @MaheshRavishankar i pushed another commit replacing two of the `[=]` by `[]` (capture no context at all).
