### PR TITLE
[GPU] Disable unaligned to instrinsic batch matmul codegen with vector distribute

### LINKED ISSUE #18601: [gpu]: error: 'vector.transfer_read' op Anchoring on transfer_read with unsupported number of elements
### What happened?

For the given IR

```mlir
module {
  func.func @torch_jit(%arg0: !torch.vtensor<[1,12,577,64],f32>, %arg1: !torch.vtensor<[1,12,577,577],f32>) -> !torch.vtensor<[1,12,577,64],f32>   attributes {torch.onnx_meta.ir_version = 7 : si64, torch.onnx_meta.opset_version = 21 : si64, torch.onnx_meta.producer_name = "pytorch", torch.onnx_meta.producer_version = "1.12.1"} {
    %1 = torch.operator "onnx.MatMul"(%arg1, %arg0) : (!torch.vtensor<[1,12,577,577],f32>, !torch.vtensor<[1,12,577,64],f32>) -> !torch.vtensor<[1,12,577,64],f32> 
    return %1 : !torch.vtensor<[1,12,577,64],f32>
  }
}
```

getting error as

```
issue1/model.torch_onnx.mlir:3:10: error: 'vector.transfer_read' op Anchoring on transfer_read with unsupported number of elements (not divisible by workgroup size), number of elements: 64, workgroup size: 256
    %1 = torch.operator "onnx.MatMul"(%arg1, %arg0) : (!torch.vtensor<[1,12,577,577],f32>, !torch.vtensor<[1,12,577,64],f32>) -> !torch.vtensor<[1,12,577,64],f32> 
         ^
issue1/model.torch_onnx.mlir:3:10: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"rocm", "rocm-hsaco-fb", {iree.gpu.target = #iree_gpu.target<arch = "gfx942", features = "", wgp = <compute =  fp64|fp32|fp16|int64|int32|int16|int8, storage =  b64|b32|b16|b8, subgroup =  shuffle|arithmetic, dot =  dp4xi8toi32, mma = [<MFMA_F32_16x16x4_F32>, <MFMA_F32_16x16x16_F16>, <MFMA_F32_32x32x8_F16>, <MFMA_F32_16x16x32_F8E4M3FNUZ>, <MFMA_I32_16x16x32_I8>, <MFMA_I32_32x32x16_I8>], subgroup_size_choices = [64], max_workgroup_sizes = [1024, 1024, 1024], max_thread_count_per_workgroup = 1024, max_workgroup_memory_bytes = 65536, max_workgroup_counts = [2147483647, 2147483647, 2147483647]>>, ukernels = "none"}>
    %1 = torch.operator "onnx.MatMul"(%arg1, %arg0) : (!torch.vtensor<[1,12,577,577],f32>, !torch.vtensor<[1,12,577,64],f32>) -> !torch.vtensor<[1,12,577,64],f32> 
         ^
failed to translate executables
(mlir_venv) xhddhirajp40x:/proj/xhdhdstaff6/dhirajp/analysis_gpu_cpu% iree-compile --iree-input-type=auto --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=rocm --mlir-print-debuginfo  --iree-hip-target=gfx942 issue1/model.torch_onnx.mlir
issue1/model.torch_onnx.mlir:3:10: error: 'vector.transfer_read' op Anchoring on transfer_read with unsupported number of elements (not divisible by workgroup size), number of elements: 64, workgroup size: 256
    %1 = torch.operator "onnx.MatMul"(%arg1, %arg0) : (!torch.vtensor<[1,12,577,577],f32>, !torch.vtensor<[1,12,577,64],f32>) -> !torch.vtensor<[1,12,577,64],f32> 
         ^
issue1/model.torch_onnx.mlir:3:10: note: see current operation: %23 = "vector.transfer_read"(%22, %0, %0, %0, %1) <{in_bounds = [true, false, false], operandSegmentSizes = array<i32: 1, 3, 1, 0>, permutation_map = affine_map<(d0, d1, d2) -> (d0, d1, d2)>}> : (memref<1x?x?xf32, strided<[332929, 577, 1], offset: ?>, #hal.descriptor_type<storage_buffer>>, index, index, index, f32) -> vector<1x16x4xf32> loc("issue1/model.torch_onnx.mlir":3:10)
issue1/model.torch_onnx.mlir:3:10: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"rocm", "rocm-hsaco-fb", {iree.gpu.target = #iree_gpu.target<arch = "gfx942", features = "", wgp = <compute =  fp64|fp32|fp16|int64|int32|int16|int8, storage =  b64|b32|b16|b8, subgroup =  shuffle|arithmetic, dot =  dp4xi8toi32, mma = [<MFMA_F32_16x16x4_F32>, <MFMA_F32_16x16x16_F16>, <MFMA_F32_32x32x8_F16>, <MFMA_F32_16x16x32_F8E4M3FNUZ>, <MFMA_I32_16x16x32_I8>, <MFMA_I32_32x32x16_I8>], subgroup_size_choices = [64], max_workgroup_sizes = [1024, 1024, 1024], max_thread_count_per_workgroup = 1024, max_workgroup_memory_bytes = 65536, max_workgroup_counts = [2147483647, 2147483647, 2147483647]>>, ukernels = "none"}>
    %1 = torch.operator "onnx.MatMul"(%arg1, %arg0) : (!torch.vtensor<[1,12,577,577],f32>, !torch.vtensor<[1,12,577,64],f32>) -> !torch.vtensor<[1,12,577,64],f32> 
```

dump.log with option '--mlir-print-ir-after-all --mlir-print-ir-before-all --mlir-disable-threading --mlir-elide-elementsattrs-if-larger=4'

[dump.log](https://github.com/user-attachments/files/17144577/dump.log)

### Steps to reproduce your issue

command to reproduce:

```
iree-compile --iree-input-type=auto --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=rocm --mlir-print-debuginfo --iree-hip-target=gfx942 model.mlir
```

### What component(s) does this issue relate to?

Compiler

### Version information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvedhmeshram**
This path doesnt support all batch matmul shapes but tries to and fails 
e.g. https://github.com/iree-org/iree/issues/18601

So this PR makes this change because by default we should favor  higher functionality support over performance. Solution is to keep this path behind a flag which is off by default.

Fixes : https://github.com/iree-org/iree/issues/18601

If we bail out here, we will go down SIMT (note that we do anyway for non batch matmul GEMMs for such shapes) for now with Tile and Fuse pipeline support planned for the future. In the time being models who have shapes that are supported by this path can do so using the provided flag. And tuners can always use this pipeline if it works for the shape. We can also turn this on by default if we can add correct heuristics on when it is okay to use this path.

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 1]
```diff
@@ -562,7 +568,8 @@ setMatmulVectorDistributionConfig(IREE::GPU::TargetAttr target,
   // Only batch_matmul is supported in the LLVMGPUPadAndVectorDistribute
   // pipeline.
   // TODO(hanchung): Support cases that there are fused producers.
-  if (!schedule && !contractionDims->batch.empty() && !hasFusedLeadingOp(op)) {
+  if (!schedule && !contractionDims->batch.empty() && !hasFusedLeadingOp(op) &&
+      clGPUUnalignedGEMMVectorDistribution) {
```
Comment (Groverkss) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:575]: that is one cursed condition

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 2]
```diff
@@ -62,6 +62,12 @@ llvm::cl::opt<bool> clGPUEnableVectorDistribution(
     llvm::cl::desc("enable the usage of the vector distribution pipeline"),
     llvm::cl::init(true));
 
+llvm::cl::opt<bool> clGPUUnalignedGEMMVectorDistribution(
```
Comment (Groverkss) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:68]: Can we put an TODO pointing to an issue tracking when we can remove this? This is a very hacky flag. Also, why does this exist (sdxl winograd batch matmuls).

**Review by Groverkss — APPROVED** [review]
I don't really like the very very specific case we are sending things down the vector distribute pipeline, but it's okay for now, there are no better alternatives.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp (hunk 1 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:575]: We have to drop it anyway
