### PR TITLE
Gracefully ignore failed driver inits when listing all devices.

### LINKED ISSUE #10090: iree-run-module --list_drivers fails in release builds if you don't have CUDA
### What happened?

```
anush@xeon8375C ~/github/transformer-benchmarks
 % iree-run-module --list_drivers
# ============================================================================
# Available HAL drivers
# ============================================================================
# Use --list_devices={driver name} to enumerate available devices.

            cuda: CUDA (dynamic)
      local-sync: Local execution using a lightweight inline synchronous queue
      local-task: Local execution using the IREE multithreading task system
          vulkan: Vulkan 1.x (dynamic)
anush@xeon8375C ~/github/transformer-benchmarks
 % iree-run-module --list_devices
FLAGS ERROR: (╯°□°)╯︵👻
iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:54: UNAVAILABLE; CUDA runtime library not available; ensure installed and on path
anush@xeon8375C ~/github/transformer-benchmarks
```

### Steps to reproduce your issue

pip install iree nightly builds (which has cuda support) on to a system that doesn't have CUDA. 

```  iree-run-module --list_drivers  ``` will fail. 

### What component(s) does this issue relate to?

_No response_

### Version information

top of main

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benvanik**
If a driver can't be initialized it means it has no devices. Errors when asking for specific devices from a driver will still
be propagated: `--list_devices` will always pass but `--list_devices=driver` will fail if the driver fails.

Fixes #10090.

### CODE REVIEW

File: runtime/src/iree/tooling/device_util.c [hunk 1]
```diff
@@ -106,12 +106,18 @@ static iree_status_t iree_hal_flags_list_driver_devices(
...
   iree_hal_driver_t* driver = NULL;
-  IREE_RETURN_IF_ERROR(iree_hal_driver_registry_try_create(
-      driver_registry, driver_name, host_allocator, &driver));
+  iree_status_t status = iree_hal_driver_registry_try_create(
+      driver_registry, driver_name, host_allocator, &driver);
+  if (!iree_status_is_ok(status)) {
+    // Driver could not be created (not found, unavailable, etc) and so there
+    // are no devices to list.
+    iree_status_ignore(status);
+    return iree_ok_status();
```
Comment (ScottTodd) [inline runtime/src/iree/tooling/device_util.c:115]: How about matching what the CTS does - looking for specific error types?
https://github.com/iree-org/iree/blob/065fe79c7bee919d287aa3cf156e821fb42044db/runtime/src/iree/hal/cts/cts_test_base.h#L45-L56

(that gets fuzzy pretty quickly though, since drivers _can_ return other error types)

Comment (benvanik) [reply runtime/src/iree/tooling/device_util.c:115]: Hmm maybe - the command here is intended to be something that can be passed to xargs and can't have any extra output so there's not much I'd want to do besides ignore it or die, and dying feels wrong for a "list me available for use" command as being unavailable for any reason just means it's not available for use and shouldn't be in the list. Could possibly change behavior based on whether doing `--list_devices` or `--list_devices=cuda`, but eh. Will wait to see if there's more confusion :)

Comment (ScottTodd) [reply runtime/src/iree/tooling/device_util.c:115]: Yeah, we could differentiate between "these are all the devices the program _could try to_ create" and "these are all the devices the program _can successfully_ create"

**Review by ScottTodd — APPROVED** [review]

**Review by ScottTodd — APPROVED** [review]
