### PR TITLE
[SPIRV] Handle sub-byte loads with EmulateNarrowTypes

### LINKED ISSUE #14972: Different results for Vulkan target triples while executing llama2
### What happened?

Llama2 7B and 13B yields correct results for vulkan target triple `ampere-rtx4090-windows`, whereas it leads to bad output in `rdna3-w7900-windows`.

I've narrowed it down to originate from dispatch number 3.

### Steps to reproduce your issue

1. [Llama 7B int4 IR](https://storage.googleapis.com/shark_tank/llama2_7b/unsharded/mlir/llama2_7b_int4.mlir)
2. IREE compile for `ampere-rtx4090-windows` (breaking at `dispatch 3`) :
```
iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary  --iree-hal-target-backends=vulkan --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=false --iree-util-zero-fill-elided-attrs --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false --iree-vulkan-target-triple=ampere-rtx4090-windows --iree-opt-const-expr-hoisting=false --iree-hal-dump-executable-sources-to=hal_sources_nvidia --iree-consteval-jit-debug=true --iree-stream-resource-max-allocation-size=3221225472 --iree-flow-break-dispatch=first_vicuna_forward_dispatch_3_ llama2_7b_int4.mlir -o vulkan_correct_7b.vmfb
```
3. IREE compile for `rdna3-w7900-windows` (breaking at `dispatch 3`):
```
iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary  --iree-hal-target-backends=vulkan --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=false --iree-util-zero-fill-elided-attrs --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false --iree-vulkan-target-triple=rdna3-w7900-windows --iree-opt-const-expr-hoisting=false --iree-hal-dump-executable-sources-to=hal_sources_amd --iree-consteval-jit-debug=true --iree-stream-resource-max-allocation-size=3221225472  --iree-flow-break-dispatch=first_vicuna_forward_dispatch_3_ llama2_7b_int4.mlir -o vulkan_faulty_7b.vmfb
```
4. For the INPUT tensor:
```
tensor([[1, 1128, 1784, 11192, 947, 263, 17205, 505, 29973, 673, 297, 3109, 1135, 29871, 29953, 3838]])
```
vulkan_correct_7b.vmfb gives correct output whereas vulkan_faulty_7b.vmfb doesn't.

Same steps for [Llama 13B int4 IR](https://storage.googleapis.com/shark_tank/llama2_13b/unsharded/mlir/llama2_13b_int4.mlir)

### What component(s) does this issue relate to?

_No response_

### Version information

I verified that this issue is in both IREE/SRT.
```
IREE
    iree-compiler             20230914.645
    iree-runtime              20230914.645
SRT
    iree-compiler             20230913.520
    iree-runtime              20230913.520 
```

### Additional context

I also worked on adding the following script to verify the differing issue via SHARK:
1. [python debug_via_shark.py](https://gist.github.com/Abhishek-Varma/d1de533bd18260559b1b630949e848eb)
2. With the vmfbs generated using the compile commands above (breaking at `dispatch 3`) I observed the following :-
```
7B
ampere-rtx4090-windows
Correct: [-0.269 -0.1919 0.0752 … 0.632 -0.05347 0.378]
rdna3-w7900-windows
Faulty: [0.10675 -0.4026 0.752 … -0.1033 0.624 0.1853]

13B
ampere-rtx4090-windows
Correct: [-0.643 1.396 1.822 … 1.127 1.137 -1.142]
rdna3-w7900-windows
Faulty: [-0.352 0.7744 1.173 … 1.071 1.125 -1.083]
```

### PR DESCRIPTION
**Pull request by qedawkins**
Fixes #14972 by preventing offset calculation from temporarily exceeding the maximum i32 value (for 32 bit indexing) even if the byte offset does not exceed it. Additionally this bring handling of sub-byte loads more in line with other backends.

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp [hunk 1]
```diff
@@ -405,6 +405,18 @@ void ConvertToSPIRVPass::runOnOperation() {
     }
   }
 
+  /// Rewrite exti(bitcast) as a mix of vector.shuffle + bitwise arithmetic to
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp]: nit: extsi, extui, or both?

File: compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp [hunk 2]
```diff
@@ -405,6 +405,18 @@ void ConvertToSPIRVPass::runOnOperation() {
...
+  /// help manage sub-byte types.
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp]: This sounds a bit vague, could you give an example that shows what it means to manage sub-byte types?

File: compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matvec.mlir [hunk 3]
```diff
@@ -100,3 +108,121 @@ hal.executable @i4_dequant_matvec_f16 {
...
+        %17 = flow.dispatch.tensor.load %12, offsets = [0, 0], sizes = [4096, 86], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<4096x86xf16>> -> tensor<4096x86xf16>
+        %18 = flow.dispatch.tensor.load %13, offsets = [0, 0], sizes = [86, 128], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<86x128xf16>> -> tensor<86x128xf16>
+        %19 = tensor.empty() : tensor<4096xf16>
+        %20 = tensor.empty() : tensor<4096x86x128xf16>
+        %21 = linalg.fill ins(%cst : f16) outs(%19 : tensor<4096xf16>) -> tensor<4096xf16>
+        %22 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>, affine_map<(d0, d1, d2) -> (d0, d1)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%15, %16, %17 : tensor<4096x86x128xi4>, tensor<4096x86xf16>, tensor<4096x86xf16>) outs(%20 : tensor<4096x86x128xf16>) {
+        ^bb0(%in: i4, %in_0: f16, %in_1: f16, %out: f16): 
+          %24 = arith.extui %in : i4 to i32
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matvec.mlir:163]: should we add something to demonstrate this also works for extsi?

File: compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp (hunk 1 above)
Comment (qedawkins) [reply compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp]: Both. I'll make it clearer.

File: compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matvec.mlir (hunk 3 above)
Comment (qedawkins) [reply compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matvec.mlir:163]: The patterns responsible for those rewrites are already tested upstream and it would just change the shift instruction used. I can add the test if it's still wanted though.

**Comment by qedawkins** [comment]
This needs a little more investigation based on the PkgCI results. Moving to a draft until I've verified performance locally.
```
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
experimental/regression_suite/tests/pregenerated/test_llama2.py Downloading https://storage.googleapis.com/shark_tank/llama_regression/09152023/llama2_7b_int4_stripped.mlir -> /_work/iree/iree/artifacts/llama2_7b_f16qi4/llama2_7b_int4_stripped.mlir---------------------------------------------------------------------------------------------------------
Benchmark                                               Time             CPU   Iterations UserCounters...
---------------------------------------------------------------------------------------------------------
BM_first_vicuna_forward/process_time/real_time       30.3 ms         6.37 ms           23 items_per_second=32.9727/s
2023-09-25T15:54:53+00:00
Running /_work/iree/iree/venv/lib/python3.11/site-packages/iree/_runtime_libs/iree-benchmark-module
Run on (32 X 5759 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x16)
  L1 Instruction 32 KiB (x16)
  L2 Unified 1024 KiB (x16)
  L3 Unified 98304 KiB (x2)
Load Average: 0.37, 0.09, 0.03
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
----------------------------------------------------------------------------------------------------------
Benchmark                                                Time             CPU   Iterations UserCounters...
----------------------------------------------------------------------------------------------------------
BM_second_vicuna_forward/process_time/real_time       21.9 ms         1.09 ms           32 items_per_second=45.5694/s
: Retrieved 2525199 bytes
```

**Review by MaheshRavishankar — APPROVED** [review]
Looks good to me!

File: compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matvec.mlir (hunk 3 above)
Comment (kuhar) [reply compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matvec.mlir:163]: OK, that's reasonable

**Comment by qedawkins** [comment]
Testing locally it seems like the PkgCI results are noise (we've seen noise like the above before too, so there is a precedent).
```
2023-09-25T14:57:16-04:00
Running /home/quinn/iree-build/tools/iree-benchmark-module
Run on (32 X 5879.88 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x16)
  L1 Instruction 32 KiB (x16)
  L2 Unified 1024 KiB (x16)
  L3 Unified 32768 KiB (x2)
Load Average: 0.43, 0.49, 0.32
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
***WARNING*** Library was built as DEBUG. Timings may be affected.
----------------------------------------------------------------------------------------------------------
Benchmark                                                Time             CPU   Iterations UserCounters...
----------------------------------------------------------------------------------------------------------
BM_second_vicuna_forward/process_time/real_time       8.99 ms         1.06 ms           76 items_per_second=111.2/s
```
If this turns out not to be the case we can revert later.

**Review by kuhar — APPROVED** [review]
LGTM

File: compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp (hunk 2 above)
Comment (qedawkins) [reply compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp]: Does the new comment here explain clearly? Or do you want explicit IR examples as well.
