### PR TITLE
[VM] Fix integer to f64 cast folding

### LINKED ISSUE #22966: Assertion failure in FloatAttr::get during constant folding of vm.cast.ui64.f64
### What happened?

**Description**
The compiler crashes during a transformation pipeline when attempting to constant fold a `vm.cast.ui64.f64` operation. This is potentially due to the VM dialect's folding logic for unsigned integer to double-precision float conversions?

**Output**
```
<unknown>:0: error: FloatAttr type doesn't match the type implied by its value
iree-opt: /workdir/sources/iree/third_party/llvm-project/mlir/include/mlir/IR/StorageUniquerSupport.h:180: static ConcreteT mlir::detail::StorageUserBase<mlir::FloatAttr, mlir::Attribute, mlir::detail::FloatAttrStorage, mlir::detail::AttributeUniquer, mlir::TypedAttr::Trait>::get(mlir::MLIRContext *, Args &&...) [ConcreteT = mlir::FloatAttr, BaseT = mlir::Attribute, StorageT = mlir::detail::FloatAttrStorage, UniquerT = mlir::detail::AttributeUniquer, Traits = <mlir::TypedAttr::Trait>, Args = <mlir::Type &, const llvm::APFloat &>]: Assertion `succeeded( ConcreteT::verifyInvariants(getDefaultDiagnosticEmitFn(ctx), args...))' failed.
Please report issues to https://github.com/iree-org/iree/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: /workdir/builds/iree/tools/iree-opt --iree-codegen-linalg-to-llvm-pipeline=enable-arm-sme --iree-flow-transformation-pipeline  test.mlir
 #0 0x000055aaf15db74b backtrace (/workdir/builds/iree/tools/iree-opt+0x9174b)
 #1 0x00007f9fc91f5828 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /workdir/sources/iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:842:13
 #2 0x00007f9fc91ed5e3 llvm::sys::RunSignalHandlers() /workdir/sources/iree/third_party/llvm-project/llvm/lib/Support/Signals.cpp:109:18
 #3 0x00007f9fc91f82e4 SignalHandler(int, siginfo_t*, void*) /workdir/sources/iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:429:38
 #4 0x00007f9fa330b520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x00007f9fa335f9fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #6 0x00007f9fa330b476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #7 0x00007f9fa32f17f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #8 0x00007f9fa32f171b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #9 0x00007f9fa3302e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#10 0x00007f9fc9390f23 mlir::FloatAttr mlir::detail::StorageUserBase<mlir::FloatAttr, mlir::Attribute, mlir::detail::FloatAttrStorage, mlir::detail::AttributeUniquer, mlir::TypedAttr::Trait>::get<mlir::Type&, llvm::APFloat const&>(mlir::MLIRContext*, mlir::Type&, llvm::APFloat const&) /workdir/sources/iree/third_party/llvm-project/mlir/include/mlir/IR/StorageUniquerSupport.h:179:5
#11 0x00007f9fc9390c69 mlir::FloatAttr::get(mlir::Type, llvm::APFloat const&) /workdir/builds/iree/llvm-project/tools/mlir/include/mlir/IR/BuiltinAttributes.cpp.inc:320:3
#12 0x00007f9fd9a2243b mlir::Attribute mlir::iree_compiler::IREE::VM::constFoldCastOp<mlir::IntegerAttr, mlir::FloatAttr, llvm::APInt, llvm::APFloat, mlir::iree_compiler::IREE::VM::CastUI64F64Op::fold(mlir::iree_compiler::IREE::VM::CastUI64F64OpGenericAdaptor<llvm::ArrayRef<mlir::Attribute> >)::$_47>(mlir::Type, mlir::Attribute, mlir::iree_compiler::IREE::VM::CastUI64F64Op::fold(mlir::iree_compiler::IREE::VM::CastUI64F64OpGenericAdaptor<llvm::ArrayRef<mlir::Attribute> >)::$_47 const&) /workdir/sources/iree/compiler/src/iree/compiler/Dialect/VM/IR/VMOpFolders.cpp:0:12
#13 0x00007f9fd9a2243b mlir::iree_compiler::IREE::VM::CastUI64F64Op::fold(mlir::iree_compiler::IREE::VM::CastUI64F64OpGenericAdaptor<llvm::ArrayRef<mlir::Attribute> >) /workdir/sources/iree/compiler/src/iree/compiler/Dialect/VM/IR/VMOpFolders.cpp:1724:10
#14 0x00007f9fd9653594 llvm::LogicalResult mlir::Op<mlir::iree_compiler::IREE::VM::CastUI64F64Op, mlir::OpTrait::ZeroRegions, mlir::OpTrait::OneResult, mlir::OpTrait::OneTypedResult<mlir::FloatType>::Impl, mlir::OpTrait::ZeroSuccessors, mlir::OpTrait::OneOperand, mlir::OpTrait::OpInvariants, mlir::OpTrait::IREE::VM::ExtF64, mlir::iree_compiler::IREE::VM::VMSerializableOp::Trait, mlir::ConditionallySpeculatable::Trait, mlir::OpTrait::AlwaysSpeculatableImplTrait, mlir::MemoryEffectOpInterface::Trait>::foldSingleResultHook<mlir::iree_compiler::IREE::VM::CastUI64F64Op>(mlir::Operation*, llvm::ArrayRef<mlir::Attribute>, llvm::SmallVectorImpl<mlir::OpFoldResult>&) /workdir/sources/iree/third_party/llvm-project/mlir/include/mlir/IR/OpDefinition.h:1915:38
#15 0x00007f9fd965153e llvm::unique_function<llvm::LogicalResult (mlir::Operation*, llvm::ArrayRef<mlir::Attribute>, llvm::SmallVectorImpl<mlir::OpFoldResult>&) const>::operator()(mlir::Operation*, llvm::ArrayRef<mlir::Attribute>, llvm::SmallVectorImpl<mlir::OpFoldResult>&) const /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/FunctionExtras.h:390:12
#16 0x00007f9fd965153e mlir::RegisteredOperationName::Model<mlir::iree_compiler::IREE::VM::CastUI64F64Op>::foldHook(mlir::Operation*, llvm::ArrayRef<mlir::Attribute>, llvm::SmallVectorImpl<mlir::OpFoldResult>&) /workdir/sources/iree/third_party/llvm-project/mlir/include/mlir/IR/OperationSupport.h:536:14
#17 0x00007f9fc961194d llvm::succeeded(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:67:45
#18 0x00007f9fc961194d mlir::Operation::fold(llvm::ArrayRef<mlir::Attribute>, llvm::SmallVectorImpl<mlir::OpFoldResult>&) /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Operation.cpp:633:7
#19 0x00007f9fc9612b7b llvm::SmallVector<mlir::Attribute, 6u>::~SmallVector() /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/SmallVector.h:1207:18
#20 0x00007f9fc9612b7b mlir::Operation::fold(llvm::SmallVectorImpl<mlir::OpFoldResult>&) /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Operation.cpp:664:1
#21 0x00007f9fc9384893 llvm::failed(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:71:42
#22 0x00007f9fc9384893 mlir::OpBuilder::tryFold(mlir::Operation*, llvm::SmallVectorImpl<mlir::Value>&, llvm::SmallVectorImpl<mlir::Operation*>*) /workdir/sources/iree/third_party/llvm-project/mlir/lib/IR/Builders.cpp:492:7
#23 0x00007f9fdf04fdb8 llvm::failed(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:71:42
#24 0x00007f9fdf04fdb8 (anonymous namespace)::OperationLegalizer::legalizeWithFold(mlir::Operation*) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Transforms/Utils/DialectConversion.cpp:2661:7
#25 0x00007f9fdf028b7e llvm::succeeded(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:67:45
#26 0x00007f9fdf028b7e (anonymous namespace)::OperationLegalizer::legalize(mlir::Operation*) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Transforms/Utils/DialectConversion.cpp:2592:9
#27 0x00007f9fdf027720 llvm::failed(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:71:42
#28 0x00007f9fdf027720 mlir::OperationConverter::convert(mlir::Operation*, bool) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Transforms/Utils/DialectConversion.cpp:3300:7
#29 0x00007f9fdf02b032 llvm::failed(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:71:42
#30 0x00007f9fdf02b032 llvm::LogicalResult mlir::OperationConverter::legalizeOperations<mlir::OperationConverter::applyConversion(llvm::ArrayRef<mlir::Operation*>)::$_21>(llvm::ArrayRef<mlir::Operation*>, mlir::OperationConverter::applyConversion(llvm::ArrayRef<mlir::Operation*>)::$_21, bool) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Transforms/Utils/DialectConversion.cpp:3401:9
#31 0x00007f9fdf02b032 mlir::OperationConverter::applyConversion(llvm::ArrayRef<mlir::Operation*>) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Transforms/Utils/DialectConversion.cpp:3447:26
#32 0x00007f9fdf05edbb applyConversion(llvm::ArrayRef<mlir::Operation*>, mlir::ConversionTarget const&, mlir::FrozenRewritePatternSet const&, mlir::ConversionConfig, (anonymous namespace)::OpConversionMode)::$_42::operator()() const /workdir/sources/iree/third_party/llvm-project/mlir/lib/Transforms/Utils/DialectConversion.cpp:0:30
#33 0x00007f9fdf05edbb void llvm::function_ref<void ()>::callback_fn<applyConversion(llvm::ArrayRef<mlir::Operation*>, mlir::ConversionTarget const&, mlir::FrozenRewritePatternSet const&, mlir::ConversionConfig, (anonymous namespace)::OpConversionMode)::$_42>(long) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:46:12
#34 0x00007f9fdf03fb72 applyConversion(llvm::ArrayRef<mlir::Operation*>, mlir::ConversionTarget const&, mlir::FrozenRewritePatternSet const&, mlir::ConversionConfig, (anonymous namespace)::OpConversionMode) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:0:12
#35 0x00007f9fdf03ff42 mlir::applyPartialConversion(llvm::ArrayRef<mlir::Operation*>, mlir::ConversionTarget const&, mlir::FrozenRewritePatternSet const&, mlir::ConversionConfig) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Transforms/Utils/DialectConversion.cpp:4183:10
#36 0x00007f9fdf03ff42 mlir::applyPartialConversion(mlir::Operation*, mlir::ConversionTarget const&, mlir::FrozenRewritePatternSet const&, mlir::ConversionConfig) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Transforms/Utils/DialectConversion.cpp:4190:10
#37 0x00007f9fd69f83f3 (anonymous namespace)::LowerAffine::runOnOperation() /workdir/sources/iree/third_party/llvm-project/mlir/lib/Conversion/AffineToStandard/AffineToStandard.cpp:564:16
#38 0x00007f9fcae1927a mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_44::operator()() const /workdir/sources/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:613:24
#39 0x00007f9fcae1927a void llvm::function_ref<void ()>::callback_fn<mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_44>(long) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:46:12
#40 0x00007f9fcadf9015 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:0:12
#41 0x00007f9fcadfb631 llvm::failed(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:71:42
#42 0x00007f9fcadfb631 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:688:9
#43 0x00007f9fcae0f4bc mlir::PassManager::runPasses(mlir::Operation*, mlir::AnalysisManager) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:1123:10
#44 0x00007f9fcae0d53c mlir::PassManager::run(mlir::Operation*) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:0:60
#45 0x00007f9fcb095814 llvm::failed(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:71:42
#46 0x00007f9fcb095814 performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:591:7
#47 0x00007f9fcb0936c8 processBuffer(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef, mlir::MlirOptMainConfig const&, mlir::DialectRegistry&, mlir::SourceMgrDiagnosticVerifierHandler*, llvm::ThreadPoolInterface*) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:673:12
#48 0x00007f9fcb0936c8 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_3::operator()(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef, llvm::raw_ostream&) const /workdir/sources/iree/third_party/llvm-project/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:771:12
#49 0x00007f9fcb0936c8 llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_3>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:46:12
#50 0x00007f9fcb09c934 llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>::operator()(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&) const /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:69:12
#51 0x00007f9fcb09c934 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0::operator()(llvm::StringRef) const /workdir/sources/iree/third_party/llvm-project/mlir/lib/Support/ToolUtilities.cpp:94:13
#52 0x00007f9fcb09b351 void llvm::interleave<llvm::StringRef const*, mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0, void llvm::interleave<llvm::SmallVector<llvm::StringRef, 8u>, mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0, llvm::raw_ostream, llvm::StringRef>(llvm::SmallVector<llvm::StringRef, 8u> const&, llvm::raw_ostream&, mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0, llvm::StringRef const&)::'lambda'(), void>(llvm::SmallVector<llvm::StringRef, 8u>, llvm::SmallVector<llvm::StringRef, 8u>, mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0, llvm::raw_ostream) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLExtras.h:2230:16
#53 0x00007f9fcb09b351 void llvm::interleave<llvm::SmallVector<llvm::StringRef, 8u>, mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0, llvm::raw_ostream, llvm::StringRef>(llvm::SmallVector<llvm::StringRef, 8u> const&, llvm::raw_ostream&, mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0, llvm::StringRef const&) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLExtras.h:2250:3
#54 0x00007f9fcb09b351 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Support/ToolUtilities.cpp:97:3
#55 0x00007f9fcb07316e mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) /workdir/sources/iree/third_party/llvm-project/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:776:26
#56 0x00007f9fc8f7b83a llvm::failed(llvm::LogicalResult) /workdir/sources/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:71:42
#57 0x00007f9fc8f7b83a ireeOptMainFromCL(int, char**, llvm::StringRef, mlir::DialectRegistry&) /workdir/sources/iree/compiler/src/iree/compiler/API/Internal/IREEOptToolEntryPoint.cpp:147:7
#58 0x00007f9fc8f7b83a ireeOptRunMain /workdir/sources/iree/compiler/src/iree/compiler/API/Internal/IREEOptToolEntryPoint.cpp:170:14
#59 0x00007f9fa32f2d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#60 0x00007f9fa32f2e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#61 0x000055aaf159fc15 _start (/workdir/builds/iree/tools/iree-opt+0x55c15)
Aborted (core dumped)
```

### Steps to reproduce your issue

**Minimal MLIR program (test.mlir)**
```
"builtin.module"() ({
  "vm.module"() <{sym_name = "test"}> ({
    "vm.func"() <{function_type = () -> ()}> ({
      %0 = "vm.const.i64"() <{value = 4294967295 : i64}> : () -> i64
      %1 = "vm.cast.ui64.f64"(%0) : (i64) -> f64
      "vm.return"() : () -> ()
    }) {sym_name = "test_cast"} : () -> ()
    "vm.module_terminator"() : () -> ()
  }) : () -> ()
}) : () -> ()
```

**Command**
```
iree-opt --iree-codegen-linalg-to-llvm-pipeline=enable-arm-sme --iree-flow-transformation-pipeline test.mlir
```

### What component(s) does this issue relate to?

MLIR

### Version information

[d4b9bb0150db9e3c20673c912cb785e988846936](https://github.com/iree-org/iree/commit/d4b9bb0150db9e3c20673c912cb785e988846936)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sommerlukas**
Fix the VM dialect constant folders for integer to float64 type casts.

Incorrectly using a float(32) zero value for initialization leads to a mismatch in float semantics between initial and converted value.

This is based on the bug reported from fuzzing and fixes https://github.com/iree-org/iree/issues/22966.

### CODE REVIEW

File: compiler/src/iree/compiler/Dialect/VM/IR/VMOpFolders.cpp [hunk 1]
```diff
@@ -1714,7 +1714,7 @@ OpFoldResult CastSI64F64Op::fold(FoldAdaptor operands) {
   return constFoldCastOp<IntegerAttr, FloatAttr>(
       Float64Type::get(getContext()), operands.getOperand(),
       [&](const APInt &a) {
-        APFloat b = APFloat(0.0f);
+        APFloat b = APFloat(0.0);
```
Comment (kuhar) [inline compiler/src/iree/compiler/Dialect/VM/IR/VMOpFolders.cpp]:
```suggestion
        APFloat b(0.0);
```

File: compiler/src/iree/compiler/Dialect/VM/IR/VMOpFolders.cpp [hunk 2]
```diff
@@ -1724,7 +1724,7 @@ OpFoldResult CastUI64F64Op::fold(FoldAdaptor operands) {
...
```
Comment (kuhar) [inline compiler/src/iree/compiler/Dialect/VM/IR/VMOpFolders.cpp]:
```suggestion
        APFloat b(0.0);
```

**Review by kuhar — APPROVED** [review]
