### PR TITLE
[VectorDistribution] Add better verifiers for anchors in layout analysis

### LINKED ISSUE #16119: [VectorDistribution] Do not crash on invalid layouts
The vector layout analysis has some assertions that can be triggered on invalid layouts, for example:
```c++
  void setInnerLayout(const VectorLayoutInterface &layout) {
    assert(!layout || layout.isValidLayout(getValue().getType().getShape()));
    vectorLayout = layout;
  }
```

This breaks the mlir-wide assumption that passes are robust given any input IR.
Instead, we should emit op errors and gracefully fail vector distribution.

### PR DESCRIPTION
**Pull request by Groverkss**
This patch moves the layout verification on anchoring for layout analysis. This allows for giving better error messages and graceful failure during vector distribution instead of crashing during the analysis.

Fixes #16119

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/Common/VectorLayoutAnalysis.cpp [hunk 1]
```diff
@@ -987,6 +974,20 @@ DistributionLayout *EnforceLayout::getLatticeElement(Value val) {
 ///        VectorLayoutAnalysis
 /// ==========================================================================
 
+LogicalResult VectorLayoutAnalysis::setAnchor(Value val, Attribute layout) {
+  VectorLayoutInterface layoutInterface =
+      dyn_cast<VectorLayoutInterface>(layout);
+  assert(layoutInterface &&
+         "expected layout to implement VectorLayoutInterface");
+  auto typedVal = dyn_cast<TypedValue<VectorType>>(val);
+  assert(typedVal && "expected value to be a vector type");
```
Comment (qedawkins) [inline compiler/src/iree/compiler/Codegen/Common/VectorLayoutAnalysis.cpp:980]: I think it would be better to take the `VectorLayoutInterface` directly as an argument instead of casting. IIUC most places where we set anchors, we're directly constructing a layout attr. Maybe for the typed value too? I could go either way on that one though.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorDistribute.cpp [hunk 2]
```diff
@@ -184,38 +191,38 @@ class ContractionVectorLayoutOptions : public VectorLayoutOptions {
...
           return llvm::isa<vector::ContractionOp>(op);
         })) {
-      return;
+      return success();
     }
 
     // TODO: Support masking.
     if (transfer.getMask()) {
-      return;
+      return success();
```
Comment (qedawkins) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorDistribute.cpp]: This should return failure so that we don't leave this as undistributed. This check also should probably be moved to after the shared memory address space check.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorDistribute.cpp [hunk 3]
```diff
@@ -184,38 +191,38 @@ class ContractionVectorLayoutOptions : public VectorLayoutOptions {
...
     }
     numElementsPerThread =
         std::min(numElementsPerThread, flatNumElements / flatNumThreads);
 
     AffineMap transferMap = transfer.getPermutationMap();
     if (transferMap.getNumDims() == 0) {
-      return;
+      return success();
```
Comment (qedawkins) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorDistribute.cpp]: Ditto, these three successes should be failures because we don't want to leave undistributed reads behind.

**Review by qedawkins — APPROVED** [review]
Awesome cleanup, thanks!

File: compiler/src/iree/compiler/Codegen/Common/VectorLayoutAnalysis.cpp (hunk 1 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/Common/VectorLayoutAnalysis.cpp:980]: I changed VectorLayoutInterface to be the argument type. I think I'll do TypedValue for a separate patch since it will involve changing things at a lot of places.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorDistribute.cpp (hunk 2 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorDistribute.cpp]: makes sense, done.

File: compiler/src/iree/compiler/Codegen/Common/VectorLayoutAnalysis.cpp (hunk 1 above)
Comment (qedawkins) [reply compiler/src/iree/compiler/Codegen/Common/VectorLayoutAnalysis.cpp:980]: Sounds good, but I could go either way. If it requires changing in a lot of places where we basically are just moving the cast out of the `setAnchor` function, probably not worth doing. I'll approve whatever you pick though :)

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorDistribute.cpp (hunk 3 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorDistribute.cpp]: done

File: compiler/src/iree/compiler/Codegen/Common/VectorLayoutAnalysis.cpp (hunk 1 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/Common/VectorLayoutAnalysis.cpp:980]: Sounds good :)
