### PR TITLE
Fixing global symbol replacement when referenced by non-load ops.

### LINKED ISSUE #17825: Deduplication of global constants leaves dangling hal.device.affinity reference
### What happened?

Running the input IR

```mlir
#executable_target_rocm_hsaco_fb = #hal.executable.target<"rocm", "rocm-hsaco-fb", {iree.gpu.target = #iree_gpu.target<arch = "gfx908", features = "", wgp = <compute =  fp64|fp32|fp16|int64|int32|int16|int8, storage =  b64|b32|b16|b8, subgroup =  shuffle|arithmetic, dot =  dp4xi8toi32, mma = [<MFMA_F16_16x16x16_F32>, <MFMA_F16_32x32x8_F32>], subgroup_size_choices = [64], max_workgroup_sizes = [1024, 1024, 1024], max_thread_count_per_workgroup = 1024, max_workgroup_memory_bytes = 65536>>, ukernels = "none"}>
#device_target_rocm = #hal.device.target<"rocm", {legacy_sync}, [#executable_target_rocm_hsaco_fb]> : !hal.device
module attributes {stream.affinity.default = #hal.device.affinity<@dev_a>} {
  util.global private @dev_a = #device_target_rocm
  util.global private @dev_b = #device_target_rocm
  util.func public @main(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub, iree.reflection = {iree.abi.declaration = "sync func @main(%input0: tensor<4x5xi32>, %input1: tensor<4x5xi32>) -> (%output0: tensor<4x5xi32>)"}} {
    %0 = hal.tensor.import %arg0 "input0" : !hal.buffer_view -> tensor<4x5xi32>
    %1 = hal.tensor.import %arg1 "input1" : !hal.buffer_view -> tensor<4x5xi32>
    %2 = flow.tensor.transfer %0 : tensor<4x5xi32> to #hal.device.affinity<@dev_a>
    %3 = flow.tensor.transfer %1 : tensor<4x5xi32> to #hal.device.affinity<@dev_b>
    %4 = arith.maxsi %2, %3 : tensor<4x5xi32>
    %5 = hal.tensor.export %4 "output0" : tensor<4x5xi32> -> !hal.buffer_view
    util.return %5 : !hal.buffer_view
  }
}
```

through `iree-util-fold-globals` (in particular `deduplicateConstantGlobals`) leaves a dangling reference to `#hal.device.affinity<@dev_b>`.

```mlir
// -----// IR Dump After FoldGlobals (iree-util-fold-globals) //----- //
#executable_target_rocm_hsaco_fb = #hal.executable.target<"rocm", "rocm-hsaco-fb", {iree.gpu.target = #iree_gpu.target<arch = "gfx908", features = "", wgp = <compute =  fp64|fp32|fp16|int64|int32|int16|int8, storage =  b64|b32|b16|b8, subgroup =  shuffle|arithmetic, dot =  dp4xi8toi32, mma = [<MFMA_F16_16x16x16_F32>, <MFMA_F16_32x32x8_F32>], subgroup_size_choices = [64], max_workgroup_sizes = [1024, 1024, 1024], max_thread_count_per_workgroup = 1024, max_workgroup_memory_bytes = 65536>>, ukernels = "none"}>
#map = affine_map<(d0, d1) -> (d0, d1)>
#device_target_rocm = #hal.device.target<"rocm", {legacy_sync}, [#executable_target_rocm_hsaco_fb]> : !hal.device
module attributes {stream.affinity.default = #hal.device.affinity<@dev_a>} {
  util.global private @dev_a = #device_target_rocm
  util.func public @main(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub, iree.reflection = {iree.abi.declaration = "sync func @main(%input0: tensor<4x5xi32>, %input1: tensor<4x5xi32>) -> (%output0: tensor<4x5xi32>)"}} {
    %0 = hal.tensor.import %arg0 "input0" : !hal.buffer_view -> tensor<4x5xi32>
    %1 = hal.tensor.import %arg1 "input1" : !hal.buffer_view -> tensor<4x5xi32>
    %2 = flow.tensor.transfer %0 : tensor<4x5xi32> to #hal.device.affinity<@dev_a>
    %3 = flow.tensor.transfer %1 : tensor<4x5xi32> to #hal.device.affinity<@dev_b>
    %4 = linalg.generic {indexing_maps = [#map, #map, #map], iterator_types = ["parallel", "parallel"]} ins(%2, %3 : tensor<4x5xi32>, tensor<4x5xi32>) outs(%2 : tensor<4x5xi32>) {
    ^bb0(%in: i32, %in_0: i32, %out: i32):
      %6 = arith.maxsi %in, %in_0 : i32
      linalg.yield %6 : i32
    } -> tensor<4x5xi32>
    %5 = hal.tensor.export %4 "output0" : tensor<4x5xi32> -> !hal.buffer_view
    util.return %5 : !hal.buffer_view
  }
}
```

### Steps to reproduce your issue

```
iree-opt --iree-util-fold-globals input.mlir
```

### What component(s) does this issue relate to?

Compiler

### Version information

This is on work that is still in progress at #17482 
I ran it on b355cfbe1e26be8f66959a5ecda1eb2b2dd9f436

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benvanik**
This cleans up the code used in FoldGlobalsPass/FuseGlobalsPass and extends it to support ops that reference globals as if they are loads.

Fixes #17825.

### CODE REVIEW

File: compiler/src/iree/compiler/Dialect/Util/Analysis/GlobalTable.h [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+  // All util.global.store ops referencing the global.
+  SmallVector<IREE::Util::GlobalStoreOpInterface> storeOps;
+  // All other operations that reference the global via an attribute.
+  SmallVector<Operation *> referencingOps;
+
+  // Returns the symbol name of the global op.
+  StringRef getName() { return op.getGlobalName().getValue(); }
+
+  // Returns true if the global is a candidate for folding.
+  bool isCandidate() { return !isIndirect && op.isGlobalPrivate(); }
```
Comment (ScottTodd) [inline compiler/src/iree/compiler/Dialect/Util/Analysis/GlobalTable.h:45]: (this code was mostly moved from the other file, but still wanted to say how much I like this code pattern)

These helper functions for seemingly trivial composite conditions have been really helpful with enhancing readability at call sites and making changes to the conditions easier in the future. Thanks!

**Review by ScottTodd — APPROVED** [review]

**Comment by benvanik** [comment]
Pushing past busted mi300 bot.
