### PR TITLE
Fixing CSE of hoisted encoding ops.

### LINKED ISSUE #21659: [DT] Encode Weights in Initializers w/o Increased Memory Footprint
With encoded weights, we see 2-3x increased memory footprint from initialization. This is because the same weights are used multiple times for prefill and decode and stored in separate globals. We should try to improve this to 1x. This requires that all encodings result in the same layout and avoid multiple globals.

**Immediate action items:**
1. Generate a simpler repro from llama model, mainly for compile-time issue.
2. Make the toy repro result in the same layout.

**Upcoming tasks:**
1. If we can't resolve them in the same layout during compile-time, we'll investigate and scope the work in goal (2).

cc @hanhanW @Max191

### PR DESCRIPTION
**Pull request by benvanik**
A bug in the fixed-point iteration applying cleanup during the stream phase and the `IREE::Stream::AsyncTransferOp` not being marked pure were preventing us from CSEing entire DAGs of work in hoisted initializers.

Example before (same parameter encoded twice and then stored in memory as two distinct buffers):
```
  util.initializer {
    %cst = stream.tensor.constant on(#hal.device.affinity<@__device_0>) : tensor<4096x4096xf8E4M3FNUZ> in !stream.resource<constant> = #stream.parameter.named<"model"::"blk.0.attn_q.weight:qs"> : tensor<4096x4096xf8E4M3FNUZ>
    %0 = stream.resource.size %cst : !stream.resource<constant>
    util.global.store %cst, @"__auto.blk.0.attn_q.weight:qs" : !stream.resource<constant>
    util.global.store %0, @"__auto.blk.0.attn_q.weight:qs__size" : index
    %__auto.blk.0.attn_q.weight3Aqs__size = util.global.load @"__auto.blk.0.attn_q.weight:qs__size" : index
    %__auto.blk.0.attn_q.weight3Aqs = util.global.load @"__auto.blk.0.attn_q.weight:qs" : !stream.resource<constant>
    %1 = stream.async.transfer %__auto.blk.0.attn_q.weight3Aqs : !stream.resource<constant>{%__auto.blk.0.attn_q.weight3Aqs__size} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<*>{%__auto.blk.0.attn_q.weight3Aqs__size}
    %2 = stream.tensor.sizeof on(#hal.device.affinity<@__device_0>) tensor<4096x4096xf8E4M3FNUZ, #encoding> : index
    %3 = stream.tensor.encode on(#hal.device.affinity<@__device_0>) %1 : tensor<4096x4096xf8E4M3FNUZ> in !stream.resource<*>{%__auto.blk.0.attn_q.weight3Aqs__size} -> tensor<4096x4096xf8E4M3FNUZ, #encoding> in !stream.resource<*>{%2}
    %4 = stream.async.transfer %3 : !stream.resource<*>{%2} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<constant>{%2}
    util.global.store %4, @__hoisted_tensor_4096x4096xf8E4M3FNUZ__encoded : !stream.resource<constant>
    util.global.store %2, @__hoisted_tensor_4096x4096xf8E4M3FNUZ__encoded__size : index
    %__auto.blk.0.attn_q.weight3Aqs__size_0 = util.global.load @"__auto.blk.0.attn_q.weight:qs__size" : index
    %__auto.blk.0.attn_q.weight3Aqs_1 = util.global.load @"__auto.blk.0.attn_q.weight:qs" : !stream.resource<constant>
    %5 = stream.async.transfer %__auto.blk.0.attn_q.weight3Aqs_1 : !stream.resource<constant>{%__auto.blk.0.attn_q.weight3Aqs__size_0} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<*>{%__auto.blk.0.attn_q.weight3Aqs__size_0}
    %6 = stream.tensor.sizeof on(#hal.device.affinity<@__device_0>) tensor<4096x4096xf8E4M3FNUZ, #encoding> : index
    %7 = stream.tensor.encode on(#hal.device.affinity<@__device_0>) %5 : tensor<4096x4096xf8E4M3FNUZ> in !stream.resource<*>{%__auto.blk.0.attn_q.weight3Aqs__size_0} -> tensor<4096x4096xf8E4M3FNUZ, #encoding> in !stream.resource<*>{%6}
    %8 = stream.async.transfer %7 : !stream.resource<*>{%6} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<constant>{%6}
    util.global.store %8, @__hoisted_tensor_4096x4096xf8E4M3FNUZ__encoded_0 : !stream.resource<constant>
    util.global.store %6, @__hoisted_tensor_4096x4096xf8E4M3FNUZ__encoded_0__size : index
    util.return
  }
```

Example after (parameter encoded once and stored in memory once):
```
  util.initializer {
    %cst = stream.tensor.constant on(#hal.device.affinity<@__device_0>) : tensor<4096x4096xf8E4M3FNUZ> in !stream.resource<constant> = #stream.parameter.named<"model"::"blk.0.attn_q.weight:qs"> : tensor<4096x4096xf8E4M3FNUZ>
    %0 = stream.resource.size %cst : !stream.resource<constant>
    %1 = stream.async.transfer %cst : !stream.resource<constant>{%0} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<*>{%0}
    %2 = stream.tensor.sizeof on(#hal.device.affinity<@__device_0>) tensor<4096x4096xf8E4M3FNUZ, #encoding> : index
    %3 = stream.tensor.encode on(#hal.device.affinity<@__device_0>) %1 : tensor<4096x4096xf8E4M3FNUZ> in !stream.resource<*>{%0} -> tensor<4096x4096xf8E4M3FNUZ, #encoding> in !stream.resource<*>{%2}
    %4 = stream.async.transfer %3 : !stream.resource<*>{%2} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<constant>{%2}
    util.global.store %4, @__hoisted_tensor_4096x4096xf8E4M3FNUZ__encoded : !stream.resource<constant>
    util.global.store %2, @__hoisted_tensor_4096x4096xf8E4M3FNUZ__encoded__size : index
    util.return
  }
```

The fixed-point change should be safe but the AsyncTransferOp change may have some unforeseen impacts due to how long it has not been marked pure. There's several places where we treat AsyncTransferOp as pure (removing duplicates, folding chains of transfers, etc) so my hope is this is more of an inconsistency we never noticed.

Fixes part of #21659 (duplication of the same encoded parameter).

### CODE REVIEW

File: compiler/src/iree/compiler/Dialect/Util/Transforms/ApplyPatterns.cpp [hunk 1]
```diff
@@ -43,7 +43,9 @@ class ApplyPatternsPass
     IREE::Util::populateCommonPatterns(context, patterns);
 
     FrozenRewritePatternSet frozenPatterns(std::move(patterns));
-    if (failed(applyPatternsGreedily(getOperation(), frozenPatterns))) {
+    bool didChange = false;
+    if (failed(applyPatternsGreedily(getOperation(), frozenPatterns,
+                                     GreedyRewriteConfig(), &didChange))) {
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Dialect/Util/Transforms/ApplyPatterns.cpp]: I guess this is your debug code, and you forgot to remove it?

**Review by hanhanW — COMMENTED** [review]
I ran the command with the repro again, and I found that they are not folded away. My input IR is slightly different from yours: https://gist.github.com/hanhanW/1508cc24a8725d69e69f2d063b8317d8

Before:

```mlir
  util.initializer {
    %cst = stream.tensor.constant on(#hal.device.affinity<@__device_0>) : tensor<4096x4096xf8E4M3FNUZ> in !stream.resource<constant> = #stream.parameter.named<"model"::"blk.0.attn_q.weight:qs"> : tensor<4096x4096xf8E4M3FNUZ>
    %0 = stream.resource.size %cst : !stream.resource<constant>
    %1 = stream.async.transfer %cst : !stream.resource<constant>{%0} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<*>{%0}
    %2 = stream.tensor.sizeof on(#hal.device.affinity<@__device_0>) tensor<4096x4096xf8E4M3FNUZ, #encoding> : index
    %3 = stream.tensor.encode on(#hal.device.affinity<@__device_0>) %1 : tensor<4096x4096xf8E4M3FNUZ> in !stream.resource<*>{%0} -> tensor<4096x4096xf8E4M3FNUZ, #encoding> in !stream.resource<*>{%2}
    %4 = stream.async.transfer %3 : !stream.resource<*>{%2} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<constant>{%2}
    %5 = stream.async.transfer %cst : !stream.resource<constant>{%0} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<*>{%0}
    %6 = stream.tensor.encode on(#hal.device.affinity<@__device_0>) %5 : tensor<4096x4096xf8E4M3FNUZ> in !stream.resource<*>{%0} -> tensor<4096x4096xf8E4M3FNUZ, #encoding> in !stream.resource<*>{%2}
    %7 = stream.async.transfer %6 : !stream.resource<*>{%2} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<constant>{%2}
    util.global.store %cst, @"__auto.blk.0.attn_q.weight:qs" : !stream.resource<constant>
    util.global.store %0, @"__auto.blk.0.attn_q.weight:qs__size" : index
    util.global.store %4, @__hoisted_tensor_4096x4096xf8E4M3FNUZ__encoded : !stream.resource<constant>
    util.global.store %7, @__hoisted_tensor_4096x4096xf8E4M3FNUZ__encoded_0 : !stream.resource<constant>
    util.global.store %2, @__hoisted_tensor_4096x4096xf8E4M3FNUZ__encoded_0__size : index
    util.global.store %2, @__hoisted_tensor_4096x4096xf8E4M3FNUZ__encoded__size : index
    util.return
  }
```

After running `iree-opt --iree-util-fold-globals ~/repro.mlir`:

```mlir
  util.initializer {
    %cst = stream.tensor.constant on(#hal.device.affinity<@__device_0>) : tensor<4096x4096xf8E4M3FNUZ> in !stream.resource<constant> = #stream.parameter.named<"model"::"blk.0.attn_q.weight:qs"> : tensor<4096x4096xf8E4M3FNUZ>
    %0 = stream.resource.size %cst : !stream.resource<constant>
    %1 = stream.async.transfer %cst : !stream.resource<constant>{%0} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<*>{%0}
    %2 = stream.tensor.sizeof on(#hal.device.affinity<@__device_0>) tensor<4096x4096xf8E4M3FNUZ, #encoding> : index
    %3 = stream.tensor.encode on(#hal.device.affinity<@__device_0>) %1 : tensor<4096x4096xf8E4M3FNUZ> in !stream.resource<*>{%0} -> tensor<4096x4096xf8E4M3FNUZ, #encoding> in !stream.resource<*>{%2}
    %4 = stream.async.transfer %3 : !stream.resource<*>{%2} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<constant>{%2}
    %5 = stream.async.transfer %cst : !stream.resource<constant>{%0} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<*>{%0}
    %6 = stream.tensor.encode on(#hal.device.affinity<@__device_0>) %5 : tensor<4096x4096xf8E4M3FNUZ> in !stream.resource<*>{%0} -> tensor<4096x4096xf8E4M3FNUZ, #encoding> in !stream.resource<*>{%2}
    %7 = stream.async.transfer %6 : !stream.resource<*>{%2} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<constant>{%2}
    util.global.store %4, @__hoisted_tensor_4096x4096xf8E4M3FNUZ__encoded : !stream.resource<constant>
    util.global.store %7, @__hoisted_tensor_4096x4096xf8E4M3FNUZ__encoded_0 : !stream.resource<constant>
    util.global.store %2, @__hoisted_tensor_4096x4096xf8E4M3FNUZ__encoded_0__size : index
    util.global.store %2, @__hoisted_tensor_4096x4096xf8E4M3FNUZ__encoded__size : index                                                                                                                                                                          util.return
  }
```

The difference is that mine has an additional transfer from the global to the encoding op.

```mlir
    %1 = stream.async.transfer %__auto.blk.0.attn_q.weight3Aqs : !stream.resource<constant>{%__auto.blk.0.attn_q.weight3Aqs__size} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<*>{%__auto.blk.0.attn_q.weight3Aqs__size}
    %3 = stream.tensor.encode on(#hal.device.affinity<@__device_0>) %1 : tensor<4096x4096xf8E4M3FNUZ> in !stream.resource<*>{%__auto.blk.0.attn_q.weight3Aqs__size} -> tensor<4096x4096xf8E4M3FNUZ, #encoding> in !stream.resource<*>{%2}
```

```mlir
    %cst = stream.tensor.constant on(#hal.device.affinity<@__device_0>) : tensor<4096x4096xf8E4M3FNUZ> in !stream.resource<constant> = #stream.parameter.named<"model"::"blk.0.attn_q.weight:qs"> : tensor<4096x4096xf8E4M3FNUZ>
    %1 = stream.async.transfer %cst : !stream.resource<constant>{%0} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<*>{%0}
    %3 = stream.tensor.encode on(#hal.device.affinity<@__device_0>) %1 : tensor<4096x4096xf8E4M3FNUZ> in !stream.resource<*>{%0} -> tensor<4096x4096xf8E4M3FNUZ, #encoding> in !stream.resource<*>{%2}

```

**Comment by hanhanW** [comment]
Here is the full dump until encoding specialization: https://gist.github.com/hanhanW/932bfac88b53ef295ec7a0fe2f670f56

File: compiler/src/iree/compiler/Dialect/Util/Transforms/ApplyPatterns.cpp (hunk 1 above)
Comment (benvanik) [reply compiler/src/iree/compiler/Dialect/Util/Transforms/ApplyPatterns.cpp]: ah no, just missed the last line in the merge - thanks for catching

**Comment by benvanik** [comment]
ah yeah - yours has the extra transfer because you're just running one pass in isolation and not the CSE pass that removes the extra transfer :) --compile-from=flow on the IR you produces the results I put above.

**Review by hanhanW — APPROVED** [review]
Thanks, I confirmed that it fixes the dup issue. The IR looks slightly cleaner after you rebase.

**Comment by benvanik** [comment]
thanks for testing it!
