### PR TITLE
[StableHLO] Fix reshape canonicalization for dense_resource constants.

### LINKED ISSUE #22230: 1D dense_resource (Bias) in stablehlo can't be compiled
### What happened?

A very basic example of a conv network lowered from Torch to stablehlo can't be compiled with iree-compile if the convolution has biases. 

### Steps to reproduce your issue

To reproduce the issue, create a file `simple_cnn_stableHLO.mlir` with this content (simple CNN with biases):
```
module {
  func.func @main(%arg0: tensor<1x2x8x8xf32>) -> tensor<1x8x8x8xf32> {
    %c = stablehlo.constant dense<0> : tensor<i64>
    %cst = stablehlo.constant dense_resource<torch_tensor_8_2_3_3_torch.float32> : tensor<8x2x3x3xf32>
    %cst_0 = stablehlo.constant dense_resource<torch_tensor_8_torch.float32> : tensor<8xf32>
    %0 = stablehlo.convolution(%arg0, %cst) dim_numbers = [b, f, 0, 1]x[o, i, 0, 1]->[b, f, 0, 1], window = {stride = [1, 1], pad = [[1, 1], [1, 1]], rhs_dilate = [1, 1]} {batch_group_count = 1 : i64, feature_group_count = 1 : i64} : (tensor<1x2x8x8xf32>, tensor<8x2x3x3xf32>) -> tensor<1x8x8x8xf32>
    %1 = stablehlo.reshape %cst_0 : (tensor<8xf32>) -> tensor<8x1x1xf32>
    %2 = stablehlo.broadcast_in_dim %0, dims = [0, 1, 2, 3] : (tensor<1x8x8x8xf32>) -> tensor<1x8x8x8xf32>
    %3 = stablehlo.broadcast_in_dim %1, dims = [1, 2, 3] : (tensor<8x1x1xf32>) -> tensor<1x8x8x8xf32>
    %4 = stablehlo.add %2, %3 : tensor<1x8x8x8xf32>
    %5 = stablehlo.convert %c : (tensor<i64>) -> tensor<f32>
    %6 = stablehlo.broadcast_in_dim %5, dims = [] : (tensor<f32>) -> tensor<1x8x8x8xf32>
    %7 = stablehlo.broadcast_in_dim %4, dims = [0, 1, 2, 3] : (tensor<1x8x8x8xf32>) -> tensor<1x8x8x8xf32>
    %8 = stablehlo.maximum %6, %7 : tensor<1x8x8x8xf32>
    return %8 : tensor<1x8x8x8xf32>
  }
}

{-#
  dialect_resources: {
    builtin: {
      torch_tensor_8_2_3_3_torch.float32: "0x040000004187383E7954483EDA2C62BD18B75D3ED48753BDEBD0423D8803EBBDFBBE0D3EB7C4543E5E1131BED6C9513EBFB0343D7951323EE7BF023DD0C2E83D9A4F08BD710F3A3E3AB30E3D265AE1BD8F16763DEE67DEBD6170E2BC5E0FC4BD521C203E8D853EBEC189DEBDB44E88BD621F11BEE73DB63CA7626EBE3EF9593EE3064DBEFA553A3EC8AA203DA5BD9CBDDA25153ECA76163D6302433E1A15D33C843C98BDD1B2813D3CE782BDD627CB3DA37D573E1B850B3EFA07D3BDFE530B3EEEBD2C3D2724F53D0F1C13BE66EC6EBED680BABDC22039BE670B463EB9098B3DCCF2C73D40AA983D8F5B86BBBFE33C3E2B7D2BBE6026733CBFBC24BEDDD8943D573DA6BDA8E9933DF52349BD682E483ED40D0FBE33F20FBE6DF40FBEB616593ECCDDA03D7C3F683E1D3047BEFA656FBEA4D43CBE115C22BE3085C33D89D9AC3D1A8D483EB749F9BD908924BE540F003EEC1DC3BD927C123E431965BD89110A3E3F873BBE889AF3BD5F2B933DBE194C3D7F2576BDE6DD0F3E0214243EF7062FBE9DDA00BEDC005D3E84E2A2BDAC21ABBDAC8969BE1C380ABE692B713DAFDCFEBCFF322FBEE62AB53B32DE24BEADC44CBE4EE804BE8C3D53BEBBAE19BEC443713EC658363D1AC1943DA31C61BEB2841EBEF2ACA0BD65F7163D856054BE82FDCFBD7F7E10BEF73A2B3AFA9EB3BD23CD85BC578D23BEF0AA25BE31CF0CBEB43BA5BD09803EBE525F4A3EBB9A3FBD23AA4F3E0768963DD6614CBE6D07273E42D184BDD909B9BD575848BE22F36FBE5F1C8A3DC8E452BDF1EEBB3D191346BE2A31333EAA2B31BE",
      torch_tensor_8_torch.float32: "0x0400000084B426BD82A6493D4434F93D0ADA423E4ADE5B3E05613FBE00F8723D30A1CFBD"
    }
  }
#-}
```

Then run:
`iree-compile simple_cnn_stableHLO.mlir --iree-input-type=stablehlo --iree-llvmcpu-target-cpu=x86-64 --iree-hal-target-backends=llvm-cpu` 

See the error:

```
ElementsAttr does not provide iteration facilities for type `mlir::Attribute`, see attribute: dense_resource<torch_tensor_8_torch.float32> : tensor<8xf32>
Please report issues to https://github.com/iree-org/iree/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/pweidel/mlir_env_3.10/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile simple_cnn_stableHLO.mlir --iree-input-type=stablehlo --iree-llvmcpu-target-cpu=x86-64 --iree-hal-target-backends=llvm-cpu
#0 0x00007e2846fb48a8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/pweidel/mlir_env_3.10/lib/python3.10/site-packages/iree/compiler/_mlir_libs/libIREECompiler.so+0x63b48a8)
#1 0x00007e2846fb221e llvm::sys::RunSignalHandlers() (/home/pweidel/mlir_env_3.10/lib/python3.10/site-packages/iree/compiler/_mlir_libs/libIREECompiler.so+0x63b221e)
#2 0x00007e2846fb5736 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
#3 0x00007e2840845330 (/lib/x86_64-linux-gnu/libc.so.6+0x45330)
#4 0x00007e2846ee94cd (/home/pweidel/mlir_env_3.10/lib/python3.10/site-packages/iree/compiler/_mlir_libs/libIREECompiler.so+0x62e94cd)
```

### What component(s) does this issue relate to?

Compiler

### Version information

iree-compile --version  
IREE (https://iree.dev):
  IREE compiler version 3.7.1 @ cb2048e0e7694c76ac1af36d5e3450aa3625995c
  LLVM version 22.0.0git
  Optimized build

### Additional context

It seems that the root cause of the issue is that IREE can't deal with 1D dense_resources (bias). You can make it work, if you manually replace the 1D shape with a 3D shape and remove the "reshape op" afterwards. Here's a manually fixed stablehlo file which works:

```
module {
  func.func @main(%arg0: tensor<1x2x8x8xf32>) -> tensor<1x8x8x8xf32> {
    %c = stablehlo.constant dense<0> : tensor<i64>
    %cst = stablehlo.constant dense_resource<torch_tensor_8_2_3_3_torch.float32> : tensor<8x2x3x3xf32>
    %cst_0 = stablehlo.constant dense_resource<torch_tensor_8_torch.float32> : tensor<8x1x1xf32>
    %0 = stablehlo.convolution(%arg0, %cst) dim_numbers = [b, f, 0, 1]x[o, i, 0, 1]->[b, f, 0, 1], window = {stride = [1, 1], pad = [[1, 1], [1, 1]], rhs_dilate = [1, 1]} {batch_group_count = 1 : i64, feature_group_count = 1 : i64} : (tensor<1x2x8x8xf32>, tensor<8x2x3x3xf32>) -> tensor<1x8x8x8xf32>
    %2 = stablehlo.broadcast_in_dim %0, dims = [0, 1, 2, 3] : (tensor<1x8x8x8xf32>) -> tensor<1x8x8x8xf32>
    %3 = stablehlo.broadcast_in_dim %cst_0, dims = [1, 2, 3] : (tensor<8x1x1xf32>) -> tensor<1x8x8x8xf32>
    %4 = stablehlo.add %2, %3 : tensor<1x8x8x8xf32>
    %5 = stablehlo.convert %c : (tensor<i64>) -> tensor<f32>
    %6 = stablehlo.broadcast_in_dim %5, dims = [] : (tensor<f32>) -> tensor<1x8x8x8xf32>
    %7 = stablehlo.broadcast_in_dim %4, dims = [0, 1, 2, 3] : (tensor<1x8x8x8xf32>) -> tensor<1x8x8x8xf32>
    %8 = stablehlo.maximum %6, %7 : tensor<1x8x8x8xf32>
    return %8 : tensor<1x8x8x8xf32>
  }
}

{-#
  dialect_resources: {
    builtin: {
      torch_tensor_8_2_3_3_torch.float32: "0x040000004187383E7954483EDA2C62BD18B75D3ED48753BDEBD0423D8803EBBDFBBE0D3EB7C4543E5E1131BED6C9513EBFB0343D7951323EE7BF023DD0C2E83D9A4F08BD710F3A3E3AB30E3D265AE1BD8F16763DEE67DEBD6170E2BC5E0FC4BD521C203E8D853EBEC189DEBDB44E88BD621F11BEE73DB63CA7626EBE3EF9593EE3064DBEFA553A3EC8AA203DA5BD9CBDDA25153ECA76163D6302433E1A15D33C843C98BDD1B2813D3CE782BDD627CB3DA37D573E1B850B3EFA07D3BDFE530B3EEEBD2C3D2724F53D0F1C13BE66EC6EBED680BABDC22039BE670B463EB9098B3DCCF2C73D40AA983D8F5B86BBBFE33C3E2B7D2BBE6026733CBFBC24BEDDD8943D573DA6BDA8E9933DF52349BD682E483ED40D0FBE33F20FBE6DF40FBEB616593ECCDDA03D7C3F683E1D3047BEFA656FBEA4D43CBE115C22BE3085C33D89D9AC3D1A8D483EB749F9BD908924BE540F003EEC1DC3BD927C123E431965BD89110A3E3F873BBE889AF3BD5F2B933DBE194C3D7F2576BDE6DD0F3E0214243EF7062FBE9DDA00BEDC005D3E84E2A2BDAC21ABBDAC8969BE1C380ABE692B713DAFDCFEBCFF322FBEE62AB53B32DE24BEADC44CBE4EE804BE8C3D53BEBBAE19BEC443713EC658363D1AC1943DA31C61BEB2841EBEF2ACA0BD65F7163D856054BE82FDCFBD7F7E10BEF73A2B3AFA9EB3BD23CD85BC578D23BEF0AA25BE31CF0CBEB43BA5BD09803EBE525F4A3EBB9A3FBD23AA4F3E0768963DD6614CBE6D07273E42D184BDD909B9BD575848BE22F36FBE5F1C8A3DC8E452BDF1EEBB3D191346BE2A31333EAA2B31BE",
      torch_tensor_8_torch.float32: "0x0400000084B426BD82A6493D4434F93D0ADA423E4ADE5B3E05613FBE00F8723D30A1CFBD"
    }
  }
#-}

```

### PR DESCRIPTION
**Pull request by weidel-p**
Handle DenseResourceElementsAttr in Canonicalization.cpp to deal with 1D dense resources.

Fixes: #22230

### CODE REVIEW

**Comment by kuhar** [comment]
@weidel-p can you remove all the unrelated commits from this PR?

**Comment by weidel-p** [comment]
sorry, the signoff added those by accident.

File: compiler/plugins/input/StableHLO/Conversion/Preprocessing/Canonicalization.cpp [hunk 1]
```diff
@@ -973,7 +974,13 @@ struct ReshapeOpCanon final : OpRewritePattern<mlir::stablehlo::ReshapeOp> {
           op, SplatElementsAttr::get(op.getType(),
                                      splat.getSplatValue<Attribute>()));
       return success();
-    }
+    } else if (auto denseResourceAttr =
+                   llvm::dyn_cast<DenseResourceElementsAttr>(cstAttr)) {
+      rewriter.replaceOpWithNewOp<mlir::stablehlo::ConstantOp>(
```
Comment (kuhar) [inline compiler/plugins/input/StableHLO/Conversion/Preprocessing/Canonicalization.cpp]: no else after return: https://llvm.org/docs/CodingStandards.html#don-t-use-else-after-a-return
```suggestion
    }
    if (auto denseResourceAttr =
                   dyn_cast<DenseResourceElementsAttr>(cstAttr)) {
      rewriter.replaceOpWithNewOp<mlir::stablehlo::ConstantOp>(
```

also you don't need to prefix casts with `llvm::`

File: tests/e2e/stablehlo_models/cnn_with_bias.mlir [hunk 2]
```diff
@@ -0,0 +1,31 @@
+// RUN: iree-run-mlir --Xcompiler,iree-input-type=stablehlo --Xcompiler,iree-hal-target-device=local --Xcompiler,iree-hal-local-target-device-backends=vmvx %s --input=1x2x8x8xf32 | FileCheck %s
```
Comment (kuhar) [inline tests/e2e/stablehlo_models/cnn_with_bias.mlir]: Can we turn this into a plain lit test that only compiles the input but doesn't execute it?

**Review by kuhar — CHANGES_REQUESTED** [review]

File: tests/e2e/stablehlo_models/cnn_with_bias.mlir (hunk 2 above)
Comment (hanhanW) [reply tests/e2e/stablehlo_models/cnn_with_bias.mlir]: I think we only maintain few models in-tree. This one should be tested by corresponding integration tests: https://groups.google.com/g/iree-discuss/c/GIWyj8hmP0k/m/ASyG_L1jBAAJ?utm_medium=email&utm_source=footer

To be more specific, and I'm +1 on the statement: https://discord.com/channels/689900678990135345/689957613152239638/1270874182128763061

You should add a test to [canonicalization.mlir](https://github.com/iree-org/iree/blob/main/compiler/plugins/input/StableHLO/Conversion/Preprocessing/test/canonicalization.mlir) instead.

**Review by hanhanW — CHANGES_REQUESTED** [review]

File: compiler/plugins/input/StableHLO/Conversion/Preprocessing/Canonicalization.cpp (hunk 1 above)
Comment (weidel-p) [reply compiler/plugins/input/StableHLO/Conversion/Preprocessing/Canonicalization.cpp]: done.

File: tests/e2e/stablehlo_models/cnn_with_bias.mlir (hunk 2 above)
Comment (weidel-p) [reply tests/e2e/stablehlo_models/cnn_with_bias.mlir]: As suggested, I replaced the full model test to a test in [canonicalization.mlir](https://github.com/iree-org/iree/blob/main/compiler/plugins/input/StableHLO/Conversion/Preprocessing/test/canonicalization.mlir)

**Comment by weidel-p** [comment]
Thanks for the feedback, please take a look again.

File: compiler/plugins/input/StableHLO/Conversion/Preprocessing/test/canonicalization.mlir [hunk 3]
```diff
@@ -412,6 +412,26 @@ func.func @merge_consecutive_reshapes(%arg0: tensor<4x4xi32>) -> tensor<16xi32>
 
 // -----
 
+// Test for reshape with dense_resource constants (regression test for crash)
+// CHECK-LABEL: func.func @reshape_dense_resource
```
Comment (hanhanW) [inline compiler/plugins/input/StableHLO/Conversion/Preprocessing/test/canonicalization.mlir]:
```suggestion
// Test for reshape with dense_resource constants (regression test for crash).

// CHECK-LABEL: func.func @reshape_dense_resource
```

File: compiler/plugins/input/StableHLO/Conversion/Preprocessing/test/canonicalization.mlir [hunk 4]
```diff
@@ -412,6 +412,26 @@ func.func @merge_consecutive_reshapes(%arg0: tensor<4x4xi32>) -> tensor<16xi32>
...
+func.func @reshape_dense_resource() -> tensor<8x1x1xf32> {
+  %cst = stablehlo.constant dense_resource<torch_tensor_8_torch.float32> : tensor<8xf32>
```
Comment (hanhanW) [inline compiler/plugins/input/StableHLO/Conversion/Preprocessing/test/canonicalization.mlir]: You don't need any torch things in `StableHLO` directory. Can you just do something like `dense_resource<__elided__> : tensor<8xf32>`, or find a builtin one?

This test will be broken if

**Review by hanhanW — COMMENTED** [review]
overall looks okay, just few nits.

**Comment by hanhanW** [comment]
Please update PR title. `[StableHLO] Fix/stablehlo 1d resource` is very meaningless when you skim through the commit history.

See https://google.github.io/eng-practices/review/developer/cl-descriptions.html for the guidance.

File: compiler/plugins/input/StableHLO/Conversion/Preprocessing/Canonicalization.cpp [hunk 5]
```diff
@@ -973,7 +974,15 @@ struct ReshapeOpCanon final : OpRewritePattern<mlir::stablehlo::ReshapeOp> {
           op, SplatElementsAttr::get(op.getType(),
                                      splat.getSplatValue<Attribute>()));
       return success();
-    }
+    } 
+    
+    if (auto denseResourceAttr =
+                   llvm::dyn_cast<DenseResourceElementsAttr>(cstAttr)) {
```
Comment (kuhar) [inline compiler/plugins/input/StableHLO/Conversion/Preprocessing/Canonicalization.cpp]:
```suggestion
                   dyn_cast<DenseResourceElementsAttr>(cstAttr)) {
```

File: compiler/plugins/input/StableHLO/Conversion/Preprocessing/test/canonicalization.mlir (hunk 4 above)
Comment (weidel-p) [reply compiler/plugins/input/StableHLO/Conversion/Preprocessing/test/canonicalization.mlir]: I renamed the dense resource with __elided__.

File: compiler/plugins/input/StableHLO/Conversion/Preprocessing/test/canonicalization.mlir [hunk 6]
```diff
@@ -412,6 +412,27 @@ func.func @merge_consecutive_reshapes(%arg0: tensor<4x4xi32>) -> tensor<16xi32>
...
+  return %0 : tensor<8x1x1xf32>
+}
+
+{-#
+  dialect_resources: {
+    builtin: {
+      __elided__: "0x040000000000803F0000004000004040000080400000A0400000C0400000E0400000004100000041"
+    }
+  }
+#-}
```
Comment (kuhar) [inline compiler/plugins/input/StableHLO/Conversion/Preprocessing/test/canonicalization.mlir]: do we still need this?

Comment (weidel-p) [reply compiler/plugins/input/StableHLO/Conversion/Preprocessing/test/canonicalization.mlir]: Turns out, we don't.

**Review by kuhar — APPROVED** [review]

**Comment by weidel-p** [comment]
sorry, I missed installing the pre-commit tool. Now linting should work.

**Review by hanhanW — APPROVED** [review]
thanks!
