### PR TITLE
Work around missing pybind in BYO LLVM build

### LINKED ISSUE #18884: BYO LLVM build configuration broken by pybind11 changes
See https://github.com/iree-org/iree/pull/18872#issuecomment-2435492981

Logs: https://github.com/iree-org/iree/actions/runs/11496514385/job/31998278068#step:4:10340

```
-- Found Python3: /__w/iree/iree/build-byo-llvm/.venv/bin/python3 (found version "3.11.0") found components: Interpreter Development Development.Module Development.Embed 
-- Found Python3: /__w/iree/iree/build-byo-llvm/.venv/bin/python3 (found version "3.11.0") found components: Interpreter Development.Module 
-- Found python include dirs: /usr/include/python3.11
-- Found python libraries: /usr/lib/x86_64-linux-gnu/libpython3.11.so
-- Found numpy v: 
-- Checking for pybind11 in python path...
-- not found (install via 'pip install pybind11' or set pybind11_DIR)
CMake Error at cmake/modules/MLIRDetectPythonEnv.cmake:28 (find_package):
  Could not find a package configuration file provided by "pybind11"
  (requested version 2.9) with any of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:175 (mlir_configure_python_dev_packages)


-- Configuring incomplete, errors occurred!
```

Code:

* https://github.com/iree-org/iree/blob/main/.github/workflows/ci_linux_x64_clang_byollvm.yml
* https://github.com/iree-org/iree/blob/main/build_tools/cmake/build_and_test_byo_llvm.sh
* https://github.com/iree-org/iree/blob/main/build_tools/llvm/byo_llvm.sh
* https://github.com/iree-org/iree/blob/main/build_tools/cmake/iree_llvm.cmake

---

We can also increase the frequency of https://github.com/iree-org/iree/blob/main/.github/workflows/ci_linux_x64_clang_byollvm.yml (from nightly to every commit) if we have CI budget/capacity, and add alerting (like posting to Discord on failure).

### PR DESCRIPTION
**Pull request by marbre**
Installs pybind via pip to work around #18884.

Closes #18884.

### CODE REVIEW

File: build_tools/cmake/build_and_test_byo_llvm.sh [hunk 1]
```diff
@@ -24,6 +24,11 @@ echo "Setting up venv at $VENV_DIR"
 python3 -m venv "$VENV_DIR"
 source "$VENV_DIR/bin/activate"
 python -m pip install -r runtime/bindings/python/iree/runtime/build_requirements.txt
+# Note: In a bundled build, pybind is made available via FetchContent.
+# However, if bringing your own LLVM, MLIR is configured before IREE is and
+# therefore pybind wasn't fetched and properly set up yet. To work around this,
+# pybind is installed via pip.
+python -m pip install pybind11==2.13.6
```
Comment (ScottTodd) [inline build_tools/cmake/build_and_test_byo_llvm.sh]: How about we follow https://mlir.llvm.org/docs/Bindings/Python/#building and run the suggested
```bash
python -m pip install -r mlir/python/requirements.txt
```
here instead?

The "bring-your-own-LLVM" path tested here is one demonstration of how users can build LLVM before IREE. Needing to install dependencies isn't so much "working around an improperly set up build" as it is "following the upstream instructions". Note that https://github.com/llvm/llvm-project/blob/main/mlir/python/requirements.txt sets `pybind11>=2.9.0, <=2.10.3`. If that isn't compatible with _our_ build then we could send a patch upstream to increase the maximum version... or keep this local pin and add a comment explaining why we don't use the upstream requirements.

We could also add a comment on prerequisites to https://github.com/iree-org/iree/blob/main/build_tools/llvm/byo_llvm.sh since that unconditionally enables the upstream Python bindings: https://github.com/iree-org/iree/blob/9731fed369ef59ee1e120f9f1315a7b9981e515c/build_tools/llvm/byo_llvm.sh#L116

**Review by ScottTodd — CHANGES_REQUESTED** [review]

File: build_tools/cmake/build_and_test_byo_llvm.sh (hunk 1 above)
Comment (marbre) [reply build_tools/cmake/build_and_test_byo_llvm.sh:31]: Installing by
```
python -m pip install -r mlir/python/requirements.txt
```
would get us
```
pybind11>=2.9.0, <=2.10.3
```
Probably not the best idea to mix versions?

Comment (marbre) [reply build_tools/cmake/build_and_test_byo_llvm.sh]: I am not confident that it is a good thing to mix versions, especially as support for free-threaded Python was first added with 2.13. Probably best to raise the upper version number upstream. However, I would still pin the version we use to not mix versions.

Comment (ScottTodd) [reply build_tools/cmake/build_and_test_byo_llvm.sh]: How about we follow the upstream instructions _then also_ manually upgrade to the version we want, with a comment / TODO to relax the requirement upstream. Then ideally also send a PR upstream to resolve that.

Comment (stellaraccident) [reply build_tools/cmake/build_and_test_byo_llvm.sh]: Don't cross the streams or overthink this. This is an extremely sharp edge and there must be one version of pybind globally. 

This use case is already full of thorns that must be known and adapted to. I'd rather that the thorn be explicit vs hidden.

Comment (marbre) [reply build_tools/cmake/build_and_test_byo_llvm.sh]: I revised the notes, but anyway we install the same version we use explicitly via pip.

**Review by ScottTodd — APPROVED** [review]
