### PR TITLE
[CPU] Limit unrolling factors for generic ops.

### LINKED ISSUE #16993: Slow compilation of DINO ViT model using `native_vector_size = 64` (cpu_features)
### What happened?

Splitting off from https://github.com/nod-ai/SHARK-Turbine/issues/523#issuecomment-2037851747, this model is very slow to compile (20 minutes - 1 hour) when using `--iree-llvmcpu-target-cpu-features=host`.

The specific features on the user machine are `--iree-llvmcpu-target-cpu-features=+prfchw,-cldemote,+avx,+aes,+sahf,+pclmul,-xop,+crc32,+xsaves,-avx512fp16,-usermsr,-sm4,-egpr,+sse4.1,+avx512ifma,+xsave,-avx512pf,+sse4.2,-tsxldtrk,-ptwrite,-widekl,-sm3,+invpcid,+64bit,+xsavec,-avx10.1-512,+avx512vpopcntdq,+cmov,-avx512vp2intersect,+avx512cd,+movbe,-avxvnniint8,-avx512er,-ccmp,-amx-int8,-kl,-avx10.1-256,-sha512,-avxvnni,-rtm,+adx,+avx2,-hreset,-movdiri,-serialize,+vpclmulqdq,+avx512vl,-uintr,-cf,+clflushopt,-raoint,-cmpccxadd,+bmi,-amx-tile,+sse,+gfni,-avxvnniint16,-amx-fp16,-ndd,+xsaveopt,+rdrnd,+avx512f,-amx-bf16,+avx512bf16,+avx512vnni,-push2pop2,+cx8,+avx512bw,+sse3,+pku,+fsgsbase,+clzero,+mwaitx,-lwp,+lzcnt,+sha,-movdir64b,-ppx,+wbnoinvd,-enqcmd,-prefetchwt1,-avxneconvert,-tbm,-pconfig,-amx-complex,+ssse3,+cx16,+bmi2,+fma,+popcnt,-avxifma,+f16c,+avx512bitalg,+rdpru,+clwb,+mmx,+sse2,+rdseed,+avx512vbmi2,-prefetchi,+rdpid,-fma4,+avx512vbmi,+shstk,+vaes,-waitpkg,-sgx,+fxsr,+avx512dq,+sse4a`

I've narrowed this down to just `native_vector_size = 16 : i64` (fast) -> `native_vector_size = 64 : i64` (slow), which setting the CPU features affects.

After the `LLVMCPUVirtualVectorLowering` pass, the MLIR module size grows to 200k+ ops: https://gist.github.com/ScottTodd/2aab78a54dd8b9399900102f8782d5e2

### Steps to reproduce your issue

Full model

1. Download https://github.com/nod-ai/SHARK-Turbine/issues/523#issuecomment-2037851747
2. Compile: `iree-compile dino_model.mlir --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-target-cpu-features=+prfchw,-cldemote,+avx,+aes,+sahf,+pclmul,-xop,+crc32,+xsaves,-avx512fp16,-usermsr,-sm4,-egpr,+sse4.1,+avx512ifma,+xsave,-avx512pf,+sse4.2,-tsxldtrk,-ptwrite,-widekl,-sm3,+invpcid,+64bit,+xsavec,-avx10.1-512,+avx512vpopcntdq,+cmov,-avx512vp2intersect,+avx512cd,+movbe,-avxvnniint8,-avx512er,-ccmp,-amx-int8,-kl,-avx10.1-256,-sha512,-avxvnni,-rtm,+adx,+avx2,-hreset,-movdiri,-serialize,+vpclmulqdq,+avx512vl,-uintr,-cf,+clflushopt,-raoint,-cmpccxadd,+bmi,-amx-tile,+sse,+gfni,-avxvnniint16,-amx-fp16,-ndd,+xsaveopt,+rdrnd,+avx512f,-amx-bf16,+avx512bf16,+avx512vnni,-push2pop2,+cx8,+avx512bw,+sse3,+pku,+fsgsbase,+clzero,+mwaitx,-lwp,+lzcnt,+sha,-movdir64b,-ppx,+wbnoinvd,-enqcmd,-prefetchwt1,-avxneconvert,-tbm,-pconfig,-amx-complex,+ssse3,+cx16,+bmi2,+fma,+popcnt,-avxifma,+f16c,+avx512bitalg,+rdpru,+clwb,+mmx,+sse2,+rdseed,+avx512vbmi2,-prefetchi,+rdpid,-fma4,+avx512vbmi,+shstk,+vaes,-waitpkg,-sgx,+fxsr,+avx512dq,+sse4a --iree-llvmcpu-enable-ukernels=all --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-flow-inline-constants-max-byte-length=1 --compile-mode=hal-executable -o /dev/null`
3. Observe slow compile

Minimal reproducer (bottleneck dispatch):

1. Download `dispatch_2_size16.mlir` and `dispatch_2_size64.mlir` from https://gist.github.com/ScottTodd/607ca024de581ae3a5ba7265eabfd158. These only differ in `native_vector_size = 16 : i64` -> `native_vector_size = 64 : i64`
2. Compile the dispatches: `iree-compile --compile-mode=hal-executable dispatch_2_size64.mlir -o /dev/null`
3. Observe slow compile, compare with `iree-compile --compile-mode=hal-executable dispatch_2_size16.mlir -o /dev/null`

### What component(s) does this issue relate to?

Compiler

### Version information

Tip of tree from source, https://github.com/openxla/iree/commit/dcc8e1990e09370d8818c42bebdec5c5e372ec01

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hanhanW**
The revision also deprecates an outdated lit test that is impacted by it. It adds the other lit test simplified from the https://github.com/iree-org/iree/issues/16993

Fixes https://github.com/iree-org/iree/issues/16993

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 1]
```diff
@@ -289,6 +289,34 @@ static int64_t getVectorSize(mlir::FunctionOpInterface entryPointFn,
...
+  if ((genericOp.getNumDpsInputs() != 1) || (genericOp.getNumDpsInits() != 1)) {
+    return false;
+  }
+
+  // Check that all the iterators are parallel.
+  if (genericOp.getNumParallelLoops() != genericOp.getNumLoops()) {
+    return false;
+  }
+
+  // Check that the two indexing maps are a permutation of each other.
```
Comment (bjacob) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:313]: The code seems to implement `Both indexing maps are permutations, and exactly one of them is the identity`. What does this comment mean by "are a permutation of each other" ?

Also, this condition could be simplified to `m0.isPermutation() && m1.isPermutation() && (m0.isIdentity() ^ m1.isIdentity())`.

What role is played by the separate checks for `isEmpty` ?

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 2]
```diff
@@ -325,21 +353,33 @@ getMinTilingSizesForEachDim(mlir::FunctionOpInterface entryPointFn,
 
   // Limit unroll factor. For now, we assume the rightmost non-one tiled
   // dimension is for vectorization and any other non-one dimension is for
-  // unrolling.
+  // unrolling. The util limits the second rightmost non-one tiled dimension
```
Comment (bjacob) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:358]: What is "the util" ?

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 3]
```diff
@@ -289,6 +289,34 @@ static int64_t getVectorSize(mlir::FunctionOpInterface entryPointFn,
   return getVectorSize(entryPointFn, byteWidth);
 }
 
+/// Returns true if the operation is a GenericOp implementing a supported
+/// transposition.
```
Comment (bjacob) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: I was curious what "a supported transposition" means: supported in what sense?

Looking at how this function is used, it seems to mean "is `defaultMaxTransposeUnrollFactor` should be used instead of `defaultMaxUnrollFactor` for this op".

If I get that right, I would suggest that this relatively minor nuance --- just which numeric threshold value is used in some logic, not a fundamental switch of what logic is applied to the op --- is not what a reader of this comment would guess from reading the above comment, which suggests a major difference instead ("supported" vs... "not supported" ? which sounds scary).

**Review by bjacob — CHANGES_REQUESTED** [review]

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp (hunk 2 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:358]: I meant the lambda function, let me update the comment.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp (hunk 3 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: This is sort of precondition for transpose op lowering. We have specialized codegen for transpose ops on x86 path. It only supports n-D transpose with single input and single output. Here I'm just moving the code from below to here, but I can update the comment and and rename it to `x86TransposeLoweringPrecondition`. What do you think?

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp (hunk 1 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:313]: As same as above response, the code is quite old. I can help update it either in the PR or in a follow-up. `isEmpty()` is the check for scalars. We don't need the specialized transpose lowering when they are scalars.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp (hunk 3 above)
Comment (bjacob) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: SG!

**Review by bjacob — APPROVED** [review]
