### PR TITLE
Test 'console' provider in 'tracing' job.

### LINKED ISSUE #16405: Compilation errors in CUDA HAL Driver with tracing features enabled
```
cmake -DIREE_BUILD_COMPILER=OFF -DIREE_ENABLE_RUNTIME_TRACING=ON -DIREE_TRACING_PROVIDER=console -DIREE_HAL_DRIVER_CUDA=ON .
ninja
```

Compilation errors:

```
FAILED: runtime/src/iree/hal/drivers/cuda/CMakeFiles/iree_hal_drivers_cuda_cuda.objects.dir/tracing.c.o 
ccache /usr/bin/clang -DIREE_TRACING_MODE=2 -DIREE_TRACING_PROVIDER_H=\"iree/base/tracing/console.h\" -I/home/stella/src/iree -I/home/stella/src/iree-build -I/home/stella/src/iree/runtime/src -I/home/stella/src/iree-build/runtime/src -I/home/stella/src/iree-build/build_tools/third_party/cuda/12.2.1/linux-x86_64/include -I/home/stella/src/iree/third_party/nccl -I/home/stella/src/iree-build/runtime/src/iree/base/internal/flatcc -I/home/stella/src/iree-build/runtime/src/iree/schemas -isystem /home/stella/src/iree/third_party/flatcc/include -O2 -g   -gsplit-dwarf -ggnu-pubnames -std=gnu11 -flto=thin -fPIC -fvisibility=hidden -Werror -Wall -Wno-error=deprecated-declarations -Wno-ambiguous-member-template -Wno-char-subscripts -Wno-extern-c-compat -Wno-gnu-alignof-expression -Wno-gnu-variable-sized-type-not-at-end -Wno-ignored-optimization-argument -Wno-invalid-offsetof -Wno-invalid-source-encoding -Wno-mismatched-tags -Wno-pointer-sign -Wno-reserved-user-defined-literal -Wno-return-type-c-linkage -Wno-self-assign-overloaded -Wno-sign-compare -Wno-signed-unsigned-wchar -Wno-strict-overflow -Wno-trigraphs -Wno-unknown-pragmas -Wno-unknown-warning-option -Wno-unused-command-line-argument -Wno-unused-const-variable -Wno-unused-function -Wno-unused-local-typedef -Wno-unused-private-field -Wno-user-defined-warnings -Wno-missing-braces -Wc++20-extensions -Wctad-maybe-unsupported -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wformat-security -Wgnu-redeclared-enum -Wimplicit-fallthrough -Winfinite-recursion -Wliteral-conversion -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wself-assign -Wstring-conversion -Wtautological-overlap-compare -Wthread-safety -Wthread-safety-beta -Wunused-comparison -Wvla -fno-lax-vector-conversions -fno-omit-frame-pointer -fmacro-prefix-map=/home/stella/src/iree=iree -I/home/stella/src/iree/third_party/flatcc/include/ -I/home/stella/src/iree/third_party/flatcc/include/flatcc/reflection/ -MD -MT runtime/src/iree/hal/drivers/cuda/CMakeFiles/iree_hal_drivers_cuda_cuda.objects.dir/tracing.c.o -MF runtime/src/iree/hal/drivers/cuda/CMakeFiles/iree_hal_drivers_cuda_cuda.objects.dir/tracing.c.o.d -o runtime/src/iree/hal/drivers/cuda/CMakeFiles/iree_hal_drivers_cuda_cuda.objects.dir/tracing.c.o -c /home/stella/src/iree/runtime/src/iree/hal/drivers/cuda/tracing.c
/home/stella/src/iree/runtime/src/iree/hal/drivers/cuda/tracing.c:65:24: error: implicit declaration of function 'iree_tracing_time' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  *out_cpu_timestamp = iree_tracing_time();
                       ^
/home/stella/src/iree/runtime/src/iree/hal/drivers/cuda/tracing.c:125:19: error: implicit declaration of function 'iree_tracing_gpu_context_allocate' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    context->id = iree_tracing_gpu_context_allocate(
                  ^
/home/stella/src/iree/runtime/src/iree/hal/drivers/cuda/tracing.c:126:9: error: use of undeclared identifier 'IREE_TRACING_GPU_CONTEXT_TYPE_CUDA'
        IREE_TRACING_GPU_CONTEXT_TYPE_CUDA, queue_name.data, queue_name.size,
        ^
/home/stella/src/iree/runtime/src/iree/hal/drivers/cuda/tracing.c:206:7: error: implicit declaration of function 'iree_tracing_gpu_zone_notify' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      iree_tracing_gpu_zone_notify(context->id, query_id, gpu_timestamp);
      ^
/home/stella/src/iree/runtime/src/iree/hal/drivers/cuda/tracing.c:252:3: error: implicit declaration of function 'iree_tracing_gpu_zone_begin' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  iree_tracing_gpu_zone_begin(context->id, query_id, src_loc);
  ^
/home/stella/src/iree/runtime/src/iree/hal/drivers/cuda/tracing.c:252:3: note: did you mean 'iree_tracing_zone_end'?
/home/stella/src/iree/runtime/src/iree/base/tracing/console.h:92:6: note: 'iree_tracing_zone_end' declared here
void iree_tracing_zone_end(iree_zone_id_t zone_id);
     ^
/home/stella/src/iree/runtime/src/iree/hal/drivers/cuda/tracing.c:263:3: error: implicit declaration of function 'iree_tracing_gpu_zone_begin_external' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  iree_tracing_gpu_zone_begin_external(context->id, query_id, file_name,
  ^
/home/stella/src/iree/runtime/src/iree/hal/drivers/cuda/tracing.c:263:3: note: did you mean 'iree_tracing_zone_begin_external_impl'?
/home/stella/src/iree/runtime/src/iree/base/tracing/console.h:88:37: note: 'iree_tracing_zone_begin_external_impl' declared here
IREE_MUST_USE_RESULT iree_zone_id_t iree_tracing_zone_begin_external_impl(
                                    ^
/home/stella/src/iree/runtime/src/iree/hal/drivers/cuda/tracing.c:273:3: error: implicit declaration of function 'iree_tracing_gpu_zone_end' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  iree_tracing_gpu_zone_end(context->id, query_id);
  ^
/home/stella/src/iree/runtime/src/iree/hal/drivers/cuda/tracing.c:273:3: note: did you mean 'iree_tracing_zone_end'?
/home/stella/src/iree/runtime/src/iree/base/tracing/console.h:92:6: note: 'iree_tracing_zone_end' declared here
void iree_tracing_zone_end(iree_zone_id_t zone_id);
     ^
7 errors generated.

```

### PR DESCRIPTION
**Pull request by ScottTodd**
This also refactors the job to use a GitHub-managed runner with less random GitHub Actions boilerplate for caching, env vars, etc. since the 'tracing' job is only building the runtime (as of https://github.com/openxla/iree/pull/6709, from 2021).

Fixes https://github.com/openxla/iree/issues/16405

### CODE REVIEW

File: build_tools/cmake/build_tracing.sh [hunk 1]
```diff
@@ -15,20 +15,28 @@ set -x
...
-  ccache --show-stats
-fi
+echo "::group::Building with -DIREE_TRACING_PROVIDER=console"
+"${CMAKE_BIN?}" -B "${BUILD_DIR}" \
+  -G Ninja . \
+  -DPython3_EXECUTABLE="${IREE_PYTHON3_EXECUTABLE}" \
+  -DPYTHON_EXECUTABLE="${IREE_PYTHON3_EXECUTABLE}" \
+  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
+  -DIREE_ENABLE_RUNTIME_TRACING=ON \
+  -DIREE_TRACING_PROVIDER=console \
```
Comment (ScottTodd) [inline build_tools/cmake/build_tracing.sh]: Oops. Forgot that https://github.com/openxla/iree/issues/16405 isn't fixed yet.

Error logs: https://github.com/openxla/iree/actions/runs/7937613025/job/21675129382?pr=16454#step:4:1238

Comment (ScottTodd) [inline build_tools/cmake/build_tracing.sh]: Seeing failures here that I can't reproduce on Windows :/

https://github.com/openxla/iree/actions/runs/7963638307/job/21739648223?pr=16454#step:4:1230

undefined reference to `iree_time_now`:
```
  FAILED: tools/iree-cpuinfo 
  : && /usr/bin/clang-9 -O2 -g -DNDEBUG -lm tools/CMakeFiles/iree-cpuinfo.dir/iree-cpuinfo.c.o -o tools/iree-cpuinfo  runtime/src/iree/base/libiree_base_base.a  runtime/src/iree/base/internal/libiree_base_internal_cpu.a  runtime/src/iree/base/libiree_base_base.a  runtime/src/iree/base/tracing/libiree_base_tracing_provider.a  -pthread && :
  /usr/bin/ld: runtime/src/iree/base/tracing/libiree_base_tracing_provider.a(console.c.o): in function `iree_tracing_zone_begin':
  /work/runtime/src/iree/base/tracing/console.c:145: undefined reference to `iree_time_now'
  /usr/bin/ld: /work/runtime/src/iree/base/tracing/console.c:145: undefined reference to `iree_time_now'
  /usr/bin/ld: runtime/src/iree/base/tracing/libiree_base_tracing_provider.a(console.c.o): in function `iree_tracing_zone_end':
  /work/runtime/src/iree/base/tracing/console.c:178: undefined reference to `iree_time_now'
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Unused variable:
```
  FAILED: runtime/src/iree/hal/drivers/cuda/CMakeFiles/iree_hal_drivers_cuda_cuda.objects.dir/nccl_channel.c.o 
  /usr/bin/clang-9 -DIREE_TRACING_MODE=2 -DIREE_TRACING_PROVIDER_H=\"iree/base/tracing/console.h\" -I/work -I/work/build-tracing -I/work/runtime/src -I/work/build-tracing/runtime/src -I/usr/local/iree_cuda_deps/include -I/work/third_party/nccl -I/work/build-tracing/runtime/src/iree/base/internal/flatcc -I/work/build-tracing/runtime/src/iree/schemas -isystem /work/third_party/flatcc/include -O2 -g -DNDEBUG -fPIC -fvisibility=hidden -Werror -Wall -Wno-error=deprecated-declarations -Wno-ambiguous-member-template -Wno-char-subscripts -Wno-extern-c-compat -Wno-gnu-alignof-expression -Wno-gnu-variable-sized-type-not-at-end -Wno-ignored-optimization-argument -Wno-invalid-offsetof -Wno-invalid-source-encoding -Wno-mismatched-tags -Wno-pointer-sign -Wno-reserved-user-defined-literal -Wno-return-type-c-linkage -Wno-self-assign-overloaded -Wno-sign-compare -Wno-signed-unsigned-wchar -Wno-strict-overflow -Wno-trigraphs -Wno-unknown-pragmas -Wno-unknown-warning-option -Wno-unused-command-line-argument -Wno-unused-const-variable -Wno-unused-function -Wno-unused-local-typedef -Wno-unused-private-field -Wno-user-defined-warnings -Wno-missing-braces -Wc++20-extensions -Wctad-maybe-unsupported -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wformat-security -Wgnu-redeclared-enum -Wimplicit-fallthrough -Winfinite-recursion -Wliteral-conversion -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wself-assign -Wstring-conversion -Wtautological-overlap-compare -Wthread-safety -Wthread-safety-beta -Wunused-comparison -Wvla -fno-omit-frame-pointer -pthread -I/work/third_party/flatcc/include/ -I/work/third_party/flatcc/include/flatcc/reflection/ -std=gnu11 -MD -MT runtime/src/iree/hal/drivers/cuda/CMakeFiles/iree_hal_drivers_cuda_cuda.objects.dir/nccl_channel.c.o -MF runtime/src/iree/hal/drivers/cuda/CMakeFiles/iree_hal_drivers_cuda_cuda.objects.dir/nccl_channel.c.o.d -o runtime/src/iree/hal/drivers/cuda/CMakeFiles/iree_hal_drivers_cuda_cuda.objects.dir/nccl_channel.c.o -c /work/runtime/src/iree/hal/drivers/cuda/nccl_channel.c
  /work/runtime/src/iree/hal/drivers/cuda/nccl_channel.c:558:26: error: unused variable 'collective_str' [-Werror,-Wunused-variable]
        iree_string_view_t collective_str =
                           ^
```

Comment (ScottTodd) [reply build_tools/cmake/build_tracing.sh]: Fixed the unused variable warning. Not sure how to make progress on the reference to `iree_time_now`. The code looks correct to me. Might need to set up a Linux machine to be able to reproduce and iterate on it locally.

Comment (ScottTodd) [reply build_tools/cmake/build_tracing.sh]: Tracked that down on Linux to using the system linker instead of LLD (via `-DIREE_ENABLE_LLD=ON`). Can fix that separately or as part of this 🤔

**Review by antiagainst — APPROVED** [review]

**Comment by jpienaar** [comment]
This just tests that it compiles, or does it test anything else?

**Comment by ScottTodd** [comment]
> This just tests that it compiles, or does it test anything else?

Just testing for compilation, yeah. Could add a lit test too 🤔

**Comment by ScottTodd** [comment]
Tried adding a lit test, but that ended up being tricky: https://github.com/iree-org/iree/actions/runs/9273552641/job/25513953669?pr=16454

* The tracing job just builds the runtime, but to run a lit test we need the compiler too
* Some other tests failed with console tracing enabled (random segfaults, didn't seem worth digging into)
