### PR TITLE
[Codegen] Add support to emulate unsupported float type

### LINKED ISSUE #19921: [ROCm][Codegen] llama 8b fp8 with attention segfault
### What happened?

iree compile bug  [llama_8b_fp8_atten_iree-comiple_gdbbug.txt](https://gist.github.com/AmosLewis/b35d16e2c4f1ab56d28942c57634e2c3#file-llama_8b_fp8_atten_iree-comiple_bug-txt)

```
iree-compile: iree/third_party/llvm-project/llvm/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From &) [To = mlir::detail::TypedValue<mlir::VectorType>, From = mlir::OpResult]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.

Thread 9 "llvm-worker-4" received signal SIGABRT, Aborted.
```

gdb shows the bug here so I guess its a codegen roc issue
```
#10 0x00007fffeb7a0402 in (anonymous namespace)::ExtFOnFloat8RewritePattern::rewrite (this=0x7fffa423dcf0, op=..., rewriter=...)
    at /home/chi/src/iree/third_party/llvm-project/mlir/lib/Conversion/ArithToAMDGPU/ArithToAMDGPU.cpp:113
...
#26 0x00007fffeb2e1b61 in mlir::iree_compiler::ConvertToROCDLPass::runOnOperation (this=0x7fffa43835e0)
    at /home/chi/src/iree/compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToROCDL.cpp:182
/home/chi/src/iree/compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToROCDL.cpp:182
```

### Steps to reproduce your issue

1. compile iree

``` 
cmake -G Ninja -B ../iree-build  -S . \
    -DCMAKE_BUILD_TYPE=Debug \
    -DIREE_ENABLE_ASSERTIONS=ON \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DIREE_ENABLE_RUNTIME_TRACING=ON \
    -DIREE_BUILD_TRACY=OFF \
    -DIREE_ENABLE_LLD=ON \
    -DIREE_BUILD_PYTHON_BINDINGS=ON \
    -DPython3_EXECUTABLE="$(which python3)" \
    -DIREE_TARGET_BACKEND_CUDA=OFF \
    -DIREE_HAL_DRIVER_HIP=ON \
    -DIREE_TARGET_BACKEND_ROCM=ON .
cmake --build ../iree-build
```
2.  Download input mlir here [f8_attn_chi_castf32_roctorch.mlir](https://sharkpublic.blob.core.windows.net/sharkpublic/chi/llama/atten/f8_attn_chi_castf32_roctorch.mlir), 
 > Optional:  Export the 8_attn_chi_castf32_roctorch.mlir manually with https://github.com/nod-ai/shark-ai/pull/907

run the following cmd:

``` 
 /home/chi/src/iree-build/tools/iree-compile f8_attn_chi_castf32_roctorch.mlir \
  --iree-hip-target=gfx942 \
  -o=f8_attn_chi_castf32_roctorch.vmfb \
  --iree-hal-target-device=hip \
  --iree-dispatch-creation-enable-aggressive-fusion=true \
  --iree-global-opt-propagate-transposes=true \
  --iree-opt-aggressively-propagate-transposes=true \
  --iree-opt-data-tiling=false \
  --iree-preprocessing-pass-pipeline='builtin.module(util.func(iree-preprocessing-generalize-linalg-matmul-experimental))' \
  --iree-hal-indirect-command-buffers=true \
  --iree-stream-resource-memory-model=discrete \
  --iree-hal-memoization=true \
  --iree-opt-strip-assertions
```

### What component(s) does this issue relate to?

Compiler

### Version information

commit 3f713f5f4743ddb6715e4ea4a361784b54489e5a (HEAD -> main, upstream/main)
Author: Jakub Kuderski <jakub@nod-labs.com>
Date:   Wed Jan 29 12:49:42 2025 -0500

    [ROCm] Add mi325x to known targets (#19846)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pashu123**
This change enables the conversion of types such as f8E4M3FNUZ and f8E5M2FNUZ (emulated via the existing APIs) into f32 operations. The conversion logic is now tightly coupled with the executable target attribute, so that it is applied only for the gfx942 target. This removes the need for manual pass configuration to specify source types and aligns the behaviour with the target’s capabilities. For any new conversion, just populate the conversion target with source and target types.

FIX: https://github.com/iree-org/iree/issues/19921#issuecomment-2643189839

### CODE REVIEW

**Review by AmosLewis — APPROVED** [review]

**Review by hanhanW — CHANGES_REQUESTED** [review]
I think it does not fix anything because you do not add the pass to any pipeline.. Can you add an e2e test to https://github.com/iree-org/iree/tree/main/tests/e2e/linalg?

Also, we need better documentation (and description) for the pass and the PR description.

E.g., people who dont have context might ask "what is unsupported float type"

**Comment by pashu123** [comment]
> I think it does not fix anything because you do not add the pass to any pipeline.. Can you add an e2e test to https://github.com/iree-org/iree/tree/main/tests/e2e/linalg?
> 
> Also, we need better documentation (and description) for the pass and the PR description.
> 
> E.g., people who dont have context might ask "what is unsupported float type"

You're right! After further thinking I'll wrap those emulate APIs in a fn and call it here: https://github.com/iree-org/iree/blob/624a9fae4f8dd03becfaae69110411c84c4ed6e8/compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToROCDL.cpp#L183 rather than creating a pass.

**Comment by krzysz00** [comment]
@pashu123 Because you need to run `--arith-to-amdgpu` to get the FP8 conversion instructions, you shouldn't just add the rewrites to ConvertotROCDL like that

This sort of thing does, with how stuff is architected today, likely need to be a pass.

See upstreams `--arith-emulate-unsupported-floats`

**Comment by pashu123** [comment]
> @pashu123 Because you need to run `--arith-to-amdgpu` to get the FP8 conversion instructions, you shouldn't just add the rewrites to ConvertotROCDL like that
> 
> This sort of thing does, with how stuff is architected today, likely need to be a pass.
> 
> See upstreams `--arith-emulate-unsupported-floats`

If you look at the current pass, it's using APIs from --arith-emulate-unsupported-floats pass. Would you like me to tailor the downstream pass for a subset of arith operations?

File: compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithToF32.cpp [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+
+} // namespace
+
+void ConvertUnsupportedFloatArithToF32Pass::runOnOperation() {
+
+  MLIRContext *context = &getContext();
+  Operation *op = getOperation();
+
+  // Add the source types to be converted to the target type.
+  SmallVector<Type> sourceTypes = {Float8E4M3FNUZType::get(context)};
```
Comment (krzysz00) [inline compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithToF32.cpp]: As a thought, could we merge the BF16 -> F32 arithmetic pass into this one?

Also, you'll also want the E5M2 type here

File: compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp [hunk 2]
```diff
@@ -1126,6 +1126,14 @@ static void addLowerToLLVMGPUPasses(OpPassManager &modulePassManager,
...
   if (forROCDL) {
     // convert to ROCDL.
+    funcPassManager.addPass([&]() {
+      ConvertUnsupportedFloatArithPassOptions options;
+      // Convert arith operation with the given `source types` to `target`
+      // type.
+      options.sourceTypeStrs = {"f8E4M3FNUZ", "f8E5M2FNUZ"};
+      options.targetTypeStr = "f32";
+      return createConvertUnsupportedFloatArithPass(options);
+    });
```
Comment (bjacob) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp]: The notion of which type is "supported" depends on the combination of (target architecture, specific operation, specific operand for that operation). For example, on CDNA3, we have matrix multiplication instructions that handle f8E4M3FNUZ and f8E5M2FNUZ for the LHS and RHS operands, but not for the accumulator operand. How is that nuance reflected in the logic being introduced in this PR?

Comment (pashu123) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp]: https://github.com/llvm/llvm-project/blob/b04a980b5597c61a8df2b489c4894bc0240b8e13/mlir/lib/Dialect/Arith/Transforms/EmulateUnsupportedFloats.cpp#L122 This doesn't touch those operations for now but in future should add the pattern downstream of what it should look for based on the target. I should add the pass under a flag checking the target.

Comment (bjacob) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp:1136]: I see... yes, it sounds like that is what is needed.

Comment (bjacob) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp]: The target should be looked up from the target attribute on the op that the pass is running on, not from a flag.

In the pass's runOnOperation() method, do something like `auto target = IREE::HAL::ExecutableTargetAttr::lookup(getOperation());` .

That means that the list of unsupported types shouldn't be a pass option. The pass should be option-less and act on the executable target. Similar to what this PR did (also see its test specifying targets): https://github.com/iree-org/iree/pull/19922

Comment (pashu123) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp]: Thanks for the info! It was constructive. I've updated the pass based on the target arch. This only populates `gfx94{*}` source and target types for now and can be updated based on the need.

File: compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+
+  auto gpuAttr = getGPUTargetAttr(op);
+  if (!gpuAttr)
+    return failure();
+
+  StringRef chipset = gpuAttr.getArch();
+  FailureOr<amdgpu::Chipset> maybeChipset = amdgpu::Chipset::parse(chipset);
+  if (failed(maybeChipset)) {
+    op->emitOpError() << "Invalid chipset name: " << chipset;
+    return failure();
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp]: It can be a single statement. `return op->emitOpError...`. I think we prefer `emitError` unless you want to print it out with "'op-name' op " prefix.

File: compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+    sourceTypes.insert(sourceTypes.end(), {Float8E4M3FNUZType::get(ctx),
+                                           Float8E5M2FNUZType::get(ctx)});
+    targetType = Float32Type::get(ctx);
+    return success();
+  }
+  return failure();
+}
+
+void ConvertUnsupportedFloatArithPass::runOnOperation() {
+
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp]: style nit: remove the leading blank lines.

File: compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp [hunk 5]
```diff
@@ -0,0 +1,107 @@
...
+  MLIRContext *context = &getContext();
+  Operation *op = getOperation();
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp]: Let's be clear that it is a FuncInterface pass, so let's do `FunctionOpInterface funcOp = getOperation()`.

File: compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp [hunk 6]
```diff
@@ -0,0 +1,107 @@
...
+          populateSourceAndTargetType(context, op, sourceTypes, targetType))) {
+    return;
+  }
+
+  if (sourceTypes.empty()) {
+    (void)emitOptionalWarning(
+        std::nullopt,
+        "no source types specified, float emulation will do nothing");
+    return signalPassFailure();
+  }
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp]: Doesn't it mean that it is a nop pass? In this case, we should not signal a pass failure.

File: compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp [hunk 7]
```diff
@@ -0,0 +1,107 @@
...
+
+  if (llvm::is_contained(sourceTypes, targetType)) {
+    emitError(UnknownLoc::get(context),
+              "target type cannot be an unsupported source type");
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp]: nit: use `op->emitError()`

File: compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp [hunk 8]
```diff
@@ -0,0 +1,107 @@
...
+  TypeConverter converter;
+  arith::populateEmulateUnsupportedFloatsConversions(converter, sourceTypes,
+                                                     targetType);
+  RewritePatternSet patterns(context);
+  arith::populateEmulateUnsupportedFloatsPatterns(patterns, converter);
+  ConversionTarget target(*context);
+  arith::populateEmulateUnsupportedFloatsLegality(target, converter);
+
+  if (failed(applyPartialConversion(op, target, std::move(patterns))))
+    signalPassFailure();
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp]: style nit: IREE uses braces for simple single-statement body.

```suggestion
  if (failed(applyPartialConversion(op, target, std::move(patterns)))) {
    signalPassFailure();
  }
```

File: compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp [hunk 9]
```diff
@@ -0,0 +1,107 @@
...
+void ConvertUnsupportedFloatArithPass::runOnOperation() {
+
+  MLIRContext *context = &getContext();
+  Operation *op = getOperation();
+  SmallVector<Type> sourceTypes;
+  Type targetType;
+
+  if (failed(
+          populateSourceAndTargetType(context, op, sourceTypes, targetType))) {
+    return;
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp]: I think the method does not need a return value. IMO, backends can skip the emulation by default if they do not care about the pass.

File: compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp (hunk 6 above)
Comment (pashu123) [reply compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp]: Any best practice in this case? Or a simple `return;`

File: compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp [hunk 10]
```diff
@@ -0,0 +1,106 @@
...
+
+struct ConvertUnsupportedFloatArithPass final
+    : public impl::ConvertUnsupportedFloatArithPassBase<
+          ConvertUnsupportedFloatArithPass> {
+  void runOnOperation() override;
+  using Base::Base;
+};
+
+} // namespace
+//
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp]: nit: typo? remove this line?

File: compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp (hunk 6 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp]: I'd suggest a log to LLVM_DEBUG and just a simple `return;`.

Comment (pashu123) [reply compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp]: I see. Thanks.

File: compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp (hunk 9 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp]: Can you add a comment about why this is resolved?

Comment (pashu123) [reply compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp]: Apologies for that! I misread that with debuginfo.

Comment (pashu123) [reply compiler/src/iree/compiler/Codegen/Common/ConvertUnsupportedFloatArithPass.cpp]: Done, PTAL.

File: compiler/src/iree/compiler/Codegen/Common/test/convert_unsupported_float_arith.mlir [hunk 11]
```diff
@@ -0,0 +1,42 @@
...
+// CHECK: return %[[TRUNC]] : f8E4M3FNUZ
+#executable_target_rocm_hsaco_fb = #hal.executable.target<"rocm", "rocm-hsaco-fb", {abi = "hip", iree.gpu.target = #iree_gpu.target<arch = "gfx942", features = "", wgp = <compute =  fp64|fp32|fp16|int64|int32|int16|int8, storage =  b64|b32|b16|b8, subgroup =  shuffle|arithmetic, dot =  dp4xi8toi32, mma = [<MFMA_F32_16x16x4_F32>, <MFMA_F32_16x16x16_F16>, <MFMA_F32_32x32x8_F16>, <MFMA_F64_16x16x4_F64>, <MFMA_F32_16x16x16_BF16>, <MFMA_F32_32x32x8_BF16>, <MFMA_F32_16x16x32_F8E5M2FNUZ>, <MFMA_F32_16x16x32_F8E5M2FNUZ_F8E4M3FNUZ>, <MFMA_F32_16x16x32_F8E4M3FNUZ>, <MFMA_F32_16x16x32_F8E4M3FNUZ_F8E5M2FNUZ>, <MFMA_F32_32x32x16_F8E5M2FNUZ>, <MFMA_F32_32x32x16_F8E5M2FNUZ_F8E4M3FNUZ>, <MFMA_F32_32x32x16_F8E4M3FNUZ>, <MFMA_F32_32x32x16_F8E4M3FNUZ_F8E5M2FNUZ>, <MFMA_I32_16x16x32_I8>, <MFMA_I32_32x32x16_I8>], subgroup_size_choices = [64], max_workgroup_sizes = [1024, 1024, 1024], max_thread_count_per_workgroup = 1024, max_workgroup_memory_bytes = 65536, max_workgroup_counts = [2147483647, 2147483647, 2147483647], max_load_instruction_bits = 128, simds_per_wgp = 4, vgpr_space_bits = 16384>>, ukernels = "none"}>
```
Comment (bjacob) [inline compiler/src/iree/compiler/Codegen/Common/test/convert_unsupported_float_arith.mlir]: If possible, find ways to elide some irrelevant parts of this target attribute. For instance, the `mma` array could be empty. (Side note: we should make `wgp` optional for things like this.)

**Review by bjacob — APPROVED** [review]

File: compiler/src/iree/compiler/Codegen/Common/test/convert_unsupported_float_arith.mlir (hunk 11 above)
Comment (pashu123) [reply compiler/src/iree/compiler/Codegen/Common/test/convert_unsupported_float_arith.mlir]: Sure.

**Review by hanhanW — APPROVED** [review]
Please update the PR description with detailed pass description and what is supported in the PR. E.g., Add what source and target conversion types for gfx94{*} series.
