### PR TITLE
[Dispatch] Clone scatter indices

### LINKED ISSUE #20077: llama 8b fp8 kv16 model compile failed
### What happened?

Find the error here https://github.com/nod-ai/shark-ai/pull/994#issuecomment-2679197958

input mlir https://sharkpublic.blob.core.windows.net/sharkpublic/chi/llama/fp8_32_kv16.mlir

detailed bug log [llama_fp8_kv16_compile_bug.txt](https://gist.github.com/AmosLewis/964b405594349c1ca1b44b104b8f399f)
```
iree-compile /sharedfile/32/fp8_32.mlir \
  --iree-hip-target=gfx942 \
  -o=/sharedfile/32/fp8_32.vmfb \
  --iree-hal-target-device=hip \
  --iree-dispatch-creation-enable-aggressive-fusion=true \
  --iree-global-opt-propagate-transposes=true \
  --iree-opt-aggressively-propagate-transposes=true \
  --iree-opt-data-tiling=false \
  --iree-preprocessing-pass-pipeline='builtin.module(util.func(iree-preprocessing-generalize-linalg-matmul-experimental))' \
  --iree-hal-indirect-command-buffers=true \
  --iree-stream-resource-memory-model=discrete \
  --iree-hal-memoization=true \
  --iree-opt-strip-assertions

/sharedfile/32/fp8_32_kv16.mlir:9019:13: error: 'func.func' op failed on workgroup distribution verification
    %3349 = torch.aten.index_put %3347, %3348, %3343, %false_2832 : !torch.vtensor<[?,32,8,128],bf16>, !torch.list<optional<vtensor>>, !torch.vtensor<[?,32,8,128],bf16>, !torch.bool -> !torch.vtensor<[?,32,8,128],bf16>
            ^
/sharedfile/32/fp8_32_kv16.mlir:9019:13: note: see current operation:

/sharedfile/32/fp8_32_kv16.mlir:28291:14: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"rocm", "rocm-hsaco-fb", {abi = "hip", iree.gpu.target = #iree_gpu.target<arch = "gfx942", features = "", wgp = <compute =  fp64|fp32|fp16|int64|int32|int16|int8, storage =  b64|b32|b16|b8, subgroup =  shuffle|arithmetic, dot =  dp4xi8toi32, mma = [<MFMA_F32_16x16x4_F32>, <MFMA_F32_16x16x16_F16>, <MFMA_F32_32x32x8_F16>, <MFMA_F64_16x16x4_F64>, <MFMA_F32_16x16x16_BF16>, <MFMA_F32_32x32x8_BF16>, <MFMA_F32_16x16x32_F8E5M2FNUZ>, <MFMA_F32_16x16x32_F8E5M2FNUZ_F8E4M3FNUZ>, <MFMA_F32_16x16x32_F8E4M3FNUZ>, <MFMA_F32_16x16x32_F8E4M3FNUZ_F8E5M2FNUZ>, <MFMA_F32_32x32x16_F8E5M2FNUZ>, <MFMA_F32_32x32x16_F8E5M2FNUZ_F8E4M3FNUZ>, <MFMA_F32_32x32x16_F8E4M3FNUZ>, <MFMA_F32_32x32x16_F8E4M3FNUZ_F8E5M2FNUZ>, <MFMA_I32_16x16x32_I8>, <MFMA_I32_32x32x16_I8>], subgroup_size_choices = [64], max_workgroup_sizes = [1024, 1024, 1024], max_thread_count_per_workgroup = 1024, max_workgroup_memory_bytes = 65536, max_workgroup_counts = [2147483647, 2147483647, 2147483647], max_load_instruction_bits = 128, simds_per_wgp = 4, vgpr_space_bits = 16384>>, ukernels = "none"}>
    %10763 = torch.aten.index_put %10761, %10762, %10757, %false_11018 : !torch.vtensor<[?,32,8,128],bf16>, !torch.list<optional<vtensor>>, !torch.vtensor<[?,32,8,128],bf16>, !torch.bool -> !torch.vtensor<[?,32,8,128],bf16>
```

### Steps to reproduce your issue

```
iree-base-compiler       3.3.0rc20250223
iree-base-runtime        3.3.0rc20250223
iree-turbine             3.3.0rc20250223
```
The input.mlir can be downloaded here  https://sharkpublic.blob.core.windows.net/sharkpublic/chi/llama/fp8_32_kv16.mlir
or exported by https://github.com/nod-ai/shark-ai/pull/994 
```
 python3 -m sharktank.examples.export_paged_llm_v1 --irpa-file=/sharedfile/llama3_8b_fp8.irpa  \
  --output-mlir=/sharedfile/32/fp8_32_kv16.mlir \
  --output-config=/sharedfile/32/config_32.json \
  --bs=1 --attention-kernel torch \
  --attention-dtype=bfloat16 \
  --kv-cache-dtype=bfloat16 \
  --activation-dtype=bfloat16 \
  --use-hf
```

```
wget  https://sharkpublic.blob.core.windows.net/sharkpublic/chi/llama/fp8_32_kv16.mlir

iree-compile /sharedfile/32/fp8_32_kv16.mlir \
  --iree-hip-target=gfx942 \
  -o=/sharedfile/32/fp8_32_kv16.vmfb \
  --iree-hal-target-device=hip \
  --iree-dispatch-creation-enable-aggressive-fusion=true \
  --iree-global-opt-propagate-transposes=true \
  --iree-opt-aggressively-propagate-transposes=true \
  --iree-opt-data-tiling=false \
  --iree-preprocessing-pass-pipeline='builtin.module(util.func(iree-preprocessing-generalize-linalg-matmul-experimental))' \
  --iree-hal-indirect-command-buffers=true \
  --iree-stream-resource-memory-model=discrete \
  --iree-hal-memoization=true \
  --iree-opt-strip-assertions
```

### What component(s) does this issue relate to?

Compiler

### Version information

iree-base-compiler       3.3.0rc20250223

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by IanWood1**
Clone `iree_linalg_ext.scatter`'s indices so that they are not also returned from the dispatch.

Fixes https://github.com/iree-org/iree/issues/20077

### CODE REVIEW

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp [hunk 1]
```diff
@@ -836,6 +847,13 @@ bool isClonableIntoDispatchOp(Operation *op,
   if (options.aggressive && isAttentionMaskGenerator(op)) {
     return true;
   }
+
+  // If the operation is used for the indices computation of a scatter op, it
+  // should be cloned into the dispatch.
+  if (options.aggressive && isScatterIndicesGenerator(op)) {
```
Comment (IanWood1) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp:853]: I'm not sure if this should be behind the aggressive flag, but since it causes re-computation it made sense

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp:853]: We should probably do it always. Cause we might have compilation issues without that.

**Review by MaheshRavishankar — APPROVED** [review]
