### PR TITLE
Integrate llvm-project@587d6fcbb685e3a57

### LINKED ISSUE #20928: [Integrate] Crash in pipeline_arm_sme_streaming_mode_tests
Identified that https://github.com/llvm/llvm-project/pull/140808 breaks the pipeline test.

https://github.com/iree-org/iree/blob/a6e81260f4eff372394f48452661c3b0dea59d94/compiler/src/iree/compiler/Codegen/LLVMCPU/test/pipeline_arm_sme_streaming_mode_tests.mlir#L77-L109

I failed to create an upstream repro, but here is a small repro in IREE: `iree-opt --iree-convert-to-llvm repro.mlir`

```mlir
func.func @foo(%2: memref<100x100xf32>, %3: index, %8: index) -> memref<?x?xf32, strided<[100, 1], offset: ?>> {
  %c100 = arith.constant 100 : index
  %vscale = vector.vscale
  %c4 = arith.constant 4 : index
  %c4_vscale = arith.muli %vscale, %c4 : index
  %5 = arith.subi %c100, %3 : index
  %6 = arith.cmpi slt, %5, %c4_vscale : index
  %7 = arith.select %6, %5, %c4_vscale : index
  %10 = arith.subi %c100, %8 : index
  %11 = arith.cmpi slt, %10, %c4_vscale : index
  %12 = arith.select %11, %10, %c4_vscale : index
  %subview = memref.subview %2[%3, %8] [%7, %12] [1, 1] : memref<100x100xf32> to memref<?x?xf32, strided<[100, 1], offset: ?>>
  return %subview : memref<?x?xf32, strided<[100, 1], offset: ?>>
}
```

It generates a remark about func op conversion, but it still triggers the error.

If you're looking for a "valid" repro, here is the one:

```mlir
module {
  func.func @scalable_dispatch_using_za() attributes {arm_locally_streaming, arm_new_za, hal.executable.target = #hal.executable.target<"llvm-cpu", "embedded-elf-arm_64", {cpu_features = "+sve,+sme", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "aarch64-none-elf"}>, translation_info = #iree_codegen.translation_info<pipeline = CPUDoubleTilingExpert>} {
    %0 = arm_sme.get_tile : vector<[4]x[4]xf32>
    %c1 = arith.constant 1 : index
    %c0 = arith.constant 0 : index
    %1 = builtin.unrealized_conversion_cast %c0 : index to i64
    %c4 = arith.constant 4 : index
    %c100 = arith.constant 100 : index
    "arm_sme.intr.zero"() <{tile_mask = 17 : i32}> : () -> ()
    %2 = hal.interface.binding.subspan layout(<constants = 1, bindings = [#hal.pipeline.binding<storage_buffer>, #hal.pipeline.binding<storage_buffer>, #hal.pipeline.binding<storage_buffer>]>) binding(2) alignment(64) offset(%c0) : memref<100x100xf32>
   memref.assume_alignment %2, 64 : memref<100x100xf32>
    %vscale = vector.vscale
    %c4_vscale = arith.muli %vscale, %c4 : index
    cf.br ^bb1(%c0 : index)
  ^bb1(%3: index):  // 2 preds: ^bb0, ^bb8
    %4 = arith.cmpi slt, %3, %c100 : index
    cf.cond_br %4, ^bb2, ^bb9
  ^bb2:  // pred: ^bb1
    %5 = arith.subi %c100, %3 : index
    %6 = arith.cmpi slt, %5, %c4_vscale : index
    %7 = arith.select %6, %5, %c4_vscale : index
    cf.br ^bb3(%c0 : index)
  ^bb3(%8: index):  // 2 preds: ^bb2, ^bb7
    %9 = arith.cmpi slt, %8, %c100 : index
    cf.cond_br %9, ^bb4, ^bb8
  ^bb4:  // pred: ^bb3
    %10 = arith.subi %c100, %8 : index
    %11 = arith.cmpi slt, %10, %c4_vscale : index
    %12 = arith.select %11, %10, %c4_vscale : index
    %subview = memref.subview %2[%3, %8] [%7, %12] [1, 1] : memref<100x100xf32> to memref<?x?xf32, strided<[100, 1], offset: ?>>
    %13 = builtin.unrealized_conversion_cast %subview : memref<?x?xf32, strided<[100, 1], offset: ?>> to !llvm.struct<(ptr, ptr, i64, array<2 x i64>, array<2 x i64>)>
    %14 = arith.index_cast %7 : index to i64
    %15 = arith.index_cast %c4_vscale : index to i64
    %16 = arith.cmpi slt, %14, %15 : i64
    %17 = arith.select %16, %14, %15 : i64
    %18 = arith.index_cast %17 : i64 to index
    %19 = vector.create_mask %12 : vector<[4]xi1>
    cf.br ^bb5(%c0 : index)
  ^bb5(%20: index):  // 2 preds: ^bb4, ^bb6
    %21 = builtin.unrealized_conversion_cast %20 : index to i64
    %22 = arith.cmpi slt, %20, %18 : index
    cf.cond_br %22, ^bb6, ^bb7
  ^bb6:  // pred: ^bb5
    %23 = llvm.extractvalue %13[1] : !llvm.struct<(ptr, ptr, i64, array<2 x i64>, array<2 x i64>)> 
    %24 = llvm.extractvalue %13[2] : !llvm.struct<(ptr, ptr, i64, array<2 x i64>, array<2 x i64>)> 
    %25 = llvm.getelementptr %23[%24] : (!llvm.ptr, i64) -> !llvm.ptr, f32
    %26 = llvm.mlir.constant(100 : index) : i64
    %27 = llvm.mul %21, %26 : i64
    %28 = llvm.add %27, %1 : i64
    %29 = llvm.getelementptr %25[%28] : (!llvm.ptr, i64) -> !llvm.ptr, f32
    %30 = arith.index_castui %20 : index to i32
    "arm_sme.intr.st1w.horiz"(%19, %29, %30) <{tile_id = 0 : i32}> : (vector<[4]xi1>, !llvm.ptr, i32) -> ()
    %31 = arith.addi %20, %c1 : index
    cf.br ^bb5(%31 : index)
  ^bb7:  // pred: ^bb5
    %32 = arith.addi %8, %c4_vscale : index
    cf.br ^bb3(%32 : index)
  ^bb8:  // pred: ^bb3
    %33 = arith.addi %3, %c4_vscale : index
    cf.br ^bb1(%33 : index)
  ^bb9:  // pred: ^bb1
    return
  }
}
```

cc @banach-space

### PR DESCRIPTION
**Pull request by hanhanW**
Carrying revert:
- https://github.com/iree-org/llvm-project/commit/1485df6415f0e44747b6bdb90878fb626dff6440

Cherry-pick:
- https://github.com/iree-org/llvm-project/commit/1b7547d06cc28a4b31cf12b263806522f92a49e1 (Mirror of https://github.com/llvm/llvm-project/pull/142025)

The revision also fixes torch-mlir for getBackwardSlice changes: https://github.com/iree-org/torch-mlir/commit/05a9860adb5ba33cc625a0c00b9a150d2a1fe5cb

The changes in IREE are for https://github.com/llvm/llvm-project/commit/6a8dde04a07287f837bbabeb93e23e47af366d3d

Closes https://github.com/iree-org/iree/issues/20928

### CODE REVIEW

**Comment by hanhanW** [comment]
Expose the visibility for others on future integration duties: https://github.com/iree-org/iree/issues/20645#issuecomment-2921182970 (and the following comment in the issue) provide the idea to drop the last revert. I don't have enough cycles to implement it. I can come back to it maybe after 2 weeks. I can prioritize it or provide guidance if it becomes a blocker.

**Review by benvanik — APPROVED** [review]

File: compiler/src/iree/compiler/Codegen/Common/GPU/DecomposeHorizontallyFusedGemms.cpp [hunk 1]
```diff
@@ -45,7 +45,9 @@ static LogicalResult captureUsedOperationsAndBlockArguements(
   auto yieldOp = cast<linalg::YieldOp>(linalgOp.getBlock()->getTerminator());
   Value result = yieldOp.getOperand(resultNumber);
 
-  getBackwardSlice(result, &usedOperations, options);
+  [[maybe_unused]] LogicalResult ret =
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/Common/GPU/DecomposeHorizontallyFusedGemms.cpp:48]: nit: llvm had a discussion on using `maybe_unsuded` vs. casting to void and decided on sticking to the latter: https://discourse.llvm.org/t/maybe-unused-vs-attribute-unused-vs-void-var-for-assert-variables/64212

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/GPU/DecomposeHorizontallyFusedGemms.cpp:48]: Thanks, I did not know this! I don't really follow why the conclusion is sticking to the latter. It seems that there is not enough data to say which option wins? I don't have a preference, and I'm okay with both. The reason that I use `maybe_unused` is just because it looks more modern and descriptive. It looks friendly to people who don't use c++ as their daily programming language, IMO.
