### PR TITLE
[scf] Fix Resource processing for `scf.for`

### LINKED ISSUE #15003: `iree-compile` crashes when input program has `scf` constructs
### What happened?

I'm trying to compile a model with loops in it and the conversion to the stream dialect (`iree-stream-conversion`) just asserts on these constructs.
```
iree/compiler/src/iree/compiler/Dialect/Stream/Conversion/PatternUtils.cpp:42:
mlir::iree_compiler::ConvertedTensor mlir::iree_compiler::consumeTensorOperand(mlir::Location, mlir::Value, mlir::OpBuilder &):
Assertion `false && "unexpected operand; expected either a IREE::Stream::ResourceType or " "the result of a mlir::UnrealizedConversionCastOp"' failed.
```

It doesn't seem that this pass is supposed to support these operations so it looks like that we are missing a `SCF -> CF` conversion somewhere in our pipeline.
That being said, I don't know that this is the right fix since I see at least one github issue around supporting `scf` dialect in `stream` https://github.com/openxla/iree/issues/13542.

I worked around this issue by adding such conversion pass before the stream conversion, but again, no idea if this is the right thing to do.
cc @benvanik for guidance.

Here is the raw patch (no test, no comment):
```
diff --git a/compiler/src/iree/compiler/Dialect/Stream/Transforms/Passes.cpp b/compiler/src/iree/compiler/Dialect/Stream/Transforms/Passes.cpp
index 797ac4773..c077789d4 100644
--- a/compiler/src/iree/compiler/Dialect/Stream/Transforms/Passes.cpp
+++ b/compiler/src/iree/compiler/Dialect/Stream/Transforms/Passes.cpp
@@ -82,6 +82,8 @@ void buildStreamTensorPassPipeline(OpPassManager &passManager,
   // Converts from all input dialects into various levels of the stream dialect.
   // Tensor-like things go to stream.tensor.* ops while lower level buffer-like
   // things will go to stream.async.* ops.
+  passManager.addNestedPass<func::FuncOp>(
+      IREE::Flow::createTopLevelSCFToCFGPass());
   passManager.addPass(IREE::Stream::createConvertToStreamPass());
 
   // No more tensor.*/etc ops are allowed. This is conservative - there may be
```

Note: The original use case doesn't directly come with `scf` instructions in it, these are inserted during the `iree-stablehlo-legalize-control-flow` pass.

### Steps to reproduce your issue

Using the following input MLIR:
```mlir
module {
  func.func @fill_matmul_static(%arg0: tensor<128x32xf32>, %arg1: tensor<32x64xf32>, %cond_storage: tensor<i1>) -> tensor<128x64xf32> {
    %cst = arith.constant 0.000000e+00 : f32
    %c0 = arith.constant 0 : i32
    %c1 = arith.constant 1 : i32
    %c5 = arith.constant 5 : i32
    %0 = tensor.empty() : tensor<128x64xf32>
    %1 = linalg.fill ins(%cst : f32) outs(%0 : tensor<128x64xf32>) -> tensor<128x64xf32>
    %3 = scf.for %arg2 = %c0 to %c5 step %c1 iter_args(%arg5 = %1) -> (tensor<128x64xf32>) : i32 {
      %2 = linalg.matmul ins(%arg0, %arg1 : tensor<128x32xf32>, tensor<32x64xf32>) outs(%arg5 : tensor<128x64xf32>) -> tensor<128x64xf32>
      scf.yield %2 : tensor<128x64xf32>
    }
    return %3 : tensor<128x64xf32>
  }
}
```

Compile with:
```bash
iree-compile --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-target-cpu=cascadelake  --iree-llvmcpu-target-triple=x86_64-unknown-linux-gnu  <in>.mlir -o <out>.vmfb
```

Result:
```
iree/compiler/src/iree/compiler/Dialect/Stream/Conversion/PatternUtils.cpp:42:
mlir::iree_compiler::ConvertedTensor mlir::iree_compiler::consumeTensorOperand(mlir::Location, mlir::Value, mlir::OpBuilder &):
Assertion `false && "unexpected operand; expected either a IREE::Stream::ResourceType or " "the result of a mlir::UnrealizedConversionCastOp"' failed.
```

Note: We get the same result with the `cuda` backend. I didn't check the others but I don't expect that would be different.

If we want to fix `iree-stream-conversion`, we can run just this one pass, with the following handcrafted reproducer:
```mlir
func.func @stuff(%arg0: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub} {
  %dim0 = hal.buffer_view.dim<%arg0 : !hal.buffer_view>[0] : index
  %0 = hal.tensor.import %arg0 : !hal.buffer_view -> tensor<i32>

  %c0 = arith.constant 0 : i32
  %c1 = arith.constant 1 : i32
  %c2 = arith.constant 2 : i32
  %c5 = arith.constant 5 : i32
  %152 = scf.for %arg19 = %c0 to %c5 step %c1 iter_args(%arg20 = %0) -> (tensor<i32>)  : i32 {
    %1 = flow.dispatch @executable::@dispatch(%arg20) : (tensor<i32>) ->tensor<i32>
    scf.yield %1 : tensor<i32>
  }

  %2 = hal.tensor.export %152 : tensor<i32> -> !hal.buffer_view
  return %2 : !hal.buffer_view
}
```

And run:
```
iree-opt --allow-unregistered-dialect  --iree-stream-conversion <in>.mlir -o <out>.mlir
```

### What component(s) does this issue relate to?

Compiler

### Version information

fb9e1b68f

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rsuderman**
Resource refinement did not include support for `scf.for`. Expanded to include
this support. This included some minor fixes for `scf.while`.

### CODE REVIEW

**Comment by rsuderman** [comment]
@qcolombet this should fix the SCF issue

**Comment by dcaballe** [comment]
Is this also what should get rid of the hanging issue?

**Comment by rsuderman** [comment]
> Is this also what should get rid of the hanging issue?

Balaji mentioned with this patch hanging was fixed but it may have been coincidental. I found a bug in the `scf.while` implementation so its possible it was a coincidence.

File: compiler/src/iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp [hunk 1]
```diff
@@ -492,6 +492,19 @@ class ValueResourceUsage : public AbstractResourceUsage<DFX::ValueElement> {
                 return WalkResult::advance();
               });
         })
+        .Case([&](mlir::scf::ForOp op) {
+          auto &operandUsage = solver.getElementFor<ValueResourceUsage>(
+              *this, Position::forValue(op.getOperand(operandIdx)),
+              DFX::Resolution::REQUIRED);
+          getState() ^= operandUsage.getState();
+          int64_t blockIdx = operandIdx > 0 ? operandIdx - 2 : operandIdx;
```
Comment (benvanik) [inline compiler/src/iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp]: anything else we could use for this? (operandIdx == 1 will result here in a -1 and that's bad - I suspect there's a helper for translating/some static thing we could use instead?)

File: compiler/src/iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp [hunk 2]
```diff
@@ -548,6 +561,19 @@ class ValueResourceUsage : public AbstractResourceUsage<DFX::ValueElement> {
                 *this, value, DFX::Resolution::REQUIRED);
             getState() ^= valueUsage.getState();
           }
+
```
Comment (benvanik) [inline compiler/src/iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp]: nesting the cases within a case feels a bit odd - are there any other ops that scf.yield could be parented in? we should probably default to failing or something if if/while/for are not matched as otherwise it'd cause hard to debug issues

File: compiler/src/iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp [hunk 3]
```diff
@@ -548,6 +561,19 @@ class ValueResourceUsage : public AbstractResourceUsage<DFX::ValueElement> {
...
+          if (auto forOp = dyn_cast_or_null<scf::ForOp>(op->getParentOp())) {
+            auto value = Position::forValue(
+                forOp.getRegion().front().getArgument(operandIdx + 1));
```
Comment (benvanik) [inline compiler/src/iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp]: same here with operandIdx indexing if we could have something more structured/less magic

File: compiler/src/iree/compiler/Dialect/Stream/Conversion/StandardToStream/ConvertStructuralOps.cpp [hunk 4]
```diff
@@ -304,6 +304,83 @@ struct ScfIfOpConversion : public OpConversionPattern<mlir::scf::IfOp> {
...
+    auto &block = op.getRegion().front();
+    TypeConverter::SignatureConversion newSignature(block.getNumArguments());
+    for (auto arg : llvm::enumerate(block.getArgumentTypes())) {
+      if (failed(typeConverter.convertSignatureArg(arg.index(), arg.value(),
+                                                   newSignature))) {
+        return failure();
+      }
+    }
+
+    // Create a new call that takes the expanded input operands and returns the
```
Comment (benvanik) [inline compiler/src/iree/compiler/Dialect/Stream/Conversion/StandardToStream/ConvertStructuralOps.cpp]:
```suggestion
    // Create a new loop that takes the expanded input operands and returns the
```

File: compiler/src/iree/compiler/Dialect/Stream/Conversion/StandardToStream/ConvertStructuralOps.cpp [hunk 5]
```diff
@@ -304,6 +304,83 @@ struct ScfIfOpConversion : public OpConversionPattern<mlir::scf::IfOp> {
...
+    // expanded output results. We can't directly replace the original call as
```
Comment (benvanik) [inline compiler/src/iree/compiler/Dialect/Stream/Conversion/StandardToStream/ConvertStructuralOps.cpp]:
```suggestion
    // expanded output results. We can't directly replace the original loop as
```

**Review by benvanik — CHANGES_REQUESTED** [review]
minor tweaks but otherwise LGTM!

File: compiler/src/iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp (hunk 3 above)
Comment (rsuderman) [reply compiler/src/iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp]: Fixed and removed magic numbers

File: compiler/src/iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp (hunk 1 above)
Comment (rsuderman) [reply compiler/src/iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp]: Fixed by removing magic numbers

File: compiler/src/iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp (hunk 2 above)
Comment (rsuderman) [reply compiler/src/iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp]: Do we have a mechanism for logging errors here? In theory the only issue is additional control flow analysis which would already fail if we encountered it.

Comment (rsuderman) [reply compiler/src/iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp]: I added a bunch of if/else statements with an assertion. Best I could think of.

File: compiler/src/iree/compiler/Dialect/Stream/Transforms/test/refine_usage.mlir [hunk 6]
```diff
@@ -307,3 +307,39 @@ func.func @testWhileRecurse(%arg0 : !stream.resource<*>) -> !stream.resource<ext
...
+// -----
+
+// CHECK-LABEL: @testForOp
+// CHECK-SAME: %[[ARG0:.+]]: index
+// CHECK-SAME: %[[ARG1:.+]]: !stream.resource<external>
+func.func @testForOp(%arg0 : index, %arg1 : !stream.resource<*>) -> !stream.resource<external> {
+  %c0 = arith.constant 0 : index
+  %c1 = arith.constant 1 : index
+  %c4 = arith.constant 4 : index
+
```
Comment (benvanik) [inline compiler/src/iree/compiler/Dialect/Stream/Transforms/test/refine_usage.mlir:320]:
```suggestion
```

File: compiler/src/iree/compiler/Dialect/Util/Analysis/Explorer.h [hunk 7]
```diff
@@ -234,7 +234,9 @@ class Explorer {
   // enumerated if there is recursion.
   TraversalResult walkIncomingBranchOperands(
```
Comment (benvanik) [inline compiler/src/iree/compiler/Dialect/Util/Analysis/Explorer.h:236]: add a line or two about what offset is

File: compiler/src/iree/compiler/Dialect/Stream/Transforms/RefineUsage.cpp [hunk 8]
```diff
@@ -303,6 +303,23 @@ struct ApplyScfIfOp : public UsageRefinementPattern<mlir::scf::IfOp> {
...
+                                PatternRewriter &rewriter) const override {
+    bool didChange = this->applyRegionTransitions(op, rewriter);
+    for (unsigned i = 0; i < op->getNumResults(); ++i) {
+      auto result = op->getResult(i);
+      if (llvm::isa<IREE::Stream::ResourceType>(result.getType())) {
+        if (this->applyResultTransition(op, result, rewriter))
+          didChange |= true;
+      }
+    }
+
```
Comment (benvanik) [inline compiler/src/iree/compiler/Dialect/Stream/Transforms/RefineUsage.cpp]:
```suggestion
```

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp [hunk 9]
```diff
@@ -182,9 +182,6 @@ void buildFlowTransformPassPipeline(OpPassManager &passManager,
         return createFormDispatchWorkgroupsPass(
             clDispatchGenerateWorkloadRegion);
       })
-      // TODO(#15003): SCF support appears to be insufficient for stream work.
-      // Need to debug the cause.
-      .addPass(IREE::Flow::createTopLevelSCFToCFGPass)
```
Comment (benvanik) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp:187]: follow-on: I noticed an upstream CFG -> SCF pass exists now - would be neat now that you have this plumbed through to start running that (assuming it works :)

**Review by benvanik — APPROVED** [review]
comment and nits then lgtm!

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp (hunk 9 above)
Comment (rsuderman) [reply compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp:187]: Lets check into turning this one once the whole pipeline is going on. As you pointed out in the other PR we are going to need a performance benchmark anyway.
