### PR TITLE
[LLVMGPU] Fix allocation space for thread local allocations

### LINKED ISSUE #498: Conv rocm numeric issue
The 2nd conv in the torch IR of SDXL unet for fp16 rocm is providing different results than the verified cpu fp32 version. Comparison of the tensor values from a tensor trace can be found in the following gist

https://gist.github.com/IanNod/72b4b13198ced90f3e3ef76ba25f094c

The conv in question is:
    %148 = torch.aten.convolution %140, %142, %143, %144, %145, %146, %false_146, %147, %int1_149 : !torch.vtensor<[2,320,128,128],f16>, !torch.vtensor<[320,320,3,3],f16>, !torch.vtensor<[320],f16>, !torch.list<int>, !torch.list<int>, !torch.list<int>, !torch.bool, !torch.list<int>, !torch.int -> !torch.vtensor<[2,320,128,128],f16>  
    
 Commands to compile and run:
 Rocm:
compile: tools/iree-compile \
    --iree-hal-target-backends=rocm \
    --iree-rocm-target-chip=gfx940 \
    --iree-rocm-link-bc=true \
    --iree-rocm-bc-dir=/opt/rocm/amdgcn/bitcode \
    --iree-global-opt-propagate-transposes=true \
    --iree-opt-outer-dim-concat=true \
    --iree-opt-const-eval=false \
    --iree-codegen-gpu-native-math-precision=true \
    --iree-rocm-waves-per-eu=2 \
    --iree-preprocessing-pass-pipeline="builtin.module(iree-preprocessing-transpose-convolution-pipeline)" \
    --iree-codegen-transform-dialect-library=attention_mfma_transform_64_spec.mlir \
    ../SHARK-Turbine/stable_diffusion_xl_base_1_0_64_1024x1024_fp16_unet.mlir -o rocm.vmfb
    
    run:
    tools/iree-run-module \
    --device=rocm --module=rocm.vmfb \
    --parameters=model=../SDXL1_unet.safetensors  \
    --function=main \
    --input=1x4x128x128xf16 --input=1xf16 --input=2x64x2048xf16 \
    --input=2x1280xf16 --input=2x6xf16 --input=1xf16 &> rocm_out.txt

cpu:
compile: iree-compile ../SHARK-Turbine/decomp_sdpa.mlir --iree-input-type=torch --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-opt-strip-assertions=true --verify=false --iree-llvmcpu-target-triple=x86_64-unknown-unknown-eabi-elf --iree-llvmcpu-target-cpu-features=host --iree-llvmcpu-fail-on-out-of-bounds-stack-allocation=false --iree-llvmcpu-distribution-size=32 --iree-opt-const-expr-hoisting=False --iree-codegen-linalg-max-constant-fold-elements=9223372036854775807 -o cpu.vmfb

    run:
    tools/iree-run-module \
    --device=local-task --module=cpu.vmfb \
    --parameters=model=../SDXL1_unet.safetensors  \
    --function=main \
    --input=1x4x128x128xf16 --input=1xf16 --input=2x64x2048xf16 \
    --input=2x1280xf16 --input=2x6xf16 --input=1xf16 &> cpu_out.txt

### PR DESCRIPTION
**Pull request by qedawkins**
If memory is allocated local to a thread, this needs to allocate private/local/function memory. Instead we are allocating workgroup memory right now, causing all threads to write to the same small buffer in the event of a conflict.

This looks at the insertion point of the allocation to determine the memory space to take. In general this is somewhat of a hack as bufferization doesn't provide any guarantee as to the insertion point of an allocation to my knowledge, but there is no other way for us to know where the allocation is happening.

This is also independent of the fact that such allocation are generally undesirable and should be treated as bugs, but this fixes incorrect numerics.

Fixes https://github.com/nod-ai/SHARK-Turbine/issues/498

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp [hunk 1]
```diff
@@ -58,19 +59,49 @@ llvm::cl::opt<int64_t> clLLVMGPUSharedMemoryLimit(
 // Bufferization Configuration
 //===----------------------------------------------------------------------===//
 
+static bool hasThreadMapping(scf::ForallOp forall) {
+  if (!forall.getMapping().has_value()) {
+    return false;
+  }
+  return llvm::any_of(forall.getMapping().value(), [](Attribute attr) {
+    return isa<gpu::GPUThreadMappingAttr>(attr);
+  });
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp:68]: unrelated to this PR, but I've seen this code patten a bunch of time now. Maybe we should add a helper upstream for `isa` to avoid writing all these lambdas...

**Review by antiagainst — CHANGES_REQUESTED** [review]
Do we need this kinda of analysis? I think we can just have two kinds of alloc function where one for workgroup memory and one for function memory? We can choose per pipeline, as the pipeline bufferization vs distribution order pretty much determines which one to use. We do that in SPIR-V:

https://github.com/openxla/iree/blob/2fe2975/compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp#L56-L83

**Comment by qedawkins** [comment]
> Do we need this kinda of analysis? I think we can just have two kinds of alloc function where one for workgroup memory and one for function memory? We can choose per pipeline, as the pipeline bufferization vs distribution order pretty much determines which one to use. We do that in SPIR-V:
> 
> https://github.com/openxla/iree/blob/2fe2975/compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp#L56-L83

Yes, and we probably need to change that on SPIR-V too. Because this happens before lowering a scf.forall, if a conflict happens inside the scf.forall we need a different memory space for the allocation than if the conflict happens outside the scf.forall.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp [hunk 2]
```diff
@@ -913,6 +944,11 @@ void registerCodegenROCDLPasses() {
       [](OpPassManager &passManager) {
         buildROCDLCodegenPassPipeline(passManager);
       });
+
+  static PassPipelineRegistration<> LLVMGPUBufferizePipeline(
+      "iree-codegen-llvmgpu-bufferize",
```
Comment (antiagainst) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp]: `iree-codegen-llvmgpu-bufferization-pipeline` to be consistent with others?

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/llvmgpu_bufferize.mlir [hunk 3]
```diff
@@ -0,0 +1,37 @@
+// RUN: iree-opt --iree-codegen-llvmgpu-bufferize --split-input-file %s | FileCheck %s
+
+module {
+  func.func @bufferize_thread_local(%arg0: index) {
```
Comment (antiagainst) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/test/llvmgpu_bufferize.mlir]: Nit: `bufferize_with_thread_private_memory`? (local memory in opencl means actually shared memory in cuda. it's a mess so better to avoid confusing terms..)

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/conv_pipeline_test.mlir [hunk 4]
```diff
@@ -90,3 +90,60 @@ hal.executable private @conv_nchw_dispatch_0 {
...
+        } -> tensor<2x320x64x64xf16>
+        flow.dispatch.tensor.store %10, %3, offsets = [0, 0, 0, 0], sizes = [2, 320, 64, 64], strides = [1, 1, 1, 1] : tensor<2x320x64x64xf16> -> !flow.dispatch.tensor<writeonly:tensor<2x320x64x64xf16>>
+        return
+      }
+    }
+  }
+}
+
+//   CHECK-LABEL:  func @conv_2d_nchw_fchw_2x320x64x64x320x3x3_f16
+//         CHECK:    memref.alloc
```
Comment (antiagainst) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/test/conv_pipeline_test.mlir]: Can we check the details (like memory space,etc.) w.r.t. these alloc ops? I think they are important. Also good to put a comment explaining what this tests is checking about so later it's easy for us to understand.

**Review by antiagainst — CHANGES_REQUESTED** [review]

**Comment by antiagainst** [comment]
> Yes, and we probably need to change that on SPIR-V too. Because this happens before lowering a scf.forall, if a conflict happens inside the scf.forall we need a different memory space for the allocation than if the conflict happens outside the scf.forall.

Looking at the logic you have yeah agreed it's a bit more robust. The SPIR-V side just assumes we would only need to resolve conflicts at one particular level within a specific pipeline; not necessarily always true. And SPIR-V side we are still using normal `scf.for` loop nest; that needs to be cleaned up.. A task for later though.

**Review by antiagainst — APPROVED** [review]
Comments not blocking actually. Feel free to land after addressing them!

**Comment by qedawkins** [comment]
> > Yes, and we probably need to change that on SPIR-V too. Because this happens before lowering a scf.forall, if a conflict happens inside the scf.forall we need a different memory space for the allocation than if the conflict happens outside the scf.forall.
> 
> Looking at the logic you have yeah agreed it's a bit more robust. The SPIR-V side just assumes we would only need to resolve conflicts at one particular level within a specific pipeline; not necessarily always true. And SPIR-V side we are still using normal `scf.for` loop nest; that needs to be cleaned up.. A task for later though.

Ah, didn't realize SPIR-V was still scf.for based. Yeah that will be harder so we can worry about that later.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/conv_pipeline_test.mlir (hunk 4 above)
Comment (qedawkins) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/test/conv_pipeline_test.mlir]: Oh I meant to drop this test. I'll leave it for now but add a TODO to drop it once the bufferization problem is fixed.

Comment (qedawkins) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/test/conv_pipeline_test.mlir]: Edit: Actually I already had the changes to check the memory space but forgot to commit it...

File: compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp (hunk 1 above)
Comment (qedawkins) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp:68]: that would be awesome, agree this pattern shows up quite frequently and `llvm::any_of` is relatively unwieldy.

Comment (kuhar) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp:68]: https://github.com/llvm/llvm-project/pull/83753

**Review by MaheshRavishankar — COMMENTED** [review]
Post submit comment. This is basically a hack (as you say). We should just use `bufferization.to _tensor` and set memory space accordingly. Then any allocation without a memory space we flag as a failure. Using bufferization to automatically create shared memory buffer is a huge footgun
