### PR TITLE
Fix stablehlo.reverse type conversion

### LINKED ISSUE #13723: `mhlo.sort` and `mhlo.reverse` fails to lower with `uint` values
Seems silly but I1 sorting is technically a thing and we should support via `iree_linalg_ext.sort`. We could consider radix sorting with splitk but probably just fix compilation to start.

```
module @jit_packbits attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<1x2x3x4xui8> {jax.arg_info = "a", mhlo.sharding = "{replicated}"}) -> (tensor<3xui8> {jax.result_info = ""}) {
    %0 = stablehlo.constant dense<0> : tensor<ui8>
    %1 = stablehlo.broadcast_in_dim %0, dims = [] : (tensor<ui8>) -> tensor<1x2x3x4xui8>
    %2 = stablehlo.compare  GT, %arg0, %1,  UNSIGNED : (tensor<1x2x3x4xui8>, tensor<1x2x3x4xui8>) -> tensor<1x2x3x4xi1>
    %3 = stablehlo.convert %2 : (tensor<1x2x3x4xi1>) -> tensor<1x2x3x4xui8>
    %4 = stablehlo.iota dim = 0 : tensor<8xui8>
    %5 = stablehlo.reverse %4, dims = [0] : tensor<8xui8>
    %6 = stablehlo.reshape %3 : (tensor<1x2x3x4xui8>) -> tensor<24xui8>
    %7 = stablehlo.reshape %6 : (tensor<24xui8>) -> tensor<3x8xui8>
    %8 = stablehlo.broadcast_in_dim %5, dims = [1] : (tensor<8xui8>) -> tensor<1x8xui8>
    %9 = stablehlo.broadcast_in_dim %8, dims = [0, 1] : (tensor<1x8xui8>) -> tensor<3x8xui8>
    %10 = stablehlo.shift_left %7, %9 : tensor<3x8xui8>
    %11 = stablehlo.convert %10 : (tensor<3x8xui8>) -> tensor<3x8xui32>
    %12 = stablehlo.constant dense<0> : tensor<ui32>
    %13 = stablehlo.reduce(%11 init: %12) across dimensions = [1] : (tensor<3x8xui32>, tensor<ui32>) -> tensor<3xui32>
     reducer(%arg1: tensor<ui32>, %arg2: tensor<ui32>)  {
      %15 = stablehlo.add %arg1, %arg2 : tensor<ui32>
      stablehlo.return %15 : tensor<ui32>
    }
    %14 = stablehlo.convert %13 : (tensor<3xui32>) -> tensor<3xui8>
    return %14 : tensor<3xui8>
  }
}
```

### PR DESCRIPTION
**Pull request by rsuderman**
The wrong return type was used when lowering to `iree_linalg_ext.reverse`. Correct to using the converted type

### CODE REVIEW

**Review by hanhanW — APPROVED** [review]

File: compiler/src/iree/compiler/InputConversion/MHLO/ConvertMHLOToLinalgExt.cpp [hunk 1]
```diff
@@ -410,7 +410,7 @@ struct ReverseOpConversion : public OpConversionPattern<mhlo::ReverseOp> {
     Value emptyTensor =
         rewriter.create<tensor::EmptyOp>(loc, mixedSizes, ty.getElementType());
     rewriter.replaceOpWithNewOp<IREE::LinalgExt::ReverseOp>(
-        op, op->getResultTypes(), adaptor.getOperands(), emptyTensor,
+        op, adaptor.getOperands().getType(), adaptor.getOperands(), emptyTensor,
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/InputConversion/MHLO/ConvertMHLOToLinalgExt.cpp]: Nit: Using operand types works, but really you want the `init` types I think? In this case it happens to be the same

Comment (rsuderman) [reply compiler/src/iree/compiler/InputConversion/MHLO/ConvertMHLOToLinalgExt.cpp]: I changed to using the type convert as its the technically correct version.
