### PR TITLE
[Codegen][GPU] Fix f32 attention compilation failure when head_dim=128

### LINKED ISSUE #24135: F32 Attention fails when head_dim=128
## What happened?

f32 attention with `hd=128` fails to compile for `gfx942` (MI300X) with:

```
error: 'func.func' op failed to distribute
```

This occurs in the `LLVMGPUVectorDistribute` pipeline. f32 attention with `hd=64` compiles successfully. All f16 attention shapes (both hd=64 and hd=128) compile and run correctly.

The failure affects all batch sizes tested (nh=1 through nh=192, seq=1024 through seq=16384).

## Steps to reproduce your issue

Input IR (`f32_attention_1x1024x128.mlir`):

```mlir
func.func @attention(%q: tensor<1x1024x128xf32>, %k: tensor<1x1024x128xf32>, %v: tensor<1x1024x128xf32>) -> tensor<1x1024x128xf32> {
  %scale = arith.constant 1.250000e-01 : f32
  %empty = tensor.empty() : tensor<1x1024x128xf32>
  %result = iree_linalg_ext.attention {
    indexing_maps = [affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2)>,
                     affine_map<(d0, d1, d2, d3, d4) -> (d0, d3, d2)>,
                     affine_map<(d0, d1, d2, d3, d4) -> (d0, d3, d4)>,
                     affine_map<(d0, d1, d2, d3, d4) -> ()>,
                     affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d4)>]}
    ins(%q, %k, %v, %scale : tensor<1x1024x128xf32>, tensor<1x1024x128xf32>, tensor<1x1024x128xf32>, f32)
    outs(%empty : tensor<1x1024x128xf32>) {
      ^bb0(%score: f32):
        iree_linalg_ext.yield %score : f32
    } -> tensor<1x1024x128xf32>
  return %result : tensor<1x1024x128xf32>
}
```

Command:

```sh
iree-compile f32_attention_1x1024x128.mlir \
  --iree-hal-target-backends=rocm \
  --iree-rocm-target=gfx942 \
  -o /dev/null
```

Changing `f32` to `f16` in the same IR compiles successfully.
Changing `hd` from 128 to 64 (i.e., `tensor<1x1024x64xf32>`) also compiles successfully.

## What component(s) does this issue relate to?

Compiler

## Version information

Commit `192602f8a7` on `main` (`[DispatchCreation] Limit attention broadcast fusion (#24127)`).

## Additional context

Assisted-by: Claude

### PR DESCRIPTION
**Pull request by keshavvinayak01**
Fix attention schedule deduction where QK intrinsic N was incorrectly set to PV intrinsic K, causing K2 tile to be smaller than the QK accumulator inner tile for f32, which later fails the packing in `GPUPackToIntrinsics`.

Added regression test for f32 attention with hd=128

Fixes #24135

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp [hunk 1]
```diff
@@ -1206,10 +1206,19 @@ FailureOr<std::pair<GPUMMASchedule, GPUMMASchedule>> deduceAttentionSchedule(
...
+      // so that packing the QK accumulator works without the intrinsic
+      // exceeding the tile size.
+      int64_t pvKTile = schedule.getTotalKTileSize() * schedule.getTotalKSize();
+      if (pvKTile % intrinsicAN != 0) {
+        return false;
+      }
+
       // Create a mma schedule for qkMatmul in attention.
       // qkMatmul.M = pvMatmul.M
       // qkMatmul.N = pvMatmul.K
```
Comment (Groverkss) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp]: Update the comment here please

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp [hunk 2]
```diff
@@ -1206,10 +1206,19 @@ FailureOr<std::pair<GPUMMASchedule, GPUMMASchedule>> deduceAttentionSchedule(
     int64_t intrinsicAN = intrinsicA.nSizes[0];
     int64_t intrinsicAK = intrinsicA.kSizes[0];
     auto isValidSchedule = [&](const GPUMMASchedule &schedule) -> bool {
+      // The PV K tile (= QK N tile) must be divisible by the QK intrinsic N
+      // so that packing the QK accumulator works without the intrinsic
+      // exceeding the tile size.
```
Comment (Groverkss) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp]: Can you write:

The output of QK matmul must be a valid lhs of PV matmul. The total lhs size of the PV matmul must be a multiple of the output size of the intrinsic used for QK matmul.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp [hunk 3]
```diff
@@ -1206,10 +1206,19 @@ FailureOr<std::pair<GPUMMASchedule, GPUMMASchedule>> deduceAttentionSchedule(
...
+      int64_t pvKTile = schedule.getTotalKTileSize() * schedule.getTotalKSize();
+      if (pvKTile % intrinsicAN != 0) {
+        return false;
+      }
```
Comment (Groverkss) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp:1218]: We also have to check pvMTile, not just pvKTile.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx942.mlir [hunk 4]
```diff
@@ -1267,3 +1267,54 @@ hal.executable.variant public @rocm target(<"rocm", "rocm-hsaco-fb">) {
...
+                qk_attrs = {lowering_config = #iree_gpu.lowering_config<{mma_kind = #iree_gpu.mma_layout<MFMA_F32_16x16x4_F32>, subgroup_basis = [[4, 1, 1, 1], [0, 1, 2]], promote_operands = [0, 1]}>},
+                pv_attrs = {lowering_config = #iree_gpu.lowering_config<{mma_kind = #iree_gpu.mma_layout<MFMA_F32_16x16x4_F32>, subgroup_basis = [[4, 1, 1, 1], [0, 2, 3]], promote_operands = [1]}>}
+               }}
+               ins(%4, %5, %6, %cst : tensor<1024x128xf32>, tensor<1024x128xf32>, tensor<1024x128xf32>, f32) outs(%7 : tensor<1024x128xf32>) {
+                ^bb0(%score: f32):
+                  iree_linalg_ext.yield %score : f32
+               } -> tensor<1024x128xf32>
+  iree_tensor_ext.dispatch.tensor.store %8, %3, offsets = [0, 0], sizes = [1024, 128], strides = [1, 1] : tensor<1024x128xf32> -> !iree_tensor_ext.dispatch.tensor<writeonly:tensor<1024x128xf32>>
+  return
+}
```
Comment (Groverkss) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx942.mlir]: This patch touches configuration, it should add a configurtion test, not a pipeline test.

**Review by Groverkss — CHANGES_REQUESTED** [review]

**Review by keshavvinayak01 — COMMENTED** [review]
@Groverkss Fixed.

File: compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp [hunk 5]
```diff
@@ -1206,10 +1206,21 @@ FailureOr<std::pair<GPUMMASchedule, GPUMMASchedule>> deduceAttentionSchedule(
...
+                        schedule.getTotalMSize() *
+                        schedule.getTotalMSubgroupCount();
+      int64_t pvKTile = schedule.getTotalKTileSize() * schedule.getTotalKSize();
+      if (pvMTile % intrinsicAM != 0 || pvKTile % intrinsicAN != 0) {
+        return false;
+      }
+
+      // Derive the QK schedule from the PV schedule. The QK and PV matmuls
+      // share M and K2 dimensions:
+      //   QK.M = PV.M, QK.N = PV.K (= K2), QK.K = head_dim
```
Comment (Groverkss) [inline compiler/src/iree/compiler/Codegen/Common/GPU/GPUHeuristics.cpp]: We don't have any head_dim terminology in IREE. It's either K1/N.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/config_vector_distribute_gfx942.mlir [hunk 6]
```diff
@@ -338,8 +338,8 @@ func.func @attention_20x4096x64x4096x64_f8() {
 // CHECK-SAME:           #iree_gpu.lowering_config
 // CHECK-SAME:            MFMA_F32_16x16x32_F8E4M3FNUZ
 // CHECK-SAME{LITERAL}:   subgroup_basis = [[1, 4, 1, 1, 1], [0, 1, 2, 3]]
-// CHECK-SAME: reduction =  [0, 0, 0, 128, 0]
-// CHECK-SAME: workgroup =  [1, 64, 0, 0, 64]
+// CHECK-SAME: reduction =  [0, 0, 0, 64, 0]
+// CHECK-SAME: workgroup =  [1, 64, 0, 0, 16]
```
Comment (Groverkss) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/config_vector_distribute_gfx942.mlir]: Why did this change? If this is changing then something is wrong with the logic. This will regress fp8 by a lot.

**Review by Groverkss — CHANGES_REQUESTED** [review]
Please check why the fp8 config test is regressing

**Comment by Groverkss** [comment]
Can you please write a comment on why the fp8 regression happened and why the new fix is correct? I can see the commit summary is AI written, but LLMs fixes are very narrow minded. Why do you think the old code was wrong and what changed? I cannot understand the LLM commit summary message.

**Comment by keshavvinayak01** [comment]
> Please check why the fp8 config test is regressing

The fix used correct tileN in the validation QK schedule, but the alignment check compared it against
`qkMatmul.n = nDims` (Which didn't divide the larger tile size for F8). `qkMatmul.n = K2Dims` should've been used.

**Comment by keshavvinayak01** [comment]
@Groverkss
Should I add a comment for that? Should be understandable from the qkMatmul assignments?

**Comment by Groverkss** [comment]
> @Groverkss Should I add a comment for that? Should be understandable from the qkMatmul assignments?

No I just meant a github comment, I just saw your comment now.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 7]
```diff
@@ -867,9 +867,12 @@ static LogicalResult setAttentionIntrinsicBasedVectorDistributionConfig(
   Type kElementType = getElementTypeOrSelf(kMatrix);
   Type vElementType = getElementTypeOrSelf(vMatrix);
   Type f32Type = b.getF32Type();
+  // qkMatmul: Q [M, K1] x K [K2, K1]^T -> S [M, K2]
```
Comment (keshavvinayak01) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:870]: @Groverkss This is that trivial comment. Can I remove this?

**Review by Groverkss — APPROVED** [review]
