### PR TITLE
Make ukernel code inlinable down to arch-specific function pointer selection.

### LINKED ISSUE #14262: Ukernel bitcode DCE'ing of non-taken SIMD variant paths is broken since #13825
Ukernels have generic code, and architecture-specific optimized code, itself having multiple code paths for target variants, such as, on x86-64, AVX512 vs AVX2.

In LLVMCPU, target information is known at compile time, so the intent is for the if() branches to resolve at compile time, resulting in all but one target-variant code path being DCE'd.

That was working as intended in @MaheshRavishankar 's original x86-64-only implementation, #13460.

But then, as I tried to make that work beyond x86-64, the first step was to separate architecture-specific from architecture-generic bitcode, #13825. That broke it. Bisection command line:

```
ninja iree-compile && tools/iree-compile ~/matmul_i8.mlir -o /tmp/a.vmfb --iree-flow-enable-data-tiling --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-enable-microkernels --iree-llvmcpu-target-triple=x86_64-unknown-unknown --iree-llvmcpu-keep-linker-artifacts --iree-llvmcpu-target-cpu=cascadelake 2>&1 --iree-llvmcpu-link-embedded=false | grep -o /tmp/.*[.]so | xargs nm | grep iree_uk_mmt4d
```

where `matmul_i8.mlir` is in [that gist](https://gist.github.com/bjacob/5ffaf3508a61ff6ac22ca98031be1629).

At #13460, this prints nothing, as everything has been inlined into the call site, as expected.

At #13825, this prints:

```
0000000000007360 t iree_uk_mmt4d_select_tile_func_arch
0000000000005c10 t iree_uk_mmt4d_tile_f32f32f32_16x16x1_x86_64_avx512_base
0000000000005200 t iree_uk_mmt4d_tile_f32f32f32_8x8x1_x86_64_avx2_fma
0000000000005e10 t iree_uk_mmt4d_tile_i8i8i32_16x16x2_x86_64_avx512_base
0000000000006e70 t iree_uk_mmt4d_tile_i8i8i32_16x16x2_x86_64_avx512_vnni
0000000000005320 t iree_uk_mmt4d_tile_i8i8i32_8x8x2_x86_64_avx2_fma
```

While inlining isn't a goal in itself, the clear bug that we see here is that there are `_avx2_fma` symbols, which we know are dead since we specified ` --iree-llvmcpu-target-cpu=cascadelake`, enabling `avx512` code paths.

I think it's clear what's happening. First we link the architecture-specific symbols with OverrideFromSrc, so we have all the above-listed symbols as overrides, but not yet actually called by anything since they are only called by architecture-generic bitcode which we haven't linked yet.
https://github.com/openxla/iree/blob/2f2d28c09e08a78f05b00e82707fa66f2fdf99a4/compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp#L471-L480

Then we load the architecture-generic bitcode, calling these symbols, thanks to the already-linked `iree_uk_mmt4d_select_tile_func_arch` overriding the weak symbol in the architecture-generic bitcode.
https://github.com/openxla/iree/blob/2f2d28c09e08a78f05b00e82707fa66f2fdf99a4/compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp#L488-L497

### PR DESCRIPTION
**Pull request by bjacob**
Fixes #14262 .

Unused ukernel code paths (e.g. different data types, different SIMD variants) were not getting DCE'd as intended. 

Code paths ("tile funcs") are selected by `*_select_tile_func_arch` functions, so in order for unused code paths to be DCE'd, these functions must be inlined. There were two problems preventing them from being inlined:

1. They had different target attributes. That's because these architecture-specific tile function selection functions were built with architecture-specific flags, while their caller was generic 64-bit code (built as wasm_64 and stripped of target attributes).
    * This is solved by moving these functions to separate `_entry_point.c` files, which are built as architecture-generic code to match their callers to make them effectively inlinable.
3. They were not marked as internal linkage by the time we run DCE, in  `runLLVMIRPasses`. The `fixupVisibility` function marks all functions as internal linkage, but only after `runLLVMIRPasses`.

### CODE REVIEW

File: compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp [hunk 1]
```diff
@@ -457,13 +459,36 @@ class LLVMCPUTargetBackend final : public TargetBackend {
              << targetTriple.str() << "'";
     }
 
+    // Tracks ukernel functions, in order to set their linkage to internal
+    // after ukernel bitcode modules are linked but before runLLVMIRPasses, so
+    // that unused ukernel code paths get DCE'd. Notes:
+    // 1. We can't rely on fixupVisibility to do this, because fixupVisibility
```
Comment (benvanik) [inline compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp:465]: I always love your comments <3

**Review by benvanik — APPROVED** [review]

File: compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp (hunk 1 above)
Comment (bjacob) [reply compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp:465]: thank you :-)
