### PR TITLE
Fix Python dtype conversion for int64 on Windows.

### LINKED ISSUE #11080: Arrays do not match in python/vm_types_test:test_variant_list_buffers on Windows
Spotted when adding a Windows CI build: https://github.com/iree-org/iree/actions/runs/3414442364/jobs/5682427788, and then reproduced locally.

Full logs:
```
    Start 1225: iree/runtime/bindings/python/vm_types_test
1225: Test command: C:\Python38\python.exe "D:/dev/projects/iree/runtime/bindings/python/tests/vm_types_test.py"
1225: Working Directory: D:/dev/projects/iree-build/runtime/bindings/python
1225: Environment variables: 
1225:  PYTHONPATH=D:/dev/projects/iree-build/compiler/bindings/python;D:/dev/projects/iree-build/runtime/bindings/python;
1225:  TEST_TMPDIR=D:/dev/projects/iree-build/test_tmpdir/iree/runtime/bindings/python/vm_types_test_test_tmpdir
1225: Test timeout computed to be: 10000000
1225: .INFO:root:variant_list: <VmVariantList(0): []>
1225: .F....
1225: ======================================================================
1225: FAIL: test_variant_list_buffers (__main__.VmTypesTest)
1225: ----------------------------------------------------------------------
1225: Traceback (most recent call last):
1225:   File "D:/dev/projects/iree/runtime/bindings/python/tests/vm_types_test.py", line 70, in test_variant_list_buffers
1225:     np.testing.assert_array_equal(ary1, ary2)
1225:   File "C:\Python38\lib\site-packages\numpy\testing\_private\utils.py", line 934, in assert_array_equal
1225:     assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
1225:   File "C:\Python38\lib\site-packages\numpy\testing\_private\utils.py", line 844, in assert_array_compare
1225:     raise AssertionError(msg)
1225: AssertionError: 
1225: Arrays are not equal
1225: 
1225: Mismatched elements: 3 / 4 (75%)
1225: Max absolute difference: 4
1225: Max relative difference: 0.5
1225:  x: array([1, 2, 3, 4], dtype=int64)
1225:  y: array([1, 0, 2, 0], dtype=int64)
1225: 
1225: ----------------------------------------------------------------------
1225: Ran 7 tests in 0.005s
1225: 
1225: FAILED (failures=1)
1225: <VmRef vm.list at 0x1a8a7d04ba0>
1225: <VmRef vm.list at 0x1a8a7d04ba0>
1225: <VmVariantList(0): []>
1225: <VmVariantList(0): []>
1225: <VmBuffer size 10 at 0x1a8a7d05030>
4/9 Test #1225: iree/runtime/bindings/python/vm_types_test ........***Failed    0.66 sec
```

Test code: https://github.com/iree-org/iree/blob/75636a94541ccd42e170c0bb72bf50a31b2a6cae/runtime/bindings/python/tests/vm_types_test.py#L49-L72

### PR DESCRIPTION
**Pull request by ScottTodd**
Fixes https://github.com/openxla/iree/issues/11080. The int64 and uint64 test cases here were failing on Windows as the element type mapping was routing via the code `l`, which is a "C long int" - not an explicitly 64 bit type. This changes the mapping to always use the explicit "type strings" (any string in `numpy.sctypeDict.keys()`, [shown in this gist](https://gist.github.com/ScottTodd/ec1f7906e9c644eb47f74280d6c26229)).

Relates to https://github.com/openxla/iree/pull/12872

### CODE REVIEW

File: runtime/bindings/python/hal.cc [hunk 1]
```diff
@@ -411,54 +411,59 @@ HalDevice HalDriver::CreateDeviceByURI(std::string& device_uri,
...
-  // TODO: Handle dtypes that do not map to a code (i.e. fp16).
-  const char* dtype_code;
+  // See:
+  //   * https://numpy.org/doc/stable/reference/arrays.dtypes.html
+  //   * https://docs.python.org/3/c-api/arg.html#numbers
+  //
+  // Single letter codes can be ambiguous across platforms, so prefer explicit
+  // bit depth values, ("Type strings: Any string in numpy.sctypeDict.keys()").
+  // See https://github.com/pybind/pybind11/issues/1908
+  const char* dtype_string;
```
Comment (ScottTodd) [inline runtime/bindings/python/hal.cc:421]: Hey @Eliasj42 , this is changing the same code as your https://github.com/openxla/iree/pull/12872 (nice timing on that and @allieculp 's ping on the Windows issue!). I think adding a complex test case to runtime/bindings/python/tests/vm_types_test.py might be enough for your PR, but we should also add more e2e tests using complex to ensure it works across all the layers.

**Review by jpienaar — APPROVED** [review]
Nice catch! Do we tests in place to fail if we regress? (I assume the test newly enabled on Windows)

**Comment by ScottTodd** [comment]
> Nice catch! Do we tests in place to fail if we regress? (I assume the test newly enabled on Windows)

Yeah, the newly enabled test covers this. We could still use some pure-python (no TF / other frameworks) tests that go through a more complete workflow with each data type though.
