### PR TITLE
Fixing fmaxf for CPU 16 bit

### LINKED ISSUE #14187: iree_linalg_ext.softmax on tensor<?xf16> causes linker error: undefined symbol: `fmaxf`
From minimizing https://github.com/openxla/iree/issues/14182.

It seems that any `softmax` on element type `f16` results in a failure to link on x86-64 due to a reference to `fmaxf`.

minimal testcase:

```mlir
func.func @softmax(%in : tensor<?xf16>, %out : tensor<?xf16>) -> tensor<?xf16> {
    %res = iree_linalg_ext.softmax dimension(0) ins(%in : tensor<?xf16>) outs(%out : tensor<?xf16>) -> tensor<?xf16>
    return %res : tensor<?xf16>
}
```

minimal repro:

```
iree-compile /tmp/a.mlir --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-target-triple=x86_64-linux-gnu -o /tmp/a.vmfb --mlir-print-op-on-diagnostic=false
```

resulting error:

```
lld: error: undefined symbol: fmaxf
```

This does not reproduce if `f16` is replaced by `f32`.

On `aarch64` we run into #14186 instead.

### PR DESCRIPTION
**Pull request by Ranvirsv**
This pull request addresses a bug affecting the 16bit fmaxf function when running on CPU. The function was erroring out, unlike its 32bit counterpart. The identified solution expands the operands to 32bit, performs the operation, and then reduces the results back to 16bit.

Our initial attempt to resolve the issue involved adding the conversion pattern to ConvertToLLVM.cpp, given a similar pattern exists for the conversion of MulSI from 32 to 64 bit. However, this approach was unsuccessful due to another conversion pattern within ExpandOps.cpp, which converts MaxF and MinF operations to respective CmpF operations. As the pass within ExpandOps.cpp is compiled prior to those inside ConvertToLLVM.cpp.

In response, we decided to write the pass into its own file: ExpandF16MaxFToF32Pass.cpp. We added this pass to Passes.cpp and LLVMCPUPasses.h. This alternative approach appears to resolve the issue, enabling successful 16bit MLIR compilation.

Fixes #14187.

### CODE REVIEW

**Review by hanhanW — COMMENTED** [review]
Can we contribute this to MLIR repo and then we use it in IREE?

**Comment by hanhanW** [comment]
It looks like it could be integrated into the pass that we're developing. https://reviews.llvm.org/D151519

We can extend the pass to converts f16 to f32 for arith ops. Basically it queries the target type from type_converter and replace it with a new op with target types. Not saying we have to land it as this way, just point out that it can fall into subtype emulation category.

**Comment by raikonenfnu** [comment]
> Can we contribute this to MLIR repo and then we use it in IREE?

Hey Hanhan, just FYI: Ranvir is part of our Summer of SHARK program at Nod. Yes, we can contribute this to MLIR and reuse in IREE. :)

**Comment by raikonenfnu** [comment]
> It looks like it could be integrated into the pass that we're developing. https://reviews.llvm.org/D151519
> 
> We can extend the pass to converts f16 to f32 for arith ops. Basically it queries the target type from type_converter and replace it with a new op with target types. Not saying we have to land it as this way, just point out that it can fall into subtype emulation category.

We can integrate this pattern into the pass once you landed it, although it is called `EmulateNarrowInt` and this is a float, maybe you can rename to EmulateNarrowNumerics? :)

**Comment by hanhanW** [comment]
Cool, welcome to the community!

Yes, I just left a review comment about renaming on the patch. 😀

**Comment by Ranvirsv** [comment]
> Cool, welcome to the community!
> 
> Yes, I just left a review comment about renaming on the patch. 😀

Great, Thank you 
What would I need to do next?

**Comment by raikonenfnu** [comment]
> > Cool, welcome to the community!
> > Yes, I just left a review comment about renaming on the patch. 😀
> 
> Great, Thank you What would I need to do next?

Hanhan can guide more on the merge/landing it into the new pattern. 
but first let's remove all the debug prints, then try run `git clang-format HEAD~1` to lint the code.
also tagging @dan-garvey since he might want to play around with this for some of his cpu LLM models :)

EDIT: We'd also need to add some LIT test for it.

**Comment by MaheshRavishankar** [comment]
THis is fairly hermetic. I am fine with this landing in IREE (even if it short term)...

File: compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+namespace {
+
+struct ExpandF16MaxFToF32Pattern : public OpRewritePattern<arith::MaxFOp> {
+  public:
+    using OpRewritePattern<arith::MaxFOp>::OpRewritePattern;
+
+    LogicalResult matchAndRewrite(arith::MaxFOp op, 
+                                  PatternRewriter &rewriter) const override{
+      Type resultType = op.getLhs().getType();
+      llvm::outs()<<"\n\n Added \n\n";
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp]: Please wrap these within

```
LLVM_DEBUG({ ...

})
```

you should be able to find examples of this in the code base. Also the convention is that you write to `llvm:dbgs()`... instead of `llvm::outs`. Such debug prints should be within `LLVM_DEBUG({..})` so that it is not on by default but can be enabled using flag on debug builds for debugging help.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Looks good overall. Few house keeping comments.

Apart from in-code comments, there should be changes to `Passes.td` file as well. I dont see this as part of this change...

**Comment by hanhanW** [comment]
I am also fine with landing it in IREE even if it is short-term. We can upstream it and retire the pattern later, like what we've done in IREE before.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp (hunk 1 above)
Comment (Ranvirsv) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp]: Understood 
Thank you

File: tests/transform_dialect/cpu/fmaxf_16bit_expantion.mlir [hunk 2]
```diff
@@ -0,0 +1,21 @@
+
```
Comment (hanhanW) [inline tests/transform_dialect/cpu/fmaxf_16bit_expantion.mlir]: You need to trigger the iree-opt run and FileCheck, see other `.mlir` file for examples.

File: compiler/src/iree/compiler/Codegen/Passes.td [hunk 3]
```diff
@@ -635,6 +635,14 @@ def LLVMCPULowerExecutableTarget :
       "mlir::iree_compiler::createLLVMCPULowerExecutableTargetPass()";
 }
 
+def ExpandF16MaxFToF32 :
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Passes.td]: I assume that there could be more arith ops needing the conversion? If so, we can rename it to `ExpandArithF16ToF32`, so we don't only scope it to max op.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp [hunk 4]
```diff
@@ -0,0 +1,82 @@
+// Copyright 2021 The IREE Authors
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp]: 2023

File: compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+#include "iree/compiler/Codegen/Utils/Utils.h"
+#include "llvm/Support/Debug.h"
+#include "mlir/Dialect/Vector/Transforms/LoweringPatterns.h"
+#include "mlir/Dialect/Vector/Transforms/VectorRewritePatterns.h"
+#include "mlir/Dialect/Vector/Transforms/VectorTransforms.h"
+#include "mlir/Pass/Pass.h"
+#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
+#include "mlir/Dialect/Linalg/IR/Linalg.h"
+#include "mlir/Dialect/Tensor/IR/Tensor.h"
+#include "mlir/Dialect/Arith/IR/Arith.h"
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp]: Many includes are not needed, please remove them.

File: tests/transform_dialect/cpu/fmaxf_16bit_expantion.mlir [hunk 6]
```diff
@@ -0,0 +1,22 @@
+// RUN: iree-opt %s
```
Comment (MaheshRavishankar) [inline tests/transform_dialect/cpu/fmaxf_16bit_expantion.mlir]: This is actually not running the pass and test.... This should be

```
iree-opt --iree-llvmcpu-expand-max-f16-to-f32 %s | FileCheck %s
```

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]

File: tests/transform_dialect/cpu/fmaxf_16bit_expantion.mlir (hunk 6 above)
Comment (MaheshRavishankar) [inline tests/transform_dialect/cpu/fmaxf_16bit_expantion.mlir]: This shouldnt be in `tests/transform_dialect/cpu`. It should be in here
https://github.com/openxla/iree/tree/main/compiler/src/iree/compiler/Codegen/LLVMCPU/test with the other CPU passes test.

Please add this test to [this](https://github.com/openxla/iree/blob/8c41e5177f6a8cc33200bb91c8b01dee72bf0942/compiler/src/iree/compiler/Codegen/LLVMCPU/test/BUILD.bazel#L20) list and from your IREE source root directory you should run

```
build_tools/bazel_to_cmake/bazel_to_cmake.py
```

This will update the relevant CMake file.

Sorry for the hoops to jump through here...

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]

File: tests/transform_dialect/cpu/fmaxf_16bit_expantion.mlir (hunk 6 above)
Comment (Ranvirsv) [reply tests/transform_dialect/cpu/fmaxf_16bit_expantion.mlir]: Sure, I'll do that. Thank you for the help.

File: compiler/src/iree/compiler/Codegen/Passes.td [hunk 7]
```diff
@@ -635,6 +635,14 @@ def LLVMCPULowerExecutableTarget :
       "mlir::iree_compiler::createLLVMCPULowerExecutableTargetPass()";
 }
 
+def ExpandArithF16ToF32 :
+    Pass<"iree-llvmcpu-expand-max-f16-to-f32", ""> {
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Passes.td]: We should also update the pass command, the summary and all the related functions.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/test/fmaxf_16bit_expantion.mlir [hunk 8]
```diff
@@ -0,0 +1,21 @@
...
+// CHECK: %[[TRUNC:.*]] = arith.truncf %[[MAX]] : tensor<4xf16>
+// CHECK: return %[[TRUNC]] : tensor<4xf16>
+
+// CHECK-LABEL: func @test_expand_f16_maxf
+// CHECK: %[[EXT1:.*]] = arith.extf %arg0 : vector<4xf16> to vector<4xf32> 
+// CHECK: %[[EXT2:.*]] = arith.extf %arg1 : vector<4xf16> to vector<4xf32>
+// CHECK: %[[MAX:.*]] = arith.maxf %[[EXT1]], %[[EXT2]] : vector<4xf32>
+// CHECK: %[[TRUNC:.*]] = arith.truncf %[[MAX]] : vector<4xf16>
+// CHECK: return %[[TRUNC]] : vector<4xf16>
+
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/test/fmaxf_16bit_expantion.mlir]: Please add a test for vector type cases?

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp [hunk 9]
```diff
@@ -690,6 +690,7 @@ static void addLowerToLLVMPasses(OpPassManager &passManager) {
 
 void buildLLVMCPUCodegenPassPipeline(OpPassManager &passManager) {
   addCommonTargetExecutablePreprocessingPasses(passManager.nest<ModuleOp>());
+  passManager.addPass(createExpandF16MaxFToF32Pass());
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: Is this where it always was? I thought this was supposed to be done in the `addLowerToLLVMPasses` call.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Thanks for the updates... I think just one more comment left.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp (hunk 9 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: I think it can be added before ArithExpandOpsPass.

https://github.com/openxla/iree/blob/8c41e5177f6a8cc33200bb91c8b01dee72bf0942/compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp#L673-L675

Comment (Ranvirsv) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: It seems to give me the same fmaxf error, if I add the pass in addLowerToLLVMPasses.
I tried adding it before passManager.addNestedPass<func::FuncOp>(arith::createArithExpandOpsPass()); 
But run into error. I also tried adding it even before in addLowerToLLVMPasses, but I still get the fmaxf error

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: What is the error? Can you share the input MLIR file and the IR dumps?

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: Could you post the output of `iree-compile` with `--mlir-disable-threading --mlir-print-ir-after-all --mlir-print-ir-before-all` somewhere. It is going to dump a lot of IR so do 
```
iree-compiler <other-flags> --mlir-disable-threading --mlir-print-ir-after-all --mlir-print-ir-before-all <input_file> -o test.vmfb 2> debug.log
```

and upload `debug.log` somewhere (easiest is on `gist.github.com`)

Comment (Ranvirsv) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: [linalg_mlir.txt](https://github.com/openxla/iree/files/11617391/linalg_mlir.txt)
[linalg_error.txt](https://github.com/openxla/iree/files/11617409/linalg_error.txt)


This is the error I get 
```
lld: error: undefined symbol: fmaxf
>>> referenced by -:4
>>>               /tmp/forward_dispatch_42_softmax_2x5x4096x4096xf16_dispatch_0-f3c0df.o:(forward_dispatch_42_softmax_2x5x4096x4096xf16_dispatch_0_softmax_2x5x4096x4096xf16)
>>> referenced by -:4
>>>               /tmp/forward_dispatch_42_softmax_2x5x4096x4096xf16_dispatch_0-f3c0df.o:(forward_dispatch_42_softmax_2x5x4096x4096xf16_dispatch_0_softmax_2x5x4096x4096xf16)
>>> referenced by -:4
>>>               /tmp/forward_dispatch_42_softmax_2x5x4096x4096xf16_dispatch_0-f3c0df.o:(forward_dispatch_42_softmax_2x5x4096x4096xf16_dispatch_0_softmax_2x5x4096x4096xf16)
```

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: > In response, we decided to write the pass into its own file: ExpandF16MaxFToF32Pass.cpp. We added this pass to Passes.cpp and LLVMCPUPasses.h. This alternative approach appears to resolve the issue, enabling successful 16bit MLIR compilation.

I thought that you put it to the beginning because it would work. But it seems not. The log you attached is using the current order, and it produces the error? Do I misunderstand something?

side question -- I mis-track if we are able to load/store fp16 in CPU backend. Will we need emulation for fp16 load/store?

Comment (raikonenfnu) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: Hey @hanhanW, @Ranvirsv has tried adding it right above `ArithExpandOpsPass` but it was failing, so he tried again putting it a bit earlier, i.e at the start of `addLowerToLLVMPasses`. However, both of these places ends up generating the error which he uploaded above.

The only place that has worked so far(**compiles + without error**) is in `buildLLVMCPUCodegenPassPipeline`.

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: Whats happening here is that the `fmaxf` is being generated by the LLVM backend... I still cant really see the error. What is atteched as `linalg_error.mlir` is with the pass being run early vs being run late..... Really it shouldnt matter whether it is run there or before `addLowerToLLVMPasses`. So looking at the IR when the pass is added late would help. Maybe there is a reason why this expansion isnt triggering when added late.

Comment (Ranvirsv) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: I am sorry, this is the file with the error log
This is when running the pass late (in ```addLowerToLLVMPasses```) 

[linalg_error.log](https://github.com/openxla/iree/files/11619428/linalg_error.log)

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: Ok there are a couple of issues here....
1) I think your pass is not geared to handle vector types, and at this stage after this is vectorized you get a `vector.reduction` of `maxf` 
```
 %51 = vector.reduction <maxf>, %28, %50 : vector<32xf16> into f16
```
So doing this all the way at the start is basically avoiding this, so its kind of a WAR.....
@raikonenfnu how important is this change for you guys? Its a legit workaround... but it is hiding the deeper issue. So trying to balance these.

2) @dcaballe and @hanhanW this is another instance of issue we have seen in different places.... There is a lot of `vector` ops being generated. We need to handle this..... Is there already an issue tracking this. We probably need an EPIC that can capture all bugs related to this issue.

Comment (powderluv) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: This is required for LLaMA / Vicuna FP16 models on CPU. Very high priority for us so we can at least do FP16 for LLMs on CPU with IREE (llama.cpp etc are on int4 and we have to get to that soon).

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: Sigh... Well we need to fix the overall vectorization story . But to unblock for now adding it here is fine. Could you please add a TODO to say this pass is being done way too late.... and it needs to happen during lowering to LLVM. Could you also file an issue documenting the reason why this is being done here. So file and issue and add a 
```
// TODO(#<issue_number) : <reason>
```

File: compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp [hunk 10]
```diff
@@ -0,0 +1,73 @@
...
+#include "mlir/Pass/Pass.h"
+#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
+#include "mlir/Dialect/Arith/IR/Arith.h"
+
+namespace mlir {
+namespace iree_compiler {
+
+namespace {
+
+struct ExpandF16MaxFToF32Pattern : public OpRewritePattern<arith::MaxFOp> {
```
Comment (dcaballe) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp]: Please, add doc to the pattern

File: compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+        wideType = VectorType::get(vecTy.getShape(), wideType);
+      }
+
+      Value lhsExt = rewriter.create<arith::ExtFOp>(loc, wideType, op.getLhs());
+      Value rhsExt = rewriter.create<arith::ExtFOp>(loc, wideType, op.getRhs());
+      Value maxExt = 
+          rewriter.create<arith::MaxFOp>(loc, wideType, lhsExt, rhsExt);
+      Value result = rewriter.create<arith::TruncFOp>(loc, resultType, maxExt);
+
+      rewriter.replaceOp(op, result);
```
Comment (dcaballe) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp]: you can use `rewriter.replaceOpWithNewOp<arith::TruncFOp>(op, resultType, maxExt);` and remove the `replaceOp` singleton.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp [hunk 12]
```diff
@@ -0,0 +1,73 @@
...
+      return success();
+    }
+};
+
+struct ExpandF16MaxFToF32Pass
+    : public ExpandArithF16ToF32Base<ExpandF16MaxFToF32Pass> {
+  void getDependentDialects(DialectRegistry &registry) const override {
+    registry.insert<linalg::LinalgDialect>();
+  }
```
Comment (dcaballe) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp]: This should be moved to the .td file and auto-generated. There is some tablegen command to add dialect dependencies.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUPasses.h [hunk 13]
```diff
@@ -35,6 +35,9 @@ createLLVMCPUEmitVectorizationRemarksPass();
 std::unique_ptr<OperationPass<IREE::HAL::ExecutableVariantOp>>
 createLLVMCPULowerExecutableTargetPass();
 
+/// Convert F16 to f32 max.
```
Comment (dcaballe) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUPasses.h]: Could we elaborate a bit more the doc, please?

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp (hunk 9 above)
Comment (dcaballe) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: Not sure what I follow the problem here. Would you mind elaborating? What do you mean by "There is a lot of vector ops being generated"? 

If this is expanding f16 -> f32 max ops, this should happen before vectorization and then the vectorizer should generate the corresponding f32 max reduction. After that, the maxf operation should be expanded to a cmp/select op (I'm assuming that the frontend has generated all the handling for the fp corner cases (ie., NaN, inf, etc.)).

Comment (Ranvirsv) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: Sure sound's good.

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: I'm surprised that it works if you only convert maxf op. Why only maxf op is needed?

@MaheshRavishankar , the reduction on f16 is generated because other operations are not expanded to f32.

```
 %51 = vector.reduction <maxf>, %28, %50 : vector<32xf16> into f16
```

Shouldn't we also handle other arith ops like subf, extf, addf?

https://gist.githubusercontent.com/hanhanW/1f85a07d1d3e75309168fc4d01f8be17/raw/ae9e627246b444c94c0fa49327a0329034b4104d/a.mlir

---

The other issue is that the first generic op is not vectorized even it has a static shape. Maybe should fie an issue and assign it to Diego..

https://gist.github.com/hanhanW/d3ba1367ed79236217ffc4c24f0db319

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: RE @dcaballe about "There is a lot of vector ops being generated", I think it means that we don't tile the operations enough. In this case, we unroll some huge vectors, which results in a lot of vector ops before LLVM conversion.

This one is another example that we need multi lowering config, though it is more complicated. It is reduction -> reduction -> element with triangle deps..

File: compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp (hunk 12 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp]: I would put this as not required category for now... that is a good convention, but it isnt done in other passes. We can make this a strong requirement once the code base is consistent w.r.t that.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp (hunk 9 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: > I'm surprised that it works if you only convert maxf op. Why only maxf op is needed?
> 
> @MaheshRavishankar , the reduction on f16 is generated because other operations are not expanded to f32.
> 
> ```
>  %51 = vector.reduction <maxf>, %28, %50 : vector<32xf16> into f16
> ```
> 

THe issue is `fmaxf` lowers to a libc function while others dont....

**Review by MaheshRavishankar — APPROVED** [review]
Please address some of the comments from other people. I am unblocking for now.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp (hunk 9 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: @dcaballe see #13888 . Lets carry over the thread there and let @Ranvirsv land this PR after all other minor comments are addressed.

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: Okay, I know what's happening.. I looked into wrong log.. we can put it here for now and should file an issue documenting the reason.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp (hunk 12 above)
Comment (Ranvirsv) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp]: Do you guys have any specific .td file you want me to add this to?

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp (hunk 9 above)
Comment (Ranvirsv) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: > Sigh... Well we need to fix the overall vectorization story . But to unblock for now adding it here is fine. Could you please add a TODO to say this pass is being done way too late.... and it needs to happen during lowering to LLVM. Could you also file an issue documenting the reason why this is being done here. So file and issue and add a
> 
> ```
> // TODO(#<issue_number) : <reason>
> ```

is this the issue ``` Vector lowering results in IR explosion #13888 ```, or should I make a different issue?

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp]: You can use #13888 (also @hanhanW I filed an issue with the log)

File: compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp (hunk 12 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/ExpandF16MaxFToF32Pass.cpp]: I think you can just leave this as is for now.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/test/CMakeLists.txt [hunk 14]
```diff
@@ -24,6 +24,7 @@ iree_lit_test_suite(
     "convert_to_llvm.mlir"
     "data_tiling_pipeline.mlir"
     "emit_vectorization_remarks.mlir"
+    "fmaxf_16bit_expantion.mlir"
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/test/CMakeLists.txt]: can we rename the file to relative name, like `expand_f16_op_to_f32.mlir`?

File: compiler/src/iree/compiler/Codegen/Passes.td [hunk 15]
```diff
@@ -635,6 +635,14 @@ def LLVMCPULowerExecutableTarget :
       "mlir::iree_compiler::createLLVMCPULowerExecutableTargetPass()";
 }
 
+def ExpandArithF16ToF32 :
+    Pass<"iree-llvmcpu-expand-f16-Op-to-f32", ""> {
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Passes.td]: it is weird to see capital case in the cmd flag, can we replace `Op` with `op`?

**Review by hanhanW — CHANGES_REQUESTED** [review]

**Comment by hanhanW** [comment]
@Ranvirsv overall looks good to me, can you run clang-format tool, or fix it manually?

The link shows the expected format: https://github.com/openxla/iree/actions/runs/5336398359/jobs/9672427826?pr=13808

**Comment by Ranvirsv** [comment]
> https://github.com/openxla/iree/actions/runs/5336398359/jobs/9672427826?pr=13808

I have ran the clang-format, but it does not seem to change anything

**Comment by hanhanW** [comment]
> > https://github.com/openxla/iree/actions/runs/5336398359/jobs/9672427826?pr=13808
> 
> I have ran the clang-format, but it does not seem to change anything

There are couple options of style in clang-format, please use one that IREE is using, or check the link about mismatch. IREE uses Google style and is switching to LLVM style, FYI. https://github.com/openxla/iree/blob/main/.clang-format

**Comment by Ranvirsv** [comment]
> > > https://github.com/openxla/iree/actions/runs/5336398359/jobs/9672427826?pr=13808
> > 
> > 
> > I have ran the clang-format, but it does not seem to change anything
> 
> There are couple options of style in clang-format, please use one that IREE is using, or check the link about mismatch. IREE uses Google style and is switching to LLVM style, FYI. https://github.com/openxla/iree/blob/main/.clang-format

I tried using `git clang-format --style=google HEAD~1`
Still get not files to change

**Comment by Ranvirsv** [comment]
Tried fixing individually, hopefully got resolved

**Comment by hanhanW** [comment]
> I tried using git clang-format --style=google HEAD~1

It only formats the diff between current and previous commits. What you want is to format the diff between current and the base. That's why you see nothing changed after formatting.

**Review by hanhanW — APPROVED** [review]

**Comment by bjacob** [comment]
This fixes #14187.  (Meaning, this PR rebased this on current `main` branch. Rebasing was trivial.)
