### PR TITLE
[Codegen] Allow folding collapse shape into partial store

### LINKED ISSUE #20390: Failed to codegen one of llama3 dispatches in padding approach
To repro:  `iree-opt -pass-pipeline="builtin.module(hal.executable(hal.executable.variant(builtin.module(iree-codegen-llvmgpu-configuration-pipeline), iree-codegen-linalg-to-rocdl-pipeline)))" ~/repro.mlir`

```mlir
#encoding = #iree_encoding.encoding<operand_index = 1 : index, op_type =  matmul, element_types = [f16, f16, f32], layouts = [#iree_encoding.pad_encoding_layout<[0, 64]>]>
#encoding1 = #iree_encoding.encoding<operand_index = 0 : index, op_type =  matmul, element_types = [f16, f16, f32], layouts = [#iree_encoding.pad_encoding_layout<[0, 64]>]>
#executable_target_rocm_hsaco_fb = #hal.executable.target<"rocm", "rocm-hsaco-fb", {abi = "hip", iree.encoding.resolver = #iree_gpu.gpu_pad_layout<cache_line_bytes = 128, cache_sets = 4>, iree.gpu.target = #iree_gpu.target<arch = "gfx942", features = "", wgp = <compute =  fp64|fp32|fp16|int64|int32|int16|int8, storage =  b64|b32|b16|b8, subgroup =  shuffle|arithmetic, dot =  dp4xi8toi32, mma = [<MFMA_F32_16x16x4_F32>, <MFMA_F32_16x16x16_F16>, <MFMA_F32_32x32x8_F16>, <MFMA_F64_16x16x4_F64>, <MFMA_F32_16x16x16_BF16>, <MFMA_F32_32x32x8_BF16>, <MFMA_F32_16x16x32_F8E5M2FNUZ>, <MFMA_F32_16x16x32_F8E5M2FNUZ_F8E4M3FNUZ>, <MFMA_F32_16x16x32_F8E4M3FNUZ>, <MFMA_F32_16x16x32_F8E4M3FNUZ_F8E5M2FNUZ>, <MFMA_F32_32x32x16_F8E5M2FNUZ>, <MFMA_F32_32x32x16_F8E5M2FNUZ_F8E4M3FNUZ>, <MFMA_F32_32x32x16_F8E4M3FNUZ>, <MFMA_F32_32x32x16_F8E4M3FNUZ_F8E5M2FNUZ>, <MFMA_I32_16x16x32_I8>, <MFMA_I32_32x32x16_I8>], subgroup_size_choices = [64], max_workgroup_sizes = [1024, 1024, 1024], max_thread_count_per_workgroup = 1024, max_workgroup_memory_bytes = 65536, max_workgroup_counts = [2147483647, 2147483647, 2147483647], max_load_instruction_bits = 128, simds_per_wgp = 4, vgpr_space_bits = 16384>>, ukernels = "none"}>
#map = affine_map<(d0, d1, d2) -> (d0, d2)>
#map1 = affine_map<(d0, d1, d2) -> (d1, d2)>
#map2 = affine_map<(d0, d1, d2) -> (d0, d1)>
#map3 = affine_map<(d0, d1) -> (d0, d1)>
#pipeline_layout = #hal.pipeline.layout<constants = 9, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>
#encoding2 = #iree_encoding.encoding<operand_index = 0 : index, op_type =  matmul, element_types = [f16, f16, f32], user_indexing_maps = [#map, #map1, #map2]>
#encoding3 = #iree_encoding.encoding<operand_index = 1 : index, op_type =  matmul, element_types = [f16, f16, f32], user_indexing_maps = [#map, #map1, #map2]>
#encoding4 = #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [f16, f16, f32], user_indexing_maps = [#map, #map1, #map2]>
hal.executable public @prefill_bs4$async_dispatch_16 {
  hal.executable.variant public @rocm_hsaco_fb target(#executable_target_rocm_hsaco_fb) {
    hal.executable.export public @prefill_bs4$async_dispatch_16_matmul_like_Dx14336x4096_f16xf16xf32 ordinal(0) layout(#pipeline_layout) {
    ^bb0(%arg0: !hal.device, %arg1: index, %arg2: index):
      %x, %y, %z = flow.dispatch.workgroup_count_from_slice %arg1, %arg2
      hal.return %x, %y, %z : index, index, index
    }
    builtin.module {
      func.func @prefill_bs4$async_dispatch_16_matmul_like_Dx14336x4096_f16xf16xf32() {
        %c32_i64 = arith.constant 32 : i64
        %cst = arith.constant 0.000000e+00 : f32
        %cst_0 = arith.constant 1.000000e+00 : f16
        %0 = hal.interface.constant.load layout(#pipeline_layout) ordinal(0) : i32
        %1 = hal.interface.constant.load layout(#pipeline_layout) ordinal(1) : i32
        %2 = hal.interface.constant.load layout(#pipeline_layout) ordinal(2) : i32
        %3 = hal.interface.constant.load layout(#pipeline_layout) ordinal(3) : i32
        %4 = hal.interface.constant.load layout(#pipeline_layout) ordinal(4) : i32
        %5 = hal.interface.constant.load layout(#pipeline_layout) ordinal(5) : i32
        %6 = hal.interface.constant.load layout(#pipeline_layout) ordinal(6) : i32
        %7 = hal.interface.constant.load layout(#pipeline_layout) ordinal(7) : i32
        %8 = hal.interface.constant.load layout(#pipeline_layout) ordinal(8) : i32
        %9 = arith.extui %0 : i32 to i64
        %10 = arith.extui %1 : i32 to i64
        %11 = arith.shli %10, %c32_i64 : i64
        %12 = arith.ori %9, %11 : i64
        %13 = arith.index_castui %12 : i64 to index
        %14 = arith.extui %2 : i32 to i64
        %15 = arith.extui %3 : i32 to i64
        %16 = arith.shli %15, %c32_i64 : i64
        %17 = arith.ori %14, %16 : i64
        %18 = arith.index_castui %17 : i64 to index
        %19 = arith.extui %4 : i32 to i64
        %20 = arith.extui %5 : i32 to i64
        %21 = arith.shli %20, %c32_i64 : i64
        %22 = arith.ori %19, %21 : i64
        %23 = arith.index_castui %22 {stream.alignment = 262144 : index, stream.values = [204472320 : index, 646184960 : index, 1087897600 : index, 1529610240 : index, 1971322880 : index, 2413035520 : index, 2854748160 : index, 3296460800 : index, 3738173440 : index, 4179886080 : index, 4621598720 : index, 5063311360 : index, 5505024000 : index, 5946736640 : index, 6388449280 : index, 6830161920 : index, 7271874560 : index, 7713587200 : index, 8155299840 : index, 8597012480 : index, 9038725120 : index, 9480437760 : index, 9922150400 : index, 10363863040 : index, 10805575680 : index, 11247288320 : index, 11689000960 : index, 12130713600 : index, 12572426240 : index, 13014138880 : index, 13455851520 : index, 13897564160 : index]} : i64 to index
        %24 = arith.extui %6 : i32 to i64
        %25 = arith.extui %7 : i32 to i64
        %26 = arith.shli %25, %c32_i64 : i64
        %27 = arith.ori %24, %26 : i64
        %28 = arith.index_castui %27 : i64 to index
        %29 = arith.index_castui %8 : i32 to index
        %30 = arith.index_castui %8 : i32 to index
        %31:6 = util.assume.int 
            %13<umin = 3145728, umax = 12881756160>, 
            %18<umin = 7372928, umax = 4425017688064>, 
            %23[<umin = 204472320, umax = 204472320, udiv = 204472320>, <umin = 646184960, umax = 646184960, udiv = 646184960>, <umin = 1087897600, umax = 1087897600, udiv = 1087897600>, <umin = 1529610240, umax = 1529610240, udiv = 1529610240>, <umin = 1971322880, umax = 1971322880, udiv = 1971322880>, <umin = 2413035520, umax = 2413035520, udiv = 2413035520>, <umin = 2854748160, umax = 2854748160, udiv = 2854748160>, <umin = 3296460800, umax = 3296460800, udiv = 3296460800>, <umin = 3738173440, umax = 3738173440, udiv = 3738173440>, <umin = 4179886080, umax = 4179886080, udiv = 4179886080>, <umin = 4621598720, umax = 4621598720, udiv = 4621598720>, <umin = 5063311360, umax = 5063311360, udiv = 5063311360>, <umin = 5505024000, umax = 5505024000, udiv = 5505024000>, <umin = 5946736640, umax = 5946736640, udiv = 5946736640>, <umin = 6388449280, umax = 6388449280, udiv = 6388449280>, <umin = 6830161920, umax = 6830161920, udiv = 6830161920>, <umin = 7271874560, umax = 7271874560, udiv = 7271874560>, <umin = 7713587200, umax = 7713587200, udiv = 7713587200>, <umin = 8155299840, umax = 8155299840, udiv = 8155299840>, <umin = 8597012480, umax = 8597012480, udiv = 8597012480>, <umin = 9038725120, umax = 9038725120, udiv = 9038725120>, <umin = 9480437760, umax = 9480437760, udiv = 9480437760>, <umin = 9922150400, umax = 9922150400, udiv = 9922150400>, <umin = 10363863040, umax = 10363863040, udiv = 10363863040>, <umin = 10805575680, umax = 10805575680, udiv = 10805575680>, <umin = 11247288320, umax = 11247288320, udiv = 11247288320>, <umin = 11689000960, umax = 11689000960, udiv = 11689000960>, <umin = 12130713600, umax = 12130713600, udiv = 12130713600>, <umin = 12572426240, umax = 12572426240, udiv = 12572426240>, <umin = 13014138880, umax = 13014138880, udiv = 13014138880>, <umin = 13455851520, umax = 13455851520, udiv = 13455851520>, <umin = 13897564160, umax = 13897564160, udiv = 13897564160>], 
            %28<umin = 14712960, umax = 4455075119104>, 
            %29<umin = 128, umax = 524160, udiv = 128>, 
            %30<umin = 128, umax = 524160, udiv = 128>
          : index, index, index, index, index, index
        %32 = hal.interface.binding.subspan layout(#pipeline_layout) binding(1) alignment(64) offset(%31#2) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<14336x4096xf16, #encoding>>
        %33 = flow.dispatch.workload.ordinal %31#4, 0 : index
        %34 = flow.dispatch.workload.ordinal %31#5, 1 : index
        %35 = hal.interface.binding.subspan layout(#pipeline_layout) binding(0) alignment(64) offset(%31#0) flags("ReadOnly|Indirect") : !flow.dispatch.tensor<readonly:tensor<?x4096xf16, #encoding1>>{%33}
        %36 = hal.interface.binding.subspan layout(#pipeline_layout) binding(0) alignment(64) offset(%31#1) flags("ReadOnly|Indirect") : !flow.dispatch.tensor<readonly:tensor<?x14336xf32>>{%34}
        %37 = hal.interface.binding.subspan layout(#pipeline_layout) binding(2) alignment(64) offset(%31#3) flags(Indirect) : !flow.dispatch.tensor<writeonly:tensor<?x14336xf16, #encoding1>>{%33}
        %38 = flow.dispatch.tensor.load %35, offsets = [0, 0], sizes = [%33, 4096], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<?x4096xf16, #encoding1>>{%33} -> tensor<?x4096xf16, #encoding2>
        %39 = flow.dispatch.tensor.load %32, offsets = [0, 0], sizes = [14336, 4096], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<14336x4096xf16, #encoding>> -> tensor<14336x4096xf16, #encoding3>
        %40 = flow.dispatch.tensor.load %36, offsets = [0, 0], sizes = [%34, 14336], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<?x14336xf32>>{%34} -> tensor<?x14336xf32>
        %41 = tensor.empty(%33) : tensor<?x14336xf16>
        %42 = tensor.empty(%34) : tensor<?x14336xf32, #encoding4>
        %43 = linalg.fill ins(%cst : f32) outs(%42 : tensor<?x14336xf32, #encoding4>) -> tensor<?x14336xf32, #encoding4>
        %44 = linalg.generic {indexing_maps = [#map, #map1, #map2], iterator_types = ["parallel", "parallel", "reduction"]} ins(%38, %39 : tensor<?x4096xf16, #encoding2>, tensor<14336x4096xf16, #encoding3>) outs(%43 : tensor<?x14336xf32, #encoding4>) {
        ^bb0(%in: f16, %in_1: f16, %out: f32):
          %48 = arith.extf %in : f16 to f32
          %49 = arith.extf %in_1 : f16 to f32
          %50 = arith.mulf %48, %49 : f32
          %51 = arith.addf %out, %50 : f32
          linalg.yield %51 : f32
        } -> tensor<?x14336xf32, #encoding4>
        %45 = iree_encoding.unset_encoding %44 : tensor<?x14336xf32, #encoding4> -> tensor<?x14336xf32>{%34}
        %46 = linalg.generic {indexing_maps = [#map3, #map3, #map3], iterator_types = ["parallel", "parallel"]} ins(%45, %40 : tensor<?x14336xf32>, tensor<?x14336xf32>) outs(%41 : tensor<?x14336xf16>) {
        ^bb0(%in: f32, %in_1: f32, %out: f16):
          %48 = arith.truncf %in_1 : f32 to f16
          %49 = arith.truncf %in : f32 to f16
          %50 = arith.negf %49 : f16
          %51 = math.exp %50 : f16
          %52 = arith.addf %51, %cst_0 : f16
          %53 = arith.divf %cst_0, %52 : f16
          %54 = arith.mulf %53, %49 : f16
          %55 = arith.mulf %54, %48 : f16
          linalg.yield %55 : f16
        } -> tensor<?x14336xf16>
        %47 = iree_encoding.set_encoding %46 : tensor<?x14336xf16> -> tensor<?x14336xf16, #encoding2>
        flow.dispatch.tensor.store %47, %37, offsets = [0, 0], sizes = [%33, 14336], strides = [1, 1] : tensor<?x14336xf16, #encoding2> -> !flow.dispatch.tensor<writeonly:tensor<?x14336xf16, #encoding1>>{%33}
        return
      }
    }
  }
}
```

Error:

```
...error: 'memref.copy' op write affecting operations on global resources are restricted to workgroup distributed contexts
flow.dispatch.tensor.store %47, %37, offsets = [0, 0], sizes = [%33, 14336], strides = [1, 1] : tensor<?x14336xf16, #encoding2> -> !flow.dispatch.tensor<writeonly:tensor<?x14336xf16, #encoding1>>{%33}
...error: 'func.func' op failed on workgroup distribution verification
```

### PR DESCRIPTION
**Pull request by kuhar**
... as long as the store is partial only along the non-collapsed dimensions.

This is to allow pad encoding propagation, which introdues partial stores.

Fixes: https://github.com/iree-org/iree/issues/20390

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/Transforms/Transforms.cpp [hunk 1]
```diff
@@ -842,33 +873,64 @@ struct FoldExpandShapeIntoInterfaceTensorStore
...
+      if (reassocIndices.size() > 1) {
+        collapsedDstDims.push_back(index);
+      }
+    }
+
+    // Make sure we are storing the full incoming subspan slice along the
+    // collapsed indices. Otherwise we cannot simply adjust the subspan's
+    // resultant type later.
+    const SmallVector<OpFoldResult, 4> origOffsets = storeOp.getMixedOffsets();
+    const SmallVector<OpFoldResult, 4> origSizes = storeOp.getMixedSizes();
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Transforms/Transforms.cpp:920]: nit: drop `, 4`. I think you are following how they define the interface method here, but the upstream needs to be updated IMO. They essentially call [getMixedValues](https://github.com/llvm/llvm-project/blob/5e2860a8d375ded2d2912894e380fefc8cb1f23a/mlir/include/mlir/Dialect/Utils/StaticValueUtils.h#L147) which uses `SmallVector<OpFoldResult>`.

```cpp
/// Return a vector of OpFoldResults with the same size a staticValues, but
/// all elements for which ShapedType::isDynamic is true, will be replaced by
/// dynamicValues.
SmallVector<OpFoldResult> getMixedValues(ArrayRef<int64_t> staticValues,
                                         ValueRange dynamicValues,
                                         MLIRContext *context);
SmallVector<OpFoldResult> getMixedValues(ArrayRef<int64_t> staticValues,
                                         ValueRange dynamicValues, Builder &b);
```

E.g., 

```td
    InterfaceMethod<
      /*desc=*/[{
        Return a vector of all the static or dynamic sizes of the op.
      }],
      /*retTy=*/"::llvm::SmallVector<::mlir::OpFoldResult, 4>",
      /*methodName=*/"getMixedSizes",
      /*args=*/(ins),
      /*methodBody=*/"",
      /*defaultImplementation=*/[{
        Builder b($_op->getContext());
        return
            ::mlir::getMixedValues($_op.getStaticSizes(), $_op.getSizes(), b);
      }]
    >,
```

https://github.com/llvm/llvm-project/blame/5e2860a8d375ded2d2912894e380fefc8cb1f23a/mlir/include/mlir/Interfaces/ViewLikeInterface.td#L173-L186

File: compiler/src/iree/compiler/Codegen/Transforms/Transforms.cpp [hunk 2]
```diff
@@ -842,33 +873,64 @@ struct FoldExpandShapeIntoInterfaceTensorStore
...
+    const SmallVector<OpFoldResult> mixedTensorShape = getMixedValues(
+        storeOp.getTargetType().getShape(), storeOp.getTargetDims(), rewriter);
+
+    for (int64_t collapsedDim : collapsedDstDims) {
+      if (origSizes[collapsedDim] != mixedTensorShape[collapsedDim] ||
+          !isConstantIntValue(origOffsets[collapsedDim], 0)) {
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Transforms/Transforms.cpp]: The offsets/sizes/strides have index type. We can use [isZeroIndex](https://github.com/llvm/llvm-project/blob/5e2860a8d375ded2d2912894e380fefc8cb1f23a/mlir/include/mlir/Dialect/Utils/StaticValueUtils.h#L27-L29) here.

File: compiler/src/iree/compiler/Codegen/Common/test/propagate_reshapes_by_expansion.mlir [hunk 3]
```diff
@@ -90,6 +90,91 @@ func.func @fold_collapse_into_stores_dynamic(%arg0 : tensor<2x?x32xf32>) {
...
+
+#pipeline_layout = #hal.pipeline.layout<constants = 1, bindings = [
+    #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>
+func.func @fold_collapse_into_stores_dynamic_partial_unsupported(%arg0 : tensor<2x?x32xf32>) {
+  %c0 = arith.constant 0 : index
+  %0 = hal.interface.constant.load layout(#pipeline_layout) ordinal(0) : index
+  %1 = hal.interface.binding.subspan layout(#pipeline_layout) binding(0) alignment(64) offset(%c0)
+      flags("ReadOnly|Indirect") : !flow.dispatch.tensor<writeonly:tensor<?x32xf32>>{%0}
+  %2 = tensor.collapse_shape %arg0 [[0, 1], [2]] : tensor<2x?x32xf32> into tensor<?x32xf32>
+  flow.dispatch.tensor.store %2, %1, offsets = [8, 0], sizes = [%0, 32], strides = [1, 1]
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/test/propagate_reshapes_by_expansion.mlir:149]: Is the offset value valid? If `%0` indicates the size of dimension 0, then it looks like an out-of-bound access to me?

File: compiler/src/iree/compiler/Codegen/Transforms/Transforms.cpp [hunk 4]
```diff
@@ -842,33 +873,64 @@ struct FoldExpandShapeIntoInterfaceTensorStore
 ///       tensor<3x?x?x96xf32> ->
 ///       !flow.dispatch.tensor<writeonly:tensor<3x?x?x96xf32>>{%d0, %d1}
 ///
-/// TODO: This handles full slices. The pattern below
-/// (`FoldCollapseShapeIntoTensorInsertSlice`) handles cases where the slic is
+/// TODO: This handles full slices (along collapsed dims). The pattern below
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Transforms/Transforms.cpp:876]: We only check the strides. Are we missing the check for offsets? I left a comment in lit tests, and I wonder if that is intended.

File: compiler/src/iree/compiler/Codegen/Transforms/Transforms.cpp (hunk 1 above)
Comment (kuhar) [reply compiler/src/iree/compiler/Codegen/Transforms/Transforms.cpp:920]: I tried to match the return value of these `.getMixed*` functions. Another thing that may work to account for these small sizes would be to rely on CTAD and do `SmallVector foo = x.bar();`, but that omits the element type.

Comment (kuhar) [reply compiler/src/iree/compiler/Codegen/Transforms/Transforms.cpp:920]: I fill keep this as-is for now and update the upstream.

File: compiler/src/iree/compiler/Codegen/Common/test/propagate_reshapes_by_expansion.mlir (hunk 3 above)
Comment (kuhar) [reply compiler/src/iree/compiler/Codegen/Common/test/propagate_reshapes_by_expansion.mlir:149]: The store is only valid for some values of `%0` and some sizes of the input tensor. We don't know that `%0` matches the dynamic dimension of the input tensor `%arg0`. From the perspective of static verification, the IR should be valid.

File: compiler/src/iree/compiler/Codegen/Transforms/Transforms.cpp (hunk 4 above)
Comment (kuhar) [reply compiler/src/iree/compiler/Codegen/Transforms/Transforms.cpp:876]: We check both to make sure it's a full slice along the non-collapsed dimensions. The criteria for 'full slice' is to have a matching size and offset = 0. Or am I missing something more?

Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Transforms/Transforms.cpp:876]: Sorry, you are right on this! I over-indexed on the lit test example and I missed that I reviewed the snippet below. 🤦

File: compiler/src/iree/compiler/Codegen/Common/test/propagate_reshapes_by_expansion.mlir (hunk 3 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/Common/test/propagate_reshapes_by_expansion.mlir:149]: The test makes sense to me now. I thought that the `arg0` was loaded from some bindings. It turns out that it is passed as a function argument.

**Review by hanhanW — APPROVED** [review]
