### PR TITLE
[LLVMGPU] Pad to intrinsic shape in LLVMGPUPadAndVectorDistribute pipeline

### LINKED ISSUE #18602: [gpu]: error: Vector shape: [1, 8, 24] does not match the layout
### What happened?

For the given IR

```
module {
  func.func @torch_jit( %arg1: !torch.vtensor<[196,16,24],f32>, %arg2: !torch.vtensor<[24,24],f32>) -> !torch.vtensor<[196,16,24],f32>   attributes {torch.onnx_meta.ir_version = 7 : si64, torch.onnx_meta.opset_version = 21 : si64, torch.onnx_meta.producer_name = "pytorch", torch.onnx_meta.producer_version = "1.12.1"} {
    %1 = torch.operator "onnx.MatMul"(%arg1, %arg2) : (!torch.vtensor<[196,16,24],f32>, !torch.vtensor<[24,24],f32>) -> !torch.vtensor<[196,16,24],f32> 
    return %1 : !torch.vtensor<[196,16,24],f32>
  }
}
```

getting error as

```
issue3/model.torch_onnx.mlir:3:10: error: Vector shape: [1, 8, 24] does not match the layout (nested_layout<subgroup_tile = [1, 1, 1], batch_tile = [1, 2, 1], outer_tile = [1, 1, 1], thread_tile = [1, 4, 16], element_tile = [1, 1, 1], subgroup_strides = [0, 0, 0], thread_strides = [0, 16, 1]>) at dim 2. Dimension expected by layout: 16 actual: 24
    %1 = torch.operator "onnx.MatMul"(%arg1, %arg2) : (!torch.vtensor<[196,16,24],f32>, !torch.vtensor<[24,24],f32>) -> !torch.vtensor<[196,16,24],f32> 
         ^
```

dump.log with '--mlir-print-ir-after-all --mlir-print-ir-before-all --mlir-disable-threading --mlir-elide-elementsattrs-if-larger=4'

[dump.log](https://github.com/user-attachments/files/17144701/dump.log)

### this issue is present only in GPU. the same model passing inference in CPU

command to reproduce:

```
iree-compile --iree-input-type=auto --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=rocm --mlir-print-debuginfo --iree-hip-target=gfx942 model.mlir 
```

### What component(s) does this issue relate to?

_No response_

### Version information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Groverkss**
This patch makes LLVMGPUPromoteToFitMMA pass pad to a multiple of intrinsic shape, instead of padding to 1.

Fixes https://github.com/iree-org/iree/issues/18602

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp [hunk 1]
```diff
@@ -36,23 +36,14 @@ class LLVMGPUPromoteMatmulToFitMMAPass final
   }
 
   void padWithZeroValue(RewriterBase &rewriter, linalg::LinalgOp op,
-                        utils::IteratorType targetIterType, bool nofold) const {
+                        ArrayRef<int64_t> paddingDims,
+                        ArrayRef<int64_t> padToMultipleOf, bool nofold) const {
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]: While we are at this, `noFold`?

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp [hunk 2]
```diff
@@ -78,6 +69,12 @@ class LLVMGPUPromoteMatmulToFitMMAPass final
     MLIRContext *ctx = &getContext();
     auto funcOp = getOperation();
 
+    llvm::StringLiteral scheduleAttrName =
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]: nit: I think we also have a using declaration for this type in `mlir::`
```suggestion
    StringLiteral scheduleAttrName =
```

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp [hunk 3]
```diff
@@ -107,7 +104,40 @@ class LLVMGPUPromoteMatmulToFitMMAPass final
 
     IRRewriter rewriter(ctx);
     for (auto op : candidates) {
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]:
```suggestion
    for (linalg::LinalgOp op : candidates) {
```

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp [hunk 4]
```diff
@@ -107,7 +104,40 @@ class LLVMGPUPromoteMatmulToFitMMAPass final
...
+      }
+
+      // Populate tile sizes. All tile sizes are one, except mma tile sizes.
+      SmallVector<int64_t> padToMultipleOf(paddingDimensions.size(), 1);
+      if (scheduleAttr) {
+        auto [padM, padN, padK] = scheduleAttr.getIntrinsic().getMNKShape();
+        padM *= scheduleAttr.getSubgroupMCount();
+        padN *= scheduleAttr.getSubgroupNCount();
+        for (auto [dim, multiple] :
+             llvm::zip(paddingDimensions, padToMultipleOf)) {
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]: zip_equal?

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp [hunk 5]
```diff
@@ -107,7 +104,40 @@ class LLVMGPUPromoteMatmulToFitMMAPass final
...
+          if (dim == dims->m.back()) {
+            multiple = padM;
+          }
+          if (dim == dims->n.back()) {
+            multiple = padN;
+          }
+          if (dim == dims->k.back()) {
+            multiple = padK;
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]: Make continuation explicit here?

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp [hunk 6]
```diff
@@ -107,7 +104,40 @@ class LLVMGPUPromoteMatmulToFitMMAPass final
...
+
+      // Populate padding dimensions.
+      SmallVector<int64_t> paddingDimensions;
+      for (auto [idx, iter] : llvm::enumerate(op.getIteratorTypesArray())) {
+        if (iter == targetIterType) {
+          paddingDimensions.push_back(idx);
+        }
+      }
+
+      // Populate tile sizes. All tile sizes are one, except mma tile sizes.
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]: Can you comment on what the desired padding is here? IE it's clear that only mma tile sizes are non-one, but  I think it would be more informative to say what the intention/end-state is.

If I'm reading this right, you want to pad to the multiple of the workgroup-level tile?

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir [hunk 7]
```diff
@@ -484,6 +484,63 @@ hal.executable.variant @rocm target(<"rocm", "rocm-hsaco-fb">) {
...
+    }
+  }
+}
+
+// CHECK-LABEL: @pad_batch_matmul
+// CHECK: scf.for
+// LHS
+// CHECK: vector.transfer_read
+// CHECK-SAME: in_bounds = [true, true, true]
+// CHECK-SAME: memref<196x16x24xf32
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir]: missing >

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir [hunk 8]
```diff
@@ -484,6 +484,63 @@ hal.executable.variant @rocm target(<"rocm", "rocm-hsaco-fb">) {
...
+// CHECK-SAME: vector<1x1x1xf32>
+// RHS
+// CHECK: vector.transfer_read
+// CHECK-SAME: in_bounds = [true, true, false]
+// CHECK-SAME: memref<1x8x24xf32
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir]: missing >

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir [hunk 9]
```diff
@@ -484,6 +484,63 @@ hal.executable.variant @rocm target(<"rocm", "rocm-hsaco-fb">) {
...
+// CHECK-SAME: vector<1x1x2xf32>
+// CHECK: scf.yield
+// CHECK: vector.transfer_write
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir]: These checks are far detached from the source and, at the same time, we don't anchor on the values for lhs/rhs/yield. This seems a bit brittle to me. Could we anchor on ssa names without too much extra check code?

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir [hunk 10]
```diff
@@ -484,6 +484,63 @@ hal.executable.variant @rocm target(<"rocm", "rocm-hsaco-fb">) {
...
+// The last dimension of output needs to be padded to intrinsic shape
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir]: I don't see how this is being checked.

**Review by kuhar — COMMENTED** [review]
I don't understand the batch matmul test

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp (hunk 6 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]: Fixed. It should have been padded to multiples of workgroup/reduction.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir (hunk 7 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir]: That's intentional to not write out the memory space.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir (hunk 8 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir]: Intentional to not write out the memory space

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir (hunk 10 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir]: We are checking if the codegen produces in_bounds=false for the last dimension, which means it is being padded out.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp [hunk 11]
```diff
@@ -78,6 +69,12 @@ class LLVMGPUPromoteMatmulToFitMMAPass final
     MLIRContext *ctx = &getContext();
     auto funcOp = getOperation();
 
+    llvm::StringLiteral scheduleAttrName =
+        IREE::GPU::MMAScheduleAttr::getMnemonic();
+    DictionaryAttr configDict = getTranslationInfo(funcOp).getConfiguration();
+    auto scheduleAttr = dyn_cast_or_null<IREE::GPU::MMAScheduleAttr>(
+        configDict.get(scheduleAttrName));
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]: I think we can move it to where it is used (i.e., line 121). And we can do something like:

```
if (auto scheduleAttr = ...
```

**Review by hanhanW — CHANGES_REQUESTED** [review]
Can you add a test to https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMGPU/test/promote_matmul_to_fit_mma.mlir ?

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir (hunk 9 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir]: It's really hard to add better tests for this... The test is mostly to check if we can get an unaligned linalg.batch_matmul through the entire pipeline.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp (hunk 11 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]: changed the logic

**Comment by Groverkss** [comment]
> Can you add a test to https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMGPU/test/promote_matmul_to_fit_mma.mlir ?

I modified the first test to use lowering_config to decide tile sizes multiples.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp [hunk 12]
```diff
@@ -106,8 +97,48 @@ class LLVMGPUPromoteMatmulToFitMMAPass final
...
-      padWithZeroValue(rewriter, op, targetIterType, nofold);
+    for (linalg::LinalgOp op : candidates) {
+      SmallVector<int64_t> padMultiples(op.getNumLoops(), 1);
+      auto config = dyn_cast_or_null<IREE::GPU::LoweringConfigAttr>(
+          getLoweringConfig(op));
+      if (config) {
+        switch (targetDimensions) {
+        case LLVMGPUMatmulPadOption::ParallelDims:
+          padMultiples = config.getStaticTilingLevelSizes(
+              (unsigned)IREE::GPU::TilingLevel::Workgroup, op);
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]: nit: avoid the c-style cast. You can either use `llvm::to_underlying()` or `static_cast<unsigned>` in this case.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp [hunk 13]
```diff
@@ -106,8 +97,48 @@ class LLVMGPUPromoteMatmulToFitMMAPass final
...
+          break;
+        case LLVMGPUMatmulPadOption::ReductionDims:
+          padMultiples = config.getStaticTilingLevelSizes(
+              (unsigned)IREE::GPU::TilingLevel::Reduction, op);
+          break;
+        default:
+          llvm_unreachable("Unexpected target dimensions");
+          break;
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]: nit: we are avoiding llvm_unreachable in this case because it could potentially lead to UB. See https://github.com/iree-org/iree/pull/8521 for more details

```suggestion
          assert(false && "Unexpected target dimensions");
          break;
```

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir (hunk 9 above)
Comment (kuhar) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir]: Could you expand the comment on top with this line of explanation?

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp [hunk 14]
```diff
@@ -106,8 +97,48 @@ class LLVMGPUPromoteMatmulToFitMMAPass final
...
+          paddingDimensions.push_back(idx);
+        }
+      }
+
+      // Populate tile sizes. We pad to multiples of workgroup/reduction
+      // tile sizes based on the selected target tiling dimensions.
+      // This pass is ran after the select target tiling is done to pad
+      // all dimensions to the select tile sizes.
+      SmallVector<int64_t> padToMultipleOf;
+      padToMultipleOf.reserve(paddingDimensions.size());
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]: I think we don't need the `reserve` method for most of `SmallVector` usages because it already allocate a ~64 bytes buffer. IMO, it's good for `std::vector`, but it is unnecessary for `SmallVector`.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp [hunk 15]
```diff
@@ -106,8 +97,48 @@ class LLVMGPUPromoteMatmulToFitMMAPass final
...
+      for (int64_t dim : paddingDimensions) {
+        if (padMultiples[dim] != 0) {
+          padToMultipleOf.push_back(padMultiples[dim]);
+        }
+      }
+
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp:141]: I think it is better to put an assertion here, which makes sure that the size of `padMultiples` equals to the size of `paddingDimensions`.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/promote_matmul_to_fit_mma.mlir [hunk 16]
```diff
@@ -77,7 +79,8 @@ func.func @batch_matmul_f16() {
 #map4 = affine_map<()[s0] -> (-s0 + 64)>
 #map5 = affine_map<()[s0] -> (-s0 + 128)>
 #map6 = affine_map<(d0) -> (-d0 + 1281, 64)>
-func.func @batch_matmul_pad_reduction_after_tiling() {
+#translation = #iree_codegen.translation_info<None, {mma_schedule = #iree_gpu.mma_schedule<intrinsic = #iree_gpu.mma_layout<MFMA_F32_16x16x16_F16>, subgroup_m_count = 1, subgroup_n_count = 1>}>
+func.func @batch_matmul_pad_reduction_after_tiling() attributes {translation_info = #translation} {
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/test/promote_matmul_to_fit_mma.mlir]: unneeded changes?

File: compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir [hunk 17]
```diff
@@ -484,6 +484,65 @@ hal.executable.variant @rocm target(<"rocm", "rocm-hsaco-fb">) {
...
+    }
+  }
+}
+
+// CHECK-LABEL: @pad_batch_matmul
+// CHECK: scf.for
+// LHS
+// CHECK: vector.transfer_read
+// CHECK-SAME: in_bounds = [true, true, true]
+// CHECK-SAME: memref<196x16x24xf32
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_vector_distribute_gfx940.mlir]: Can you pad checks with spaces, so the code can start on the same column?

**Comment by MaheshRavishankar** [comment]
cc @nirvedhmeshram

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp (hunk 13 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]: Oh wow, thank you for pointing this out!

Comment (kuhar) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]: At the end of that thread the conclusion is that llvm_unreachable should be fine to use after all? https://github.com/iree-org/iree/pull/8521#issuecomment-1565084742

**Review by hanhanW — APPROVED** [review]

File: compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp (hunk 13 above)
Comment (Groverkss) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUPromoteMatmulToFitMMA.cpp]: interesting. I'm going to just use assert(false) for consistency since there was another use of assert(false) before.
