### PR TITLE
[CPU] Make VectorPreProcStrategy consider undefined behaviors

### LINKED ISSUE #18085: `arith.remsi` causes floating point exception on `llvm-cpu`
It appears there is a bug with lowering `arith.remsi` to `x86`. Not entirely certain where in the pipeline this goes wrong but it results in a floating point exception.

Repro IR:

```
module {
  util.func public @test_mod_mixed_sign_int32(%arg0: tensor<6xi32>, %arg1: tensor<6xi32>) -> tensor<6xi32> {
    %2 = tensor.empty() : tensor<6xi32>
    %3 = linalg.generic {indexing_maps = [affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>], iterator_types = ["parallel"]} ins(%arg0, %arg1 : tensor<6xi32>, tensor<6xi32>) outs(%2 : tensor<6xi32>) {
    ^bb0(%in: i32, %in_0: i32, %out: i32):
      %6 = arith.remsi %in, %in_0 : i32
      linalg.yield %6 : i32
    } -> tensor<6xi32>
    util.return %3 : tensor<6xi32>
  }
}
```

Command:
```
iree-compile model.mlir --iree-hal-target-backends=llvm-cpu | iree-run-module --module=- --input=6xi32=1111 --input=6xi32=1111
```

Result
```
EXEC @test_mod_mixed_sign_int32
Floating point exception (core dumped)
```

### PR DESCRIPTION
**Pull request by lialan**
Vectorization pass should not introduce extra undefined behaviors.

In some particular cases, using masking strategy could result in divide-by-zero exception, as the masking strategy by default loads zero values when mask is false.

This patch addresses such issue by falling back to loop peeling, in case extra undefined behaviors could happen using mask strategy.

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 1]
```diff
@@ -219,6 +220,23 @@ getVectorPreProcStrategy(linalg::LinalgOp linalgOp) {
...
+  linalgOp.walk([&](Operation *op) -> WalkResult {
+    if (isa<mlir::arith::RemSIOp, mlir::arith::RemUIOp, mlir::arith::DivSIOp,
+            mlir::arith::DivUIOp, mlir::arith::CeilDivSIOp,
+            mlir::arith::CeilDivUIOp, mlir::arith::FloorDivSIOp,
+            mlir::arith::DivFOp, mlir::arith::RemFOp>(op)) {
+      usePeelingStrategy = true;
+      return WalkResult::interrupt();
+    }
+    return WalkResult::advance();
+  });
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: I think it's better to create a method for it. You can put it to `LLVMCPU/Utils.[h|cpp]`: https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMCPU/Utils.h#L53

Comment (lialan) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: Done.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Utils.h [hunk 2]
```diff
@@ -51,6 +51,9 @@ bool hasI8mmFeature(IREE::HAL::ExecutableTargetAttr targetAttr);
 ///   argument corresponding to the input.
 bool isLinalgGeneric2DTranspose(linalg::GenericOp genericOp);
 
+/// Returns true if the op could result in undefined behavior.
+bool mayHaveUndefinedBehavior(Operation *op);
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/Utils.h]: I think people will miss context because of the naming and comments. Undefined behavior could happen in many places. Perhaps we can rename it to `mayHaveUndefinedBehaviorInMasking`? In this case, people knows that the method is used for vectorization related logics.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 3]
```diff
@@ -219,6 +219,20 @@ getVectorPreProcStrategy(linalg::LinalgOp linalgOp) {
     return VectorPreProcStrategy::None;
   }
 
+  // Walk the linalgOp code, if there is any instruction that could result in
+  // undefined behavior in mask strategy, fall back to using peel strategy.
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:223]: nit: let's be consistent with other comments and variable naming.

```suggestion
  // undefined behavior in masking strategy, fall back to using peeling strategy.
```

File: compiler/src/iree/compiler/Codegen/LLVMCPU/test/peel.mlir [hunk 4]
```diff
@@ -113,3 +113,45 @@ module {
...
+    %extracted_slice_0 = tensor.extract_slice %5[%arg0] [%7] [1] : tensor<6xi32> to tensor<?xi32>
+    %extracted_slice_1 = tensor.extract_slice %arg1[%arg0] [%7] [1] : tensor<6xi32> to tensor<?xi32>
+    %8 = linalg.generic {indexing_maps = [affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>], iterator_types = ["parallel"]} ins(%extracted_slice, %extracted_slice_0 : tensor<?xi32>, tensor<?xi32>) outs(%extracted_slice_1 : tensor<?xi32>) attrs =  {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[6], [4], [0], [0]]>} {
+    ^bb0(%in: i32, %in_2: i32, %out: i32):
+      %9 = arith.remsi %in, %in_2 : i32
+      linalg.yield %9 : i32
+    } -> tensor<?xi32>
+    %inserted_slice = tensor.insert_slice %8 into %arg1[%arg0] [%7] [1] : tensor<?xi32> into tensor<6xi32>
+    scf.yield %inserted_slice : tensor<6xi32>
+  }
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/test/peel.mlir]: Please make the test simpler. Because it could be hard to maintain the test. IMO, we can remove those scf.for loops. Instead, we only have `flow.dispatch.load/store` + `linalg.generic` and perhaps a `tensor.empty` op. E.g., https://github.com/iree-org/iree/blob/4bea50ea31f9de3b48888cf2f44827aae55aff8e/compiler/src/iree/compiler/Codegen/LLVMCPU/test/select_x86_64_lowering_strategy.mlir#L3-L24

File: compiler/src/iree/compiler/Codegen/LLVMCPU/test/peel.mlir [hunk 5]
```diff
@@ -113,3 +113,45 @@ module {
...
+  %4 = flow.dispatch.tensor.load %0, offsets = [0], sizes = [6], strides = [1] : !flow.dispatch.tensor<readonly:tensor<6xi32>> -> tensor<6xi32>
+  %5 = flow.dispatch.tensor.load %1, offsets = [0], sizes = [6], strides = [1] : !flow.dispatch.tensor<readonly:tensor<6xi32>> -> tensor<6xi32>
+  %6 = scf.for %arg0 = %c0 to %c6 step %c4 iter_args(%arg1 = %3) -> (tensor<6xi32>) {
+    %7 = affine.min affine_map<(d0) -> (-d0 + 6, 4)>(%arg0)
+    %extracted_slice = tensor.extract_slice %4[%arg0] [%7] [1] : tensor<6xi32> to tensor<?xi32>
+    %extracted_slice_0 = tensor.extract_slice %5[%arg0] [%7] [1] : tensor<6xi32> to tensor<?xi32>
+    %extracted_slice_1 = tensor.extract_slice %arg1[%arg0] [%7] [1] : tensor<6xi32> to tensor<?xi32>
+    %8 = linalg.generic {indexing_maps = [affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>], iterator_types = ["parallel"]} ins(%extracted_slice, %extracted_slice_0 : tensor<?xi32>, tensor<?xi32>) outs(%extracted_slice_1 : tensor<?xi32>) attrs =  {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[6], [4], [0], [0]]>} {
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/test/peel.mlir]: nit: remove the lowering_config. It should be set by the pass. If the `lowering_config` or `translation_info` present, the convention is treating that they are preset configuration from frontends. In this context, the pass does nothing on the dispatch -- which means that your changes are not tested.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/test/peel.mlir [hunk 6]
```diff
@@ -113,3 +113,45 @@ module {
 // CHECK:             tensor.pack {{.*}} : tensor<16x16xf32> -> tensor<1x16x16x1xf32>
 // CHECK:           scf.for
 // CHECK:             tensor.pack {{.*}} : tensor<16x?xf32> -> tensor<1x?x16x1xf32>
+
+// -----
+
+func.func @test_mod_mixed_sign_int32_dispatch_0_elementwise_6_i32() attributes {translation_info = #iree_codegen.translation_info<CPUDoubleTilingExpert, {enable_loop_peeling}>} {
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/test/peel.mlir]: nit1: remove the `translation_info`, see below for the explanation
nit2: Make function name clearer, perhaps we can rename it to `test_mod_no_masking`.
nit3: Add a comment about what the test checks, and explain why we don't use masking for the case.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/test/peel.mlir [hunk 7]
```diff
@@ -113,3 +113,45 @@ module {
...
+// CHECK: linalg.generic
+// CHECK: %[[RESULT1:.*]] = arith.remsi
+// CHECK-NEXT: linalg.yield %[[RESULT1]]
+// CHECK-NEXT: } -> tensor<4xi32>
+
+// CHECK: linalg.generic
+// CHECK: %[[RESULT2:.*]] = arith.remsi
+// CHECK: linalg.yield %[[RESULT2]]
+// CHECK: } -> tensor<2xi32>
+
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/test/peel.mlir]: nit: remove the trailing blank line.

**Review by hanhanW — CHANGES_REQUESTED** [review]
It looks okay to me. Just few nits about function name and the test.

**Comment by lialan** [comment]
@hanhanW I realized deciding the vectorization strategy is actually before we do `peeling` (in hindsight, of course), so I created a new test file to check the decision making part instead. 

but I feel like we should also test the peeling part (that the computing of residual values are good). Let me know what you think.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/test/peel.mlir (hunk 4 above)
Comment (lialan) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/test/peel.mlir]: I feel like the `scf.for` is what we are testing here? `scf.for` defines strided access to make it possible for vectorizing the inner `linalg.generic` loop. without it there won't be a loop peeling at the end?

**Comment by hanhanW** [comment]
> @hanhanW I realized deciding the vectorization strategy is actually before we do `peeling` (in hindsight, of course), so I created a new test file to check the decision making part instead.

We split the tests based on CPU arch, so there are few `select_*_lowering_strategy.mlir` in https://github.com/iree-org/iree/tree/main/compiler/src/iree/compiler/Codegen/LLVMCPU/test. Here I'd suggest to put the test to `select_x86_64_lowering_strategy.mlir` because the target in the test is x86.

> 
> but I feel like we should also test the peeling part (that the computing of residual values are good). Let me know what you think.

There are few pipeline tests in [pipeline_peel_and_vectorize_tests.mlir](https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMCPU/test/pipeline_peel_and_vectorize_tests.mlir). You can add a test to the file with a preset configuration.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/Utils.h (hunk 2 above)
Comment (lialan) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/Utils.h]: done.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp (hunk 3 above)
Comment (lialan) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:223]: done.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/test/vectorize_linalg_generic.mlir
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/test/vectorize_linalg_generic.mlir:1]: As discussed yesterday, I think we already have enough test coverage about peeling strategy. So this test is not needed. The config test in `select_x86_64_lowering_stratetgy.mlir` should be enough. Let's remove this one.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/test/BUILD.bazel [hunk 8]
```diff
@@ -51,6 +51,7 @@ iree_lit_test_suite(
             "select_aarch64_sme_lowering_strategy.mlir",
             "select_aarch64_sve_lowering_strategy.mlir",
             "select_aarch64_sve_lowering_strategy_peeling.mlir",
+            "select_lowering_strategy_peeling.mlir",
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/test/BUILD.bazel]: nit: remove it. This is the root cause of CI failures.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/test/BUILD.bazel [hunk 9]
```diff
@@ -65,6 +66,7 @@ iree_lit_test_suite(
             "vector_contract_to_arm_intrinsics.mlir",
             "vector_lowering.mlir",
             "vector_transpose_lowering.mlir",
+            "vectorize_linalg_generic.mlir",
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/test/BUILD.bazel]: nit: we don't need it if we remove the file.

**Review by hanhanW — APPROVED** [review]
LGTM, just one nit about testing.

(cc @banach-space )

**Comment by banach-space** [comment]
Hey, avoiding masking like this is a bit counter-intuitive to me TBH:

> In some particular cases, using masking strategy could result in divide-by-zero exception, as the masking strategy by default loads zero values when mask is false.

In general, this would depend on the ISA, right? I've just double-check [DIV for SVE](https://developer.arm.com/documentation/ddi0602/2024-06/SVE-Instructions/SDIV--Signed-divide--predicated--?lang=en) and note that (extra emphasis from me):

> Signed divide **active** elements of the first source vector by corresponding elements of the second source vector

So, masking should be totally safe, no?

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
Comment (ScottTodd) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:1]: This PR appears to have fixed a previously failing test, causing CI to fail: https://github.com/iree-org/iree/actions/runs/10408412024/job/28826260334#step:8:54

```
=================================== FAILURES ===================================
_ IREE compile and run: test_mod_uint64::model.mlir::model.mlir::cpu_llvm_sync _
[gw1] linux -- Python 3.11.9 /home/runner/work/iree/iree/venv/bin/python
[XPASS(strict)] Expected run to fail (included in 'expected_run_failures')
--- generated report log file: /tmp/iree_tests_onnx_cpu_llvm_sync_logs.json ----
```

Please watch CI results before merging - automerge will not block on that job at the moment.

Comment (lialan) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:1]: Oops... Hmm, why is a failing test not blocking auto-merge? So it is generally discouraged to use auto-merge for IREE?

Comment (ScottTodd) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:1]: Our self-hosted GitHub Actions runners are too unreliable at the moment for auto-merge. They flake regularly and I don't want them blocking all commit traffic. Auto-merge will wait for the `linux_x64_clang` and `linux_x64_clang_asan` jobs which build and run unit tests. It is not currently waiting for model tests, GPU tests, ONNX op tests, Android builds, etc. (anything in `pkgci.yml`)

**Comment by lialan** [comment]
> Hey, avoiding masking like this is a bit counter-intuitive to me TBH:
> 
> > In some particular cases, using masking strategy could result in divide-by-zero exception, as the masking strategy by default loads zero values when mask is false.
> 
> In general, this would depend on the ISA, right? I've just double-check [DIV for SVE](https://developer.arm.com/documentation/ddi0602/2024-06/SVE-Instructions/SDIV--Signed-divide--predicated--?lang=en) and note that (extra emphasis from me):
> 
> > Signed divide **active** elements of the first source vector by corresponding elements of the second source vector
> 
> So, masking should be totally safe, no?

Masking it safe for SVE, yes. but generally speaking, in LLVM IR semantics:
```
Division by zero is undefined behavior. For vectors, if any element of the divisor is zero, the operation has undefined behavior.
```
Since we are lowering to LLVM IR so less undefined behavior is better..?

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
Comment (ScottTodd) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:1]: Weird... I saw the same test "failure" (newly passing) on https://github.com/iree-org/iree/actions/runs/10409729467/job/28830476078?pr=18223, which I think was before including this code... I wonder if the test is flaky? It certainly looked related to the code changes here 🤔

**Comment by banach-space** [comment]
> Masking it safe for SVE, yes. 

SVE is just a specific example of an ISA with masking. Similar argument would hold for any ISA with native masking.

> but generally speaking, in LLVM IR semantics:
> 
> ```
> 
> Division by zero is undefined behavior. For vectors, if any element of the divisor is zero, the operation has undefined behavior.
> 
> ```

Isn't the point of masking to make sure that division doesnt't happen?

I might be missing sth here, but I think that it would be good to try to compile your example to assembly to see what happens there (I am AFK, but can try SVE tomorrow). Do you have an example for an ISA without masking?

**Comment by banach-space** [comment]
Below is the main loop for SVE:

```asm
.LBB0_1:
  sub x15, x12, x8
  cmp x15, #4
  csel  x15, x15, x13, lo
  dup v2.2d, x15
  mov w15, w14
  mov w14, wzr
  cmhi  v3.2d, v2.2d, v0.2d
  cmhi  v2.2d, v2.2d, v1.2d
  uzp1  v2.4s, v2.4s, v3.4s
  cmpne p1.s, p0/z, z2.s, #0
  ld1w  { z2.s }, p1/z, [x9, x8, lsl #2]
  ld1w  { z3.s }, p1/z, [x10, x8, lsl #2]
  .loc  1 8 12
  movprfx z4, z2
  sdiv  z4.s, p0/m, z4.s, z3.s
  mls v2.4s, v4.4s, v3.4s
  st1w  { z2.s }, p1, [x11, x8, lsl #2]
  mov w8, #4
  .loc  1 6 10
  tbnz  w15, #0, .LBB0_1
  mov w0, wzr
  .loc  1 6 10 epilogue_begin is_stmt 0
  ldp x29, x30, [sp], #16
  ret
```

As expected, it looks fine. This instruction computes the predicate:
```asm
  cmpne p1.s, p0/z, z2.s, #0
```

Here's the example that I compiled (based on your test):
```mlir
module {
  func.func @test_mod_vectorizing_strategy_peeling(%3 : tensor<6xi32>, %4: tensor<6xi32>) -> tensor<6xi32> {
    %c0 = arith.constant 0 : index
    %5 = tensor.empty() : tensor<6xi32>
    %6 = linalg.generic {indexing_maps = [affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>], iterator_types = ["parallel"]} ins(%3, %4 : tensor<6xi32>, tensor<6xi32>) outs(%5 : tensor<6xi32>) {
    ^bb0(%in: i32, %in_0: i32, %out: i32):
      %7 = arith.remsi %in, %in_0 : i32
      linalg.yield %7 : i32
    } -> tensor<6xi32>
    return %6 : tensor<6xi32>
  }
}
```

Note, upstream IREE doesn't support scalable vectorisation of `linalg.generic` just yet. I am a bit behind with my PRs 😅 (I generated that using my downstream version) 

Anyway, as hinted in my previous messages, this should probably be disabled for ISAs that support masking. WDYT? I can add this to my TODO list and send a PR once my other bits for vectorising `linalg.generic` (for SVE) are ready.

**Comment by hanhanW** [comment]
> Isn't the point of masking to make sure that division doesnt't happen?
> I might be missing sth here, but I think that it would be good to try to compile your example to assembly to see what happens there (I am AFK, but can try SVE tomorrow). Do you have an example for an ISA without masking?

How does it happen in practice? I could have wrong understanding about masking. I think they will eventually be lowered to masked load/store, and produce native_vector_size vectors. The rest of computation ops all take the results to perform the computation. So say that if we have 6 elements and two tiles, the second tile loads `[v_0, v_1, 0, 0]` for LHS and `[v_2, v_3, 0, 0]` for RHS, and the divisor becomes zeros which could lead to UB. The main reason is that the upstream vectorizer always use zeros as padding value.

In Alan's investigation, this is the case at LLVM level:

```ll
  %28 = getelementptr i32, ptr %9, i64 %20, !dbg !81
  %29 = tail call <4 x i32> @llvm.masked.load.v4i32.p0(ptr %28, i32 4, <4 x i1> %25, <4 x i32> zeroinitializer), !dbg !81
  %30 = srem <4 x i32> %27, %29, !dbg !81
```

where vectorization actually loads zero as divider due to mask being zero, and the zeroinitializer.

I don't really remember how SVE codegen config work right now. IIRC, we firstly peel the loop, and apply scalable vectorization on the main loop? If this is the case, I think we're doing the same thing here. The main loop is vectorized without masking on x86 path. The distinction of the IR is that one has scalar vector and the other does not. Correct me if I'm wrong. :)

> Anyway, as hinted in my previous messages, this should probably be disabled for ISAs that support masking. WDYT? I can add this to my TODO list and send a PR once my other bits for vectorising linalg.generic (for SVE) are ready.

Yes, we can disable it if we know the ISAs support the masking. Thanks for offering the help!

**Comment by banach-space** [comment]
Hey @hanhanW 👋🏻 

> How does it happen in practice? 

ISel :-)  (*)

Yes, looking at your LLVM example it's quite apparent that there's potential UB. But then the backend can do it's magic and leverage the ISA to get rid of that and generate the predicated `sdiv` instruction that I shared in my example. IIUC, that happens during ISel. 

> IIRC, we firstly peel the loop, and apply scalable vectorization on the main loop? If this is the case, I think we're doing the same thing here.

Correct :) (well, strictly speaking we don't have scalable vectorization for `linalg.generic` _yet_, but that's a separate matter)

> The main loop is vectorized without masking on x86 path. 

Sure, but then I wonder - shouldn't every iteration in the main loop "consume" exactly vector-width of elements? (where vector-width matches hardware vector-register length) So even without masking, it would be fine? 

(*) I will be OOO for a while, but will double check before sending a PR for SVE.

**Comment by hanhanW** [comment]
> Yes, looking at your LLVM example it's quite apparent that there's potential UB. But then the backend can do it's magic and leverage the ISA to get rid of that and generate the predicated sdiv instruction that I shared in my example. IIUC, that happens during ISel.

Yeah, I'm happy that we are on the same page now. The issue is that we generated potential UB IRs, and then some backends can get rid of UB because they have such support.

I don't find a predicated `sdiv` instruction in x86 ISA, so we end up with disabling the masking strategy. But sure, we can enable it for SVE path if they have the support.

> Sure, but then I wonder - shouldn't every iteration in the main loop "consume" exactly vector-width of elements? (where vector-width matches hardware vector-register length) So even without masking, it would be fine?

Yes, that's right on the x86 path. On the x86 path (or say without scalable vectors), there are two strategies. One is peeling and the other is masking. The operations in the main loop are all vectorized without masking. Because they have static shapes.

Things are a little different on scalable vectorization path. The "masking" strategy that we used on x86 path becomes "peeling first, then do masking on the main loop". I think you will likely hit the same issue if the ISA does not support predicated `sdiv`.
