### PR TITLE
[Codegen][ROCM] Add validation for quantization data types

### LINKED ISSUE #18367: [compile][rocm]: error: 'llvm.fptrunc' op result #0 must be floating point LLVM type or LLVM dialect-compatible vector of floating point LLVM type, but got 'i8'
### What happened?

for the given IR

```mlir
module @module {
  util.global private @"__auto.model.layers.31.self_attn.v_proj.qdq_output:rscale" = #stream.parameter.named<"model"::"model.layers.31.self_attn.v_proj.qdq_output:rscale"> : tensor<f16>
  func.func @prefill_bs2(%arg0: !torch.vtensor<[2,?],si64>, %arg1: !torch.vtensor<[2],si64>, %arg2: !torch.vtensor<[2,?],si64>, %arg3: !torch.tensor<[?,4194304],f16>, %arg4: !torch.vtensor<[?,4096],f16>, %arg5: !torch.vtensor<[4096,32000],f16>, %arg6: !torch.vtensor<[2,?],si64>, %arg7:!torch.vtensor<[?,4194304],f16>, %arg8:!torch.vtensor<[2,?],si64>, %arg9:!torch.vtensor<[2,?,4096],f16>) -> !torch.vtensor<[2,?,4096],f16>  attributes {torch.assume_strict_symbolic_shapes} {
    %__auto.model.layers.31.self_attn.v_proj.qdq_output3Arscale = util.global.load @"__auto.model.layers.31.self_attn.v_proj.qdq_output:rscale" : tensor<f16>
    %944 = torch_c.from_builtin_tensor %__auto.model.layers.31.self_attn.v_proj.qdq_output3Arscale : tensor<f16> -> !torch.vtensor<[],f16>
    %int24_8273 = torch.constant.int 24
    %9307 = torch.prims.convert_element_type %arg9, %int24_8273 : !torch.vtensor<[2,?,4096],f16>, !torch.int -> !torch.vtensor<[2,?,4096],f8E4M3FN>
    %int5_8274 = torch.constant.int 5
    %9308 = torch.prims.convert_element_type %9307, %int5_8274 : !torch.vtensor<[2,?,4096],f8E4M3FN>, !torch.int -> !torch.vtensor<[2,?,4096],f16>
    %9309 = torch.aten.mul.Tensor %9308, %944 : !torch.vtensor<[2,?,4096],f16>, !torch.vtensor<[],f16> -> !torch.vtensor<[2,?,4096],f16>
    return %9309 : !torch.vtensor<[2,?,4096],f16>
  }
}
```

getting error as 

unknown>:0: error: 'llvm.fptrunc' op result #0 must be floating point LLVM type or LLVM dialect-compatible vector of floating point LLVM type, but got 'i8'
<unknown>:0: note: see current operation: %87 = "llvm.fptrunc"(%86) : (f16) -> i8

### Steps to reproduce your issue

command to reproduce:

```
iree-compile --iree-hal-target-backends=rocm --iree-input-demote-i64-to-i32 --iree-hip-target=gfx942 small.mlir
```
[dump.log](https://github.com/user-attachments/files/16758067/dump.log)

dump.log with flag "--mlir-print-ir-after-all --mlir-print-ir-before-all --mlir-disable-threading --mlir-elide-elementsattrs-if-larger=4"

### What component(s) does this issue relate to?

Compiler

### Version information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nithinsubbiah**
Add a check for valid quantized data types for the ROCm backend 
fixes #18367

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToROCDL.cpp [hunk 1]
```diff
@@ -72,6 +72,20 @@ static void populateConvertGPUToAMDGPUPatterns(RewritePatternSet &patterns) {
...
 
+// Function to check valid data types on the ROCm backend.
+LogicalResult validateDataTypes(Operation *op) {
+  if (llvm::any_of(op->getOperandTypes(),
+                   [](Type type) {
+                     return (type.isFloat8E4M3FN() || type.isFloat8E4M3FN());
+                   }) ||
+      llvm::any_of(op->getResultTypes(), [](Type type) {
+        return (type.isFloat8E4M3FN() || type.isFloat8E4M3FN());
+      }))
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToROCDL.cpp]: Use `llvm::IsaPred`

File: compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToROCDL.cpp [hunk 2]
```diff
@@ -90,6 +104,16 @@ struct ConvertToROCDLPass final
   void runOnOperation() override {
     ModuleOp m = getOperation();
 
+    m.walk(
+        [&](Operation *op) {
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToROCDL.cpp]: Does this capture anything? If we only need the capture for `this`, it seems like we could make `validateDataTypes` a free/static function instead

File: compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToROCDL.cpp [hunk 3]
```diff
@@ -90,6 +104,16 @@ struct ConvertToROCDLPass final
...
+          if (failed(validateDataTypes(op))) {
+            op->emitOpError()
+                << "F8E5M2 and F8E4M3FN types are not supported on "
+                   "the ROCm backend; try F8E5M2FNUZ or F8E4M3FNUZ instead.";
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToROCDL.cpp]: The exact error message can be emitted from within the validation function. This is so that the error and the validation logic stay together and don't diverge

**Review by kuhar — CHANGES_REQUESTED** [review]

File: compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToROCDL.cpp [hunk 4]
```diff
@@ -72,6 +72,21 @@ static void populateConvertGPUToAMDGPUPatterns(RewritePatternSet &patterns) {
 
 } // namespace
 
+// Function to check valid data types on the ROCm backend.
+static LogicalResult validateDataTypes(Operation *op) {
+  if (llvm::any_of(op->getOperandTypes(),
+                   llvm::IsaPred<Float8E4M3FNType, Float8E5M2Type>) ||
+      llvm::any_of(op->getResultTypes(),
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToROCDL.cpp]: I think you can combine these two with `llvm::concat<Type>(op.getOperandTypes(), op.getResultTypes())`

Comment (nithinsubbiah) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToROCDL.cpp]: that's neat, thanks for the pointer :)

**Review by kuhar — APPROVED** [review]
LGTM

**Review by MaheshRavishankar — COMMENTED** [review]
This needs a test.
