### PR TITLE
[Codegen] Canonicalize loops and subviews after copy vectorization

### LINKED ISSUE #22335: Recent change caused weight backward 1x1 Conv failed to compile
### What happened?

The following input IR
```
#map = affine_map<(d0, d1, d2, d3, d4, d5, d6) -> (d4, d1 + d5 * 2, d2 + d6 * 2, d3)>
#map1 = affine_map<(d0, d1, d2, d3, d4, d5, d6) -> (d4, d5, d6, d0)>
#map2 = affine_map<(d0, d1, d2, d3, d4, d5, d6) -> (d0, d1, d2, d3)>
#map3 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
module @module {
  util.func public @conv_2d_bfloat16_weight_backward_16x96x64x40_nhwc_96x1x1x40_fhwc_nhwf_2x2s_0x0p_1x1d_1g$async(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view, %arg2: !hal.buffer_view, %arg3: !hal.fence, %arg4: !hal.fence) -> !hal.buffer_view attributes {inlining_policy = #util.inline.never, iree.abi.model = "coarse-fences", iree.abi.stub} {
    %cst = arith.constant 0.000000e+00 : f32
    %0 = hal.tensor.import wait(%arg3) => %arg0 : !hal.buffer_view -> tensor<16x48x32x96xbf16>
    %1 = hal.tensor.import wait(%arg3) => %arg1 : !hal.buffer_view -> tensor<16x96x64x40xbf16>
    %2 = tensor.empty() : tensor<96x1x1x40xf32>
    %3 = linalg.fill ins(%cst : f32) outs(%2 : tensor<96x1x1x40xf32>) -> tensor<96x1x1x40xf32>
    %4 = linalg.generic {indexing_maps = [#map, #map1, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel", "reduction", "reduction", "reduction"]} ins(%1, %0 : tensor<16x96x64x40xbf16>, tensor<16x48x32x96xbf16>) outs(%3 : tensor<96x1x1x40xf32>) {
    ^bb0(%in: bf16, %in_0: bf16, %out: f32):
      %9 = arith.extf %in : bf16 to f32
      %10 = arith.extf %in_0 : bf16 to f32
      %11 = arith.mulf %9, %10 : f32
      %12 = arith.addf %out, %11 : f32
      linalg.yield %12 : f32
    } -> tensor<96x1x1x40xf32>
    %5 = tensor.empty() : tensor<96x1x1x40xbf16>
    %6 = linalg.generic {indexing_maps = [#map3, #map3], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%4 : tensor<96x1x1x40xf32>) outs(%5 : tensor<96x1x1x40xbf16>) {
    ^bb0(%in: f32, %out: bf16):
      %9 = arith.truncf %in : f32 to bf16
      linalg.yield %9 : bf16
    } -> tensor<96x1x1x40xbf16>
    %7 = hal.tensor.barrier join(%6 : tensor<96x1x1x40xbf16>) => %arg4 : !hal.fence
    %8 = hal.tensor.export %7 : tensor<96x1x1x40xbf16> -> !hal.buffer_view
    util.return %8 : !hal.buffer_view
  }
  util.func public @conv_2d_bfloat16_weight_backward_16x96x64x40_nhwc_96x1x1x40_fhwc_nhwf_2x2s_0x0p_1x1d_1g(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view, %arg2: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub} {
    %0 = util.null : !hal.fence
    %c-1_i32 = arith.constant -1 : i32
    %c0 = arith.constant 0 : index
    %device_0 = hal.devices.get %c0 : !hal.device
    %fence = hal.fence.create device(%device_0 : !hal.device) flags("None") : !hal.fence
    %1 = util.call @conv_2d_bfloat16_weight_backward_16x96x64x40_nhwc_96x1x1x40_fhwc_nhwf_2x2s_0x0p_1x1d_1g$async(%arg0, %arg1, %arg2, %0, %fence) : (!hal.buffer_view, !hal.buffer_view, !hal.buffer_view, !hal.fence, !hal.fence) -> !hal.buffer_view
    %status = hal.fence.await until([%fence]) timeout_millis(%c-1_i32) flags("None") : i32
    util.return %1 : !hal.buffer_view
  }
}

```
It was able to compile with head commit 0b0a17abbb4951b3ffbd229bde397012753d64b2.

But failed to compile with head commit fe3b8fe42a23141b6cc5968ac0f950c6db199f81.

The error shows as
```
conv_2d_bfloat16_weight_backward_16x96x64x40_nhwc_96x1x1x40_fhwc_nhwf_2x2s_0x0p_1x1d_1g.mlir:12:10: error: expected result type to be 'memref<1x?xbf16, strided<[4, 1]>, #gpu.address_space<private>>' or a rank-reduced version. (mismatch of result layout), but got 'memref<1x?xbf16, strided<[4, 1], offset: ?>, #gpu.address_space<private>>'
    %4 = linalg.generic {indexing_maps = [#map, #map1, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel", "reduction", "reduction", "reduction"]} ins(%1, %0 : tensor<16x96x64x40xbf16>, tensor<16x48x32x96xbf16>) outs(%3 : tensor<96x1x1x40xf32>) {
```

### Steps to reproduce your issue

Compile command:

`iree-compile --iree-hal-target-backends=rocm --iree-hip-target=mi300x --iree-opt-level=O3 example_ir.mlir`

### What component(s) does this issue relate to?

_No response_

### Version information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jtuyls**
Fixes: https://github.com/iree-org/iree/issues/22335

The new `memref.copy` tiling and vectorization patterns can generate loops and subviews that can be canonicalized further. If this isn't done, it can lead to errors in a later `FoldMemRefAliasOp` pass as the subviews are supposed to be canonicalized at that point.

The alternative is to always run (subview) canonicalization before `FoldMemRefAliasOp`. I can implement it that way as well in upstream, but I think canonicalizing the generated loops and subviews after `VectorizeMemrefCopy` makes sense as well.

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp [hunk 1]
```diff
@@ -564,6 +564,7 @@ void addGPUTileAndFusePassPipeline(OpPassManager &funcPassManager,
   funcPassManager.addPass(createGPUDistributeForallPass());
 
   // Vectorize copies that came out of bufferization.
+  funcPassManager.addPass(createRemoveSingleIterationLoopPass());
```
Comment (jtuyls) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp]: I added this before the `VectorizeMemrefCopy` pass as the latter has the effect of simplifying loops as well and if there exist non-simplified loops before this one, that would be a side-effect on ops that are unrelated to the copy.

But I am going to have a look at just simplifying the for ops that were created for the copy. Putting this in draft for now.

Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp]: I updated the logic to only simplify for ops that were created in the pass itself so it doesn't have any opaque side effects.

File: compiler/src/iree/compiler/Codegen/Transforms/RemoveSingleIterationLoop.cpp [hunk 2]
```diff
@@ -62,15 +62,21 @@ namespace {
 struct SimplifyTrivialLoops : public OpRewritePattern<scf::ForOp> {
   using Base::Base;
 
+  SimplifyTrivialLoops(MLIRContext *context, ForControlFnRef controlFn)
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/Transforms/RemoveSingleIterationLoop.cpp:64]: Are we still using the constructor a couple of lines above?

File: compiler/src/iree/compiler/Codegen/Transforms/RemoveSingleIterationLoop.cpp [hunk 3]
```diff
@@ -62,15 +62,21 @@ namespace {
...
+      : OpRewritePattern(context), controlFn(controlFn) {}
+
   LogicalResult matchAndRewrite(scf::ForOp op,
                                 PatternRewriter &rewriter) const override {
+    if (controlFn && !controlFn(op)) {
+      return rewriter.notifyMatchFailure(
+          op, "doesn't match according to the the control function");
+    }
     if (!(neverRunsSecondIteration(op))) {
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/Transforms/RemoveSingleIterationLoop.cpp]: The parens here are not necessary

File: compiler/src/iree/compiler/Codegen/Common/VectorizeMemrefCopy.cpp [hunk 4]
```diff
@@ -104,12 +111,18 @@ struct VectorizeMemrefCopyPass final
     patterns.add<TileLinalgCopy>(&getContext());
     patterns.add<linalg::CopyVectorizationPattern>(&getContext());
     patterns.add<ConvertLinalgCopyToMemrefCopy>(&getContext());
+    // Try to remove generated single iteration loops and canonicalize generated
+    // subview operations.
+    populateRemoveSingleIterationLoopPattern(
+        patterns,
+        [&](scf::ForOp forOp) -> bool { return forOp->hasAttr(kIsTiled); });
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/Common/VectorizeMemrefCopy.cpp:118]: Would it make sense to add a lit test that checks for this directly?

**Review by kuhar — COMMENTED** [review]
I'm surprised single-iteration `scf.for` ops are not folded by the default canonicalizer? https://github.com/llvm/llvm-project/blob/565e9fa1956802f9c4aefe2dea9a1061f52667b0/mlir/lib/Dialect/SCF/IR/SCF.cpp#L1149

File: compiler/src/iree/compiler/Codegen/Common/VectorizeMemrefCopy.cpp (hunk 4 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/Common/VectorizeMemrefCopy.cpp:118]: Like a test with for loops that have the attribute and checks that they are simplified right?

**Comment by jtuyls** [comment]
> I'm surprised single-iteration `scf.for` ops are not folded by the default canonicalizer? https://github.com/llvm/llvm-project/blob/565e9fa1956802f9c4aefe2dea9a1061f52667b0/mlir/lib/Dialect/SCF/IR/SCF.cpp#L1149

Oh, weird, I will have a look at that.

File: compiler/src/iree/compiler/Codegen/Common/VectorizeMemrefCopy.cpp (hunk 4 above)
Comment (kuhar) [reply compiler/src/iree/compiler/Codegen/Common/VectorizeMemrefCopy.cpp:118]: yes

**Review by MaheshRavishankar — APPROVED** [review]
The original issue is blocking IREE bump downstream. Can we land this and remove later after the upstream issue is triaged...

File: compiler/src/iree/compiler/Codegen/Transforms/RemoveSingleIterationLoop.cpp (hunk 3 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/Transforms/RemoveSingleIterationLoop.cpp]: Removed now.

File: compiler/src/iree/compiler/Codegen/Common/VectorizeMemrefCopy.cpp (hunk 4 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/Common/VectorizeMemrefCopy.cpp:118]: I added a test for this now.

File: compiler/src/iree/compiler/Codegen/Transforms/RemoveSingleIterationLoop.cpp (hunk 2 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/Transforms/RemoveSingleIterationLoop.cpp:64]: No, removed it.

**Comment by jtuyls** [comment]
@kuhar I merged this to unblock the downstream bump, but I will still look at the why the upstream canonicalizer didn't work for this.
