### PR TITLE
[DispatchCreation] Fix producer fusion with nested region uses

### LINKED ISSUE #23339: Failed to LayerNorm with unit batch with enabled split reduction
### What happened?

The MLIR can be found [here](https://gist.github.com/a-sidorova/1f1abd464f98232f2aa0a97211c7058c).

Command line:
```
iree-compile layernorm_single_batch.mlir --iree-hal-target-backends=rocm --iree-hip-target=gfx950 \
             --iree-opt-level=O3 --iree-preprocessing-pass-pipeline="builtin.module(util.func(iree-preprocessing-convert-conv-filter-to-channels-last))" \
             --iree-flow-enable-pad-handling --iree-global-opt-propagate-transposes-through-conv \
             --iree-global-opt-enable-sink-transpose-through-pad --iree-dispatch-creation-enable-fuse-padding-into-linalg-consumer-ops \
             --iree-dispatch-creation-enable-aggressive-reshape-movement --iree-dispatch-creation-enable-split-reduction \
              -o iree-compile-output.vmfb
```

Output:
```
layernorm_single_batch.mlir:22:29: error: operand #0 does not dominate this use
    %y_layernorm_fwd_perm = torch.aten.layer_norm %x_layernorm_fwd_perm, %normalized_shape_layernorm_fwd, %none_scale_layernorm_fwd, %none_bias_layernorm_fwd, %eps_layernorm_fwd, %cudnn_enable_layernorm_fwd : !torch.vtensor<[1,3,128,128],f32>, !torch.list<int>, !torch.none, !torch.none, !torch.float, !torch.bool -> !torch.vtensor<[1,3,128,128],f32>
                            ^
layernorm_single_batch.mlir:22:29: note: see current operation: %32 = "tensor.extract_slice"(%17#1, %arg12, %arg13) <{operandSegmentSizes = array<i32: 1, 2, 0, 0>, static_offsets = array<i64: -9223372036854775808, -9223372036854775808, 0>, static_sizes = array<i64: 1, 8, 128>, static_strides = array<i64: 1, 1, 1>}> : (tensor<3x128x128xf32>, index, index) -> tensor<1x8x128xf32>
layernorm_single_batch.mlir:22:29: note: operand defined here (op in a parent region)
```

But I remove the key `--iree-dispatch-creation-enable-split-reduction` from compilation command line, the MLIR is successfully built and executed.

### What component(s) does this issue relate to?

IREE Compiler

### Version information

Can be successfully reproduced on the IREE commits: https://github.com/iree-org/iree/commit/18fe0926981becffb1332ed727aaf916a9727b13 (30/01/26) and https://github.com/iree-org/iree/commit/4031503a5536c232c5dc0a0412bbf7086db38207 (14/01/26).

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvedhmeshram**
In `fuseRootsWithProducers`, the pass only checked same-block uses via `getFusableUses`, missing uses from above where a producer's result is captured in nested regions. This caused dominance violations when the producer was fused into a later dispatch, breaking intervening ops that used it.

The fix walks up from each use to the parent op in the same block as root and verifies the root dominates it, blocking fusion if not.

Fixes: https://github.com/iree-org/iree/issues/23339

Co-authored-by: GitHub Copilot <noreply@github.com>

### CODE REVIEW

File: compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp [hunk 1]
```diff
@@ -754,6 +754,40 @@ static bool isFusableWithProducer(OpOperand &operand,
...
 
+/// Check if moving the producer into the dispatch at the root's position would
+/// break any existing uses. Returns true if there are uses between the producer
+/// and the root that are not in the fusion group, which would cause a dominance
+/// violation.
+static bool hasUsesBetweenProducerAndRoot(Operation *producer, Operation *root,
+                                          const FusionGroup &fusionGroup,
+                                          const DominanceInfo &dominanceInfo) {
+  for (Value result : producer->getResults()) {
+    for (OpOperand &use : result.getUses()) {
```
Comment (IanWood1) [inline compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp]: Looks like these two loops can be simplified to just `producer->getUsers()`

File: compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp [hunk 2]
```diff
@@ -754,6 +754,40 @@ static bool isFusableWithProducer(OpOperand &operand,
   return true;
 }
 
+/// Check if moving the producer into the dispatch at the root's position would
+/// break any existing uses. Returns true if there are uses between the producer
+/// and the root that are not in the fusion group, which would cause a dominance
+/// violation.
+static bool hasUsesBetweenProducerAndRoot(Operation *producer, Operation *root,
```
Comment (IanWood1) [inline compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp:761]: Side note: ideally, we would have something like `hasTransitiveDependencyOnFusionGroup` but for the producer case. Then `movePrecedingOpsIntoDispatchRegion` would need to move uses of producer that dominate the root.

File: compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp
Comment (IanWood1) [inline compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp:822]: We might be able to remove this now.

File: compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp [hunk 3]
```diff
@@ -754,6 +754,40 @@ static bool isFusableWithProducer(OpOperand &operand,
...
+        }
+      }
+      if (!user) {
+        continue;
+      }
+      // If the user is in the fusion group, it will be moved too.
+      if (fusionGroup.contains(user) || user == producer) {
+        continue;
+      }
+      // If the user does not come after the root, then moving the producer
```
Comment (IanWood1) [inline compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp]: I don't see when this would be true `user == producer`.

File: compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp
Comment (nirvedhmeshram) [reply compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp:822]: maybe better to do that in a separate PR? I wouldnt want this one getting reverted in case there is some use case where this is not yet safe.

File: compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp (hunk 2 above)
Comment (nirvedhmeshram) [reply compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp:761]: Makes sense, probably want to file an issue for this and use this PR as a workaround for the compilation bug in the time being?

Comment (IanWood1) [reply compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp:761]: Yeah that makes sense, I'm using https://github.com/iree-org/iree/issues/22528 to track this (specifically https://github.com/iree-org/iree/issues/22528#issuecomment-3745446056).

File: compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp
Comment (IanWood1) [reply compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp:822]: Good point, there's no reason to risk a revert.

File: compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp [hunk 4]
```diff
@@ -754,6 +754,38 @@ static bool isFusableWithProducer(OpOperand &operand,
...
+                                          const DominanceInfo &dominanceInfo) {
+  for (OpOperand &use : producer->getUses()) {
+    Operation *user = use.getOwner();
+    // Walk up to the parent in the same block as the producer/root.
+    while (user->getBlock() != root->getBlock()) {
+      user = user->getParentOp();
+      if (!user) {
+        break;
+      }
+    }
```
Comment (IanWood1) [inline compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp]: optional nit:
```suggestion
    while (user && user->getBlock() != root->getBlock()) {
      user = user->getParentOp();
    }
```

File: compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp [hunk 5]
```diff
@@ -754,6 +754,38 @@ static bool isFusableWithProducer(OpOperand &operand,
...
+    if (!user) {
+      continue;
+    }
+    // If the user is in the fusion group, it will be moved too.
+    if (fusionGroup.contains(user)) {
+      continue;
+    }
```
Comment (IanWood1) [inline compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp]: Optional:
```suggestion
    // If the user is in the fusion group, it will be moved too.
    if (!user || fusionGroup.contains(user)) {
      continue;
    }
```

**Review by IanWood1 — APPROVED** [review]
LGTM!
