### PR TITLE
[codegen] more consumer fusion

### LINKED ISSUE #21814: Failure in compilation of llama 3.1 405B model
### What happened?

Llama 405B model fails to compile with the following error, starting from the commit https://github.com/iree-org/iree/commit/4d91ffb09a8e48844b6460edce58ccba245bced7.

```
/__w/shark-ai/shark-ai/scripts/../output_artifacts/output.mlir:274794:12: error: 'vector.transfer_write' op write affecting operations on global resources are restricted to workgroup distributed contexts.
      %9 = arith.scaling_truncf %in, %8 : f32, f32 to f4E2M1FN
           ^
/__w/shark-ai/shark-ai/scripts/../output_artifacts/output.mlir:6770:15: note: called from
    %2425:2 = util.call @dynamic_quantize_to_fp4_N_M32_32_f32_N_i8_N_M16_16_i8(%2424) : (tensor<?x32xf32>) -> (tensor<?xi8>, tensor<?x16xi8>)
              ^
/__w/shark-ai/shark-ai/scripts/../output_artifacts/output.mlir:274794:12: note: see current operation: "vector.transfer_write"(%59, %49, %54#0, %54#1, %6) <{in_bounds = [true], operandSegmentSizes = array<i32: 1, 1, 3, 0>, permutation_map = affine_map<(d0, d1, d2) -> (d2)>}> : (vector<32xf4E2M1FN>, memref<?x65536x32xf4E2M1FN, strided<[2097152, 32, 1], offset: ?>, #hal.descriptor_type<storage_buffer>>, index, index, index) -> ()
      %9 = arith.scaling_truncf %in, %8 : f32, f32 to f4E2M1FN
           ^
/__w/shark-ai/shark-ai/scripts/../output_artifacts/output.mlir:274777:16: error: 'func.func' op failed on workgroup distribution verification
    %reduced = linalg.reduce ins(%arg0 : tensor<?x32xf32>) outs(%3 : tensor<?xf32>) dimensions = [1] 
               ^
/__w/shark-ai/shark-ai/scripts/../output_artifacts/output.mlir:6770:15: note: called from
    %2425:2 = util.call @dynamic_quantize_to_fp4_N_M32_32_f32_N_i8_N_M16_16_i8(%2424) : (tensor<?x32xf32>) -> (tensor<?xi8>, tensor<?x16xi8>)
```

### Steps to reproduce your issue

Download the IR 
```
wget https://sharkpublic.blob.core.windows.net/sharkpublic/halo-models/llm-dev/llama3_405b/fp4/mlir/prefill_4_decode_8_asm_sharktank_02_09_2025.mlir
```

Compile 

```
iree-compile prefill_4_decode_8_asm_sharktank_02_09_2025.mlir \
        --iree-hip-target=gfx950 -o output.vmfb \
        --iree-hal-target-device=hip \
        --iree-opt-level=O3 \
        --iree-dispatch-creation-propagate-collapse-across-expands=true \
        --iree-hal-indirect-command-buffers=true \
        --iree-stream-resource-memory-model=discrete \
        --iree-hal-memoization=true \
        --iree-codegen-enable-default-tuning-specs=true \
        --iree-stream-affinity-solver-max-iterations=1024 \
        --iree-llvmgpu-set-workgroup-distribution-along=z \
        --iree-dispatch-creation-enable-early-trunc-fusion=true
```

### What component(s) does this issue relate to?

Compiler

### Version information

6cfd70e97881c425d817ba69ea48aa20e497846b

### Additional context

Error log: https://gist.github.com/praveen-g-ctt/bd719afb7d70c93a88f48d68b77add13

CC: @ftynse

### LINKED ISSUE #21847: [GPU][DT] Llama3 8b 'Cannot set layouts on a dynamically shaped iteration space' compilation error
On latest main (https://github.com/iree-org/iree/commit/933f798046a817dcff48d84df8fd987c5cb9e72b) llama3 8b fails compilation with data tiling because [[codegen] more consumer fusion](https://github.com/iree-org/iree/pull/21521) was reverted. I didn't notice this on [[DT] Fuse encoding ops more aggressively for multi-use, gather, and slices ops.](https://github.com/iree-org/iree/pull/21830) as that PR was based on a commit on main before the former was reverted.

Repro: https://gist.github.com/jtuyls/de2917a483082d5ffc86be6282cc3668. You should an error similar to the below when running with a build based on https://github.com/iree-org/iree/commit/933f798046a817dcff48d84df8fd987c5cb9e72b:
```
error: Cannot set layouts on a dynamically shaped iteration space
        %55 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> ()>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%47, %48, %49 : tensor<?x4096xf32>, tensor<?x4096xf32>, tensor<f32>) outs(%54 : tensor<?x4096xf32>) {
...
```

### PR DESCRIPTION
**Pull request by jtuyls**
Resolves: https://github.com/iree-org/iree/issues/21814
Resolves: https://github.com/iree-org/iree/issues/21847

Resubmits https://github.com/iree-org/iree/pull/21521 after a revert (https://github.com/iree-org/iree/pull/21819) with an additional fix for the llama 405b compilation issue. 

I verified this on the following reported IR: https://sharkpublic.blob.core.windows.net/sharkpublic/halo-models/llm-dev/llama3_405b/fp4/mlir/asm/f4_bs4_ds4.iree0902.shark0903_4aa.mlir:
```
iree-compile --iree-hip-target=gfx950     -o=test.vmfb     --iree-hal-target-device=hip     --iree-opt-level=O3     --iree-dispatch-creation-propagate-collapse-across-expands=true     --iree-stream-affinity-solver-max-iterations=1024     --iree-hal-indirect-command-buffers=true     --iree-stream-resource-memory-model=discrete     --iree-hip-specialize-dispatches     --iree-hal-memoization=true     --iree-codegen-enable-default-tuning-specs=true f4_bs4_ds4.iree0902.shark0903_4aa.mlir
```

Does anyone want to check the numerics as well with this patch as I don't have that setup @pravg-amd @AmosLewis ?

Additionally resolves a compilation issue encountered for data-tiled llama3 8b after the revert (https://github.com/iree-org/iree/issues/21847).

### CODE REVIEW

**Review by dan-garvey — COMMENTED** [review]
So the fix was basically to consider all the fusableUsers?

**Comment by ftynse** [comment]
> So the fix was basically to consider all the fusableUsers?

Yep. The initial algorithm would look at essentially one chain of users. I updated it to look at users of multiple results, but forgot (or rather didn't need) to update for multiple disconnected users of the same result, both of which are being returned.

**Review by ftynse — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by jtuyls** [comment]
Could I get a review from a non-author as well? @MaheshRavishankar @hanhanW

**Review by dan-garvey — APPROVED** [review]
LGTM but probably good to get a review from a code owner

File: compiler/src/iree/compiler/Codegen/Common/TileAndFuseUtils.cpp [hunk 1]
```diff
@@ -87,16 +88,51 @@ void collectTiledAndFusedOps(Operation *rootOp,
...
+  // update them as fusion happens, in particular, more slices may need to be
+  // handled. For example, fusing B with A will create a slice of B that will
+  // need to be handled correctly.
+  SmallVector<ConsumerFusionQueueEntry> candidates;
   llvm::SmallDenseSet<tensor::ParallelInsertSliceOp> allCandidates;
   auto addCandidateSlices = [&candidates, &allCandidates,
                              &filterFn](Operation *fusedOp) {
+    // Dominance info recreated since op creation/movement in the fusion logic
+    // invalidates it anyway.
+    DominanceInfo dominanceInfo;
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Codegen/Common/TileAndFuseUtils.cpp]: I dont think we want the `dominanceInfo` instantiated on every call of `addCandidateSlices`. Best to share the dominance object.

**Review by MaheshRavishankar — APPROVED** [review]
Phew! That is some complex logic, but looks good. Thanks! 

Left one comment.

File: compiler/src/iree/compiler/Codegen/Common/TileAndFuseUtils.cpp (hunk 1 above)
Comment (jtuyls) [reply compiler/src/iree/compiler/Codegen/Common/TileAndFuseUtils.cpp]: Done where possible by adding `dominanceInfo` as a parameter.
