### PR TITLE
[mlir][DispatchCreation] Avoid cloning for ops that are index return type dispatch operands.

### LINKED ISSUE #18229: Failed to legalize operation 'stream.cmd.dispatch'
For IR provided [here](https://gist.github.com/nirvedhmeshram/f350fa447fdf5cdcbff45ced0dd77e6c)

with
```
iree-compile uncased_transpose_repro.mlir --iree-hal-target-backends="rocm" --iree-rocm-target-chip=gfx942 -o dump.vmfb
```
OR
```
iree-compile uncased_transpose_repro.mlir --iree-hal-target-backends=llvm-cpu -o dump.vmfb
```
We get the following error
```
uncased_transpose_repro.mlir:92:11: error: failed to legalize operation 'stream.cmd.dispatch' that was explicitly marked illegal
    %88 = torch.operator "onnx.Transpose"(%87) {torch.onnx.perm = [0 : si64, 2 : si64, 1 : si64, 3 : si64]} : (!torch.vtensor<[?,?,?,?],f32>) -> !torch.vtensor<[?,?,?,?],f32> 
          ^
cased_MM.mlir:92:11: note: see current operation: "stream.cmd.dispatch"(%17, %18, %5, %6, %106, %108, %78, %80, %82, %84, <<UNKNOWN SSA VALUE>>, <<UNKNOWN SSA VALUE>>, %66, %42, %7, %7, %66, %42) <{entry_points = [@torch_jit$async_dispatch_10::@embedded_elf_x86_64::@torch_jit$async_dispatch_10_transpose_Dx12xDx64_f32], operandSegmentSizes = array<i32: 4, 6, 2, 2, 2, 2>, resource_accesses = [1 : i32, 2 : i32]}> : (index, index, index, index, i32, i32, i32, i32, i32, i32, !stream.resource<transient>, !stream.resource<external>, index, index, index, index, index, index) -> ()
```

### PR DESCRIPTION
**Pull request by nirvedhmeshram**
Such operations are shape computations that need to happen on host.

Fixes: https://github.com/iree-org/iree/issues/18229

### CODE REVIEW

**Comment by benvanik** [comment]
We may not want this hard of a rule here - if we can absorb a bunch of index math we want to do that.
(index is not only used for shape computations - it's used for indexing, like loops and slices and stuff)

**Comment by MaheshRavishankar** [comment]
> We may not want this hard of a rule here - if we can absorb a bunch of index math we want to do that. (index is not only used for shape computations - it's used for indexing, like loops and slices and stuff)

Yeah, those should still get absorbed.  We can probably change this to look for the case where the "owner" is a `flow.dispatch.region`. The only operands for it are shape of the result tensors.

**Comment by nirvedhmeshram** [comment]
> We may not want this hard of a rule here - if we can absorb a bunch of index math we want to do that. (index is not only used for shape computations - it's used for indexing, like loops and slices and stuff)

That makes sense, not sure what a good way forward is for the failing models. One way could be that we want to not fuse both direct and indirect index.casts when they are dispatch operands then? If thats acceptable then will need to rewrite the logic to carry some more state so as to not make it expensive to check this all the time.

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp [hunk 1]
```diff
@@ -762,12 +762,12 @@ static bool hasUnfusableUseInDispatch(Value v, Operation *dispatchOp) {
...
-    // owner.
-    if (auto indexCastOp = v.getDefiningOp<arith::IndexCastOp>()) {
-      if (user == dispatchOp) {
-        return true;
-      }
+    // Do not fuse operations if they are already an operand of the
+    // owner and have an index return type as that means its a shape
+    // computation that needs to happen on the host.
+    auto op = v.getDefiningOp();
+    if (op && user == dispatchOp && v.getType().isIndex()) {
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp]: For now just add a check that the `dispatchOp` is a `flow.dispatch.region`.

**Comment by MaheshRavishankar** [comment]
Actually I dont know if we want to support moving operations into `flow.dispatch.workgroups`. I dont think we actually do it anywhere or want to support that. IIUC, the logic as written does not prevent absorbing index math when the uses are inside the `flow.dispatch.region`. It only prevents it when it is operands of a `flow.dispatch.region`. So I think its fine?

File: compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp (hunk 1 above)
Comment (nirvedhmeshram) [reply compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp]: Added the check despite your comment below that it is okay as is, as that check doesnt hurt. Can remove it though.

**Review by MaheshRavishankar — APPROVED** [review]
