### PR TITLE
[Codegen][LLVMGPU] Optionally linearize the number of workgroups specified

### LINKED ISSUE #20766: [HIP] Runtime failure for forward conv
### What happened?

The following IR compiles successfully for `gfx942`, but results in an error when running:

### Error

```
EXEC @conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g
c/runtime/src/iree/hal/drivers/hip/event_semaphore.c:786: ABORTED; the semaphore was aborted; while invoking native function hal.fence.await; while calling import; 
[ 0] bytecode module.conv_2d_float
```

### Reproducer IR

```mlir
#map = affine_map<(d0, d1, d2, d3, d4, d5, d6) -> (d0, d1 + d4, d2 + d5, d6)>
#map1 = affine_map<(d0, d1, d2, d3, d4, d5, d6) -> (d3, d4, d5, d6)>
#map2 = affine_map<(d0, d1, d2, d3, d4, d5, d6) -> (d0, d1, d2, d3)>
module @module {
  util.func public @conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view, %arg2: !hal.fence, %arg3: !hal.fence) -> !hal.buffer_view attributes {inlining_policy = #util.inline.never, iree.abi.model = "coarse-fences", iree.abi.stub, preprocessing_pipeline = #util.preprocessing_pipeline<"iree-preprocessing-make-single-dispatch">} {
    %cst = arith.constant 0.000000e+00 : f32
    %0 = hal.tensor.import wait(%arg2) => %arg0 : !hal.buffer_view -> tensor<11x470x725x32xf32>
    %1 = hal.tensor.import wait(%arg2) => %arg1 : !hal.buffer_view -> tensor<224x1x1x32xf32>
    %2 = tensor.empty() : tensor<11x470x725x224xf32>
    %3 = linalg.fill ins(%cst : f32) outs(%2 : tensor<11x470x725x224xf32>) -> tensor<11x470x725x224xf32>
    %4 = linalg.generic {indexing_maps = [#map, #map1, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel", "reduction", "reduction", "reduction"]} ins(%0, %1 : tensor<11x470x725x32xf32>, tensor<224x1x1x32xf32>) outs(%3 : tensor<11x470x725x224xf32>) {
    ^bb0(%in: f32, %in_0: f32, %out: f32):
      %7 = arith.mulf %in, %in_0 : f32
      %8 = arith.addf %out, %7 : f32
      linalg.yield %8 : f32
    } -> tensor<11x470x725x224xf32>
    %5 = hal.tensor.barrier join(%4 : tensor<11x470x725x224xf32>) => %arg3 : !hal.fence
    %6 = hal.tensor.export %5 : tensor<11x470x725x224xf32> -> !hal.buffer_view
    util.return %6 : !hal.buffer_view
  }
  util.func public @conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub} {
    %0 = util.null : !hal.fence
    %c-1_i32 = arith.constant -1 : i32
    %c0 = arith.constant 0 : index
    %device_0 = hal.devices.get %c0 : !hal.device
    %fence = hal.fence.create device(%device_0 : !hal.device) flags("None") : !hal.fence
    %1 = util.call @conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async(%arg0, %arg1, %0, %fence) : (!hal.buffer_view, !hal.buffer_view, !hal.fence, !hal.fence) -> !hal.buffer_view
    %status = hal.fence.await until([%fence]) timeout_millis(%c-1_i32) flags("None") : i32
    util.return %1 : !hal.buffer_view
  }
}
```

### Steps to reproduce your issue

1. Compile the IR with ```iree-compile --iree-hal-target-backends=rocm --iree-hip-target=gfx942 -o repro.vmfb```
2. Run with ```iree-run-module --module=<repro.vmfb> --function=conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g --device=hip --input="11x470x725x32xf32=1.0" --input="224x1x1x32xf32=1.0" ```

### What component(s) does this issue relate to?

Runtime

### Version information

local build @ efeb94bc1ddb9ddc00c525cf8c8385c501799ef6

### Additional context

Running with `--trace_execution` gives:

```
[module.__init+00000000]    <block>
[module.__init+00000001]    %i0 = vm.const.i32 1  // 0x00000001
[module.__init+00000008]    %r0 = vm.const.ref.zero
[module.__init+0000000B]    %i1 = vm.const.i32 14  // 0x0000000E
[module.__init+00000012]    %i2:3 = vm.const.i64 -1  // 0xFFFFFFFFFFFFFFFF
[module.__init+0000001D]    %i4 = vm.const.i32 18  // 0x00000012
[module.__init+00000024]    %i5 = vm.const.i32.zero
[module.__init+00000027]    %i6:7 = vm.const.i64.zero
[module.__init+0000002A]    %i8:9 = vm.const.i64 1  // 0x0000000000000001
[module.__init+00000035]    %r1 = vm.const.ref.zero
[module.__init+00000038]    %i10 = vm.call @hal.devices.count()
[module.__init+00000044]    %i10:11 = vm.ext.i32.i64.s %i10(1)
[module.__init+00000049]    vm.br ^00000064(%r1(null)->%r2, %i6(0)->%i12, %i7(0)->%i13, %i6(0)->%i14, %i7(0)->%i15)
[module.__init+00000065]    %i16 = vm.cmp.nz.ref %r2(null)
[module.__init+0000006A]    %i16 = vm.xor.i32 %i16(0), %i0(1)
[module.__init+00000071]    %i17 = vm.cmp.lt.i64.s %i12:13(0), %i10:11(1)
[module.__init+00000078]    %i17 = vm.and.i32 %i16(1), %i17(1)
[module.__init+0000007F]    vm.cond_br %i17(1), ^0000008E(), ^00000158()
[module.__init+0000008F]    %i16 = vm.trunc.i64.i32 %i12:13(0)
[module.__init+00000094]    %r2 = vm.call @hal.devices.get(%i16(0))
[module.__init+000000A2]    %r3 = vm.const.ref.rodata 0  // 0x0x5cf05d77fe5c 13b
[module.__init+000000A9]    %r4 = vm.const.ref.rodata 1  // 0x0x5cf05d77fe78 3b
[module.__init+000000B0]    %i16, %i18 = vm.call @hal.device.query.i64(%r2(!hal.device/0x0x5cf05e379950), %r3(!vm.buffer/0x0x5cf05d77dc90), %r4(!vm.buffer/0x0x5cf05d77dcb8))
[module.__init+000000C4]    %i17 = vm.cmp.nz.i64 %i18:19(1)
[module.__init+000000C9]    %i16 = vm.select.i32 %i16(1) ? %i17(1) : %i5(0)
[module.__init+000000D2]    vm.cond_br %i16(1), ^000000E6(), ^0000011E(%i5(0)->%i16)
[module.__init+000000E7]    %r3 = vm.const.ref.rodata 2  // 0x0x5cf05d77fe88 21b
[module.__init+000000EE]    %r4 = vm.const.ref.rodata 3  // 0x0x5cf05d77feac 13b
[module.__init+000000F5]    %i16, %i18 = vm.call @hal.device.query.i64(%r2(!hal.device/0x0x5cf05e379950), %r3(!vm.buffer/0x0x5cf05d77dce0), %r4(!vm.buffer/0x0x5cf05d77dd08))
[module.__init+00000108]    %i17 = vm.cmp.nz.i64 %i18:19(1)
[module.__init+0000010D]    %i16 = vm.select.i32 %i16(1) ? %i17(1) : %i5(0)
[module.__init+00000116]    vm.br ^0000011E()
[module.__init+0000011F]    %i17 = vm.cmp.eq.i64 %i14:15(0), %i6:7(0)
[module.__init+00000126]    %i18:19 = vm.select.i64 %i16(1) ? %i8:9(1) : %i6:7(0)
[module.__init+0000012F]    %i14:15 = vm.add.i64 %i14:15(0), %i18:19(1)
[module.__init+00000136]    %i16 = vm.and.i32 %i16(1), %i17(1)
[module.__init+0000013D]    %r2 = vm.select.ref %i16(1) ? %r2(!hal.device/0x0x5cf05e379950) : %r1(null) -> !hal.device
[module.__init+0000014A]    %i12:13 = vm.add.i64 %i12:13(0), %i8:9(1)
[module.__init+00000151]    vm.br ^00000064()
[module.__init+00000065]    %i16 = vm.cmp.nz.ref %r2(!hal.device/0x0x5cf05e379950)
[module.__init+0000006A]    %i16 = vm.xor.i32 %i16(1), %i0(1)
[module.__init+00000071]    %i17 = vm.cmp.lt.i64.s %i12:13(1), %i10:11(1)
[module.__init+00000078]    %i17 = vm.and.i32 %i16(0), %i17(0)
[module.__init+0000007F]    vm.cond_br %i17(0), ^0000008E(), ^00000158()
[module.__init+00000159]    vm.cond_br %i16(0), ^00000168(), ^000005F0()
[module.__init+000005F1]    %r1 = vm.const.ref.rodata 2  // 0x0x5cf05d77fe88 21b
[module.__init+000005F8]    %r3 = vm.const.ref.rodata 3  // 0x0x5cf05d77feac 13b
[module.__init+000005FF]    %i0, %i8 = vm.call @hal.device.query.i64(%r2(!hal.device/0x0x5cf05e379950), %r1(!vm.buffer/0x0x5cf05d77dce0), %r3(!vm.buffer/0x0x5cf05d77dd08))
[module.__init+00000612]    %i4 = vm.cmp.nz.i64 %i8:9(1)
[module.__init+00000617]    %i0 = vm.select.i32 %i0(1) ? %i4(1) : %i5(0)
[module.__init+00000620]    %i4:5 = vm.select.i64 %i0(1) ? %i6:7(0) : %i2:3(-1)
[module.__init+00000629]    %i0 = vm.cmp.eq.i64 %i4:5(0), %i6:7(0)
[module.__init+00000630]    vm.global.store.ref %r2(!hal.device/0x0x5cf05e379950), .refs[0] : !hal.device
[module.__init+0000063B]    vm.cond_br %i0(1), ^0000064A(), ^0000068C()
[module.__init+0000064B]    %r1 = vm.const.ref.rodata 4  // 0x0x5cf05d780b30 7480b
[module.__init+00000652]    %r0 = vm.call @hal.executable.create(%r2(!hal.device/0x0x5cf05e379950), %i2(4294967295), %r3(!vm.buffer/0x0x5cf05d77dd08), %r1(!vm.buffer/0x0x5cf05d77dd30), %r0(null))
[module.__init+00000668]    vm.global.store.ref %r0(!hal.executable/0x0x5cf05fd6b780), .refs[1] : !hal.executable
[module.__init+00000673]    %r0 = vm.call @module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply()
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+00000000]    <block>
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+00000001]    %i0 = vm.const.i32 13  // 0x0000000D
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+00000008]    %i1 = vm.const.i32 28  // 0x0000001C
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+0000000F]    %i2 = vm.const.i32 2  // 0x00000002
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+00000016]    %r0 = vm.const.ref.zero
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+00000019]    %i3 = vm.const.i32 1  // 0x00000001
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+00000020]    %i4 = vm.const.i32 117133  // 0x0001C98D
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+00000027]    %i5 = vm.const.i32 7  // 0x00000007
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+0000002E]    %i6 = vm.const.i32 3  // 0x00000003
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+00000035]    %i7 = vm.const.i32.zero
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+00000038]    %i8:9 = vm.const.i64 3358432000  // 0x00000000C82D9B00
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+00000043]    %i10:11 = vm.const.i64 28672  // 0x0000000000007000
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+0000004E]    %i12:13 = vm.const.i64 479776000  // 0x000000001C98CD00
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+00000059]    %i14:15 = vm.const.i64.zero
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+0000005C]    %i16:17 = vm.const.i64 -1  // 0xFFFFFFFFFFFFFFFF
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+00000067]    %r1 = vm.global.load.ref .refs[0](!hal.device/0x0x5cf05e379950) : !hal.device
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+00000072]    %r2 = vm.global.load.ref .refs[1](!hal.executable/0x0x5cf05fd6b780) : !hal.executable
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+0000007D]    %r1 = vm.call @hal.command_buffer.create(%r1(!hal.device/0x0x5cf05e379950), %i7(0), %i6(3), %i16(4294967295), %i6(3))
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+00000092]    vm.call.varadic @hal.command_buffer.dispatch(%r1(!hal.command_buffer/0x0x5cf05fd6e5b0), %r2(!hal.executable/0x0x5cf05fd6b780), %i7(0), %i5(7), %i4(117133), %i3(1), %i14(0), %i7(0), %i7(0), %r0(null), %i14(0), %i12(479776000), %i7(0), %i3(1), %r0(null), %i14(0), %i10(28672), %i7(0), %i2(2), %r0(null), %i14(0), %i8(3358432000))
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+000000DC]    vm.call @hal.command_buffer.execution_barrier(%r1(!hal.command_buffer/0x0x5cf05fd6e5b0), %i1(28), %i0(13), %i14(0))
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+000000EE]    vm.call @hal.command_buffer.finalize(%r1(!hal.command_buffer/0x0x5cf05fd6e5b0))
[module.__conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async_memoize_apply+000000FA]    vm.return %r1(!hal.command_buffer/0x0x5cf05fd6e5b0)
[module.__init+0000067E]    vm.global.store.ref %r0(!hal.command_buffer/0x0x5cf05fd6e5b0), .refs[2] : !hal.command_buffer
[module.__init+00000689]    vm.return 
EXEC @conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g+00000000]    <block>
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g+00000001]    %r2 = vm.const.ref.zero
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g+00000004]    %i0 = vm.const.i32 -1  // 0xFFFFFFFF
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g+0000000B]    %i2:3 = vm.const.i64.zero
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g+0000000E]    %i1 = vm.const.i32.zero
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g+00000011]    %r3 = vm.call @hal.devices.get(%i1(0))
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g+0000001E]    %r3 = vm.call @hal.fence.create(%r3(!hal.device/0x0x5cf05e379950), %i2(0))
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g+0000002E]    %r0 = vm.call @module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async(%r0(!hal.buffer_view/0x0x5cf05fd6eeb0), %r1(!hal.buffer_view/0x0x5cf05fda00c0), %r2(null), %r3(!hal.fence/0x0x5cf05fd99610))
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000000]    <block>
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000001]    %i0 = vm.const.i32 48  // 0x00000030
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000008]    %i1 = vm.const.i32 3075  // 0x00000C03
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+0000000F]    %i2 = vm.const.i32 16  // 0x00000010
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000016]    %i3 = vm.const.i32 1  // 0x00000001
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+0000001D]    %i4 = vm.const.i32 553648160  // 0x21000020
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000024]    %i6:7 = vm.const.i64 11  // 0x000000000000000B
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+0000002F]    %i8:9 = vm.const.i64 470  // 0x00000000000001D6
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+0000003A]    %i10:11 = vm.const.i64 725  // 0x00000000000002D5
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000045]    %i12:13 = vm.const.i64 32  // 0x0000000000000020
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000050]    %i14:15 = vm.const.i64 224  // 0x00000000000000E0
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+0000005B]    %i16:17 = vm.const.i64 1  // 0x0000000000000001
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000066]    %i18:19 = vm.const.i64 479776000  // 0x000000001C98CD00
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000071]    %i20:21 = vm.const.i64 28672  // 0x0000000000007000
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+0000007C]    %i22:23 = vm.const.i64 3358432000  // 0x00000000C82D9B00
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000087]    %i24:25 = vm.const.i64.zero
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+0000008A]    %i26:27 = vm.const.i64 -1  // 0xFFFFFFFFFFFFFFFF
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000095]    %r4 = vm.global.load.ref .refs[0](!hal.device/0x0x5cf05e379950) : !hal.device
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+000000A0]    %r5 = vm.global.load.ref .refs[2](!hal.command_buffer/0x0x5cf05fd6e5b0) : !hal.command_buffer
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+000000AB]    %r6 = vm.const.ref.rodata 5  // 0x0x5cf05d77fee0 6b
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+000000B2]    vm.call.varadic @hal.buffer_view.assert(%r0(!hal.buffer_view/0x0x5cf05fd6eeb0), %r6(!vm.buffer/0x0x5cf05d77dd58), %i4(553648160), %i3(1), %i6(11), %i8(470), %i10(725), %i12(32))
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+000000D8]    %r0 = vm.call @hal.buffer_view.buffer(%r0(!hal.buffer_view/0x0x5cf05fd6eeb0))
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+000000E6]    %r7 = vm.call @hal.device.allocator(%r4(!hal.device/0x0x5cf05e379950))
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+000000F4]    vm.call @hal.buffer.assert(%r0(!hal.buffer/0x0x5cf05fd6e6c0), %r6(!vm.buffer/0x0x5cf05d77dd58), %r7(!hal.allocator/0x0x5cf05fd66220), %i18(479776000), %i2(16), %i1(3075))
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+0000010A]    vm.call.varadic @hal.buffer_view.assert(%r1(!hal.buffer_view/0x0x5cf05fda00c0), %r6(!vm.buffer/0x0x5cf05d77dd58), %i4(553648160), %i3(1), %i14(224), %i16(1), %i16(1), %i12(32))
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000130]    %r1 = vm.call @hal.buffer_view.buffer(%r1(!hal.buffer_view/0x0x5cf05fda00c0))
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+0000013E]    vm.call @hal.buffer.assert(%r1(!hal.buffer/0x0x5cf05fd6ef10), %r6(!vm.buffer/0x0x5cf05d77dd58), %r7(!hal.allocator/0x0x5cf05fd66220), %i20(28672), %i2(16), %i1(3075))
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000154]    %r6 = vm.call @hal.fence.create(%r4(!hal.device/0x0x5cf05e379950), %i24(0))
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000164]    %r2 = vm.call @hal.device.queue.alloca(%r4(!hal.device/0x0x5cf05e379950), %i26(4294967295), %r2(null), %r6(!hal.fence/0x0x5cf05fd99ac0), %i24(0), %i0(48), %i1(3075), %i22(3358432000), %i24(0))
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+00000182]    vm.call.varadic @hal.device.queue.execute.indirect(%r4(!hal.device/0x0x5cf05e379950), %i26(4294967295), %r6(!hal.fence/0x0x5cf05fd99ac0), %r3(!hal.fence/0x0x5cf05fd99610), %r5(!hal.command_buffer/0x0x5cf05fd6e5b0), %i24(0), %r0(!hal.buffer/0x0x5cf05fd6e6c0), %i24(0), %i18(479776000), %r1(!hal.buffer/0x0x5cf05fd6ef10), %i24(0), %i20(28672), %r2(!hal.buffer/0x0x5cf05fd99b00), %i24(0), %i22(3358432000))
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+000001BA]    %r0 = vm.call.varadic @hal.buffer_view.create(%r2(!hal.buffer/0x0x5cf05fd99b00), %i24(0), %i22(3358432000), %i4(553648160), %i3(1), %i6(11), %i8(470), %i10(725), %i14(224))
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g$async+000001E6]    vm.return %r0(!hal.buffer_view/0x0x5cf05fd99d60)
[module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g+00000042]    %i0 = vm.call.varadic @hal.fence.await(%i0(4294967295), %i2(0), %r3(!hal.fence/0x0x5cf05fd99610))
iree/runtime/src/iree/hal/drivers/hip/event_semaphore.c:786: ABORTED; the semaphore was aborted; while invoking native function hal.fence.await; while calling import; 
[ 0] bytecode module.conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g:92 repro.mlir:29:5; invoking function 'conv_2d_float32_forward_11x470x725x32_nhwc_224x1x1x32_fhwc_nhwf_1x1s_0x0p_1x1d_1g'
```

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
While IREE generated code itself might have a logical view of grid along x/y/z dimension, the hardware itself does not really care about that. The number of workgroups can just be linearized along (x) or (x, y) dimensions and then the generated code can split out the physical workgroup ID into many different logical workgroup IDs. This avoids hitting some limits of number of workgroups along y/z dimensions (We never really launch workgroups, or should launch, more workgroups than the limit on x dimension).

This logic already exists for handling logical distributions of greater than 3D. Add an option to allow it to constrain physical distribution to 1D/2D.

Fixes #20766

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp [hunk 1]
```diff
@@ -81,6 +81,24 @@ static llvm::cl::opt<bool> clDistributeToWorkgroupsUsingForall(
     llvm::cl::desc("Use scf.forall for distribution to workgroups"),
     llvm::cl::init(false), llvm::cl::Hidden);
 
+static llvm::cl::opt<IREE::Codegen::WorkgroupId>
+    clSetWorkgroupDistributionAlong(
+        "iree-llvmgpu-set-workgroup-distribution-along",
+        llvm::cl::desc(
+            "Contrain the workgroup distribution along grid dimensions"),
```
Comment (benvanik) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp]:
```suggestion
            "Constrain the workgroup distribution along grid dimensions."),
```

File: compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp [hunk 2]
```diff
@@ -81,6 +81,24 @@ static llvm::cl::opt<bool> clDistributeToWorkgroupsUsingForall(
...
+        llvm::cl::values(clEnumValN(IREE::Codegen::WorkgroupId::IdX, "x",
+                                    "Constrain the workgroup distribution to "
+                                    "use only workgroups along x"),
```
Comment (benvanik) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp]:
```suggestion
                                    "use only workgroups along x."),
```

File: compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp [hunk 3]
```diff
@@ -81,6 +81,24 @@ static llvm::cl::opt<bool> clDistributeToWorkgroupsUsingForall(
...
+                         clEnumValN(IREE::Codegen::WorkgroupId::IdY, "y",
+                                    "Constrain the workgroup distribution to "
+                                    "use only workgroups along x and y"),
```
Comment (benvanik) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp]:
```suggestion
                                    "use only workgroups along x and y."),
```

File: compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp [hunk 4]
```diff
@@ -81,6 +81,24 @@ static llvm::cl::opt<bool> clDistributeToWorkgroupsUsingForall(
...
+                         clEnumValN(IREE::Codegen::WorkgroupId::IdZ, "z",
+                                    "Constrain the workgroup distribution to "
+                                    "use only workgroups along x, y and z")),
```
Comment (benvanik) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp]:
```suggestion
                                    "use only workgroups along x, y and z.")),
```

File: compiler/src/iree/compiler/Codegen/Common/Passes.td [hunk 5]
```diff
@@ -265,6 +265,20 @@ def ReconcileTranslationInfoPass
...
       "and set them at the appropriate places in the surrounding HAL ops";
+  let options = [
+    Option<"distributeAlong", "distribute-along",
+           "::mlir::iree_compiler::IREE::Codegen::WorkgroupId",
+           /*default=*/"IREE::Codegen::WorkgroupId::IdZ",
+           "Constrain the workgroup distribution along grid dimensions.",
+           [{
+           ::llvm::cl::values(
+            clEnumValN(IREE::Codegen::WorkgroupId::IdX, "x",
+              "Constrain the workgroup distribution to use only workgroups along x"),
```
Comment (benvanik) [inline compiler/src/iree/compiler/Codegen/Common/Passes.td]:
```suggestion
              "Constrain the workgroup distribution to use only workgroups along x."),
```

File: compiler/src/iree/compiler/Codegen/Common/Passes.td [hunk 6]
```diff
@@ -265,6 +265,20 @@ def ReconcileTranslationInfoPass
...
+            clEnumValN(IREE::Codegen::WorkgroupId::IdY, "y",
+              "Constrain the workgroup distribution to use only workgroups along x and y"),
```
Comment (benvanik) [inline compiler/src/iree/compiler/Codegen/Common/Passes.td]:
```suggestion
              "Constrain the workgroup distribution to use only workgroups along x and y."),
```

File: compiler/src/iree/compiler/Codegen/Common/Passes.td [hunk 7]
```diff
@@ -265,6 +265,20 @@ def ReconcileTranslationInfoPass
...
+            clEnumValN(IREE::Codegen::WorkgroupId::IdZ, "z",
+              "Constrain the workgroup distribution to use only workgroups along x, y and z"))}]>
```
Comment (benvanik) [inline compiler/src/iree/compiler/Codegen/Common/Passes.td]:
```suggestion
              "Constrain the workgroup distribution to use only workgroups along x, y and z."))}]>
```

**Review by benvanik — CHANGES_REQUESTED** [review]

File: compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp (hunk 1 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp]: Is this one resolved?

File: compiler/src/iree/compiler/Codegen/Common/test/reconcile_translation_info_linearize.mlir [hunk 8]
```diff
@@ -0,0 +1,176 @@
...
+  }
+}
+//       DISTRIBUTEX:   hal.executable.export
+//  DISTRIBUTEX-SAME:       %[[ARG0:[a-zA-Z0-9]+]]: !hal.device
+//  DISTRIBUTEX-SAME:       %[[ARG1:[a-zA-Z0-9]+]]: index
+//  DISTRIBUTEX-SAME:       %[[ARG2:[a-zA-Z0-9]+]]: index
+//  DISTRIBUTEX-SAME:       %[[ARG3:[a-zA-Z0-9]+]]: index
+//  DISTRIBUTEX-SAME:       %[[ARG4:[a-zA-Z0-9]+]]: index
+//  DISTRIBUTEX-SAME:       %[[ARG5:[a-zA-Z0-9]+]]: index
+//  DISTRIBUTEX-SAME:       %[[ARG6:[a-zA-Z0-9]+]]: index
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/Common/test/reconcile_translation_info_linearize.mlir]: Here is the trick to remove dup checks: you can add `CHECK-ALL` or `DISTRIBUTE-ALL` to the `--check-prefix`s. Then you can write checks like:

```mlir
// CHECK-ALL:       hal.executable.export
// CHECK-ALL-SAME:    %[[ARG0:[a-zA-Z0-9]+]]: !hal.device
// CHECK-ALL-SAME:    %[[ARG1:[a-zA-Z0-9]+]]: !hal.device

...

// The chunk of X checks
// DISTRIBUTEX: ...

// The chunk of Y checks.
// DISTRIBUTEY: ...

// The chunk of Z checks:
// DISTRIBUTEZ: ...
```

Below is an example in IREE:

https://github.com/iree-org/iree/blob/d1aaeae079bf689eb895a1b6599f0988892fb162/compiler/src/iree/compiler/Codegen/Common/test/decompose_pack_unpack_ops.mlir#L29-L41

File: compiler/src/iree/compiler/Codegen/Common/ReconcileTranslationInfo.cpp [hunk 9]
```diff
@@ -77,7 +78,8 @@ getProcIdsAndNprocs(
     scf::ForallOp forallOp, RewriterBase &builder, Location loc,
     SmallVector<IREE::Codegen::WorkgroupMappingAttr> workgroupMappings,
     SmallVector<OpFoldResult> lowerBounds,
-    SmallVector<OpFoldResult> upperBounds, SmallVector<OpFoldResult> steps) {
+    SmallVector<OpFoldResult> upperBounds, SmallVector<OpFoldResult> steps,
+    IREE::Codegen::WorkgroupId deLinearizeFrom) {
```
Comment (qedawkins) [inline compiler/src/iree/compiler/Codegen/Common/ReconcileTranslationInfo.cpp:82]:
```suggestion
    IREE::Codegen::WorkgroupId delinearizeFrom) {
```

**Review by benvanik — APPROVED** [review]

File: compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp (hunk 1 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp]: yeah missed it.

**Review by qedawkins — APPROVED** [review]

**Review by hanhanW — APPROVED** [review]
