### PR TITLE
[mlir][DispatchCreation] Avoid SSA violation due to consumer fusion while forming dispatches

### LINKED ISSUE #21176: [codegen] Wan2.1 transformer domination issue with aggressive fusion
### What happened?

Compiler input:
[MLIR (wan_transformer_bf16_trunc.mlir)](https://sharkpublic.blob.core.windows.net/sharkpublic/ean/wan/wan_transformer_bf16_trunc.mlir) <-- Truncated from full model
Command:
```
iree-compile --iree-hal-target-backends=rocm --iree-hip-target=gfx942 --iree-execution-model=async-external  wan_transformer_bf16_trunc.mlir  -o wan2_1_transformer_1280x720_bf16_gfx942.vmfb --iree-opt-level=O3
```
Also reproduces with `--iree-opt-level=O0` and `--iree-dispatch-creation-enable-aggressive-fusion=1`
Compiler error:
```
/home/eagarvey/iree-build-debug/tools/iree-compile --iree-hal-target-backends=rocm --iree-hip-target=gfx942 --iree-execution-model=async-external  /home/eagarvey/shark-ai/sharktank/sharktank/models/wan/wan_transformer_bf16.mlir  -o /home/eagarvey/shark-ai/sharktank/sharktank/models/wan/wan2_1_transformer_1280x720_bf16_gfx942.vmfb --iree-opt-level=O3
/home/eagarvey/shark-ai/sharktank/sharktank/models/wan/wan_transformer_bf16.mlir:706:12: error: operand #0 does not dominate this use
    %240 = torch.aten.layer_norm %238, %239, %24, %25, %float9.999990e-07_332, %true_333 : !torch.vtensor<[1,75600,5120],bf16>, !torch.list<int>, !torch.vtensor<[5120],bf16>, !torch.vtensor<[5120],bf16>, !torch.float, !torch.bool -> !torch.vtensor<[1,75600,5120],bf16>
           ^
/home/eagarvey/shark-ai/sharktank/sharktank/models/wan/wan_transformer_bf16.mlir:706:12: note: see current operation: %153 = "tensor.expand_shape"(%155#0) <{reassociation = [[0], [1, 2]], static_output_shape = array<i64: 75600, 1, 5120>}> : (tensor<75600x5120xbf16>) -> tensor<75600x1x5120xbf16>
/home/eagarvey/shark-ai/sharktank/sharktank/models/wan/wan_transformer_bf16.mlir:706:12: note: operand defined here (op in the same block)
```
Output with `--mlir-print-ir-after-all`: [Azure -  wan_dom_fail_ir_after_all.txt](https://sharkpublic.blob.core.windows.net/sharkpublic/ean/wan/wan_dom_fail_ir_after_all.txt)

### Steps to reproduce your issue

- Download source IR
- Run compile command

### What component(s) does this issue relate to?

Compiler

### Version information

6c6fa9578acb3955f627e1c784e441de9a30ef1c (built in debug mode)

### Additional context

Without aggressive fusion, we encounter a semaphore abort at runtime tracked by https://github.com/iree-org/iree/issues/21155 -- I've found no evidence that these are related in cause.

The export of this wan model has yet to be fully validated through IREE, so this shouldn't be considered a regression.

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
Consumer fusion would create illegal dispatches in presence of diamond fusion patterns when one of the operations arent fused into dispatch. For example

```
%producer = ...
%0 = "non_fused_op"(%producer)
%1 = "fused_op"(%producer, %0)
```

Moving `"fused_op"` into the same dispatch as `%producer` is a SSA violation. Avoid this fusion.

Fixes #21176

### CODE REVIEW

File: compiler/src/iree/compiler/DispatchCreation/FoldUnitExtentDims.cpp [hunk 1]
```diff
@@ -259,8 +259,10 @@ void FoldUnitExtentDimsPass::runOnOperation() {
 
   RewritePatternSet foldUnitDimsPatterns(context);
   populatefoldUnitDimsPatterns(foldUnitDimsPatterns);
-  if (failed(
-          applyPatternsGreedily(moduleOp, std::move(foldUnitDimsPatterns)))) {
+  GreedyRewriteConfig rewriterConfig;
+  rewriterConfig.setMaxIterations(GreedyRewriteConfig::kNoLimit);
+  if (failed(applyPatternsGreedily(moduleOp, std::move(foldUnitDimsPatterns),
+                                   rewriterConfig))) {
```
Comment (IanWood1) [inline compiler/src/iree/compiler/DispatchCreation/FoldUnitExtentDims.cpp:265]: Is there a reason this was changed?

File: compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp [hunk 2]
```diff
@@ -993,6 +1028,13 @@ createFusionGroups(TensorDimTrackingRewriter &rewriter,
...
       }
 
+      // Check to see if it is still legal to fuse into consumer.
+      if (!checkConsumerFusionLegality(regionOp, consumer, dominanceInfo)) {
+        // Leave the consumer as is, it will get put into its own dispatch
+        // later.
+        continue;
+      }
+
       if (failed(moveOperandDefs(rewriter, consumer, regionOp, dominanceInfo,
```
Comment (IanWood1) [inline compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp:996]: I think this might be a bug with `moveOperandDefs` since it also should be checking that the movement is legal. Using the PR description example, it **_should_** see that `non_fused_op` can't be moved before the region and return failure. 

The upstream function you added `mlir::moveOperationDependencies` does the same thing (and hopefully is bug free).

File: compiler/src/iree/compiler/DispatchCreation/FoldUnitExtentDims.cpp (hunk 1 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/DispatchCreation/FoldUnitExtentDims.cpp:265]: I thought the unit dims should be dropped and it wasnt, so I increased the threshold. It wasnt the issue, but left it in there cause it was probably a good thing to do anyway

File: compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp (hunk 2 above)
Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp:996]: No it is not that issue.

We have

```
%producer = linalg.generic
%root = linalg.generic ... ins(%producer ...)
%expand_shape = tensor.expand_shape %producer
%consumer = linalg.generic ... ins(%consumer, %expand_shape, ...)
```

So the only way all of this can fit in a dispatch is to move the `expand_shape` into the dispatch as well, but that is not something codegen can handle well (at least for now). So we need to split up the dispatch, but it is very hard/disruptive to form the right fusion groups to start with. So the only alternative here is to force break the dispatch while actually creating the dispatch.

File: compiler/src/iree/compiler/DispatchCreation/test/form_dispatch_regions.mlir [hunk 3]
```diff
@@ -1331,3 +1331,53 @@ util.func @attention_rope_fusion(%arg0: tensor<10x20x30x50xbf16>,
 //  CHECK-SAME:         ins(%[[Q]], %[[K]], %[[V]]
 //       CHECK:     flow.return %[[ATTENTION]]
 //       CHECK:   util.return %[[DISPATCH]]
+
+// -----
+
+util.func public @avoid_illegal_consumer_fusion(%arg0: tensor<75600x5120xf32>) -> tensor<75600x1x5120xbf16> {
```
Comment (hanhanW) [inline compiler/src/iree/compiler/DispatchCreation/test/form_dispatch_regions.mlir]: It may be easier if you put `diamond` to the func name or the ASCII art to a comment. E.g., 

```
    [1]     [2]
    /  \     |
   /    \   [3]
 [E]   [4] <-'
   \   /
    [6]
```

**Review by IanWood1 — APPROVED** [review]

**Review by hanhanW — APPROVED** [review]
