### PR TITLE
Unbreak the `byo_llvm.sh` build with `iree_bitcode_library`.

### LINKED ISSUE #13957: CPU ukernel breaks byo LLVM builds
### What happened?

[runtime/src/iree/builtins/ukernel/arch/x86_64/common_x86_64.h](https://github.com/openxla/iree/blob/main/runtime/src/iree/builtins/ukernel/arch/x86_64/common_x86_64.h) relies on `immintrin.h` which is included from Clang via `set(_BUILTIN_HEADERS_PATH "${IREE_BINARY_DIR}/llvm-project/lib/clang/${_CLANG_VERSION_MAJOR}/include/")` in [build_tools/cmake/iree_bitcode_library.cmake](https://github.com/openxla/iree/blob/main/build_tools/cmake/iree_bitcode_library.cmake).

However, when building IREE using [build_tools/scripts/byo_llvm.sh](https://github.com/openxla/iree/blob/main/build_tools/scripts/byo_llvm.sh), the system's LLVM is used instead of being built, so `${IREE_BINARY_DIR}` does not contain `llvm-project`.

Trying to build IREE using the `byo_llvm.sh` breaks due to this issue. To fix, check if `IREE_BUILD_BUNDLED_LLVM=OFF` and look for the installed Clang headers.

### Steps to reproduce your issue

_No response_

### What component(s) does this issue relate to?

Runtime

### Version information

686860c6ba561401f8df1b86f193723470703954

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bjacob**
The byo-llvm build is broken by the way `iree_bitcode_library` assumes it's dealing with our own bundled `clang` (#13957). This is an attempt to fix that. Specifically, this implements the idea in https://github.com/openxla/iree/issues/13957#issuecomment-1579175544 .

So `iree_bitcode_library` is changed to take `clang`, Clang builtin headers, and `llvm-link` paths from externally defined variables.

`iree_llvm.cmake` is updated to set these variables appropriately, in both the bundled and the installed cases.

`byo_llvm.sh` is updated to pass a `LLVM_INSTALL_DIR` to `iree_llvm.cmake`.

Fixes #13957 .

### CODE REVIEW

File: build_tools/scripts/byo_llvm.sh [hunk 1]
```diff
@@ -77,6 +77,7 @@ do_build_llvm() {
   cmake_options="${cmake_options} -DLLVM_INSTALL_UTILS=ON"
   cmake_options="${cmake_options} -DCMAKE_BUILD_TYPE=Release"
   cmake_options="${cmake_options} -DLLVM_ENABLE_ASSERTIONS=ON"
+  cmake_options="${cmake_options} -DLLVM_TARGETS_TO_BUILD=X86;ARM;AArch64;RISCV"
```
Comment (ScottTodd) [inline build_tools/scripts/byo_llvm.sh]: This is already listed above:
`cmake_options="-DLLVM_ENABLE_PROJECTS='${enable_projects}' -DLLVM_TARGETS_TO_BUILD='${targets_to_build}'"`

(and the script should not be overriding what the user specifies)

Comment (bjacob) [reply build_tools/scripts/byo_llvm.sh]: d'oh! thanks.

File: build_tools/cmake/iree_llvm.cmake [hunk 2]
```diff
@@ -93,6 +94,11 @@ macro(iree_llvm_configure_installed)
   if(NOT LLVM_EXTERNAL_LIT)
     set(LLVM_EXTERNAL_LIT "${IREE_SOURCE_DIR}/third_party/llvm-project/llvm/utils/lit/lit.py")
   endif()
+
+  set(IREE_LLVM_LINK_BINARY "${LLVM_INSTALL_DIR}/llvm/bin/llvm-link")
+  set(IREE_CLANG_BINARY "${LLVM_INSTALL_DIR}/llvm/bin/clang")
```
Comment (ScottTodd) [inline build_tools/cmake/iree_llvm.cmake]: These might want to append `CMAKE_EXECUTABLE_SUFFIX` for Windows compatibility... I'm not sure.

File: build_tools/cmake/iree_llvm.cmake [hunk 3]
```diff
@@ -82,9 +86,6 @@ macro(iree_llvm_configure_installed)
   list(APPEND CMAKE_MODULE_PATH "${LLD_CMAKE_DIR}")
   include_directories(${LLD_INCLUDE_DIRS})
 
-  find_package(Clang REQUIRED)
-  list(APPEND CMAKE_MODULE_PATH "${CLANG_CMAKE_DIR}")
-
```
Comment (bjacob) [inline build_tools/cmake/iree_llvm.cmake:87]: I had to remove those two lines to get this to run on my machine. It was failing at FindClang like pasted there: https://github.com/openxla/iree/issues/13957#issuecomment-1579116706

The code below didn't seem to be making use of that, so I thought we might just delete these lines (?!). Caveat reviewer!

File: build_tools/scripts/byo_llvm.sh [hunk 4]
```diff
@@ -69,7 +69,7 @@ do_build_llvm() {
   echo "*********************** BUILDING LLVM *********************************"
   main_build_dir="${LLVM_BUILD_DIR}/llvm"
   main_install_dir="${LLVM_INSTALL_DIR}/llvm"
-  targets_to_build="${LLVM_TARGETS_TO_BUILD:-X86}"
+  targets_to_build="${LLVM_TARGETS_TO_BUILD:-X86;ARM;AArch64;RISCV}"
```
Comment (ScottTodd) [inline build_tools/scripts/byo_llvm.sh]: Might want to keep this defaulting to just `X86`. Anyone using this script likely has special requirements anyways, so they'll want to just enable what they use.

Comment (bjacob) [reply build_tools/scripts/byo_llvm.sh]: OK. I realize now, that the need for this is only because of a "bug" in the ukernels bitcode setup: it only checks whether `IREE_TARGET_BACKEND_LLVM_CPU` and then it tries to build the bitcode for ALL architectures. It needs to act more precisely based on the enabled LLVM architecture backends. So I'll do your suggestion here now and separately I'll send a PR to fix that.

File: build_tools/cmake/iree_llvm.cmake (hunk 2 above)
Comment (bjacob) [reply build_tools/cmake/iree_llvm.cmake]: I think you're right!

**Review by ScottTodd — APPROVED** [review]

**Comment by JackWolfard** [comment]
LGTM. This fixes the issue I was having.
