### PR TITLE
Avoid linking with MUSL imported functions if `--iree-llvmcpu-link-embedded` is `false`.

### LINKED ISSUE #14208: iree-compile generates empty function for fmaf (RISCV32)
### What happened?

@hcindyl and myself are running a small model that consists of a single softmax layer (1x2xi8), on an rv32im core. At execution time, we noticed that the output doesn't match what's expected. I traced through the execution, and at some point, there's a call to `fmodf` that ends up returning NaN, and then math collapses :)

In the intermediate assembly generated by iree-compile, I do not see any call sites for `fmodf`, but do see many calls to `fmaf` -- and this is also reflected in the dumped IR: `fma` is what we expect, not `fmod`.

In the intermediate assembly, there exists a function definition for `fmaf` with no body, followed by a definition of `fmodf` with a body:

```
	.section	.text.fmaf,"ax",@progbits
	.p2align	2
	.type	fmaf,@function
fmaf:
.Lfunc_begin23:
	.cfi_startproc
.Lfunc_end23:
	.size	fmaf, .Lfunc_end23-fmaf
	.cfi_endproc

	.section	.text.fmodf,"ax",@progbits
	.p2align	2
	.type	fmodf,@function
fmodf:
.Lfunc_begin24:
	.cfi_startproc
	addi	sp, sp, -16
	.cfi_def_cfa_offset 16
	sw	ra, 12(sp)
	sw	s0, 8(sp)
```

It seems like this empty `fmaf` method probably shouldn't exist, and a call out to libm woud be appropriate instead? Any idea what causes this empty method to be generated?

### Steps to reproduce your issue

`iree-compile --mlir-print-ir-after-all -iree-llvmcpu-target-triple=riscv32-pc-linux-elf -iree-llvmcpu-target-cpu=generic-rv32 -iree-llvmcpu-target-cpu-features="+m" -iree-llvmcpu-target-abi=ilp32 person_detection_c_module_static.mlir --iree-llvmcpu-keep-linker-artifacts --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-link-static --iree-llvmcpu-link-embedded=false --iree-hal-dump-executable-intermediates-to=/tmp/iree -o /dev/null`

The MLIR file is available here: https://github.com/atvrager/person_detection_c_module/blob/main/person_detection_c_module_static.mlir

In the same repo (https://github.com/atvrager/person_detection_c_module), I've also included the intermediate assembly, and output from my above iree-compile execution.

### What component(s) does this issue relate to?

Compiler

### Version information

IREE (https://openxla.github.io/iree):
  IREE compiler version (unknown)
  LLVM version 17.0.0git
  Optimized build

cd0d1f11713e48c2b17945520602e7ea9f6498c9

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
Fixes #14208

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
@hcindyl can you check if this PR fixes the Nan issue in #14208

File: compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp [hunk 1]
```diff
@@ -444,17 +445,20 @@ class LLVMCPUTargetBackend final : public TargetBackend {
...
-      return mlir::emitError(variantOp.getLoc())
-             << "failed linking in builtin library for target triple '"
-             << targetTriple.str() << "'";
+    if (options_.linkEmbedded) {
+      // Link musl last and pull in all of it - this is sad but LLVM will take
+      // IR
+      // intrinsics and generate calls out to libc during code generation and we
+      // have no control over that - if we don't provide the symbols here then
+      // linking with ld will fail.
+      if (failed(linkBitcodeModule(
```
Comment (ScottTodd) [inline compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp]: Do we actually want to condition linking bitcode on this? I was under the impression (back from https://github.com/openxla/iree/pull/7721 and others) that we wanted to always link musl / the builtin library, to avoid any system dependencies (so artifacts are more portable and don't suffer from performance penalties from calling out to the system).

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp]: yes, this isnt changing the default. `options_.linkEmbedded` is by default `true`. When set to `false` we avoid linking musl generated files. This is for cases where you generate a library from IREE and link it with `libm`. In those cases we dont need the implementation from musl.

Comment (ScottTodd) [reply compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp]: Can we safely assume that system linking has access to libm? (LLVM appears to assume libm's existence in it's lowering, but I thought we wanted to more portable than that, even with the system linking mode)

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp]: Well, I don't know how important that support point is. We can say you don't need libm and we use musl to get the implementation. Or we say we won't use musl, but you need a libm. 
First though, checking if this fixes the problem. It is really a Riscv backend issue that we are trying to work around .

**Comment by hcindyl** [comment]
> @hcindyl can you check if this PR fixes the Nan issue in #14208

Test with the softmax op with soft_fp. At least now we have a valid `fmaf` implementation
https://gist.github.com/hcindyl/0e9e65b7ef7df03fb7e2a69920f2909d

**Comment by MaheshRavishankar** [comment]
So the issue is fixed with this?

**Comment by hcindyl** [comment]
> So the issue is fixed with this?

Seems to be going toward the right direction. Also, if `+f` is enabled the codegen resumed to use inline float ops to implement `softmax`. I think we are relatively safe to merge the code, if CI is also happy.

**Comment by MaheshRavishankar** [comment]
> > So the issue is fixed with this?
> 
> Seems to be going toward the right direction. Also, if `+f` is enabled the codegen resumed to use inline float ops to implement `softmax`. I think we are relatively safe to merge the code, if CI is also happy.

All this is pointing to gaps in LLVM risc-v backend

File: compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp [hunk 2]
```diff
@@ -444,17 +445,20 @@ class LLVMCPUTargetBackend final : public TargetBackend {
...
-            loadMuslBitcode(targetMachine.get(), context)))) {
-      return mlir::emitError(variantOp.getLoc())
-             << "failed linking in builtin library for target triple '"
-             << targetTriple.str() << "'";
+    if (options_.linkEmbedded) {
+      // Link musl last and pull in all of it - this is sad but LLVM will take
+      // IR
+      // intrinsics and generate calls out to libc during code generation and we
+      // have no control over that - if we don't provide the symbols here then
+      // linking with ld will fail.
```
Comment (ScottTodd) [inline compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp]: Can you re-flow this comment block? (nesting it one level pushed a line over the limit and clang-format doesn't re-flow on its own)
```suggestion
      // Link musl last and pull in all of it - this is sad but LLVM will take
      // IR intrinsics and generate calls out to libc during code generation
      // and we have no control over that - if we don't provide the symbols
      // here then linking with ld will fail.
```

File: compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp (hunk 1 above)
Comment (ScottTodd) [reply compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp]: Okay, I don't fully understand all the implications for each platform / configuration, so this might be fine... could check with Ben when he's around.

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp]: Agreed. I will wait for @benvanik to see if this is OK.

**Comment by MaheshRavishankar** [comment]
@benvanik could you look at this PR?

**Review by benvanik — APPROVED** [review]
lgtm!

**Review by hcindyl — APPROVED** [review]
