### PR TITLE
[DispatchCreation] Fix trailing unit dims case for collapse of expand folding

### LINKED ISSUE #21648: [DispatchCreation] FoldUnitDims failure for leading+trailing expand
### What happened?

Copying from a slack thread:

repro gist: https://gist.github.com/oyazdanb/9ed815a7cb8f5e2786f07d17b6c78490
iree-opt --run-reproducer repro.mlir

error:
```
iree-compile  \
/home/sonbol/open-weight-model-pre-release/gpt-oss-20b/shark_files_bfp16/gpt-oss-20b_model.mlir  \
--iree-hal-target-device=hip  \
--iree-hip-target=gfx942 \
 -o /home/sonbol/open-weight-model-pre-release/gpt-oss-20b/shark_files_bfp16/gpt-oss-20b_model.vmfb \
--mlir-pass-pipeline-crash-reproducer=repro.mlir \
--mlir-pass-pipeline-local-reproducer \
--mlir-disable-threading
/home/sonbol/open-weight-model-pre-release/gpt-oss-20b/shark_files_bfp16/gpt-oss-20b_model.mlir:32026:12: error: 'tensor.expand_shape' op expected collapsed rank (2) to equal the number of reassociation maps (1).
    %887 = torch.aten.view %885, %886 : !torch.vtensor<[1,23040,1],bf16>, !torch.list<int> -> !torch.vtensor<[4,5760,1,1],bf16>
           ^
/home/sonbol/open-weight-model-pre-release/gpt-oss-20b/shark_files_bfp16/gpt-oss-20b_model.mlir:32026:12: note: see current operation: %811 = "tensor.expand_shape"(%810) <{reassociation = [[0, 1]], static_output_shape = array<i64: 4, 5760>}> : (tensor<23040x1xbf16>) -> tensor<4x5760xbf16>
/home/sonbol/open-weight-model-pre-release/gpt-oss-20b/shark_files_bfp16/gpt-oss-20b_model.mlir:1:1: error: Failures have been detected while processing an MLIR pass pipeline
module @module {
^
/home/sonbol/open-weight-model-pre-release/gpt-oss-20b/shark_files_bfp16/gpt-oss-20b_model.mlir:1:1: note: Pipeline failed while executing `FoldUnitExtentDimsPass` on 'builtin.module' operation: @module: reproducer generated at `repro.mlir`
```

It seems pretty clear to me from the error that the new expand op is expecting the collapsed shape to be without the trailing unit dim, so I expect there is some faulty logic in the pattern that drops unit dims in the case when you have leading and trailing unit dims. (Seems weird that we'd hit this otherwise). 

### What component(s) does this issue relate to?

_No response_

### Version information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dan-garvey**
Previous logic only prevented collapsing all unit dims in a reassociation element if the first element of the reassociation represented a unit dim in the input.

i.e. it worked for cases like 1x1x44x5 -> 1x44x5
but failed for 5x44x1x1 -> 5x44x1

### CODE REVIEW

**Review by IanWood1 — CHANGES_REQUESTED** [review]
The problem seems to be that if a unit dim gets expanded the pattern will try to drop all of the unit dims. I think all you need here is to change L180-L185 (couldn't attach the comment to that since it wasn't modified by the PR) to not drop the first expanded dim if the src shape contains a unit dim. I.e.

```c++
for (const auto &[inDim, indices] : llvm::enumerate(expandReassoc)) {
  if (indices.size() == 1 || srcShape[inDim] == 1) {
    toDrop.erase(indices[0]);
  }
}
```

**Comment by dan-garvey** [comment]
by srcShape do you mean the shape that is the input to the expand op?

**Comment by IanWood1** [comment]
> by srcShape do you mean the shape that is the input to the expand op?

yep

**Comment by dan-garvey** [comment]
Ok, the problem with the proposed solution is made clearer by this expand shape:
```
 %expanded = tensor.expand_shape %arg0 [[0, 1, 2], [3, 4]] output_shape [4, %arg1, 1, 1, 1] : tensor<?x1xf16> into tensor<4x?x1x1x1xf16>
```
In this case, we want this op to return `4x?x1xf16`. `toDrop` after being populated will have `2, 3`.  In our removal check, `inDim =1`, `srcShape[inDim] = 1`, so we remove `3` from `toDrop`, leaving us with `4x?x1x1`. This would be okay if we cleaned it up recursively, but on future runs of the pass we end up removing `2` from `toDrop` using the same logic.

**Comment by IanWood1** [comment]
> Ok, the problem with the proposed solution is made clearer by this expand shape:
> 
> ```
>  %expanded = tensor.expand_shape %arg0 [[0, 1, 2], [3, 4]] output_shape [4, %arg1, 1, 1, 1] : tensor<?x1xf16> into tensor<4x?x1x1x1xf16>
> ```
> 
> In this case, we want this op to return `4x?x1xf16`. `toDrop` after being populated will have `2, 3`. In our removal check, `inDim =1`, `srcShape[inDim] = 1`, so we remove `3` from `toDrop`, leaving us with `4x?x1x1`. This would be okay if we cleaned it up recursively, but on future runs of the pass we end up removing `2` from `toDrop` using the same logic.

I think I understand. Your change here fixes the pattern but it doesn't directly fix the broken part. L153-178 inserts dimensions into `toDrop` based on the `tensor.collapse_shape` and ensures that we don't drop all the dims in a reassociation. L180-L185 ___should___ be removing dimensions from `toDrop` based on the producing `tensor.expand_shape` to make sure we don't drop all of the dims in a single reassociation from the expand. However, `indices.size() == 1` isn't enough to make this true.

I thought the code snip-it would fix the problem. I remember it working locally but maybe there were other changes I forgot to paste here. 

Here is a branch that should actually work and does it with a single application of the pattern: https://github.com/iree-org/iree/compare/main...IanWood1:iree:fix_trailing_unit_dims_changes?expand=1

**Comment by dan-garvey** [comment]
the commit history is a bit ugly, but I wanted to preserve that you contributed the all_of change. I also removed a condition that I think is irrelevant given the update you made

File: compiler/src/iree/compiler/DispatchCreation/FoldUnitExtentDims.cpp [hunk 1]
```diff
@@ -86,12 +86,6 @@ struct DropUnitDimsFromCollapseOfExpand
         if (indices.size() == 1 || interShape[inDim] != 1) {
           continue;
         }
-
-        // If we are collapsing multiple unit dims together, at least 1 must be
-        // kept (prefer the first).
-        if (outShape[outDim] == 1 && innerIdx != 0) {
-          continue;
-        }
```
Comment (IanWood1) [inline compiler/src/iree/compiler/DispatchCreation/FoldUnitExtentDims.cpp]: I think this is still needed. Without it this example will fail (looks like I didn't add a good test to cover this case):

```mlir
util.func @test(%arg0: tensor<1x23040xbf16>) -> tensor<4x5760x1xbf16> {
  %expanded = tensor.expand_shape %arg0 [[0], [1, 2, 3, 4]] output_shape [1, 4, 5760, 1, 1] : tensor<1x23040xbf16> into tensor<1x4x5760x1x1xbf16>
  %collapsed = tensor.collapse_shape %expanded [[0, 1], [2], [3, 4]] : tensor<1x4x5760x1x1xbf16> into tensor<4x5760x1xbf16>
  util.return %collapsed : tensor<4x5760x1xbf16>
}
```

Comment (dan-garvey) [reply compiler/src/iree/compiler/DispatchCreation/FoldUnitExtentDims.cpp]: Good catch. I really could not reason about this pattern without inspecting the intermediate values. 

I simplified the logic to `innerIdx == 0` so that the pattern wouldn't have to run multiple times in the case where there are >2 unit dims being collapsed.

**Review by IanWood1 — APPROVED** [review]
