### PR TITLE
[rv32] Expand `arith.mulsi_extended` before going to LLVM

### LINKED ISSUE #12239: RV32 code size regression from #11576 LLVM integrate on 2022-12-16
Suspected LLVM integration: #11576

https://perf.iree.dev/serie?IREE?PersonDetect%20%5Bint8%5D%20(TFLite)%20CPU-RV32-Generic%20full-inference%2Cdefault-flags%20%5Bcompilation%3Amodule%3Acomponent-size%3Atotal-dispatch-size%5D

Direct local repro is nontrivial due to MLIR IR format change since that time, requires an `iree-import-tflite` from that timeframe. To make it easier, attaching here the already imported file. 
[person_detect.zip](https://github.com/iree-org/iree/files/10758622/person_detect.zip)

```
cmake --build . --target iree-compile && tools/iree-compile --iree-hal-target-backends=llvm-cpu --iree-input-type=tosa --iree-llvm-target-abi=ilp32 --iree-llvm-target-cpu-features=+m,+a,+f,+zvl512b,+zve32x --iree-llvm-target-cpu=generic-rv32 --iree-llvm-target-triple=riscv32-pc-linux-elf --riscv-v-fixed-length-vector-lmul-max=8 --riscv-v-vector-bits-min=512 benchmark_suites/TFLite/person_detect.tflite.mlir -o /tmp/a.vmfb --iree-llvm-keep-linker-artifacts 2>&1 | grep -o '/.*\.so' | xargs size -A | grep '^\.text' | awk '{print $2}'
```

Prints:

at IREE commit (and `git submodule update`) | value
--- | ---
[79b90d32d1723b0650b33bc5584dccb4828e5421](https://github.com/iree-org/iree/commit/79b90d32d1723b0650b33bc5584dccb4828e5421) | 871912
[7b4688272e40e939dc02053c7178b111a21eadd5](https://github.com/iree-org/iree/commit/7b4688272e40e939dc02053c7178b111a21eadd5) | 180752

### PR DESCRIPTION
**Pull request by kuhar**
This enables `tosa.apply_scale` to be vectorized, and thus fixes a code size regression.

Fixes: https://github.com/iree-org/iree/issues/12239

### CODE REVIEW

**Comment by kuhar** [comment]
I need to write some tests

**Review by dcaballe — APPROVED** [review]
Thanks for fixing this. LGTM (+tests)

**Review by bjacob — APPROVED** [review]
Verified to actually fix the issue: https://github.com/iree-org/iree/issues/12239#issuecomment-1433726842

File: compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp [hunk 1]
```diff
@@ -358,6 +361,47 @@ struct RewriteExternCallOpToDynamicImportCallOp
   LLVMTypeConverter &typeConverter;
 };
 
+// The 32-bit RISC-V backend is very sensitive to how extended multiplication is
+// lowered. This pattern lowers `arith.mulsi_extended` before going to the LLVM
+// dialect, in a way compatible with that backend, so that we break down any
+// 64-bit constants that would otherwise prevent the code from being vectorized.
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp]: style nit: Use `///`

File: compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp [hunk 2]
```diff
@@ -358,6 +361,47 @@ struct RewriteExternCallOpToDynamicImportCallOp
...
+class ExpandMulSIExtended : public OpRewritePattern<arith::MulSIExtendedOp> {
+ public:
+  using OpRewritePattern<arith::MulSIExtendedOp>::OpRewritePattern;
+
+  LogicalResult matchAndRewrite(arith::MulSIExtendedOp op,
+                                PatternRewriter &rewriter) const override {
+    Type resultType = op.getLhs().getType();
+    if (getElementTypeOrSelf(resultType).getIntOrFloatBitWidth() != 32)
+      return failure();
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp]: IREE style nit: we wrap single statements with braces in IREE.

```suggestion
    if (getElementTypeOrSelf(resultType).getIntOrFloatBitWidth() != 32) {
      return failure();
    }
```

File: compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp [hunk 3]
```diff
@@ -358,6 +361,47 @@ struct RewriteExternCallOpToDynamicImportCallOp
...
+
+    Location loc = op->getLoc();
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp]: [optional] can we use `op.getLoc()` instead? From my review experience, we use `->` when it is a `Operation *` type or we want to use some methods in `Operation *`.

File: compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp [hunk 4]
```diff
@@ -465,6 +509,11 @@ void ConvertToLLVMPass::runOnOperation() {
   }
   tosa::populateTosaRescaleToArithConversionPatterns(&patterns, use32BitImpl);
 
+  // Make sure we expand any `arith.mulsi_extended` before going to the LLVM
+  // dialect.
+  if (use32BitImpl)
+    patterns.add<ExpandMulSIExtended>(patterns.getContext(), /*benefit=*/1024);
+
```
Comment (hanhanW) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp]: IREE style nit: wrap with braces.

```suggestion
  if (use32BitImpl) {
    patterns.add<ExpandMulSIExtended>(patterns.getContext(), /*benefit=*/1024);
  }
```

**Review by hanhanW — APPROVED** [review]
Thanks, just few style nits!
