### PR TITLE
[LLVMCPU] Unify conv/pooling kernel configs for different layouts.

### LINKED ISSUE #13586: Failure compiling PyTorch ResNet50 on x86_64
### What happened?

Error when compiling PyTorch ResNet50 on x86_64:

```
iree-compile --output-format=vm-bytecode --iree-hal-target-backends=llvm-cpu --iree-input-type=none --iree-llvmcpu-target-triple=x86_64-unknown-linux-gnu --iree-llvmcpu-target-cpu=cascadelake Resnet50PTBatch1.mlir -o module.vmfb

2023-05-12T01:53:39.8457500Z iree-compile: /work/third_party/llvm-project/llvm/include/llvm/ADT/SmallVector.h:294: llvm::SmallVectorTemplateCommon::reference llvm::SmallVectorTemplateCommon<long, void>::operator[](llvm::SmallVectorTemplateCommon::size_type) [T = long]: Assertion `idx < size()' failed.
```

Full error: [Resnet50PTBatch1_error.txt](https://github.com/openxla/iree/files/11458890/Resnet50PTBatch1_error.txt)

### Steps to reproduce your issue

1. Download https://storage.googleapis.com/iree-model-artifacts/pytorch/torch_models_20230401.795_1680469670/RESNET50/batch_1/linalg.mlir

2. Compile:
```
iree-compile --output-format=vm-bytecode \
    --iree-hal-target-backends=llvm-cpu --iree-input-type=none \
    --iree-llvmcpu-target-triple=x86_64-unknown-linux-gnu \
    --iree-llvmcpu-target-cpu=cascadelake linalg.mlir -o module.vmfb
```

### What component(s) does this issue relate to?

Compiler

### Version information

e85a7c82792fcb4083154879e206cf765a74d7e6

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hanhanW**
According to previous commits and comments, we aim to use the same tile sizes for conv and pooling ops. The tiling sizes should be shuffled accordingly for different layouts. This revision changes NCHW format ops to take NHWC configs and apply permutation on it.

Also fixes bugs in verifyConvTileAndDecomposeExpertConfig. Some NCHW ops followed NHWC checks which were not correct.

Fixes https://github.com/openxla/iree/issues/13586

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 1]
```diff
@@ -1634,148 +1660,75 @@ static LogicalResult setConvRootConfig(func::FuncOp entryPointFn,
...
-        .Case<linalg::PoolingNhwcSumOp, linalg::PoolingNhwcMaxOp,
-              linalg::PoolingNhwcMaxUnsignedOp, linalg::PoolingNhwcMinOp,
-              linalg::PoolingNhwcMinUnsignedOp>([&](auto op) {
-          tileSizes = {1, 1, vectorSize, vectorSize, 1, vectorSize};
-        })
-        .Case<linalg::DepthwiseConv2DNhwcHwcOp>([&](auto op) {
-          tileSizes = {1, 1, vectorSize, vectorSize, 1, vectorSize};
-        })
-        .Default([&](Operation *op) { llvm_unreachable("unsupported conv"); });
+    if (is2DConvOp(op)) return {1, 1, 8, vectorSize * 2, 1, 1, 8};
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:1674]: Nit: I think x86 and risc-v are same for now. Maybe we can combine for now.

**Review by MaheshRavishankar — APPROVED** [review]
Nice cleanup. Looks good to me!

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp (hunk 1 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:1674]: I thought they are the same, but then I found that the answer is no. The depthwise conv configurations is different. One is `{1, 1, 8, vectorSize * 2, 1, 3}` and the other is `{1, 1, 8, vectorSize, 1, 3}`. We can make them the same after running benchmarks, maybe. That should be a different PR to me.

Comment (MaheshRavishankar) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:1674]: Sounds good!

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 2]
```diff
@@ -1570,22 +1571,47 @@ static LogicalResult setRootConfig(
...
+
+static bool is2DPoolingOp(Operation *op) {
+  return isa<linalg::PoolingNhwcSumOp, linalg::PoolingNhwcMaxOp,
+             linalg::PoolingNhwcMaxUnsignedOp, linalg::PoolingNhwcMinOp,
+             linalg::PoolingNhwcMinUnsignedOp, linalg::PoolingNchwSumOp,
+             linalg::PoolingNchwMaxOp>(op);
+}
+
+/// Helper enum to represent conv2d input traversal order.
+enum class Conv2DOpOrder {
```
Comment (dcaballe) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: -> DimOrder?

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp (hunk 1 above)
Comment (dcaballe) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:1674]: I might have changed the sizes to reduce register pressure/unrolling for RISC-V

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp [hunk 3]
```diff
@@ -1634,148 +1660,74 @@ static LogicalResult setConvRootConfig(func::FuncOp entryPointFn,
...
-                                   linalg::PoolingNchwSumOp convOp) {
-  return setConvNchwRootConfigImpl(entryPointFn, convOp);
-}
+      getNhwcConvWorkgroupSizes(entryPointFn, convOp, vectorSize);
 
-static LogicalResult setRootConfig(func::FuncOp entryPointFn,
-                                   linalg::PoolingNchwMaxOp convOp) {
-  return setConvNchwRootConfigImpl(entryPointFn, convOp);
-}
+  Conv2DOpOrder order = getConv2DOpOrder(convOp);
```
Comment (dcaballe) [inline compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: Good to add a comment about how we compute the tile sizes below

**Review by dcaballe — APPROVED** [review]
LGTM, thanks! A couple of comments

File: compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp (hunk 2 above)
Comment (hanhanW) [reply compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp]: I followed upstream convention, but I agreed that `DimOrder` looks better. updated!
