### PR TITLE
Preserve unsigned integer inputs/outputs

### LINKED ISSUE #9282: Unsigned integer outputs become signed
Repro:
```
import platform
import iree.compiler
import iree.runtime
import numpy as np

CODE = """
#loc0 = loc(unknown)
module @jit_prim_fun.0 {
  func.func public @main(%arg0: tensor<5x7xui32> loc(unknown)) -> tensor<5x7xui32> {
    %0 = "mhlo.sort"(%arg0) ({
    ^bb0(%arg1: tensor<ui32> loc(unknown), %arg2: tensor<ui32> loc(unknown)):
      %1 = "mhlo.compare"(%arg1, %arg2) {compare_type = #mhlo<"comparison_type UNSIGNED">, comparison_direction = #mhlo<"comparison_direction LT">} : (tensor<ui32>, tensor<ui32>) -> tensor<i1> loc(#loc2)
      "mhlo.return"(%1) : (tensor<i1>) -> () loc(#loc1)
    }) {dimension = 1 : i64, is_stable = false} : (tensor<5x7xui32>) -> tensor<5x7xui32> loc(#loc1)
    return %0 : tensor<5x7xui32> loc(#loc0)
  } loc(#loc0)
} loc(#loc0)
#loc1 = loc("jit(sort)/jit(main)/sort[dimension=1 is_stable=False num_keys=1]"("/Users/phawkins/p/jax/tests/lax_test.py":2039:1))
#loc2 = loc("jit(sort)/jit(main)/lt"("/Users/phawkins/p/jax/tests/lax_test.py":2039:1))
"""

# Work around https://github.com/google/iree/issues/9028
extra_args = []
if platform.system() == "Darwin" and platform.machine() == "arm64":
  extra_args += ["--iree-llvm-target-triple=arm64-apple-darwin21.5.0"]

iree_config = iree.runtime.system_api.Config("dylib")
iree_binary = iree.compiler.compile_str(
    CODE, target_backends=["dylib"], input_type="mhlo", extra_args=extra_args)
vm_module = iree.runtime.VmModule.from_flatbuffer(iree_binary)
module_object = iree.runtime.load_vm_module(vm_module, iree_config)

out = module_object["main"](np.ones((5, 7), dtype=np.uint32))
assert out.dtype == np.uint32, out.dtype
```

Get:
```
Traceback (most recent call last):
  File "/Users/phawkins/p/jax/t.py", line 34, in <module>
    assert out.dtype == np.uint32, out.dtype
AssertionError: int32
```

The MHLO has a ui32 output, so I expect a uint32 result from IREE.

### LINKED ISSUE #12665: JAX: Preserve unsigned return type information for return types
Compiled models return signless tensors from execution. We need to preserve the check that the element type is unsigned when necessary. Likely this means including an ABI change.

E.g. Jax integration test below produces a tensor with the correct contents but is assumed to be signed integers when it should be unsigned:

`JAX_PLATFORMS=iree_cpu pytest jax/tests/lax_numpy_operators_test.py::JaxNumpyOperatorTests::testBitwiseOp8`

### PR DESCRIPTION
**Pull request by trevor-m**
Thanks so much to @rsuderman for the guidance and help !

This PR solves a bug where the signedness of inputs and outputs is lost, because lowering to linalg dialect throws the signedness away. To fix it, I'm using a new op `tensor.bitcast`, which casts the inputs/outputs of the function from an unsigned type to the signless type in the body.

I am completely new to IREE, so this PR is still a little rough. Any critique and suggestions for improvement is highly welcome. I'm particularly interested in ways to make this more robust.

Fixes #9282
Fixes #12665

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
Skimmed through this (I can review more if it doesnt get reviewed). This seems fine to me. Thanks!

**Review by benvanik — CHANGES_REQUESTED** [review]
This has a layering violation (we can't be making the generic util dialect depend on the stream dialect). I'll need to parse through this. I feel like a tensor.bitcast would be a much better way of accomplishing this and usable from many other frontend dialects for various purposes (specifically, this has been requested for custom imports that may take tensors of various types).

File: compiler/src/iree/compiler/Dialect/Util/IR/UtilOps.cpp [hunk 1]
```diff
@@ -1372,6 +1372,13 @@ void BufferStoreOp::setSubrangeOperand(unsigned operandIndex,
   getLengthMutable().assign(operand.length);
 }
 
+bool ReinterpretOp::areCastCompatible(TypeRange inputs, TypeRange outputs) {
+  if (inputs.size() != 1 || outputs.size() != 1)
+    return false;
+  // TODO(trevor-m): Improve this.
```
Comment (benvanik) [inline compiler/src/iree/compiler/Dialect/Util/IR/UtilOps.cpp]: this is a really dangerous op and we will need more checks on this - I'm not comfortable with the amount of errors this could lead to lower in the stack if we allow any -> any.

**Review by benvanik — CHANGES_REQUESTED** [review]
Yeah, I don't think we can take this as-is :/

The util dialect is a general purpose dialect used throughout all IREE transformation stages and adding ops to it implies that they are expected to function at those layers of the stack (not all do, but it's at least the goal). This op when misused will break nearly all of the analysis and optimizations we have in flow/stream. For example, copy-on-write, scheduling, and allocation won't know how to handle these. There are some cases where a reinterpret cast is useful but they should almost always be footguns that are reached for when nothing else will suffice, and in this case there are other choices we should explore first. I understand that unrealized_conversion_cast is _also_ a major footgun but I think this is just renaming the footgun instead of making it better - I'd rather have unrealized_conversion_cast than a new op we have to handle.

I think scoping the problem more to what you actually want to do (bitcast between two tensor element types) would make it safer and allow us to verify that it is properly eliminated prior to lowering further down in the stack from the ABI level. I feel like upstreaming a tensor.bitcast (effectively tensor.cast but without the requirement that the element types match, which is silly to me and maybe could be relaxed with upstream discussion) would be the best solution and if upstream doesn't want that then I'd say we should delete the entire tensor dialect as what is even the point :)

Is the primary motivation here not to have the unrealized_conversion_cast spelled like that? WrapEntryPoints should kick in far before the stream dialect and capture the type as defined on the func.func, like here where we take the type directly from the function signature: https://github.com/openxla/iree/blob/186cdd4b7abf9be5de0cd6a5e2dde273edc226d1/compiler/src/iree/compiler/Bindings/Native/Transforms/WrapEntryPoints.cpp#L418-L420

If there's a bug/that is pulling from the wrong source we should be able to fix that. I'd much prefer us find a way to make that level of the stack happy where we emit the hal.tensor.import/hal.tensor.export ops than trying to preserve this through several of the layers where it's dangerous.

Another option is to add a `flow.tensor.bitcast`, but I believe a `tensor.bitcast` may be able to accomplish what's needed. Worst case we add that op and ensure it is elided by the time we lower into the stream dialect.

**Comment by MaheshRavishankar** [comment]
> This has a layering violation (we can't be making the generic util dialect depend on the stream dialect). I'll need to parse through this. I feel like a tensor.bitcast would be a much better way of accomplishing this and usable from many other frontend dialects for various purposes (specifically, this has been requested for custom imports that may take tensors of various types).

Ah missed that. Thanks for catching that.

**Comment by trevor-m** [comment]
Thanks @benvanik for taking a look!

> Yeah, I don't think we can take this as-is :/
> 
> The util dialect is a general purpose dialect used throughout all IREE transformation stages and adding ops to it implies that they are expected to function at those layers of the stack (not all do, but it's at least the goal). This op when misused will break nearly all of the analysis and optimizations we have in flow/stream. For example, copy-on-write, scheduling, and allocation won't know how to handle these. There are some cases where a reinterpret cast is useful but they should almost always be footguns that are reached for when nothing else will suffice, and in this case there are other choices we should explore first. I understand that unrealized_conversion_cast is _also_ a major footgun but I think this is just renaming the footgun instead of making it better - I'd rather have unrealized_conversion_cast than a new op we have to handle.
> 
> I think scoping the problem more to what you actually want to do (bitcast between two tensor element types) would make it safer and allow us to verify that it is properly eliminated prior to lowering further down in the stack from the ABI level. I feel like upstreaming a tensor.bitcast (effectively tensor.cast but without the requirement that the element types match, which is silly to me and maybe could be relaxed with upstream discussion) would be the best solution and if upstream doesn't want that then I'd say we should delete the entire tensor dialect as what is even the point :)

Yes, `tensor.bitcast` would be perfect. The intention of `util.reinterpret` was to basically be a proxy for that since it doesn't exist yet. I didn't mean for the op to actually be Any -> Any, and I was hoping for feedback on how to properly restrict it.


> Is the primary motivation here not to have the unrealized_conversion_cast spelled like that? WrapEntryPoints should kick in far before the stream dialect and capture the type as defined on the func.func, like here where we take the type directly from the function signature:
> 
> https://github.com/openxla/iree/blob/186cdd4b7abf9be5de0cd6a5e2dde273edc226d1/compiler/src/iree/compiler/Bindings/Native/Transforms/WrapEntryPoints.cpp#L418-L420
> 
> If there's a bug/that is pulling from the wrong source we should be able to fix that. I'd much prefer us find a way to make that level of the stack happy where we emit the hal.tensor.import/hal.tensor.export ops than trying to preserve this through several of the layers where it's dangerous.

The `ConvertMHLOToLinalgOnTensors` pass converts all integers to signless, and that runs before `WrapEntryPoints`. Could we just move `WrapEntryPoints` before converting to linalg?

**Comment by rsuderman** [comment]
@benvanik `tensor.bitcast` feels like exactly what the intention of `util.reinterpret` is, so if upstreaming to the `tensor` dialect seems feasible, we should do that. Validation should be that the byte behavior would be the same. E.g. `complex<f32>` would be equivalent `2xf32`, etc. Most of the issue just stems from `mlir` having no way to cast between `i32`, `si32` and `ui32`.

Lets look into upstreaming the components relate to `tensor.bitcast` and then we can merge on top of this one.

**Comment by trevor-m** [comment]
Submitted LLVM patch for `tensor.bitcast`: https://reviews.llvm.org/D149608

**Comment by trevor-m** [comment]
@benvanik @rsuderman @MaheshRavishankar Thanks again for all of the suggestions! `tensor.bitcast` is in and this PR is ready for re-review.

I am wondering if there is an easier/cleaner way to remove the bitcast ops as we are lowering to stream dialect, rather than having to make the RemoveBitcast matchAndRewrite.

**Comment by benvanik** [comment]
I think we need to handle them like we do the other flow ops like flow.tensor.reshape - that means we'll want a flow.tensor.bitcast and then a pattern like https://github.com/iree-org/iree/blob/8f387c65f556495a4b3537161dea018f82e7ae81/compiler/src/iree/compiler/Dialect/Stream/Conversion/FlowToStream/Patterns.cpp#L48-L68 matching it.

This is because by the end of the flow dialect (before we lower into stream) we want to have all tensor shapes fully captured and no tensor dialect ops remaining (this is why there are no existing tensor->stream conversions - it's expected they've all been done already). 

If you'd like I can hack that together real quick now that tensor.bitcast is upstream and then your PR here can just add the mhlo portion. WDYT?

**Comment by benvanik** [comment]
(since I have some time between meetings I'm going to plow ahead ~~with flow.tensor.bitcast~~ and send that out)

update: forgot that flow.tensor.reshape can do what bitcast does already (and cast) - I'll just convert to that and the rest should happen automatically

**Comment by trevor-m** [comment]
> (since I have some time between meetings I'm going to plow ahead ~with flow.tensor.bitcast~ and send that out)
> 
> update: forgot that flow.tensor.reshape can do what bitcast does already (and cast) - I'll just convert to that and the rest should happen automatically

Thanks Ben, that would be awesome!

**Comment by benvanik** [comment]
Added in #13538 - there may still be issues hiding lower down but with your changes we can hopefully get some inputs that highlight them!

**Comment by trevor-m** [comment]
> Added in #13538 - there may still be issues hiding lower down but with your changes we can hopefully get some inputs that highlight them!

Thanks Ben for helping with that!
I've fixed the remaining tests that were failing.  Could you take another pass at my changes?

**Review by benvanik — APPROVED** [review]
looks great!
