### PR TITLE
Skipping generic from root op when it computes slice indices

### LINKED ISSUE #19746: [Codegen] Failure compiling scatter with fused indices
### What happened?

Running into codegen issues after enabling scatter fusion. `GPUFuseAndHoistParallelLoopsPass` seems is causing the failure ([IR after failure](https://gist.github.com/IanWood1/5adc98c9ec3bd7f4c659fbe210d20086))

### Steps to reproduce your issue

1. Download the dispatch https://gist.github.com/IanWood1/d62452d2a2940784ff6ada711483c981
2. Run with `iree-compile`

### What component(s) does this issue relate to?

_No response_

### Version information

6052a1d14ca2c6c28c3679cff27430ce2b51c96f + https://github.com/iree-org/iree/pull/19704

The PR makes changes to scatter to allow dropping the unit dim in `indices`. It changes the verifier + interfaces so its required to compile the repro.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jerryyin**
This PR prevents the linalg.generic to become root op when it is used to compute slice indices. This PR fix https://github.com/iree-org/iree/issues/19746. @IanWood1 has help confirmed this will not cause performance degradation compared with another alternative: having scatter op take precedence over generics.

I'd like to thank @qedawkins for providing mentorship to this PR.

### CODE REVIEW

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 1]
```diff
@@ -2529,12 +2533,32 @@ LogicalResult initGPULaunchConfig(FunctionOpInterface funcOp) {
...
+      if (auto genericOp =
+              dyn_cast<linalg::GenericOp>(indices.getDefiningOp())) {
+        genericToSkip.insert(genericOp);
+      }
+      // If scatter's backward slices are generic ops, mark them as to skip too.
+      SetVector<Operation *> slices;
+      getBackwardSlice(indices, &slices);
+      for (auto slice : slices) {
+        if (isa<linalg::GenericOp>(slice)) {
+          genericToSkip.insert(slice);
```
Comment (qedawkins) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp]: We don't have to filter out generics, we can just add the `slice` directly to `genericToSkip` and make it a set of all operations used in defining the indices of the scatter.

**Review by qedawkins — CHANGES_REQUESTED** [review]
Thanks, just one comment on how to construct the set of ops to skip.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp (hunk 1 above)
Comment (jerryyin) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp]: Sounds reasonable

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 2]
```diff
@@ -2529,12 +2533,28 @@ LogicalResult initGPULaunchConfig(FunctionOpInterface funcOp) {
         break;
       }
     }
+
+    if (auto scatterOp = dyn_cast<IREE::LinalgExt::ScatterOp>(op)) {
+      auto indices = scatterOp.getIndices();
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp]: Do not use `auto` here, the type is not obvious based on the context: https://llvm.org/docs/CodingStandards.html#use-auto-type-deduction-to-make-code-more-readable

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 3]
```diff
@@ -2529,12 +2533,28 @@ LogicalResult initGPULaunchConfig(FunctionOpInterface funcOp) {
...
+      if (indices.getDefiningOp() == nullptr) {
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp]: nit: llvm prefers casts to bool over explicit comparisons with nullptr unless we are dealing with custom nullable types or double-nullable types like `optional<Value>` etc.
```suggestion
      if (!indices.getDefiningOp()) {
```

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 4]
```diff
@@ -2529,12 +2533,28 @@ LogicalResult initGPULaunchConfig(FunctionOpInterface funcOp) {
...
+      }
+      // If scatter's indices is a generic op, mark it as to skip.
+      if (auto genericOp =
+              dyn_cast<linalg::GenericOp>(indices.getDefiningOp())) {
+        genericToSkip.insert(genericOp);
+      }
+      // Mark scatter's backward slices as to skip too.
+      SetVector<Operation *> slices;
+      getBackwardSlice(indices, &slices);
+      genericToSkip.insert(slices.begin(), slices.end());
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2548]: nit: you can use `append_range`
```suggestion
      llvm::append_range(genericToSkip, slices);
```

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 5]
```diff
@@ -2529,12 +2533,28 @@ LogicalResult initGPULaunchConfig(FunctionOpInterface funcOp) {
...
+    }
   }
 
   // Generic ops take priority over scatter and fill ops as the root op.
   if (!rootOperation) {
     for (Operation *op : llvm::reverse(computeOps)) {
-      if (isa<linalg::GenericOp>(op)) {
+      if (isa<linalg::GenericOp>(op) && genericToSkip.count(op) == 0) {
```
Comment (kuhar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp]: Use `.contains(op)`

**Review by kuhar — COMMENTED** [review]
Just some drive-by coding style nits

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp (hunk 4 above)
Comment (jerryyin) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2548]: I just gave it a shot, as it turns out `llvm::append_range` is not compatible with `llvm::SmallDenseSet`.

```cpp
template <typename Container, typename Range>
void append_range(Container &C, Range &&R) {
  C.insert(C.end(), adl_begin(R), adl_end(R));
}
```

`append_range` expects the container to support `insert` with 3 iterators. Clang complained that it can't find matching function and can only find insert with 1 or 2 arguments:
```
candidate function template not viable: requires 2 arguments, but 3 were provided
    template <typename InputIt> void insert(InputIt I, InputIt E) {
/root/iree/third_party/llvm-project/llvm/include/llvm/ADT/DenseSet.h:213:29: note: candidate function not viable: requires single argument 'V', but 3 arguments were provided
    std::pair<iterator, bool> insert(const ValueT &V) {
/root/iree/third_party/llvm-project/llvm/include/llvm/ADT/DenseSet.h:218:29: note: candidate function not viable: requires single argument 'V', but 3 arguments were provided
   std::pair<iterator, bool> insert(ValueT &&V) {
```

Nice intro to some handy utilities though!

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp (hunk 3 above)
Comment (jerryyin) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp]: Thanks for the background

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp (hunk 2 above)
Comment (jerryyin) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp]: Sounds reasonable.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 6]
```diff
@@ -2529,12 +2533,28 @@ LogicalResult initGPULaunchConfig(FunctionOpInterface funcOp) {
...
+    if (auto scatterOp = dyn_cast<IREE::LinalgExt::ScatterOp>(op)) {
+      Value indices = scatterOp.getIndices();
+      if (!indices.getDefiningOp()) {
+        continue;
+      }
+      // If scatter's indices is a generic op, mark it as to skip.
+      if (auto genericOp =
+              dyn_cast<linalg::GenericOp>(indices.getDefiningOp())) {
+        genericToSkip.insert(genericOp);
+      }
```
Comment (qedawkins) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp]: You can add
```
  BackwardSliceOptions options;
  options.inclusive = true;
```
to `getBackwardSlice` so that you don't need to add the generics here and it will include them in the program slice.

**Review by qedawkins — APPROVED** [review]

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp [hunk 7]
```diff
@@ -2529,12 +2533,28 @@ LogicalResult initGPULaunchConfig(FunctionOpInterface funcOp) {
         break;
       }
     }
+
```
Comment (MaheshRavishankar) [inline compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2536]: There is a slightly better solution here (at least IMO). 
Similar to 
```
 if (!rootOperation) {
    for (Operation *op : llvm::reverse(computeOps)) {
      if (isa<linalg::GenericOp>(op) && !genericToSkip.contains(op)) {
        rootOperation = op;
        break;
      }
    }
  }
```
below, before that you could do

```
 if (!rootOperation) {
    for (Operation *op : llvm::reverse(computeOps)) {
      if (isa<IREE::LinalgExt::ScatterOp>(op)) {
        rootOperation = op;
        break;
      }
    }
  }
```

Should give you the same answer.

Comment (jerryyin) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2536]: This is the first attempt we experimented. @qedawkins asked about the changing the precedence before we come up with this PR. I can confirm this indeed fixed the problem for the case in #19746. But then upon @IanWood1's experiment on verifying the perf, and quote: "on 8b fp16, the perf dropped from 80ms to 120ms". It looks like changing the priority of scatter/generic op can change the root op, resulting in a different tiling strategy to degrade the performance somehow.

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp (hunk 6 above)
Comment (jerryyin) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp]: Good point, thanks for the suggestion!

File: compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp (hunk 7 above)
Comment (IanWood1) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2536]: I don't see what would cause the difference. Its possible that I messed something up while checking. I was juggling several commits to get llama to fuse correctly and generally 8b gives times around ~43.5 ms. So maybe it was something unrelated?

Also, I'm using https://github.com/iree-org/iree/pull/19775 to track all the scatter related fusion changes.

Comment (qedawkins) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2536]: The difference is that this suggestion would prioritize setting the lowering config on the scatter instead of the producer of `updates`. It's not implausible that the config we get from the producer is better than what gets fused with the generic. Also the config setting logic could use improvement too.

Comment (IanWood1) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2536]: Okay thank you. Just for further context 1/2 of the dispatches are like https://gist.github.com/IanWood1/5b0b0d73f0d76dabd7669b714f066b3c ("rope "+ indices fused) and the other half are similar to the one in the original issue (only `indices` fused)

Comment (jerryyin) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2536]: What would justify us to altering the precedence here? For the scope of this ticket, we can go with either. If by experience, y'all think having scatter getting the lowering config is better, I can just push another commit. Or else let me know what benchmark needs to run.

Comment (qedawkins) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2536]: I don't think either option is always better, but I would guess that *most* of the time setting the lowering config on the producer is better. The reason being that the scatter doesn't provide much information for how best to compile the dispatch, just the shape of the inner slice that is vectorizable. Conversely, a producer could be a transpose, bitextend or truncate, or something else that would meaningfully affect the lowering config.

Comment (jerryyin) [reply compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp:2536]: I'm going to mark this as resolved as the comments are converging. I'll be waiting till next morning to land this PR in case more comments are to come in.
